(async function(){
'use strict';
const D=EnergyData,C=EnergyCore,E=EnergyEditor,$=id=>document.getElementById(id),key='sjs-energy-enthalpy-v2';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const B=globalThis.TestModeBridge,test=(await B?.connect())||null;
const P=MastersProgress,settings=IGCSEMasteryConfig.activities['energy-enthalpy'];
const reviewBank=QuestionReview.bank('EE',D.questions),params=new URLSearchParams(location.search);
let results=[],state=C.fresh(),q,editor,hinted=false,revealed=false,storageOK=true,marked=null,completedAt=null;
if(!test){try{results=P.read(localStorage);}catch{}try{state=C.load(localStorage.getItem(key),D);}catch{storageOK=false;}}
const requestedGrade=Number(test?.level||params.get('grade'));
if((test||params.get('practice')==='grade')&&[1,2].includes(requestedGrade))state.filter='grade'+requestedGrade;else if(params.get('practice')==='mastery')state.filter='mixed';
function hash(value){let n=2166136261;for(const char of String(value)){n^=char.charCodeAt(0);n=Math.imul(n,16777619);}return n>>>0;}
function testQuestion(snapshot){const restored=D.questions.find(item=>item.id===snapshot?.questionId&&item.grade===requestedGrade);if(restored)return restored;let pool=D.questions.filter(item=>item.grade===requestedGrade),previousId=test?.previous?.questionId;if(pool.length>1&&previousId)pool=pool.filter(item=>item.id!==previousId);return pool[hash(test?.attemptId)%pool.length];}
function answers(){return(q?.fields||[]).map((field,index)=>$('answer-'+index)?.value||'');}
function snapshot(){return q?{version:1,questionId:q.id,grade:q.grade,answers:answers(),editor:q.kind?editor?.value()||null:null,hinted,revealed,marked,completedAt}:null;}
function saveTest(){if(test&&q)return B.save(snapshot());}
function save(){if(test){saveTest();return;}try{localStorage.setItem(key,JSON.stringify(state));}catch{storageOK=false;}$('saveStatus').textContent=storageOK?'Progress stays in this browser.':'Storage unavailable: progress lasts for this visit.';}
function progress(){if(test)return;$('quickMode').value=state.filter;const achievement=P.achievement(results,settings.leafId);$('strands').innerHTML=D.strands.map(g=>{const rows=results.filter(r=>r.leafId===settings.leafId&&r.strand===g.id),score=P.weightedScore(rows.map(r=>r.score),settings.halfLives[g.grade]);return `<button class="mode" data-strand="${g.id}" aria-pressed="${state.filter===g.id}">${g.name}<span>${P.bands[g.grade]}</span>${P.masteryBar(score,g.name+' mastery',g.grade).outerHTML}</button>`;}).join('');$('total').textContent=`${achievement.achievedGrade} / 2 levels`;$('mixed').setAttribute('aria-pressed',state.filter==='mixed');$('session').innerHTML=[1,2].map(grade=>{const p=P.summarise(results,settings.leafId,grade);return `<span>${P.bands[grade]}</span>${P.masteryBar(p.score,P.bands[grade]+' mastery',grade).outerHTML}`;}).join('')+'<span>Grade 9 unavailable</span>';}
function loadReview(id){if(!test)start(reviewBank.get(id));}
function renderMarked(result,independent){const pass=result.every(Boolean)&&independent;$('check').disabled=true;$('hint').disabled=true;$('giveUp').hidden=true;$('error').textContent='';$('written').querySelectorAll('input').forEach((input,index)=>{input.disabled=true;input.setAttribute('aria-invalid',String(!result[index]));$('note-'+index).textContent=result[index]?'Correct.':'Expected: '+q.fields[index].accept[0];});$('written').querySelectorAll('.answer-option').forEach(button=>{button.disabled=true;});$('written').querySelectorAll('.choice-field').forEach(field=>field.setAttribute('aria-invalid',String(!result[Number(field.id.slice(6))])));if(editor)editor.lock();$('feedback').innerHTML=`<h3>${result.filter(Boolean).length} / ${result.length} marks</h3><ul class="mark-list">${q.points.map((point,index)=>`<li class="${result[index]?'pass':'fail'}">${result[index]?'✓':'Review:'} ${esc(point)}</li>`).join('')}</ul><p>${esc(q.feedback)}</p><p class="${pass?'pass':'fail'}">${independent?(pass?'All marking points met.':'Review the feedback, then try a fresh question.'):'Recorded as practice; a fresh unhinted answer is needed for mastery.'}</p>`;$('feedback').hidden=false;$('next').hidden=false;$('next').focus({preventScroll:true});}
async function emitResult(){if(!test||!marked||!completedAt)return;const score=P.questionScore(marked),independent=!hinted;await B.result({score,independent,completedAt,evidence:independent?{score,questionId:q.id,grade:q.grade,marks:marked,total:marked.length}:null});}
async function start(supplied,restore=test?.state){
 if(editor){editor.destroy();editor=null;}q=test?testQuestion(restore):(supplied?.id?supplied:C.next(state,D,q?.id));hinted=!!restore?.hinted;revealed=!!restore?.revealed;marked=Array.isArray(restore?.marked)?restore.marked:null;completedAt=Number(restore?.completedAt)||null;
 $('prompt').textContent=q.prompt;$('prompt').dataset.question=q.id;$('equation').textContent=q.equation||'';$('equation').hidden=!q.equation;$('enthalpy').textContent=q.enthalpyText||'';$('enthalpy').hidden=!q.enthalpyText;$('strandName').textContent=D.strands.find(g=>g.id===q.strand).name+' · '+P.bands[q.grade];
 const choices=q.fields?.some(f=>f.options),typed=q.fields?.some(f=>!f.options);$('format').textContent=`${q.points.length} ${q.points.length===1?'mark':'marks'} · ${q.kind?'Editable diagram':choices?(typed?'Short answers and choices':'Choose answers'):'Short answer'}`;$('instruction').textContent=q.kind?'':choices?(typed?'Choose the buttons and fill in the remaining gaps.':'Choose one button for each answer.'):'Fill in each gap with a short answer.';$('instruction').hidden=!!q.kind;$('diagram').innerHTML=q.diagram?E.reference(q.diagram):'';$('builder').replaceChildren();
 $('written').innerHTML=(q.fields||[]).map((field,index)=>field.options?`<fieldset class="answer-field choice-field" id="field-${index}" aria-describedby="note-${index}"><legend>${esc(field.label)}</legend><input type="hidden" id="answer-${index}" value=""><div class="answer-options">${field.options.map(option=>`<button type="button" class="answer-option" data-field="${index}" data-value="${esc(option)}" aria-pressed="false">${esc(option.charAt(0).toUpperCase()+option.slice(1))}</button>`).join('')}</div><p id="note-${index}" class="field-note small"></p></fieldset>`:`<div class="answer-field"><label for="answer-${index}">${esc(field.label)}</label><input id="answer-${index}" class="answer-input" autocomplete="off" spellcheck="false" maxlength="180" aria-describedby="note-${index}"><p id="note-${index}" class="field-note small"></p></div>`).join('');
 if(q.kind){const child=document.createElement('div');$('builder').append(child);editor=E.mount(child,q,$('diagramTools'),restore?.editor);}(restore?.answers||[]).forEach((value,index)=>{const input=$('answer-'+index);if(!input)return;input.value=value;if(q.fields[index]?.options)$('field-'+index).querySelectorAll('.answer-option').forEach(option=>option.setAttribute('aria-pressed',String(option.dataset.value===value)));});
$('feedback').hidden=true;$('feedback').replaceChildren();$('next').hidden=true;$('hintText').hidden=!hinted;$('hintText').textContent=hinted?D.hints[q.strand]+' This question will count as practice.':'';$('error').textContent='';$('check').disabled=false;$('hint').disabled=false;$('giveUp').hidden=true;QuestionReview.mount($('prompt').parentElement,reviewBank.id(q),test ? null : loadReview);progress();save();if(revealed&&marked){renderMarked(marked,!hinted);await emitResult();}
}
async function mark(force=false){
 if(revealed)return;let result;if(q.fields){const values=q.fields.map((field,index)=>$('answer-'+index).value),states=q.fields.map((field,index)=>C.markField(field,values[index],D));if(!force&&states.some(value=>value==='empty'||value==='unknown')){states.forEach((value,index)=>{$('note-'+index).textContent=value==='empty'?(q.fields[index].options?'Choose an answer, or choose “Show answer”.':'Enter an answer, or choose “Show answer”.'):value==='unknown'?'Not recognized. Use just the requested word or phrase, or ask your teacher.':'';});$('error').textContent='Check the highlighted fields. Your answers are preserved; no attempt has been recorded.';$('giveUp').hidden=false;saveTest();return;}result=states.map(value=>value==='correct');}else result=C.check(q,editor.value(),D);
 revealed=true;hinted=hinted||force;marked=result;completedAt=Date.now();if(!test){const pass=result.every(Boolean)&&!force;C.record(state,q,pass,hinted);if(!hinted&&ChemistryMode.get()!=='teacher'){const item={id:'energy-'+completedAt+'-'+Math.random().toString(36).slice(2),leafId:settings.leafId,grade:q.grade,strand:q.strand,score:P.questionScore(result),completedAt};try{results=P.merge(results,P.read(localStorage));results=P.append(results,item);localStorage.setItem(P.key,JSON.stringify(results));}catch{storageOK=false;results=P.append(results,item);}}save();progress();}renderMarked(result,!hinted);if(test){await B.save(snapshot());await emitResult();}
}
function filter(value){if(test)return;state.filter=value;start();$('prompt').focus();}
$('strands').onclick=event=>{const button=event.target.closest('[data-strand]');if(button)filter(button.dataset.strand);};$('mixed').onclick=()=>filter('mixed');$('check').onclick=()=>mark();$('giveUp').onclick=()=>mark(true);$('hint').onclick=()=>{hinted=true;$('hintText').textContent=D.hints[q.strand]+' This question will count as practice.';$('hintText').hidden=false;saveTest();};
$('written').addEventListener('click',event=>{const button=event.target.closest('.answer-option');if(!button||revealed)return;const index=button.dataset.field;$('answer-'+index).value=button.dataset.value;$('field-'+index).querySelectorAll('.answer-option').forEach(option=>option.setAttribute('aria-pressed',String(option===button)));$('note-'+index).textContent='';saveTest();});$('written').addEventListener('input',()=>saveTest());$('builder').addEventListener('input',()=>saveTest());$('builder').addEventListener('change',()=>saveTest());$('builder').addEventListener('keyup',()=>saveTest());$('diagramTools').addEventListener('click',()=>setTimeout(saveTest,0));$('diagramTools').addEventListener('keyup',()=>setTimeout(saveTest,0));window.addEventListener('pointerup',()=>setTimeout(saveTest,0));
$('written').addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target.matches('input:not([type=hidden])')){event.preventDefault();mark();}});document.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.repeat&&revealed&&!event.isComposing&&!$('resetDialog').open&&document.querySelector('.workspace').contains(event.target)){event.preventDefault();event.stopPropagation();if(test)B.next();else{start();$('prompt').focus();}}},true);
$('next').onclick=()=>{if(test)B.next();else{start();$('prompt').focus();}};$('reset').onclick=()=>{if(!test)$('resetDialog').showModal();};$('resetDialog').addEventListener('close',()=>{if(!test&&$('resetDialog').returnValue==='reset'){state=C.fresh();try{results=P.merge(results,P.read(localStorage)).filter(row=>row.leafId!==settings.leafId);localStorage.setItem(P.key,JSON.stringify(results));}catch{results=results.filter(row=>row.leafId!==settings.leafId);storageOK=false;}start();$('prompt').focus();}});
$('quickMode').insertAdjacentHTML('beforeend',[1,2].map(grade=>`<option value="grade${grade}">${P.bands[grade]}</option>`).join('')+D.strands.map(group=>`<option value="${group.id}">${esc(group.name)} · ${P.bands[group.grade]}</option>`).join(''));$('quickMode').onchange=event=>filter(event.target.value);if(test){$('reset').disabled=true;$('mixed').disabled=true;$('quickMode').disabled=true;}await start();if(!test)QuestionReview.requested(loadReview);
})();
