import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {server,project} from './server.mjs';
const require=createRequire(path.join(project,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');const {chromium}=require('playwright');
const here=import.meta.dirname,temp=path.join(here,'.browser');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const host=server();await new Promise(r=>host.listen(5201,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${temp}/cache`]}),report={startedAt:new Date().toISOString(),browser:await browser.version(),playwright:'1.62.1',checks:[],failures:[]};
async function rows(page,course,table){return page.evaluate(async({course,table})=>{const db=await new Promise((r,j)=>{const q=indexedDB.open(`masters-of-chemistry-${course}-local`);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});try{return await new Promise((r,j)=>{const q=db.transaction(table).objectStore(table).getAll();q.onsuccess=()=>r(q.result.map(x=>x.value));q.onerror=()=>j(q.error);})}finally{db.close()}},{course,table});}
async function run(id,fn){try{const detail=await fn();report.checks.push({id,status:'PASS',...detail});console.log('PASS '+id)}catch(e){report.failures.push({id,status:'FAIL',error:e.stack});console.log('FAIL '+id+' '+e.message)}}
const contexts=[];
try{
 for(const course of ['alevel','igcse']){
 const context=await browser.newContext({acceptDownloads:true});contexts.push(context);await context.addInitScript(()=>{window.oldWrites=[];const s=Storage.prototype.setItem,r=Storage.prototype.removeItem,c=Storage.prototype.clear;Storage.prototype.setItem=function(k,v){window.oldWrites.push(['set',k]);return s.call(this,k,v)};Storage.prototype.removeItem=function(k){window.oldWrites.push(['remove',k]);return r.call(this,k)};Storage.prototype.clear=function(){window.oldWrites.push(['clear']);return c.call(this)};});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=`http://127.0.0.1:5201/stage-s5/${course}/index.html`;
 await run(course+'-all-targets-practice-revision',async()=>{
 await page.goto(url);await page.getByRole('button',{name:'Start practice',exact:true}).waitFor();
 const targets=await page.getByLabel('Target',{exact:true}).locator('option').evaluateAll(es=>es.map(e=>({key:e.value,label:e.textContent})));
 const visited=[];
 for(const t of targets){
  await page.getByLabel('Target',{exact:true}).selectOption(t.key);await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.locator('.question-player').waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();
  let a=(await rows(page,course,'attempts')).at(-1);const sessions=await rows(page,course,'sessions');a=(await rows(page,course,'attempts')).find(a=>a.attemptId===sessions[0].currentAttemptId);
  assert.equal(a.target.gemId+':'+a.target.level,t.key);assert.equal(a.phase,'answering');assert.equal(await page.evaluate(()=>window.__mastersActivity),undefined);
  await page.getByRole('button',{name:'Reveal answer (assisted)',exact:true}).click();await page.locator('.assessment-feedback').waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();assert.equal((await rows(page,course,'evidence')).length,0);
  await page.getByRole('button',{name:'Change activity or view',exact:true}).click();visited.push({key:t.key,ref:a.ref,idleLimitMs:a.timing.idleLimitMs});
 }
 await page.getByLabel('Session',{exact:true}).selectOption('revision');const buttons=page.getByRole('button',{name:/^ADD ALL /});for(let i=0;i<await buttons.count();i++){await buttons.nth(i).click();await buttons.nth(i).click()};assert((await page.getByTestId('selected-count').innerText()).startsWith(String(targets.length)+' '));await page.getByRole('button',{name:'Start revision',exact:true}).click();await page.locator('.question-player').waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();const base=(await rows(page,course,'sessions'))[0];assert.equal(base.levels.length,targets.length);assert(!base.selectedGemIds.some(x=>/c3|rocket/.test(x)));await page.getByRole('button',{name:'Pause and save',exact:true}).click();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();
 // Each controlled valid session retains all selected levels and explicitly binds a current target.
 // This exercises production restore/assessment on every supported target, independently of ADD ALL's initial target.
 const revision=[];
 for(let i=0;i<visited.length;i++){
  const v=visited[i],target=base.levels.find(x=>x.target.gemId+':'+x.target.level===v.key).target,id='s5-revision-'+course+'-'+i;
  await page.evaluate(async({base,target,v,id,course})=>{const {createChemistryRepository}=await import('/src/persistence/repository.ts');const r=createChemistryRepository(`masters-of-chemistry-${course}-local`);const a={mode:'student',namespace:{course,profileId:'local'},attemptId:id,ref:v.ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:v.idleLimitMs,finished:false}};const s={...base,status:'paused',current:{attemptId:id,target,ref:v.ref,completed:false},submittedAttemptIds:[]};const result=await r.saveCurriculum({attempt:a,session:s});if(!result.ok)throw Error(JSON.stringify(result));},{base,target,v,id,course});
  await page.goto(url+'?view=revision');await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await page.locator('.question-player').waitFor();assert.equal(await page.locator('.question-meta code').innerText(),v.ref.questionId);await page.getByRole('button',{name:'Reveal answer (assisted)',exact:true}).click();await page.locator('.assessment-feedback').waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();const s=(await rows(page,course,'sessions'))[0];assert(s.submittedAttemptIds.includes(id));assert(s.current.completed);assert.equal((await rows(page,course,'evidence')).length,0);revision.push(v.key);
 }
 await page.screenshot({path:path.join(here,course+'-revision-final.png'),fullPage:true});return{practice:visited,revisionTargets:revision,addAllSelected:base.levels.length,zeroAssistedEvidence:true};
 });
 await run(course+'-aliases-direct-refresh',async()=>{
 const all=report.checks.find(c=>c.id===course+'-all-targets-practice-revision').practice,slugs=course==='alevel'?['acid-base-calculations','electrons-bonding','electron-configurations','dot-and-cross','ph-titration-curves','c3l6-organic-reactions']:['calorimetry','bond-enthalpy','structure-and-bonding','dot-and-cross','energy-enthalpy','energetics-practical'];const tested=[];
 for(const slug of slugs){const alias=`http://127.0.0.1:5201/stage-s5/${course}/activities/${slug}/index.html`;await page.goto(alias);await page.getByRole('heading',{name:slug==='c3l6-organic-reactions'?/C3|Olympiad/:/Choose your practice/}).first().waitFor().catch(async()=>{await page.getByRole('button',{name:slug==='c3l6-organic-reactions'?'Start part (a)':'Start practice',exact:true}).waitFor()});await page.reload();await page.locator('.course-shell').waitFor();
 const q=all.find(q=>q.ref.activityId===course+'/'+slug);if(q){await page.goto(alias+'?review='+encodeURIComponent(q.ref.questionId)+'&level='+q.ref.level+'&seed='+q.ref.seed);await page.locator('.teacher-answer').waitFor();assert.equal(await page.locator('.question-meta code').innerText(),q.ref.questionId);await page.reload();await page.locator('.teacher-answer').waitFor();assert.equal(await page.locator('.question-meta code').innerText(),q.ref.questionId)}tested.push({slug,coded:!!q,codeless:true,refresh:true});}
 await page.goto(url+'?legacy='+encodeURIComponent('https://old.invalid/activities/rocket-recall/index.html?review=RR-1'));await page.getByText('Rocket Recall is excluded from this application.',{exact:true}).waitFor();assert.equal((await rows(page,course,'evidence')).length,0);return{tested,rocketRejected:true};
 });
 await run(course+'-old-writes-page-errors',async()=>{assert.deepEqual(await page.evaluate(()=>window.oldWrites),[]);assert.deepEqual(errors,[]);return{pageErrors:errors,oldWrites:[]}});
 }
}finally{for(const c of contexts)await c.close();await browser.close();await new Promise(r=>host.close(r));report.status=report.failures.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,checks:report.checks.length,failures:report.failures}));if(report.failures.length)process.exitCode=1;}
