import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {server,project} from './server.mjs';
const require=createRequire(path.join(project,'../../package.json')),here=import.meta.dirname,temp=path.join(here,'.olympiad-browser');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;const host=server();await new Promise(r=>host.listen(5201,'127.0.0.1',r));const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${temp}/cache`]}),context=await browser.newContext(),page=await context.newPage(),report={startedAt:new Date().toISOString(),status:'RUNNING',pageErrors:[]};page.on('pageerror',e=>report.pageErrors.push(e.message));
async function curriculum(){return page.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('masters-of-chemistry-alevel-local');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});const x={};for(const table of ['attempts','sessions','evidence'])x[table]=await new Promise((r,j)=>{const q=db.transaction(table).objectStore(table).getAll();q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});db.close();return x})}
try{
await page.goto('http://127.0.0.1:5201/stage-s5/alevel/index.html?view=olympiad');await page.getByRole('button',{name:'Start part (a)',exact:true}).waitFor();const before=await curriculum();assert.equal(await page.evaluate(()=>window.__mastersOlympiad),undefined);
await page.evaluate(()=>{window.failChallenge=true;const old=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='olympiad'&&window.failChallenge)throw new DOMException('S5 challenge quota','QuotaExceededError');return old.apply(this,args)}});await page.getByRole('button',{name:'Start part (a)',exact:true}).click();await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();await page.getByRole('button',{name:'Practice',exact:true}).click();await page.waitForTimeout(100);assert.equal(new URL(page.url()).searchParams.get('view'),'olympiad');await page.evaluate(()=>window.failChallenge=false);await page.getByRole('button',{name:'Retry save',exact:true}).click();await page.getByText('Challenge drawings saved on this device',{exact:true}).waitFor();assert.deepEqual(await curriculum(),before);
const complete=await page.evaluate(async()=>{
const {sourceBank,bUnits}=await import('/src/activities/olympiad/c3l6/source-bank.ts');const {c3Dependencies}=await import('/src/activities/olympiad/c3l6/dependencies.ts');const {c3Policy,blankC3Progress}=await import('/src/activities/olympiad/c3l6/policy.ts');const {createChemistryRepository}=await import('/src/persistence/repository.ts');
const challenge={activityId:'alevel/c3l6-organic-reactions',introduction:[],classifications:sourceBank.stages.a.answers.map(a=>({...a,reaction:[]})),hydrolysis:bUnits.map(u=>({unitId:u.id,context:[],slots:u.slots.map(id=>sourceBank.stages.b.answers.find(a=>a.id===id))})),network:{context:[],slots:sourceBank.stages.c.answers},dependencies:c3Dependencies};let progress=blankC3Progress('local');const doCommand=c=>{const result=c3Policy.transition(challenge,progress,c);if(!result.accepted)throw Error(JSON.stringify({command:c,result}));progress=result.progress};
doCommand({kind:'navigate',stage:'a'});for(const a of challenge.classifications)doCommand({kind:'classify',id:a.id,value:a.answer});doCommand({kind:'check-a'});doCommand({kind:'navigate',stage:'b'});for(const u of challenge.hydrolysis){for(const slot of u.slots)doCommand({kind:'draw-b',slotId:slot.id,drawing:{kind:'molecule',graph:structuredClone(slot.alternatives[0].graph),history:[]}});doCommand({kind:'check-b-unit',unitId:u.unitId})}doCommand({kind:'navigate',stage:'c'});for(const slot of challenge.network.slots){doCommand({kind:'draw-c',slotId:slot.id,drawing:{kind:'molecule',graph:structuredClone(slot.alternatives[0].graph),history:[]}});doCommand({kind:'check-c-slot',slotId:slot.id})}if(!progress.completed.c)throw Error('Challenge incomplete');const r=await createChemistryRepository('masters-of-chemistry-alevel-local').saveOlympiad(progress);if(!r.ok)throw Error(JSON.stringify(r));return progress;
});
await page.reload();await page.getByText('Saved challenge restored.',{exact:true}).waitFor();const body=await page.locator('body').innerText();assert(!/mastery|\bgem\b|active answering time|saved practice result/i.test(body));assert.deepEqual(await curriculum(),before);const loaded=await page.evaluate(async()=>{const {createChemistryRepository}=await import('/src/persistence/repository.ts');return(await createChemistryRepository('masters-of-chemistry-alevel-local').loadOlympiad('local')).value});assert.deepEqual(loaded,complete);await page.screenshot({path:path.join(here,'olympiad-completed.png'),fullPage:true});await page.getByRole('button',{name:'Statistics',exact:true}).click();await page.getByTestId('statistics-total').waitFor();assert.equal(await page.getByTestId('statistics-total').innerText(),'0');assert.equal(Number(await page.getByTestId('statistics-time').getAttribute('data-active-ms')),0);assert.deepEqual(await curriculum(),before);assert.deepEqual(report.pageErrors,[]);report.status='PASS';report.checks={quotaBlocksDepartureRetry:true,fullCheckedCompletion:complete.completed,drawingsB:Object.keys(complete.drawingsB).length,drawingsC:Object.keys(complete.drawingsC).length,allGraphsPreserved:true,zeroCurriculumAttemptSessionEvidence:true,statisticsTotal:0,statisticsActiveMs:0,uiNoMasteryTimingLabels:true};
}catch(e){report.status='FAIL';report.failure=e.stack;await page.screenshot({path:path.join(here,'olympiad-failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'olympiad-browser-results.json'),JSON.stringify(report,null,2)+'\n');await context.close();await browser.close();await new Promise(r=>host.close(r));console.log(JSON.stringify(report));}
