import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import{pathToFileURL}from'node:url';
const here=import.meta.dirname,origin='http://127.0.0.1:5183',report={status:'RUNNING',headless:true,method:'Pinned workspace Playwright, fresh nonpersistent Edge contexts, isolated run IDs; trusted browser mouse/keyboard and CDP touchscreen events',checks:[],errors:[]};
const{chromium}=await import(pathToFileURL(path.join(process.cwd(),'node_modules/playwright/index.mjs')).href);const response=await fetch(origin+'/src/editors/molecule/MoleculeEditor.tsx');assert.equal(response.status,200);assert((await response.text()).includes('Carbon chain'));
const browser=await chromium.launch({channel:'msedge',headless:true});let active;
const snapshot=p=>p.evaluate(()=>window.__mastersOlympiad.snapshot().progress),flush=p=>p.evaluate(()=>window.__mastersOlympiad.flush());
async function drawPoint(page,x,y){return page.locator('.molecule-workspace').evaluate((svg,[x,y])=>{const p=new DOMPoint(x,y).matrixTransform(svg.getScreenCTM());return{x:p.x,y:p.y};},[x,y]);}
async function drag(page,start,end){const a=await drawPoint(page,...start),b=await drawPoint(page,...end);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();await flush(page);}
async function images(page){await page.locator('.c3l6 img').evaluateAll(nodes=>Promise.all(nodes.map(n=>n.decode())));assert(await page.locator('.c3l6 img').evaluateAll(nodes=>nodes.every(n=>n.complete&&n.naturalWidth>0)));}
try{
 for(const[name,viewport]of[['desktop',{width:1440,height:1000}],['tablet',{width:1024,height:900}],['mobile',{width:390,height:844}]]){
  const context=await browser.newContext({viewport,hasTouch:true}),page=await context.newPage();active=page;page.on('pageerror',e=>report.errors.push(`${name}: ${e.message}`));
  await page.goto(`${origin}/alevel.html?run=e03-restore-${name}-${Date.now()}&view=olympiad`);await page.waitForFunction(()=>window.__mastersOlympiad);await page.locator('.c3-intro').waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(here,`${name}-intro.png`),fullPage:true});
  assert.equal(await page.locator('.c3-intro .level').count(),3);assert.equal(await page.locator('.c3-examples img').count(),15);await images(page);await page.screenshot({path:path.join(here,`${name}-intro.png`),fullPage:true});
  await page.getByRole('button',{name:'Start part (a)',exact:true}).click();assert.equal(await page.locator('.digitised-a .digitised-reaction').count(),10);await images(page);await page.screenshot({path:path.join(here,`${name}-a.png`),fullPage:true});
  await page.evaluate(async()=>{const m=await import('/src/activities/olympiad/c3l6/index.ts');for(const a of m.c3Challenge.classifications)await window.__mastersOlympiad.command({kind:'classify',id:a.id,value:a.answer});});await page.getByRole('button',{name:'Check part (a)',exact:true}).click();await page.getByRole('button',{name:'Continue to part (b)',exact:true}).click();await page.locator('.molecule-workspace').waitFor();
  assert.equal(await page.locator('.digitised-b [data-step]').count(),7);assert.equal(await page.locator('.digitised-b [data-b-slot]').count(),12);assert.equal(await page.locator('.b-coefficient').count(),2);await images(page);await page.screenshot({path:path.join(here,`${name}-b.png`),fullPage:true});
  const scheme=page.locator('.b-scheme-scroll').last();assert(await scheme.evaluate(n=>n.scrollWidth>n.clientWidth));await scheme.focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.b-scheme-scroll:last-child')?.scrollLeft>0||[...document.querySelectorAll('.b-scheme-scroll')].at(-1).scrollLeft>0);await scheme.evaluate(n=>n.scrollLeft=0);assert(await page.locator('.c3-scroll-guidance').isVisible());
  const canvas=page.locator('.molecule-workspace');await canvas.scrollIntoViewIfNeeded();await canvas.focus();await page.keyboard.press('Enter');await flush(page);assert.equal((await snapshot(page)).drawingsB.A.graph.atoms.length,1);
  await canvas.locator('[data-atom="1"]').focus();await page.keyboard.press('ArrowRight');assert.equal(await canvas.locator('.ghost').count(),1);await page.screenshot({path:path.join(here,`${name}-keyboard-preview.png`)});await page.keyboard.press('Enter');await flush(page);let p=await snapshot(page);assert.equal(p.drawingsB.A.graph.atoms.length,2);assert.equal(p.drawingsB.A.history.length,2);assert.equal(p.drawingsB.A.graph.atoms[0].x,0);assert.equal(p.drawingsB.A.graph.atoms[1].x,74);
  await canvas.locator('[data-bond]').focus();await page.keyboard.press('Enter');await flush(page);assert.equal((await snapshot(page)).drawingsB.A.graph.bonds[0].order,2);await page.keyboard.press('Delete');await flush(page);assert.equal((await snapshot(page)).drawingsB.A.graph.bonds.length,0);await canvas.focus();await page.keyboard.press('Control+z');await flush(page);assert.equal((await snapshot(page)).drawingsB.A.graph.bonds[0].order,2);
  await page.getByRole('button',{name:'Oxygen',exact:true}).click();await canvas.locator('[data-atom="2"]').click();await flush(page);await page.locator('.molecule-editor .drawing-card').screenshot({path:path.join(here,`${name}-carbonyl.png`)});
  p=await snapshot(page);const before=p.drawingsB.A;await page.getByRole('button',{name:'Clean up',exact:true}).click();await flush(page);const cleaned=(await snapshot(page)).drawingsB.A;assert.deepEqual(cleaned.graph.bonds,before.graph.bonds);await page.getByRole('button',{name:'Undo',exact:true}).click();await flush(page);assert.deepEqual((await snapshot(page)).drawingsB.A,before);
  await page.getByRole('button',{name:'Clear structure',exact:true}).click();await flush(page);await page.getByRole('button',{name:'Carbon chain',exact:true}).click();await canvas.scrollIntoViewIfNeeded();await drag(page,[-200,0],[200,0]);p=await snapshot(page);assert(p.drawingsB.A.graph.atoms.length>4);assert.equal(p.drawingsB.A.history.length,before.history.length+2);await page.locator('.drawing-card').screenshot({path:path.join(here,`${name}-chain.png`)});await page.getByRole('button',{name:'Undo',exact:true}).click();await flush(page);assert.equal((await snapshot(page)).drawingsB.A.graph.atoms.length,0);
  await page.getByRole('button',{name:'Carbon',exact:true}).click();const center=await drawPoint(page,0,0);await page.mouse.move(center.x,center.y);await page.mouse.down();await page.mouse.move(center.x+90,center.y+30,{steps:5});await page.keyboard.press('Escape');await page.mouse.up();await flush(page);assert.equal((await snapshot(page)).drawingsB.A.graph.atoms.length,0);
  await page.mouse.move(center.x,center.y);await page.mouse.down();await page.mouse.move(center.x+80,center.y,{steps:3});const rect=await canvas.boundingBox();await page.mouse.move(rect.x+rect.width+20,rect.y+20);await page.mouse.up();await flush(page);assert.equal((await snapshot(page)).drawingsB.A.graph.atoms.length,0);
  const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:center.x,y:center.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:center.x+80,y:center.y-30}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await flush(page);assert.equal((await snapshot(page)).drawingsB.A.graph.atoms.length,2);
  const touchBefore=(await snapshot(page)).drawingsB.A;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:center.x-80,y:center.y+70}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:center.x-10,y:center.y+70}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await flush(page);assert.deepEqual((await snapshot(page)).drawingsB.A,touchBefore);
  await page.getByRole('button',{name:'Structural',exact:true}).click();assert((await canvas.locator('.atom-subscript').count())>0);await page.locator('.drawing-card').screenshot({path:path.join(here,`${name}-structural.png`)});
  await flush(page);p=await snapshot(page);await page.reload();await canvas.waitFor();assert.deepEqual((await snapshot(page)).drawingsB.A,p.drawingsB.A);
  await page.evaluate(async()=>{const m=await import('/src/activities/olympiad/c3l6/index.ts');for(const u of m.c3Challenge.hydrolysis)for(const s of u.slots)await window.__mastersOlympiad.command({kind:'draw-b',slotId:s.id,drawing:{kind:'molecule',graph:s.alternatives[0].graph,history:[]}});});
  for(const id of ['b-i','b-ii','b-iii','b-iv-1','b-iv-2','b-iv-3','b-iv-4'])await page.getByRole('button',{name:`Check reaction ${id}`,exact:true}).click();await flush(page);p=await snapshot(page);assert(p.completed.b);assert.equal(await page.locator('[data-b-repeat] .molecule-preview').count(),2);await page.getByRole('button',{name:'View completed structure A',exact:true}).click();assert(await page.getByRole('button',{name:'Carbon',exact:true}).isDisabled());
  await page.getByRole('button',{name:'Continue to part (c)',exact:true}).click();assert.equal(await page.locator('.c-answer-node').count(),9);assert.equal(await page.locator('.c-check').count(),9);await page.screenshot({path:path.join(here,`${name}-c.png`),fullPage:true});
  await page.evaluate(async()=>{const m=await import('/src/activities/olympiad/c3l6/index.ts');for(const s of m.c3Challenge.network.slots)await window.__mastersOlympiad.command({kind:'draw-c',slotId:s.id,drawing:{kind:'molecule',graph:s.alternatives[0].graph,history:[]}});});for(const id of ['R','S','T','U','V','W','X','Y','Z'])await page.getByRole('button',{name:`Check structure ${id}`,exact:true}).click();await flush(page);assert((await snapshot(page)).completed.c);
  const teacherBefore=await snapshot(page);await page.getByRole('button',{name:'Teacher preview',exact:true}).click();await page.getByRole('button',{name:'Part (b) · Complete',exact:true}).click();await page.getByRole('button',{name:'View completed structure K',exact:true}).click();await page.locator('[aria-label="K source erratum"]').waitFor();await page.screenshot({path:path.join(here,`${name}-teacher-k.png`),fullPage:true});assert(await page.getByRole('button',{name:'Carbon',exact:true}).isDisabled());await canvas.focus();await page.keyboard.press('Enter');await page.keyboard.press('Control+z');await flush(page);assert.deepEqual(await snapshot(page),teacherBefore);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const rows=await page.evaluate(async()=>{const{createChemistryRepository}=await import('/src/persistence/index.ts');return createChemistryRepository(window.__mastersOlympiad.snapshot().databaseName).curriculumHistory({course:'alevel',profileId:'local'});});assert(rows.ok);assert.equal(rows.value.length,0);
  report.checks.push(`${name}: ordered intro/A/B/C topology; keyboard growth/bond cycle/delete/undo; source carbonyl/clean/chain; lossless Escape/outside/touchCancel; trusted touch growth; structural subscripts; graph/history reload; seven B and nine C actual checks/locks/repeated H/J; teacher K erratum no mutation; no page overflow/zero curriculum rows`);await context.close();
 }
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;await active?.screenshot({path:path.join(here,'browser-failure.png'),fullPage:true}).catch(()=>{});}
finally{await browser.close();await fs.writeFile(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
