import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import{pathToFileURL}from'node:url';
const cleaned=process.argv.includes('--clean'),prefix=cleaned?'compare-clean':'compare',here=import.meta.dirname,root=path.join(process.cwd(),'apps/Masters-of-A-Level-Chemistry/src'),report={status:'RUNNING',cleanedUsingOriginalSource:cleaned,method:'Same graph/representation in isolated original and React contexts; source naturally sized and React card constrained to same source card width for scoped depiction comparison; no runtime CSS writes',checks:[],comparisons:[]};
const{chromium}=await import(pathToFileURL(path.join(process.cwd(),'node_modules/playwright/index.mjs')).href);
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf'};const server=http.createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const original=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'msedge',headless:true});
const geometry=p=>p.locator('svg#canvas,svg.molecule-workspace').evaluate(svg=>({labels:[...svg.querySelectorAll('.atom-label')].map(n=>({x:Number(n.getAttribute('x')),y:Number(n.getAttribute('y')),chunks:[...n.querySelectorAll('tspan')].map(t=>({text:t.textContent,sub:t.classList.contains('atom-subscript')}))})),bonds:[...svg.querySelectorAll('.bond-line')].map(n=>['x1','y1','x2','y2'].map(a=>Number(n.getAttribute(a))))}));
try{
for(const[name,viewport]of[['desktop',{width:1440,height:1000}],['tablet',{width:1024,height:900}],['mobile',{width:390,height:844}]]){
 const context=await browser.newContext({viewport}),source=await context.newPage(),current=await context.newPage();
 await source.goto(original+'/activities/c3l6-organic-reactions/index.html');await source.locator('#panel-intro .digitised-intro').waitFor();await source.locator('#startQuestions').click();await source.locator('.classification-row').first().waitFor();await source.evaluate(()=>{for(const a of C3L6Content.stages.a.answers)document.querySelector(`input[name="reaction-${a.id}"][value="${a.answer}"]`).click();});await source.locator('#checkPart').click();await source.locator('#continue').click();await source.locator('.digitised-b').waitFor();
 await source.waitForFunction(()=>JSON.parse(localStorage.getItem('sjs:c3l6:2012-q2:draft:v1')).stage==='b');
 if(cleaned && name==='mobile'){await source.locator('.digitised-b img').evaluateAll(ns=>Promise.all(ns.map(n=>n.decode())));await source.screenshot({path:path.join(here,'source-mobile-b.png'),fullPage:true});}
 const sample=await source.evaluate(useClean=>{const g=C3L6Content.stages.b.answers.find(a=>a.id==='C').alternatives[0].graph;return useClean?MoleculeLayout.clean(g):g;},cleaned);await source.addInitScript(g=>{const p=JSON.parse(localStorage.getItem('sjs:c3l6:2012-q2:draft:v1'));p.responses.b.A={graph:g,history:[]};localStorage.setItem('sjs:c3l6:2012-q2:draft:v1',JSON.stringify(p));},sample);await source.reload();await source.locator('#canvas [data-atom]').first().waitFor();await source.evaluate(()=>document.fonts.ready);assert.deepEqual(await source.evaluate(()=>JSON.parse(localStorage.getItem('sjs:c3l6:2012-q2:draft:v1')).responses.b.A.graph),sample);
 await current.goto(`http://127.0.0.1:5183/alevel.html?run=e03-compare-${name}-${Date.now()}&view=olympiad`);await current.locator('.c3-intro').waitFor();await current.evaluate(async g=>{const m=await import('/src/activities/olympiad/c3l6/index.ts');for(const a of m.c3Challenge.classifications)await window.__mastersOlympiad.command({kind:'classify',id:a.id,value:a.answer});await window.__mastersOlympiad.command({kind:'check-a'});await window.__mastersOlympiad.command({kind:'navigate',stage:'b'});await window.__mastersOlympiad.command({kind:'draw-b',slotId:'A',drawing:{kind:'molecule',graph:g,history:[]}});},sample);await current.locator('.molecule-workspace [data-atom]').first().waitFor();await current.evaluate(()=>document.fonts.ready);assert.deepEqual(await current.evaluate(()=>window.__mastersOlympiad.snapshot().progress.drawingsB.A.graph),sample);
 const width=(await source.locator('.drawing-card').boundingBox()).width;await current.locator('.drawing-card').evaluate((n,w)=>{n.style.width=`${w}px`;n.style.maxWidth='none';},width);
 for(const view of ['Skeletal','Structural']){
  await source.getByRole('button',{name:view,exact:true}).click();await current.getByRole('button',{name:view,exact:true}).click();await source.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await current.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const a=await geometry(source),b=await geometry(current);assert.deepEqual(b,a);report.comparisons.push({name,view,cardWidth:width,atomCount:sample.atoms.length,bondCount:sample.bonds.length,exactLabelAndBondGeometry:true});
  await source.locator('.drawing-card').screenshot({path:path.join(here,`${prefix}-original-${name}-${view.toLowerCase()}.png`)});await current.locator('.drawing-card').screenshot({path:path.join(here,`${prefix}-react-${name}-${view.toLowerCase()}.png`)});
 }
 report.checks.push(`${name}: matching ${sample.atoms.length}-heavy-atom accepted dihydroxyketone graph${cleaned?' cleaned by original source':''}; exact measured labels/true subscripts and clipped multiple-bond endpoints equal source in both representations; screenshots at equal card width`);await context.close();
}
report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;}
finally{await browser.close();await new Promise(r=>server.close(r));await fs.writeFile(path.join(here,`${prefix}-results.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
