import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import{pathToFileURL}from'node:url';
const here=import.meta.dirname,{chromium}=await import(pathToFileURL(path.join(process.cwd(),'node_modules/playwright/index.mjs')).href),browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),report={status:'RUNNING',checks:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
const snapshot=()=>page.evaluate(()=>window.__mastersOlympiad.snapshot().progress),flush=()=>page.evaluate(()=>window.__mastersOlympiad.flush());
const point=(id)=>page.locator('.molecule-workspace').evaluate((svg,id)=>{const a=svg.querySelector(`[data-atom="${id}"] .atom-hit`),p=new DOMPoint(Number(a.getAttribute('cx')),Number(a.getAttribute('cy'))).matrixTransform(svg.getScreenCTM());return{x:p.x,y:p.y};},id);
try{
 await page.goto(`http://127.0.0.1:5183/alevel.html?run=e03-edge-${Date.now()}&view=olympiad`);await page.locator('.c3-intro').waitFor();
 await page.evaluate(async()=>{const m=await import('/src/activities/olympiad/c3l6/index.ts');for(const a of m.c3Challenge.classifications)await window.__mastersOlympiad.command({kind:'classify',id:a.id,value:a.answer});await window.__mastersOlympiad.command({kind:'check-a'});await window.__mastersOlympiad.command({kind:'navigate',stage:'b'});await window.__mastersOlympiad.command({kind:'draw-b',slotId:'A',drawing:{kind:'molecule',graph:{atoms:[{id:1,element:'C',x:0,y:0},{id:2,element:'C',x:74,y:0},{id:3,element:'C',x:74,y:74}],bonds:[{a:1,b:2,order:1},{a:2,b:3,order:1}]},history:[]}});});const canvas=page.locator('.molecule-workspace');await canvas.scrollIntoViewIfNeeded();let a=await point(3),b=await point(1);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});assert.equal(await canvas.locator('.preview-target').count(),1);await page.locator('.drawing-card').screenshot({path:path.join(here,'ring-target-preview.png')});await page.mouse.up();await flush();let p=await snapshot();assert.equal(p.drawingsB.A.graph.atoms.length,3);assert.equal(p.drawingsB.A.graph.bonds.length,3);assert.equal(p.drawingsB.A.history.length,1);assert.equal(p.drawingsB.A.graph.atoms[2].x,74);
 await page.getByRole('button',{name:'Erase',exact:true}).click();a=await point(1);b=await point(2);await page.mouse.click((a.x+b.x)/2,(a.y+b.y)/2);await flush();assert.equal((await snapshot()).drawingsB.A.graph.bonds.length,2);await canvas.focus();await page.keyboard.press('Control+z');await flush();assert.equal((await snapshot()).drawingsB.A.graph.bonds.length,3);await page.getByRole('button',{name:'Erase',exact:true}).click();
 const before=(await snapshot()).drawingsB.A;a=await point(3);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(a.x+70,a.y+20,{steps:5});await canvas.evaluate(svg=>{for(let i=0;i<100;i++)if(svg.hasPointerCapture(i))svg.releasePointerCapture(i);});await page.mouse.up();await flush();assert.deepEqual((await snapshot()).drawingsB.A,before);
 await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(a.x+70,a.y+20,{steps:5});await page.evaluate(()=>window.__mastersOlympiad.command({kind:'select-slot',stage:'b',slotId:'B'}));await page.mouse.up();await flush();p=await snapshot();assert.deepEqual(p.drawingsB.A,before);assert(!p.drawingsB.B?.graph.atoms.length);
 assert.equal(await page.getByRole('button',{name:'Skeletal',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Structural',exact:true}).click();await page.getByRole('button',{name:'Edit structure A',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Structural',exact:true}).getAttribute('aria-pressed'),'true');
 await canvas.scrollIntoViewIfNeeded();a=await point(3);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(a.x+70,a.y+20,{steps:5});await page.evaluate(()=>window.__mastersOlympiad.command({kind:'navigate',stage:'a'}));await page.mouse.up();await flush();assert.equal(await page.locator('.molecule-workspace').count(),0);assert.deepEqual((await snapshot()).drawingsB.A,before);
 await page.getByRole('button',{name:'Part (b)',exact:true}).click();await page.getByText('Alternative controls and view',{exact:true}).click();await page.getByLabel('Selected atom',{exact:true}).selectOption('3');await page.getByLabel('New element',{exact:true}).selectOption('O');await page.getByLabel('Extension direction',{exact:true}).selectOption('90');await page.getByRole('button',{name:'Extend selected atom',exact:true}).click();await flush();p=await snapshot();assert.equal(p.drawingsB.A.graph.atoms.length,4);assert.equal(p.drawingsB.A.graph.atoms[3].element,'O');const graph=p.drawingsB.A;await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Pan right',exact:true}).click();await page.getByRole('button',{name:'Fit molecule',exact:true}).click();assert.deepEqual((await snapshot()).drawingsB.A,graph);
 report.checks.push('Trusted mouse closes ring without atom movement/extra atoms; target preview; bond eraser/undo; lost pointer capture, slot switch and real editor unmount cancel losslessly; representation survives slot switch; accessible inspector grows O at90deg; view changes create no drawing/history edit');assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;await page.screenshot({path:path.join(here,'edge-failure.png'),fullPage:true}).catch(()=>{});}
finally{await browser.close();await fs.writeFile(path.join(here,'edge-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
