import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {productionRegistry} from '../../../../../src/foundation/registry.ts';
const here=import.meta.dirname,app=path.resolve(here,'../../../../..'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.f08-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const all=JSON.parse(fs.readFileSync(path.join(here,'fixtures.json'))),fixtures=all.filter(f=>['acid','calorimetry','bond','bonding','energy','practical'].includes(f.source.family)&&!f.question.parts.some(p=>p.kind==='energy-profile'));
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={agentId:'F08',jobId:'F2-SHARED',status:'RUNNING',startedAt:new Date().toISOString(),checks:[],shots:[],errors:[],limits:['Fresh synthetic app IndexedDB namespaces and nonpersistent contexts only.','Native OS suspend/minimize coverage retained by foreman; this browser suite checks reload and first timing.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.locator('.source-player').screenshot({path:path.join(here,name+'.png')});report.shots.push(name+'.png')}
async function start(c,f,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5188/${f.course}.html?run=f08-family-${Date.now()}-${Math.random().toString(36).slice(2)}`);await p.locator('.original-landing').waitFor({state:'attached'});
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();if(f.course==='alevel'&&f.gem.startsWith('u6'))await p.locator('#flipYear').click();const gem=p.locator('[data-leaf="'+f.gem+'"]').first();await gem.locator('xpath=ancestor::*[contains(@class,"topic-section")]').locator('.topic-trigger').click();await gem.click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click()}
 else{await p.evaluate(gem=>location.hash=gem,f.gem);await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${f.ref.level}"]`).click()}
 await p.locator('.question-player').waitFor();await flush(p);
 if(mode!=='revision'&&((await snap(p)).question.ref.questionId!==f.ref.questionId|| (await snap(p)).question.ref.level!==f.ref.level)){await p.evaluate(async f=>{const s=window.__mastersActivity.snapshot(),{productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const a=productionRegistry.get(f.activity),provider=await a.provider();provider.restore(f.ref);const id=crypto.randomUUID(),target={...s.attempt.target,gemId:f.gem,level:f.ref.level},attempt={...s.attempt,attemptId:id,ref:f.ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{...s.attempt.timing,attemptId:id,activeMs:0,finished:false}};const session={...s.session,currentAttemptId:id,...(s.session.kind==='practice'?{target,previousQuestionIds:[f.ref.questionId]}:{})};const repo=createChemistryRepository(s.databaseName),saved=await repo.saveCurriculum({attempt,session,question:provider.restore(f.ref),namespace:attempt.namespace});if(!saved.ok)throw Error(JSON.stringify(saved));repo.close?.()},f);await p.reload();await p.locator('.source-player').waitFor();await flush(p)}
 if(mode!=='revision')assert.equal((await snap(p)).question.ref.questionId,f.ref.questionId);return p;
}
function answers(f){const out={};for(const part of f.question.parts){if(part.kind==='numeric')out[part.id]={kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit};if(part.kind==='text')out[part.id]={kind:'text',value:part.accepted[0]};if(part.kind==='choice')out[part.id]={kind:'choice',selected:part.acceptedOptionSets[0]};if(part.kind==='correction'){const s=part.segments.find(x=>x.id===f.source.practical.correction.errorId);out[part.id]={kind:'correction',selections:[s],replacement:f.source.practical.fields[0].answers[0]}}}return out}
async function fill(p,f,data){for(const part of f.question.parts){const r=data[part.id];if(!r)continue;if(r.kind==='numeric'){const inputs=p.locator('.response-input');await inputs.nth(f.question.parts.filter(x=>x.kind==='numeric').findIndex(x=>x.id===part.id)).fill(r.raw)}else if(r.kind==='text'){await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.value)}else if(r.kind==='choice'){const field=p.locator('.choice-field,.choice-box').filter({has:p.getByText(f.source.fields[part.id].label,{exact:true})});if(f.source.family==='practical'){for(const selected of r.selected)await field.getByText(selected,{exact:true}).click()}else{for(const selected of r.selected)await field.getByRole('button').filter({hasText:selected}).click()}}else if(r.kind==='correction'){await p.getByRole('button',{name:r.selections[0].text.trim(),exact:true}).click();await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.replacement)}}await flush(p)}
async function wrong(f,correct){const a=productionRegistry.get(f.activity),policy=await a.marking();for(const part of f.question.parts){const v=correct[part.id];const candidates=part.kind==='numeric'?['999999']:part.kind==='choice'?part.options.map(o=>o.id).filter(id=>!v.selected.includes(id)):part.kind==='correction'?['increases','wrong']:['0','1','2','3','4','5','6','proton','neutron','ionic','covalent','metallic','endothermic','exothermic','positive','negative','wrong'];for(const x of candidates){const copy=structuredClone(correct);copy[part.id]=v.kind==='numeric'?{...v,raw:x}:v.kind==='choice'?{...v,selected:v.selected.length===1?[x]:[x,...v.selected.slice(1)]}:v.kind==='correction'?{...v,replacement:x}:{...v,value:x};const outcome=policy.mark(f.question,copy);if(outcome.accepted&&outcome.marks.earned<outcome.marks.available)return copy}}throw Error('No meaningful wrong fixture '+f.ref.questionId)}

async function review(p,met){const q=(await snap(p)).question,part=q.parts[0];for(const section of part.sections)await p.locator('[id$="-'+section.id+'"]').fill(part.rubric.map(r=>r.text).join(' '));await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.locator('.locked-answer').waitFor();await flush(p);return (await snap(p)).attempt}
async function finish(p,met){const a=(await snap(p)).attempt;for(const point of (await snap(p)).question.parts[0].rubric){if(!met)await p.locator('.decision.no:enabled').click();else{await p.locator('.decision.yes:enabled').click();await p.locator('.keyboard-evidence summary').click();await p.getByLabel('Start',{exact:true}).fill('0');await p.getByLabel('End (exclusive)',{exact:true}).fill(String(a.reviews[0].lockedText.length));await p.getByRole('button',{name:'Use selected text',exact:true}).click()}}await p.getByRole('button',{name:'Finish marking',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await flush(p)}
try{
 // Ready, chemically correct specialist states must never submit through an anchor commit.
 for(const f of all.filter(f=>['titration-curve','energy-profile'].includes(f.question.parts[0].kind))){const c=await b.newContext({viewport:{width:1440,height:1000}}),p=await start(c,f);await p.evaluate(async f=>{for(const [partId,response] of Object.entries(f.source.modelResponses))await window.__mastersActivity.respond(partId,response)},f);await flush(p);await p.locator(f.source.family==='titration'?'.tc-alternatives summary':'.coordinate-alternatives summary').click();const before=await snap(p),label=f.source.family==='titration'?'Final pH':'Arrow x position',input=p.getByLabel(label,{exact:true});await input.fill(f.source.family==='titration'?'15':'1000');await input.press('Enter');await flush(p);const after=await snap(p);assert.equal(await input.getAttribute('aria-invalid'),'true');assert.equal(after.attempt.phase,'answering');assert.equal(after.attempt.firstAssessment,undefined);assert.deepEqual(after.attempt.currentResponses,before.attempt.currentResponses);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,0);await shot(p,'invalid-enter-'+f.source.family);report.checks.push({family:f.source.family,invalidCoordinateEnterNoSubmission:true,validPriorModelRetained:true});await c.close()}
 // Teacher mounts all 35 source signatures, including graphs, self-rubrics and source-native models.
 for(const f of all){const c=await b.newContext({viewport:{width:390,height:844}}),p=await c.newPage();await p.goto('http://127.0.0.1:5188/'+f.course+'.html?view=teacher&activity='+f.activity+'&review='+f.ref.questionId+'&level='+f.ref.level+'&seed='+f.ref.seed+'&run=f08-teacher-all');await p.locator('.question-player').waitFor();await flush(p);assert.equal((await snap(p)).attempt,null);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('.question-player').screenshot({path:path.join(here,'teacher-mobile-'+f.ref.questionId+'.png')});report.shots.push('teacher-mobile-'+f.ref.questionId+'.png');report.checks.push({teacher:f.ref.questionId,signature:f.signature,evidenceZero:true,overflow:false});await c.close()}
 // Actual topic selection, revision launch, locked-answer reload, final score and scheduler Next.
 const f=all.find(f=>f.source.family==='comparison'),c=await b.newContext({viewport:{width:820,height:1180}}),p=await start(c,f,'revision');assert.equal((await snap(p)).session.kind,'revision');const frozen=await review(p,true);await p.locator('.decision.yes:enabled').click();await flush(p);await p.reload();await p.locator('.keyboard-evidence').waitFor();await flush(p);let restored=await snap(p);assert.equal(restored.attempt.attemptId,frozen.attemptId);assert.deepEqual(restored.attempt.firstResponse,frozen.firstResponse);const t=restored.attempt.reviews[0].lockedText;await p.locator('.keyboard-evidence summary').click();await p.getByLabel('Start',{exact:true}).fill('0');await p.getByLabel('End (exclusive)',{exact:true}).fill(String(t.length));await p.getByRole('button',{name:'Use selected text',exact:true}).click();for(const point of restored.question.parts[0].rubric.slice(1)){await p.locator('.decision.no:enabled').click()}await p.getByRole('button',{name:'Finish marking',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await flush(p);const completed=await snap(p);assert.equal(completed.attempt.firstAssessment.marks.earned,1);assert.deepEqual(completed.attempt.firstResponse,frozen.firstResponse);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);await shot(p,'rubric-revision-finished');await p.reload();await p.locator('.assessment-feedback').waitFor();await flush(p);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);await p.getByRole('button',{name:'Next question',exact:true}).click();await p.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,frozen.attemptId);await flush(p);assert.equal((await snap(p)).session.kind,'revision');assert.equal((await snap(p)).attempt.phase,'answering');assert.equal((await snap(p)).attempt.timing.finished,false);report.checks.push({family:'comparison',revisionLaunch:true,awaitingEvidenceReload:true,lockedRangePersisted:true,firstScoreFrozen:true,historyDedup:true,schedulerNext:true});await c.close();report.status='PASS'
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'extra-browser-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,shots:report.shots.length,failure:report.failure}))}
