import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {productionRegistry} from '../../../../../src/foundation/registry.ts';
const here=import.meta.dirname,app=path.resolve(here,'../../../../..'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.f08-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const all=JSON.parse(fs.readFileSync(path.join(here,'fixtures.json'))),fixtures=all.filter(f=>['acid','calorimetry','bond','bonding','energy','practical'].includes(f.source.family)&&!f.question.parts.some(p=>p.kind==='energy-profile'));
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={agentId:'F08',jobId:'F2-SHARED',status:'RUNNING',startedAt:new Date().toISOString(),checks:[],shots:[],errors:[],limits:['Fresh synthetic app IndexedDB namespaces and nonpersistent contexts only.','Native OS suspend/minimize coverage retained by foreman; this browser suite checks reload and first timing.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.locator('.source-player').screenshot({path:path.join(here,name+'.png')});report.shots.push(name+'.png')}
async function start(c,f,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5188/${f.course}.html?run=f08-family-${Date.now()}-${Math.random().toString(36).slice(2)}`);await p.locator('.original-landing').waitFor({state:'attached'});
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();if(f.course==='alevel'&&f.gem.startsWith('u6'))await p.locator('#flipYear').click();const gem=p.locator('[data-leaf="'+f.gem+'"]').first();await gem.locator('xpath=ancestor::*[contains(@class,"topic-section")]').locator('.topic-trigger').click();await gem.click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click()}
 else{await p.evaluate(gem=>location.hash=gem,f.gem);await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${f.ref.level}"]`).click()}
 await p.locator('.question-player').waitFor();await flush(p);
 if((await snap(p)).question.ref.questionId!==f.ref.questionId|| (await snap(p)).question.ref.level!==f.ref.level){await p.evaluate(async f=>{const s=window.__mastersActivity.snapshot(),{productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const a=productionRegistry.get(f.activity),provider=await a.provider();provider.restore(f.ref);const id=crypto.randomUUID(),target={...s.attempt.target,gemId:f.gem,level:f.ref.level},attempt={...s.attempt,attemptId:id,ref:f.ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{...s.attempt.timing,attemptId:id,activeMs:0,finished:false}};const session={...s.session,currentAttemptId:id,...(s.session.kind==='practice'?{target,previousQuestionIds:[f.ref.questionId]}:{})};const repo=createChemistryRepository(s.databaseName),saved=await repo.saveCurriculum({attempt,session,question:provider.restore(f.ref),namespace:attempt.namespace});if(!saved.ok)throw Error(JSON.stringify(saved));repo.close?.()},f);await p.reload();await p.locator('.source-player').waitFor();await flush(p)}
 assert.equal((await snap(p)).question.ref.questionId,f.ref.questionId);return p;
}
function answers(f){const out={};for(const part of f.question.parts){if(part.kind==='numeric')out[part.id]={kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit};if(part.kind==='text')out[part.id]={kind:'text',value:part.accepted[0]};if(part.kind==='choice')out[part.id]={kind:'choice',selected:part.acceptedOptionSets[0]};if(part.kind==='correction'){const s=part.segments.find(x=>x.id===f.source.practical.correction.errorId);out[part.id]={kind:'correction',selections:[s],replacement:f.source.practical.fields[0].answers[0]}}}return out}
async function fill(p,f,data){for(const part of f.question.parts){const r=data[part.id];if(!r)continue;if(r.kind==='numeric'){const inputs=p.locator('.response-input');await inputs.nth(f.question.parts.filter(x=>x.kind==='numeric').findIndex(x=>x.id===part.id)).fill(r.raw)}else if(r.kind==='text'){await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.value)}else if(r.kind==='choice'){const field=p.locator('.choice-field,.choice-box').filter({has:p.getByText(f.source.fields[part.id].label,{exact:true})});if(f.source.family==='practical'){for(const selected of r.selected)await field.getByText(selected,{exact:true}).click()}else{for(const selected of r.selected)await field.getByRole('button').filter({hasText:selected}).click()}}else if(r.kind==='correction'){await p.getByRole('button',{name:r.selections[0].text.trim(),exact:true}).click();await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.replacement)}}await flush(p)}
async function wrong(f,correct){const a=productionRegistry.get(f.activity),policy=await a.marking();for(const part of f.question.parts){const v=correct[part.id];const candidates=part.kind==='numeric'?['999999']:part.kind==='choice'?part.options.map(o=>o.id).filter(id=>!v.selected.includes(id)):part.kind==='correction'?['increases','wrong']:['0','1','2','3','4','5','6','proton','neutron','ionic','covalent','metallic','endothermic','exothermic','positive','negative','wrong'];for(const x of candidates){const copy=structuredClone(correct);copy[part.id]=v.kind==='numeric'?{...v,raw:x}:v.kind==='choice'?{...v,selected:v.selected.length===1?[x]:[x,...v.selected.slice(1)]}:v.kind==='correction'?{...v,replacement:x}:{...v,value:x};const outcome=policy.mark(f.question,copy);if(outcome.accepted&&outcome.marks.earned<outcome.marks.available)return copy}}throw Error('No meaningful wrong fixture '+f.ref.questionId)}

const {record:energyRecord}=await import('../../../../../src/activities/igcse/energy-enthalpy/provider.ts');const {bondingRecord}=await import('../../../../../src/activities/alevel/electrons-bonding/provider.ts');
async function written(c,f){const p=await c.newPage(),family=f.source.family;await p.goto('http://127.0.0.1:5197/'+f.course+'/activities/'+f.activity.split('/')[1]+'/index.html?'+(family==='bonding'?'mode=pupil&question='+bondingRecord(f.ref.questionId).id+'&leaf='+f.gem+'&level=1':'mode=pupil&practice=grade&grade='+f.ref.level));if(family==='energy'){await p.locator('#prompt').waitFor();const state=await p.evaluate(()=>JSON.parse(localStorage.getItem('sjs-energy-enthalpy-v2')));state.filter='grade'+f.ref.level;await p.addInitScript(({f,state,q})=>{localStorage.setItem('sjs-energy-enthalpy-v2',JSON.stringify(state));localStorage.setItem('sjs-energy-enthalpy-v2-attempt-'+state.filter,JSON.stringify({version:1,questionId:q.id,grade:f.ref.level,answers:[],editor:null,hinted:false,revealed:false,marked:null,completedAt:null,attemptId:'source-written-fixture'}))},{f,state,q:energyRecord(f.ref.questionId)});await p.reload()}await p.locator('#written').waitFor();assert.equal(await p.locator('#prompt').innerText(),f.question.context[0].text);return p}
async function write(p,f,r){for(const [i,part] of f.question.parts.entries()){const response=r[part.id];if(response.kind==='text')await p.locator('#answer-'+i).fill(response.value);else if(response.kind==='choice')await p.locator('#field-'+i+' .answer-option[data-value="'+response.selected[0]+'"]').click()}}
async function shotw(p,name){await p.evaluate(()=>document.fonts.ready);await p.locator('.workspace').screenshot({path:here+'/'+name+'.png'});report.shots.push(name+'.png')}
try{for(const size of ['desktop','tablet','mobile']){const viewport={desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}}[size];const picked=all.filter(f=>f.source.family==='bonding'||(f.source.family==='energy'&&!f.question.parts.some(p=>p.kind==='energy-profile')));for(const f of picked){const c=await b.newContext({viewport}),p=await written(c,f),good=answers(f),bad=await wrong(f,good),tag=size+'-'+f.ref.questionId;await shotw(p,'native-written-'+tag+'-unanswered');await write(p,f,bad);await p.locator('#check').click();await p.locator('#feedback').waitFor();await shotw(p,'native-written-'+tag+'-incorrect');await c.close();const cc=await b.newContext({viewport}),cp=await written(cc,f);await write(cp,f,good);await cp.locator('#check').click();await cp.locator('#feedback').waitFor();assert.equal(await cp.locator('#feedback .fail').count(),0);await shotw(cp,'native-written-'+tag+'-correct');await cc.close();report.checks.push({tag,nativeFinalController:true,promptExact:true,correctNativeMarks:true,nativeCorrection:'Native controller freezes fields after marking; shared learning correction is tested separately.'});console.log('PASS native written '+tag)}}report.status='PASS'}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(here+'/written-source-results.json',JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,shots:report.shots.length,failure:report.failure}))}
