import {suiteEvidenceFile} from '../../test-evidence.mjs';
const _migrationEvidence=(name)=>suiteEvidenceFile(import.meta.url,name);
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {calorimetryConfigurations,calorimetryCode,calorimetrySource,calorimetryRef,calorimetryProvider} from '../../../../../src/activities/igcse/calorimetry/provider.ts';
import {bondSource,bondCode,bondRef,bondProvider} from '../../../../../src/activities/igcse/bond-enthalpy/provider.ts';
import {calorimetryMarking} from '../../../../../src/activities/igcse/calorimetry/marking.ts';
import {bondMarking} from '../../../../../src/activities/igcse/bond-enthalpy/marking.ts';
import {workingFramework} from '../../../../../src/chemistry/thermochemistry/framework.ts';
import {createHash} from 'node:crypto';
import {reviewedMethanolSynthesisSVG} from '../../../../../src/chemistry/thermochemistry/reviewed-co-svg.ts';
import {svgImage} from '../../../../../src/chemistry/thermochemistry/presentation.ts';
const source=new URL('../../../../../../Masters-of-IGCSE-Chemistry/src/',import.meta.url),context={};vm.createContext(context);
for(const rel of ['assets/question-review.js','activities/calorimetry/data.js','activities/calorimetry/core.js','activities/bond-enthalpy/data.js','activities/bond-enthalpy/core.js','assets/generated-review.js'])vm.runInContext(fs.readFileSync(new URL(rel,source),'utf8'),context);
const sha=value=>createHash('sha256').update(value).digest('hex'),coReview=JSON.parse(fs.readFileSync(new URL('../../../fixtures/legacy/s3/review-co/provenance.json',import.meta.url),'utf8'));
assert.equal(coReview.status,'PASS');assert.equal(coReview.jobId,'S3-REVIEW-CO');assert.equal(coReview.agentId,'A07');
assert.equal(coReview.source.originalSvgSha256,'8290640db0821f819075df57ea3d85f2828fdb9139aa8721ef3e85a0802d4da7');assert.equal(coReview.correction.newSvgSha256,'02de76dd4029588cd04a591c7bb514fb2b6103f5ce96239e24543ec5babae2eb');
assert.equal(sha(context.BondEnthalpyData.reactions.find(r=>r.id==='methanol-synthesis').svg),coReview.source.originalSvgSha256);assert.equal(sha(reviewedMethanolSynthesisSVG),coReview.correction.newSvgSha256);
assert.equal(sha(fs.readFileSync(new URL('../../../../../src/chemistry/thermochemistry/reviewed-co-svg.ts',import.meta.url))),coReview.correction.outputSha256);assert.equal(sha(fs.readFileSync(new URL('../../../../../src/chemistry/thermochemistry/bond-enthalpy-data.js',import.meta.url))),coReview.source.copiedDataFileSha256);
assert.equal(sha(fs.readFileSync(new URL('activities/bond-enthalpy/data.js',source))),coReview.source.fileSha256);assert.equal(reviewedMethanolSynthesisSVG.replace(coReview.correction.insertedElement,''),context.BondEnthalpyData.reactions.find(r=>r.id==='methanol-synthesis').svg);
const inventory=JSON.parse(fs.readFileSync(new URL('../../../../../resources/source-generation/inventory/coverage-manifest.json',import.meta.url),'utf8')).activities;
const calInventory=inventory.find(a=>a.id==='igcse/calorimetry'),bondInventory=inventory.find(a=>a.id==='igcse/bond-enthalpy');
const configs=calorimetryConfigurations();assert.equal(configs.length,4512);assert.deepEqual(configs.map(c=>({level:c.difficulty,exampleId:c.example,target:c.target,massRoute:c.massRoute,amountRoute:c.amountRoute,temperatureRoute:c.temperatureRoute,structure:c.structure})),calInventory.finiteGeneratorConfigurations.entries);
const plain=x=>JSON.parse(JSON.stringify(x)),close=(actual,expected)=>assert(Math.abs(actual-expected)<=1e-10*Math.max(1,Math.abs(expected)),`${actual} versus ${expected}`),num=s=>Number(String(s).match(/[-+]?\d+(?:\.\d+)?/)[0]);
let outputs=0,moleChecks=0,frameworks=0;
function independentCal(r){const v=r.values,rows=Object.fromEntries(r.rows),e=context.CalorimetryReviewData.examples.find(e=>e.id===r.example.id),c=r.config;
 let mass=v.mass;if(c.massRoute==='direct')mass=num(rows[e.setup==='combustion'?'Mass of water':'Mass of reaction mixture']);if(c.massRoute==='single-volume')mass=num(rows['Volume of '+(e.setup==='combustion'?'water':e.solution||'solution')])*num(rows['Density of '+(e.setup==='combustion'?'water':e.solution||'solution')]);if(c.massRoute==='sum-volumes')mass=(num(rows['Volume of '+e.solutionA])+num(rows['Volume of '+e.solutionB]))*num(rows['Density of both solutions']);if(c.massRoute==='water-solid')mass=num(rows['Mass of water'])+num(rows['Mass of '+e.solid]);close(v.mass,mass);close(v.final-v.initial,v.deltaT);close(v.q,mass*4.2*v.deltaT);assert.equal(v.qReported,Number(v.q.toPrecision(3)));assert.equal(Math.sign(v.q),e.sign);
 if(c.target==='dh'){let n;const substance=e.setup==='combustion'||e.group==='dissolving'?e.name.replace(' dissolving',''):e.metal,formula=e.setup==='combustion'||e.group==='dissolving'?e.formula:e.metalFormula;
  if(c.amountRoute==='given')n=num(rows['Amount of '+e.basis]);
  if(c.amountRoute==='mass')n=num(rows['Mass of '+substance])/num(rows['Mᵣ of '+formula]);
  if(c.amountRoute==='burner-loss')n=Number((num(rows['Initial mass of burner and fuel'])-num(rows['Final mass of burner and fuel'])).toFixed(2))/num(rows['Mᵣ of '+e.formula]);
  if(c.amountRoute==='fuel-volume')n=num(rows['Volume of '+e.name+' burned'])*num(rows['Density of '+e.name])/num(rows['Mᵣ of '+e.formula]);
  if(c.amountRoute==='concentration'){const f=e.group==='neutralisation'?e.formulaA:e.solutionFormula,s=e.group==='neutralisation'?e.solutionA:e.solution; n=num(rows['Concentration of '+f])*num(rows['Volume of '+s])/1000/(e.group==='neutralisation'?e.coeffA:e.solutionCoeff);}
  if(c.amountRoute==='limiting'){if(e.group==='neutralisation'){const vals=[rows[e.formulaA],rows[e.formulaB]].map(s=>[...s.matchAll(/\d+(?:\.\d+)?/g)].map(m=>Number(m[0])));n=Math.min(vals[0][0]*vals[0][1]/1000/e.coeffA,vals[1][0]*vals[1][1]/1000/e.coeffB);}else n=Math.min(num(rows['Mass of '+e.metal])/num(rows['Mᵣ of '+e.metalFormula]),num(rows['Concentration of '+e.solutionFormula])*num(rows['Volume of '+e.solution])/1000/e.solutionCoeff);}
  close(v.n,n);close(v.dh,-mass*4.2*v.deltaT/1000/n);assert.equal(v.dhReported,Number(v.dh.toPrecision(3)));moleChecks++;
 }
}
for(const config of configs)for(const seed of [0,7,411,0xffffffff]){const original=context.CalorimetryReviewCore.generate(config,seed),code=calorimetryCode(config,seed);assert.equal(code,original.reviewId);const r=calorimetrySource(code);const copy=plain(original);delete copy.reviewId;assert.deepEqual(plain(r),copy);independentCal(r);const q=calorimetryProvider.restore(calorimetryRef(code));assert.equal(q.parts.length,r.responses.length);const answers=Object.fromEntries(r.responses.map(p=>[p.key,{kind:'numeric',unit:p.unit,raw:String(p.expected)}]));assert.equal(calorimetryMarking.masteryScore(calorimetryMarking.mark(q,answers).marks),1);assert.equal(calorimetryMarking.mark(q,{}).accepted,false);for(const [i,p] of q.parts.entries()){const f=workingFramework(r.answerParts[i],`working-${p.id}`);assert.deepEqual(p.workingFramework,f);const fields=f.rows.flatMap(row=>row.right.kind==='tokens'?row.right.tokens:[...row.right.numerator,...row.right.denominator]).filter(t=>typeof t!=='string');assert.equal(fields.filter(f=>f.finalResponse).length,1);assert(fields.every(f=>Number.isFinite(f.expected)&&f.tolerance>0));frameworks++;}outputs++;}
function atoms(side){const totals={};const digits={'₀':'0','₁':'1','₂':'2','₃':'3','₄':'4','₅':'5','₆':'6','₇':'7','₈':'8','₉':'9'};for(const term of side.split(' + ')){const ascii=term.replace(/[₀-₉]/g,c=>digits[c]),coefficient=Number(ascii.match(/^\d+/)?.[0]||1),formula=ascii.replace(/^\d+/,'');for(const m of formula.matchAll(/([A-Z][a-z]?)(\d*)/g))totals[m[1]]=(totals[m[1]]||0)+coefficient*Number(m[2]||1);}return Object.fromEntries(Object.entries(totals).sort());}
let bonds=0;const routes=[];
assert.equal(context.BondEnthalpyData.reactions.length,16);
for(const level of [1,2,3]){assert.deepEqual(plain(context.BondEnthalpyData.reactions.filter(r=>r.allowedLevels.includes(level)).map(r=>r.id)),bondInventory.levelMapping[level].sourceIds);for(const reaction of context.BondEnthalpyData.reactions){const [left,right]=reaction.equation.split(' → ');assert.deepEqual(atoms(left),atoms(right),reaction.id);for(const [rows,total] of [[reaction.broken,reaction.brokenTotal],[reaction.made,reaction.madeTotal]]){assert.equal(rows.reduce((sum,r)=>sum+r.count*r.energy,0),total);for(const row of rows)assert.equal(row.subtotal,row.count*row.energy);}assert.equal(reaction.deltaH,reaction.brokenTotal-reaction.madeTotal);
 if(!reaction.allowedLevels.includes(level)){assert.throws(()=>bondCode(reaction.id,level,7));continue;}
 const seen=new Set();for(let seed=0;seed<128;seed++){const original=context.BondEnthalpyReviewCore.generate({reaction:reaction.id,difficulty:level},seed),code=bondCode(reaction.id,level,seed);assert.equal(code,original.reviewId);const r=bondSource(code),copy=plain(original);delete copy.reviewId;assert.deepEqual(plain(r),copy);seen.add(r.questionType);if(r.unknownBond){const u=r.unknownBond,knownBroken=reaction.brokenTotal-(u.side==='broken'?u.count*u.energy:0),knownMade=reaction.madeTotal-(u.side==='made'?u.count*u.energy:0);close((u.side==='broken'?reaction.deltaH+knownMade-knownBroken:knownBroken-knownMade-reaction.deltaH)/u.count,u.energy);}const q=bondProvider.restore(bondRef(code)),answers=Object.fromEntries(r.responses.map(p=>[p.key,{kind:'numeric',unit:p.unit,raw:String(p.expected)}]));assert.equal(bondMarking.mark(q,answers).marks.earned,r.responses.length);assert.equal(q.parts.filter(p=>p.kind==='drawing-self-check').length,level===3?1:0);
 const expectedImage=svgImage(reaction.id==='methanol-synthesis'?reviewedMethanolSynthesisSVG:reaction.svg,reaction.description);const imageBlocks=[...q.context,...q.workedAnswer,...q.hints.flatMap(h=>h.content),...q.parts.flatMap(p=>p.kind==='drawing-self-check'?p.model:[])].filter(b=>b.kind==='image');assert(imageBlocks.length>=1);for(const image of imageBlocks)assert.deepEqual(image,expectedImage);bonds++;}assert.deepEqual([...seen].sort(),level===1?['enthalpy-change']:['enthalpy-change','unknown-bond']);routes.push({level,reaction:reaction.id,families:[...seen].sort()});}}
for(const [provider,activityId,gemId] of [[calorimetryProvider,'igcse/calorimetry','lower-10-3'],[bondProvider,'igcse/bond-enthalpy','lower-10-4']])for(const level of [1,2,3]){const previousQuestionIds=[];for(let seed=0;seed<128;seed++){const ref=provider.select({activityId,gemId,level,seed,previousQuestionIds});assert.deepEqual(provider.resolveLink(ref.questionId),ref);assert.equal(provider.restore(ref).ref.level,level);previousQuestionIds.push(ref.questionId);}}
fs.writeFileSync(_migrationEvidence('./coverage-results.json'),JSON.stringify({status:'PASS',finiteConfigurations:configs.length,calorimetryOutputs:outputs,independentMoleChecks:moleChecks,frameworkChecks:frameworks,bondOutputs:bonds,bondRoutes:routes,checked:'Complete original equality, mixed-radix historical identity, independent mass/moles/Q/ΔH and balanced atom counts, level exclusions, unknown-bond rearrangement, framework last-final mapping; source SVGs preserved'},null,2));
console.log(JSON.stringify({status:'PASS',finiteConfigurations:configs.length,calorimetryOutputs:outputs,moleChecks,frameworks,bondOutputs:bonds}));
