import {chromium} from '../../../../../node_modules/playwright/index.mjs';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {propertiesBank} from '../../../src/activities/alevel/explaining-properties/bank.ts';
const here=import.meta.dirname,run='ebp-independent-'+Date.now(),base='http://127.0.0.1:5197',report={jobId:'EBP-REVIEW',startedAt:new Date().toISOString(),checks:[],errors:[]};
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot());
async function fixture(code){const record=propertiesBank.find(r=>r.code===code);await page.goto(`${base}/alevel.html?run=${run}-${code}&view=practice&activity=alevel/explaining-properties`);await page.waitForFunction(()=>window.__mastersActivity);
 await page.evaluate(async code=>{const {productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const reg=productionRegistry.get('alevel/explaining-properties'),provider=await reg.provider(),ref=provider.resolveLink(code),id=crypto.randomUUID(),namespace={course:'alevel',profileId:'local'},target={course:'alevel',activityId:reg.id,gemId:reg.gems[0].id,level:ref.level},session={kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:id,previousQuestionIds:[],paused:false},attempt={mode:'student',namespace,attemptId:id,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:180000,finished:false}};const saved=await createChemistryRepository(window.__mastersActivity.snapshot().databaseName).saveCurriculum({attempt,session});if(!saved.ok)throw Error(saved.error.message);},code);
 await page.reload();await page.locator('.question-player').waitFor();await page.waitForFunction(code=>window.__mastersActivity.snapshot().attempt?.ref.questionId===code,code);return record;}
try{
 for(const code of ['EBP-K7M2Q9','EBP-C6R2Y8','EBP-S8L4J2','EBP-I5B9S3']){const r=await fixture(code);await page.screenshot({path:path.join(here,code+'-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(here,code+'-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  if(r.format==='gaps'){const input=page.getByLabel('Gap 1',{exact:true});await input.focus();await page.keyboard.type('incorrect');await page.keyboard.press('Tab');assert(await page.getByLabel('Gap 2',{exact:true}).evaluate(el=>document.activeElement===el));for(let i=0;i<r.answers.length;i++)await page.getByLabel('Gap '+(i+1),{exact:true}).fill('incorrect');}
  else{await page.locator('[data-error-id="phrase-0"]').focus();await page.keyboard.press('Space');assert.equal(await page.locator('[data-error-id="phrase-0"]').getAttribute('aria-pressed'),'true');await page.locator(`[data-error-id="phrase-${r.errorIndex}"]`).click();await page.getByLabel('Replacement / correction',{exact:true}).fill('incorrect');}
  await page.getByRole('button',{name:'Check',exact:true}).click();await page.locator('.assessment-feedback').waitFor();await page.evaluate(()=>window.__mastersActivity.flush());const first=await snap(),history=await page.evaluate(()=>window.__mastersActivity.history());assert.equal(history.length,1);assert.equal(first.attempt.firstAssessment.marks.earned,r.format==='gaps'?0:1);
  if(r.format==='gaps'){for(let i=0;i<r.answers.length;i++)await page.getByLabel('Gap '+(i+1),{exact:true}).fill(r.answers[i][0]);}else await page.getByLabel('Replacement / correction',{exact:true}).fill(r.answers[0][0]);await page.getByRole('button',{name:'Check',exact:true}).click();await page.locator('.correction-feedback').waitFor();await page.evaluate(()=>window.__mastersActivity.flush());assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),history);assert.deepEqual((await snap()).attempt.firstResponse,first.attempt.firstResponse);report.checks.push({id:code+'-desktop-mobile-keyboard-wrong-first-retry',status:'PASS'});await page.setViewportSize({width:1440,height:1000});
 }
 for(const code of ['EBP-U4C8Q6','EBP-Z3R6F8','EBP-H6Z4N9','EBP-D8O2Y7']){const r=propertiesBank.find(r=>r.code===code);await page.goto(`${base}/alevel.html?run=${run}-teacher&activity=alevel/explaining-properties&review=${code}&level=${r.level}&seed=0`);await page.locator('.teacher-answer').waitFor();assert.equal(await page.locator('.header-question-code').innerText(),code);assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,0);await page.screenshot({path:path.join(here,code+'-teacher.png'),fullPage:true});report.checks.push({id:code+'-teacher-render-no-evidence',status:'PASS'});}
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;await page.screenshot({path:path.join(here,'browser-failure.png'),fullPage:true}).catch(()=>{});}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-sample.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify(report));}
