import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import vm from 'node:vm';import{createRequire}from'node:module';
import{bank,reviewCode,titrationProvider}from '../../../../src/activities/alevel/ph-titration-curves/provider.ts';
import{answer,curve,grade,initial}from '../../../../src/chemistry/titration-curve/core.js';
import{checkSubmission}from '../../../../src/chemistry/titration-curve/engine.ts';
const here=import.meta.dirname,require=createRequire(path.resolve('package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.resolve('apps/Masters-of-Chemistry/.f06-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});
const report={jobId:'F2-TITRATION',agentId:'F06',startedAt:new Date().toISOString(),status:'RUNNING',checks:[],screenshots:[],metrics:[],errors:[],limits:['Headless Edge/pinned root Playwright 1.62.1; no native OS hidden/suspension claim.','Source interactions occur in fresh nonpersistent synthetic browser contexts.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,label){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(here,label+'.png'),fullPage:true});report.screenshots.push(label+'.png');}
async function start(c,q,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:5188/alevel.html?run=f06-'+Date.now()+'-'+Math.random().toString(36).slice(2));await p.locator('.original-landing').waitFor();
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();await p.locator('[data-topic="u6-topic-1"] .topic-trigger').click();await p.locator('[data-leaf="u6-t1-1-9"]').click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click();}
 else{await p.evaluate(()=>location.hash='u6-t1-1-9');await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator('a.practice-choice[data-practice="'+q.level+'"]').click();}
 await p.locator('.tc-chart').waitFor();await flush(p);if((await snap(p)).question.ref.questionId!==reviewCode(q.id)){
 await p.evaluate(async({qid,level})=>{const s=window.__mastersActivity.snapshot();const{titrationProvider}=await import('/src/activities/alevel/ph-titration-curves/provider.ts');const{createChemistryRepository}=await import('/src/persistence/index.ts');const ref={...s.question.ref,questionId:qid,level};const question=titrationProvider.restore(ref);const newId=crypto.randomUUID();const attempt={...s.attempt,attemptId:newId,timing:{...s.attempt.timing,attemptId:newId,activeMs:0},ref,target:{...s.attempt.target,level},currentResponses:{},phase:'answering'};const session={...s.session,currentAttemptId:newId,target:attempt.target,previousQuestionIds:[qid]};const repo=createChemistryRepository(s.databaseName);const r=await repo.saveCurriculum({attempt,session});repo.close();if(!r.ok)throw Error(r.error.message);},{qid:reviewCode(q.id),level:q.level});await p.reload();await p.locator('.tc-chart').waitFor();await flush(p);}
 assert.equal((await snap(p)).question.ref.questionId,reviewCode(q.id));return p;
}
async function set(p,q,wrong=false){const a=answer(q);await p.locator('[data-piece="'+a.before+'"]').click();await p.locator('[data-piece="'+a.after+'"]').click();await p.locator('.tc-alternatives summary').click();for(const[label,val]of[['Initial pH',a.initialPH],['Equivalence volume / cm\u00b3',a.equivalenceVolume+(wrong?2:0)],['Final pH',a.finalPH]]){await p.getByLabel(label,{exact:true}).fill(String(val));await p.getByLabel(label,{exact:true}).press('Enter');}await p.locator('[data-indicator="'+a.indicator+'"]').click();await p.locator('.tc-alternatives summary').click();await flush(p);}
async function source(c,q,state){const p=await c.newPage();p.on('pageerror',e=>report.errors.push('source: '+e.message));await p.goto('http://127.0.0.1:5197/alevel/activities/ph-titration-curves/index.html?level='+q.level);await p.locator('#curve-chart').waitFor();await originalState(p,q,state);return p;}
async function originalState(p,q,state){await p.evaluate(({qid,state})=>TitrationActivity.loadQuestion(qid,state),{qid:q.id,state});}
function response(q,wrong=false){return{...answer(q),equivalenceVolume:answer(q).equivalenceVolume+(wrong?2:0)}}
try{
 const sourceCore=vm.createContext({});vm.runInContext(fs.readFileSync('apps/Masters-of-A-Level-Chemistry/src/activities/ph-titration-curves/core.js','utf8'),sourceCore);
 for(const q of bank){const a=answer(q);assert.equal(grade(q,a).score,1);assert.deepEqual(JSON.parse(JSON.stringify(sourceCore.TitrationCore.answer(q))),a);assert.deepEqual(JSON.parse(JSON.stringify(sourceCore.TitrationCore.curve(q,a))),curve(q,a));const ref={activityId:'alevel/ph-titration-curves',questionId:reviewCode(q.id),seed:3,level:q.level};assert.equal(titrationProvider.restore(ref).ref.questionId,ref.questionId);assert.equal(checkSubmission(q,{kind:'titration-curve',...a}).status,'ready');}report.checks.push({name:'all36 source-equilibrium/model/grade/submission/canonical-ID fixtures',status:'PASS'});
 const selected=[0,4,8,12,15,18,21].map(i=>bank[i]);
 for(const[size,viewport]of Object.entries({desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}})){
 for(const q of selected){const c=await b.newContext({viewport,hasTouch:size==='mobile'}),oc=await b.newContext({viewport,hasTouch:size==='mobile'}),p=await start(c,q),o=await source(oc,q,initial(q));const tag=size+'-'+reviewCode(q.id);
 await shot(p,'react-'+tag+'-unanswered');await shot(o,'original-'+tag+'-unanswered');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const info=async(p,selector)=>p.locator(selector).first().evaluate(e=>{const s=getComputedStyle(e);return{fontFamily:s.fontFamily,fontSize:s.fontSize,lineHeight:s.lineHeight,color:s.color,border:s.border,background:s.backgroundColor}});report.metrics.push({tag,react:await info(p,'.piece-choice'),original:await info(o,'.piece-choice')});
 await p.locator('[data-piece="'+q.before+'"]').click();await flush(p);await originalState(o,q,{...initial(q),before:q.before});await shot(p,'react-'+tag+'-partial');await shot(o,'original-'+tag+'-partial');
 await set(p,q,true);await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await flush(p);const first=await snap(p);assert.equal(first.attempt.firstAssessment.marks.earned,5);assert(first.attempt.firstResponse.timing.activeMs>0);const wrong=response(q,true);await originalState(o,q,{...wrong,checked:true,attempted:true,result:grade(q,wrong)});assert.notEqual(await p.locator('.curve-before').evaluate(e=>getComputedStyle(e).stroke),'none');assert.notEqual(await p.locator('.curve-after').evaluate(e=>getComputedStyle(e).stroke),'none');assert.notEqual(await p.locator('.guide-eq').evaluate(e=>getComputedStyle(e).stroke),'none');await shot(p,'react-'+tag+'-incorrect');await shot(o,'original-'+tag+'-incorrect');
 await set(p,q);await p.getByRole('button',{name:'Check correction',exact:true}).click();await p.locator('.correction-feedback').waitFor();await flush(p);assert.equal((await snap(p)).correctionFeedback.marks.earned,6);assert.deepEqual((await snap(p)).attempt.firstAssessment,first.attempt.firstAssessment);assert.deepEqual((await snap(p)).attempt.firstResponse,first.attempt.firstResponse);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);await originalState(o,q,{...answer(q),checked:true,attempted:true,result:grade(q,answer(q))});await shot(p,'react-'+tag+'-correction');await shot(o,'original-'+tag+'-correction');
 await p.getByRole('button',{name:'Show worked answer',exact:true}).click();await p.locator('.worked-answer').waitFor();await originalState(o,q,{...answer(q),revealed:true,assisted:true,attempted:true});await shot(p,'react-'+tag+'-model');await shot(o,'original-'+tag+'-model');await p.reload();await p.locator('.tc-chart').waitFor();await flush(p);assert.equal((await snap(p)).attempt.attemptId,first.attempt.attemptId);assert.deepEqual((await snap(p)).attempt.firstAssessment,first.attempt.firstAssessment);
 const cc=await b.newContext({viewport}),correct=await start(cc,q);await set(correct,q);await correct.getByRole('button',{name:'Check answer',exact:true}).click();await correct.locator('.assessment-feedback').waitFor();await flush(correct);assert.equal((await snap(correct)).attempt.firstAssessment.marks.earned,6);await originalState(o,q,{...answer(q),checked:true,attempted:true,result:grade(q,answer(q))});await shot(correct,'react-'+tag+'-correct');await shot(o,'original-'+tag+'-correct');await cc.close();
 report.checks.push({tag,states:['unanswered','partial','incorrect','correct','correction','model'],restoredSameAttempt:true,firstResponseMarksTimeFrozen:true,historyOne:true,status:'PASS'});console.log('PASS '+tag);await c.close();await oc.close();}
 }
 report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1;}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));await b.close();}

