import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import vm from 'node:vm';import{createRequire}from'node:module';
import{bank,reviewCode,titrationProvider}from '../../../../src/activities/alevel/ph-titration-curves/provider.ts';
import{answer,curve,grade,initial}from '../../../../src/chemistry/titration-curve/core.js';
import{checkSubmission}from '../../../../src/chemistry/titration-curve/engine.ts';
const here=import.meta.dirname,require=createRequire(path.resolve('package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.resolve('apps/Masters-of-Chemistry/.f06-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});
const report={jobId:'F2-TITRATION',agentId:'F06',startedAt:new Date().toISOString(),status:'RUNNING',checks:[],screenshots:[],metrics:[],errors:[],limits:['Headless Edge/pinned root Playwright 1.62.1; no native OS hidden/suspension claim.','Source interactions occur in fresh nonpersistent synthetic browser contexts.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,label){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(here,label+'.png'),fullPage:true});report.screenshots.push(label+'.png');}
async function start(c,q,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:5188/alevel.html?run=f06-'+Date.now()+'-'+Math.random().toString(36).slice(2));await p.locator('.original-landing').waitFor();
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();await p.locator('#flipYear').click();await p.locator('[data-topic="u6-t1-topic-1"] .topic-trigger').click();await p.locator('[data-leaf="u6-t1-1-9"]').click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click();}
 else{await p.evaluate(()=>location.hash='u6-t1-1-9');await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator('a.practice-choice[data-practice="'+q.level+'"]').click();}
 await p.locator('.tc-chart').waitFor();await flush(p);if((await snap(p)).question.ref.questionId!==reviewCode(q.id)){
 await p.evaluate(async({qid,level})=>{const s=window.__mastersActivity.snapshot();const{titrationProvider}=await import('/src/activities/alevel/ph-titration-curves/provider.ts');const{createChemistryRepository}=await import('/src/persistence/index.ts');const ref={...s.question.ref,questionId:qid,level};const question=titrationProvider.restore(ref);const newId=crypto.randomUUID();const attempt={...s.attempt,attemptId:newId,timing:{...s.attempt.timing,attemptId:newId,activeMs:0},ref,target:{...s.attempt.target,level},currentResponses:{},phase:'answering'};const session={...s.session,currentAttemptId:newId,target:attempt.target,previousQuestionIds:[qid]};const repo=createChemistryRepository(s.databaseName);const r=await repo.saveCurriculum({attempt,session});repo.close();if(!r.ok)throw Error(r.error.message);},{qid:reviewCode(q.id),level:q.level});await p.reload();await p.locator('.tc-chart').waitFor();await flush(p);}
 assert.equal((await snap(p)).question.ref.questionId,reviewCode(q.id));return p;
}
async function set(p,q,wrong=false){const a=answer(q);await p.locator('[data-piece="'+a.before+'"]').click();await p.locator('[data-piece="'+a.after+'"]').click();await p.locator('.tc-alternatives summary').click();for(const[label,val]of[['Initial pH',a.initialPH],['Equivalence volume / cm\u00b3',a.equivalenceVolume+(wrong?2:0)],['Final pH',a.finalPH]]){await p.getByLabel(label,{exact:true}).fill(String(val));await p.getByLabel(label,{exact:true}).press('Enter');}await p.locator('[data-indicator="'+a.indicator+'"]').click();await p.locator('.tc-alternatives summary').click();await flush(p);}
async function source(c,q,state){const p=await c.newPage();p.on('pageerror',e=>report.errors.push('source: '+e.message));await p.goto('http://127.0.0.1:5197/alevel/activities/ph-titration-curves/index.html?level='+q.level);await p.locator('#curve-chart').waitFor();await originalState(p,q,state);return p;}
async function originalState(p,q,state){await p.evaluate(({qid,state})=>TitrationActivity.loadQuestion(qid,state),{qid:q.id,state});}
function response(q,wrong=false){return{...answer(q),equivalenceVolume:answer(q).equivalenceVolume+(wrong?2:0)}}
try{
const revC=await b.newContext({viewport:{width:1440,height:1000}}),r=await start(revC,bank[0],'revision');await set(r,bank[0]);await flush(r);const rs=await snap(r);assert.equal(rs.session.kind,'revision');await r.reload();await r.locator('.tc-chart').waitFor();await flush(r);assert.equal((await snap(r)).attempt.attemptId,rs.attempt.attemptId);assert.deepEqual((await snap(r)).attempt.currentResponses,rs.attempt.currentResponses);await r.getByRole('button',{name:'Check answer',exact:true}).click();await r.locator('.assessment-feedback').waitFor();await flush(r);const rf=await snap(r);assert.equal(rf.attempt.firstAssessment.marks.earned,6);await r.getByRole('button',{name:'Next question',exact:true}).click();await r.waitForFunction(id=>window.__mastersActivity.snapshot().attempt?.attemptId!==id,rf.attempt.attemptId);await flush(r);assert.equal((await snap(r)).session.kind,'revision');assert.equal((await snap(r)).attempt.phase,'answering');report.checks.push({name:'actual revision selection/launch/restoration/assessment/scheduler Next',status:'PASS'});await revC.close();report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1;}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'interaction-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify(report.checks));}

