import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { currentInputs } from '../../../scripts/current-inputs.mjs';
const here=import.meta.dirname,app=path.resolve(here,'../../..');
const json=file=>JSON.parse(fs.readFileSync(path.join(here,file),'utf8'));
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const contractSha256=hash(fs.readFileSync(path.join(app,'ui-consistency-contract.json')));
assert.equal(contractSha256,hash(fs.readFileSync(path.join(here,'before/ui-consistency-contract.json'))),'Root-owned requirements changed');
const build=json('build-and-release.json'),audit=json('source-audit.json'),originals=json('original-preservation.json');
for(const report of [build,audit,originals,json('regression-results.json'),json('assets-config-preservation.json'),json('timing-continuity.json')])assert.equal(report.status,'PASS');
const inputs=currentInputs(),sourceInputs=inputs.filter(row=>!row.path.startsWith('dist/')&&!row.path.startsWith('release/'));
assert.deepEqual(sourceInputs,build.sourceInputsAfter,'Source changed after final build');
const workers=['controls','theme','olympiad'].map(folder=>({folder,manifest:json(folder+'/completion.json')}));
for(const worker of workers)assert.equal(worker.manifest.status,'PASS');
for(const row of json('controls/source-fingerprints.json').files)assert.equal(hash(fs.readFileSync(path.join(app,row.path))),row.sha256,row.path);
for(const row of json('theme/changed-files.json'))assert.equal(hash(fs.readFileSync(path.join(app,'src',row.path))),row.afterSha256,row.path);
const browserReports=['controls/browser-results.json','controls/app-browser-results.json','theme/browser-results.json','theme/static-results.json','theme/transition-cancellation-results.json','theme/ec-axis-source-results.json','theme/ec-axis-static-results.json','olympiad/browser-report.json'];
for(const file of browserReports){const report=json(file);if(report.status!==undefined)assert.equal(report.status,'PASS',file);assert.equal(report.errors?.length??report.pageErrors?.length??0,0,file);if(report.checks)assert(report.checks.every(c=>c.status===undefined||c.status==='PASS'),file);}
const closure={status:'PASS',at:new Date().toISOString(),currentInputCount:inputs.length,sourceInputCount:sourceInputs.length,treeSha256:hash(JSON.stringify(inputs)),inputs};
fs.writeFileSync(path.join(here,'current-inputs.json'),JSON.stringify(closure,null,2)+'\n');
const walk=directory=>fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?entry.name==='before'?[]:walk(path.join(directory,entry.name)):[path.join(directory,entry.name)]);
const excluded=new Set(['foreman-report.json','evidence-fingerprints.json']);
const evidence=walk(here).filter(file=>!excluded.has(path.basename(file))).sort().map(file=>{const bytes=fs.readFileSync(file);return{path:path.relative(app,file).replaceAll('\\','/'),bytes:bytes.length,sha256:hash(bytes)};});
fs.writeFileSync(path.join(here,'evidence-fingerprints.json'),JSON.stringify({at:new Date().toISOString(),files:evidence},null,2)+'\n');
const report={runId:'UI-CONSISTENCY-20261003',stage:'U1',status:'VALIDATED_AWAITING_ROOT_CODE_RENDER_GATE',owner:'U01',at:new Date().toISOString(),contractSha256,jobs:workers.map(w=>({agentId:w.manifest.agentId,jobId:w.manifest.jobId,status:'FOREMAN_VALIDATED',manifest:`validation/ui-consistency/u1/${w.folder}/completion.json`,requestedModel:'gpt-6.1-sol',requestedEffort:'high',effectiveSettings:'unknown',usage:'not exposed'})),
 source:{files:audit.sourceFiles,unchanged:audit.unchanged,modifiedExisting:audit.changed.filter(r=>r.beforeSha256).length,new:audit.changed.filter(r=>!r.beforeSha256).length,changed:audit.changed,patch:'validation/ui-consistency/u1/source-changes.patch',baseline:'validation/ui-consistency/u1/before/src',chemicalContent:'Providers/marking/policies/content/identity/timing byte-identical; UI/editor presentation only, plus four centralized clear/current-action/persistence files.'},
 implementation:{controls:'One shared question-end footer and pure action state across source/generic/dot players. Clear is one central command; persisted currentResponseChanged/currentGiveUp markers invalidate stale highlight through reload without changing immutable first evidence. Required self-rubric/drawing stages stay gated. Editor-local tools remain supporting UI.',theme:'Exact landing background applied once, all UI/live text Comfortaa,1120px default pane; dot full-width exceptions removed.110+110ms opacity/16px directional course change, reduced-motion immediate; existing650ms L6/U6 flip unchanged. EC energy-axis clipping corrected with scoped CSS.',olympiad:'One genuine faceted completion gem per existing challenge; current validated fingerprints/contributions determine dim/partial/full, independent of curriculum evidence. Both stores reload on map return. Existing staged controls retained/restyled.'},
 validation:{distinctRetainedUnitTests:53,suites:{centralAndTiming:12,canonicalContentPersistenceWorking:14,controlState:5,olympiadSelectorChemistry:22},browserReports,mainThemeMeasurements:66,settledStaticFrames:23,postFixEcFrames:3,olympiadResponsiveChecks:24,olympiadFullpageScreenshots:26,controlFamilies:11,controlViewportWidths:[1280,768,390],themeViewportWidths:[1440,820,390,350],typeAndBuild:build.checks,releases:build.releases,originals,immutableAssetsAndConfig:'validation/ui-consistency/u1/assets-config-preservation.json',timingContinuity:'validation/ui-consistency/u1/timing-continuity.json'},
 renderedReview:{foremanInspected:['theme/static-alevel-dot-and-cross-390.png','theme/static-alevel-electrons-bonding-1440.png','theme/contact-final-390.png','theme/ec-axis-detail-static-390.png','olympiad/map-partial-1440.png','olympiad/contact-sheet.png','controls-contact.png'],rootStartHere:['theme/contact-final-1440.png','theme/contact-final-390.png','theme/ec-axis-detail-static-390.png','controls/screens/actual-app-reload.png','olympiad/map-unstarted-1440.png','olympiad/map-partial-1440.png','olympiad/map-complete-1440.png','olympiad/isomers-390.png','olympiad/c3-a-1440.png'],scope:'Fullsize exports and contact sheets retained. Final EC frames supersede pre-fix EC static images; all other scoped family images remain applicable.'},
 closure:{currentInputs:'validation/ui-consistency/u1/current-inputs.json',treeSha256:closure.treeSha256,currentInputCount:inputs.length,sourceInputCount:sourceInputs.length,evidenceFingerprints:'validation/ui-consistency/u1/evidence-fingerprints.json',evidenceCount:evidence.length},
 evidenceProcessException:{owner:'U03',action:'Legacy protect-originals guard once at22:11:22UTC overwrote mutable validation/original-app-check.json and attempted523 placeholder reads; all failed, no hydration or original changes.',disposition:'Root explicitly accepted bounded generated-summary exception. No exact raw backup exists; no reconstruction/restoration. New stat-only794hash+523metadata guard authoritative. Other history immutable.',evidence:'validation/ui-consistency/u1/theme/legacy-original-check-incident.json'},
 unresolved:[],limits:['Root U1 code/render acceptance and independent U2 review still required; U2 not dispatched.','Real headless Edge/emulated widths; no new native OS foreground/suspension, physical-device or screen-reader certification. Unchanged clock/binding plus retained native evidence applies.','EC final containment fixture is canonical teacher-preview energy representation; shared UI geometry also covered in practice family/browser checks.','Current correction checks remain transient learning feedback; first result/timing immutable and Next access persisted. No new independent evidence for corrections.','Usage/model effectiveness not exposed; requested settings recorded, no invented accounting.'],published:false};
fs.writeFileSync(path.join(here,'foreman-report.json'),JSON.stringify(report,null,2)+'\n');
const progressFile=path.join(app,'ui-consistency-progress.json'),progress=JSON.parse(fs.readFileSync(progressFile,'utf8'));
progress.status='awaiting_root_U1_gate';progress.currentStage='U1';progress.stages.U1='validated_awaiting_root_code_render_gate';progress.stages.U2='pending_root_gate';progress.jobs=report.jobs;progress.evidence='validation/ui-consistency/u1/foreman-report.json';progress.currentInputTree=closure.treeSha256;progress.unresolved=[];progress.updatedAt=report.at;progress.nextAction='Root reviews current shared patches and rendered exports; authorize independent U2 only after U1 gate.';
fs.writeFileSync(progressFile,JSON.stringify(progress,null,2)+'\n');
console.log(JSON.stringify({status:report.status,jobs:report.jobs.length,sourceInputs:sourceInputs.length,currentInputs:inputs.length,evidence:evidence.length,treeSha256:closure.treeSha256}));
