import {chromium} from '../../../../../../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const here=import.meta.dirname,run=`a14-s5-typing-${Date.now()}`,r={jobId:'S5-FIX-TITRATION-TYPING',status:'RUNNING',startedAt:new Date().toISOString(),checks:[],errors:[]};
const b=await chromium.launch({channel:'msedge',headless:true});const c=await b.newContext({viewport:{width:390,height:844}}),p=await c.newPage();p.on('pageerror',e=>r.errors.push(e.message));
const snap=()=>p.evaluate(()=>window.__mastersActivity.snapshot());const flush=()=>p.evaluate(()=>window.__mastersActivity.flush());
const input=label=>p.getByLabel(label,{exact:true});const close=(a,b)=>assert(Math.abs(a-b)<1e-7,'numeric values differ');
const record=s=>{r.checks.push(s);console.log(s);};
async function type(label,text){const i=input(label);await i.focus();await p.keyboard.press('Control+A');await p.keyboard.press('Backspace');assert.equal(await i.inputValue(),'');await i.pressSequentially(text,{delay:40});assert.equal(await i.inputValue(),text);return i;}
async function commit(label,text,{blur=false}={}){const i=await type(label,text);if(blur)await p.getByRole('heading',{name:'Your response',exact:true}).click();else await i.press('Enter');await flush();}
try{
 await p.goto(`http://127.0.0.1:5208/alevel.html?activity=alevel/ph-titration-curves&run=${run}`);await p.getByLabel('Target',{exact:true}).selectOption('u6-t1-1-9:2');await p.getByRole('button',{name:'Start practice',exact:true}).click();await p.locator('.tc-chart').waitFor();
 let s=await snap();const initial=s.attempt.currentResponses.curve?.initialPH??4;const id=s.attempt.attemptId;
 // Exact failing independent keyboard sequence, retaining intermediate decimal text.
 await type('Initial pH','3.1');assert.equal((await snap()).attempt.currentResponses.curve?.initialPH??4,initial);await input('Initial pH').press('Enter');await flush();assert.equal((await snap()).attempt.currentResponses.curve.initialPH,3.1);
 for(const v of ['4.2','5.3']){await commit('Initial pH',v);close((await snap()).attempt.currentResponses.curve.initialPH,Number(v));}record('actual Ctrl+A/Backspace/40ms sequential3.1,4.2,5.3 retain text and commit on Enter');
 await commit('Final pH','12.9',{blur:true});close((await snap()).attempt.currentResponses.curve.finalPH,12.9);await commit('Equivalence volume / cm³','37.5');assert.equal((await snap()).attempt.currentResponses.curve.equivalenceVolume,37.5);record('all three controls accept completed decimals; longer37.5 volume and blur completion work');
 await type('Initial pH','20');assert.equal(await input('Initial pH').inputValue(),'20');close((await snap()).attempt.currentResponses.curve.initialPH,5.3);await input('Initial pH').press('Tab');await flush();assert.equal(await input('Initial pH').inputValue(),'5.3');assert.match(await input('Initial pH').getAttribute('aria-invalid'),/true/);await p.getByText(/The previous curve value, 5.3, has been kept/).waitFor();
 await type('Initial pH','3.15');await input('Initial pH').press('Enter');assert.equal(await input('Initial pH').inputValue(),'5.3');await commit('Initial pH','2.8');close((await snap()).attempt.currentResponses.curve.initialPH,2.8);assert.equal(await input('Initial pH').getAttribute('aria-invalid'),null);record('out-of-range and off-step values remain editable while typing, reject explicitly on completion, then recover');
 const final=input('Final pH');await final.focus();await p.keyboard.press('Control+A');await p.keyboard.press('Backspace');assert.equal(await final.inputValue(),'');await final.press('Escape');assert.equal(await final.inputValue(),'12.9');await type('Equivalence volume / cm³','.');assert.equal(await input('Equivalence volume / cm³').inputValue(),'.');await input('Equivalence volume / cm³').press('Tab');assert.equal(await input('Equivalence volume / cm³').inputValue(),'37.5');record('empty and incomplete decimal drafts are not replaced per keystroke; Escape cancels and invalid blur retains accepted graph');
 await commit('Equivalence volume / cm³','22.5');await p.getByRole('button',{name:'Undo curve edit',exact:true}).click();await flush();assert.equal(await input('Equivalence volume / cm³').inputValue(),'37.5');assert.equal((await snap()).attempt.currentResponses.curve.equivalenceVolume,37.5);
 // External controlled response changes restore values rather than leaving old editable text.
 s=await snap();await type('Initial pH','6.');await p.evaluate(async response=>{await window.__mastersActivity.respond('curve',response);await window.__mastersActivity.flush();},{...s.attempt.currentResponses.curve,initialPH:4.4,finalPH:11.1,equivalenceVolume:25});await p.waitForFunction(()=>document.querySelector('input[aria-label="Initial pH"]').value==='4.4');assert.equal(await final.inputValue(),'11.1');assert.equal(await input('Equivalence volume / cm³').inputValue(),'25');record('Undo and changed external controlled restoration synchronise all raw drafts with semantic anchors');
 const slider=p.getByRole('slider',{name:'Initial pH anchor',exact:true});await slider.scrollIntoViewIfNeeded();await slider.focus();await p.keyboard.press('ArrowUp');await flush();assert.equal(await input('Initial pH').inputValue(),'4.5');
 const handle=p.getByRole('slider',{name:'Equivalence volume anchor',exact:true});await handle.scrollIntoViewIfNeeded();const box=await handle.boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+20,box.y+box.height/2,{steps:5});await p.mouse.up();await flush();assert.notEqual((await snap()).attempt.currentResponses.curve.equivalenceVolume,25);assert.equal(Number(await input('Equivalence volume / cm³').inputValue()),(await snap()).attempt.currentResponses.curve.equivalenceVolume);record('unchanged SVG keyboard and pointer-drag controls still synchronise inputs');
 assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,0);s=await snap();assert.equal(s.attempt.phase,'answering');assert.equal(s.attempt.attemptId,id);const retained=s.attempt.currentResponses.curve;
 await p.screenshot({path:path.join(here,'typing-mobile.png'),fullPage:true});await p.reload();await p.locator('.tc-chart').waitFor();s=await snap();assert.equal(s.attempt.attemptId,id);assert.deepEqual(s.attempt.currentResponses.curve,retained);assert.equal(Number(await input('Initial pH').inputValue()),retained.initialPH);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,0);record('editing produces no independent assessment; committed drafts reload under same question/attempt');
 // Next mount must discard old input text/history; first evidence remains immutable during corrections.
 await p.getByRole('button',{name:'Weak acid · rising',exact:true}).click();await p.getByRole('button',{name:'Strong base · rising',exact:true}).click();await p.getByRole('button',{name:/^Phenolphthalein/}).click();await p.getByRole('button',{name:'Check answer',exact:true}).click();await flush();s=await snap();assert.equal(s.attempt.phase,'assessed');const first=structuredClone(s.attempt.firstResponse);await commit('Initial pH','2.8');await p.getByRole('button',{name:'Check correction',exact:true}).click();await flush();assert.deepEqual((await snap()).attempt.firstResponse,first);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);await p.getByRole('button',{name:'Next question',exact:true}).click();await p.waitForFunction(old=>window.__mastersActivity.snapshot().attempt.attemptId!==old,id);assert.equal((await snap()).question.ref.questionId,'TC02');assert.equal(await input('Initial pH').inputValue(),'4');assert(await p.getByRole('button',{name:'Undo curve edit',exact:true}).isDisabled());record('correction preserves immutable first response/time; Next resets anchor drafts and curve Undo history');
 const teacher=await c.newPage();await teacher.goto(`http://127.0.0.1:5208/alevel.html?activity=alevel/ph-titration-curves&mode=teacher&run=${run}-teacher`);await teacher.getByRole('heading',{name:'Checked answer and diagrams',exact:true}).waitFor();assert.equal(await teacher.getByLabel('Initial pH',{exact:true}).count(),0);assert.equal((await teacher.evaluate(()=>window.__mastersActivity.history())).length,0);await teacher.close();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));record('teacher anchors remain disabled/read only and mobile document does not overflow');assert.deepEqual(r.errors,[]);r.status='PASS';
}catch(e){r.status='FAIL';r.failure=e.stack;console.error(e);await p.screenshot({path:path.join(here,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{r.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(r,null,2));await b.close();}







