import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { server, project } from '../server.mjs';
import { rows, seed } from './fixtures.mjs';
const here=import.meta.dirname, require=createRequire(path.join(project,'../../package.json'));
const temp=path.join(here,'.extended');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const host=server();await new Promise(r=>host.listen(5201,'127.0.0.1',r));
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true});
const report={startedAt:new Date().toISOString(),browser:await browser.version(),checks:[],failures:[],pageErrors:[]};
async function poll(page,course,condition){const until=Date.now()+10000;let value;while(Date.now()<until){value=await rows(page,course);if(condition(value))return value;await page.waitForTimeout(25);}throw Error('Durable readiness timeout: '+JSON.stringify(value));}
function immutable(before,after,id){const first=before.attempts.find(a=>a.attemptId===id),last=after.attempts.find(a=>a.attemptId===id);assert.equal(after.attempts.length,before.attempts.length);assert.deepEqual(last.firstResponse,first.firstResponse);assert.deepEqual(last.firstAssessment,first.firstAssessment);assert.deepEqual(last.timing,first.timing);assert.deepEqual(after.evidence,before.evidence);}
try {for(const course of ['alevel','igcse'])for(const mode of ['after-complete','ordered-two-family-retry']){
 const context=await browser.newContext(),page=await context.newPage(),id=course+'-'+mode;let diagnostics={};page.on('pageerror',e=>report.pageErrors.push({id,error:e.message}));
 try {
  const fixture=await seed(page,course),attemptId=fixture.attempt.attemptId;
  await context.addInitScript(()=>{window.failSession=false;window.failAttempt=false;window.writeEvents=[];window.lastAttemptRaw=null;const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){const value=args[0]?.value;const raw=value?.currentResponses?.[Object.keys(value?.currentResponses??{})[0]]?.raw;const fail=this.name==='sessions'?window.failSession:this.name==='attempts'?window.failAttempt:false;window.writeEvents.push({store:this.name,raw,status:value?.status,fail});if(this.name==='attempts')window.lastAttemptRaw=raw;if(fail)throw new DOMException('A21 '+this.name+' ordered quota','QuotaExceededError');return original.apply(this,args);};});
  await page.goto(`http://127.0.0.1:5201/stage-s5/${course}/index.html?view=revision`);await page.locator('.question-player').waitFor();await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.getByRole('button',{name:'Next question',exact:true}).waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();
  const before=await rows(page,course),first=before.attempts.find(a=>a.attemptId===attemptId),key=Object.keys(first.currentResponses)[0];diagnostics.before=before;assert.equal(first.firstAssessment.score,1);assert(before.sessions[0].levels.every(l=>l.confirmedAt!==null));
  if(mode==='ordered-two-family-retry')await page.evaluate(async course=>{const db=await new Promise((r,j)=>{const q=indexedDB.open(`masters-of-chemistry-${course}-local`);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});window.failSession=true;window.failAttempt=true;window.holdSession=true;window.holdDone=false;const tx=db.transaction('sessions','readwrite'),store=tx.objectStore('sessions');const pump=()=>{const q=store.get([course,'local','current-session']);q.onsuccess=()=>{if(window.holdSession)pump();};};tx.oncomplete=()=>{db.close();window.holdDone=true;};tx.onabort=()=>{db.close();window.holdDone=true;};pump();},course);
  await page.getByRole('button',{name:'Next question',exact:true}).click();
  if(mode==='after-complete'){await page.getByText('Revision complete',{exact:true}).waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();}else{await page.getByText('Saving…',{exact:true}).waitFor();assert.equal(await page.getByText('Revision complete',{exact:true}).count(),0);}
  const input=page.locator('.question-part input').first();await input.focus();await page.keyboard.press('Control+A');await page.keyboard.press('Backspace');await input.pressSequentially('912.5',{delay:30});assert.equal(await input.inputValue(),'912.5');
  let firstRetry,failed;
  if(mode==='ordered-two-family-retry'){
   await page.evaluate(()=>window.holdSession=false);await page.waitForFunction(()=>window.holdDone===true);await page.waitForFunction(()=>window.lastAttemptRaw==='912.5');await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();
   failed=await rows(page,course);assert.deepEqual(failed,before);assert.equal(await page.getByText('Revision complete',{exact:true}).count(),0);assert((await page.locator('body').innerText()).includes('Storage is full. Your current work remains in memory; free space and retry.'));
   assert.equal(await page.getByRole('button',{name:'Next question',exact:true}).isEnabled(),false);diagnostics.initialEvents=await page.evaluate(()=>window.writeEvents);
   const eventStart=diagnostics.initialEvents.length;await page.evaluate(()=>window.failSession=false);await page.getByRole('button',{name:'Retry save',exact:true}).click();await page.getByText('Revision complete',{exact:true}).waitFor();
   firstRetry=await poll(page,course,r=>r.sessions[0].status==='complete');assert.equal(firstRetry.sessions[0].current,null);assert.deepEqual(firstRetry.attempts,before.attempts);immutable(before,firstRetry,attemptId);await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();assert((await page.locator('body').innerText()).includes('Storage is full. Your current work remains in memory; free space and retry.'));
   const sessionRetryEvents=(await page.evaluate(()=>window.writeEvents)).slice(eventStart);assert.deepEqual(sessionRetryEvents.map(e=>e.store),['sessions']);assert.equal(sessionRetryEvents[0].fail,false);diagnostics.sessionRetryEvents=sessionRetryEvents;
   await page.screenshot({path:path.join(here,id+'-first-retry.png'),fullPage:true});await page.evaluate(()=>window.failAttempt=false);await page.getByRole('button',{name:'Retry save',exact:true}).click();
  }
  const after=await poll(page,course,r=>r.sessions[0].status==='complete'&&r.attempts.find(a=>a.attemptId===attemptId).currentResponses[key].raw==='912.5');immutable(before,after,attemptId);assert.equal(after.sessions[0].current,null);await page.getByText('Saved on this device',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Retry save',exact:true}).count(),0);assert.equal(await input.inputValue(),'912.5');assert(!(await page.locator('body').innerText()).includes('Session does not reference attempt'));
  const events=await page.evaluate(()=>window.writeEvents);await page.screenshot({path:path.join(here,id+'.png'),fullPage:true});await page.reload();await page.getByText('Revision complete',{exact:true}).waitFor();assert.deepEqual(await rows(page,course),after);
  report.checks.push({id,status:'PASS',before,failed,firstRetry,after,events,originalFirstResponseScoreTimeEvidenceImmutable:true,durableAndMemoryAgree:true,reloadExact:true});console.log('PASS '+id);
 }catch(e){await page.evaluate(()=>window.holdSession=false).catch(()=>{});diagnostics.error=e.stack;diagnostics.final=await rows(page,course).catch(x=>({error:x.message}));diagnostics.dom=await page.locator('body').innerText().catch(x=>x.message);diagnostics.events=await page.evaluate(()=>window.writeEvents).catch(()=>null);fs.writeFileSync(path.join(here,id+'-failure.json'),JSON.stringify(diagnostics,null,2)+'\n');report.failures.push({id,error:e.stack});await page.screenshot({path:path.join(here,id+'-failure.png'),fullPage:true}).catch(()=>{});console.log('FAIL '+id+' '+e.message);}finally{await context.close();}
}}finally{report.status=report.failures.length||report.pageErrors.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'extended-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();await new Promise(r=>host.close(r));console.log(JSON.stringify({status:report.status,failures:report.failures}));if(report.status!=='PASS')process.exitCode=1;}
