import { projectRoot, outputDirectory, devOrigin, previewOrigin, chromium } from '../../paths.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const here=outputDirectory('landing/design');const report={startedAt:new Date().toISOString(),status:'RUNNING',checks:[],errors:[],browser:'Pinned root Playwright1.62.1 headless Edge; fresh isolated contexts'};
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const fixture=`${devOrigin}/scripts/browser/fixtures/landing/harness.html`;
async function screen(name){await page.screenshot({path:path.join(here,'screens',name+'.png'),fullPage:true});}
try{
await page.goto(fixture+'?course=alevel');await page.locator('#yearGrid .gem').first().waitFor();
await page.locator('#statsTile').hover();await screen('alevel-controls-hover');await page.locator('#statsTile').focus();await screen('alevel-controls-focus');
await page.locator('#l6-t2-topic-1 .topic-trigger').click();await page.locator('#l6-t2-topic-2 .topic-trigger').click();assert.equal(await page.locator('[data-column="l6-t2:0"] .topic-section.expanded').count(),1);
await page.locator('[data-leaf="l6-t2-1-2"]').focus();await page.keyboard.press('Enter');assert(await page.locator('#gemDetails').evaluate(e=>e.open));await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.dataset.leaf),'l6-t2-1-2');
await page.locator('[data-leaf="l6-t1-1-1"]').click();assert.equal(await page.locator('#gemDetails .practice-choice').count(),0);await page.keyboard.press('Escape');
await page.locator('[data-leaf="l6-t2-1-2"]').click();await page.locator('.practice-choice[data-practice="2"]').click();let launches=await page.evaluate(()=>window.landingFixture.launches);assert.equal(launches.length,1);assert.equal(launches[0].gemId,'l6-t2-1-2');assert.equal(launches[0].level,2);assert.equal(launches[0].selection,'fixed-level');
await page.locator('#testModeTile').click();await page.locator('#testYearBulk [data-year="l6"]').click();assert.equal(await page.locator('#testSelectionCount').textContent(),'3 gems selected');await page.locator('#testYearBulk [data-year="l6"]').click();assert.equal(await page.locator('#testSelectionCount').textContent(),'0 gems selected');
await page.locator('#l6-t2-topic-1 .test-topic-all').click();assert.equal(await page.locator('#testSelectionCount').textContent(),'3 gems selected');await page.locator('[data-leaf="l6-t1-1-1"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#testSelectionCount').textContent(),'3 gems selected');assert(!await page.locator('#gemDetails').evaluate(e=>e.open));await page.locator('#testClear').click();await page.locator('[data-leaf="l6-t2-1-2"]').click();
await page.locator('#flipYear').click();await page.waitForTimeout(720);assert(await page.locator('#l6-t1').evaluate(e=>e.inert));assert(!await page.locator('#u6-t1').evaluate(e=>e.inert));
await page.getByRole('switch',{name:'A Level Chemistry',exact:true}).click();assert.equal(await page.locator('#yearGrid .gem').count(),64);assert.equal(await page.locator('#gemDetails').evaluate(e=>e.open),false);await page.locator('#testModeTile').click();assert.equal(await page.locator('#testSelectionCount').textContent(),'0 gems selected');await page.locator('[data-leaf="lower-10-3"]').click();
await page.getByRole('switch',{name:'A Level Chemistry',exact:true}).click();assert.equal(await page.locator('#flipYear').getAttribute('aria-checked'),'true');await page.locator('#testModeTile').click();assert.equal(await page.locator('#testSelectionCount').textContent(),'1 gem selected');await page.locator('#testStart').click();launches=await page.evaluate(()=>window.landingFixture.launches);assert.equal(launches.length,2);assert.deepEqual(launches[1].gemIds,['l6-t2-1-2']);assert.notEqual(launches[0].id,launches[1].id);
await page.getByRole('switch',{name:'A Level Chemistry',exact:true}).click();await page.locator('#testModeTile').click();assert.equal(await page.locator('#testSelectionCount').textContent(),'1 gem selected');await page.locator('#testCancel').click();
await page.locator('#topic-10 .topic-trigger').click();await page.locator('#topic-9 .topic-trigger').click();assert.equal(await page.locator('[data-year="lower"] .topic-section.expanded').count(),1);
await page.locator('[data-leaf="lower-10-3"]').focus();await page.keyboard.press('Space');assert(await page.locator('#gemDetails').evaluate(e=>e.open));await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.dataset.leaf),'lower-10-3');
await page.locator('[data-leaf="lower-10-3"]').click();await page.mouse.click(10,10);assert(!await page.locator('#gemDetails').evaluate(e=>e.open));
await page.locator('[data-mode-toggle]').click();assert.equal(await page.locator('.original-landing').getAttribute('data-learning-mode'),'teacher');await screen('igcse-teacher-eagle');await page.locator('[data-leaf="lower-10-3"]').click();assert.equal(await page.locator('#gemDetails .practice-choice').count(),0);assert(await page.locator('#activityLink').isVisible());await page.keyboard.press('Escape');
await page.reload();await page.locator('[data-mode-toggle]').waitFor();assert.equal(await page.locator('.original-landing').getAttribute('data-learning-mode'),'teacher');const keys=await page.evaluate(()=>Object.keys(localStorage));assert(keys.every(key=>key.startsWith('masters-of-chemistry:landing:v1:')));
report.checks.push('Keyboard gem launch/Escape/focus restoration; unavailable detail no launch; direct fixed-level token; ALevel year/topic ADD/REMOVE ALL; revision eligibility; unique launch tokens; inactive face inert; independent course selections/year; IGCSE one expanded topic per year, outside dismissal and eagle teacher mode; project-only preference writes');
const reduced=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),rp=await reduced.newPage();await rp.goto(fixture+'?course=alevel#u6-t1-1-4');await rp.locator('#gemDetails').waitFor({state:'visible'});assert.equal(await rp.locator('#detailName').textContent(),'Weak Acid Calculations');assert.equal(new URL(rp.url()).hash,'#u6-t1-1-5');await rp.keyboard.press('Escape');await rp.locator('#u6-t1-topic-2 .topic-trigger').click();assert.equal(await rp.locator('#yearGrid').evaluate(e=>e.getAnimations({subtree:true}).length),0);await rp.locator('#flipYear').click();assert.equal(await rp.locator('.flip-card').first().evaluate(e=>getComputedStyle(e).transform),'none');await rp.screenshot({path:path.join(here,'screens','alevel-reduced-motion-mobile.png'),fullPage:true});await reduced.close();
report.checks.push('Reduced motion zero layout animations/no flip transform; historical hidden alias deep link redirects to preserved visible gem');assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(error){report.status='FAIL';report.failure=error.stack;process.exitCode=1;await screen('interaction-failure').catch(()=>{});console.error(error);}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-interactions.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({status:report.status,failure:report.failure}));}
