import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
import{getVariant}from'../../../../../../src/chemistry/electron-configuration/identity.ts';import{data}from'../../../../../../src/chemistry/electron-configuration/data.js';import{referenceState,blankState}from'../../../../../../src/chemistry/electron-configuration/engine.ts';import{same}from'../../../../../../src/chemistry/electron-configuration/core.js';
const here=import.meta.dirname,project=path.resolve(here,'../../../../../..'),require=createRequire(path.resolve(project,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');const temp=path.join(project,'.f09-context-temp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;const{chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true});
const base='http://127.0.0.1:5188',original='http://127.0.0.1:5197/alevel/activities/electron-configurations/index.html';
const report={jobId:'F2-EC',agentId:'F09',startedAt:new Date().toISOString(),checks:[],screenshots:[],metrics:[],errors:[],limitations:['Native hidden/minimized/OS suspend not newly tested.','Original correction drawing is compared by reopening the same isolated source review question with the corrected response: the original EC source freezes assessed answers and has no correction action. Shared React first evidence remains immutable.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name,selector){await p.evaluate(()=>document.fonts.ready);await p.locator(selector).screenshot({path:path.join(here,name+'.png')});report.screenshots.push(name+'.png');}
async function startReact(ctx,id,mode='practice'){
 const run=`f09-${mode}-${id}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`${base}/alevel.html?view=home&run=${run}`);await p.locator('.original-landing').waitFor();
 await p.evaluate(async({id,run,mode})=>{
  const{createChemistryRepository}=await import('/src/persistence/index.ts'),{getVariant}=await import('/src/chemistry/electron-configuration/identity.ts'),{electronConfigurationsProvider:provider}=await import('/src/activities/alevel/electron-configurations/provider.ts');
  const q=getVariant(id),level=q.kind==='bonus'?3:q.minimumLevel,ref={activityId:'alevel/electron-configurations',questionId:id,level,seed:q.kind==='bonus'?parseInt(id.slice(4),36):0};provider.restore(ref);
  const namespace={course:'alevel',profileId:'local'},target={course:'alevel',activityId:ref.activityId,gemId:'l6-t2-1-2',level},attemptId=`f09-${run}`,attempt={mode:'student',namespace,attemptId,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId,activeMs:0,idleLimitMs:q.kind==='main'&&q.direction==='identify'?60000:180000,finished:false}};
  const session=mode==='revision'?{kind:'revision',namespace,id:'current-session',createdAt:Date.now(),status:'active',selectedGemIds:[target.gemId],levels:[{target,mode:'practice',required:1,streak:0,confirmedAt:null,initialScore:null}],round:[target.gemId],lastGemId:null,current:{attemptId,target,ref,completed:false},previous:[],submittedAttemptIds:[]}:{kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:attemptId,previousQuestionIds:[id],paused:false};
  const repo=createChemistryRepository(`masters-of-chemistry-alpha-v2-alevel-${run}`),a=await repo.saveCurriculum({attempt}),s=await repo.saveSession(session);repo.close();if(!a.ok||!s.ok)throw Error(JSON.stringify([a,s]));
 },{id,run,mode});await p.goto(`${base}/alevel.html?view=${mode}&run=${run}&activity=alevel%2Felectron-configurations`);await p.locator('.ec-workspace').waitFor();await flush(p);assert.equal((await snap(p)).attempt.ref.questionId,id);return p;
}
async function startOriginal(ctx,id){const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(original+`?review=${id}&mode=teacher`);await p.locator('#questionPanel .question-top').waitFor();return p;}
function answerFor(q){if(q.kind==='bonus'){return{...blankState(),selectedSpeciesIds:q.options.filter(id=>same(data.species.find(s=>s.id===id).counts,q.counts))};}return referenceState(q.speciesId,q.representation);}
async function fill(p,q,answer,app){
 if(q.kind==='bonus'){for(const id of q.options){const item=data.species.find(s=>s.id===id);const field=app==='react'?p.locator('.bonus-options input').nth(q.options.indexOf(id)):p.locator(`[data-species="${id}"]`);await field.setChecked(answer.selectedSpeciesIds.includes(id));}return;}
 if(q.direction==='identify'){await p.getByLabel('Element name or symbol',{exact:true}).fill(answer.identity);return;}
 if(q.representation==='row'||q.representation==='energy'){for(const [index,row]of answer.boxes.entries())for(const [orbital,spin]of row.entries()){const box=p.locator(`[data-orbital="${index}:${orbital}"]`);await box.focus();await p.keyboard.press(spin===3?'2':spin===2?'d':String(spin));if(app==='react')await flush(p);}return;}
 if(q.representation==='short')await p.locator('.core-select select').selectOption(answer.core);
 for(const [index,value]of answer.counts.entries()){const field=p.getByLabel(`Electrons in ${data.subshells[index]}`,{exact:true});if(await field.count()){await field.fill(value);if(app==='react')await flush(p);}}
}
async function submit(p,app){await p.getByRole('button',{name:'Check answer',exact:true}).click();if(app==='react'){await p.waitForFunction(()=>window.__mastersActivity.snapshot().attempt.phase==='assessed');await flush(p);}else await p.locator('#feedback').waitFor({state:'visible'});}
async function metrics(p,app,size,family){return p.evaluate(({app,size,family})=>{const pick=s=>{const e=document.querySelector(s);if(!e)return null;const c=getComputedStyle(e),r=e.getBoundingClientRect();return{fontFamily:c.fontFamily,fontSize:c.fontSize,lineHeight:c.lineHeight,fontWeight:c.fontWeight,color:c.color,background:c.backgroundColor,padding:c.padding,border:c.border,borderRadius:c.borderRadius,width:r.width,height:r.height};};return{app,size,family,orbital:pick('.orbital'),notationInput:pick('.subshell-entry input'),card:pick('.species-card'),energy:pick('.energy-diagram'),match:pick('.bonus-option'),overflow:document.documentElement.scrollWidth>innerWidth};},{app,size,family});}
try{
 for(const [size,viewport]of Object.entries({desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}})){
  const ctx=await browser.newContext({viewport,hasTouch:size==='mobile'}),p=await startReact(ctx,'EC-GYMGZS');
  const first=p.locator('[data-orbital="0:0"]');if(size==='mobile')await first.tap();else await first.click();await flush(p);assert.equal((await snap(p)).attempt.currentResponses.configuration.boxes[0][0],1);
  await first.focus();await p.keyboard.press('Space');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.configuration.boxes[0][0],3);await p.keyboard.press('Shift+Space');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.configuration.boxes[0][0],1);await p.keyboard.press('d');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.configuration.boxes[0][0],2);await first.click();await flush(p);assert.equal((await snap(p)).attempt.currentResponses.configuration.boxes[0][0],1);
  await p.getByText('Set spins without cycling',{exact:true}).click();await p.getByLabel('1s orbital 1',{exact:true}).selectOption('2');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.configuration.boxes[0][0],2);
  await p.getByRole('button',{name:'Periodic table',exact:true}).click();assert.equal(await p.locator('.ec-periodic-element').count(),114);await p.locator('.ec-periodic-scroll').focus();await p.keyboard.press('End');await p.keyboard.press('Escape');assert.equal(await p.getByRole('button',{name:'Periodic table',exact:true}).evaluate(e=>document.activeElement===e),true);
  await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);const draft=await snap(p);await p.reload();await p.locator('.ec-workspace').waitFor();await flush(p);assert.equal((await snap(p)).attempt.attemptId,draft.attempt.attemptId);assert.deepEqual((await snap(p)).attempt.currentResponses,draft.attempt.currentResponses);
  if(size==='mobile'){await p.locator('.orbital-scroll').first().evaluate(e=>e.scrollLeft=e.scrollWidth);assert(await p.locator('.orbital-scroll').first().evaluate(e=>e.scrollLeft>0));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
  await p.getByRole('button',{name:'Clear answer',exact:true}).click();await flush(p);assert.deepEqual((await snap(p)).attempt.currentResponses.configuration,blankState());await fill(p,getVariant('EC-GYMGZS'),answerFor(getVariant('EC-GYMGZS')),'react');await submit(p,'react');const assessed=await snap(p);const history=await p.evaluate(()=>window.__mastersActivity.history());assert.equal(history.length,1);assert.equal(assessed.attempt.firstAssessment.score,1);assert(assessed.attempt.firstResponse.timing.activeMs>0);assert.equal(assessed.attempt.timing,undefined);
  await p.getByRole('button',{name:'Show worked answer',exact:true}).click();await p.locator('.ec-reference-answer').waitFor();assert.equal(await p.locator('.ec-reference-answer .orbital').count(),36);await p.reload();await p.locator('.ec-reference-answer').waitFor();await flush(p);assert.deepEqual((await snap(p)).attempt.firstResponse,assessed.attempt.firstResponse);assert.deepEqual(await p.evaluate(()=>window.__mastersActivity.history()),history);await p.getByRole('button',{name:'Next question',exact:true}).click();await p.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,assessed.attempt.attemptId);await flush(p);assert.equal((await snap(p)).attempt.phase,'answering');assert.equal((await snap(p)).attempt.assistance.length,0);assert.equal((await snap(p)).attempt.timing.finished,false);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);
  const teacherIds=['EC-TH921N','EC-TXYUKV','EC-PNWLL0','EC-UH3QI8','EC-5AUBIM','EC-U5RDA2','EC-RRCPUY','EC-RGVK0U','ECB-00000F'];
  for(const id of teacherIds){const t=await ctx.newPage();await t.goto(`${base}/alevel.html?view=teacher&activity=alevel%2Felectron-configurations&review=${id}&run=f09-teacher-${id}-${size}`);await t.locator('.ec-reference-answer').waitFor();await flush(t);assert.equal((await snap(t)).attempt,null);assert.equal((await t.evaluate(()=>window.__mastersActivity.history())).length,0);assert.equal(await t.locator('.ec-workspace input:not([disabled]),.ec-workspace select:not([disabled]),.ec-workspace button.orbital:not([disabled])').count(),0);assert.equal(await t.locator('.header-question-code').count(),1);if(id.startsWith('EC-'))assert.equal(await t.locator('.ec-reference-answer .orbital').count(),36);await shot(t,`teacher-${size}-${id}`,'.question-player');await t.close();}
  report.checks.push({size,pointer:true,touch:size==='mobile',spaceSpin:true,shiftBackward:true,downSpin:true,nonDragSelect:true,periodicFacts:114,escapeFocusRestored:true,drawingRestore:true,firstScoreTimeImmutable:true,modelReloadDedup:true,freshNext:true,teacherCases:teacherIds.length});await ctx.close();
 }
 report.status='PASS';
}catch(e){report.status='FAIL';report.errors.push(e.stack??String(e));console.error(e);}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'lifecycle-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,screenshots:report.screenshots.length,errors:report.errors}));if(report.status!=='PASS')process.exitCode=1;}
