import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const app=process.cwd(),out=path.join(app,'validation/ui-consistency/u1/theme'),require=createRequire(path.resolve(app,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.u03tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true});let report={status:'RUNNING',startedAt:new Date().toISOString(),screens:[],transitions:[],errors:[]};
const base='http://127.0.0.1:5188/';
async function sample(p,name){await p.waitForFunction(()=>document.querySelectorAll('button').length>0&&getComputedStyle(document.body).backgroundImage.includes('radial-gradient'));await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(250);const result=await p.evaluate(()=>{
 const shown=e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&getComputedStyle(e).visibility!=='hidden'};
 const relevant=[...document.querySelectorAll('button,input,textarea,select,code,svg text,label,p,h1,h2,h3,.score,.response-feedback')].filter(shown);
 const fonts=[...new Set(relevant.map(e=>getComputedStyle(e).fontFamily))];const badFonts=relevant.filter(e=>!getComputedStyle(e).fontFamily.startsWith('Comfortaa')).map(e=>({tag:e.tagName,class:e.className,text:e.textContent?.slice(0,60),font:getComputedStyle(e).fontFamily}));
 const wrappers=[...document.querySelectorAll('.original-landing,.course-shell,.course-question-screen,.landing-course-stage')].filter(shown).map(e=>({class:e.className,color:getComputedStyle(e).backgroundColor,image:getComputedStyle(e).backgroundImage}));
 const layout=document.querySelector('.course-layout');return {viewport:innerWidth,pageWidth:document.documentElement.scrollWidth,fonts,badFonts,wrappers,bodyBackground:getComputedStyle(document.body).backgroundImage,bodyColor:getComputedStyle(document.body).backgroundColor,stars:getComputedStyle(document.body,'::before').backgroundImage,paneWidth:layout?.getBoundingClientRect().width??null,paneMax:layout?getComputedStyle(layout).maxWidth:null,count:relevant.length};
 });result.name=name;report.screens.push(result);assert.equal(result.badFonts.length,0,name+' non Comfortaa');assert(result.pageWidth<=result.viewport,name+' page overflow '+result.pageWidth);assert(result.wrappers.every(w=>w.color==='rgba(0, 0, 0, 0)'&&w.image==='none'),name+' opaque viewport');const row=p.locator('.question-actions');if(await row.count()){assert.equal(await row.count(),1);const actions=await row.locator('button').allTextContents();assert.deepEqual(actions,['Check','Clear','Give Up','Next']);const geometry=await row.evaluate(e=>({right:e.getBoundingClientRect().right,buttons:[...e.querySelectorAll('button')].map(b=>({y:b.getBoundingClientRect().y,right:b.getBoundingClientRect().right,height:b.getBoundingClientRect().height}))}));assert(geometry.buttons.every(b=>Math.abs(b.y-geometry.buttons[0].y)<1));assert(Math.abs(geometry.right-geometry.buttons[3].right)<1);assert(geometry.buttons.every(b=>b.height>=44));result.actions={actions,geometry};}await p.screenshot({path:path.join(out,'final-'+name+'.png'),fullPage:true});console.log('PASS '+name);fs.writeFileSync(path.join(out,'final-browser-checkpoint.json'),JSON.stringify(report,null,2));}
try{
 const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'alevel.html?course=alevel&run=u03-theme');await p.locator('#flipCourse').waitFor();
 await p.evaluate(()=>{window.__courseAnimations=[];const real=Element.prototype.animate;Element.prototype.animate=function(frames,options){if(this.classList.contains('landing-course-surface'))window.__courseAnimations.push({frames,options,at:performance.now()});return real.call(this,frames,options)}});
 for(const target of ['igcse','alevel']){await p.locator('#flipCourse').click();const busy=await p.locator('.landing-course-surface').getAttribute('aria-busy');assert.equal(busy,'true');await p.evaluate(()=>document.querySelector('#flipCourse')?.click());await p.waitForFunction(t=>document.querySelector('.original-landing')?.classList.contains(t)&&document.querySelector('.landing-course-surface')?.getAttribute('aria-busy')==='false',target);const state=await p.evaluate(()=>({url:location.href,focus:document.activeElement?.id,count:document.querySelectorAll('.original-landing').length,inert:document.querySelector('.landing-course-surface')?.inert,animations:window.__courseAnimations.slice(-2)}));assert.equal(state.focus,'flipCourse');assert.equal(state.count,1);assert.equal(state.inert,false);assert(state.url.includes('course='+target));assert(state.animations.every(a=>a.options.duration===110&&a.frames.every(f=>!f.transform.includes('rotate'))));report.transitions.push({target,busy,state});}
 await p.emulateMedia({reducedMotion:'reduce'});const before=await p.evaluate(()=>window.__courseAnimations.length);await p.locator('#flipCourse').click();await p.waitForFunction(()=>document.querySelector('.original-landing')?.classList.contains('igcse'));assert.equal(await p.evaluate(()=>window.__courseAnimations.length),before);assert.equal(await p.locator('.landing-course-surface').getAttribute('aria-busy'),'false');assert.equal(await p.evaluate(()=>document.activeElement.id),'flipCourse');report.transitions.push({reducedMotion:true,animationCalls:0,focus:'flipCourse'});await p.emulateMedia({reducedMotion:'no-preference'});
 const registrations=await p.evaluate(async()=>{const {productionRegistry}=await import('/src/foundation/registry.ts');return productionRegistry.activities.filter(a=>a.strand==='curriculum').map(a=>({id:a.id,course:a.course,gem:a.gems[0].id,level:a.gems[0].supportedLevels[0]}))});
 for(const width of [1440,390]){
 await p.setViewportSize({width,height:width<600?844:1000});
 for(const course of ['alevel','igcse']){await p.goto(base+course+'.html?course='+course+'&run=u03-theme-'+width);await p.locator('.original-landing').waitFor();await sample(p,course+'-landing-'+width)}
 for(const view of ['statistics','teacher','import','olympiad']){await p.goto(base+'alevel.html?course=alevel&view='+view+'&run=u03-theme-'+width);await p.locator('.course-shell,.olympiad-landing').waitFor();await p.waitForTimeout(250);await sample(p,view+'-'+width)}
 for(const r of registrations){await p.goto(base+r.course+'.html?activity='+encodeURIComponent(r.id)+'&fresh=1&gem='+r.gem+'&level='+r.level+'&run=u03-'+width+'-'+r.id.split('/')[1]);await p.locator('.question-player').waitFor({timeout:30000});await sample(p,r.id.replace('/','-')+'-'+width);assert.equal(report.screens.at(-1).paneMax,'1120px');}
 }
 await c.close();assert.equal(report.errors.length,0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'final-browser-results.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({status:report.status,screens:report.screens.length,transitions:report.transitions.length,failure:report.failure}))}

