import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {productionRegistry} from '../../../../src/foundation/registry.ts';
const app=process.cwd(),out=path.join(app,'validation/ui-consistency/u1/theme'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.u03tmp');
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true}),c=await b.newContext(),p=await c.newPage(),report={status:'RUNNING',startedAt:new Date().toISOString(),base:'http://127.0.0.1:5192/',screens:[],errors:[]};p.on('pageerror',e=>report.errors.push(e.message));
async function shot(name){await p.evaluate(()=>document.fonts.ready);const s=await p.evaluate(()=>{const visible=e=>{const b=e.getBoundingClientRect();return b.width>0&&b.height>0&&getComputedStyle(e).visibility!=='hidden'};const text=[...document.querySelectorAll('button,input,textarea,select,code,svg text,label,p,h1,h2,h3')].filter(visible),layout=document.querySelector('.course-layout');const row=document.querySelector('.question-actions');return{viewport:innerWidth,pageWidth:document.documentElement.scrollWidth,fonts:[...new Set(text.map(e=>getComputedStyle(e).fontFamily))],count:text.length,questionCode:document.querySelector('.header-question-code')?.textContent??null,bodyBackground:getComputedStyle(document.body).backgroundImage,paneWidth:layout?.getBoundingClientRect().width??null,paneMax:layout?getComputedStyle(layout).maxWidth:null,wrappers:[...document.querySelectorAll('.original-landing,.course-shell,.olympiad-landing')].filter(visible).map(e=>({class:e.className,color:getComputedStyle(e).backgroundColor,image:getComputedStyle(e).backgroundImage})),actions:row?{rowCount:document.querySelectorAll('.question-actions').length,right:row.getBoundingClientRect().right,buttons:[...row.querySelectorAll('button')].map(e=>({text:e.textContent,y:e.getBoundingClientRect().y,right:e.getBoundingClientRect().right,height:e.getBoundingClientRect().height,font:getComputedStyle(e).fontFamily}))}:null}});s.name=name;assert(s.count>0);assert(s.fonts.every(f=>f.startsWith('Comfortaa')),name+' fonts');assert(s.pageWidth<=s.viewport,name+'overflow');assert(s.wrappers.every(e=>e.color==='rgba(0, 0, 0, 0)'&&e.image==='none'));if(s.actions){assert.equal(s.actions.rowCount,1);assert.deepEqual(s.actions.buttons.map(b=>b.text),['Check','Clear','Give Up','Next']);assert(s.actions.buttons.every(b=>Math.abs(b.y-s.actions.buttons[0].y)<1&&b.height>=44));assert(Math.abs(s.actions.right-s.actions.buttons[3].right)<1)}report.screens.push(s);await p.screenshot({path:path.join(out,'static-'+name+'.png'),fullPage:true});console.log('PASS '+name);fs.writeFileSync(path.join(out,'static-checkpoint.json'),JSON.stringify(report,null,2))}
try{
const targets=productionRegistry.activities.filter(a=>a.strand==='curriculum'&&['alevel/acid-base-calculations','alevel/electrons-bonding','alevel/electron-configurations','alevel/dot-and-cross','alevel/ph-titration-curves','igcse/calorimetry','igcse/bond-enthalpy','igcse/energy-enthalpy'].includes(a.id));
for(const width of [1440,390]){await p.setViewportSize({width,height:width===1440?1000:844});for(const a of targets){const gem=a.gems[0],url=report.base+a.course+'/?course='+a.course+'&activity='+encodeURIComponent(a.id)+'&gem='+gem.id+'&level='+gem.supportedLevels[0]+'&fresh=1';await p.goto(url);await p.locator('.question-player').waitFor();await p.waitForTimeout(300);await shot(a.id.replace('/','-')+'-'+width);assert.equal(report.screens.at(-1).paneMax,'1120px');if(a.id==='alevel/electron-configurations'&&await p.locator('.orbital[data-orbital]').count()){await p.locator('.orbital[data-orbital]').first().click();assert.equal(await p.locator('.orbital[data-orbital]').first().innerText(),String.fromCharCode(8593));await shot('electron-live-spin-'+width)}if(a.id==='igcse/bond-enthalpy'){const pan=await p.locator('.reaction-diagram').evaluate(e=>{e.scrollLeft=80;return{width:e.clientWidth,scrollWidth:e.scrollWidth,left:e.scrollLeft}});if(width<500){assert(pan.scrollWidth>pan.width);assert(pan.left>0)}report.screens.at(-1).internalPan=pan}if(a.id==='alevel/dot-and-cross'&&width===390){await p.getByText('Keyboard and non-drag controls',{exact:true}).click();await p.getByRole('button',{name:'Add atom',exact:true}).click();await p.getByRole('button',{name:'Magnify diagram',exact:true}).click();await shot('dotcross-live-pan-390')}}
for(const id of ['alevel/c3l6-organic-reactions','alevel/olympiad-2011-q4']){await p.goto(report.base+'alevel/?course=alevel&activity='+encodeURIComponent(id));await p.locator('.olympiad-question-frame').waitFor();await p.waitForTimeout(300);await shot(id.split('/')[1]+'-'+width);assert.equal(report.screens.at(-1).paneMax,'1120px')}
}assert.equal(report.errors.length,0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'static-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify({status:report.status,screens:report.screens.length,failure:report.failure}))}
