import {chromium} from '../../../../../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {bank} from '../../../src/activities/alevel/dot-and-cross/bank.js';
const here=import.meta.dirname,run=`a10-dot-headless-${Date.now()}`;
const report={jobId:'S2-DOTCROSS',run,startedAt:new Date().toISOString(),browser:'pinned Playwright1.62.1 Microsoft Edge headless; deterministic native seed1 triggers original ionic pool; actual headed timing is separate',checks:[],errors:[],status:'RUNNING'};
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100}});
await context.addInitScript(()=>{const original=crypto.getRandomValues.bind(crypto);Object.defineProperty(crypto,'getRandomValues',{value:array=>array instanceof Uint32Array&&array.length===1?(array[0]=1,array):original(array)});});const page=await context.newPage();page.on('pageerror',error=>report.errors.push(error.message));
const snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot());
const flush=()=>page.evaluate(async()=>{await window.__mastersActivity.flush();});
const wait=()=>page.waitForFunction(()=>window.__mastersActivity?.snapshot().saveStatus.kind==='saved');
const click=async(name)=>{const prior=await snap();await page.getByRole('button',{name,exact:true}).click();if(name==='Next question')await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.attemptId!==id,prior.attempt.attemptId);if(name==='Start practice')await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);await flush();await wait();};
const check=name=>{report.checks.push(name);console.log(name);};
const openAlternatives=async()=>{const details=page.locator('.editor-alternatives');if(!await details.evaluate(el=>el.open))await details.locator(':scope > summary').click();};
async function buildReference(record,{skipAtoms=false}={}){
 await openAlternatives();const map=Object.fromEntries(record.reference.atoms.map((atom,index)=>[atom.id,`a${index+1}`]));
 if(!skipAtoms)for(const atom of record.reference.atoms){await page.getByLabel('Element',{exact:true}).selectOption(atom.element);await page.getByLabel('X position',{exact:true}).fill(String(atom.x));await page.getByLabel('Y position',{exact:true}).fill(String(atom.y));await click('Add atom');}
 for(const electron of record.reference.electrons){await page.getByLabel('Electron symbol',{exact:true}).selectOption(electron.symbol);await page.getByLabel('First atom',{exact:true}).selectOption(map[electron.anchor.kind==='atom'?electron.anchor.atomId:electron.anchor.a]);await page.getByLabel('Second atom',{exact:true}).selectOption(electron.anchor.kind==='atom'?'':map[electron.anchor.b]);await page.getByLabel('Electron slot',{exact:true}).selectOption({value:String(electron.anchor.slot)});await page.waitForTimeout(50);const ui=await page.locator('.dc-alternatives select').evaluateAll(nodes=>nodes.map(n=>({label:n.getAttribute('aria-label'),value:n.value})));await click('Add electron');report.electronEdits??=[];report.electronEdits.push({expected:electron,ui,state:(await snap()).attempt.currentResponses.diagram.electrons,status:await page.locator('.dc-status').innerText()});}
 for(const group of record.reference.groups){const selected=await page.locator('.dc-atom-list button[aria-pressed=true]').all();for(const button of selected)await button.click();for(const id of group.atomIds){const atom=record.reference.atoms.find(a=>a.id===id);await page.locator('.dc-atom-list').getByRole('button',{name:`${atom.element} ${map[id]}`,exact:true}).click();}await page.getByLabel('Ion charge',{exact:true}).fill(String(group.charge));await page.getByLabel('Show brackets',{exact:true}).setChecked(group.bracket);await click('Apply bracket and charge');}
}
try{
 await page.goto(`http://127.0.0.1:5181/alevel.html?run=${run}`);await page.getByLabel('Target',{exact:true}).selectOption('l6-t2-1-3:1');await click('Start practice');
 let state=await snap();const record=bank.find(record=>record.id===state.question.ref.questionId);assert(record);assert.equal(state.attempt.timing.idleLimitMs,180000);
 await openAlternatives();await page.getByLabel('Element',{exact:true}).selectOption(record.reference.atoms[0].element);await page.getByLabel('X position',{exact:true}).fill(String(record.reference.atoms[0].x));await page.getByLabel('Y position',{exact:true}).fill(String(record.reference.atoms[0].y));await click('Add atom');
 const attemptId=state.attempt.attemptId;await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);await wait();state=await snap();assert.equal(state.attempt.attemptId,attemptId);assert.equal(state.attempt.currentResponses.diagram.atoms.length,1);assert.equal(state.attempt.currentResponses.diagram.history.length,1);await click('Undo');assert.equal((await snap()).attempt.currentResponses.diagram.atoms.length,0);await click('Redo');assert.equal((await snap()).attempt.currentResponses.diagram.atoms.length,1);check('actual controller/repository restores diagram and undo/redo history against same ID after reload');
 await click('Clear diagram');await buildReference(record);state=await snap();report.constructed={questionId:record.id,atomCount:state.attempt.currentResponses.diagram.atoms.length,electronCount:state.attempt.currentResponses.diagram.electrons.length,groupCount:state.attempt.currentResponses.diagram.groups.length};assert.equal(state.attempt.currentResponses.diagram.electrons.length,record.reference.electrons.length);assert.equal(state.attempt.currentResponses.diagram.groups.length,record.reference.groups.length);check(`full ${record.id} reference constructed using real non-drag atom/electron/bracket controls`);
 // Keyboard movement is chemical-layout independent and reversible.
 await page.locator('.dc-atom-list button').first().click();const before=(await snap()).attempt.currentResponses.diagram.atoms[0];await page.locator('.dc-canvas').focus();await page.keyboard.press('ArrowRight');await flush();assert.equal((await snap()).attempt.currentResponses.diagram.atoms[0].x,before.x+5);await click('Undo');
 const firstElectron=state.attempt.currentResponses.diagram.electrons[0].id;await page.getByText('Electron inventory and deletion',{exact:true}).click();await page.getByRole('button',{name:`Delete electron ${firstElectron}`,exact:true}).click();await flush();await wait();
 await click('Check answer');state=await snap();assert.equal(state.attempt.phase,'assessed');assert(state.attempt.firstAssessment.marks.earned<1);const firstResponse=structuredClone(state.attempt.firstResponse),firstAssessment=structuredClone(state.attempt.firstAssessment);assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,1);check('chemical wrongness is assessed with immutable first response/result/time and one curriculum evidence record');
 await click('Undo');await click('Check correction');state=await snap();assert.equal(state.correctionFeedback.status,'correct');assert.deepEqual(state.attempt.firstResponse,firstResponse);assert.deepEqual(state.attempt.firstAssessment,firstAssessment);assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,1);check('real undo plus correction check gives correct learning feedback without changing first assessment');
 await click('Show worked answer');await page.screenshot({path:path.join(here,'practice-correction-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Magnify diagram',exact:true}).click();assert.equal(await page.locator('.dc-canvas').evaluate(el=>Math.round(el.getBoundingClientRect().width)),1000);assert(await page.locator('.dc-viewport').evaluate(el=>el.scrollWidth>el.clientWidth));await page.screenshot({path:path.join(here,'mobile-magnified-ionic-editor.png'),fullPage:true});await page.getByRole('button',{name:'Fit diagram',exact:true}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.setViewportSize({width:1440,height:1100});check('Fit/Magnify preserves full-sized atom/electron labels within a scrollable mobile viewport');
 await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await wait();state=await snap();assert.deepEqual(state.attempt.firstResponse,firstResponse);assert.deepEqual(state.attempt.firstAssessment,firstAssessment);check('assessed reload keeps first evidence and corrected drawing separate');
 await click('Next question');state=await snap();assert.notEqual(state.attempt.attemptId,attemptId);assert.equal(state.attempt.phase,'answering');assert.equal(state.attempt.timing.activeMs,0);assert.notEqual(state.question.ref.questionId,record.id);check('Next creates fresh identity and timing via production scheduler');
 await click('Pause');const paused=await snap();await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await flush();await wait();assert.equal((await snap()).attempt.attemptId,paused.attempt.attemptId);check('practice pause/reload/resume preserves question and attempt');
 await page.setViewportSize({width:390,height:844});await openAlternatives();await page.screenshot({path:path.join(here,'mobile-editor.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));check('mobile controls render inside viewport with no document overflow');
 // Touch input uses actual pointer/touch dispatch, not the development response seam.
 const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const touch=await touchContext.newPage();await touch.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-touch`);await touch.getByLabel('Target',{exact:true}).selectOption('l6-t2-1-3:1');await touch.getByRole('button',{name:'Start practice',exact:true}).tap();await touch.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);await touch.locator('.dc-canvas').tap({position:{x:100,y:120}});await touch.evaluate(()=>window.__mastersActivity.flush());assert.equal(await touch.evaluate(()=>window.__mastersActivity.snapshot().attempt.currentResponses.diagram.atoms.length),1);await touch.screenshot({path:path.join(here,'mobile-touch-placement.png'),fullPage:true});await touchContext.close();check('real touchscreen tap places atom; non-drag and keyboard routes are also exercised');
 await page.setViewportSize({width:1440,height:1100});
 // Teacher/review resolves exact historical bank identities without any pupil writes.
 for(const id of ['sulfur-hexafluoride','magnesium-peroxide','carbonate-ion']){const teacher=await context.newPage();await teacher.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-teacher-${id}&mode=teacher&review=${id}`);await teacher.getByRole('heading',{name:'Worked answer',exact:true}).waitFor();await teacher.locator('.dc-canvas').waitFor();await teacher.locator('.worked-answer img').evaluate(img=>img.decode());assert.equal(await teacher.locator('.dc-controls button:not(:disabled)').count(),0);assert.equal(await teacher.evaluate(()=>window.__mastersActivity.history().then(records=>records.length)),0);await teacher.screenshot({path:path.join(here,`teacher-${id}-desktop.png`),fullPage:true});await teacher.setViewportSize({width:390,height:844});await teacher.screenshot({path:path.join(here,`teacher-${id}-mobile.png`),fullPage:true});assert(await teacher.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await teacher.close();}check('91-bank teacher/review path: crowded expanded shell, grouped peroxide and charged carbonate are read only with no evidence');
 // Real revision ADD ALL launches the same migrated dot-cross adapter (only L6 topic is selected).
 await page.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-revision&session=revision`);await page.getByRole('button',{name:'ADD ALL l6-t2-1',exact:true}).click();assert.equal((await snap()).selectedCount,3);await click('Start practice');state=await snap();assert.equal(state.session.kind,'revision');assert.equal(state.question.ref.activityId,'alevel/dot-and-cross');await openAlternatives();await page.getByLabel('Element',{exact:true}).selectOption('H');await click('Add atom');await click('Pause');const revisionId=(await snap()).attempt.attemptId;await page.reload();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await flush();await wait();assert.equal((await snap()).attempt.attemptId,revisionId);await click('Check answer');assert.equal((await snap()).attempt.phase,'assessed');await click('Next question');assert.notEqual((await snap()).attempt.attemptId,revisionId);assert.equal((await snap()).session.kind,'revision');await page.screenshot({path:path.join(here,'revision-next-desktop.png'),fullPage:true});check('revision topic ADD ALL, real launch, answer, pause/reload/resume and scheduler Next pass');
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(error){report.status='FAIL';report.failure=error.stack;console.error(error);try{await page.screenshot({path:path.join(here,'browser-failure.png'),fullPage:true});}catch{}process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(here,run+'-results.json'),JSON.stringify(report,null,2));await browser.close();}










