import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const here=import.meta.dirname,project=path.resolve(here,'../../..'),require=createRequire(path.join(project,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');const temp=path.join(here,'.revision-tmp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true}),base='http://127.0.0.1:5183',report={startedAt:new Date().toISOString(),browser:await browser.version(),checks:[],failures:[],pageErrors:[]};
async function run(name,fn){const context=await browser.newContext(),page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push({name,error:e.message}));try{report.checks.push({name,status:'PASS',...await fn(page)});console.log('PASS '+name);}catch(e){report.failures.push({name,error:e.stack});await page.screenshot({path:path.join(here,name.replaceAll(' ','-')+'-failure.png'),fullPage:true}).catch(()=>{});console.log('FAIL '+name+' '+e.message)}finally{await context.close()}}
async function snapshot(page){return page.evaluate(()=>window.__mastersActivity.snapshot())}async function flush(page){await page.evaluate(()=>window.__mastersActivity.flush());await page.getByText('Saved on this device',{exact:true}).waitFor()}
async function home(page){await page.getByRole('button',{name:'Home',exact:true}).click();await page.locator('.original-landing').waitFor()}
try{
for(const course of['alevel','igcse'])await run(course+' revision matching resume and changed set',async page=>{
const fixture='revision-'+course+'-'+Date.now();await page.goto(`${base}/${course}.html?course=${course}&run=${fixture}`);await page.locator('.original-landing').waitFor();const metadata=await page.evaluate(async course=>{const{productionRegistry}=await import('/src/foundation/registry.ts');return productionRegistry.curriculumFor(course).map(r=>({id:r.id,gems:r.gems}));},course),chosen=metadata.find(r=>r.id===(course==='alevel'?'alevel/acid-base-calculations':'igcse/calorimetry')).gems[0];
await page.evaluate(({course,id})=>localStorage.setItem(`masters-of-chemistry:landing:v1:${course}:selection`,JSON.stringify([id])),{course,id:chosen.id});await page.reload();await page.locator('.original-landing').waitFor();await page.getByRole('button',{name:'Revision',exact:true}).click();assert.equal(await page.locator('#testSelectionCount').innerText(),'1 gem selected');await page.getByRole('button',{name:'Go: start revision',exact:true}).click();await page.locator('.question-player').waitFor();await flush(page);const first=await snapshot(page);assert.equal(first.session.kind,'revision');assert.equal(first.session.levels.length,chosen.supportedLevels.length);assert.equal(await page.locator('[aria-label="Practice setup"]').count(),0);
const question=first.question.parts.find(p=>p.kind==='numeric');if(question)await page.evaluate(async({id,unit})=>window.__mastersActivity.respond(id,{kind:'numeric',raw:'123',unit}),{id:question.id,unit:question.unit});await flush(page);const responses=(await snapshot(page)).attempt.currentResponses;await home(page);await page.getByRole('button',{name:'Revision',exact:true}).click();await page.getByRole('button',{name:'Go: start revision',exact:true}).click();await page.locator('.question-player').waitFor();await flush(page);const resumed=await snapshot(page);assert.equal(resumed.attempt.attemptId,first.attempt.attemptId);assert.deepEqual(resumed.attempt.currentResponses,responses);assert.equal(resumed.session.status,'active');assert.equal(resumed.session.current.ref.questionId,first.session.current.ref.questionId);
await home(page);await page.getByRole('button',{name:'Revision',exact:true}).click();if(course==='alevel')await page.getByRole('button',{name:'ADD ALL UPPER SIXTH',exact:true}).click();else {await page.locator('[data-topic="lower-topic-10"] .topic-trigger').click();await page.locator('[data-topic="lower-topic-10"] .test-topic-all').click();}const count=parseInt(await page.locator('#testSelectionCount').innerText());assert(count>1);await page.getByRole('button',{name:'Go: start revision',exact:true}).click();await page.locator('.question-player').waitFor();await flush(page);const changed=await snapshot(page);assert.notEqual(changed.attempt.attemptId,first.attempt.attemptId);assert.equal(changed.session.selectedGemIds.length,count);const selectedTargets=metadata.flatMap(r=>r.gems.filter(g=>changed.session.selectedGemIds.includes(g.id)).flatMap(g=>g.supportedLevels.map(level=>({gemId:g.id,level}))));assert.deepEqual(changed.session.levels.map(l=>({gemId:l.target.gemId,level:l.target.level})).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),selectedTargets.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))));assert.equal(changed.history.length,0);await home(page);return{fixture,originalAttempt:first.attempt.attemptId,resumedAttempt:resumed.attempt.attemptId,changedAttempt:changed.attempt.attemptId,selectedGemCount:count,expandedLevelCount:changed.session.levels.length,responsesRestored:true};});
await run('course preference namespaces hash aliases and direct links',async page=>{
const fixture='routing-'+Date.now();await page.goto(`${base}/alevel.html?run=${fixture}`);await page.locator('.original-landing.alevel').waitFor();await page.getByRole('switch',{name:'A Level Chemistry',exact:true}).click();await page.locator('.original-landing.igcse').waitFor();assert.equal(new URL(page.url()).searchParams.get('course'),'igcse');await page.goto(`${base}/alevel.html?run=${fixture}`);await page.locator('.original-landing.igcse').waitFor();await page.goto(`${base}/igcse.html?run=${fixture}&course=alevel`);await page.locator('.original-landing.alevel').waitFor();
for(const [alias,target]of[['u6-t2-7-1','l6-t2-1-2'],['u6-t1-1-4','u6-t1-1-5']]){await page.goto(`${base}/igcse.html?run=${fixture}#${alias}`);await page.locator('.original-landing.alevel').waitFor();await page.locator('#gemDetails').waitFor({state:'visible'});assert.equal(new URL(page.url()).hash,'#'+target);assert.equal(await page.locator(`[data-leaf="${alias}"]`).count(),0);await page.getByRole('button',{name:'Close gem details',exact:true}).click();}
await page.goto(`${base}/alevel.html?run=${fixture}#upper-1-1`);await page.locator('.original-landing.igcse').waitFor();
// Exact old saved-question URL wins the other entry and remembered course, and opens teacher only.
const ref=await page.evaluate(async()=>{const{productionRegistry}=await import('/src/foundation/registry.ts');const r=productionRegistry.get('igcse/calorimetry'),g=r.gems[0];return(await r.provider()).select({activityId:r.id,gemId:g.id,level:1,seed:12345,previousQuestionIds:[]})});const legacy=`/Masters-of-IGCSE-Chemistry/activities/calorimetry/index.html?review=${ref.questionId}`;await page.goto(`${base}/alevel.html?run=${fixture}&legacy=${encodeURIComponent(legacy)}`);await page.locator('.teacher-answer').waitFor();assert.equal(await page.getByLabel('Teacher activity',{exact:true}).inputValue(),'igcse/calorimetry');assert.equal((await snapshot(page)).history.length,0);assert.equal((await snapshot(page)).attempt,null);await home(page);
const gemId=await page.evaluate(async()=>{const{productionRegistry}=await import('/src/foundation/registry.ts');return productionRegistry.get('igcse/calorimetry').gems[0].id});await page.evaluate(id=>location.hash=id,gemId);await page.locator('#gemDetails').waitFor({state:'visible'});await page.locator('a.practice-choice[data-practice="1"]').click();await page.locator('.question-player').waitFor();await flush(page);const igcse=await snapshot(page);await home(page);await page.getByRole('switch',{name:'A Level Chemistry',exact:true}).click();await page.locator('.original-landing.alevel').waitFor();await page.getByRole('button',{name:'Teacher',exact:true}).click();await page.locator('.teacher-answer').waitFor();const alevel=await snapshot(page);assert.equal(alevel.history.length,0);assert.equal(alevel.attempt,null);assert.notEqual(alevel.databaseName,igcse.databaseName);await home(page);await page.locator('#olympiadTile').click();await page.getByRole('button',{name:'Return to challenge',exact:true}).or(page.getByRole('button',{name:'Teacher preview',exact:true})).waitFor();await page.getByRole('button',{name:'Home',exact:true}).click();await page.locator('.original-landing.alevel').waitFor();return{fixture,rememberedCourseWinsEntry:true,explicitCourseWinsPreference:true,hiddenAliasesRedirected:true,oldQuestionTeacherOnly:true,courseDatabases:[igcse.databaseName,alevel.databaseName],olympiadHome:true};});
}finally{report.finishedAt=new Date().toISOString();report.status=report.failures.length||report.pageErrors.length?'FAIL':'PASS';fs.writeFileSync(path.join(here,'revision-browser-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;}

