import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),workspace=path.resolve(project,'../..'),area=process.argv[2];assert(['molecule','dot-cross'].includes(area));
const dir=path.join(here,'..',area),json=f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8')),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const resolve=p=>p.startsWith('apps/')?path.join(workspace,p):path.join(project,p);
const manifest=json('completion.json');assert.equal(manifest.status,'PASS');assert.equal(manifest.agentId,area==='molecule'?'E03':'E02');assert.equal(manifest.jobId,area==='molecule'?'MOLECULE-RESTORE':'DOT-CROSS-RESTORE');assert(manifest.output||manifest.outputPath);for(const key of ['output','outputPath','evidence','fingerprints'])if(manifest[key])assert(fs.existsSync(resolve(manifest[key])));for(const p of manifest.evidencePaths||[])assert(fs.existsSync(resolve(p)));for(const f of manifest.artifactHashes||[])assert.equal(hash(path.join(dir,f.path)),f.sha256,f.path);assert(manifest.confidence>=0&&manifest.confidence<=1);
const fingerprints=json('source-fingerprints.json');let checked=0;
function inspect(o){if(!o||typeof o!=='object')return;if(o.path&&(o.sha256||o.currentSha256)){const full=resolve(o.path),expected=o.sha256||o.currentSha256;assert.equal(hash(full),expected,'Worker source fingerprint changed '+o.path);if(o.auditSha256)assert.equal(expected,o.auditSha256,'Original changed '+o.path);if(o.bytes!==undefined)assert.equal(fs.statSync(full).size,o.bytes);checked++;}else for(const v of Object.values(o))inspect(v);}
inspect(fingerprints);assert(checked>0);
const verification=json('verification.json');assert.equal(verification.status,'PASS');const files=area==='molecule'?['browser-results.json','compare-results.json','compare-clean-results.json','edge-results.json','rendered-review.json']:['browser-results.json','image-review.json'];
const evidence=files.map(file=>{const result=json(file);assert.equal(result.status,'PASS',file);assert.equal((result.errors||result.pageErrors||[]).length,0,file);assert.equal((result.failures||[]).length,0,file);return{path:path.relative(project,path.join(dir,file)).replaceAll('\\','/'),sha256:hash(path.join(dir,file))};});
const report={status:'PASS',checkedAt:new Date().toISOString(),agentId:manifest.agentId,jobId:manifest.jobId,fingerprintsChecked:checked,manifestPath:path.relative(project,path.join(dir,'completion.json')).replaceAll('\\','/'),manifestSha256:hash(path.join(dir,'completion.json')),verificationSha256:hash(path.join(dir,'verification.json')),evidence,foremanReview:area==='molecule'?'Relevant editor/state/C3 changes inspected; source core/content/policy/errata unchanged, atomic checked gesture history. Original/new raw and source-clean structural SVGs plus mobile B/teacher K substantively inspected. Source compact controls and discoverable local scrolling verified by owner; whole shell pixel identity not claimed.':'Relevant dot editor/engine/model/layout and shared UI changes inspected; gesture preview/cancellation, source regions/charges/circles/history/keyboard routing. Owner source-based chemistry/geometry and matching screenshots reviewed; first-attempt/timing/revision/save/teacher integration independently verified.'};
fs.writeFileSync(path.join(here,area+'-worker-validation.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,agentId:report.agentId,fingerprintsChecked:checked}));
