import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import assert from 'node:assert/strict';
import {hashCore} from './hash-core.mjs';
const project=path.resolve(import.meta.dirname,'../../..'),here=import.meta.dirname;
for(const [label,args] of [['family-tests',['--test','validation/s4/authoring-release/family.test.mjs']],['typecheck',['node_modules/typescript/bin/tsc','--noEmit']]]){const result=spawnSync(process.execPath,args,{cwd:project,encoding:'utf8'});fs.writeFileSync(path.join(here,label+'.log'),result.stdout+result.stderr);assert.equal(result.status,0,label);}
const read=p=>JSON.parse(fs.readFileSync(path.join(here,p),'utf8')),before=read('core-before.json').hashes,after=hashCore(),changed=Object.keys(before).filter(k=>before[k]!==after[k]);
assert(Object.keys(before).filter(k=>k.startsWith('src/domain/')||k.startsWith('src/persistence/')&&!k.startsWith('src/persistence/legacy/')).every(k=>before[k]===after[k]));assert.equal(before['src/foundation/registry.ts'],after['src/foundation/registry.ts']);
fs.writeFileSync(path.join(here,'core-after.json'),JSON.stringify({time:new Date().toISOString(),hashes:after},null,2));
fs.writeFileSync(path.join(here,'core-audit.json'),JSON.stringify({status:'PASS',unchangedAttemptTimerSessionMasteryRepository:true,unchangedProductionRegistry:true,changed,attribution:'A01 contracts/integration.ts; A17 ActivityHost/UI; A19 persistence/legacy*. A20 made no shared plumbing writes.',checkedAt:new Date().toISOString()},null,2));
assert.equal(read('browser-results.json').status,'PASS');assert.equal(read('release-browser-results.json').status,'PASS');
const report={id:'A20/S4-AUTHORING-RELEASE',agentId:'A20',jobId:'S4-AUTHORING-RELEASE',status:'PASS',confidence:0.97,rootAcceptance:false,completedAt:new Date().toISOString(),model:{requested:'gpt-6.1-sol',requestedEffort:'high',actualModel:null,actualEffort:null,usage:null},
 sourceOwnership:['development/authoring/','docs/authoring/','src/development/catalogue/','release/','scripts/release-s4.mjs','scripts/validate-s4-release.mjs','validation/s4/authoring-release/'],
 authoring:{independent:true,productionEnabled:false,fixedQuestions:1,generatedLevelConfigurations:72,levels:[1,2,3],curriculum:'OCR H4325.1.3(d),(f)(i), official retained2016 archive plus current departmental OCR3.1 map; current fullPDF not reread',chemistryReview:'docs/authoring/chemistry-review.md',developmentEntry:'src/development/catalogue/index.tsx',proofRegistry:'development/authoring/registry.ts',actualHost:'src/foundation/ActivityHost.tsx',newIdPrefix:'DEV-PH-v1',coreUnchangedEvidence:'validation/s4/authoring-release/core-audit.json'},
 validation:{family:'validation/s4/authoring-release/family-tests.log',typecheck:'validation/s4/authoring-release/typecheck.log',configurationInvariants:'validation/s4/authoring-release/configuration-validation.json',actualBrowser:'validation/s4/authoring-release/browser-results.json',releaseBrowser:'validation/s4/authoring-release/release-browser-results.json',renderedInspection:'validation/s4/authoring-release/rendered-review.md',scaffold:'development/authoring/families/dev-validation/authoring-plan.json'},
 releases:['alevel','igcse'].map(course=>({...read(`release-${course}-check.json`),path:`release/${course}.runtime.json`,buildAcceptance:'sample S4dist, source updates still require foreman finalbuild/regeneration/checks'})),
 preservedProbes:['browser-first-probe.json','browser-ui-transition-probe.json','browser-level-scope-probe.json','browser-scheduler-expectation-probe.json','browser-teacher-label-probe.json','browser-temp-load-probe.json'],
 limitations:['Foreman must rebuild after A17/A19 sources settle and regenerate/recheck both runtime manifests plus browser results; sample fingerprints are preserved, not finalstage acceptance.','Exact Rocket legacy-link rejection clause is approved in compatibility decoder; no Rocket functionality/assets allowed.','Earlier browser probes used default ephemeral browser profiles; final authoring/release checks direct temporary profiles/cache into project validation.','Requested actual model/effort/usage are not exposed.','No deploy/publication/oldappbuild/original-source/dependency modifications.']};
function walk(p){return fs.readdirSync(path.join(project,p),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(p+'/'+e.name):[p+'/'+e.name]);}
report.sourceFingerprints=Object.fromEntries(['development/authoring','docs/authoring','src/development/catalogue','release'].flatMap(walk).concat(['scripts/release-s4.mjs','scripts/validate-s4-release.mjs']).sort().map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(project,p))).digest('hex')]));
fs.writeFileSync(path.join(here,'completion.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({id:report.id,status:report.status,output:'validation/s4/authoring-release/completion.json',confidence:report.confidence}));
