import {chromium} from '../../../../../../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {dilutionValues,proofRef} from './family.ts';
const here=path.resolve(import.meta.dirname,'../../../../validation/component-fidelity/f1-correction/identity/authoring','__SCAFFOLD_SLUG__');fs.mkdirSync(here,{recursive:true});
const run=`A20-${Date.now()}`,report={jobId:'F1-CODEC-DEV',startedAt:new Date().toISOString(),checks:[],errors:[]};
const browserTemp=path.resolve(import.meta.dirname,'../../../../validation/component-fidelity/f1-correction/identity/.bt');fs.mkdirSync(browserTemp,{recursive:true});process.env.TEMP=browserTemp;process.env.TMP=browserTemp;process.env.TMPDIR=browserTemp;
report.browserTempRoot=browserTemp;
const browser=await chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${path.join(browserTemp,'cache')}`]}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot()),flush=()=>page.evaluate(()=>window.__mastersActivity.flush());
const url=s=>`http://127.0.0.1:5181/development/authoring/families/__SCAFFOLD_SLUG__/preview.html?run=${run}-${s}`;
const check=s=>{report.checks.push(s);console.log(s);};
async function click(name){if(name==='Back to course map')await page.getByRole('button',{name,exact:true}).first().click();else await page.getByRole('button',{name,exact:true}).click();await flush();await page.waitForTimeout(120);}
async function ready(){await page.waitForFunction(()=>window.__mastersActivity);}
async function waitAttempt(){await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);}
async function answer(wrong=false){const s=await snap(),v=dilutionValues(s.question.ref);await page.evaluate(({value,unit,wrong})=>window.__mastersActivity.respond('ph',{kind:'numeric',unit,raw:wrong?'99':value}),{value:s.question.ref.level===3?String(v.finalVolume):v.pH.toFixed(2),unit:s.question.ref.level===3?'cm³':'',wrong});await page.evaluate(()=>window.__mastersActivity.respond('change',{kind:'choice',selected:['increase']}));await flush();}
try{
 await page.goto(url('fixed'),{waitUntil:'domcontentloaded'});await ready();await page.getByText('Component examples and checked model',{exact:true}).click();await page.getByLabel('Example variant').selectOption('2');await page.screenshot({path:path.join(here,'catalogue-desktop.png'),fullPage:true});await page.getByText('Component examples and checked model',{exact:true}).click();
 await page.getByLabel('Target',{exact:true}).selectOption('u6-t1-1-2:1');await click('Start practice');await waitAttempt();let s=await snap();assert.equal(s.question.ref.questionId,proofRef(1,0).questionId);assert.equal(s.attempt.timing.idleLimitMs,180000);await answer(true);await page.waitForTimeout(1150);await click('Back to course map');const paused=await snap();assert(paused.session.paused===true);assert(paused.attempt.timing.activeMs>0);
 await page.reload();await ready();await waitAttempt();await page.getByRole('button',{name:'Check answer',exact:true}).waitFor();await flush();s=await snap();assert.equal(s.attempt.attemptId,paused.attempt.attemptId);assert.deepEqual(s.attempt.currentResponses,paused.attempt.currentResponses);assert(s.attempt.timing.activeMs>=paused.attempt.timing.activeMs);check('Fixed question real host pause/reload restores ID,seed,response and cumulative clock');
 await click('Check answer');await page.waitForFunction(()=>window.__mastersActivity.snapshot().history.length===1);s=await snap();assert.equal(s.attempt.firstAssessment.marks.earned,1);assert.equal(s.history.length,1);const first=s.attempt.firstAssessment,firstResponse=s.attempt.firstResponse;assert(firstResponse.timing.activeMs>0);assert.equal(s.history[0].timing.activeMs,firstResponse.timing.activeMs);
 await answer(false);await click('Check correction');s=await snap();assert.equal(s.correctionFeedback.marks.earned,2);assert.deepEqual(s.attempt.firstAssessment,first);assert.deepEqual(s.attempt.firstResponse,firstResponse);assert.equal(s.history.length,1);await click('Show worked answer');await page.screenshot({path:path.join(here,'fixed-correction-desktop.png'),fullPage:true});check('First1/2 marks and timing transfer to repository; corrected2/2 feedback leaves first response/evidence fixed');
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(here,'fixed-correction-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.reload();await waitAttempt();assert.deepEqual((await snap()).attempt.firstResponse,firstResponse);await click('Next question');await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,s.attempt.attemptId);s=await snap();assert.equal(s.attempt.phase,'answering');assert(s.attempt.timing.activeMs<1000);check('Completed reload preserves timing; Next creates fresh attempt through same player');
 await page.goto(url('generated'));await ready();await page.getByLabel('Target',{exact:true}).selectOption('u6-t1-1-2:2');await click('Start practice');await waitAttempt();s=await snap();assert.equal(s.question.ref.level,2);assert.match(s.question.ref.questionId,/^AB-[A-Z0-9]{6}$/);const generated=s.question;await answer();await click('Back to course map');await page.reload();await ready();await waitAttempt();await page.getByRole('button',{name:'Check answer',exact:true}).waitFor();await flush();assert.deepEqual((await snap()).question,generated);await click('Check answer');assert.equal((await snap()).attempt.firstAssessment.marks.earned,2);check('Seeded real host content reproduces exactly from ID+seed across resume; correct2/2 first assessment');
 await page.goto(url('revision')+'&session=revision');await ready();await click('ADD ALL u6-t1-1');assert.equal((await snap()).selectedCount,3);await click('Start revision');await waitAttempt();await answer();await click('Back to course map');const revision=await snap();await page.reload();await ready();await waitAttempt();await page.getByRole('button',{name:'Check answer',exact:true}).waitFor();await flush();assert.equal((await snap()).attempt.attemptId,revision.attempt.attemptId);await click('Check answer');const done=await snap();assert.equal(done.session.kind,'revision');assert.equal(done.history.length,1);await click('Next question');await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,done.attempt.attemptId);s=await snap();assert.equal(s.session.kind,'revision');assert.equal(s.history.length,1);assert.equal(s.attempt.phase,'answering');check('Revision ADDALL true three levels; saved attempt resumes; scheduler Next creates fresh attempt and preserves evidence');
 for(let i=0;i<12&&(await snap()).question.ref.level!==3;i++){await answer();await click('Check answer');const prior=await snap();assert.equal(prior.attempt.firstAssessment.marks.earned,2);await click('Next question');await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,prior.attempt.attemptId);}
 s=await snap();assert.equal(s.question.ref.level,3);assert.match(s.question.ref.questionId,/^AB-[A-Z0-9]{6}$/);await answer();await click('Check answer');assert.equal((await snap()).attempt.firstAssessment.marks.earned,2);await click('Show worked answer');await page.screenshot({path:path.join(here,'revision-level3-application.png'),fullPage:true});check('Original weighted mastery progression advances through level2 to inverse-dilution level3; genuine application assessed2/2');
 await page.goto(url('teacher')+'&mode=teacher&review='+proofRef(2,24).questionId);await page.getByRole('heading',{name:/Worked answer|Checked answer and diagrams/}).waitFor();assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,0);await page.screenshot({path:path.join(here,'teacher-generated.png'),fullPage:true});check('DEV teacher code restores seed24 checked model and creates no timing/mastery evidence');
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;await page.screenshot({path:path.join(here,'failure.png'),fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));await browser.close();}


