import fs from 'node:fs';
import path from 'node:path';
const here=import.meta.dirname,s2=path.resolve(here,'../../s2/dot-cross');
let s=fs.readFileSync(path.join(s2,'browser.mjs'),'utf8');
const revisionStart=s.indexOf(' // Real revision ADD ALL'),revisionEnd=s.indexOf(' assert.deepEqual(report.errors,[])',revisionStart);
const editorRegression=s.slice(0,revisionStart)+' // Bounded S3 A Level shared-editor regression. IGCSE host revision is covered by browser.mjs.\n'+s.slice(revisionEnd);
fs.writeFileSync(path.join(here,'alevel-editor-regression.mjs'),editorRegression.replaceAll('a10-dot-headless','a15-alevel-headless').replaceAll('browser-results.json','alevel-browser-results.json').replaceAll('.png','-alevel.png'));
s=s.replaceAll('alevel.html','igcse.html').replaceAll('alevel/dot-and-cross','igcse/dot-and-cross').replaceAll('l6-t2-1-3','fourth-3-1').replaceAll('a10-dot-headless','a15-igcse-headless').replaceAll('S2-DOTCROSS','S3-IGCSE-DOTCROSS').replaceAll('ADD ALL l6-t2-1','ADD ALL fourth-3').replaceAll('selectedCount,3','selectedCount,5').replaceAll("['sulfur-hexafluoride','magnesium-peroxide','carbonate-ion']","['aluminium-oxide','caoh2','c2h4cl2-12']").replaceAll('91-bank teacher/review path: crowded expanded shell, grouped peroxide and charged carbonate','72-bank teacher/review path: multivalent ions, grouped hydroxide and formula-isomer example');
fs.writeFileSync(path.join(here,'browser.mjs'),s);
let r=fs.readFileSync(path.join(s2,'render-bank.mjs'),'utf8').replace('alevel/dot-and-cross','igcse/dot-and-cross').replace('import {modelSVG}',"import {referenceRecord} from '../../../src/activities/igcse/dot-and-cross/types.ts';\nimport {modelSVG}").replace('records.map(modelSVG)','records.map(record=>modelSVG(referenceRecord(record)))').replaceAll('record.displayFormula','record.formula').replaceAll('record.totalCharge','0');
fs.writeFileSync(path.join(here,'render-bank.mjs'),r);
