import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
const here=import.meta.dirname,project=path.resolve(here,'../../..'),file=path.join(project,'src/editors/dot-and-cross/DotCrossEditor.tsx');
const current=fs.readFileSync(file,'utf8');
const configuration=" const igcse=part.markingPolicyId.startsWith('igcse-dot-cross:');\n const elements=igcse?allElements.filter(value=>value!=='B'&&value!=='P'):allElements;\n const symbols=igcse?allSymbols.filter(value=>value!=='triangle'):allSymbols;\n const tools:readonly Tool[]=igcse?['select','atom','dot','cross','erase']:['select','atom','dot','cross','triangle','erase'];\n const questionId=part.markingPolicyId.replace(/^(?:igcse-)?dot-cross:/,'');";
const baseline=current.replace('const allElements:','const elements:').replace('const allSymbols:','const symbols:').replace(configuration," const questionId=part.markingPolicyId.replace(/^dot-cross:/,'');").replace('{tools.map(value=>','{([\'select\',\'atom\',\'dot\',\'cross\',\'triangle\',\'erase\'] as const).map(value=>').replace("{igcse?'Dots and crosses':'Dots, crosses and triangles'} represent electron origins.",'Dots, crosses and triangles represent electron origins.');
const expected=JSON.parse(fs.readFileSync(path.join(here,'source-fingerprints.json'),'utf8')).sharedBefore.find(item=>item.path==='src/editors/dot-and-cross/DotCrossEditor.tsx').sha256;
const actual=createHash('sha256').update(baseline).digest('hex');if(actual!==expected)throw Error('Reconstructed accepted baseline does not match recorded initial fingerprint.');
const baselinePath=path.join(here,'DotCrossEditor.s2-accepted.tsx.txt');fs.writeFileSync(baselinePath,baseline);
const diff=spawnSync('git',['diff','--no-index','--',baselinePath,file],{encoding:'utf8'});if(![0,1].includes(diff.status))throw Error(diff.stderr);fs.writeFileSync(path.join(here,'shared-editor.diff'),diff.stdout);
fs.writeFileSync(path.join(here,'shared-diff-validation.json'),JSON.stringify({status:'PASS',initialFingerprintMatched:true,initialSha256:expected,changedFile:'src/editors/dot-and-cross/DotCrossEditor.tsx',baseline:'DotCrossEditor.s2-accepted.tsx.txt',diff:'shared-editor.diff',rationale:'Source-specific IGCSE dot/cross and16-element palette selected by part policy prefix; A Level palette unchanged. No chemistry/engine/layout/model changes.'},null,2));
console.log('Retained exact shared editor diff against fingerprint-verified accepted S2 baseline.');
