import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { validateRelease } from '../../scripts/validate-s4-release.mjs';
import { productionRegistry } from '../../src/foundation/registry.ts';
const project=path.resolve(import.meta.dirname,'../..');
const git='C:/Users/JELC/AppData/Local/GitHubDesktop/app-3.6.6/resources/app/git/cmd/git.exe';
const gitFiles=(...args)=>execFileSync(git,['ls-files','-z',...args],{cwd:project}).toString().split('\0').filter(Boolean);
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(project,file))).digest('hex');
const tracked=gitFiles(), untracked=gitFiles('--others','--exclude-standard');
const sourceFiles=[...new Set([...tracked,...untracked].filter(file=>/^(src|public|scripts|development)\//.test(file)))].filter(file=>fs.existsSync(path.join(project,file))).sort();
const fingerprint=crypto.createHash('sha256');
for(const file of sourceFiles)fingerprint.update(`${file}\0${hash(file)}\n`);
const sourcePreservation={fileCount:sourceFiles.length,sha256:fingerprint.digest('hex')};
assert.deepEqual(sourcePreservation,JSON.parse(fs.readFileSync(path.join(import.meta.dirname,'audit.json'))).sourcePreservation,'Cleanup must preserve every source byte');
const retained=JSON.parse(fs.readFileSync(path.join(project,'validation/s3/c3l6/output-fingerprints.json')));
assert.equal(retained.status,'PASS');
const assets=[...new Set([...tracked,...untracked])].filter(file=>file.startsWith('src/activities/olympiad/c3l6/assets/') && file.endsWith('.svg')).map(file=>{
  const sha256=hash(file),approved=retained.files.find(entry=>entry.path===file);
  assert(approved,`Missing retained approval: ${file}`);assert.equal(sha256,approved.sha256,`Approved asset changed: ${file}`);
  return {path:file,sha256,approval:'validation/s3/c3l6/output-fingerprints.json'};
});
const definition=productionRegistry.activities.find(entry=>entry.id==='alevel/c3l6-organic-reactions');
assert.equal(definition.title,'A Class of their Own');
const definitions=fs.readFileSync(path.join(project,'src/catalogue/definitions.ts'),'utf8');
assert(definitions.includes(hash('src/activities/alevel/explaining-properties/bank.ts')),'Catalogue provenance must describe the actual accepted bank');
const result={status:'PASS',checkedAt:new Date().toISOString(),sourcePreservation,approvedRuntimeSvgAssets:assets.length,assets,releaseChecks:['alevel','igcse'].map(validateRelease),metadataChecks:['Accepted C3 title matches generator/catalogue','Explaining Properties source fingerprint matches current accepted bank']};
fs.writeFileSync(path.join(import.meta.dirname,'verification.json'),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({...result,assets:undefined}));
