import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),worker='validation/s5/render-release/session-only-save-fix',raw=worker+'/fa9-live-region-assumption',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
fs.mkdirSync(path.join(here,'retained'),{recursive:true});
const paths=[raw+'/mobile-awaited-proposal.mjs',worker+'/mobile-live-region-proposal.mjs',raw+'/mobile-results.json',raw+'/alevel-terminal-failure.json',raw+'/igcse-terminal-failure.json',raw+'/alevel-terminal-failure.png',raw+'/igcse-terminal-failure.png',raw+'/disposition.json',worker+'/fixtures.mjs',worker+'/server.mjs','src/ui/QuestionPlayer.tsx','src/foundation/ActivityHost.tsx','validation/s5/integration/freeze-current.json'];
const hashes={};for(const p of paths){const b=fs.readFileSync(path.join(project,p)),dest=path.join(here,'retained',p);fs.mkdirSync(path.dirname(dest),{recursive:true});if(!fs.existsSync(dest))fs.writeFileSync(dest,b);assert.equal(sha(fs.readFileSync(dest)),sha(b));hashes[p]={sha256:sha(b),retained:path.relative(project,dest).replaceAll('\\','/')};}
const baseline=fs.readFileSync(path.join(project,paths[0]),'utf8'),proposal=fs.readFileSync(path.join(project,paths[1]),'utf8');
assert.equal(sha(Buffer.from(baseline)),'1e46d79fc827cd238f52b0fe9192caa0ccd6c9886c5865c7a1c4fb601b4aca1a');assert.equal(sha(Buffer.from(proposal)),'d0190eb5b0c044eebd8bc45ae0d22e31e771dd74a0a016233e3bd2bc320f9581');
const replacements=[
 ["const alert=page.getByRole('alert');await alert.waitFor();assert.match(await alert.innerText(),/Work has not saved[\\s\\S]*Storage is full/);","const alert=kind==='terminal'?page.locator('.question-player .save-status.save-error'):page.getByRole('alert');await alert.waitFor();if(kind==='terminal')assert.equal(await alert.getAttribute('aria-live'),'polite');assert.match(await alert.innerText(),/Work has not (?:been )?saved[\\s\\S]*Storage is full/);"],
 ["keyboardRetry:true,roleAlert:true,pausedStatus:","keyboardRetry:true,errorAnnouncement:kind==='terminal'?'aria-live polite':'role alert',pausedStatus:"]
];let transformed=baseline;for(const [old,next]of replacements){assert.equal(transformed.split(old).length,2);transformed=transformed.replace(old,next);}assert.equal(transformed,proposal,'Only reviewed selector/text/accurate report metadata changes allowed');
const diff=spawnSync('git',['diff','--no-index','--',path.join(project,paths[0]),path.join(project,paths[1])],{encoding:'utf8'});assert.equal(diff.status,1);fs.writeFileSync(path.join(here,'proposal.diff'),diff.stdout);
const player=fs.readFileSync(path.join(project,'src/ui/QuestionPlayer.tsx'),'utf8'),host=fs.readFileSync(path.join(project,'src/foundation/ActivityHost.tsx'),'utf8');assert(player.includes('className={`save-status save-${saveStatus.kind}`} aria-live="polite"'));assert(player.includes('<strong>Work has not been saved.</strong>'));assert(host.includes('<div className="save-error" role="alert">'));assert(host.includes('<p>Work has not saved. {saveStatus.error.message}</p>'));assert.equal(hashes['src/foundation/ActivityHost.tsx'].sha256,'bd69aee5a89e1bcdf61ed8f22b134654b18096910b92de7e37040c7a07391d9e');
const freeze=JSON.parse(fs.readFileSync(path.join(project,'validation/s5/integration/freeze-current.json'),'utf8'));assert.equal(freeze.treeSha256,'fa9b70c77954462612fb26a8d125d255f0af3456efff569d53a8ae3fa3dd3c52');const controls=freeze.currentInputHashes.filter(p=>p.path.startsWith('dist/')||['src/ui/QuestionPlayer.tsx','src/foundation/ActivityHost.tsx'].includes(p.path));for(const p of controls)assert.equal(sha(fs.readFileSync(path.join(project,p.path))),p.sha256);
const original=JSON.parse(fs.readFileSync(path.join(project,raw+'/mobile-results.json'),'utf8'));assert.equal(original.status,'FAIL');assert.equal(original.checks.length,4);assert.deepEqual(original.failures.map(f=>f.id),['alevel-terminal','igcse-terminal']);assert.equal(original.pageErrors.length,0);
const facts=[];for(const course of ['alevel','igcse']){const f=JSON.parse(fs.readFileSync(path.join(project,raw+'/'+course+'-terminal-failure.json'),'utf8'));assert(f.error.includes("waiting for getByRole('alert')"));assert(f.dom.includes('Work has not been saved. Storage is full.'));assert(f.dom.includes('Retry save'));assert(!f.dom.includes('Revision complete'));assert.equal(f.before.sessions[0].status,'active');facts.push({course,error:'getByRole(alert) timeout',actualBodyText:'Work has not been saved. Storage is full. Your current work remains in memory; free space and retry.Retry save',priorDurableStatus:f.before.sessions[0].status,rawLimit:'Failure capture contains before rows and body text only; it does not independently prove post-error durable equality or live announcement.'});}
const report={agentId:'A06',jobId:'S5-REVIEW-MOBILE-LIVE-REGION-HARNESS',status:'PASS',confidence:'high',verifiedAt:new Date().toISOString(),approval:'ONE exact source-backed mobile continuation using d019 proposal; behavior gates remain with A23/A21',approvedProposal:{path:paths[1],sha256:hashes[paths[1]].sha256},baseline:{path:paths[0],sha256:hashes[paths[0]].sha256},checks:['Raw failures preserved; four empty cases PASS and two terminal alert-role timeouts retained','Both screenshots inspected: visible work-unsaved/full-storage error and Retry; no false completed UI','Exact two textual patch operations explain entire diff; all later durable/Next-disabled/focus-visible/Enter/immutable/reload assertions unchanged','Terminal selector targets actual QuestionPlayer error region and asserts aria-live=polite plus strong failed/quota wording','Paused branch retains getByRole(alert); wording accepts both source variants','Original awaited durable polling and 30000ms deadline byte-preserved','Current approved Host and QuestionPlayer plus served production files match fa9 freeze'],facts,controlsChecked:controls.length,freezeTree:freeze.treeSha256,hashes,limits:['No browser executed by reviewer; screenshot/body text plus source provide fixture-cause evidence','aria-live polite describes intended live-region semantics; no actual native screen-reader speech or AX live-announcement claim','Post-error durable equality, keyboard Retry, recovered completion and reload assertions in terminal continuation remain unexecuted','No product correctness acceptance inferred from harness approval'],requestedSettings:{model:'gpt-6.1-sol',effort:'high'},effectiveSettings:null,actualUsage:null};fs.writeFileSync(path.join(here,'verification.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(here,'completion.json'),JSON.stringify({agentId:report.agentId,jobId:report.jobId,status:report.status,confidence:report.confidence,outputPath:'validation/s5/review-session-only-save/mobile-fixture-review/verification.json',approvedProposal:report.approvedProposal,reason:'Exact terminal save-error live-region fixture correction approved once; all substantive gates retained and pending.',validation:report.checks,effectiveSettings:null,actualUsage:null},null,2)+'\n');console.log(JSON.stringify({status:report.status,approvedProposal:report.approvedProposal,controlsChecked:controls.length,failuresRetained:original.failures.map(f=>f.id)}));
