import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {seedStatic} from '../../render-release/seed-static.mjs';
import {bank} from '../../../../src/activities/igcse/energy-enthalpy/provider.ts';
import {checkProfile} from '../../../../src/chemistry/energy-profile/index.ts';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),require=createRequire(path.join(project,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');const {chromium}=require('playwright');fs.mkdirSync(path.join(here,'t'),{recursive:true});process.env.TEMP=path.join(here,'t');process.env.TMP=process.env.TEMP;
const browser=await chromium.launch({channel:'msedge',headless:true}),report={agentId:'A06',jobId:'S5-REVIEW-ENERGY-NEXT-CLASSIFICATION',startedAt:new Date().toISOString(),browser:await browser.version(),settings:{cpu:4,viewport:{width:390,height:844},network:{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750}},cases:[],errors:[]};
async function durable(p){return p.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('masters-of-chemistry-igcse-local');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});try{const result={};for(const table of ['attempts','sessions','evidence'])result[table]=await new Promise((r,j)=>{const q=db.transaction(table).objectStore(table).getAll();q.onsuccess=()=>r(q.result.map(x=>x.value));q.onerror=()=>j(q.error)});return result;}finally{db.close()}});}
async function type(p,input,value,commit=true){await input.focus();await p.keyboard.press('Control+A');await p.keyboard.press('Backspace');await input.pressSequentially(value,{delay:40});assert.equal(await input.inputValue(),value);if(commit)await input.press('Enter');}
async function dom(p){return p.evaluate(()=>({code:document.querySelector('.question-meta code')?.textContent,save:document.querySelector('.save-status')?.textContent,nextDisabled:[...document.querySelectorAll('button')].find(x=>x.textContent==='Next question')?.disabled,focused:document.activeElement?.getAttribute('aria-label')||document.activeElement?.textContent,draft:document.querySelector('input[aria-label="Peak level screen y"]')?.value,events:window.__nextEvents}));}
try{
 for(const mode of ['unfinished-draft','clean-control']){
  const context=await browser.newContext({viewport:report.settings.viewport}),p=await context.newPage(),cdp=await context.newCDPSession(p);p.on('pageerror',e=>report.errors.push({mode,error:e.message}));await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',report.settings.network);
  const q=bank.questions.find(q=>q.id==='D03'),ref={activityId:'igcse/energy-enthalpy',questionId:'D03',seed:0,level:2};await seedStatic(p,ref,'A06-classify-'+mode);const url=p.url();await p.goto(new URL('.vite/manifest.json',url).href);await p.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('masters-of-chemistry-igcse-local');q.onsuccess=()=>r(q.result)});await new Promise(r=>{const t=db.transaction('sessions','readwrite'),s=t.objectStore('sessions'),q=s.get(['igcse','local','current-session']);q.onsuccess=()=>{q.result.value.previousQuestionIds=['D03'];s.put(q.result)};t.oncomplete=r});db.close()});await p.goto(url);await p.locator('.question-player').waitFor();
  await type(p,p.getByLabel('Peak level screen y',{exact:true}),'150');await p.getByText('Saved on this device',{exact:true}).waitFor();await p.getByRole('button',{name:'Add activation energy arrow',exact:true}).click();const field=p.locator('fieldset').filter({has:p.locator('legend').filter({hasText:/^Activation energy arrow$/})}).last();await field.getByLabel('Tail',{exact:true}).selectOption('free');await field.getByLabel('Arrowhead',{exact:true}).selectOption('free');await type(p,field.getByLabel('Endpoint screen y',{exact:true}).first(),'240');await type(p,field.getByLabel('Endpoint screen y',{exact:true}).last(),'160');await type(p,field.getByLabel('Arrow x position',{exact:true}),'300');await p.getByText('Saved on this device',{exact:true}).waitFor();await p.reload();await p.locator('.question-player').waitFor();await p.getByLabel('Left formula label',{exact:true}).selectOption(q.editor.formula[0]);await p.getByLabel('Right formula label',{exact:true}).selectOption(q.editor.formula[1]);await p.getByRole('button',{name:'Add enthalpy change arrow',exact:true}).click();await p.getByText('Saved on this device',{exact:true}).waitFor();const ready=await durable(p);assert.equal(checkProfile(ready.attempts[0].currentResponses.profile,q).status,'ready');assert.deepEqual(ready.sessions[0].previousQuestionIds,['D03']);await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.getByRole('button',{name:'Next question',exact:true}).waitFor();await p.getByText('Saved on this device',{exact:true}).waitFor();
  await p.evaluate(()=>{window.__nextEvents=[];const snap=(type,event)=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent==='Next question'),active=document.activeElement;window.__nextEvents.push({type,at:performance.now(),wall:Date.now(),code:document.querySelector('.question-meta code')?.textContent,nextDisabled:button?.disabled,save:document.querySelector('.save-status')?.textContent,focused:active?.getAttribute('aria-label')||active?.textContent?.slice(0,80),...(event?{trusted:event.isTrusted,targetTag:event.target?.tagName,target:event.target?.getAttribute?.('aria-label')||event.target?.textContent?.slice(0,80),key:event.key}:{} )})};for(const type of ['pointerdown','mousedown','focusin','focusout','blur','pointerup','mouseup','click','keydown','input'])document.addEventListener(type,e=>{if(e.target?.matches?.('input')||e.target?.textContent==='Next question')snap(type,e)},true);let last='';new MutationObserver(()=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent==='Next question'),signature=JSON.stringify([button?.disabled,document.querySelector('.save-status')?.textContent,document.querySelector('.question-meta code')?.textContent]);if(signature!==last){last=signature;snap('state-mutation')}}).observe(document.body,{subtree:true,attributes:true,childList:true,characterData:true});snap('installed');});
  const before=await durable(p);assert.equal(before.attempts[0].phase,'assessed');assert.equal(before.evidence.length,1);if(mode==='unfinished-draft')await type(p,p.getByLabel('Peak level screen y',{exact:true}),'270',false);const beforeClick=await dom(p);await p.getByRole('button',{name:'Next question',exact:true}).click();let changed=false;try{await p.waitForFunction(()=>document.querySelector('.question-meta code')?.textContent!=='D03',null,{timeout:5000});changed=true}catch{}const afterClick=await dom(p),after=await durable(p);const result={mode,before,beforeClick,changed,afterClick,after};await p.screenshot({path:path.join(here,mode+'.png'),fullPage:true});
  if(mode==='unfinished-draft'&&!changed){await p.getByText('Saved on this device',{exact:true}).waitFor();await p.getByRole('button',{name:'Next question',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.question-meta code')?.textContent!=='D03',null,{timeout:5000});result.secondClick={dom:await dom(p),durable:await durable(p)};}
  report.cases.push(result);fs.writeFileSync(path.join(here,'execution.json'),JSON.stringify(report,null,2)+'\n');await context.close();
 }
 assert.equal(report.errors.length,0);report.status='CAPTURED';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'execution.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({status:report.status,cases:report.cases.map(c=>({mode:c.mode,changed:c.changed,nextEvents:c.afterClick.events.filter(e=>e.target==='Next question').map(e=>({type:e.type,disabled:e.nextDisabled,trusted:e.trusted})),beforeId:c.before.sessions[0].currentAttemptId,afterId:c.after.sessions[0].currentAttemptId,recovered:c.secondClick?.durable.sessions[0].currentAttemptId})),failure:report.failure}));}
