import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {reviewedMethanolSynthesisSVG} from '../../../src/chemistry/thermochemistry/reviewed-co-svg.ts';
import {data} from '../../../src/chemistry/thermochemistry/bond-enthalpy-data.js';
const project=path.resolve(import.meta.dirname,'../../..');
const read=f=>JSON.parse(fs.readFileSync(path.join(project,f),'utf8').replace(/^\uFEFF/,''));
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const sets=['electrons/output-fingerprints.json','thermochemistry/output-fingerprints.json','energy/output-fingerprints.json','titration/output-fingerprints.json','igcse-dot-cross/final-output-fingerprints.json','c3l6/output-fingerprints.json'];
const checks=[];
for(const file of sets){const d=read('validation/s3/'+file),rows=Array.isArray(d)?d:d.files??Object.entries(d).map(([path,sha256])=>({path,sha256}));for(const row of rows)assert.equal(hash(fs.readFileSync(path.join(project,row.path))),row.sha256,row.path);checks.push({file,count:rows.length,status:'PASS'});}
const p=read('validation/s3/review-co/provenance.json'),old=data.reactions.find(r=>r.id==='methanol-synthesis').svg;
assert.equal(hash(old),p.source.originalSvgSha256);assert.equal(hash(reviewedMethanolSynthesisSVG),p.correction.newSvgSha256);assert.equal(reviewedMethanolSynthesisSVG.replace(p.correction.insertedElement,''),old);
assert.equal(hash(fs.readFileSync(path.join(project,p.correction.output))),p.correction.outputSha256);
assert.equal(hash(fs.readFileSync(path.resolve(project,'../../',p.source.file))),p.source.fileSha256);
assert.equal(hash(fs.readFileSync(path.join(project,'src/chemistry/thermochemistry/bond-enthalpy-data.js'))),p.source.copiedDataFileSha256);
for(const row of [...p.validation.manualVisualInspection.images,...p.validation.scripts])assert.equal(hash(fs.readFileSync(path.join(project,'validation/s3/review-co',row.path))),row.sha256,row.path);
assert.equal(read('validation/s3/review-co/chemistry-check.json').status,'PASS');assert.equal(read('validation/s3/review-co/render-results.json').status,'PASS');
checks.push({id:'CO-independent-reviewed-exception',status:'PASS',sameOriginalBytesAfterRemovingOneApprovedPath:true,unchangedCalculation:-119});
const result={status:'PASS',checkedAt:new Date().toISOString(),checks,scope:'Foreman independently verifies final owned runtime hashes and exact CO correction/provenance/render evidence; substantive bank chemistry and manual render reviews remain assigned worker evidence.'};fs.writeFileSync(path.join(import.meta.dirname,'owned-verification.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
