import type {TitrationRecord,CurveResponse,CurvePiece,Indicator,CurveAnswer,CurveGrade,CurvePoint} from './types.ts';
export const KW:number;
export function snap(x:number,step:number):number;
export function clamp(x:number,a:number,b:number):number;
export function quantities(q:TitrationRecord):{volume:number;initial:number;titrant:number};
export function equivalenceVolume(q:TitrationRecord):number;
export function chargeResidual(q:TitrationRecord,v:number,pH:number,opts?:{acidWeak:boolean;baseWeak:boolean;reverse:boolean}):number;
export function equilibriumPH(q:TitrationRecord,v:number,opts?:{acidWeak:boolean;baseWeak:boolean;reverse:boolean}):number;
export function answer(q:TitrationRecord):CurveAnswer;
export function initial(q:TitrationRecord):CurveResponse;
export const pieces:readonly CurvePiece[];
export const indicators:readonly Indicator[];
export function suitableIndicators(q:TitrationRecord):readonly string[];
export function curve(q:TitrationRecord,s:CurveResponse):{before:readonly CurvePoint[];after:readonly CurvePoint[];equivalencePH:number};
export function grade(q:TitrationRecord,s:CurveResponse):CurveGrade;
