import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const here=import.meta.dirname,project=path.resolve(here,'../../../..');
const require=createRequire(path.join(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');
const temp=path.join(here,'.browser-tmp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const base=process.env.QUESTION_SOURCE_URL||'http://127.0.0.1:5183';
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true});
const report={startedAt:new Date().toISOString(),method:'Pinned root Playwright1.62.1, current source Vite, headless Edge with fresh isolated contexts/current-app run databases. Actual UI navigation, inputs, checks and picker; reference drawing fixtures use retained DEV response harness. Persistence inspection supplies invisible timing evidence.',checks:[],failures:[],pageErrors:[]};
const snapshot=page=>page.evaluate(()=>window.__mastersActivity.snapshot());
async function ready(page){await page.locator('.question-player,.dot-cross-player').waitFor();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().saveStatus.kind==='saved');await page.waitForTimeout(80);}
async function flush(page){await page.evaluate(()=>window.__mastersActivity.flush());await page.waitForFunction(()=>window.__mastersActivity.snapshot().saveStatus.kind!=='saving');}
async function dbRows(page,databaseName){return page.evaluate(async(databaseName)=>{const s=databaseName?{databaseName}:window.__mastersActivity?.snapshot()||window.__mastersOlympiad.snapshot();const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(s.databaseName);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const result={};try{for(const table of ['attempts','sessions','evidence','olympiad'])result[table]=await new Promise((resolve,reject)=>{const r=db.transaction(table).objectStore(table).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return result;}finally{db.close();}},databaseName);}
async function numericResponse(page){await page.evaluate(async()=>{const s=window.__mastersActivity.snapshot();for(const part of s.question.parts){if(part.kind!=='numeric')throw Error('Numeric fixture required');await window.__mastersActivity.respond(part.id,{kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit});}await window.__mastersActivity.flush();});}
async function dotResponse(page){return page.evaluate(async()=>{const s=window.__mastersActivity.snapshot();const m=await import(`/src/activities/${s.question.ref.activityId}/provider.ts`);const raw=m.getRecord(s.question.ref.questionId);const response={kind:'dot-and-cross',...structuredClone(raw.reference),circles:false};await window.__mastersActivity.respond('diagram',response);await window.__mastersActivity.flush();return response;});}
async function chrome(page,expected,level,course){const h=page.locator('.question-subject');assert.equal(await h.textContent(),`${course==='alevel'?'A Level Chemistry':'IGCSE Chemistry'} - ${expected}`);assert.equal(await page.locator('.header-question-code').count(),1);const s=await snapshot(page);assert.equal((await page.locator('.header-question-code').textContent()).trim(),s.question.ref.questionId);assert.equal(await page.locator('.platform-navigation,.course-navigation,.focus-controls,.practice-progress,.pause-notice,.development-verification').count(),0);const text=await page.locator('body').innerText();assert(!/\b(?:Pause|Resume)\b|Active answering time|Active time:|saved practice results?/.test(text),text);const label=course==='alevel'?`LEVEL ${level} QUESTION`:[null,'GRADE 5–6 QUESTION','GRADE 7–8 QUESTION','GRADE 9 QUESTION'][level];assert.equal(await page.locator('.question-level-pill').textContent(),label);const colours=['','rgb(255, 222, 89)','rgb(84, 245, 181)','rgb(197, 154, 255)'];assert.equal(await page.locator('.question-level-pill').evaluate(el=>getComputedStyle(el).color),colours[level]);assert.equal(await page.locator('.header-question-code').evaluate(el=>getComputedStyle(el).color),'rgb(255, 94, 203)');assert(await page.locator('.question-back').isVisible());return{title:await h.textContent(),id:s.question.ref.questionId,pill:label};}
async function launch(page,course,activity,gem,level=1,run='q-'+course+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)){await page.goto(`${base}/${course}.html?course=${course}&run=${run}&activity=${course}/${activity}&gem=${gem}&practice=fixed-level&level=${level}&fresh=1`);await ready(page);return{run,initial:await snapshot(page)};}
async function scenario(id,fn){const context=await browser.newContext(),page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push({id,message:e.message}));await context.addInitScript(()=>{window.qWrites=[];window.qFailAttempts=false;window.qFailSessions=false;window.qFailEvidence=false;window.qFailOlympiad=false;const put=IDBObjectStore.prototype.put,add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.put=function(...args){window.qWrites.push({table:this.name,id:args[0]?.id,value:args[0]?.value});if(this.name==='attempts'&&window.qFailAttempts||this.name==='sessions'&&window.qFailSessions||this.name==='olympiad'&&window.qFailOlympiad)throw new DOMException('Question chrome quota fixture','QuotaExceededError');return put.apply(this,args);};IDBObjectStore.prototype.add=function(...args){if(this.name==='evidence'&&window.qFailEvidence)throw new DOMException('Question chrome evidence quota fixture','QuotaExceededError');return add.apply(this,args);};});try{report.checks.push({id,status:'PASS',...await fn(page,context)});console.log('PASS '+id);}catch(error){report.failures.push({id,error:error.stack});await page.screenshot({path:path.join(here,id+'-failure.png'),fullPage:true}).catch(()=>{});console.log('FAIL '+id+' '+error.message);}finally{await context.close();}}
try {
  for(const course of ['alevel','igcse'])for(const level of [1,2,3])await scenario(`${course}-pill-${level}`,async page=>{const {run}=await launch(page,course,course==='alevel'?'acid-base-calculations':'calorimetry',course==='alevel'?'u6-t1-1-7':'lower-10-3',level);return{run,...await chrome(page,course==='alevel'?'Making Buffers':'Calorimetry',level,course)};});
  await scenario('numeric-first-freeze-current-reload-next-statistics',async page=>{
    const {run,initial}=await launch(page,'alevel','acid-base-calculations','u6-t1-1-7');await numericResponse(page);await page.waitForTimeout(1150);await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.locator('.assessment-feedback').waitFor();await flush(page);const first=await snapshot(page);assert.equal(first.attempt.phase,'assessed');assert.equal(first.history.length,1);assert(first.attempt.firstResponse.timing.activeMs>500);assert.deepEqual(first.history[0].timing,first.attempt.firstResponse.timing);const immutable=structuredClone([first.attempt.firstResponse,first.attempt.firstAssessment,first.history]);await page.waitForTimeout(1600);await page.reload();await ready(page);const restored=await snapshot(page);assert.equal(restored.attempt.attemptId,initial.attempt.attemptId);assert.deepEqual([restored.attempt.firstResponse,restored.attempt.firstAssessment,restored.history],immutable);await page.getByRole('button',{name:'Check correction',exact:true}).click();await flush(page);assert.deepEqual([(await snapshot(page)).attempt.firstResponse,(await snapshot(page)).attempt.firstAssessment,(await snapshot(page)).history],immutable);await page.getByRole('button',{name:'Next question',exact:true}).click();await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,first.attempt.attemptId);await ready(page);const next=await snapshot(page);assert.equal(next.attempt.phase,'answering');assert.equal(next.history.length,1);assert.equal(Object.keys(next.attempt.currentResponses).length,0);assert(next.attempt.timing.activeMs<1500);await page.locator('.question-back').click();await page.locator('.original-landing').waitFor();await page.getByRole('button',{name:'Stats',exact:true}).click();await page.locator('.statistics').waitFor();const record=page.locator(`[data-evidence-id="${first.attempt.attemptId}"]`);await record.locator(':scope > summary').click();assert(await record.getByText('Recorded active time',{exact:true}).isVisible());assert(await page.locator('.statistics-chart').isVisible());const rows=await page.evaluate(async(databaseName)=>{const db=await new Promise(resolve=>{const r=indexedDB.open(databaseName);r.onsuccess=()=>resolve(r.result)});try{return await new Promise(resolve=>{const r=db.transaction('evidence').objectStore('evidence').getAll();r.onsuccess=()=>resolve(r.result)});}finally{db.close();}},first.databaseName);assert.equal(rows.length,1);assert.deepEqual(rows[0].value.timing,first.history[0].timing);await page.screenshot({path:path.join(here,'numeric-statistics.png'),fullPage:true});return{run,firstAttemptId:first.attempt.attemptId,firstActiveMs:first.attempt.firstResponse.timing.activeMs,immutableAfterReloadCorrection:true,nextAttemptId:next.attempt.attemptId,statisticsTiming:rows[0].value.timing};
  });
  for(const course of ['alevel','igcse'])await scenario(`${course}-historical-paused-drawing-auto-restore`,async page=>{
    const gem=course==='alevel'?'l6-t2-1-3':'fourth-3-2';const {run,initial}=await launch(page,course,'dot-and-cross',gem,1);await dotResponse(page);await page.waitForTimeout(900);await page.locator('.question-brand-mark').click();await page.locator('.original-landing').waitFor();const stored=await page.evaluate(async(databaseName)=>{const db=await new Promise(resolve=>{const r=indexedDB.open(databaseName);r.onsuccess=()=>resolve(r.result);});try{const rows=await new Promise(resolve=>{const r=db.transaction('sessions').objectStore('sessions').getAll();r.onsuccess=()=>resolve(r.result);});if(!rows[0].value.paused)throw Error('Guard did not persist historical pause');return rows[0].value;}finally{db.close();}},initial.databaseName);const savedBeforeAway=(await dbRows(page,initial.databaseName)).attempts[0].value;await page.waitForTimeout(2300);await page.goto(`${base}/${course}.html?course=${course}&view=practice&run=${run}`);await ready(page);const resumed=await snapshot(page);assert.equal(resumed.attempt.attemptId,initial.attempt.attemptId);assert.deepEqual(resumed.attempt.ref,initial.attempt.ref);assert.equal(resumed.attempt.currentResponses.diagram.circles,false);assert.equal(resumed.session.paused,false);const rows=await dbRows(page);assert.equal(rows.attempts.length,1);assert.equal(rows.evidence.length,0);assert.equal(rows.sessions[0].value.paused,false);const afterResume=resumed.attempt.timing.activeMs;const lastStored=savedBeforeAway.timing.activeMs;assert(afterResume-lastStored>=0&&afterResume-lastStored<1500);assert.deepEqual(resumed.attempt.currentResponses,savedBeforeAway.currentResponses);await chrome(page,course==='alevel'?'Dot-and-Cross Diagrams':'Covalent bonding',1,course);await page.screenshot({path:path.join(here,course+'-auto-restored-dot.png'),fullPage:true});return{run,attemptId:resumed.attempt.attemptId,storedPaused:stored.paused,resumedDurably:true,drawingsAndRefExact:true,awayMs:2300,timingCheckpoint:lastStored};
  });
  await scenario('paused-restoration-session-save-failure-retry',async(page,context)=>{
    const {run,initial}=await launch(page,'alevel','acid-base-calculations','u6-t1-1-7');await numericResponse(page);await page.locator('.question-back').click();await page.locator('.original-landing').waitFor();await context.addInitScript(()=>{window.qFailSessions=true;});await page.goto(`${base}/alevel.html?course=alevel&view=practice&run=${run}`);await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();assert.equal(await page.locator('.question-player').count(),0);const blocked=await snapshot(page);assert.equal(blocked.session.paused,true);const rows=await dbRows(page);assert.equal(rows.sessions[0].value.paused,true);const before=blocked.attempt.timing.activeMs;await page.waitForTimeout(2100);assert.equal((await snapshot(page)).attempt.timing.activeMs,before);await page.evaluate(()=>window.qFailSessions=false);await page.getByRole('button',{name:'Retry save',exact:true}).click();await ready(page);const resumed=await snapshot(page);assert.equal(resumed.attempt.attemptId,initial.attempt.attemptId);assert.equal(resumed.session.paused,false);assert.deepEqual(resumed.attempt.currentResponses,blocked.attempt.currentResponses);return{run,attemptId:resumed.attempt.attemptId,failureBlocksAnswering:true,failedAwayMsExcluded:2100,retryDurable:true};
  });
  await scenario('fresh-request-does-not-save-or-resume-old-attempt',async page=>{
    const {run,initial}=await launch(page,'alevel','acid-base-calculations','u6-t1-1-7');await numericResponse(page);await page.locator('.question-back').click();await page.locator('.original-landing').waitFor();await page.goto(`${base}/alevel.html?course=alevel&run=${run}&activity=alevel/acid-base-calculations&gem=u6-t1-1-3&level=2&fresh=1`);await ready(page);const fresh=await snapshot(page);assert.notEqual(fresh.attempt.attemptId,initial.attempt.attemptId);assert.equal(fresh.attempt.target.gemId,'u6-t1-1-3');assert.equal(fresh.attempt.ref.level,2);assert.equal(Object.keys(fresh.attempt.currentResponses).length,0);const writes=await page.evaluate(()=>window.qWrites);assert(!writes.some(w=>w.table==='attempts'&&w.id===initial.attempt.attemptId));const rows=await dbRows(page);assert.equal(rows.attempts.length,2);assert.equal(rows.evidence.length,0);await chrome(page,'Kw & Strong Bases',2,'alevel');return{run,oldAttemptId:initial.attempt.attemptId,newAttemptId:fresh.attempt.attemptId,oldAttemptWrites:0,strictModeAttemptRows:2};
  });
  await scenario('back-save-failure-keeps-identity-and-retry-leaves',async page=>{
    const {run,initial}=await launch(page,'alevel','acid-base-calculations','u6-t1-1-7');await page.evaluate(()=>window.qFailAttempts=true);await numericResponse(page);await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();const url=page.url();await page.locator('.question-back').click();await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();await flush(page);assert.equal(page.url(),url);assert.equal((await snapshot(page)).attempt.attemptId,initial.attempt.attemptId);await page.evaluate(()=>window.qFailAttempts=false);await page.getByRole('button',{name:'Retry save',exact:true}).click();await ready(page);await page.locator('.question-back').click();await page.locator('.original-landing').waitFor();return{run,attemptId:initial.attempt.attemptId,faultBlocksBack:true,retryLeaves:true};
  });
  await scenario('teacher-provider-title-and-no-student-evidence',async page=>{
    const run='q-teacher-'+Date.now();await page.goto(`${base}/alevel.html?course=alevel&view=teacher&activity=alevel/acid-base-calculations&run=${run}`);await page.locator('.teacher-answer').waitFor();const option=await page.getByLabel('Teacher question',{exact:true}).locator('option').evaluateAll(options=>options.find(o=>o.textContent.includes('buffer-component-ratio')&&o.textContent.includes('Level 1'))?.value);assert(option);await page.getByLabel('Teacher question',{exact:true}).selectOption(option);await page.waitForFunction(()=>document.querySelector('.question-subject')?.textContent==='A Level Chemistry - Making Buffers');assert.equal(await page.locator('.header-question-code').count(),1);assert(await page.getByText('This read-only view creates no assessment or progress evidence.',{exact:true}).isVisible());assert.equal(await page.getByRole('button',{name:'Check answer',exact:true}).count(),0);let rows=await dbRows(page);assert.deepEqual([rows.attempts.length,rows.evidence.length],[0,0]);await page.getByLabel('Teacher activity',{exact:true}).selectOption('alevel/electron-configurations');await page.waitForFunction(()=>document.querySelector('.question-subject')?.textContent==='A Level Chemistry - Electron configurations');await page.locator('.electron-configuration-editor').waitFor().catch(()=>{});rows=await dbRows(page);assert.deepEqual([rows.attempts.length,rows.evidence.length],[0,0]);return{run,teacherActualProviderHeading:true,teacherNoEvidence:true};
  });
  await scenario('revision-identical-continuation-changed-selection-isolated',async page=>{
    const run='q-revision-'+Date.now();const landing=async(gem)=>{await page.goto(`${base}/alevel.html?course=alevel&view=home&run=${run}`);await page.locator('.original-landing').waitFor();await page.evaluate(gem=>localStorage.setItem('masters-of-chemistry:landing:v1:alevel:selection',JSON.stringify([gem])),gem);await page.reload();await page.locator('.original-landing').waitFor();await page.getByRole('button',{name:'Revision',exact:true}).click();await page.getByRole('button',{name:'Go: start revision',exact:true}).click();await ready(page);};await landing('u6-t1-1-7');const first=await snapshot(page);assert.equal(first.session.kind,'revision');await numericResponse(page);const response=(await snapshot(page)).attempt.currentResponses;await page.locator('.question-back').click();await page.locator('.original-landing').waitFor();await landing('u6-t1-1-7');const same=await snapshot(page);assert.equal(same.attempt.attemptId,first.attempt.attemptId);assert.deepEqual(same.attempt.currentResponses,response);await chrome(page,'Making Buffers',same.attempt.ref.level,'alevel');await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.locator('.assessment-feedback').waitFor();await flush(page);await page.getByRole('button',{name:'Next question',exact:true}).click();await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,first.attempt.attemptId);await ready(page);const next=await snapshot(page);assert.equal(next.session.current.attemptId,next.attempt.attemptId);assert.equal(next.history.length,1);await chrome(page,'Making Buffers',next.attempt.ref.level,'alevel');await page.locator('.question-back').click();await page.locator('.original-landing').waitFor();await landing('u6-t1-1-3');const changed=await snapshot(page);assert.notEqual(changed.attempt.attemptId,next.attempt.attemptId);assert.equal(changed.attempt.target.gemId,'u6-t1-1-3');assert.equal(changed.history.length,1);const writes=await page.evaluate(()=>window.qWrites);assert(!writes.some(w=>w.table==='attempts'&&w.id===next.attempt.attemptId));await chrome(page,'Kw & Strong Bases',changed.attempt.ref.level,'alevel');return{run,exactContinuedAttempt:first.attempt.attemptId,schedulerNext:next.attempt.attemptId,changedAttempt:changed.attempt.attemptId,oldAttemptWritesDuringChangedLaunch:0,oneEvidence:true};
  });
  await scenario('olympiad-header-stage-drawing-save-fault-readonly',async page=>{
    const run='q-c3-'+Date.now();await page.goto(`${base}/alevel.html?course=alevel&view=olympiad&run=${run}`);await page.waitForFunction(()=>window.__mastersOlympiad?.snapshot().progress);assert.equal(await page.locator('.question-subject').textContent(),'A Level Chemistry - C3L6 organic reactions');assert.equal(await page.locator('.header-question-code').textContent(),'C3L6 2012 Q2');assert.equal(await page.locator('.question-level-pill').textContent(),'OLYMPIAD QUESTION');assert.equal(await page.locator('.platform-navigation,.course-navigation').count(),0);await page.evaluate(async()=>{const{c3Challenge}=await import('/src/activities/olympiad/c3l6/index.ts');for(const item of c3Challenge.classifications)await window.__mastersOlympiad.command({kind:'classify',id:item.id,value:item.answer});await window.__mastersOlympiad.command({kind:'check-a'});await window.__mastersOlympiad.command({kind:'navigate',stage:'b'});const graph=c3Challenge.hydrolysis[0].slots[0].alternatives[0].graph;await window.__mastersOlympiad.command({kind:'draw-b',slotId:'A',drawing:{kind:'molecule',graph,history:[]}});await window.__mastersOlympiad.flush();});await page.locator('.molecule-editor').waitFor();const first=await page.evaluate(()=>window.__mastersOlympiad.snapshot());await page.reload();await page.waitForFunction(()=>window.__mastersOlympiad?.snapshot().progress?.stage==='b');assert.deepEqual((await page.evaluate(()=>window.__mastersOlympiad.snapshot())).progress,first.progress);await page.evaluate(()=>window.qFailOlympiad=true);await page.evaluate(async()=>{const s=window.__mastersOlympiad.snapshot();const d=structuredClone(s.progress.drawingsB.A);d.graph.atoms[0].x+=10;await window.__mastersOlympiad.command({kind:'draw-b',slotId:'A',drawing:d});});await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();const url=page.url();await page.locator('.question-back').click();await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();assert.equal(page.url(),url);await page.evaluate(()=>window.qFailOlympiad=false);await page.getByRole('button',{name:'Retry save',exact:true}).click();await page.waitForFunction(()=>window.__mastersOlympiad.snapshot().saveStatus.kind==='saved');await page.getByRole('button',{name:'Teacher preview',exact:true}).click();await page.getByRole('button',{name:'Part (b)',exact:true}).click();assert(await page.getByRole('button',{name:'Carbon',exact:true}).isDisabled());const rows=await dbRows(page);assert.deepEqual([rows.olympiad.length,rows.attempts.length,rows.evidence.length],[1,0,0]);await page.screenshot({path:path.join(here,'c3-teacher-stage-b.png'),fullPage:true});return{run,existingIdentity:true,drawingRestored:true,faultGuardAndRetry:true,teacherReadonly:true,noCurriculumEvidence:true};
  });
} finally {
  report.finishedAt=new Date().toISOString();report.status=report.failures.length||report.pageErrors.length?'FAIL':'PASS';fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,failures:report.failures,pageErrors:report.pageErrors}));if(report.status!=='PASS')process.exitCode=1;
}
