import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),require=createRequire(path.join(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');
const out=path.join(here,'root-hierarchy-correction');fs.mkdirSync(out,{recursive:true});const temp=path.join(project,'.qhc-tmp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const prior=JSON.parse(fs.readFileSync(path.join(here,'before-root-hierarchy-correction/current-inputs.json')));
const sourceChanges=prior.inputs.filter(row=>row.path.startsWith('src/')&&hash(path.join(project,row.path))!==row.sha256).map(row=>row.path);
assert.deepEqual(sourceChanges,['src/styles/platform.css']);
const base='http://127.0.0.1:5182',urls=[];
for(const course of ['alevel','igcse']){const url=`${base}/${course}/`,response=await fetch(url);assert.equal(response.status,200);const html=Buffer.from(await response.arrayBuffer());assert.deepEqual(html,fs.readFileSync(path.join(project,'dist',course,'index.html')));urls.push({url,status:200,currentHtmlSha256:crypto.createHash('sha256').update(html).digest('hex')});}
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true});
const report={status:'RUNNING',startedAt:new Date().toISOString(),method:'Verified persistent preview5182 current static builds; pinned root Playwright1.62.1/headless Edge fresh isolated contexts; actual desktop/mobile hierarchy assertions and captures. CSS-only source change independently checked; prior Host/domain/idle proof exact.',sourceChanges,urls,checks:[],failures:[],pageErrors:[]};
try{for(const [name,course,query,ready] of [
 ['numeric','alevel','activity=alevel/acid-base-calculations&gem=u6-t1-1-7&level=1&fresh=1','.question-player'],
 ['dot','igcse','activity=igcse/dot-and-cross&gem=fourth-3-2&level=1&fresh=1','.dc-canvas'],
 ['olympiad','alevel','view=olympiad','.c3l6'],
 ])for(const mobile of [false,true]){
 const id=name+'-'+(mobile?'mobile':'desktop'),context=await browser.newContext({viewport:{width:mobile?390:1440,height:mobile?844:1000}}),page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push({id,message:e.message}));
 try{const url=`${base}/${course}/?course=${course}&${query}`;await page.goto(url);await page.locator(ready).waitFor();await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>[...document.images].every(image=>image.complete&&image.naturalWidth>0));
 const actual=await page.evaluate(()=>{const brand=document.querySelector('.question-wordmark'),subject=document.querySelector('.question-subject'),b=getComputedStyle(brand),s=getComputedStyle(subject),badge=getComputedStyle(document.querySelector('.header-question-code'));return{brand:{text:brand.textContent,font:b.fontFamily,size:b.fontSize,colour:b.color,spacing:b.letterSpacing},subject:{text:subject.textContent,font:s.fontFamily,size:s.fontSize,colour:s.color},badgeColour:badge.color,badgeCount:document.querySelectorAll('.header-question-code').length,navCount:document.querySelectorAll('.platform-navigation,.course-navigation').length,width:innerWidth,scrollWidth:document.documentElement.scrollWidth};});
 assert.equal(actual.brand.text,'MASTERS OF CHEMISTRY');assert.equal(actual.brand.size,mobile?'10px':'11px');assert.equal(actual.brand.colour,'rgb(84, 245, 181)');assert.equal(actual.subject.size,mobile?'21px':'24px');assert.equal(actual.subject.colour,'rgb(247, 247, 255)');assert(actual.subject.font.startsWith('Comfortaa'));assert.equal(actual.badgeColour,'rgb(255, 94, 203)');assert.equal(actual.badgeCount,1);assert.equal(actual.navCount,0);assert(actual.scrollWidth<=actual.width);
 const screen=id+'.png';await page.screenshot({path:path.join(out,screen),fullPage:true});report.checks.push({id,status:'PASS',url,...actual,screen});console.log('PASS hierarchy '+id);
 }catch(error){report.failures.push({id,error:error.stack});await page.screenshot({path:path.join(out,id+'-failure.png'),fullPage:true}).catch(()=>{});}finally{await context.close();}}
 }finally{await browser.close();report.status=report.failures.length||report.pageErrors.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();report.currentCssSha256=hash(path.join(project,'src/styles/platform.css'));report.currentHostSha256=hash(path.join(project,'src/foundation/ActivityHost.tsx'));fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,checks:report.checks.length,failures:report.failures,pageErrors:report.pageErrors,urls}));if(report.status!=='PASS')process.exitCode=1;}
