import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),require=createRequire(path.join(project,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');
const temp=path.join(here,'.timing-browser-tmp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const paths=['src/foundation/ActivityHost.tsx','src/domain/timing/active-clock.ts','src/domain/timing/browser-binding.ts','src/domain/attempt/attempt.ts'];
const sourceBefore=paths.map(file=>({path:file,sha256:hash(path.join(project,file))}));
const report={startedAt:new Date().toISOString(),method:'Current immutable static builds, pinned root Playwright1.62.1/headless Edge, fresh contexts, actual wall-time trusted-input idle cutoff and durable IndexedDB reads. Passive lifecycle observation only. No timing hooks, synthetic visibility, clock patches or visible counters.',sourceBefore,checks:[],failures:[],capabilities:[],pageErrors:[]};
const server=http.createServer((req,res)=>{try{const segments=decodeURIComponent(new URL(req.url,'http://localhost').pathname).split('/').filter(Boolean),course=segments.shift();assert(['alevel','igcse'].includes(course));const root=path.join(project,'dist',course),file=path.resolve(root,...(segments.length?segments:['index.html']));assert(file.startsWith(root+path.sep));const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true});
async function observe(page,course,label){return page.evaluate(async({course,label})=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(`masters-of-chemistry-${course}-local`);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{const get=name=>new Promise((resolve,reject)=>{const r=db.transaction(name).objectStore(name).getAll();r.onsuccess=()=>resolve(r.result.map(row=>row.value));r.onerror=()=>reject(r.error)});const attempts=await get('attempts'),evidence=await get('evidence'),attempt=attempts.at(-1);return{label,wallMs:Date.now(),monoMs:performance.now(),documentToken:window.qDocumentToken,timeOrigin:performance.timeOrigin,hidden:document.hidden,focused:document.hasFocus(),attemptId:attempt.attemptId,activeMs:attempt.phase==='answering'?attempt.timing.activeMs:attempt.firstResponse.timing.activeMs,idleLimitMs:attempt.phase==='answering'?attempt.timing.idleLimitMs:attempt.firstResponse.timing.idleLimitMs,events:window.qNativeEvents,evidenceCount:evidence.length};}finally{db.close();}}, {course,label});}
async function setup(course,activity,gem,level=1){const context=await browser.newContext(),page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push({course,activity,message:e.message}));await context.addInitScript(()=>{window.qDocumentToken=crypto.randomUUID();window.qNativeEvents=[];const record=e=>window.qNativeEvents.push({type:e.type,trusted:e.isTrusted,wallMs:Date.now(),monoMs:performance.now(),hidden:document.hidden,focused:document.hasFocus(),buttons:e.buttons});for(const event of ['visibilitychange','freeze','resume','pointerdown','keydown','input','wheel','scroll','touchmove'])document.addEventListener(event,record,{capture:true,passive:true});for(const event of ['blur','focus','pagehide','pageshow'])window.addEventListener(event,record,{capture:true,passive:true});});await page.goto(`${base}/${course}/?course=${course}&activity=${course}/${activity}&gem=${gem}&level=${level}&fresh=1`);await page.locator('.question-player,.dot-cross-player').waitFor();assert.equal(await page.evaluate(()=>typeof window.__mastersActivity),'undefined');await page.waitForTimeout(200);return{context,page};}
try {
  await Promise.all([
    {id:'short-60s',course:'alevel',activity:'electrons-bonding',gem:'l6-t2-1-1',limit:60000},
    {id:'editor-180s',course:'igcse',activity:'dot-and-cross',gem:'fourth-3-1',limit:180000},
  ].map(async fixture=>{const{context,page}=await setup(fixture.course,fixture.activity,fixture.gem);try{await page.locator(fixture.activity==='dot-and-cross'?'.dc-canvas':'.question-player').click({position:{x:70,y:70}});await page.waitForTimeout(1000);const before=await observe(page,fixture.course,'after trusted input');assert.equal(before.hidden,false);assert.equal(before.focused,true);assert.equal(before.idleLimitMs,fixture.limit);const lastInput=before.events.filter(e=>e.trusted&&['pointerdown','keydown','input','wheel','scroll','touchmove'].includes(e.type)).at(-1);assert(lastInput);console.log('START real idle '+fixture.id);await page.waitForTimeout(fixture.limit+6500);const idle=await observe(page,fixture.course,'allowance exhausted');await page.waitForTimeout(6500);const later=await observe(page,fixture.course,'durable plateau');assert.equal(later.activeMs,idle.activeMs);assert(idle.activeMs>=fixture.limit-2000&&idle.activeMs<=fixture.limit+2000);assert.equal(later.documentToken,before.documentToken);assert.equal(later.attemptId,before.attemptId);const newInputs=later.events.filter(e=>e.trusted&&['pointerdown','keydown','input','wheel','scroll','touchmove'].includes(e.type)&&e.monoMs>lastInput.monoMs);assert.equal(newInputs.length,0);assert.equal(later.evidenceCount,0);await page.locator(fixture.activity==='dot-and-cross'?'.dc-canvas':'.question-player').click({position:{x:110,y:70}});await page.waitForTimeout(6500);const restarted=await observe(page,fixture.course,'new trusted interaction restarts answering');assert(restarted.activeMs>later.activeMs&&restarted.activeMs-later.activeMs<8500);report.checks.push({id:fixture.id,status:'PASS',before,idle,later,restarted,noTrustedInputsAfterStart:true,plateauDeltaMs:0,realWallSinceLastInputMs:idle.wallMs-lastInput.wallMs});console.log('PASS real idle '+fixture.id);}catch(error){report.failures.push({id:fixture.id,error:error.stack});console.log('FAIL timing '+fixture.id+' '+error.message);}finally{await context.close();}}));
  const {context,page}=await setup('alevel','electrons-bonding','l6-t2-1-1');try{await page.locator('.question-player').click({position:{x:70,y:70}});await page.waitForTimeout(6000);const before=await observe(page,'alevel','before requested native freeze');const cdp=await context.newCDPSession(page);await cdp.send('Page.setLifecycleEventsEnabled',{enabled:true});const lifecycle=[];cdp.on('Page.lifecycleEvent',event=>lifecycle.push({...event,nodeWallMs:Date.now()}));await cdp.send('Page.setWebLifecycleState',{state:'frozen'});const requestWall=Date.now();await new Promise(resolve=>setTimeout(resolve,8000));await cdp.send('Page.setWebLifecycleState',{state:'active'});await page.waitForTimeout(6000);const after=await observe(page,'alevel','after requested native freeze');const observedFreeze=after.events.some(e=>e.type==='freeze'&&e.wallMs>=requestWall-1000),observedResume=after.events.some(e=>e.type==='resume'&&e.wallMs>=requestWall);const actualFreeze=observedFreeze&&observedResume;let hiddenProbe;try{const root=await browser.newBrowserCDPSession();const {windowId}=await root.send('Browser.getWindowForTarget');await root.send('Browser.setWindowBounds',{windowId,bounds:{windowState:'minimized'}});await new Promise(resolve=>setTimeout(resolve,1000));hiddenProbe=await page.evaluate(()=>({hidden:document.hidden,focused:document.hasFocus(),events:window.qNativeEvents.filter(e=>['visibilitychange','blur','focus'].includes(e.type))}));}catch(error){hiddenProbe={error:error.message};}report.capabilities.push({id:'native-freeze-background-probe',status:actualFreeze?'ESTABLISHED_REQUIRES_BOUNDARY_REVIEW':'UNESTABLISHED',before,after,requestWall,frozenRequestWallMs:8000,observedFreeze,observedResume,lifecycle,hiddenProbe,disposition:'Actual document lifecycle and durable timing retained. Command success alone is not a frozen/hidden interval; no background/native PASS invented.'});console.log('NATIVE capability '+(actualFreeze?'ESTABLISHED':'UNESTABLISHED'));}catch(error){report.capabilities.push({id:'native-freeze-background-probe',status:'CAPABILITY_ERROR',error:error.stack});}finally{await context.close();}
}finally{report.finishedAt=new Date().toISOString();report.sourceAfter=paths.map(file=>({path:file,sha256:hash(path.join(project,file))}));try{assert.deepEqual(report.sourceAfter,report.sourceBefore);}catch(error){report.failures.push({id:'source-stability',error:error.message});}report.status=report.failures.length||report.pageErrors.length?'FAIL':'PASS_WITH_NATIVE_CAPABILITY_LIMIT';fs.writeFileSync(path.join(here,'timing-browser-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();await new Promise(resolve=>server.close(resolve));console.log(JSON.stringify({status:report.status,idleChecks:report.checks.length,failures:report.failures,capabilities:report.capabilities.map(c=>({id:c.id,status:c.status})),pageErrors:report.pageErrors}));if(report.failures.length||report.pageErrors.length)process.exitCode=1;}
