import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {bank,energyProvider} from '../../../../src/activities/igcse/energy-enthalpy/provider.ts';
import {selectPracticeQuestion} from '../../../../src/domain/session/practice.ts';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const files=['validation/s5/render-release/final-energy-next-incomplete-harness-failure.json','validation/s5/render-release/final-energy-next-code-wait-failure.json','validation/s5/render-release/final-energy-tail-baseline.mjs','validation/s5/render-release/final-energy-tail-proposal.mjs','validation/s5/render-release/seed-static.mjs','src/domain/session/practice.ts','src/activities/igcse/energy-enthalpy/provider.ts','src/foundation/ActivityHost.tsx','src/domain/timing/browser-binding.ts'];fs.mkdirSync(path.join(here,'retained'),{recursive:true});const hashes={};
for(const f of files){const dst=path.join(here,'retained',f.replaceAll('/','__'));if(!fs.existsSync(dst))fs.copyFileSync(path.join(project,f),dst);hashes[f]={sha256:sha(fs.readFileSync(dst)),retained:'validation/s5/review-render-harness/energy-next/retained/'+path.basename(dst)};}
const read=f=>fs.readFileSync(path.join(project,hashes[f].retained),'utf8').replaceAll('\r\n','\n');
assert.equal(hashes['validation/s5/render-release/final-energy-tail-proposal.mjs'].sha256,'a51069b27f2e0d24441ec6e90e70765c4d00f72c93ceceb19c0a6731175a1c8c');
const candidate=read('validation/s5/render-release/final-energy-tail-proposal.mjs'),baseline=read('validation/s5/render-release/final-energy-tail-baseline.mjs'),start=candidate.indexOf('await p.evaluate(async questionId=>'),end=candidate.indexOf("await type(p,p.getByLabel('Peak level screen y'",start);assert(start>0&&end>start);const patch=candidate.slice(start,end);assert(patch.includes('row.value.previousQuestionIds=[questionId]'));assert.equal((candidate.slice(0,start)+candidate.slice(end)).trimEnd(),baseline.trimEnd());
const q=bank.questions.find(q=>q.editor&&q.editor.type!=='levels'&&q.editor.arrows.includes('ea'));assert.equal(q.id,'D03');const pool=bank.questions.filter(x=>x.grade===q.grade),target={course:'igcse',activityId:'igcse/energy-enthalpy',gemId:'lower-10-1',level:q.grade},namespace={course:'igcse',profileId:'local'},session={kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:'source-review-only',previousQuestionIds:[]};
const badSeed=pool.findIndex(x=>x.id===q.id),bad=selectPracticeQuestion({session,provider:energyProvider,seed:badSeed,summaries:[]});assert.equal(bad.ref.questionId,q.id);assert.deepEqual(bad.session.previousQuestionIds,[q.id]);const corrected=[];
for(let seed=0;seed<pool.length-1;seed++){const result=selectPracticeQuestion({session:{...session,previousQuestionIds:[q.id]},provider:energyProvider,seed,summaries:[]});assert.notEqual(result.ref.questionId,q.id);assert.deepEqual(result.session.previousQuestionIds,[q.id,result.ref.questionId]);corrected.push({seed,ref:result.ref});}
const report={agentId:'A06',jobId:'S5-REVIEW-ENERGY-NEXT-HARNESS',status:'ESCALATE',capturedAt:new Date().toISOString(),reason:'Exact proposal repairs missing history but writes under mounted old host before reload; pagehide checkpoint may overwrite it. Await source-faithful unloaded-host proposal.',hashes,patch,sourceProof:{currentQuestion:q.id,pool:pool.map(x=>x.id),emptyHistoryCanRepeat:{seed:badSeed,ref:bad.ref},correctedHistoryAllModuloChoices:corrected},failedExecutionCause:'Unknown: retained changed-code timeout has no post-click attempt/code snapshot; source possibility is not classification of that run.',substantiveAssertionsPreserved:true,fullTailReplayed:false};fs.writeFileSync(path.join(here,'initial-source-review.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,question:q.id,emptyHistoryRepeatSeed:badSeed,correctedChoices:corrected.length}));
