import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
import{getVariant}from'../../../../../../src/chemistry/electron-configuration/identity.ts';import{data}from'../../../../../../src/chemistry/electron-configuration/data.js';import{referenceState,blankState}from'../../../../../../src/chemistry/electron-configuration/engine.ts';import{same}from'../../../../../../src/chemistry/electron-configuration/core.js';
const here=import.meta.dirname,project=path.resolve(here,'../../../../../..'),require=createRequire(path.resolve(project,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');const temp=path.join(here,'.browser-temp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;const{chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true});
const base='http://127.0.0.1:5188',original='http://127.0.0.1:5197/alevel/activities/electron-configurations/index.html';
const report={jobId:'F2-EC',agentId:'F09',startedAt:new Date().toISOString(),checks:[],screenshots:[],metrics:[],errors:[],limitations:['Native hidden/minimized/OS suspend not newly tested.','Original correction drawing is compared by reopening the same isolated source review question with the corrected response: the original EC source freezes assessed answers and has no correction action. Shared React first evidence remains immutable.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name,selector){await p.evaluate(()=>document.fonts.ready);await p.locator(selector).screenshot({path:path.join(here,name+'.png')});report.screenshots.push(name+'.png');}
async function startReact(ctx,id,mode='practice'){
 const run=`f09-${mode}-${id}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`${base}/alevel.html?view=home&run=${run}`);await p.locator('.original-landing').waitFor();
 await p.evaluate(async({id,run,mode})=>{
  const{createChemistryRepository}=await import('/src/persistence/index.ts'),{getVariant}=await import('/src/chemistry/electron-configuration/identity.ts'),{electronConfigurationsProvider:provider}=await import('/src/activities/alevel/electron-configurations/provider.ts');
  const q=getVariant(id),level=q.kind==='bonus'?3:q.minimumLevel,ref={activityId:'alevel/electron-configurations',questionId:id,level,seed:q.kind==='bonus'?parseInt(id.slice(4),36):0};provider.restore(ref);
  const namespace={course:'alevel',profileId:'local'},target={course:'alevel',activityId:ref.activityId,gemId:'l6-t2-1-2',level},attemptId=`f09-${run}`,attempt={mode:'student',namespace,attemptId,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId,activeMs:0,idleLimitMs:q.kind==='main'&&q.direction==='identify'?60000:180000,finished:false}};
  const session=mode==='revision'?{kind:'revision',namespace,id:'current-session',createdAt:Date.now(),status:'active',selectedGemIds:[target.gemId],levels:[{target,mode:'practice',required:1,streak:0,confirmedAt:null,initialScore:null}],round:[target.gemId],lastGemId:null,current:{attemptId,target,ref,completed:false},previous:[],submittedAttemptIds:[]}:{kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:attemptId,previousQuestionIds:[id],paused:false};
  const repo=createChemistryRepository(`masters-of-chemistry-alpha-v2-alevel-${run}`),a=await repo.saveCurriculum({attempt}),s=await repo.saveSession(session);repo.close();if(!a.ok||!s.ok)throw Error(JSON.stringify([a,s]));
 },{id,run,mode});await p.goto(`${base}/alevel.html?view=${mode}&run=${run}&activity=alevel%2Felectron-configurations`);await p.locator('.ec-workspace').waitFor();await flush(p);assert.equal((await snap(p)).attempt.ref.questionId,id);return p;
}
async function startOriginal(ctx,id){const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(original+`?review=${id}&mode=teacher`);await p.locator('#questionPanel .question-top').waitFor();return p;}
function answerFor(q){if(q.kind==='bonus'){return{...blankState(),selectedSpeciesIds:q.options.filter(id=>same(data.species.find(s=>s.id===id).counts,q.counts))};}return referenceState(q.speciesId,q.representation);}
async function fill(p,q,answer,app){
 if(q.kind==='bonus'){for(const id of q.options){const item=data.species.find(s=>s.id===id);const field=app==='react'?p.locator('.bonus-options input').nth(q.options.indexOf(id)):p.locator(`[data-species="${id}"]`);await field.setChecked(answer.selectedSpeciesIds.includes(id));}return;}
 if(q.direction==='identify'){await p.getByLabel('Element name or symbol',{exact:true}).fill(answer.identity);return;}
 if(q.representation==='row'||q.representation==='energy'){for(const [index,row]of answer.boxes.entries())for(const [orbital,spin]of row.entries()){const box=p.locator(`[data-orbital="${index}:${orbital}"]`);await box.focus();await p.keyboard.press(spin===3?'2':spin===2?'d':String(spin));if(app==='react')await flush(p);}return;}
 if(q.representation==='short')await p.locator('.core-select select').selectOption(answer.core);
 for(const [index,value]of answer.counts.entries()){const field=p.getByLabel(`Electrons in ${data.subshells[index]}`,{exact:true});if(await field.count()){await field.fill(value);if(app==='react')await flush(p);}}
}
async function submit(p,app){await p.getByRole('button',{name:'Check answer',exact:true}).click();if(app==='react'){await p.waitForFunction(()=>window.__mastersActivity.snapshot().attempt.phase==='assessed');await flush(p);}else await p.locator('#feedback').waitFor({state:'visible'});}
async function metrics(p,app,size,family){return p.evaluate(({app,size,family})=>{const pick=s=>{const e=document.querySelector(s);if(!e)return null;const c=getComputedStyle(e),r=e.getBoundingClientRect();return{fontFamily:c.fontFamily,fontSize:c.fontSize,lineHeight:c.lineHeight,fontWeight:c.fontWeight,color:c.color,background:c.backgroundColor,padding:c.padding,border:c.border,borderRadius:c.borderRadius,width:r.width,height:r.height};};return{app,size,family,orbital:pick('.orbital'),notationInput:pick('.subshell-entry input'),coreSelect:pick('.core-select select'),card:pick('.species-card'),energy:pick('.energy-diagram'),match:pick('.bonus-option'),overflow:document.documentElement.scrollWidth>innerWidth};},{app,size,family});}
const cases=[['full','EC-TH921N'],['short','EC-VUXW9Q'],['row','EC-5AUBIM'],['energy','EC-GYMGZS'],['matching','ECB-00000F'],['identify-full','EC-TXYUKV'],['identify-short','EC-UH3QI8'],['identify-row','EC-U5RDA2'],['identify-energy','EC-RGVK0U']];
try{
 for(const [size,viewport]of Object.entries({desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}})){
  for(const [family,id]of cases){const rc=await browser.newContext({viewport,hasTouch:size==='mobile'}),oc=await browser.newContext({viewport,hasTouch:size==='mobile'}),r=await startReact(rc,id),o=await startOriginal(oc,id),q=getVariant(id),answer=answerFor(q),prefix=`${size}-${family}`;
   await shot(r,`react-${prefix}-unanswered`,'.question-player');await shot(o,`original-${prefix}-unanswered`,'.question-stack');
   if(size==='desktop'&&family==='full'){await r.screenshot({path:path.join(here,'react-desktop-full-chrome.png'),fullPage:true});report.screenshots.push('react-desktop-full-chrome.png');}const rm=await metrics(r,'react',size,family),om=await metrics(o,'original',size,family);report.metrics.push(rm,om);assert.equal(rm.overflow,false);for(const kind of ['orbital','notationInput','coreSelect','card','match'])if(rm[kind]&&om[kind])for(const prop of['fontFamily','fontSize','lineHeight','fontWeight','border','borderRadius'])assert.equal(rm[kind][prop],om[kind][prop],`${prefix} ${kind} ${prop}`);
   if(q.kind==='main'&&q.direction==='identify'){await r.getByLabel('Element name or symbol',{exact:true}).fill('A');await o.getByLabel('Element name or symbol',{exact:true}).fill('A');}else if(q.kind==='bonus'){await r.locator('.bonus-options input').first().setChecked(true);await o.locator('.bonus-options input').first().setChecked(true);}else if(q.representation==='row'||q.representation==='energy'){const b=r.locator('[data-orbital="0:0"]');await b.focus();await r.keyboard.press('1');await o.locator('[data-orbital="0:0"]').focus();await o.keyboard.press('1');}else{await r.getByLabel('Electrons in 1s',{exact:true}).fill('1');await o.getByLabel('Electrons in 1s',{exact:true}).fill('1');}
   await flush(r);await shot(r,`react-${prefix}-partial`,'.question-player');await shot(o,`original-${prefix}-partial`,'.question-stack');const draft=await snap(r);await r.reload();await r.locator('.ec-workspace').waitFor();await flush(r);assert.equal((await snap(r)).attempt.attemptId,draft.attempt.attemptId);assert.deepEqual((await snap(r)).attempt.currentResponses,draft.attempt.currentResponses);
   const wrong=structuredClone(answer);if(q.kind==='main'&&q.direction==='identify')wrong.identity='Xx';else if(q.kind==='bonus')wrong.selectedSpeciesIds=q.options.filter(id=>!answer.selectedSpeciesIds.includes(id));else if(q.representation==='row'||q.representation==='energy')wrong.boxes[0][0]=1;else wrong.counts[q.representation==='short'?5:0]='1';await fill(r,q,wrong,'react');await fill(o,q,wrong,'original');await submit(r,'react');await submit(o,'original');const first=await snap(r);assert.equal(first.attempt.firstAssessment.score,0);assert(first.attempt.firstResponse.timing.activeMs>0);await shot(r,`react-${prefix}-incorrect`,'.question-player');await shot(o,`original-${prefix}-incorrect`,'.question-stack');
   await fill(r,q,answer,'react');await r.getByRole('button',{name:'Check correction',exact:true}).click();await flush(r);assert.equal((await snap(r)).correctionFeedback.status,'correct');assert.deepEqual((await snap(r)).attempt.firstAssessment,first.attempt.firstAssessment);assert.deepEqual((await snap(r)).attempt.firstResponse,first.attempt.firstResponse);assert.equal((await r.evaluate(()=>window.__mastersActivity.history())).length,1);
   await o.reload();await o.locator('#questionPanel .question-top').waitFor();await fill(o,q,answer,'original');await submit(o,'original');await shot(r,`react-${prefix}-correction`,'.question-player');await shot(o,`original-${prefix}-correction`,'.question-stack');
   const cr=await startReact(rc,id);await fill(cr,q,answer,'react');await submit(cr,'react');assert.equal((await snap(cr)).attempt.firstAssessment.score,1);await shot(cr,`react-${prefix}-correct`,'.question-player');await shot(o,`original-${prefix}-correct`,'.question-stack');
   await r.getByRole('button',{name:'Show worked answer',exact:true}).click();await r.locator('.worked-answer').waitFor();await o.locator('#answerPanel summary').click();await shot(r,`react-${prefix}-model`,'.question-player');await shot(o,`original-${prefix}-model`,'.question-stack');await r.reload();await r.locator('.worked-answer').waitFor();await flush(r);assert.deepEqual((await snap(r)).attempt.firstResponse,first.attempt.firstResponse);assert.equal((await r.evaluate(()=>window.__mastersActivity.history())).length,1);
   if(family==='energy'){await r.getByRole('button',{name:'Periodic table',exact:true}).click();await o.getByRole('button',{name:'Periodic table',exact:true}).click();assert.equal(await r.locator('.ec-periodic-element').count(),114);await shot(r,`react-${size}-periodic`,'.ec-periodic-dialog');await shot(o,`original-${size}-periodic`,'.ocr-periodic-dialog');await r.keyboard.press('Escape');await o.keyboard.press('Escape');assert.equal(await r.getByRole('button',{name:'Periodic table',exact:true}).evaluate(e=>document.activeElement===e),true);}
   report.checks.push({size,family,id,states:['unanswered','partial','incorrect','correct','correction','model'],restoredDraft:true,firstEvidenceImmutable:true,records:1,fontAndBorderMatch:true});await rc.close();await oc.close();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));
  }
 }
 report.status='PASS';
}catch(e){report.status='FAIL';report.errors.push(e.stack??String(e));console.error(e);}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,screenshots:report.screenshots.length,errors:report.errors}));if(report.status!=='PASS')process.exitCode=1;}
