import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
import{getVariant}from'../../../../../../src/chemistry/electron-configuration/identity.ts';import{referenceState}from'../../../../../../src/chemistry/electron-configuration/engine.ts';import{data}from'../../../../../../src/chemistry/electron-configuration/data.js';
const here=import.meta.dirname,project=path.resolve(here,'../../../../../..'),require=createRequire(path.resolve(project,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');fs.mkdirSync(path.join(project,'.f09-production-tmp'),{recursive:true});process.env.TEMP=process.env.TMP=path.join(project,'.f09-production-tmp');
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true}),report={jobId:'F2-EC',agentId:'F09',startedAt:new Date().toISOString(),method:'Production build; real UI gestures, isolated current-alpha IndexedDB fixtures; no DEV globals or runtime instrumentation changes',checks:[],errors:[],limitations:['CDP frozen does not suspend interval callbacks in the hosted Edge session; native OS suspension is not claimed.']};
async function rows(p,dbName){return p.evaluate(async name=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(name);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{const out={};for(const store of ['attempts','sessions','evidence'])out[store]=await new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return out;}finally{db.close();}},dbName);}
try{await Promise.allSettled([['build','EC-GYMGZS',180000],['identify','EC-TXYUKV',60000]].map(async([family,id,limit])=>{const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage(),run='f09-prod-'+family+'-'+Date.now(),dbName='masters-of-chemistry-alpha-v2-alevel-local',q=getVariant(id),level=q.minimumLevel;
try{p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:5192/alevel/?run='+run+'&activity=alevel/electron-configurations&gem=l6-t2-1-2&practice=fixed-level&level='+level+'&fresh=1');await p.locator('.ec-workspace').waitFor();assert.equal(await p.evaluate(()=>typeof window.__mastersActivity),'undefined');await p.waitForTimeout(500);
await p.evaluate(async({dbName,id,level,limit})=>{const db=await new Promise(resolve=>{const r=indexedDB.open(dbName);r.onsuccess=()=>resolve(r.result)});const read=store=>new Promise(resolve=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result)});const old=(await read('attempts'))[0],session=(await read('sessions'))[0],attemptId=crypto.randomUUID(),ref={...old.value.ref,questionId:id,seed:0,level},attempt={mode:'student',namespace:old.value.namespace,attemptId,ref,target:{...old.value.target,level},currentResponses:{},assistance:[],phase:'answering',timing:{attemptId,activeMs:0,idleLimitMs:limit,finished:false}};await new Promise((resolve,reject)=>{const tx=db.transaction(['attempts','sessions'],'readwrite');tx.objectStore('attempts').clear();tx.objectStore('attempts').put({...old,id:attemptId,value:attempt});tx.objectStore('sessions').put({...session,value:{...session.value,target:attempt.target,currentAttemptId:attemptId,previousQuestionIds:[id],paused:false}});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();},{dbName,id,level,limit});await p.goto('http://127.0.0.1:5192/alevel/?view=practice&activity=alevel%2Felectron-configurations');await p.locator('.ec-workspace').waitFor();assert.equal(await p.locator('.header-question-code').innerText(),id);
const answer=referenceState(q.speciesId,q.representation);if(q.direction==='identify')await p.getByLabel('Element name or symbol',{exact:true}).fill(answer.identity);else for(const[index,row]of answer.boxes.entries())for(const[orbital,spin]of row.entries()){await p.locator('[data-orbital="'+index+':'+orbital+'"]').focus();await p.keyboard.press(spin===3?'2':spin===2?'d':String(spin));}
await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await p.waitForTimeout(500);const assessed=await rows(p,dbName),first=assessed.attempts[0].value;assert.equal(first.firstAssessment.score,1);assert.equal(assessed.evidence.length,1);assert.deepEqual(assessed.evidence[0].value.timing,first.firstResponse.timing);await p.locator('.question-back').click();await p.locator('.original-landing').waitFor();await p.getByRole('button',{name:'Stats',exact:true}).click();await p.locator('.statistics').waitFor();const record=p.locator('[data-evidence-id="'+first.attemptId+'"]');await record.locator(':scope > summary').click();assert(await record.getByText('Recorded active time',{exact:true}).isVisible());assert(await p.locator('.statistics-chart').isVisible());const expectedMs=first.firstResponse.timing.activeMs;assert.equal(await p.locator('[data-testid=statistics-time]').getAttribute('data-active-ms'),String(expectedMs));const bar=p.locator('.statistics-chart button[data-active-ms="'+expectedMs+'"]');assert.equal(await bar.count(),1);await bar.scrollIntoViewIfNeeded();assert(await bar.locator('.statistics-bar').evaluate(e=>e.getBoundingClientRect().height>0));await bar.click();assert.equal(await bar.getAttribute('aria-pressed'),'true');assert.match(await p.locator('.statistics-day-detail').innerText(),/1 assessments/);await p.screenshot({path:path.join(here,'production-'+family+'-statistics-chart.png'),fullPage:true});
report.checks.push({family,id,firstTiming:first.firstResponse.timing,chartActiveMs:expectedMs,historyTiming:assessed.evidence[0].value.timing,barHasHeight:true,selectedDayTotal:await p.locator('.statistics-day-detail').innerText(),debugGlobalsAbsent:true});console.log('PASS '+family);
}catch(error){report.errors.push({family,error:error.stack});console.error(error);}finally{await ctx.close();}}));report.status=report.errors.length?'FAIL':'PASS';}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'production-chart-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,errors:report.errors}));if(report.status!=='PASS')process.exitCode=1;}
