import fs from 'node:fs';
import {syncBuiltinESMExports} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const project=path.resolve(import.meta.dirname,'../..');
const command=process.argv[1];
const family=path.basename(path.dirname(command));
const artifactRoot=path.join(project,'.artifacts/source-generation',family);
if(!process.argv.includes('--check'))fs.mkdirSync(artifactRoot,{recursive:true});
else {
 const candidates=new Map();
 fs.mkdirSync=()=>undefined;
 fs.writeFileSync=(target,content)=>{
  const absolute=target instanceof URL?fileURLToPath(target):path.resolve(target);
  if(absolute.startsWith(path.join(project,'.artifacts')+path.sep))return;
  if(absolute.startsWith(path.join(project,'validation')+path.sep))return;
  const relative=path.relative(project,absolute).replaceAll('\\','/');
  const bytes=Buffer.isBuffer(content)?content:Buffer.from(content);
  candidates.set(relative,{absolute,bytes});
 };
 fs.cpSync=(source,target)=>{
  function visit(from,to){for(const entry of fs.readdirSync(from,{withFileTypes:true})){const a=path.join(from,entry.name),b=path.join(to,entry.name);if(entry.isDirectory())visit(a,b);else fs.writeFileSync(b,fs.readFileSync(a));}}
  visit(source,target);
 };
 syncBuiltinESMExports();
 process.on('exit',()=>{
  const differences=[...candidates].filter(([,candidate])=>!fs.existsSync(candidate.absolute)||!fs.readFileSync(candidate.absolute).equals(candidate.bytes)).map(([relative])=>relative);
  const outputs=[...candidates].map(([relative,{bytes}])=>{
   // Header-only normalisation compares extraction content before/after path migration.
   const content=bytes.toString('utf8').replace(/^\/\/[^\n]*\r?\n/,'').replace(/^\/\*[\s\S]*?\*\//,'');
   return {path:relative,contentSha256:createHash('sha256').update(content).digest('hex')};
  });
  console.log(JSON.stringify({mode:'read-only-check',generator:path.relative(project,command).replaceAll('\\','/'),checked:candidates.size,differences,...(process.argv.includes('--migration-capture')?{outputs}:{}),note:'Only final generated bytes are compared; subsequent accepted edits may differ. This check never replaces live content.'}));
  if(differences.length)process.exitCode=1;
 });
}
