import {chromium} from '../../../../../../node_modules/playwright/index.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {gzipSync} from 'node:zlib';
import {validateRelease} from '../../../../scripts/validate-s4-release.mjs';
import {compatibilityRoutes} from '../../../../src/compatibility/routes.ts';
const project=path.resolve(import.meta.dirname,'../../../..'),report={startedAt:new Date().toISOString(),checks:[],courses:[],errors:[]};
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local'),match=u.pathname.match(/^\/chemistry\/(alevel|igcse)\/(.*)$/);if(!match){res.writeHead(404);res.end();return;}
 const course=match[1],part=match[2]||'index.html',root=path.join(project,'dist',course),file=path.resolve(root,part);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end();return;}
 const ext=path.extname(file),type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':type});res.end(fs.readFileSync(file));});
await new Promise(r=>server.listen(5198,'127.0.0.1',r));
const browserTemp=path.join(import.meta.dirname,'release-browser-temp');fs.mkdirSync(browserTemp,{recursive:true});process.env.TEMP=browserTemp;process.env.TMP=browserTemp;process.env.TMPDIR=browserTemp;report.browserTempRoot=browserTemp;
const browser=await chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${path.join(browserTemp,'cache')}`]});
try{for(const course of ['alevel','igcse']){
 const result=validateRelease(course),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),loaded=new Set();page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{const u=new URL(r.url());if(u.pathname.endsWith('.js'))loaded.add(u.pathname.split(`/chemistry/${course}/`)[1]);});
 const entry=`http://127.0.0.1:5198/chemistry/${course}/`;await page.goto(entry);await page.getByRole('button',{name:'Start practice',exact:true}).waitFor();await page.waitForLoadState('networkidle');assert.equal(await page.evaluate(()=>window.__mastersActivity),undefined);const initialFiles=[...loaded];
 const actualInitialGzipBytes=initialFiles.reduce((n,f)=>n+gzipSync(fs.readFileSync(path.join(project,'dist',course,f))).length,0);assert(actualInitialGzipBytes<=204800,`Real loaded shell ${actualInitialGzipBytes} exceeds204800`);
 assert(!initialFiles.some(f=>f.startsWith('assets/provider-')),'Provider/bank loaded before activity selection');
 await page.reload();await page.getByRole('button',{name:'Start practice',exact:true}).waitFor();await page.screenshot({path:path.join(import.meta.dirname,`release-${course}-prefix-refresh.png`),fullPage:true});
 await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.locator('.question-player').waitFor();await page.waitForLoadState('networkidle');assert([...loaded].some(f=>!initialFiles.includes(f)),'Activity did not load additional lazy code');
 await page.reload();await page.locator('.question-player').waitFor();await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(import.meta.dirname,`release-${course}-activity-refresh-mobile.png`),fullPage:true});
 report.courses.push({...result,actualInitialGzipBytes,initialFiles,postStartJavascriptFiles:[...loaded].filter(f=>!initialFiles.includes(f)),prefix:entry,developmentHarnessAbsent:true});await context.close();
 for(const alias of compatibilityRoutes[course]){const aliasContext=await browser.newContext(),aliasPage=await aliasContext.newPage();aliasPage.on('pageerror',e=>report.errors.push(e.message));await aliasPage.goto(entry+alias);await aliasPage.waitForURL(u=>u.pathname===`/chemistry/${course}/index.html`);const destination=new URL(aliasPage.url());assert.equal(destination.searchParams.get('view'),alias.includes('c3l6')?'olympiad':'practice');await aliasPage.reload();await aliasPage.locator('.site-header').waitFor();await aliasContext.close();}
 }assert.deepEqual(report.errors,[]);report.status='PASS';report.checks=['Independent course manifests against current build','Relative nested static prefixes/direct index refresh','All twelve explicit old activity aliases redirect under nested course prefix and destination refresh','Saved activity direct refresh','Initial no-provider loading and lazy activity code','Actual loaded initial shell JS gzip<=204800','Production DEV harness absent','390px activity render without document overflow'];
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(import.meta.dirname,'release-browser-results.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}
