import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const here=import.meta.dirname,project=path.resolve(here,'../../..');
const read=file=>JSON.parse(fs.readFileSync(path.join(project,file),'utf8').replace(/^\uFEFF/,''));
const evidence=['foreman-validation.json','protected-originals.json','accepted-current-inputs.json','historical-landing-freeze.json','dot-cross/audit.json','dot-cross/completion.json','dot-cross/HANDOVER.md','dot-cross/browser-results.json','dot-cross/inventory-verification.json','dot-cross/source-fingerprints.json','molecule/audit.json','molecule/completion.json','molecule/HANDOVER.md','molecule/verification.json','molecule/source-fingerprints.json','molecule/reference-browser-results.json','molecule/react-browser-results.json'];
const validation=read('validation/editor-restoration/audit/foreman-validation.json');
if(validation.status!=='PASS'||validation.workers.length!==2)throw Error('Two accepted audit validations required');
const report={
  schemaVersion:1,runId:'EDITORS-RESTORE-20261003',stage:'E0',status:'PASS',rootGate:'AWAITING_ROOT_ACCEPTANCE',reportedAt:new Date().toISOString(),
  outcome:'Both original editor/context inventories and reusable sources reviewed; runtime unchanged. E1 has not been dispatched.',
  delegation:{foreman:{agentId:'E01',handle:'/root/editor_foreman',requestedModel:'gpt-6.1-sol',requestedEffort:'high',effectiveSettings:'unknown'},workers:[{agentId:'E02',handle:'/root/editor_foreman/dot_cross_audit',jobId:'DOT-CROSS-AUDIT'},{agentId:'E03',handle:'/root/editor_foreman/molecule_audit',jobId:'MOLECULE-AUDIT'}],workerSettings:{requestedModel:'gpt-6.1-sol',requestedEffort:'high',fork:'none',effectiveSettings:'unknown',usage:null},maximumActiveIncludingRoot:5,maximumGenuineExceptionReviewers:1,workersMayDelegate:false,retry:'One clarified bounded retry, then independent exception/root disposition. No model substitution.',rootSettings:'unknown'},
  acceptance:validation,
  findings:[
    {id:'DOT-TOPOLOGY',detail:'Original compact palette, dark adaptive canvas, desktop marking sidebar and modal answer differ materially from React dropdowns, nested frames, white canvas and inline answer. Reuse effective original DOM/CSS/renderer geometry under the accepted shared shell.'},
    {id:'DOT-GESTURES',detail:'Restore palette drag, snapped placement, tool-independent atom drag, bracket-group drag, electron relocate/cycle/slot organisation, direct local/whole-ion charge targeting, region previews, cursor/focus/key routing and circles. Preserve source course palettes/scaffolds and controlled semantic commits.'},
    {id:'DOT-FIT',detail:'Current min-width:600px dot answer CSS overrides shared fit viewport; IGCSE mobile KI initially omits iodide. Restore source dynamically fitted black-on-white answer SVG and modal, including circle preference and local-charge label position. Source answer is not a permanently fixed 1000x650 viewBox.'},
    {id:'MOLECULE-GESTURES',detail:'Core graph chemistry is already exactly reused, but primary original atom drag grows bonds/atoms while React moves coordinates. Restore source 74px/30-degree growth, ring closure, chain, bond cycling/erase, clean-up, transient previews, keyboard growth and original label/bond rendering.'},
    {id:'C3-CONTEXT',detail:'Restore source introduction sequence and connected B reaction diagrams with embedded slots/checks/masses/coefficient/equilibrium arrows; C has node-adjacent checks. Retain sequential policies, historical drawings, hydrazone qualification and K erratum.'}
  ],
  sourceFacts:{dotRecords:{alevel:91,igcse:72,exactBankEquality:true,referenceSelfChecks:true,electronCoordinateComparisons:2380},molecule:{mappedOperations:15,contextGaps:6,coreBodyExact:true},fingerprintedWorkerInputs:129,screenshots:82,protectedOriginals:validation.protectedOriginals,currentAcceptedInputFiles:545},
  substantiveForemanReview:{source:'Reviewed current shared player/editor/host boundaries, source dot palette/DOM and circles snapshot behaviour, independent chemistry engines and current C3 erratum review; reviewed both complete worker inventories/ownership/gates.',rendered:'Viewed original/current desktop dot workspace and IGCSE mobile KI answers; original/current desktop molecule editor and mobile B context. Differences substantiate reported gaps; matching-compound E1 comparison is still required.',decision:'Both audit jobs accepted. No genuine ambiguity requiring separate reviewer; E1 remains root-gated.'},
  E1:{
    authorisation:'Pending root E0 acceptance; no additional user permission required within existing scope.',
    staffing:'Reuse E02 and E03 with bounded handoffs, one E01 foreman owns shared integration; no extra routine reviewer. One separate exception reviewer only for genuine substantive failure/ambiguity.',
    ownership:{
      E02:{jobId:'DOT-CROSS-RESTORE',paths:['src/editors/dot-and-cross/**','src/chemistry/dot-and-cross/engine.ts','src/chemistry/dot-and-cross/layout.js','src/chemistry/dot-and-cross/layout.d.ts','src/chemistry/dot-and-cross/model.ts','src/chemistry/dot-and-cross/interaction.ts (if useful)','validation/editor-restoration/implementation/dot-cross/**'],readOnly:['both dot-and-cross banks/providers/marking','src/chemistry/dot-and-cross/core.js','accepted landing and other editors']},
      E03:{jobId:'MOLECULE-RESTORE',paths:['src/editors/molecule/**','src/chemistry/molecule/engine.ts','src/chemistry/molecule/layout.ts','src/chemistry/molecule/interaction.ts','src/chemistry/molecule/depiction.ts (if useful)','src/activities/olympiad/c3l6/C3L6View.tsx','src/activities/olympiad/c3l6/c3l6.css','validation/editor-restoration/implementation/molecule/**'],readOnly:['src/chemistry/molecule/core.js','C3 policy/content/source-bank/qualification/legacy/bank/panels/dependencies/copied assets','accepted landing and other activities']},
      E01:{jobId:'EDITOR-INTEGRATION',paths:['src/foundation/ActivityHost.tsx','src/foundation/OlympiadHost.tsx (only if required)','src/ui/QuestionPlayer.tsx','src/ui/ResponseControl.tsx','src/ui/EditorFrame.tsx','src/ui/DotCrossPlayer.tsx (if useful)','src/ui/Content.tsx and DiagramViewport.tsx (only bounded dot fit integration)','src/styles/platform.css (only scoped editor presentation)','src/contracts/editors.ts','src/persistence/validation.ts','scripts/editor-restoration verification helpers','validation/editor-restoration/implementation/integration/**','editor-restoration-progress.json'],readOnly:['src/landing/**','historical S0-S5 and landing evidence','scope contracts','attempt/timing/session/mastery algorithms','both original applications and workspace dependencies']}
    },
    interfaces:[
      {id:'WORKSPACE-ASIDE',owner:'E01',shape:'EditorSurfaceProps.workspaceAside?: ReactNode',meaning:'One existing player-owned marking/action/save/feedback pane flows through ResponseControl into dot original sidebar; bypass generic frame for dot only. No duplicate controllers or evidence writes.'},
      {id:'DOT-CIRCLES',owner:'E01 contracts/persistence; E02 engine/editor',shape:'DotCrossState.circles?: boolean',meaning:'Absent=true for historical drafts; explicit boolean only and strict whitelist. View preference excluded from chemical snapshots; all edits/clear/undo/redo preserve it. Toggle adds no chemical undo history, marks, assistance or time. Existing stable IDs only; no full question snapshots.'},
      {id:'DOT-ANSWER',owner:'E01 player/host; E02 renderer',shape:'Existing stable course/question ID resolves checked bank reference; modelSVG/modelImage presentation options or a source-backed pure exported renderer',meaning:'Dynamic source reference fit, white answer surface, same current circles flag. Native React-owned dialog uses existing assist/submit/correction/next commands; close/reopen is UI only. Banks/marking remain unchanged.'},
      {id:'MOLECULE-COMMIT',owner:'E03',shape:'Existing MoleculeEditorProps/MoleculePreview/MoleculeState; local engine command addition for atomic checked graph replacement/clean',meaning:'One immutable semantic edit/history entry per gesture; no storage schema change. SVG React layers reuse pure original label/gesture/layout mathematics.'},
      {id:'C3-CONTROLS',owner:'E03 View; E01 Host',shape:'Existing ChallengeCommand and C3L6ViewProps',meaning:'Draw/select/check/navigate remain policy-authoritative; separate Olympiad saving; all mutation paths respect readOnly. No mastery/revision or standalone prototype registration.'}
    ],
    gates:[
      {id:'SOURCE-FIDELITY',gate:'Matching original/new desktop/tablet/mobile and breakpoint states, exact scoped source topology/geometry/palette/labels/marks/answer fit, substantive image inspection. No-overflow alone insufficient.',owners:['E02','E03','E01 integration','root acceptance']},
      {id:'EDITOR-OPERATIONS',gate:'Meaningful mouse/pointer, keyboard, touch/non-drag tests including drag previews/cancellation/lost capture/outside release, history/clear/clean, semantic grouping, readable fit and view controls; no pointermove persistence.',owners:['E02','E03']},
      {id:'CHEMISTRY',gate:'Complete preserved bank/reference/pool fixtures, all dot coordinate invariants, chemical sample including charge/origins/expanded shells/isomer acceptance; molecule topology/formula/clean invariants and all 22 current C3 alternatives including K rejection and qualification.',owners:['E02','E03']},
      {id:'DOT-ATTEMPT',gate:'Exact landing launch/course/category/level/ID transfer, standalone and revision first assessment/score/time, correction/reveal/hints, scheduler Next, save/quota retry, pause/reload/resume same attempt/diagram/circles; one independent evidence record; teacher/read-only creates zero evidence; old keys never written.',owners:['E01','E02']},
      {id:'C3-STATE',gate:'Pupil introduction+A/B/C sequential checks/locks, all units/nodes, repeated drawings/history, save/reload/retry/navigation guard and teacher zero writes; completion only in Olympiad channel, no curriculum evidence.',owners:['E03','E01']},
      {id:'ACTIVE-TIME',gate:'Fresh browser same-attempt restore/idle/background/suspension boundaries, stop on first assessment, no retry/reveal time growth and stats transfer. Preserve established allowances and retained native limitations; new current source-bound evidence supplements immutable historical reports.',owners:['E01','E02']},
      {id:'REGRESSION-BUILD',gate:'Pinned project typecheck; focused new tests plus applicable retained regression/registration/timing/landing tests; both builds, runtime manifests and budget, prefixes/refresh; protected-original hashes/metadata-only limits; unrelated source/landing preservation.',owners:['E01']}
    ],
    evidencePolicy:'New current gates/closure/evidence under editor-restoration. Historical S0-S5/landing freeze and reports remain byte exact after E1 edits; never rerun historical writers into old destinations or weaken assertions. Redirect reproducible compatible checks, retain original source hash and document replaced stage bindings. Legacy whole-tree freezes are historical after authorised edits.',
    stop:'Return one final aggregate or genuine systemic/consequential exception. No publication.'
  },
  unresolved:[],
  limits:['Audit captures are headless Edge fresh-context browser-engine evidence, not native foreground or physical-device certification. Exhaustive gesture/timing/restore/save-failure checks remain E1 work.','Molecule audit source carbonyl/current methanol screenshots illustrate interface differences; E1 must compare matching compounds/states.','Original C source used documented developer inspection while React C was teacher reference; pupil end-to-end flow remains E1 verification.','Known 523 original offline placeholders retain metadata-only evidence; none opened or hydrated.','Effective root/foreman/worker settings and complete usage are unexposed; no token/cost totals invented.'],
  evidenceHashes:evidence.map(file=>({path:'validation/editor-restoration/audit/'+file,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(here,file))).digest('hex')}))
};
fs.writeFileSync(path.join(here,'foreman-report.json'),JSON.stringify(report,null,2)+'\n');
const progress=read('editor-restoration-progress.json');
progress.stages.E0={status:'awaiting_root_acceptance',foremanReport:'validation/editor-restoration/audit/foreman-report.json',jobs:[{agentId:'E02',jobId:'DOT-CROSS-AUDIT',status:'accepted_by_foreman',evidence:'validation/editor-restoration/audit/dot-cross/completion.json'},{agentId:'E03',jobId:'MOLECULE-AUDIT',status:'accepted_by_foreman',evidence:'validation/editor-restoration/audit/molecule/completion.json'}]};
progress.updatedAt=new Date().toISOString();progress.nextAction='Root E0 acceptance before any E1 runtime changes.';
fs.writeFileSync(path.join(project,'editor-restoration-progress.json'),JSON.stringify(progress,null,2)+'\n');
console.log(JSON.stringify({status:'PASS',rootGate:report.rootGate,report:'validation/editor-restoration/audit/foreman-report.json',runtimeUnchanged:true}));
