import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {productionRegistry} from '../../../../src/foundation/registry.ts';
const here=import.meta.dirname,app=path.resolve(here,'../../../..'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.f08-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const all=JSON.parse(fs.readFileSync(path.join(here,'../../f2/shared/resume-f08/fixtures.json'))),fixtures=all.filter(f=>['calorimetry','bond'].includes(f.source.family)&&!f.question.parts.some(p=>p.kind==='energy-profile'));
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={agentId:'F08',jobId:'F2-SHARED',status:'RUNNING',startedAt:new Date().toISOString(),checks:[],shots:[],errors:[],limits:['Fresh synthetic app IndexedDB namespaces and nonpersistent contexts only.','Native OS suspend/minimize coverage retained by foreman; this browser suite checks reload and first timing.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.locator('.source-player').screenshot({path:path.join(here,name+'.png')});report.shots.push(name+'.png')}
async function start(c,f,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5188/${f.course}.html?run=f08-f3-${Date.now()}-${Math.random().toString(36).slice(2)}`);await p.locator('.original-landing').waitFor({state:'attached'});
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();if(f.course==='alevel'&&f.gem.startsWith('u6'))await p.locator('#flipYear').click();const gem=p.locator('[data-leaf="'+f.gem+'"]').first();await gem.locator('xpath=ancestor::*[contains(@class,"topic-section")]').locator('.topic-trigger').click();await gem.click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click()}
 else{await p.evaluate(gem=>location.hash=gem,f.gem);await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${f.ref.level}"]`).click()}
 await p.locator('.question-player').waitFor();await flush(p);
 if((await snap(p)).question.ref.questionId!==f.ref.questionId|| (await snap(p)).question.ref.level!==f.ref.level){await p.evaluate(async f=>{const s=window.__mastersActivity.snapshot(),{productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const a=productionRegistry.get(f.activity),provider=await a.provider();provider.restore(f.ref);const id=crypto.randomUUID(),target={...s.attempt.target,gemId:f.gem,level:f.ref.level},attempt={...s.attempt,attemptId:id,ref:f.ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{...s.attempt.timing,attemptId:id,activeMs:0,finished:false}};const session={...s.session,currentAttemptId:id,...(s.session.kind==='practice'?{target,previousQuestionIds:[f.ref.questionId]}:{})};const repo=createChemistryRepository(s.databaseName),saved=await repo.saveCurriculum({attempt,session,question:provider.restore(f.ref),namespace:attempt.namespace});if(!saved.ok)throw Error(JSON.stringify(saved));repo.close?.()},f);await p.reload();await p.locator('.source-player').waitFor();await flush(p)}
 assert.equal((await snap(p)).question.ref.questionId,f.ref.questionId);return p;
}
function answers(f){const out={};for(const part of f.question.parts){if(part.kind==='numeric')out[part.id]={kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit};if(part.kind==='text')out[part.id]={kind:'text',value:part.accepted[0]};if(part.kind==='choice')out[part.id]={kind:'choice',selected:part.acceptedOptionSets[0]};if(part.kind==='correction'){const s=part.segments.find(x=>x.id===f.source.practical.correction.errorId);out[part.id]={kind:'correction',selections:[s],replacement:f.source.practical.fields[0].answers[0]}}}return out}
async function fill(p,f,data){for(const part of f.question.parts){const r=data[part.id];if(!r)continue;if(r.kind==='numeric'){const inputs=p.locator('.response-input');await inputs.nth(f.question.parts.filter(x=>x.kind==='numeric').findIndex(x=>x.id===part.id)).fill(r.raw)}else if(r.kind==='text'){await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.value)}else if(r.kind==='choice'){const field=p.locator('.choice-field,.choice-box').filter({has:p.getByText(f.source.fields[part.id].label,{exact:true})});if(f.source.family==='practical'){for(const selected of r.selected)await field.getByText(selected,{exact:true}).click()}else{for(const selected of r.selected)await field.getByRole('button').filter({hasText:selected}).click()}}else if(r.kind==='correction'){await p.getByRole('button',{name:r.selections[0].text.trim(),exact:true}).click();await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.replacement)}}await flush(p)}
async function wrong(f,correct){const a=productionRegistry.get(f.activity),policy=await a.marking();for(const part of f.question.parts){const v=correct[part.id];const candidates=part.kind==='numeric'?['999999']:part.kind==='choice'?part.options.map(o=>o.id).filter(id=>!v.selected.includes(id)):part.kind==='correction'?['increases','wrong']:['0','1','2','3','4','5','6','proton','neutron','ionic','covalent','metallic','endothermic','exothermic','positive','negative','wrong'];for(const x of candidates){const copy=structuredClone(correct);copy[part.id]=v.kind==='numeric'?{...v,raw:x}:v.kind==='choice'?{...v,selected:v.selected.length===1?[x]:[x,...v.selected.slice(1)]}:v.kind==='correction'?{...v,replacement:x}:{...v,value:x};const outcome=policy.mark(f.question,copy);if(outcome.accepted&&outcome.marks.earned<outcome.marks.available)return copy}}throw Error('No meaningful wrong fixture '+f.ref.questionId)}
try {
 for(const size of ['desktop','tablet','mobile']){const viewport={desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}}[size];const families=new Set();
 for(const f of fixtures){const group=f.source.family+(f.source.practical?.diagram??'')+(f.question.parts.some(p=>p.kind==='correction')?'correction':'')+(f.question.parts.some(p=>p.kind==='choice')?'choice':'')+(f.question.parts.some(p=>p.kind==='drawing-self-check')?'drawing':'');if(families.has(group))continue;families.add(group);const tag=size+'-'+f.ref.questionId,c=await b.newContext({viewport,hasTouch:size==='mobile'}),p=await start(c,f);const correct=answers(f),bad=await wrong(f,correct);const numeric=f.question.parts[0].kind==='numeric';assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('.header-question-code').innerText(),f.ref.questionId);assert.equal(await p.locator('.source-player .marking-pane').count(),1);await shot(p,'numeric-'+tag+'-unanswered');
 const firstPart=f.question.parts[0];await fill(p,{...f,question:{...f.question,parts:[firstPart]}},{[firstPart.id]:correct[firstPart.id]});await shot(p,'numeric-'+tag+'-partial');const partial=await snap(p);await p.reload();await p.locator('.source-player').waitFor();await flush(p);assert.equal((await snap(p)).attempt.attemptId,partial.attempt.attemptId);assert.deepEqual((await snap(p)).attempt.currentResponses,partial.attempt.currentResponses);
 // Clear choices before setting a different full response so multiple selectors toggle accurately.
 if(f.question.parts.some(x=>x.kind==='choice'))await p.evaluate(async()=>{for(const part of window.__mastersActivity.snapshot().question.parts)if(part.kind==='choice')await window.__mastersActivity.respond(part.id,{kind:'choice',selected:[]})});await fill(p,f,bad);await p.getByRole('button',{name:f.source.family==='acid'?'Check answers':'Check answer',exact:true}).click();if(f.question.parts.some(x=>x.kind==='drawing-self-check')){await p.getByRole('button',{name:'My drawing needs correction',exact:true}).click()}await p.locator('.assessment-feedback').waitFor();await flush(p);const first=await snap(p);const details=p.locator('.original-first-marking');assert.equal(await details.getAttribute('open'),null);assert.equal(await p.locator('.assessment-feedback .field-results').isVisible(),false);assert(await p.locator('.response-feedback').count()>0);await details.locator('summary').focus();await details.locator('summary').press('Enter');assert.equal(await p.locator('.assessment-feedback .field-results').isVisible(),true);assert.equal(await p.locator('.assessment-feedback .result-row').count(),first.attempt.firstAssessment.marks.points.length);await shot(p,'numeric-'+tag+'-original-details');await details.locator('summary').press('Enter');assert.equal(await p.locator('.assessment-feedback .field-results').isVisible(),false);assert((await p.locator('.assessment-feedback .score').innerText()).includes('First score:'));assert(first.attempt.firstResponse.timing.activeMs>0);assert.equal(first.attempt.timing,undefined);await shot(p,'numeric-'+tag+'-incorrect');
 if(f.question.parts.some(x=>x.kind==='choice'))await p.evaluate(async()=>{for(const part of window.__mastersActivity.snapshot().question.parts)if(part.kind==='choice')await window.__mastersActivity.respond(part.id,{kind:'choice',selected:[]})});await fill(p,f,correct);await p.getByRole('button',{name:'Check correction',exact:true}).click();await p.locator('.correction-feedback').waitFor();await flush(p);assert.deepEqual((await snap(p)).attempt.firstResponse,first.attempt.firstResponse);assert.deepEqual((await snap(p)).attempt.firstAssessment,first.attempt.firstAssessment);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);await shot(p,'numeric-'+tag+'-correction');await p.getByRole('button',{name:'Show worked answer',exact:true}).click();await p.locator('.worked-answer').waitFor();await shot(p,'numeric-'+tag+'-model');await p.reload();await p.locator('.worked-answer').waitFor();await flush(p);assert.equal((await snap(p)).attempt.attemptId,first.attempt.attemptId);assert.deepEqual((await snap(p)).attempt.firstResponse,first.attempt.firstResponse);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);
 const cc=await b.newContext({viewport,hasTouch:size==='mobile'}),cr=await start(cc,f);await fill(cr,f,correct);await cr.getByRole('button',{name:f.source.family==='acid'?'Check answers':'Check answer',exact:true}).click();if(f.question.parts.some(x=>x.kind==='drawing-self-check'))await cr.getByRole('button',{name:'My drawing meets every criterion',exact:true}).click();await cr.locator('.assessment-feedback').waitFor();await flush(cr);const good=await snap(cr);assert.equal(good.attempt.firstAssessment.marks.earned,good.attempt.firstAssessment.marks.available);await shot(cr,'numeric-'+tag+'-correct');
 if(numeric&&f.question.parts[0].workingFramework){const wc=await b.newContext({viewport}),wp=await start(wc,f);await wp.getByRole('button',{name:'Show working framework',exact:true}).first().click();await wp.locator('.working-scaffold').first().waitFor();assert.equal((await snap(wp)).attempt.assistance.length,1);await wp.getByRole('button',{name:'Show working framework',exact:true}).first().click();assert.equal(await wp.locator('.working-scaffold').count(),0);await wp.getByRole('button',{name:'Show working framework',exact:true}).first().click();await wp.locator('.working-input').first().fill('12');await flush(wp);const working=await snap(wp);await wp.reload();await wp.locator('.working-scaffold').waitFor();await flush(wp);assert.deepEqual((await snap(wp)).attempt.currentResponses,working.attempt.currentResponses);await wp.getByRole('button',{name:'Check working',exact:true}).first().click();assert.equal((await snap(wp)).attempt.firstAssessment,undefined);await shot(wp,'numeric-'+tag+'-working');await wc.close()}
 const old=good.attempt.attemptId;await cr.getByRole('button',{name:'Next question',exact:true}).click();await cr.waitForFunction(id=>window.__mastersActivity.snapshot().attempt?.attemptId!==id,old);await flush(cr);assert.equal((await snap(cr)).attempt.phase,'answering');assert.equal((await snap(cr)).attempt.timing.finished,false);report.checks.push({tag,family:group,states:['unanswered','partial','incorrect','correct','correction','model'],restore:true,firstScoreTimeFrozen:true,historyDedup:true,nextFresh:true,overflow:false});console.log('PASS '+tag);await cc.close();await c.close();fs.writeFileSync(path.join(here,'numeric-checkpoint.json'),JSON.stringify(report,null,2));
 }}
 report.status='PASS';assert.equal(report.errors.length,0);
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'numeric-browser-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,shots:report.shots.length,errors:report.errors,failure:report.failure}))}
