import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {productionRegistry} from '../../../../src/foundation/registry.ts';
const here=import.meta.dirname,app=path.resolve(here,'../../../..'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.f08-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const all=JSON.parse(fs.readFileSync(path.join(here,'../../f2/shared/resume-f08/fixtures.json'))),fixtures=all.filter(f=>['acid','calorimetry','bond','bonding','energy','practical'].includes(f.source.family)&&!f.question.parts.some(p=>p.kind==='energy-profile'));
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={agentId:'F08',jobId:'F2-SHARED',status:'RUNNING',startedAt:new Date().toISOString(),checks:[],shots:[],errors:[],limits:['Fresh synthetic app IndexedDB namespaces and nonpersistent contexts only.','Native OS suspend/minimize coverage retained by foreman; this browser suite checks reload and first timing.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.locator('.source-player').screenshot({path:path.join(here,name+'.png')});report.shots.push(name+'.png')}
async function start(c,f,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5188/${f.course}.html?run=f08-f3-${Date.now()}-${Math.random().toString(36).slice(2)}`);await p.locator('.original-landing').waitFor({state:'attached'});
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();if(f.course==='alevel'&&f.gem.startsWith('u6'))await p.locator('#flipYear').click();const gem=p.locator('[data-leaf="'+f.gem+'"]').first();await gem.locator('xpath=ancestor::*[contains(@class,"topic-section")]').locator('.topic-trigger').click();await gem.click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click()}
 else{await p.evaluate(gem=>location.hash=gem,f.gem);await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${f.ref.level}"]`).click()}
 await p.locator('.question-player').waitFor();await flush(p);
 if((await snap(p)).question.ref.questionId!==f.ref.questionId|| (await snap(p)).question.ref.level!==f.ref.level){await p.evaluate(async f=>{const s=window.__mastersActivity.snapshot(),{productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const a=productionRegistry.get(f.activity),provider=await a.provider();provider.restore(f.ref);const id=crypto.randomUUID(),target={...s.attempt.target,gemId:f.gem,level:f.ref.level},attempt={...s.attempt,attemptId:id,ref:f.ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{...s.attempt.timing,attemptId:id,activeMs:0,finished:false}};const session={...s.session,currentAttemptId:id,...(s.session.kind==='practice'?{target,previousQuestionIds:[f.ref.questionId]}:{})};const repo=createChemistryRepository(s.databaseName),saved=await repo.saveCurriculum({attempt,session,question:provider.restore(f.ref),namespace:attempt.namespace});if(!saved.ok)throw Error(JSON.stringify(saved));repo.close?.()},f);await p.reload();await p.locator('.source-player').waitFor();await flush(p)}
 assert.equal((await snap(p)).question.ref.questionId,f.ref.questionId);return p;
}
function answers(f){const out={};for(const part of f.question.parts){if(part.kind==='numeric')out[part.id]={kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit};if(part.kind==='text')out[part.id]={kind:'text',value:part.accepted[0]};if(part.kind==='choice')out[part.id]={kind:'choice',selected:part.acceptedOptionSets[0]};if(part.kind==='correction'){const s=part.segments.find(x=>x.id===f.source.practical.correction.errorId);out[part.id]={kind:'correction',selections:[s],replacement:f.source.practical.fields[0].answers[0]}}}return out}
async function fill(p,f,data){for(const part of f.question.parts){const r=data[part.id];if(!r)continue;if(r.kind==='numeric'){const inputs=p.locator('.response-input');await inputs.nth(f.question.parts.filter(x=>x.kind==='numeric').findIndex(x=>x.id===part.id)).fill(r.raw)}else if(r.kind==='text'){await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.value)}else if(r.kind==='choice'){const field=p.locator('.choice-field,.choice-box').filter({has:p.getByText(f.source.fields[part.id].label,{exact:true})});if(f.source.family==='practical'){for(const selected of r.selected)await field.getByText(selected,{exact:true}).click()}else{for(const selected of r.selected)await field.getByRole('button').filter({hasText:selected}).click()}}else if(r.kind==='correction'){await p.getByRole('button',{name:r.selections[0].text.trim(),exact:true}).click();await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.replacement)}}await flush(p)}
async function wrong(f,correct){const a=productionRegistry.get(f.activity),policy=await a.marking();for(const part of f.question.parts){const v=correct[part.id];const candidates=part.kind==='numeric'?['999999']:part.kind==='choice'?part.options.map(o=>o.id).filter(id=>!v.selected.includes(id)):part.kind==='correction'?['increases','wrong']:['0','1','2','3','4','5','6','proton','neutron','ionic','covalent','metallic','endothermic','exothermic','positive','negative','wrong'];for(const x of candidates){const copy=structuredClone(correct);copy[part.id]=v.kind==='numeric'?{...v,raw:x}:v.kind==='choice'?{...v,selected:v.selected.length===1?[x]:[x,...v.selected.slice(1)]}:v.kind==='correction'?{...v,replacement:x}:{...v,value:x};const outcome=policy.mark(f.question,copy);if(outcome.accepted&&outcome.marks.earned<outcome.marks.available)return copy}}throw Error('No meaningful wrong fixture '+f.ref.questionId)}

try {
 for(const size of ['desktop','tablet','mobile']){const viewport={desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}}[size];
 for(const f of all.filter(f=>f.source.family==='comparison')){const c=await b.newContext({viewport,hasTouch:size==='mobile'}),p=await start(c,f);const part=f.question.parts[0],tag=size+'-'+f.ref.questionId;
 if(f.ref.level===3){const height=await p.locator('.student-response').evaluate(el=>parseFloat(getComputedStyle(el).minHeight));assert(Math.abs(height-Math.min(680,Math.max(390,viewport.height*.56)))<.01)} assert.equal(await p.locator('.marking-pane').count(),1);await shot(p,'rubric-'+tag+'-unanswered');
 for(const [i,s] of part.sections.entries()){await p.locator('[id$="-'+s.id+'"]').fill(part.rubric.map(r=>r.text).join(' '));if(i===0)await shot(p,'rubric-'+tag+'-partial')}
 await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.locator('.locked-answer').waitFor();await flush(p);const locked=await snap(p);assert.equal(locked.attempt.phase,'rubric-review');assert.equal(locked.attempt.firstAssessment,undefined);assert.equal(locked.attempt.timing,undefined);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,0);await shot(p,'rubric-'+tag+'-self-review');
 // Every rubric point receives a real keyboard-selected immutable text range.
 for(const point of part.rubric){await p.locator('.decision.yes:enabled').click();await p.locator('.keyboard-evidence summary').click();const t=(await snap(p)).attempt.reviews[0].lockedText;await p.getByLabel('Start',{exact:true}).fill('0');await p.getByLabel('End (exclusive)',{exact:true}).fill(String(t.length));await p.getByRole('button',{name:'Use selected text',exact:true}).click()}
 await p.getByRole('button',{name:'Finish marking',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await flush(p);const marked=await snap(p);assert.equal(marked.attempt.firstAssessment.marks.earned,marked.attempt.firstAssessment.marks.available);assert.deepEqual(marked.attempt.firstResponse,locked.attempt.firstResponse);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);assert.equal(await p.getByRole('button',{name:'Finish marking',exact:true}).count(),0);assert.equal(await p.locator('.decision:enabled').count(),0);assert.equal(await p.locator('.keyboard-evidence').count(),0);assert((await p.locator('.answer-card .instruction').innerText()).startsWith('Marking complete.'));assert.equal(await p.locator('.original-first-marking').getAttribute('open'),null);assert.equal(await p.locator('.assessment-feedback .field-results').isVisible(),false);await shot(p,'rubric-'+tag+'-correct');await p.locator('.original-first-marking summary').focus();await p.locator('.original-first-marking summary').press('Enter');assert.equal(await p.locator('.assessment-feedback .result-row').count(),marked.attempt.firstAssessment.marks.points.length);await shot(p,'rubric-'+tag+'-original-details');await p.locator('.original-first-marking summary').press('Enter');await p.getByRole('button',{name:'Show worked answer',exact:true}).click();await shot(p,'rubric-'+tag+'-model');await p.reload();await p.locator('.worked-answer').waitFor();await flush(p);assert.deepEqual((await snap(p)).attempt.firstAssessment,marked.attempt.firstAssessment);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await c.close();
 const nc=await b.newContext({viewport}),np=await start(nc,f);for(const s of part.sections)await np.locator('[id$="-'+s.id+'"]').fill('The structures have different bonding and properties.');await np.getByRole('button',{name:'Check answer',exact:true}).click();await np.locator('.locked-answer').waitFor();for(const point of part.rubric)await np.locator('.decision.no:enabled').click();await np.getByRole('button',{name:'Finish marking',exact:true}).click();await np.locator('.assessment-feedback').waitFor();assert.equal((await snap(np)).attempt.firstAssessment.marks.earned,0);await shot(np,'rubric-'+tag+'-incorrect');await nc.close();report.checks.push({tag,keyboardEvidence:true,selfReview:true,firstScoreTimeFrozen:true,reload:true,historyDedup:true,overflow:false});console.log('PASS rubric '+tag);
 }}report.status='PASS';assert.equal(report.errors.length,0);
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'rubric-browser-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,shots:report.shots.length,errors:report.errors,failure:report.failure}))}
