import {chromium} from '../../../../../../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {productionRegistry} from '../../../../src/foundation/registry.ts';
const here=import.meta.dirname,run=`a15-dot-charge-${Date.now()}`,report={jobId:'S5-FIX-DOT-CHARGE-TYPING',agentId:'A15',startedAt:new Date().toISOString(),status:'RUNNING',browser:'pinned workspace Playwright with installed Edge, headless, unthrottled; real trusted keyboard typing',checks:[],typing:[],errors:[]};
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot()),flush=()=>page.evaluate(()=>window.__mastersActivity.flush()),diagram=async()=>(await snap()).attempt.currentResponses.diagram;
async function seed(course){const ref={activityId:`${course}/dot-and-cross`,questionId:'h2',seed:0,level:1},reg=productionRegistry.get(ref.activityId),question=(await reg.provider()).restore(ref),target={course,activityId:ref.activityId,gemId:(reg.gems.find(g=>g.id==='fourth-3-2')??reg.gems[0]).id,level:1},namespace={course,profileId:'local'},id=`${run}-${course}-h2`,attempt={mode:'student',namespace,attemptId:id,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:reg.idleAllowance(question),finished:false}},session={kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:id,previousQuestionIds:[]};
 await page.goto(`http://127.0.0.1:5211/${course}.html?run=${run}-${course}`);await page.getByRole('button',{name:'Start practice',exact:true}).waitFor();const dbName=(await snap()).databaseName;await page.evaluate(async({dbName,course,attempt,session})=>{const db=await new Promise((r,j)=>{const q=indexedDB.open(dbName);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});await new Promise((r,j)=>{const t=db.transaction(['attempts','sessions'],'readwrite');for(const [name,value,id]of [['attempts',attempt,attempt.attemptId],['sessions',session,session.id]])t.objectStore(name).put({course,profileId:'local',id,value});t.oncomplete=r;t.onerror=()=>j(t.error);});db.close();},{dbName,course,attempt,session});await page.reload();await page.locator('.dc-canvas').waitFor();assert.equal((await snap()).question.ref.questionId,'h2');return id;
}
async function alternatives(){const details=page.locator('.editor-alternatives');if(!await details.evaluate(el=>el.open))await details.locator(':scope > summary').click();}
const charge=()=>page.getByLabel('Ion charge',{exact:true});
async function typeCharge(value){await charge().click();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.press('Backspace');assert.equal(await charge().inputValue(),'');const steps=[{stage:'clear',value:''}];for(const character of value){await page.keyboard.type(character);steps.push({stage:`type ${character}`,value:await charge().inputValue()});}assert.equal(await charge().inputValue(),value);report.typing.push({course:(await snap()).question.ref.activityId,value,steps});}
async function applyCharge(){await page.getByRole('button',{name:'Apply bracket and charge',exact:true}).click();await flush();}
try{
 for(const course of ['alevel','igcse']){const attemptId=await seed(course);await alternatives();await page.getByRole('button',{name:'Add atom',exact:true}).click();await flush();await page.locator('.dc-atom-list').getByRole('button',{name:'H a1',exact:true}).click();assert.equal(await charge().inputValue(),'1');
  await page.evaluate(()=>{window.__a15ChargeEvents=[];document.querySelector('[aria-label="Ion charge"]').addEventListener('input',event=>window.__a15ChargeEvents.push({trusted:event.isTrusted,value:event.target.value,inputType:event.inputType,data:event.data}));});
  for(const value of ['-1','+2','0','-9','9']){const prior=structuredClone(await diagram());await typeCharge(value);assert.deepEqual(await diagram(),prior);await applyCharge();assert.equal((await diagram()).groups[0].charge,Number(value));assert.equal((await diagram()).groups[0].bracket,true);}
  report.checks.push(`${course}: trusted clear/sign/digit typing preserves raw text and Apply commits −1,+2,0,−9,+9 exactly`);
  for(const invalid of ['','-','+','1.5','1e2','NaN','Infinity','10','-10','abc','--1']){const prior=structuredClone(await diagram());await typeCharge(invalid);await applyCharge();assert.deepEqual(await diagram(),prior,`${invalid}: no graph/history mutation`);assert((await page.locator('.dc-status').innerText()).includes('complete integer charge'));}
  report.checks.push(`${course}: blank, incomplete sign, non-integer, non-finite, out-of-range and malformed text are rejected without semantic edits`);
  await typeCharge('-1');await applyCharge();const committed=structuredClone(await diagram());await page.getByRole('button',{name:'Undo',exact:true}).click();await flush();assert.notEqual((await diagram()).groups[0].charge,-1);assert.equal(await charge().inputValue(),'-1');await page.getByRole('button',{name:'Redo',exact:true}).click();await flush();assert.deepEqual((await diagram()).groups,committed.groups);
  await typeCharge('-');const partialGraph=structuredClone(await diagram());await page.locator('.dc-atom-list').getByRole('button',{name:'H a1',exact:true}).click();assert.equal(await charge().inputValue(),'-');assert.deepEqual(await diagram(),partialGraph);await page.locator('.dc-atom-list').getByRole('button',{name:'H a1',exact:true}).click();
  const trustedEvents=await page.evaluate(()=>window.__a15ChargeEvents);assert(trustedEvents.length>0);assert(trustedEvents.every(event=>event.trusted));report[`${course}TrustedEvents`]=trustedEvents;
  await page.reload();await page.locator('.dc-canvas').waitFor();assert.equal((await snap()).attempt.attemptId,attemptId);assert.deepEqual((await diagram()).groups,committed.groups);assert.deepEqual((await diagram()).history,committed.history);await alternatives();assert.equal(await charge().inputValue(),'1');assert.equal(await page.getByRole('button',{name:'Apply bracket and charge',exact:true}).isEnabled(),false);
  await page.locator('.dc-atom-list').getByRole('button',{name:'H a1',exact:true}).click();await typeCharge('-1');await applyCharge();assert.equal((await diagram()).groups[0].charge,-1);assert.equal((await snap()).attempt.phase,'answering');assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,0);report.checks.push(`${course}: selection, undo/redo and reload preserve semantic groups/history; editing/applying creates no independent evidence`);
  await page.screenshot({path:path.join(here,`${course}-negative-charge.png`),fullPage:true});
  await page.setViewportSize({width:390,height:844});await typeCharge('-1');await applyCharge();assert.equal((await diagram()).groups[0].charge,-1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,0);await page.screenshot({path:path.join(here,`${course}-mobile-charge.png`),fullPage:true});report.checks.push(`${course}: trusted signed typing and Apply work at 390px with no overflow or evidence`);await page.setViewportSize({width:1440,height:1100});
  await page.goto(`http://127.0.0.1:5211/${course}.html?run=${run}-${course}-teacher&mode=teacher&review=h2`);await page.getByRole('heading',{name:'Checked answer and diagrams',exact:true}).waitFor();assert.equal(await charge().count(),0);assert.equal(await page.getByRole('button',{name:'Apply bracket and charge',exact:true}).count(),0);assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,0);report.checks.push(`${course}: accepted S4 teacher view has checked models, no editable controls and no evidence`);
 }
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;try{await page.screenshot({path:path.join(here,'browser-failure.png'),fullPage:true});}catch{}}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(here,run+'.json'),JSON.stringify(report,null,2));await browser.close();}console.log(JSON.stringify({status:report.status,checks:report.checks,failure:report.failure}));
