import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),source='src/editors/dot-and-cross/DotCrossEditor.tsx',prior=path.join(project,'validation/s3/igcse-dot-cross');
const files=['activity.test.mjs','test_dot_cross_bank.mjs','alevel-activity.test.mjs','alevel-test_dot_cross_alevel.mjs','alevel-test_dot_cross_isomers.mjs','alevel-test_dot_cross_lithium.mjs','alevel-test_dot_cross_pair_layout.mjs'];
const provenance=[];
for(const name of files){const original=fs.readFileSync(path.join(prior,name),'utf8');provenance.push({path:`validation/s3/igcse-dot-cross/${name}`,sha256:createHash('sha256').update(original).digest('hex'),adaptation:'Only import/root depth changes for S5 evidence folder; assertions and output semantics unchanged.'});fs.writeFileSync(path.join(here,name),original.replaceAll("'../../../src/","'../../../../src/").replaceAll("'../../../../..'","'../../../../../..'"));}
fs.writeFileSync(path.join(here,'copied-regression-provenance.json'),JSON.stringify(provenance,null,2));
const commands=[['typecheck',[path.join(project,'node_modules/typescript/bin/tsc'),'--noEmit']],['prettier-check',[path.join(project,'node_modules/prettier/bin/prettier.cjs'),'--check',source]],['protected-originals',[path.join(project,'scripts/protect-originals.mjs'),'check']],...files.map(name=>[name,[...(name.includes('activity.test')||name.includes('pair_layout')?['--test']:[]),path.join(here,name)]])];
const checks=commands.map(([name,args])=>{const result=spawnSync(process.execPath,args,{cwd:project,encoding:'utf8'});fs.writeFileSync(path.join(here,name+'.log'),result.stdout+(result.stderr??''));return {name,command:[process.execPath,...args],exitCode:result.status,passed:result.status===0};});
const bytes=fs.readFileSync(path.join(project,source)),before=JSON.parse(fs.readFileSync(path.join(here,'before.json'),'utf8'));const diff=spawnSync('git',['diff','--no-index','--',path.join(here,'before.tsx.txt'),path.join(project,source)],{encoding:'utf8'});if(![0,1].includes(diff.status))throw Error(diff.stderr);fs.writeFileSync(path.join(here,'source.diff'),diff.stdout);fs.writeFileSync(path.join(here,'after.json'),JSON.stringify({source,beforeSha256:before.sha256,sha256:createHash('sha256').update(bytes).digest('hex'),changedFiles:[source],diff:'source.diff',checkedAt:new Date().toISOString()},null,2));
const report={checkedAt:new Date().toISOString(),status:checks.every(c=>c.passed)?'PASS':'FAIL',checks};fs.writeFileSync(path.join(here,'checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(checks.some(c=>!c.passed))process.exitCode=1;
