import {chromium} from '../../../../node_modules/playwright/index.mjs';
import fs from 'node:fs';import path from 'node:path';
const report={startedAt:new Date().toISOString(),method:'Actual headed Edge offscreen; Playwright background suppression defaults removed, CDP focus emulation explicitly disabled. No replacement visibility properties/events.',observations:[],errors:[]};
const browser=await chromium.launch({channel:'msedge',headless:false,args:['--window-position=-32000,-32000'],ignoreDefaultArgs:['--disable-background-timer-throttling','--disable-backgrounding-occluded-windows','--disable-renderer-backgrounding']});
const context=await browser.newContext({viewport:null});await context.addInitScript(()=>{window.ebpEvents=[];for(const type of ['visibilitychange','freeze','resume'])document.addEventListener(type,e=>window.ebpEvents.push({type:e.type,trusted:e.isTrusted,wall:Date.now(),hidden:document.hidden,focused:document.hasFocus()}));for(const type of ['blur','focus'])window.addEventListener(type,e=>window.ebpEvents.push({type:e.type,trusted:e.isTrusted,wall:Date.now(),hidden:document.hidden,focused:document.hasFocus()}));});
const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Emulation.setFocusEmulationEnabled',{enabled:false});
async function observe(label){report.observations.push(await page.evaluate(label=>({label,wall:Date.now(),hidden:document.hidden,focused:document.hasFocus(),events:window.ebpEvents,timing:window.__mastersActivity?.snapshot().attempt?.timing}),label));}
try{
 await page.goto('http://127.0.0.1:5197/alevel.html?run=ebp-native-'+Date.now()+'&view=practice&activity=alevel/explaining-properties&gem=l6-t2-1-properties&level=1&fresh=1');await page.locator('.question-player').waitFor();await page.locator('.question-player').click({position:{x:40,y:40}});await page.waitForTimeout(1200);await observe('foreground');
 const other=await context.newPage();await other.goto('about:blank');const otherCdp=await context.newCDPSession(other);await otherCdp.send('Emulation.setFocusEmulationEnabled',{enabled:false});await other.bringToFront();await new Promise(resolve=>setTimeout(resolve,6500));await observe('background via other tab');
 await page.bringToFront();await page.waitForTimeout(1200);const {targetInfo}=await cdp.send('Target.getTargetInfo'),root=await browser.newBrowserCDPSession(),{windowId}=await root.send('Browser.getWindowForTarget',{targetId:targetInfo.targetId});await root.send('Browser.setWindowBounds',{windowId,bounds:{windowState:'minimized'}});await new Promise(resolve=>setTimeout(resolve,6500));await observe('native window minimized');
 await root.send('Browser.setWindowBounds',{windowId,bounds:{windowState:'normal'}});await page.bringToFront();await page.waitForTimeout(1200);await observe('restored');await other.close();
}catch(error){report.errors.push(error.stack);}finally{report.status=report.observations.some(o=>o.hidden&&o.events.some(e=>e.type==='visibilitychange'&&e.trusted&&e.hidden))?'ESTABLISHED':'UNESTABLISHED';report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(import.meta.dirname,'background-probe.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));await context.close();await browser.close();}
