import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {propertiesBank} from '../../src/activities/alevel/explaining-properties/bank.ts';
import {propertiesProvider,correctedSentence} from '../../src/activities/alevel/explaining-properties/provider.ts';
const notes={
 '2.2.2(a)':'Electrostatic attraction between oppositely charged ions, not repulsion or discrete pair transfer definition.',
 '2.2.2(b)':'Extended alternating giant ionic lattice, ions not molecules; charges/species and all-directions attraction checked. CaO gaps: A=O²⁻, B=Ca²⁺; second fragment has4Ca²⁺/4O²⁻.',
 '2.2.2(c)':'Melting/boiling: strong electrostatic attractions/large energy; conductivity: fixed vs mobile ions; dissolving: ions separate/surrounded by water with correct partial-charge orientation; solubility qualified as some/not all. No ionic intermolecular-force or neutral-atom explanation credited.',
 '2.2.2(f)':'Larger average bond enthalpy denotes stronger covalent bond and greater average energy per mole to break; hypothetical400>250, X–Z stronger. No reaction enthalpy calculation or boiling-point inference.',
};
const review={jobId:'EBP-IMPLEMENT',agentId:'A01-EBP',reviewedAt:new Date().toISOString(),kind:'Author substantive chemistry/pedagogy review, separate from deterministic tests and independent review',specification:'OCR Chemistry A Version3.1 May2026, retained retrieval4October2026',items:propertiesBank.map(record=>({code:record.code,level:record.level,format:record.format,spec:record.spec,provenance:record.provenance,status:'AUTHOR_CHECKED',correctedExplanation:correctedSentence(record),review:notes[record.spec],marks:propertiesProvider.restore(propertiesProvider.resolveLink(record.code)).parts.reduce((sum,part)=>sum+part.marks,0)})),renderedReview:{status:'AUTHOR_CHECKED',evidence:['desktop-EBP-K7M2Q9.png','mobile-EBP-K7M2Q9.png','desktop-EBP-C6R2Y8.png','mobile-EBP-C6R2Y8.png','desktop-EBP-S8L4J2.png','mobile-EBP-S8L4J2.png','desktop-EBP-I5B9S3.png','mobile-EBP-I5B9S3.png','production-mobile-lattice.png','alevel-prefix-practice.png','statistics-timing.png'],notes:'Actual exported/rendered screens inspected: all required labels/charges are legible, diagrams show correct alternating species, coherent sentences/selectable phrases, keyboard/touch controls, no body overflow or visible timer. Teacher32-route rendered coverage is in browser-results.json.'},independentReview:'Pending root-managed separate reviewer',fingerprint:crypto.createHash('sha256').update(fs.readFileSync(path.join(import.meta.dirname,'../../src/activities/alevel/explaining-properties/bank.ts'))).digest('hex')};
fs.writeFileSync(path.join(import.meta.dirname,'chemical-review.json'),JSON.stringify(review,null,2)+'\n');
