import {chromium} from '../../../../node_modules/playwright/index.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const here=import.meta.dirname,project=path.resolve(here,'../..'),temp=path.join(here,'browser-temp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const report={status:'RUNNING',startedAt:new Date().toISOString(),method:'Actual production builds served under /review/ prefix; fresh Edge context; canonical routes/refresh and shared course switch.',checks:[],failures:[],errors:[],httpFailures:[]};
const server=http.createServer((request,response)=>{try{const [prefix,course,...segments]=decodeURIComponent(new URL(request.url,'http://local').pathname).split('/').filter(Boolean);assert.equal(prefix,'review');assert(['alevel','igcse'].includes(course));const root=path.join(project,'dist',course),file=path.resolve(root,...(segments.length?segments:['index.html']));assert(file.startsWith(root+path.sep));assert(fs.statSync(file).isFile());response.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf','.json':'application/json'})[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(response);}catch{response.writeHead(404).end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port+'/review';
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',error=>report.errors.push(error.message));page.on('response',response=>{if(response.status()>=400)report.httpFailures.push({url:response.url(),status:response.status()});});
try{
 for(const course of ['alevel','igcse']){
  await page.goto(`${base}/${course}/?course=${course}&view=home`);await page.locator('.original-landing').waitFor();assert.equal(await page.evaluate(()=>typeof window.__mastersActivity),'undefined');
  if(course==='igcse')await page.getByRole('switch',{name:'A Level Chemistry',exact:true}).click();await page.locator('.original-landing.alevel.navigation-ready').waitFor();assert.equal(await page.getByRole('switch',{name:'A Level Chemistry',exact:true}).getAttribute('aria-checked'),'true');
  await page.getByRole('button',{name:/Explaining Properties.*practice available/}).click();await page.locator('[data-practice="1"]').click();await page.locator('.question-player').waitFor();assert.match(await page.locator('.header-question-code').innerText(),/^EBP-[A-Z0-9]{6}$/);await page.reload();await page.locator('.question-player').waitFor();await page.screenshot({path:path.join(here,course+'-prefix-practice.png'),fullPage:true});report.checks.push({id:course+'-prefix-practice-switch-refresh',status:'PASS'});
 }
 await page.goto(`${base}/alevel/index.html?activity=alevel/explaining-properties&review=EBP-S8L4J2&level=2&seed=0`);await page.locator('.teacher-answer').waitFor();assert.equal(await page.locator('.header-question-code').innerText(),'EBP-S8L4J2');await page.reload();await page.locator('.teacher-answer').waitFor();assert.equal(await page.locator('.header-question-code').innerText(),'EBP-S8L4J2');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(here,'production-mobile-lattice.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.checks.push({id:'canonical-EBP-source-link-prefix-refresh',status:'PASS'});
 for(const course of ['alevel','igcse']){
  const manifest=JSON.parse(fs.readFileSync(path.join(project,'release',course+'.runtime.json'),'utf8'));
  for(const file of manifest.files){const response=await fetch(`${base}/${course}/${file.path}`);assert.equal(response.status,200,file.path);assert.equal((await response.arrayBuffer()).byteLength,file.bytes,file.path);}
  report.checks.push({id:course+'-complete-runtime-prefix-closure',status:'PASS',files:manifest.files.length});
 }
 assert.equal(report.errors.length,0);assert.equal(report.httpFailures.length,0);
}catch(error){report.failures.push(error.stack);await page.screenshot({path:path.join(here,'production-prefix-failure.png'),fullPage:true}).catch(()=>{});}finally{report.status=report.failures.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'prefix-browser-results.json'),JSON.stringify(report,null,2)+'\n');await context.close();await browser.close();await new Promise(resolve=>server.close(resolve));console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;}
