import {chromium} from '../../../../../node_modules/playwright/index.mjs';
import {spawn} from 'node:child_process';
import {mkdirSync,readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {resolve,relative} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {bank} from '../../../src/activities/alevel/ph-titration-curves/bank.ts';
import {answer} from '../../../src/chemistry/titration-curve/core.js';
const here=import.meta.dirname,project=resolve(here,'../../..'),run=`a06s3-${Date.now().toString(36)}`,profile=resolve(project,`.browser/${run}`),port=9368;
mkdirSync(here,{recursive:true});
const sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const fingerprints=root=>readdirSync(root,{withFileTypes:true}).flatMap(e=>{const p=resolve(root,e.name);return e.isDirectory()?fingerprints(p):[{path:relative(project,p).replaceAll('\\','/'),sha256:sha(p)}];});
const relevant=path=>/^(src\/(contracts|domain|persistence|catalogue|foundation|shell|ui|styles)\/|src\/main-|src\/(activities\/alevel\/ph-titration-curves|activities\/igcse\/(calorimetry|bond-enthalpy)|chemistry\/(titration-curve|calorimetry|bond-enthalpy)|editors\/titration-curve)\/)/.test(path);
const priorPath=resolve(project,'validation/s3/thermochemistry/timing-browser-results-ordinary-freeze.json');
const report={agentId:'A06',jobId:'S3-REVIEW-TIMING-ENERGY-TAIL',run,profile,startedAt:new Date().toISOString(),status:'RUNNING',requestedModel:'gpt-6.1-sol',requestedEffort:'high',effectiveModelEffort:null,usage:null,playwright:JSON.parse(readFileSync(resolve(project,'../../node_modules/playwright/package.json'))).version,sourceBefore:fingerprints(resolve(project,'src')),priorEvidence:{path:relative(project,priorPath).replaceAll('\\','/'),sha256:sha(priorPath),result:JSON.parse(readFileSync(priorPath))},observations:[],nativeEvents:[],navigations:[],console:[],pageErrors:[],checks:[],sourcePolicy:'Target-loaded timing/controller/host/repository/contracts/UI/titration/thermochemistry sources must remain unchanged; unrelated worker source changes recorded separately'};
const save=()=>writeFileSync(resolve(here,'energy-results.json'),JSON.stringify(report,null,2)+'\n');save();assert.equal(report.playwright,'1.62.1');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const args=[`--user-data-dir=${profile}`,`--remote-debugging-port=${port}`,'--remote-debugging-address=127.0.0.1','--no-first-run','--no-default-browser-check','--disable-extensions','--disable-background-networking','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows','--disable-gpu','--window-size=1440,1000','about:blank'];
report.launch={exe:'C:/Program Files/Google/Chrome/Application/chrome.exe',args,noDefaults:true,host:'http://127.0.0.1:5188',hmr:false,developmentClient:"Review-owned CSS-only helper; no sockets or lifecycle reload; actual app sources unchanged"};
const child=spawn(report.launch.exe,args,{stdio:['ignore','ignore','pipe'],windowsHide:false});child.stderr.on('data',data=>writeFileSync(resolve(here,'energy-browser-stderr.log'),data,{flag:'a'}));
let browser,page,context,cdp;
try{
 let ready=false;for(let n=0;n<80;n++){try{const r=await fetch(`http://127.0.0.1:${port}/json/version`);if(r.ok){report.endpoint=await r.json();ready=true;break;}}catch{}await delay(250);}assert(ready,'Native isolated Chrome CDP endpoint');
 browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`,{noDefaults:true,isLocal:true,artifactsDir:here});report.browserVersion=browser.version();context=browser.contexts()[0];page=context.pages()[0]??await context.newPage();
 await page.exposeBinding('__a06Record',(_,value)=>report.nativeEvents.push(value));
 await page.addInitScript(()=>{
  const origin=performance.timeOrigin,token=crypto.randomUUID();window.__a06Document={origin,token};
  const emit=(event,stage)=>window.__a06Record({event:event.type,trusted:event.isTrusted,stage,wallMs:Date.now(),monoMs:performance.now(),timeOrigin:origin,token,url:location.href,hidden:document.hidden,focused:document.hasFocus(),key:event.key,attempt:window.__mastersActivity?.snapshot().attempt});
  for(const type of ['visibilitychange','freeze','resume','keydown'])document.addEventListener(type,event=>{emit(event,'capture');queueMicrotask(()=>emit(event,'after handlers'));},{capture:true});
  for(const type of ['focus','blur','pagehide','pageshow'])window.addEventListener(type,event=>{emit(event,'capture');queueMicrotask(()=>emit(event,'after handlers'));},{capture:true});
 });
 page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('framenavigated',frame=>{if(frame===page.mainFrame())report.navigations.push({at:Date.now(),url:frame.url()});});page.on('console',m=>{if(/vite|reload|disconnect/i.test(m.text()))report.console.push({at:Date.now(),text:m.text()});});
 cdp=await context.newCDPSession(page);
 const flush=()=>page.evaluate(async()=>{await window.__mastersActivity.checkpoint();await window.__mastersActivity.flush();});
 const snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot());
 const observe=async label=>{await flush();const o=await page.evaluate(label=>{const s=window.__mastersActivity.snapshot();return {label,wallMs:Date.now(),monoMs:performance.now(),timeOrigin:performance.timeOrigin,token:window.__a06Document.token,hidden:document.hidden,focused:document.hasFocus(),attemptId:s.attempt.attemptId,phase:s.attempt.phase,activeMs:s.attempt.phase==='answering'?s.attempt.timing.activeMs:s.attempt.firstResponse.timing.activeMs,idleLimitMs:s.attempt.phase==='answering'?s.attempt.timing.idleLimitMs:s.attempt.firstResponse.timing.idleLimitMs}},label);report.observations.push(o);save();return o;};
 const start=async(course,target,id)=>{await page.goto(`http://127.0.0.1:5188/${course}.html?run=${run}-${id}`);await page.bringToFront();await page.getByLabel('Target',{exact:true}).selectOption(target);await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>!!window.__mastersActivity?.snapshot().attempt);await flush();};
 async function freeze(id){
  await page.keyboard.press('Tab');await delay(1500);const before=await observe(`${id} before freeze`);assert(!before.hidden&&before.focused);const eventIndex=report.nativeEvents.length,navIndex=report.navigations.length;
  const requestedAt=Date.now();await cdp.send('Page.setWebLifecycleState',{state:'frozen'});const frozenAckAt=Date.now();await delay(6600);const thawRequestedAt=Date.now();await cdp.send('Page.setWebLifecycleState',{state:'active'});await delay(1200);const after=await observe(`${id} after thaw`);
  const events=report.nativeEvents.slice(eventIndex),f=events.find(e=>e.event==='freeze'&&e.stage==='after handlers'),r=events.find(e=>e.event==='resume'&&e.stage==='after handlers');
  const result={id,before,after,requestedAt,frozenAckAt,thawRequestedAt,measuredWallMs:thawRequestedAt-frozenAckAt,events,navigations:report.navigations.slice(navIndex),freeze:f,resume:r};report.suspension??=[];report.suspension.push(result);save();
  assert(f&&r&&f.trusted&&r.trusted);assert.equal(f.timeOrigin,r.timeOrigin);assert.equal(f.token,r.token);assert.equal(f.attempt.attemptId,r.attempt.attemptId);assert(f.hidden&&r.hidden);assert(r.wallMs-f.wallMs>=6500);assert.equal(r.attempt.timing.activeMs,f.attempt.timing.activeMs,'Trusted native suspension boundary must exclude frozen interval');assert.equal(after.timeOrigin,before.timeOrigin);assert.equal(after.token,before.token);assert.equal(result.navigations.length,0);assert.equal(after.activeMs,r.attempt.timing.activeMs);
  await delay(1300);assert.equal((await observe(`${id} thaw remains stopped`)).activeMs,after.activeMs);
  const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await page.bringToFront();await delay(650);const focused=await observe(`${id} native foreground no input`);assert(!focused.hidden&&focused.focused);assert.equal(focused.activeMs,after.activeMs);await page.keyboard.press('Tab');await delay(1600);assert((await observe(`${id} trusted restart`)).activeMs>focused.activeMs);await other.close();report.checks.push(`${id}: same-document trusted freeze/resume, stable thaw and focus-only stop; trusted input resumes`);save();console.log(JSON.stringify({milestone:'SUSPENSION PASS',id,intervalMs:r.wallMs-f.wallMs,activeDeltaMs:0}));
 }

 for(const definition of [{id:'energy',target:'lower-10-1:2',activity:'igcse/energy-enthalpy'},{id:'practical',target:'lower-10-2:2',activity:'igcse/energetics-practical'}]){
  await start('igcse',definition.target,definition.id);let s=await snap();assert.equal(s.attempt.ref.activityId,definition.activity);assert.equal(s.attempt.timing.idleLimitMs,180000);report.cases??=[];const c={...definition,initialRef:s.attempt.ref,initialAttemptId:s.attempt.attemptId};report.cases.push(c);
  const text=page.locator('.question-parts textarea').first();if(await text.count()){await text.fill('I am unsure about this explanation.');await flush();}else{const input=page.locator('.question-parts input:not([type=radio]):not([type=checkbox])').first();if(await input.count()){await input.fill('1');await flush();}}
  await page.keyboard.press('Tab');await delay(1400);const foreground=await observe(definition.id+' native foreground');assert(!foreground.hidden&&foreground.focused&&foreground.activeMs>0);
  const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await delay(600);const hidden=await observe(definition.id+' native background');assert(hidden.hidden&&!hidden.focused);await delay(2300);const stopped=await observe(definition.id+' background interval');assert.equal(stopped.activeMs,hidden.activeMs);await page.bringToFront();await delay(1200);assert.equal((await observe(definition.id+' focus without input')).activeMs,hidden.activeMs);await page.keyboard.press('Tab');await delay(1300);assert((await observe(definition.id+' trusted input')).activeMs>hidden.activeMs);await other.close();report.checks.push(definition.id+': actual native background stops; focus alone remains stopped; trusted input resumes');
  await freeze(definition.id);
  await page.getByRole('button',{name:'Pause',exact:true}).click();await flush();const paused=await snap();await delay(1200);await flush();assert.equal((await snap()).attempt.timing.activeMs,paused.attempt.timing.activeMs);await page.reload();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();await flush();s=await snap();assert.equal(s.attempt.attemptId,c.initialAttemptId);assert.deepEqual(s.attempt.ref,paused.attempt.ref);assert.deepEqual(s.attempt.currentResponses,paused.attempt.currentResponses);assert.deepEqual(s.attempt.timing,paused.attempt.timing);assert.equal(s.history.length,0);c.paused=paused;c.restored=s;await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await page.keyboard.press('Tab');await delay(1400);const resumed=await observe(definition.id+' pause reload resumed');assert(resumed.activeMs>paused.attempt.timing.activeMs);c.resumed=resumed;report.checks.push(definition.id+': pause/reload keeps exact ID/ref/response/time; resume trusted input accrues, no false evidence');await page.screenshot({path:resolve(here,definition.id+'-native-tail.png'),fullPage:true});save();console.log(JSON.stringify({milestone:'ENERGY TAIL CASE PASS',id:definition.id}));
 }
 report.sourceAfter=fingerprints(resolve(project,'src'));const b=new Map(report.sourceBefore.map(x=>[x.path,x.sha256])),a=new Map(report.sourceAfter.map(x=>[x.path,x.sha256]));report.changedSourcePaths=[...new Set([...b.keys(),...a.keys()])].filter(p=>b.get(p)!==a.get(p));const selected=p=>/^src\/(domain|persistence|foundation|shell|ui|styles)\//.test(p)||/^src\/(activities\/igcse\/(energy-enthalpy|energetics-practical)|chemistry\/energy-profile|editors\/energy-profile)\//.test(p);report.relevantSourceChanges=report.changedSourcePaths.filter(selected);report.unrelatedSourceChanges=report.changedSourcePaths.filter(p=>!selected(p));assert.deepEqual(report.relevantSourceChanges,[]);assert.deepEqual(report.pageErrors,[]);report.status='PASS';
}catch(error){report.status='ESCALATE';report.failure={message:error.message,stack:error.stack};if(page){report.failureSnapshot=await page.evaluate(()=>({wallMs:Date.now(),monoMs:performance.now(),timeOrigin:performance.timeOrigin,token:window.__a06Document?.token,hidden:document.hidden,focused:document.hasFocus(),snapshot:window.__mastersActivity?.snapshot()})).catch(e=>({error:e.message}));await page.screenshot({path:resolve(here,'energy-failure.png'),fullPage:true}).catch(()=>{});}report.sourceAfter=fingerprints(resolve(project,'src'));console.error(error);}
finally{report.finishedAt=new Date().toISOString();report.scriptSha256=sha(resolve(here,'energy-sample.mjs'));save();if(browser){const session=await browser.newBrowserCDPSession().catch(()=>null);if(session)await session.send('Browser.close').catch(()=>{});await browser.close().catch(()=>{});}child.kill();console.log(JSON.stringify({status:report.status,result:'validation/s3/review-timing/energy-results.json'}));process.exitCode=report.status==='PASS'?0:1;}
