import {chromium} from '../../../../../node_modules/playwright/index.mjs';
import {spawn} from 'node:child_process';
import {mkdirSync,readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {resolve,relative} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {bank} from '../../../src/activities/alevel/ph-titration-curves/bank.ts';
import {answer} from '../../../src/chemistry/titration-curve/core.js';
const here=import.meta.dirname,project=resolve(here,'../../..'),run=`a06s3-${Date.now().toString(36)}`,profile=resolve(project,`.browser/${run}`),port=9368;
mkdirSync(here,{recursive:true});
const sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const fingerprints=root=>readdirSync(root,{withFileTypes:true}).flatMap(e=>{const p=resolve(root,e.name);return e.isDirectory()?fingerprints(p):[{path:relative(project,p).replaceAll('\\','/'),sha256:sha(p)}];});
const relevant=path=>/^(src\/(contracts|domain|persistence|catalogue|foundation|shell|ui|styles)\/|src\/main-|src\/(activities\/alevel\/ph-titration-curves|activities\/igcse\/(calorimetry|bond-enthalpy)|chemistry\/(titration-curve|calorimetry|bond-enthalpy)|editors\/titration-curve)\/)/.test(path);
const priorPath=resolve(project,'validation/s3/thermochemistry/timing-browser-results-ordinary-freeze.json');
const report={agentId:'A06',jobId:'S3-REVIEW-TIMING',run,profile,startedAt:new Date().toISOString(),status:'RUNNING',requestedModel:'gpt-6.1-sol',requestedEffort:'high',effectiveModelEffort:null,usage:null,playwright:JSON.parse(readFileSync(resolve(project,'../../node_modules/playwright/package.json'))).version,sourceBefore:fingerprints(resolve(project,'src')),priorEvidence:{path:relative(project,priorPath).replaceAll('\\','/'),sha256:sha(priorPath),result:JSON.parse(readFileSync(priorPath))},observations:[],nativeEvents:[],navigations:[],console:[],pageErrors:[],checks:[],sourcePolicy:'Target-loaded timing/controller/host/repository/contracts/UI/titration/thermochemistry sources must remain unchanged; unrelated worker source changes recorded separately'};
const save=()=>writeFileSync(resolve(here,'results.json'),JSON.stringify(report,null,2)+'\n');save();assert.equal(report.playwright,'1.62.1');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const args=[`--user-data-dir=${profile}`,`--remote-debugging-port=${port}`,'--remote-debugging-address=127.0.0.1','--no-first-run','--no-default-browser-check','--disable-extensions','--disable-background-networking','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows','--disable-gpu','--window-size=1440,1000','about:blank'];
report.launch={exe:'C:/Program Files/Google/Chrome/Application/chrome.exe',args,noDefaults:true,host:'http://127.0.0.1:5188',hmr:false,developmentClient:"Review-owned CSS-only helper; no sockets or lifecycle reload; actual app sources unchanged"};
const child=spawn(report.launch.exe,args,{stdio:['ignore','ignore','pipe'],windowsHide:false});child.stderr.on('data',data=>writeFileSync(resolve(here,'browser-stderr.log'),data,{flag:'a'}));
let browser,page,context,cdp;
try{
 let ready=false;for(let n=0;n<80;n++){try{const r=await fetch(`http://127.0.0.1:${port}/json/version`);if(r.ok){report.endpoint=await r.json();ready=true;break;}}catch{}await delay(250);}assert(ready,'Native isolated Chrome CDP endpoint');
 browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`,{noDefaults:true,isLocal:true,artifactsDir:here});report.browserVersion=browser.version();context=browser.contexts()[0];page=context.pages()[0]??await context.newPage();
 await page.exposeBinding('__a06Record',(_,value)=>report.nativeEvents.push(value));
 await page.addInitScript(()=>{
  const origin=performance.timeOrigin,token=crypto.randomUUID();window.__a06Document={origin,token};
  const emit=(event,stage)=>window.__a06Record({event:event.type,trusted:event.isTrusted,stage,wallMs:Date.now(),monoMs:performance.now(),timeOrigin:origin,token,url:location.href,hidden:document.hidden,focused:document.hasFocus(),key:event.key,attempt:window.__mastersActivity?.snapshot().attempt});
  for(const type of ['visibilitychange','freeze','resume','keydown'])document.addEventListener(type,event=>{emit(event,'capture');queueMicrotask(()=>emit(event,'after handlers'));},{capture:true});
  for(const type of ['focus','blur','pagehide','pageshow'])window.addEventListener(type,event=>{emit(event,'capture');queueMicrotask(()=>emit(event,'after handlers'));},{capture:true});
 });
 page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('framenavigated',frame=>{if(frame===page.mainFrame())report.navigations.push({at:Date.now(),url:frame.url()});});page.on('console',m=>{if(/vite|reload|disconnect/i.test(m.text()))report.console.push({at:Date.now(),text:m.text()});});
 cdp=await context.newCDPSession(page);
 const flush=()=>page.evaluate(async()=>{await window.__mastersActivity.checkpoint();await window.__mastersActivity.flush();});
 const snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot());
 const observe=async label=>{await flush();const o=await page.evaluate(label=>{const s=window.__mastersActivity.snapshot();return {label,wallMs:Date.now(),monoMs:performance.now(),timeOrigin:performance.timeOrigin,token:window.__a06Document.token,hidden:document.hidden,focused:document.hasFocus(),attemptId:s.attempt.attemptId,phase:s.attempt.phase,activeMs:s.attempt.phase==='answering'?s.attempt.timing.activeMs:s.attempt.firstResponse.timing.activeMs,idleLimitMs:s.attempt.phase==='answering'?s.attempt.timing.idleLimitMs:s.attempt.firstResponse.timing.idleLimitMs}},label);report.observations.push(o);save();return o;};
 const start=async(course,target,id)=>{await page.goto(`http://127.0.0.1:5188/${course}.html?run=${run}-${id}`);await page.bringToFront();await page.getByLabel('Target',{exact:true}).selectOption(target);await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>!!window.__mastersActivity?.snapshot().attempt);await flush();};
 async function freeze(id){
  await page.keyboard.press('Tab');await delay(1500);const before=await observe(`${id} before freeze`);assert(!before.hidden&&before.focused);const eventIndex=report.nativeEvents.length,navIndex=report.navigations.length;
  const requestedAt=Date.now();await cdp.send('Page.setWebLifecycleState',{state:'frozen'});const frozenAckAt=Date.now();await delay(6600);const thawRequestedAt=Date.now();await cdp.send('Page.setWebLifecycleState',{state:'active'});await delay(1200);const after=await observe(`${id} after thaw`);
  const events=report.nativeEvents.slice(eventIndex),f=events.find(e=>e.event==='freeze'&&e.stage==='after handlers'),r=events.find(e=>e.event==='resume'&&e.stage==='after handlers');
  const result={id,before,after,requestedAt,frozenAckAt,thawRequestedAt,measuredWallMs:thawRequestedAt-frozenAckAt,events,navigations:report.navigations.slice(navIndex),freeze:f,resume:r};report.suspension??=[];report.suspension.push(result);save();
  assert(f&&r&&f.trusted&&r.trusted);assert.equal(f.timeOrigin,r.timeOrigin);assert.equal(f.token,r.token);assert.equal(f.attempt.attemptId,r.attempt.attemptId);assert(f.hidden&&r.hidden);assert(r.wallMs-f.wallMs>=6500);assert.equal(r.attempt.timing.activeMs,f.attempt.timing.activeMs,'Trusted native suspension boundary must exclude frozen interval');assert.equal(after.timeOrigin,before.timeOrigin);assert.equal(after.token,before.token);assert.equal(result.navigations.length,0);assert.equal(after.activeMs,r.attempt.timing.activeMs);
  await delay(1300);assert.equal((await observe(`${id} thaw remains stopped`)).activeMs,after.activeMs);
  const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await page.bringToFront();await delay(650);const focused=await observe(`${id} native foreground no input`);assert(!focused.hidden&&focused.focused);assert.equal(focused.activeMs,after.activeMs);await page.keyboard.press('Tab');await delay(1600);assert((await observe(`${id} trusted restart`)).activeMs>focused.activeMs);await other.close();report.checks.push(`${id}: same-document trusted freeze/resume, stable thaw and focus-only stop; trusted input resumes`);save();console.log(JSON.stringify({milestone:'SUSPENSION PASS',id,intervalMs:r.wallMs-f.wallMs,activeDeltaMs:0}));
 }
 // A12 exact activity family: no long idle repeated; independent native lifecycle only.
 await start('igcse','lower-10-3:1','thermo-freeze');await page.locator('.question-part input').first().fill('1');await freeze('thermochemistry');
 await start('alevel','u6-t1-1-9:2','titration');await page.locator('.tc-chart').waitFor();let s=await snap();assert.equal(s.attempt.timing.idleLimitMs,600000);report.initialAttemptId=s.attempt.attemptId;report.initialRef=s.attempt.ref;
 const record=bank.find(q=>q.id===s.attempt.ref.questionId),a=answer(record),response={kind:'titration-curve',before:a.before,after:a.after,initialPH:a.initialPH,finalPH:a.finalPH,equivalenceVolume:a.equivalenceVolume,indicator:a.indicator};report.controlledAnswer={recordId:record.id,response};await page.evaluate(response=>window.__mastersActivity.respond('curve',response),response);await flush();
 await page.keyboard.press('Tab');await delay(1500);const initial=await observe('titration foreground');assert(!initial.hidden&&initial.focused&&initial.activeMs>0);
 const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await delay(600);const background=await observe('titration native background');assert(background.hidden&&!background.focused);await delay(2700);assert.equal((await observe('titration background interval')).activeMs,background.activeMs);await page.bringToFront();await delay(1300);const returned=await observe('titration focus only');assert(!returned.hidden&&returned.focused);assert.equal(returned.activeMs,background.activeMs);await page.keyboard.press('Tab');await delay(1500);assert((await observe('titration input after background')).activeMs>returned.activeMs);await other.close();report.checks.push('titration native hidden background excludes time; focus alone stopped; trusted input restarts');
 const win=await cdp.send('Browser.getWindowForTarget');await cdp.send('Browser.setWindowBounds',{windowId:win.windowId,bounds:{windowState:'minimized'}});await delay(600);const minimized=await observe('titration minimized');const actualWin=await cdp.send('Browser.getWindowForTarget');report.minimizedBounds=actualWin.bounds;assert.equal(actualWin.bounds.windowState,'minimized');assert(minimized.hidden&&!minimized.focused);await delay(2200);assert.equal((await observe('titration minimized interval')).activeMs,minimized.activeMs);await cdp.send('Browser.setWindowBounds',{windowId:win.windowId,bounds:{windowState:'normal'}});await page.bringToFront();await delay(1300);assert.equal((await observe('titration restored focus only')).activeMs,minimized.activeMs);await page.keyboard.press('Tab');await delay(1500);assert((await observe('titration input after minimized')).activeMs>minimized.activeMs);report.checks.push('actual minimized bounds/native hidden state excludes time and requires trusted restart');
 await freeze('titration');
 await page.getByRole('button',{name:'Pause',exact:true}).click();await flush();const paused=await snap();report.paused=paused;await delay(1500);await flush();assert.equal((await snap()).attempt.timing.activeMs,paused.attempt.timing.activeMs);await page.reload();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();await flush();const restoredPause=await snap();assert.equal(restoredPause.attempt.attemptId,report.initialAttemptId);assert.deepEqual(restoredPause.attempt.currentResponses,paused.attempt.currentResponses);assert.deepEqual(restoredPause.attempt.timing,paused.attempt.timing);report.restoredPause=restoredPause;await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await page.locator('.tc-chart').waitFor();await page.keyboard.press('Tab');await delay(1600);assert((await observe('titration pause reload resume input')).activeMs>paused.attempt.timing.activeMs);report.checks.push('pause/reload preserves exact attempt ID/ref/curve/time; real resume input restarts');
 await page.keyboard.press('Tab');const idleStart=await observe('after last trusted input before ten-minute idle');const key=report.nativeEvents.filter(e=>e.event==='keydown'&&e.trusted&&e.stage==='after handlers'&&e.timeOrigin===idleStart.timeOrigin).at(-1);assert(key);report.idle={keyEvent:key,start:idleStart,nodeStartWall:Date.now()};save();console.log(JSON.stringify({milestone:'REAL TEN-MINUTE IDLE START',allowance:600000}));
 const until=Date.now()+602200;while(Date.now()<until)await delay(Math.min(30000,until-Date.now()));
 const idleEnd=await observe('real source ten-minute idle cutoff');report.idle.end=idleEnd;report.idle.actualWallMs=Date.now()-report.idle.nodeStartWall;report.idle.deltaMs=idleEnd.activeMs-idleStart.activeMs;report.idle.preObservationMs=idleStart.monoMs-key.monoMs;assert(!idleEnd.hidden&&idleEnd.focused);assert.equal(idleEnd.timeOrigin,idleStart.timeOrigin);assert(report.idle.actualWallMs>=600000);assert(report.idle.deltaMs<=600002&&report.idle.deltaMs>=600000-report.idle.preObservationMs-2,`Precise idle delta ${report.idle.deltaMs}`);await delay(1600);assert.equal((await observe('ten-minute cutoff remains stopped')).activeMs,idleEnd.activeMs);report.checks.push('real ten-minute source allowance reaches deadline and stays stopped');save();console.log(JSON.stringify({milestone:'REAL TEN-MINUTE IDLE PASS',wallMs:report.idle.actualWallMs,deltaMs:report.idle.deltaMs}));
 await page.keyboard.press('Tab');await delay(1500);assert((await observe('trusted input after ten-minute idle')).activeMs>idleEnd.activeMs);await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await page.getByTestId('evidence-count').filter({hasText:'1 independent'}).waitFor();await flush();s=await snap();report.firstResponse=structuredClone(s.attempt.firstResponse);report.firstAssessment=structuredClone(s.attempt.firstAssessment);assert.equal(s.attempt.firstAssessment.marks.earned,6);assert.equal(s.history.length,1);assert.deepEqual(s.history[0].timing,report.firstResponse.timing);
 await delay(1500);await page.keyboard.press('Tab');await page.getByRole('button',{name:'Check correction',exact:true}).click();await flush();s=await snap();assert.deepEqual(s.attempt.firstResponse,report.firstResponse);assert.deepEqual(s.attempt.firstAssessment,report.firstAssessment);assert.equal(s.history.length,1);await page.reload();await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.attemptId===id,report.initialAttemptId);await page.locator('.tc-chart').waitFor();await flush();s=await snap();assert.deepEqual(s.attempt.firstResponse,report.firstResponse);assert.deepEqual(s.attempt.firstAssessment,report.firstAssessment);assert.equal(s.history.length,1);report.restoredAssessment=s;await page.screenshot({path:resolve(here,'titration-assessed.png'),fullPage:true});
 await page.getByRole('button',{name:'Next question',exact:true}).click();await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.attemptId!==id,report.initialAttemptId);await page.locator('.tc-chart').waitFor();const fresh=await observe('titration fresh Next');s=await snap();assert.equal(s.attempt.phase,'answering');assert.equal(s.attempt.timing.idleLimitMs,600000);assert(fresh.activeMs<1200);assert.equal(s.history.length,1);report.next=s;report.checks.push('first timing/response/marks immutable after wait/correction/reload; one history record with exact timing; Next fresh ID/time/600000 allowance');
 report.sourceAfter=fingerprints(resolve(project,'src'));const beforeMap=new Map(report.sourceBefore.map(x=>[x.path,x.sha256])),afterMap=new Map(report.sourceAfter.map(x=>[x.path,x.sha256]));report.changedSourcePaths=[...new Set([...beforeMap.keys(),...afterMap.keys()])].filter(p=>beforeMap.get(p)!==afterMap.get(p));report.relevantSourceChanges=report.changedSourcePaths.filter(relevant);report.unrelatedSourceChanges=report.changedSourcePaths.filter(p=>!relevant(p));assert.deepEqual(report.relevantSourceChanges,[],'Target-loaded source must remain quiescent');report.relevantSourceUnchanged=true;assert.deepEqual(report.pageErrors,[]);report.status='PASS';
}catch(error){report.status='ESCALATE';report.failure={message:error.message,stack:error.stack};if(page){report.failureSnapshot=await page.evaluate(()=>({wallMs:Date.now(),monoMs:performance.now(),timeOrigin:performance.timeOrigin,token:window.__a06Document?.token,hidden:document.hidden,focused:document.hasFocus(),snapshot:window.__mastersActivity?.snapshot()})).catch(e=>({error:e.message}));await page.screenshot({path:resolve(here,'failure.png'),fullPage:true}).catch(()=>{});}report.sourceAfter=fingerprints(resolve(project,'src'));console.error(error);}
finally{report.finishedAt=new Date().toISOString();report.scriptSha256=sha(resolve(here,'native-check.mjs'));save();if(browser){const session=await browser.newBrowserCDPSession().catch(()=>null);if(session)await session.send('Browser.close').catch(()=>{});await browser.close().catch(()=>{});}child.kill();console.log(JSON.stringify({status:report.status,result:'validation/s3/review-timing/results.json'}));process.exitCode=report.status==='PASS'?0:1;}
