import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
import{getVariant}from'../../../../../../src/chemistry/electron-configuration/identity.ts';import{data}from'../../../../../../src/chemistry/electron-configuration/data.js';import{referenceState,blankState}from'../../../../../../src/chemistry/electron-configuration/engine.ts';import{same}from'../../../../../../src/chemistry/electron-configuration/core.js';
const here=import.meta.dirname,project=path.resolve(here,'../../../../../..'),require=createRequire(path.resolve(project,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');const temp=path.join(here,'.browser-temp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;const{chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true});
const base='http://127.0.0.1:5188',original='http://127.0.0.1:5197/alevel/activities/electron-configurations/index.html';
const report={jobId:'F2-EC',agentId:'F09',startedAt:new Date().toISOString(),checks:[],screenshots:[],metrics:[],errors:[],limitations:['Native hidden/minimized/OS suspend not newly tested.','Original correction drawing is compared by reopening the same isolated source review question with the corrected response: the original EC source freezes assessed answers and has no correction action. Shared React first evidence remains immutable.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name,selector){await p.evaluate(()=>document.fonts.ready);await p.locator(selector).screenshot({path:path.join(here,name+'.png')});report.screenshots.push(name+'.png');}
async function startReact(ctx,id,mode='practice'){
 const run=`f09-${mode}-${id}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`${base}/alevel.html?view=home&run=${run}`);await p.locator('.original-landing').waitFor();
 await p.evaluate(async({id,run,mode})=>{
  const{createChemistryRepository}=await import('/src/persistence/index.ts'),{getVariant}=await import('/src/chemistry/electron-configuration/identity.ts'),{electronConfigurationsProvider:provider}=await import('/src/activities/alevel/electron-configurations/provider.ts');
  const q=getVariant(id),level=q.kind==='bonus'?3:q.minimumLevel,ref={activityId:'alevel/electron-configurations',questionId:id,level,seed:q.kind==='bonus'?parseInt(id.slice(4),36):0};provider.restore(ref);
  const namespace={course:'alevel',profileId:'local'},target={course:'alevel',activityId:ref.activityId,gemId:'l6-t2-1-2',level},attemptId=`f09-${run}`,attempt={mode:'student',namespace,attemptId,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId,activeMs:0,idleLimitMs:q.kind==='main'&&q.direction==='identify'?60000:180000,finished:false}};
  const session=mode==='revision'?{kind:'revision',namespace,id:'current-session',createdAt:Date.now(),status:'active',selectedGemIds:[target.gemId],levels:[{target,mode:'practice',required:1,streak:0,confirmedAt:null,initialScore:null}],round:[target.gemId],lastGemId:null,current:{attemptId,target,ref,completed:false},previous:[],submittedAttemptIds:[]}:{kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:attemptId,previousQuestionIds:[id],paused:false};
  const repo=createChemistryRepository(`masters-of-chemistry-alpha-v2-alevel-${run}`),a=await repo.saveCurriculum({attempt}),s=await repo.saveSession(session);repo.close();if(!a.ok||!s.ok)throw Error(JSON.stringify([a,s]));
 },{id,run,mode});await p.goto(`${base}/alevel.html?view=${mode}&run=${run}&activity=alevel%2Felectron-configurations`);await p.locator('.ec-workspace').waitFor();await flush(p);assert.equal((await snap(p)).attempt.ref.questionId,id);return p;
}
async function startOriginal(ctx,id){const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(original+`?review=${id}&mode=teacher`);await p.locator('#questionPanel .question-top').waitFor();return p;}
function answerFor(q){if(q.kind==='bonus'){return{...blankState(),selectedSpeciesIds:q.options.filter(id=>same(data.species.find(s=>s.id===id).counts,q.counts))};}return referenceState(q.speciesId,q.representation);}
async function fill(p,q,answer,app){
 if(q.kind==='bonus'){for(const id of q.options){const item=data.species.find(s=>s.id===id);const field=app==='react'?p.locator('.bonus-options input').nth(q.options.indexOf(id)):p.locator(`[data-species="${id}"]`);await field.setChecked(answer.selectedSpeciesIds.includes(id));}return;}
 if(q.direction==='identify'){await p.getByLabel('Element name or symbol',{exact:true}).fill(answer.identity);return;}
 if(q.representation==='row'||q.representation==='energy'){for(const [index,row]of answer.boxes.entries())for(const [orbital,spin]of row.entries()){const box=p.locator(`[data-orbital="${index}:${orbital}"]`);await box.focus();await p.keyboard.press(spin===3?'2':spin===2?'d':String(spin));if(app==='react')await flush(p);}return;}
 if(q.representation==='short')await p.locator('.core-select select').selectOption(answer.core);
 for(const [index,value]of answer.counts.entries()){const field=p.getByLabel(`Electrons in ${data.subshells[index]}`,{exact:true});if(await field.count()){await field.fill(value);if(app==='react')await flush(p);}}
}
async function submit(p,app){await p.getByRole('button',{name:'Check answer',exact:true}).click();if(app==='react'){await p.waitForFunction(()=>window.__mastersActivity.snapshot().attempt.phase==='assessed');await flush(p);}else await p.locator('#feedback').waitFor({state:'visible'});}
async function metrics(p,app,size,family){return p.evaluate(({app,size,family})=>{const pick=s=>{const e=document.querySelector(s);if(!e)return null;const c=getComputedStyle(e),r=e.getBoundingClientRect();return{fontFamily:c.fontFamily,fontSize:c.fontSize,lineHeight:c.lineHeight,fontWeight:c.fontWeight,color:c.color,background:c.backgroundColor,padding:c.padding,border:c.border,borderRadius:c.borderRadius,width:r.width,height:r.height};};return{app,size,family,orbital:pick('.orbital'),notationInput:pick('.subshell-entry input'),card:pick('.species-card'),energy:pick('.energy-diagram'),match:pick('.bonus-option'),overflow:document.documentElement.scrollWidth>innerWidth};},{app,size,family});}

try {
 await Promise.allSettled([['build','EC-GYMGZS',180000],['identify','EC-TXYUKV',60000]].map(async([family,id,limit])=>{
  const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await startReact(ctx,id);
  try {
   const control=family==='build'?p.locator('[data-orbital="0:0"]'):p.getByLabel('Element name or symbol',{exact:true});
   await control.click();await flush(p);const begin=await snap(p);assert.equal(begin.attempt.timing.idleLimitMs,limit);
   const visible=await p.evaluate(()=>({visible:!document.hidden,focused:document.hasFocus()}));assert.deepEqual(visible,{visible:true,focused:true});
   console.log('START '+family+' '+limit+' wall-time idle');
   await p.waitForTimeout(limit+6000);await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);const idle=await snap(p);
   await p.waitForTimeout(6000);await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);const stopped=await snap(p);
   assert.equal(stopped.attempt.timing.activeMs,idle.attempt.timing.activeMs);const idleGap=idle.attempt.timing.activeMs-begin.attempt.timing.activeMs;assert(idleGap>=limit-2000&&idleGap<=limit+2000);
   await control.click();await p.waitForTimeout(1500);await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);const beforeFreeze=await snap(p);
   const cdp=await ctx.newCDPSession(p);await cdp.send('Emulation.setFocusEmulationEnabled',{enabled:false});await p.evaluate(()=>{window.__f09ticks=0;window.__f09timer=setInterval(()=>window.__f09ticks++,250);});const other=await ctx.newPage();const otherCdp=await ctx.newCDPSession(other);await otherCdp.send('Emulation.setFocusEmulationEnabled',{enabled:false});await other.goto('about:blank');await other.bringToFront();await p.waitForTimeout(1000);const background=await p.evaluate(()=>({hidden:document.hidden,focused:document.hasFocus(),ticks:window.__f09ticks}));await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);const hiddenBefore=await snap(p);await p.waitForTimeout(3000);await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);const hiddenAfter=await snap(p);const diag={family,id,limit,idleGap,idleBefore:begin.attempt.timing,idleAfter:idle.attempt.timing,stopped:stopped.attempt.timing,beforeFreeze:beforeFreeze.attempt.timing,background,hiddenBefore:hiddenBefore.attempt.timing,hiddenAfter:hiddenAfter.attempt.timing};fs.writeFileSync(path.join(here,family+'-diagnostic.json'),JSON.stringify(diag,null,2));assert(background.hidden||!background.focused,'Real background transition required');assert.equal(hiddenAfter.attempt.timing.activeMs,hiddenBefore.attempt.timing.activeMs);await cdp.send('Page.setWebLifecycleState',{state:'frozen'});await new Promise(resolve=>setTimeout(resolve,8000));await cdp.send('Page.setWebLifecycleState',{state:'active'});await p.waitForTimeout(1500);await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);const afterFreeze=await snap(p);
   const frozenGap=afterFreeze.attempt.timing.activeMs-hiddenAfter.attempt.timing.activeMs;const thaw=await p.evaluate(()=>({ticks:window.__f09ticks,hidden:document.hidden,focused:document.hasFocus()}));Object.assign(diag,{afterFreeze:afterFreeze.attempt.timing,frozenGap,thaw,cdpActuallyFrozen:thaw.ticks-background.ticks<=16});fs.writeFileSync(path.join(here,family+'-diagnostic.json'),JSON.stringify(diag,null,2));assert(frozenGap>=0&&frozenGap<5000);assert.equal(afterFreeze.attempt.attemptId,begin.attempt.attemptId);
   await p.bringToFront();await other.close();await cdp.send('Emulation.setFocusEmulationEnabled',{enabled:true});await fill(p,getVariant(id),answerFor(getVariant(id)),'react');await submit(p,'react');const assessed=await snap(p),history=await p.evaluate(()=>window.__mastersActivity.history());assert.equal(history.length,1);assert.deepEqual(history[0].timing,assessed.attempt.firstResponse.timing);
   await p.locator('.question-back').click();await p.locator('.original-landing').waitFor();await p.getByRole('button',{name:'Stats',exact:true}).click();await p.locator('.statistics').waitFor();
   const record=p.locator('[data-evidence-id="'+assessed.attempt.attemptId+'"]');await record.locator(':scope > summary').click();assert(await record.getByText('Recorded active time',{exact:true}).isVisible());assert(await p.locator('.statistics-chart').isVisible());await shot(p,'timing-'+family+'-statistics','.statistics');
   report.checks.push({family,id,idleAllowanceMs:limit,idleActiveMs:idle.attempt.timing.activeMs,idleStoppedExactly:true,frozenWallMs:8000,countedFreezeGapMs:frozenGap,sameAttempt:true,singleScore:true,statisticsTiming:history[0].timing,statisticsChart:true,visible});console.log('PASS '+family);
  }catch(error){report.errors.push(family+': '+(error.stack??error));console.error(error);}finally{await ctx.close();}
 }));report.status=report.errors.length?'FAIL':'PASS';
}catch(error){report.status='FAIL';report.errors.push(error.stack??String(error));console.error(error);}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'timing-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,errors:report.errors}));if(report.status!=='PASS')process.exitCode=1;}
