import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const project=path.resolve(import.meta.dirname,'../../../..'),base='validation/component-fidelity/f3/',own=base+'foreman/',read=n=>JSON.parse(fs.readFileSync(path.join(project,n),'utf8')),hash=n=>crypto.createHash('sha256').update(fs.readFileSync(path.join(project,n))).digest('hex');
const author=read(own+'author-validation.json'),independent=read(own+'independent-validation.json'),r=read(base+'independent/report.json'),audit=read(own+'audit-after.json'),release=read(own+'release-check-final.json'),scope=read(own+'source-scope.json'),build=read(own+'build-validation.json');for(const x of[author,independent,r,audit,release,scope,build,read(own+'final-c3-k.json')])assert.equal(x.status,'PASS');assert.deepEqual(r.unresolved,[]);
for(const row of r.sourceFreeze.files)assert.equal(hash(row.file),row.sha256);
const report={schemaVersion:1,runId:'COMPONENT-FIDELITY-20261003',stage:'F3',status:'VALIDATED_AWAITING_ROOT_FINAL_ACCEPTANCE',foreman:'F07',checkedAt:new Date().toISOString(),unresolved:[],rootGate:'Root final source/render acceptance remains. F2 implementation acceptance is recorded; independent F3 verification and all authorized bounded fixes complete. No publication.',jobs:[{jobId:'F3-SHARED-FINAL-FIX',agentId:'F08',status:'FOREMAN_VALIDATED',manifest:base+'shared-final/completion.json',validation:own+'author-validation.json'},{jobId:'F3-INDEPENDENT',agentId:'F12',status:'INDEPENDENT_PASS_FOREMAN_VALIDATED',manifest:base+'independent/completion.json',report:base+'independent/report.json',handover:base+'independent/HANDOVER.md',validation:own+'independent-validation.json'}],changes:[
'EE action buttons retain natural content widths/source sizing and wrap with one-line labels at mobile widths; embedded EE profile actions independently verified.',
'Completed self-rubrics derive completion from immutable first assessment, remove Finish marking and further evidence selection, retain disabled judgements/saved evidence and show completed text.',
'Numeric and completed rubric views keep compact labelled immutable first score, collapse duplicate original marking into keyboard-accessible native details, retain visible models/per-field feedback and distinct correction score. Eligible learning-alternative feedback remains expanded.'
],currentSourceFiles:r.sourceFreeze.files,patch:base+'shared-final/f3-only.patch',sourceClosure:{report:own+'source-scope.json',independent:base+'independent/source-closure.json',inputs:308,unchanged:305,authorizedChanges:3,removed:0,statement:'No engine, provider, chemistry, identity, clock, persistence, original source or foreign OLY changes since accepted F2.'},validation:{author:{cases:22,rawPngs:148,contacts:21,artifactHashes:author.images.length},independent:r.validation,independentEvidenceHashGate:own+'independent-validation.json',foremanTypeBuild:own+'build-validation.json',buildLogs:[own+'typecheck-final.log',own+'build-final.log'],exactBuildSourceFreeze:own+'build-source-inputs.json',release:own+'release-check-final.json',originals:own+'audit-after.json',independentFinalOriginals:base+'independent/audit-final.json',currentC3Browser:own+'final-c3-k.json',priorApplicableC3Tests:'validation/component-fidelity/f2/resume/c3-regression-final.log',priorApplicable68Tests:'validation/component-fidelity/f2/resume/foreman-report.json',priorF2CorpusMatrices:'validation/component-fidelity/f2/resume/foreman-report.json'},releaseBudgets:release.courses,preservation:{originals:audit.originals,priorF1:audit.priorF1Evidence,historical:audit.historicalEvidence,existingEditors:'90 exact unchanged dot-cross/molecule/C3 source files;8 specialist editor/SVG inputs unchanged independently.'},scope:'All11 existing curriculum and preserved C3/dot-cross/molecule experience. Concurrent OLY2011 content excluded from review; its current registration/assets remain build dependencies only. Registry13 is correct for combined current source.',staffing:{foremen:1,authors:1,independentReviewers:1,requestedModel:'gpt-6.1-sol',requestedEffort:'high',effectiveModel:null,usage:null,nestedDelegation:false},retainedDispositions:r.dispositions,limits:r.limits,livePreview:{url:'http://127.0.0.1:5192/alevel/',igcse:'http://127.0.0.1:5192/igcse/',vite:5188,originalReadOnly:5197,execSessions:[50930,79911,54640],old5182:'Not restarted or touched'},rootFullSizeSamples:['mobile-EE-incorrect.png','mobile-EE-model.png','mobile-numeric-correction.png','current-desktop-SBC-UFFEIZ-natural-completed.png','current-mobile-SBC-U5FSU0-natural-completed.png','current-mobile-energy-correct.png','current-desktop-titration-model.png','current-tablet-electron-model.png','production-pause-resume-stats.png'].map(n=>base+'independent/'+n)};
for(const n of report.rootFullSizeSamples)assert(fs.existsSync(path.join(project,n)),n);fs.writeFileSync(path.join(project,own+'foreman-report.json'),JSON.stringify(report,null,2)+'\n');
const p=read('component-fidelity-progress.json');p.currentStage='F3';p.status='awaiting_root_final_acceptance';p.stages.F3='validated_awaiting_root_final_acceptance';p.updatedAt=report.checkedAt;p.unresolved=[];for(const job of report.jobs){const row=p.jobs.find(j=>j.jobId===job.jobId);Object.assign(row,{status:'foreman_validated',manifest:job.manifest,validation:job.validation});}p.evidence=[...new Set([...p.evidence,own+'foreman-report.json'])];fs.writeFileSync(path.join(project,'component-fidelity-progress.json'),JSON.stringify(p,null,2)+'\n');console.log(JSON.stringify({status:report.status,report:own+'foreman-report.json',jobs:2,unresolved:0,currentSources:3,preview:report.livePreview.url}));
