import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {acidProvider} from '../../../src/activities/alevel/acid-base-calculations/provider.ts';
const project=path.resolve(import.meta.dirname,'../../..'),require=createRequire(path.resolve(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');
const {chromium}=require('playwright'),here=import.meta.dirname;
const temporary=path.join(here,'.production-browser');fs.mkdirSync(temporary,{recursive:true});process.env.TEMP=temporary;process.env.TMP=temporary;
const browser=await chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${temporary}/cache`]}),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();
const report={status:'RUNNING',startedAt:new Date().toISOString(),checks:[],pageErrors:[],builds:Object.fromEntries(['alevel','igcse'].map(course=>[course,crypto.createHash('sha256').update(fs.readFileSync(path.join(project,`release/${course}.runtime.json`))).digest('hex')]))};page.on('pageerror',error=>report.pageErrors.push(error.message));
async function rows(table){return page.evaluate(async table=>{const db=await new Promise((resolve,reject)=>{const request=indexedDB.open('masters-of-chemistry-alevel-local');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});try{return await new Promise((resolve,reject)=>{const request=db.transaction(table).objectStore(table).getAll();request.onsuccess=()=>resolve(request.result.map(row=>row.value));request.onerror=()=>reject(request.error);});}finally{db.close();}},table);}
async function leave(view){const change=page.getByRole('button',{name:'Change activity or view',exact:true});if(await change.isVisible())await change.click();await page.getByRole('button',{name:view,exact:true}).click();}
try{
 await page.goto('http://127.0.0.1:5197/stage-s4/alevel/index.html');await page.getByRole('button',{name:'Start practice',exact:true}).waitFor();await page.getByLabel('Target',{exact:true}).selectOption('u6-t1-1-2:1');await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.locator('.question-player').waitFor();
 assert.equal(await page.getByLabel('Practice setup').count(),0);assert.equal(await page.locator('.course-navigation').isVisible(),false);assert.equal(await page.evaluate(()=>window.__mastersActivity),undefined);
 const current=(await rows('attempts'))[0],question=acidProvider.restore(current.ref);assert(question.parts.every(part=>part.kind==='numeric'));
 for(let i=0;i<question.parts.length;i++)await page.locator('.question-part').nth(i).locator('input').fill(String(question.parts[i].acceptance.expected+100));await page.waitForTimeout(1100);await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.locator('.assessment-feedback').waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();
 const first=(await rows('evidence'));assert.equal(first.length,1);assert.equal(first[0].score,0);assert(first[0].timing.activeMs>=1000);const firstAttempt=(await rows('attempts')).find(row=>row.attemptId===first[0].id);
 for(let i=0;i<question.parts.length;i++)await page.locator('.question-part').nth(i).locator('input').fill(String(question.parts[i].acceptance.expected));for(let repeat=0;repeat<3;repeat++){await page.getByRole('button',{name:'Check correction',exact:true}).click();await page.locator('.correction-feedback').waitFor();assert(await page.getByText('Correction is correct',{exact:true}).isVisible());await page.getByText('Saved on this device',{exact:true}).waitFor();assert.deepEqual(await rows('evidence'),first);}
 const corrected=(await rows('attempts')).find(row=>row.attemptId===first[0].id);assert.deepEqual(corrected.firstResponse,firstAttempt.firstResponse);assert.deepEqual(corrected.firstAssessment,firstAttempt.firstAssessment);
 await leave('Statistics');await page.getByTestId('statistics-time').waitFor();assert.equal(Number(await page.getByTestId('statistics-time').getAttribute('data-active-ms')),first[0].timing.activeMs);assert.equal(await page.getByTestId('statistics-total').innerText(),'1');const chart=page.locator('.statistics-day button');assert.equal((await chart.evaluateAll(elements=>elements.reduce((sum,element)=>sum+Number(element.dataset.activeMs),0))),first[0].timing.activeMs);await page.locator('.statistics-history-record').first().locator('summary').first().click();assert((await page.locator('.statistics-history-record').innerText()).includes(`(${first[0].timing.activeMs} ms)`));await page.screenshot({path:path.join(here,'production-mobile-statistics.png'),fullPage:true});
 report.checks.push({id:'actual-static-first-correction-statistics-transfer',status:'PASS',attemptId:first[0].id,score:0,activeMs:first[0].timing.activeMs,evidenceCount:1,corrections:3,chartSum:first[0].timing.activeMs});
 await leave('Practice');await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await page.getByRole('button',{name:'Next question',exact:true}).click();await page.locator('.question-player').waitFor();await page.getByRole('button',{name:'Pause and save',exact:true}).click();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();const paused=(await rows('sessions'))[0],saved=(await rows('attempts')).find(row=>row.attemptId===paused.currentAttemptId);assert.notEqual(saved.attemptId,first[0].id);assert(paused.paused);await page.reload();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();assert.deepEqual((await rows('attempts')).find(row=>row.attemptId===saved.attemptId),saved);assert.deepEqual(await rows('evidence'),first);await leave('Teacher');await page.locator('.teacher-answer').waitFor();assert.equal(await page.locator('.teacher-answer~.question-parts input,.teacher-answer~.question-parts textarea').count(),0);assert.deepEqual(await rows('evidence'),first);
 report.checks.push({id:'actual-static-pause-next-reload-teacher-isolation',status:'PASS',attemptId:saved.attemptId,activeMs:saved.timing.activeMs});
 for(const [code,name] of [['EC-CMICC5','orbital'],['EE-19M67S','energy']]){const course=name==='orbital'?'alevel':'igcse';await page.goto(`http://127.0.0.1:5197/stage-s4/${course}/index.html?view=teacher&review=${code}`);await page.locator('.teacher-answer').waitFor();if(name==='energy')assert(await page.locator('.teacher-answer .diagram-viewport').count()>0);assert.equal(await page.locator('.question-parts .diagram-editor').count(),0);await page.screenshot({path:path.join(here,`production-mobile-teacher-${name}.png`),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const highlighted=page.locator('.course-navigation button[aria-current=page]');assert.equal(await highlighted.count(),1);assert((await highlighted.innerText()).includes(name==='orbital'?'Electron configurations':'Energy and enthalpy'));if(name==='orbital'){await page.getByRole('button',{name:'Electrons and bonding',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[aria-label=\"Teacher activity\"]')?.value==='alevel/electrons-bonding');await page.waitForFunction(()=>document.querySelector('.question-meta code')?.textContent==='EB01');assert((await highlighted.innerText()).includes('Electrons and bonding'));assert.deepEqual(await rows('evidence'),first);await leave('Practice');await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();assert.deepEqual((await rows('attempts')).find(row=>row.attemptId===saved.attemptId),saved);report.checks.push({id:'teacher-sidebar-current-preview-and-selection',status:'PASS',pausedAttemptUnchanged:true});}}
 const fonts=await page.evaluate(()=>({body:getComputedStyle(document.body).fontFamily,brand:getComputedStyle(document.querySelector('.brand h1')).fontFamily}));assert(/Segoe UI|system-ui|sans-serif/.test(fonts.body));assert(/Comfortaa/.test(fonts.brand));report.checks.push({id:'production-whole-reference-mobile-fonts',status:'PASS',fonts});
 await page.goto('http://127.0.0.1:5197/stage-s4/alevel/index.html?view=olympiad');await page.getByRole('button',{name:'Start part (a)',exact:true}).waitFor();await page.evaluate(()=>{window.failOlympiadSave=true;const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='olympiad'&&window.failOlympiadSave)throw new DOMException('Synthetic new-platform save fault','QuotaExceededError');return original.apply(this,args);};});await page.getByRole('button',{name:'Start part (a)',exact:true}).click();await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();await page.getByRole('button',{name:'Practice',exact:true}).click();await page.waitForTimeout(100);assert.equal(new URL(page.url()).searchParams.get('view'),'olympiad');assert(await page.getByRole('button',{name:'Retry save',exact:true}).isVisible());await page.evaluate(()=>{window.failOlympiadSave=false;});await page.getByRole('button',{name:'Retry save',exact:true}).click();await page.getByText('Challenge drawings saved on this device',{exact:true}).waitFor();assert.equal((await rows('olympiad'))[0].stage,'a');await page.getByRole('button',{name:'Practice',exact:true}).click();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();assert.deepEqual(await rows('evidence'),first);report.checks.push({id:'actual-olympiad-save-failure-blocks-departure-retry',status:'PASS',curriculumEvidenceUnchanged:true});
 assert.deepEqual(report.pageErrors,[]);report.status='PASS';
}catch(error){report.status='FAIL';report.failure=error.stack;process.exitCode=1;await page.screenshot({path:path.join(here,'production-browser-failure.png'),fullPage:true}).catch(()=>{});}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'production-browser.json'),JSON.stringify(report,null,2)+'\n');await context.close();await browser.close();console.log(JSON.stringify(report));}
