import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
const out=import.meta.dirname,app=path.resolve(out,'../../../..'),require=createRequire(path.resolve(app,'../../package.json'));process.env.TEMP=process.env.TMP=path.join(app,'.u05tmp');
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1600,height:1200}});
const sets={
 'desktop-contact-sheet':['igcse-calorimetry-1440.png','alevel-acid-base-calculations-1440.png','alevel-electrons-bonding-1440.png','alevel-dot-and-cross-1440.png','alevel-electron-configurations-1440.png','alevel-ph-titration-curves-1440.png','igcse-energy-enthalpy-1440.png','igcse-energetics-practical-1440.png','igcse-structure-and-bonding-1440.png','map-complete-1440.png','c3-b-1440.png','isomers-1440.png'],
 'mobile-contact-sheet':['final-alevel-acid-base-calculations-350.png','final-alevel-electrons-bonding-350.png','final-igcse-calorimetry-350.png','final-igcse-bond-enthalpy-350.png','final-igcse-structure-and-bonding-350.png','final-igcse-energetics-practical-350.png','dotcross-live-label-magnify-390.png','ordinary-ec-current-correct-390.png','ordinary-energy-clear-reload-390.png','ordinary-titration-clear-390.png','c3-b-350.png','isomers-350.png'],
 'completion-and-evidence-contact-sheet':['map-unstarted-1440.png','map-partial-1440.png','map-complete-1440.png','ordinary-ec-current-correct-390.png','ordinary-ec-frozen-stats-390.png','ordinary-titration-teacher-390.png'],
};
try{for(const [name,files]of Object.entries(sets)){
const html='<!doctype html><meta charset="utf-8"><style>body{margin:0;padding:20px;background:#080a1d;color:#eef0ff;font:16px sans-serif}h1{font-size:24px;margin:0 0 16px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}figure{margin:0;border:1px solid #46516f;background:#11172d;padding:8px;min-width:0}figcaption{height:36px;font-size:13px;overflow-wrap:anywhere}img{width:100%;height:660px;object-fit:contain;object-position:top}</style><h1>U05 independent current render review · '+name+'</h1><div class="grid">'+files.map(file=>'<figure><figcaption>'+file+'</figcaption><img src="data:image/png;base64,'+fs.readFileSync(path.join(out,file)).toString('base64')+'"></figure>').join('')+'</div>';
fs.writeFileSync(path.join(out,name+'.html'),html);await page.setContent(html);await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});
}fs.writeFileSync(path.join(out,'representative-renders.json'),JSON.stringify({status:'EXPORTED',checkedAt:new Date().toISOString(),sets,scope:'Contact sheets are downscaled review aids. Listed full exported PNG files remain the authoritative readable views.'},null,2)+'\n');}finally{await browser.close()}
