import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const app=process.cwd(),out=path.join(app,'validation/ui-consistency/u2/independent'),require=createRequire(path.resolve(app,'../../package.json'));process.env.TEMP=process.env.TMP=path.join(app,'.u05tmp');
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true}),c=await b.newContext({viewport:{width:390,height:844}}),p=await c.newPage();const r={status:'RUNNING',checks:[],errors:[],startedAt:new Date().toISOString()};p.on('pageerror',e=>r.errors.push(e.message));
async function shot(name){await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(180);const s=await p.evaluate(()=>{const el=[...document.querySelectorAll('button,input,textarea,select,code,svg text,label,p,h1,h2,h3,.score,.response-feedback')].filter(e=>{const b=e.getBoundingClientRect();return b.width&&b.height&&getComputedStyle(e).visibility!=='hidden'});return{fonts:[...new Set(el.map(e=>getComputedStyle(e).fontFamily))],overflow:document.documentElement.scrollWidth>innerWidth,bodyBackground:getComputedStyle(document.body).backgroundImage,paneWidth:document.querySelector('.course-layout')?.getBoundingClientRect().width??null,paneMax:document.querySelector('.course-layout')?getComputedStyle(document.querySelector('.course-layout')).maxWidth:null,count:el.length}});assert(s.fonts.every(f=>f.startsWith('Comfortaa')),name);assert.equal(s.overflow,false,name);r.checks.push({name,...s});await p.screenshot({path:path.join(out,name+'.png'),fullPage:true});console.log('PASS '+name)}
const launch=async(id)=>{await p.goto('http://127.0.0.1:5188/alevel.html?course=alevel&activity='+id+'&fresh=1&run=u03-extra');if(!id.includes('olympiad')&&!id.includes('c3l6')){const reg=await p.evaluate(async id=>{const {productionRegistry}=await import('/src/foundation/registry.ts');const a=productionRegistry.get(id);return{gem:a.gems[0].id,level:a.gems[0].supportedLevels[0]}},id);await p.goto('http://127.0.0.1:5188/alevel.html?course=alevel&activity='+id+'&fresh=1&gem='+reg.gem+'&level='+reg.level+'&run=u03-extra');await p.locator('.question-player').waitFor()}else await p.locator('.olympiad-question-frame').waitFor();await p.waitForFunction(()=>getComputedStyle(document.body).backgroundImage.includes('radial-gradient'))};
try{
 await launch('alevel/dot-and-cross');await p.getByText('Keyboard and non-drag controls',{exact:true}).click();await p.getByLabel('Element',{exact:true}).selectOption('O');await p.getByRole('button',{name:'Add atom',exact:true}).click();assert(await p.locator('.dc-canvas text').count()>0);await shot('dotcross-live-label-fit-390');await p.getByRole('button',{name:'Magnify diagram',exact:true}).click();const pan=await p.locator('.canvas-wrap').evaluate(e=>{e.scrollLeft=80;return{width:e.clientWidth,scrollWidth:e.scrollWidth,left:e.scrollLeft}});assert(pan.scrollWidth>pan.width);assert(pan.left>0);r.checks.push({name:'dotcross-internal-pan',...pan});await shot('dotcross-live-label-magnify-390');
 await launch('alevel/electron-configurations');await p.evaluate(async()=>{const s=window.__mastersActivity.snapshot(),{variants}=await import('/src/chemistry/electron-configuration/identity.ts'),{productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const v=variants.find(v=>v.direction==='build'&&v.representation==='energy'&&v.minimumLevel===1),ref={...s.question.ref,questionId:v.questionId,seed:1},provider=await productionRegistry.get(ref.activityId).provider(),id=crypto.randomUUID(),attempt={...s.attempt,attemptId:id,ref,currentResponses:{},assistance:[],phase:'answering',timing:{...s.attempt.timing,attemptId:id,activeMs:0,finished:false}},session={...s.session,currentAttemptId:id,previousQuestionIds:[ref.questionId]},repo=createChemistryRepository(s.databaseName);const result=await repo.saveCurriculum({attempt,session,question:provider.restore(ref),namespace:attempt.namespace});if(!result.ok)throw Error(JSON.stringify(result));repo.close?.()});await p.reload();await p.locator('.question-player').waitFor();await p.waitForTimeout(500);await p.screenshot({path:path.join(out,'ec-extra-debug.png'),fullPage:true});await p.locator('.orbital[data-orbital]').first().click();assert.equal(await p.locator('.orbital[data-orbital]').first().innerText(),String.fromCharCode(8593));await shot('electron-spin-arrow-390');await p.getByRole('button',{name:'Periodic table',exact:true}).click();await shot('electron-periodic-table-390');await p.getByRole('button',{name:'Close periodic table',exact:true}).click();
 await launch('alevel/acid-base-calculations');await p.getByRole('button',{name:'Give Up',exact:true}).click();await p.locator('.worked-answer').waitFor();await shot('acid-model-feedback-390');
 await launch('alevel/ph-titration-curves');await shot('titration-fit-390');
 for(const width of [1440,390,350]){await p.setViewportSize({width,height:width===1440?1000:844});for(const id of ['alevel/c3l6-organic-reactions','alevel/olympiad-2011-q4']){await launch(id);await shot(id.split('/')[1]+'-'+width);assert.equal(r.checks.at(-1).paneMax,'1120px');}}
 assert.equal(r.errors.length,0);r.status='PASS';
}catch(e){r.status='FAIL';r.failure=e.stack;console.error(e);process.exitCode=1}finally{r.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'browser-extra-results.json'),JSON.stringify(r,null,2));await b.close();console.log(JSON.stringify({status:r.status,checks:r.checks.length,failure:r.failure}))}
