import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {acidProvider} from '../../../../src/activities/alevel/acid-base-calculations/provider.ts';import {acidEngine} from '../../../../src/activities/alevel/acid-base-calculations/engine.js';import {electronsBondingProvider} from '../../../../src/activities/alevel/electrons-bonding/provider.ts';import {data as bondingData} from '../../../../src/activities/alevel/electrons-bonding/data.js';import {productionRegistry} from '../../../../src/foundation/registry.ts';import {sourceBank,currentBAnswers} from '../../../../src/activities/olympiad/c3l6/source-bank.ts';
const root=path.resolve(import.meta.dirname,'../../../..'),out=import.meta.dirname,require=createRequire(path.resolve(root,'../../package.json')),{chromium}=require('playwright'),sha=s=>crypto.createHash('sha256').update(s).digest('hex'),dbName='masters-of-chemistry-alevel-local',baseUrl='http://127.0.0.1:5202/alevel/index.html';
const server=http.createServer((req,res)=>{try{const parts=decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname).split('/').filter(Boolean);if(!['alevel','igcse'].includes(parts[0]))throw Error('route');const base=path.resolve(root,'dist',parts[0]),file=path.resolve(base,...parts.slice(1));if(!file.startsWith(base+path.sep)||!fs.existsSync(file))throw Error('scope');res.writeHead(200,{'content-type':{'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf'}[path.extname(file)]??'application/octet-stream','cache-control':'no-store'});fs.createReadStream(file).pipe(res);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(5202,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true}),report={at:new Date().toISOString(),status:'RUNNING',browser:browser.version(),playwright:require('playwright/package.json').version,checks:[],errors:[],screenshots:[],method:'Actual frozen production build, UI and native IndexedDB in fresh synthetic browser contexts; no DEV harness API or source/build mutation.'};let context;
async function fresh(){await context?.close();context=await browser.newContext({viewport:{width:1360,height:1000}});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));return page;}
async function shot(page,name,selector){const file=path.join(out,name+'.png');if(selector)await page.locator(selector).screenshot({path:file});else await page.screenshot({path:file,fullPage:true});report.screenshots.push({file:path.basename(file),sha256:sha(fs.readFileSync(file))});}
async function records(page,store){return page.evaluate(async({dbName,store})=>new Promise((resolve,reject)=>{const r=indexedDB.open(dbName);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,q=db.transaction(store).objectStore(store).getAll();q.onerror=()=>reject(q.error);q.onsuccess=()=>{db.close();resolve(q.result)};};}),{dbName,store});}
async function put(page,rows){await page.evaluate(async({dbName,rows})=>new Promise((resolve,reject)=>{const r=indexedDB.open(dbName);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,tx=db.transaction(Object.keys(rows),'readwrite');for(const [store,values]of Object.entries(rows))for(const value of values)tx.objectStore(store).put(value);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error);};}),{dbName,rows});}
async function checkText(page,q){const body=await page.locator('body').innerText();for(const p of q.parts)for(const b of p.prompt)if(b.kind==='text')assert(body.includes(b.text),b.text);for(const b of q.context)if(b.kind==='text')assert(body.includes(b.text),b.text);}
async function teacher(page,ref,provider){await page.goto(baseUrl+'?'+new URLSearchParams({view:'teacher',activity:ref.activityId,review:ref.questionId,level:String(ref.level),seed:String(ref.seed)}));await page.locator('.teacher-answer').waitFor();await checkText(page,provider.restore(ref));assert.equal((await records(page,'evidence')).length,0);}
async function fixture(page,ref){await page.goto(baseUrl+'?view=practice&activity='+encodeURIComponent(ref.activityId));await page.getByRole('button',{name:'Start practice',exact:true}).waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Start practice'&&!b.disabled));const registration=productionRegistry.get(ref.activityId),q=(await registration.provider()).restore(ref),gem=registration.gems.find(g=>g.supportedLevels.includes(ref.level)),id='A22-chemical-'+ref.questionId,namespace={course:'alevel',profileId:'local'},target={course:'alevel',activityId:ref.activityId,gemId:gem.id,level:ref.level},attempt={mode:'student',namespace,attemptId:id,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:registration.idleAllowance(q),finished:false}},session={kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:id,previousQuestionIds:[]};await put(page,{attempts:[{...namespace,id,value:attempt}],sessions:[{...namespace,id:'current-session',value:session}]});await page.reload();await page.locator('.question-parts').waitFor();await checkText(page,q);return {q,id};}
async function graded(page,id){await page.locator('.score').first().waitFor();await page.locator('.save-status.save-saved').waitFor();let result;for(let i=0;i<10;i++){result=(await records(page,'attempts')).find(x=>x.id===id)?.value;if(result?.firstAssessment)return result;}throw Error('Assessment did not persist');}
try{let page=await fresh();await teacher(page,acidProvider.resolveLink('AB-0000SN'),acidProvider);await shot(page,'continuity-teacher-acid');report.checks.push({kind:'acid-current-dp2-sf3-instruction',id:'AB-0000SN',noEvidence:true});page=await fresh();await teacher(page,electronsBondingProvider.resolveLink('EB09'),electronsBondingProvider);await shot(page,'continuity-teacher-bonding');report.checks.push({kind:'qualified-bonding-solid-phase',id:'EB09',noEvidence:true});page=await fresh();const ref=acidProvider.resolveLink('AB2-3-1-1'),{id}=await fixture(page,ref),source=acidEngine.generateFromReview(ref.questionId),inputs=page.locator('.question-parts input');assert.equal(await inputs.count(),source.responses.length);for(let n=0;n<source.responses.length;n++){const r=source.responses[n];await inputs.nth(n).fill(r.format==='dp2'?r.expected.toFixed(2):r.expected.toPrecision(3));}await page.getByRole('button',{name:'Check answer',exact:true}).click();const a=await graded(page,id);assert.equal(a.firstAssessment.marks.earned,3);assert.equal(a.firstAssessment.marks.available,3);await shot(page,'continuity-pupil-acid');report.checks.push({kind:'actual-pupil-marking-persistence',id:ref.questionId,earned:3,available:3});assert.deepEqual(report.errors,[]);report.status='PASS';}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;if(context?.pages()[0])await shot(context.pages()[0],'final-production-browser-failure').catch(()=>{});console.error(e);}finally{await context?.close();await browser.close();await new Promise(r=>server.close(r));report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'final-production-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,errors:report.errors}));}




