import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'../../../..'),out=import.meta.dirname,sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8').replace(/^\uFEFF/,'')),prior=read('validation/s5/chemistry/next-save-fix/freeze-current.retained.json'),current=read('validation/s5/integration/freeze-current.json'),accepted=read('validation/s5/chemistry/next-save-fix/verification.json');assert.equal(prior.treeSha256,accepted.currentTreeSha256);assert.equal(current.treeSha256,'c1c56180ba0bedb54cfa88eb666b22cb951869371488ef332c7a23e0c00e6812');
for(const row of current.currentInputHashes){const bytes=fs.readFileSync(path.join(root,row.path));assert.equal(bytes.length,row.bytes,row.path);assert.equal(sha(bytes),row.sha256,row.path);}assert.equal(sha(JSON.stringify(current.currentInputHashes)),current.treeSha256);
const oldMap=new Map(prior.currentInputHashes.map(x=>[x.path,x])),nowMap=new Map(current.currentInputHashes.map(x=>[x.path,x])),changed=current.currentInputHashes.filter(x=>oldMap.get(x.path)?.sha256!==x.sha256).map(x=>({path:x.path,before:oldMap.get(x.path)??null,after:x})),removed=prior.currentInputHashes.filter(x=>!nowMap.has(x.path));const sourceChanged=changed.filter(x=>x.path.startsWith('src/'));assert.deepEqual(sourceChanged.map(x=>x.path),['src/foundation/ActivityHost.tsx']);assert(!removed.some(x=>x.path.startsWith('src/')));assert(changed.every(x=>x.path==='src/foundation/ActivityHost.tsx'||(x.path.startsWith('dist/')||/^release\/(alevel|igcse)\.runtime\.json$/.test(x.path))));assert(removed.every(x=>x.path.startsWith('dist/')));
const host='src/foundation/ActivityHost.tsx',candidates=['validation/s5/behaviour/session-only-save-fix/ActivityHost-before.tsx.txt'],before=candidates.find(p=>fs.existsSync(path.join(root,p))&&sha(fs.readFileSync(path.join(root,p)))===oldMap.get(host).sha256);assert(before,'Exact accepted prior ActivityHost bytes must be retained');fs.copyFileSync(path.join(root,before),path.join(out,'ActivityHost-before.retained.tsx'));const diff=spawnSync('git',['diff','--no-index','--',path.join(out,'ActivityHost-before.retained.tsx'),path.join(root,host)],{encoding:'utf8'});fs.writeFileSync(path.join(out,'ActivityHost.diff'),diff.stdout);assert.equal(diff.status,1);
const originals=read('validation/s5/chemistry/source-fingerprints.json').sources.map(row=>{const b=fs.readFileSync(path.resolve(root,'../..',row.path));assert.equal(sha(b),row.sha256,row.path);return {path:row.path,bytes:b.length,sha256:sha(b)};});assert.equal(originals.length,237);
fs.copyFileSync(path.join(root,'validation/s5/integration/freeze-current.json'),path.join(out,'freeze-current.retained.json'));fs.copyFileSync(path.join(root,'validation/s5/chemistry/next-save-fix/freeze-current.retained.json'),path.join(out,'freeze-prior.retained.json'));
fs.writeFileSync(path.join(out,'source-guard.json'),JSON.stringify({agentId:'A22',status:'PASS',at:new Date().toISOString(),priorAcceptedTreeSha256:prior.treeSha256,currentTreeSha256:current.treeSha256,currentExactInputs:current.currentInputHashes.length,allCurrentFreezeBytesExact:true,onlyChangedSource:sourceChanged,sourceUnchangedExceptHost:true,contentMarkingEditorC3SourceUnchanged:true,nonRuntimeInputsUnchanged:true,changed,removed,originalsUnchanged:237,originals,priorAcceptance:'validation/s5/chemistry/completion.json and final-build-guard.json; prior bounded followup verification.json and next-save-fix/completion.json',diffEvidence:'ActivityHost.diff'},null,2));
// Retain the accepted browser harness as a reusable read-only fixture implementation.
let browser=fs.readFileSync(path.join(root,'validation/s5/chemistry/final-production-browser.mjs'),'utf8').replaceAll("'../../../src/","'../../../../src/").replace("path.resolve(import.meta.dirname,'../../..')","path.resolve(import.meta.dirname,'../../../..')");const start=browser.indexOf('try{let page='),end=browser.indexOf('}catch(e){report.status=',start);assert(start>0&&end>start);const body=`try{let page=await fresh();await teacher(page,acidProvider.resolveLink('AB-0000SN'),acidProvider);await shot(page,'continuity-teacher-acid');report.checks.push({kind:'acid-current-dp2-sf3-instruction',id:'AB-0000SN',noEvidence:true});page=await fresh();await teacher(page,electronsBondingProvider.resolveLink('EB09'),electronsBondingProvider);await shot(page,'continuity-teacher-bonding');report.checks.push({kind:'qualified-bonding-solid-phase',id:'EB09',noEvidence:true});page=await fresh();const ref=acidProvider.resolveLink('AB2-3-1-1'),{id}=await fixture(page,ref),source=acidEngine.generateFromReview(ref.questionId),inputs=page.locator('.question-parts input');assert.equal(await inputs.count(),source.responses.length);for(let n=0;n<source.responses.length;n++){const r=source.responses[n];await inputs.nth(n).fill(r.format==='dp2'?r.expected.toFixed(2):r.expected.toPrecision(3));}await page.getByRole('button',{name:'Check answer',exact:true}).click();const a=await graded(page,id);assert.equal(a.firstAssessment.marks.earned,3);assert.equal(a.firstAssessment.marks.available,3);await shot(page,'continuity-pupil-acid');report.checks.push({kind:'actual-pupil-marking-persistence',id:ref.questionId,earned:3,available:3});assert.deepEqual(report.errors,[]);report.status='PASS';`;browser=browser.slice(0,start)+body+browser.slice(end);fs.writeFileSync(path.join(out,'continuity-browser.mjs'),browser);console.log(JSON.stringify({status:'PASS',currentFreeze:current.treeSha256,changedSource:sourceChanged.map(x=>x.path),originals:originals.length}));


