import '../check-output.mjs';
import path from 'node:path';
process.chdir(path.resolve(import.meta.dirname,'../../..'));
import fs from 'node:fs';
import crypto from 'node:crypto';
const bankPath='src/activities/alevel/explaining-properties/bank.ts';
const hash=crypto.createHash('sha256').update(fs.readFileSync(bankPath)).digest('hex');
const metadata=JSON.parse(fs.readFileSync('src/catalogue/authored-metadata.json','utf8'));
metadata.activities=metadata.activities.filter(activity=>activity.id!=='alevel/explaining-properties');
metadata.activities.push({id:'alevel/explaining-properties',course:'alevel',strand:'curriculum',title:'Explaining Properties',source:[{path:'apps/Masters-of-Chemistry/'+bankPath,sha256:hash,symbolOrSection:'32 approved specification-authored/adapted questions; see activity README and retained source review.'}],gems:[{id:'l6-t2-1-properties',topicId:'l6-t2-1',label:'Explaining Properties',supportedLevels:[1,2],mastery:{gemId:'l6-t2-1-properties',supportedLevels:[{level:1,halfLife:3,label:'Level 1'},{level:2,halfLife:3,label:'Level 2'}],threshold:.8,comparison:'strictly-greater',historicalAliases:[],legacySourceKeys:[],activeProgressionVersion:1}}]});
fs.writeFileSync('src/catalogue/authored-metadata.json',JSON.stringify(metadata,null,2)+'\n');
const catalogue=JSON.parse(fs.readFileSync('src/landing/catalogue-data.json','utf8'));
catalogue.alevel.display.identities={...catalogue.alevel.display.identities,'l6-t2-1-4':'l6-t2-1-properties'};
catalogue.alevel.activities['l6-t2-1-properties']={label:'Explaining Properties',note:'Complete and correct explanations of ionic lattices, properties and covalent bond strength. Levels 1 and 2.',mastery:true,availableGrades:[1,2]};
fs.writeFileSync('src/landing/catalogue-data.json',JSON.stringify(catalogue,null,2)+'\n');
