import fs from 'node:fs';
import assert from 'node:assert/strict';
const file = 'validation/s5/fixes/next-save-transition/author-report.json';
const report = JSON.parse(fs.readFileSync(file, 'utf8'));
const evidence = ['validation/s5/review-render-harness/energy-next-fix/completion.json', 'validation/s5/behaviour/next-save-fix/completion.json', 'validation/s5/chemistry/next-save-fix/completion.json', 'validation/s5/render-release/completion.json'];
for (const path of evidence) assert.equal(JSON.parse(fs.readFileSync(path, 'utf8').replace(/^\uFEFF/, '')).status, 'PASS');
report.status = 'PASS';
report.checkedAt = new Date().toISOString();
report.independentEvidence = evidence;
delete report.independentPending;
report.currentTreeSha256 = JSON.parse(fs.readFileSync('validation/s5/integration/freeze-current.json', 'utf8')).treeSha256;
fs.writeFileSync(file, JSON.stringify(report, null, 2) + '\n');
