import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
import{bank,reviewCode}from'../../../../../src/activities/igcse/energy-enthalpy/provider.ts';import{initialProfile,modelProfile}from'../../../../../src/chemistry/energy-profile/index.ts';
const temporary=path.resolve('apps/Masters-of-Chemistry/.f10-tmp');fs.mkdirSync(temporary,{recursive:true});process.env.TEMP=temporary;process.env.TMP=temporary;
const here=import.meta.dirname,require=createRequire(path.resolve(here,'../../../../../../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');const{chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true});
const report={jobId:'F2-ENERGY',agentId:'F10',startedAt:new Date().toISOString(),status:'RUNNING',browser:'Edge headless / pinned root Playwright 1.62.1',isolation:'Fresh ephemeral browser contexts; original source served readonly. Synthetic source snapshots only in isolated context localStorage.',checks:[],screenshots:[],metrics:[],errors:[],limitations:['No new native OS hide/suspend certification.','The original has no correction/reveal-model flow; its correction/model paired diagrams are original saved-state rendering of the equivalent corrected/checked model, while React uses the shared live correction/reveal engine.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shoot(p,name,selector){await p.evaluate(()=>document.fonts.ready);const file=name+'.png';await p.locator(selector).screenshot({path:path.join(here,file)});report.screenshots.push(file);}
async function startReact(context,q,mode='practice'){
 const pool=bank.questions.filter(x=>x.grade===q.grade),seed=pool.findIndex(x=>x.id===q.id)||pool.length;
 await context.addInitScript(seed=>{crypto.getRandomValues=array=>{array.fill(seed);return array;};},seed);
 const p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:5188/igcse.html?course=igcse&run=f10-'+mode+'-'+Date.now()+'-'+Math.random());await p.locator('.original-landing').waitFor();
 await p.evaluate(()=>location.hash='lower-10-1');await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${q.grade}"]`).click();await p.locator('.question-player').waitFor();if(q.editor)await p.locator('.energy-profile-editor').waitFor();await flush(p);assert.equal((await snap(p)).question.ref.questionId,reviewCode(q.id));return p;
}
async function sourceState(context,q,m,state){
 const p=await context.newPage();await p.addInitScript(({q,m,state})=>{localStorage.setItem('sjs-energy-enthalpy-v2-attempt-grade'+q.grade,JSON.stringify({version:1,questionId:q.id,grade:q.grade,answers:[],editor:m,hinted:false,revealed:['incorrect','correct','correction','model'].includes(state),marked:null,attemptId:'synthetic-f10-'+q.id}));},{q,m,state});
 p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5197/igcse/activities/energy-enthalpy/index.html?practice=grade&grade=${q.grade}`);await p.locator(q.editor?'#builder .energy-svg':'#diagram .energy-svg').waitFor();
 if(['incorrect','correct','correction','model'].includes(state))await p.evaluate(({q,m})=>{const marked=EnergyCore.check(q,m,EnergyData);const key='sjs-energy-enthalpy-v2-attempt-grade'+q.grade,save=JSON.parse(localStorage.getItem(key));localStorage.setItem(key,JSON.stringify({...save,revealed:true,marked,completedAt:Date.now()}));},{q,m});
 if(['incorrect','correct','correction','model'].includes(state)){await p.reload();await p.locator('#builder .energy-svg').waitFor();}
 return p;
}
async function setProfile(p,m){await p.evaluate(m=>window.__mastersActivity.respond('profile',m),m);await flush(p);}
async function metric(p,selector){return p.locator(selector).evaluate(el=>{const text=el.querySelector('text'),c=getComputedStyle(text),card=getComputedStyle(el);return{width:el.getBoundingClientRect().width,fontFamily:c.fontFamily,fontWeight:c.fontWeight,fontSize:c.fontSize,fill:c.fill,bg:card.backgroundColor,overflow:document.documentElement.scrollWidth>innerWidth};});}
async function gesture(p,action,dx,dy,touch=false){const loc=p.locator('.energy-profile-editor [data-act="'+action+'"]');const box=await loc.boundingBox();assert(box,action);const x=box.x+box.width/2,y=box.y+box.height/2;await loc.scrollIntoViewIfNeeded();const rect=await loc.boundingBox(),px=rect.x+rect.width/2,py=rect.y+rect.height/2;
 if(touch){const cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:px,y:py}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:px+dx,y:py+dy}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await p.mouse.move(px,py);await p.mouse.down();await p.mouse.move(px+dx,py+dy,{steps:5});await p.mouse.up();}await flush(p);}
try{const q=bank.questions.find(q=>q.id==='D03'),context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage();await p.clock.install({time:new Date()});await context.addInitScript(()=>{crypto.getRandomValues=a=>{a.fill(2);return a;};});await p.goto('http://127.0.0.1:5188/igcse.html?course=igcse&run=f10-timing-'+Date.now());await p.locator('.original-landing').waitFor();await p.evaluate(()=>location.hash='lower-10-1');await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator('a.practice-choice[data-practice="2"]').click();await p.locator('.energy-profile-editor').waitFor();await p.locator('[data-act="level:peak"]').focus();await p.keyboard.press('ArrowUp');await flush(p);await new Promise(resolve=>setTimeout(resolve,500));await p.clock.runFor(1000);await new Promise(resolve=>setTimeout(resolve,500));await p.clock.runFor(180100);await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);const deadline=(await snap(p)).attempt;assert.equal(deadline.timing.idleLimitMs,180000);assert(deadline.timing.activeMs>=179000);await p.clock.runFor(30000);await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);assert.equal((await snap(p)).attempt.timing.activeMs,deadline.timing.activeMs);await p.locator('[data-act="level:peak"]').focus();await p.keyboard.press('ArrowDown');await p.clock.runFor(1000);await p.evaluate(()=>window.__mastersActivity.checkpoint());await flush(p);assert((await snap(p)).attempt.timing.activeMs>deadline.timing.activeMs);assert.equal(await p.getByRole('button',{name:/Pause question|Resume question/}).count(),0);report.checks.push({kind:'browser-idle-deadline',idleAllowanceMs:180000,realTrustedKeyboardRestarts:true,idleStops:true,clock:'Playwright controlled browser Date/performance/timers; no native OS certification',invisibleTiming:true});await context.close();report.status='PASS';}catch(e){report.status='FAIL';report.errors.push(e.stack);console.error(e);}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'timing-settled-results.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;}
