import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const directory=import.meta.dirname,project=path.resolve(directory,'../../..'),workspace=path.resolve(project,'../..');
const hash=file=>{const bytes=fs.readFileSync(file);return {path:path.relative(workspace,file).replaceAll('\\','/'),bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};};
const sourceNames=['apps/Masters-of-A-Level-Chemistry/src/assets/alevel-stats-core.js','apps/Masters-of-A-Level-Chemistry/src/assets/alevel-stats.js','apps/Masters-of-A-Level-Chemistry/src/assets/alevel-mastery.js','apps/Masters-of-A-Level-Chemistry/src/assets/active-question-time.js','apps/Masters-of-IGCSE-Chemistry/src/assets/igcse-stats-core.js','apps/Masters-of-IGCSE-Chemistry/src/assets/igcse-stats-progress.js','apps/Masters-of-IGCSE-Chemistry/src/assets/igcse-stats.js','apps/Masters-of-IGCSE-Chemistry/src/assets/igcse-mastery-config.js','apps/Masters-of-IGCSE-Chemistry/src/landing/progress.js','apps/Masters-of-IGCSE-Chemistry/src/assets/active-question-time.js'];
const imports=['src/domain/mastery/course-mastery.ts','src/domain/attempt/attempt.ts','src/domain/timing/active-clock.ts','src/persistence/repository.ts','src/persistence/legacy.ts','src/foundation/ActivityHost.tsx','src/foundation/registry.ts','src/contracts/integration.ts','src/contracts/session.ts','src/catalogue/definitions.ts'];
const owned=[...fs.readdirSync(path.join(project,'src/statistics')).map(name=>path.join(project,'src/statistics',name)),...['model.test.mjs','browser.mjs','harness.html','harness.tsx','HANDOVER.md','verify.mjs','browser-results.json','reviewed-continuation.json','readiness-continuation.json','history-readiness-continuation.json','accessible-label-fix.json','caption-selector-fix.json','render-inspection.json','desktop-question-marks.png','desktop-untimed-and-archive.png','mobile-chart.png','mobile-day-detail.png','igcse-assisted-history.png'].map(name=>path.join(directory,name))];
const checks=[['model',['--test',path.join(directory,'model.test.mjs')]],['typecheck',[path.join(project,'node_modules/typescript/bin/tsc'),'--noEmit']],['originals',[path.join(project,'scripts/protect-originals.mjs'),'check']]].map(([name,args])=>{
  const result=spawnSync(process.execPath,args,{cwd:name==='model'?workspace:project,encoding:'utf8'});fs.writeFileSync(path.join(directory,`${name}.log`),String(result.stdout??'')+String(result.stderr??''));return {name,status:result.status===0?'PASS':'FAIL',exitCode:result.status,log:`validation/s4/statistics/${name}.log`};
});
const proof={agentId:'A18',jobId:'S4-STATISTICS',checkedAt:new Date().toISOString(),status:checks.every(row=>row.status==='PASS')?'PASS':'FAIL',ownership:['src/statistics/','validation/s4/statistics/'],sources:sourceNames.map(name=>hash(path.join(workspace,name))),sharedImports:imports.map(name=>hash(path.join(project,name))),owned:owned.map(hash),checks};
fs.writeFileSync(path.join(directory,'verification.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({status:proof.status,checks}));if(proof.status!=='PASS')process.exitCode=1;
