import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {currentInputs} from '../../../scripts/current-inputs.mjs';
const app=path.resolve(import.meta.dirname,'../../..'),here=import.meta.dirname,previous=path.join(app,'validation/ui-consistency/u1');
const json=file=>JSON.parse(fs.readFileSync(path.join(here,file),'utf8')),hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const build=json('build-and-release.json'),browser=json('browser-results.json'),originals=json('original-preservation.json');
for(const result of [build,browser,originals])assert.equal(result.status,'PASS');
const old=JSON.parse(fs.readFileSync(path.join(previous,'current-inputs.json'),'utf8'));
const inputs=currentInputs(),source=inputs.filter(row=>!row.path.startsWith('dist/')&&!row.path.startsWith('release/'));
assert.deepEqual(source,build.sourceInputsAfter);
const priorSource=old.inputs.filter(row=>!row.path.startsWith('dist/')&&!row.path.startsWith('release/')),map=new Map(priorSource.map(row=>[row.path,row]));
const changed=source.filter(row=>row.sha256!==map.get(row.path)?.sha256);
assert.deepEqual(changed.map(row=>row.path),['src/ui/shared-actions.css']);
assert.equal(source.length,priorSource.length);
const oldCss=fs.readFileSync(path.join(here,'shared-actions.before.css'),'utf8'),css=fs.readFileSync(path.join(app,'src/ui/shared-actions.css'),'utf8');
assert.equal(hash(Buffer.from(oldCss)),map.get('src/ui/shared-actions.css').sha256);
assert.equal(css,oldCss.replace('  flex: 0 1 auto;','  flex: 0 1 auto;\n  width: auto;'));
const diff=spawnSync('git',['diff','--no-index','--no-ext-diff','--',path.join(here,'shared-actions.before.css'),path.join(app,'src/ui/shared-actions.css')],{encoding:'utf8'});assert.equal(diff.status,1);fs.writeFileSync(path.join(here,'source-changes.patch'),diff.stdout);
const oldEvidence=JSON.parse(fs.readFileSync(path.join(previous,'evidence-fingerprints.json'),'utf8'));
for(const row of oldEvidence.files)assert.equal(hash(fs.readFileSync(path.join(app,row.path))),row.sha256,'Prior U1 evidence changed: '+row.path);
const closure={at:new Date().toISOString(),treeSha256:hash(JSON.stringify(inputs)),count:inputs.length,inputs};
fs.writeFileSync(path.join(here,'current-inputs.json'),JSON.stringify(closure,null,2)+'\n');
const report={jobId:'UI-FOOTER-FIX',owner:'U01',status:'VALIDATED_AWAITING_ROOT_GATE',at:new Date().toISOString(),execution:'Bounded local foreman integration fix; no additional agents/reviewer',problem:'Calorimetry inherited width100% on every button, filling the desktop footer despite right edge/one-row checks.',change:'Added width:auto to existing high-specificity shared footer selector; resets inherited family widths centrally.',sourceDiff:changed,before:'shared-actions.before.css',patch:'source-changes.patch',validation:{browser:browser.status,cases:browser.checks.length,families:11,widths:[1440,390,350],compact:'Each button under160px, occupied row under400px; desktop occupied span below60% of available pane. Four exact labels, one row, right aligned,44px heights, Comfortaa, no page overflow.',rootFailureReproduced:'browser-before.json / before-igcse-calorimetry-1440.png',currentCalorimetry:browser.checks.filter(row=>row.name.startsWith('igcse-calorimetry')),typeAndBuild:build.checks,releases:build.releases,originals,priorU1EvidenceHashesUnchanged:oldEvidence.files.length},closure:{count:closure.count,treeSha256:closure.treeSha256,file:'current-inputs.json'},priorAggregate:'validation/ui-consistency/u1/foreman-report.json',preservation:'All prior U1 evidence preserved unchanged; exactly one CSS source property changed. Chemistry, identities, actions, keyboard and Olympiad progression unchanged.',unresolved:[],nextGate:'Root U1 corrected-render/code acceptance; U2 still pending. No publication.'};
fs.writeFileSync(path.join(here,'report.json'),JSON.stringify(report,null,2)+'\n');
const progressFile=path.join(app,'ui-consistency-progress.json'),progress=JSON.parse(fs.readFileSync(progressFile,'utf8'));
progress.status='awaiting_root_U1_gate';progress.stages.U1='validated_footer_fix_awaiting_root_gate';progress.footerFix={jobId:report.jobId,status:report.status,evidence:'validation/ui-consistency/u1-footer-fix/report.json'};progress.currentInputTree=closure.treeSha256;progress.updatedAt=report.at;progress.nextAction=report.nextGate;fs.writeFileSync(progressFile,JSON.stringify(progress,null,2)+'\n');
console.log(JSON.stringify({status:report.status,cases:browser.checks.length,oldEvidenceUnchanged:oldEvidence.files.length,currentInputs:inputs.length,treeSha256:closure.treeSha256}));
