import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const owned=import.meta.dirname,project=path.resolve(owned,'../../../..'),rootRequire=createRequire(path.resolve(project,'../../package.json')),appRequire=createRequire(path.join(project,'package.json'));
assert.equal(rootRequire('playwright/package.json').version,'1.62.1');const {chromium}=rootRequire('playwright');const {createServer}=await import(pathToFileURL(appRequire.resolve('vite')).href);
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const inputPaths=['development/authoring/serve.mjs','development/authoring/families/dev-formatted-starter/browser.mjs','development/authoring/families/dev-formatted-starter/family.ts','development/authoring/families/dev-formatted-starter/mount.tsx','development/authoring/families/dev-formatted-starter/Catalogue.tsx','development/authoring/families/dev-formatted-starter/tsconfig.json','development/authoring/families/dev-formatted-starter/generation-manifest.json','src/foundation/ActivityHost.tsx','src/development/catalogue/index.tsx'];
const fingerprint=()=>Object.fromEntries(inputPaths.map(p=>[p,hash(fs.readFileSync(path.join(project,p)))]));
const report={agentId:'A06',jobId:'S4-REVIEW-FORMATTED-STARTUP',startedAt:new Date().toISOString(),before:fingerprint(),cases:[],errors:[],effectiveModelEffort:null,usage:null};
const retained=['browser-results.json','failure.png','configuration-validation.json'];for(const f of retained){const b=fs.readFileSync(path.join(project,'validation/s4/authoring-release/refinement/dev-formatted-starter',f));fs.writeFileSync(path.join(owned,'original-'+f),b);}
for(const f of ['browser.mjs','generation-manifest.json'])fs.writeFileSync(path.join(owned,'original-'+f+'.txt'),fs.readFileSync(path.join(project,'development/authoring/families/dev-formatted-starter',f)));
await import(pathToFileURL(path.join(project,'development/authoring/families/dev-formatted-starter/family.ts')).href);
const privateServer=await createServer({configFile:false,root:project,cacheDir:path.join(owned,'cold-cache'),server:{host:'127.0.0.1',port:5200,strictPort:true},publicDir:path.join(project,'public')});await privateServer.listen();
const originalTemp=path.join(project,'validation/s4/authoring-release/refinement/dev-formatted-starter/browser-temp');
try{for(const [id,port] of [['cold-private',5200],['current-host',5195]]){
 const suffix=id==='cold-private'?'c':'w',temp=path.join(owned,suffix.repeat(originalTemp.length-owned.length-1));assert.equal(temp.length,originalTemp.length);fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;process.env.TMPDIR=temp;
 const row={id,port,temp,tempLength:temp.length,nodeTempRoot:os.tmpdir(),events:[],console:[],errors:[],navigations:[],startedAt:new Date().toISOString()};assert.equal(row.nodeTempRoot,temp);report.cases.push(row);let browser;
 try{browser=await chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${path.join(temp,'cache')}`]});row.browser=browser.version();const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
 page.on('request',r=>row.events.push({kind:'request',url:r.url(),at:Date.now()}));page.on('response',r=>row.events.push({kind:'response',url:r.url(),status:r.status(),at:Date.now()}));page.on('requestfailed',r=>row.events.push({kind:'failure',url:r.url(),failure:r.failure(),at:Date.now()}));page.on('requestfinished',r=>row.events.push({kind:'finished',url:r.url(),at:Date.now()}));page.on('console',m=>row.console.push({kind:m.type(),text:m.text(),at:Date.now()}));page.on('pageerror',e=>row.errors.push(e.message));page.on('framenavigated',f=>{if(f===page.mainFrame())row.navigations.push({url:f.url(),at:Date.now()});});
 const cdp=await context.newCDPSession(page);await cdp.send('Page.setLifecycleEventsEnabled',{enabled:true});cdp.on('Page.lifecycleEvent',e=>row.events.push({kind:'lifecycle',...e,at:Date.now()}));
 const began=Date.now();try{await page.goto(`http://127.0.0.1:${port}/development/authoring/families/dev-formatted-starter/preview.html?run=a06-formatted-${id}-${began}`,{waitUntil:'domcontentloaded',timeout:30000});row.domReadyMs=Date.now()-began;await page.waitForFunction(()=>!!window.__mastersActivity,null,{timeout:15000});row.hostReady=true;row.hostReadyMs=Date.now()-began;}catch(e){row.failure=String(e.stack??e);}
 try{const snapshot=await cdp.send('Runtime.evaluate',{expression:"JSON.stringify({href:location.href,readyState:document.readyState,timeOrigin:performance.timeOrigin,hostReady:!!window.__mastersActivity,historyLength:window.__mastersActivity?.snapshot().history.length,attempt:window.__mastersActivity?.snapshot().attempt??null})",returnByValue:true,timeout:3000});row.rendererSnapshot=snapshot.result;}catch(e){row.rendererFailure=String(e);}
 if(row.hostReady)await page.screenshot({path:path.join(owned,id+'.png'),fullPage:true});
 }catch(e){row.setupFailure=String(e.stack??e);}finally{fs.writeFileSync(path.join(owned,'diagnostic.json'),JSON.stringify(report,null,2));if(browser)await browser.close();row.finishedAt=new Date().toISOString();}
}}
finally{await privateServer.close();report.after=fingerprint();report.changed=inputPaths.filter(p=>report.before[p]!==report.after[p]);report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(owned,'diagnostic.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({cases:report.cases.map(r=>({id:r.id,nodeTempRoot:r.nodeTempRoot,hostReady:r.hostReady,domReadyMs:r.domReadyMs,hostReadyMs:r.hostReadyMs,failure:r.failure,setupFailure:r.setupFailure,console:r.console,errors:r.errors,navigations:r.navigations.length,rendererSnapshot:r.rendererSnapshot,rendererFailure:r.rendererFailure})),changed:report.changed}));}
