import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(path.resolve('../../package.json')),out='validation/isomer-copy';process.env.TEMP=path.resolve('btmp-popup');process.env.TMP=process.env.TEMP;
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const report={status:'RUNNING',layouts:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:5188/alevel.html?course=alevel&activity=alevel/olympiad-2011-q4&run=copy-'+Date.now());await page.locator('[data-isomer-box="7"]').waitFor();
 assert.equal(await page.locator('.isomer-question-heading').innerText(),'There are 7 structural isomers with the formula C4H10O. Use the evidence to identify compounds 1\u20137.');assert.equal(await page.locator('.isomer-clues h3').innerText(),'CLUES');assert.equal(await page.getByText('All seven boxes are available immediately.',{exact:false}).count(),0);
 const button=page.locator('.isomer-check');assert(await button.isDisabled());
 await page.evaluate(async()=>{const {isomerChallenge}=await import('/src/activities/olympiad/isomers2011/content.ts');for(const [box,index] of [['1',1],['2',0]])await window.__mastersOlympiad.command({kind:'draw',box,drawing:{kind:'molecule',graph:isomerChallenge.answers[index].graph,history:[]}});});await button.click();await page.locator('.isomer-assessment p').filter({hasText:'0 fully correct; 2 correct but in the wrong place.'}).waitFor();
 for(const width of [1440,768,390,350]){await page.setViewportSize({width,height:1000});await page.mouse.move(0,0);await page.evaluate(()=>document.fonts.ready);const r=await page.evaluate(()=>{const row=document.querySelector('.isomer-assessment').getBoundingClientRect(),b=document.querySelector('.isomer-check'),r=b.getBoundingClientRect(),s=document.querySelector('.isomer-assessment p').getBoundingClientRect();return{width:innerWidth,page:document.documentElement.scrollWidth,right:r.right,rowRight:row.right,verdictRight:s.right,buttonLeft:r.left,background:getComputedStyle(b).backgroundColor};});assert(r.page<=width);assert(Math.abs(r.right-r.rowRight)<1);assert(r.verdictRight<r.buttonLeft);assert.equal(r.background,'rgb(85, 246, 255)');report.layouts.push(r);await page.screenshot({path:out+'/verdict-'+width+'.png',fullPage:true});}
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;}finally{fs.writeFileSync(out+'/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();}
