import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';import {server,project} from '../behaviour/server.mjs';
const require=createRequire(path.resolve(project,'../../package.json')),owned=import.meta.dirname,temp=path.join(owned,'t');if(require('playwright/package.json').version!=='1.62.1')throw Error('Wrong pinned Playwright');
fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;process.env.TMPDIR=temp;
const {chromium}=require('playwright'),host=server();await new Promise(r=>host.listen(5206,'127.0.0.1',r));let browser;
const report={agentId:'A06',jobId:'S5-REVIEW-BEHAVIOUR-HARNESS',startedAt:new Date().toISOString(),port:5206,nodeTempRoot:os.tmpdir(),cases:[],errors:[],actions:'Import view and synthetic textarea fill only; no Preview or Import commands'};
try{browser=await chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${path.join(temp,'cache')}`]});report.browser=browser.version();const context=await browser.newContext(),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
for(const course of ['alevel','igcse']){await page.goto(`http://127.0.0.1:5206/stage-s5/${course}/index.html?view=import`,{waitUntil:'domcontentloaded'});const area=page.locator('.legacy-import textarea');await area.waitFor();
const snapshot=async()=>({exactLabelCount:await page.getByLabel('Source JSON',{exact:true}).count(),scopedCount:await area.count(),dom:await area.evaluate(e=>({value:e.value,labelText:e.closest('label').textContent,outerHTML:e.outerHTML})),aria:await page.locator('.legacy-import').ariaSnapshot()});
const before=await snapshot();await area.fill('[{"id":"a06-control-name-only","note":"synthetic UI text"}]');const after=await snapshot();
report.cases.push({course,before,after});await page.screenshot({path:path.join(owned,course+'-source-json-dom.png'),fullPage:true});}
}catch(e){report.failure=String(e.stack??e);}finally{if(browser)await browser.close();await new Promise(r=>host.close(r));report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(owned,'dom-probe.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({cases:report.cases.map(c=>({course:c.course,beforeExact:c.before.exactLabelCount,afterExact:c.after.exactLabelCount,scoped:c.after.scopedCount,labelText:c.after.dom.labelText})),errors:report.errors,failure:report.failure}));}
