import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const owned=import.meta.dirname,project=path.resolve(owned,'../../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const verification=JSON.parse(fs.readFileSync(path.join(owned,'verification.json'),'utf8'));
const pictures=['alevel-first-scores-corrections-pause-stats-ui-failure.png','igcse-first-scores-corrections-pause-stats-ui-failure.png','actual-source-repository-faults-version-isolation-failure.png','alevel-import-failure.png','igcse-import-failure.png'];
const screenshots=[];
for(const file of pictures){const src=path.join(project,'validation/s5/behaviour',file),dest=path.join(owned,'retained',file);if(!fs.existsSync(src))continue;if(!fs.existsSync(dest))fs.copyFileSync(src,dest);screenshots.push({path:'validation/s5/review-behaviour-harness/retained/'+file,sha256:sha(fs.readFileSync(dest))});}
fs.writeFileSync(path.join(owned,'retained-screenshots.json'),JSON.stringify(screenshots,null,2)+'\n');
const completion={agentId:'A06',jobId:'S5-REVIEW-BEHAVIOUR-HARNESS',status:'PASS',confidence:'high',reason:'Exact source-backed harness repairs approved for one deep and one import continuation; substantive behaviour remains pending worker execution.',outputPaths:['validation/s5/review-behaviour-harness/HANDOVER.md','validation/s5/review-behaviour-harness/verification.json','validation/s5/review-behaviour-harness/inputs.json','validation/s5/review-behaviour-harness/dom-probe.json','validation/s5/review-behaviour-harness/retained-screenshots.json','validation/s5/review-behaviour-harness/completion.json'],validation:{deterministicChecks:verification.checks.length,assertionsPreserved:true,realPartialMarks:verification.partial.map(p=>({course:p.course,earned:p.marks.earned,available:p.marks.available})),domProbe:'Both production course import views, no imports/assessments performed',fullSuiteReplayed:false,sourceChanges:false,proposals:verification.proposals},settings:{requestedModel:'gpt-6.1-sol',requestedEffort:'high',effectiveModel:null,effectiveEffort:null,actualUsage:null},finishedAt:new Date().toISOString()};
fs.writeFileSync(path.join(owned,'completion.json'),JSON.stringify(completion,null,2)+'\n');console.log(JSON.stringify(completion));
