import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {createRequire} from 'node:module';
const owned=import.meta.dirname,project=path.resolve(owned,'../../..'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),require=createRequire(path.join(project,'package.json')),ts=require('typescript');
const files=['validation/s5/behaviour/deep-browser.mjs','validation/s5/behaviour/deep-browser-results.json','validation/s5/behaviour/deep-browser-stdout.txt','validation/s5/behaviour/deep-first-failure.json','validation/s5/behaviour/deep-first-stdout.txt','validation/s5/behaviour/import-browser.mjs','validation/s5/behaviour/import-browser-results.json','validation/s5/behaviour/import-browser-stdout.txt','validation/s5/behaviour/import-first-harness-failure.json','validation/s5/behaviour/import-first-harness-stdout.txt','validation/s5/behaviour/proposed-deep-browser.mjs','validation/s5/behaviour/proposed-deep-browser-v2.mjs','validation/s5/behaviour/proposed-import-browser.mjs','validation/s5/behaviour/server.mjs','validation/s5/behaviour/multipart-source-proof.jsonl','src/contracts/question.ts','src/domain/attempt/attempt.ts','src/domain/attempt/input-checks.ts','src/foundation/ActivityHost.tsx','src/persistence/repository.ts','src/ui/QuestionPlayer.tsx','src/compatibility/LegacyImportView.tsx','src/activities/alevel/acid-base-calculations/provider.ts','src/activities/alevel/acid-base-calculations/marking.ts','src/activities/igcse/calorimetry/provider.ts','src/activities/igcse/calorimetry/marking.ts'];
const record={capturedAt:new Date().toISOString(),files:{}};
for(const file of files){const name=file.replaceAll('/','__')+'.txt',out=path.join(owned,'retained',name);fs.mkdirSync(path.dirname(out),{recursive:true});if(!fs.existsSync(out))fs.writeFileSync(out,fs.readFileSync(path.join(project,file)));record.files[file]={path:'validation/s5/review-behaviour-harness/retained/'+name,sha256:hash(fs.readFileSync(out))};}
const text=fs.readFileSync(path.join(project,'src/domain/attempt/attempt.ts'),'utf8'),options={target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX};
const first=ts.transpileModule(text,{compilerOptions:options,reportDiagnostics:true}),fixed=ts.transpileModule(text,{fileName:path.join(project,'src/domain/attempt/attempt.ts'),compilerOptions:options,reportDiagnostics:true});
record.actualSourceTranspile={typescript:ts.version,source:'src/domain/attempt/attempt.ts',sourceSha256:hash(text),withoutFileNameDiagnostics:first.diagnostics.map(d=>({code:d.code,message:ts.flattenDiagnosticMessageText(d.messageText,' ')})),withFileNameDiagnostics:fixed.diagnostics.map(d=>({code:d.code,message:ts.flattenDiagnosticMessageText(d.messageText,' ')}))};
fs.writeFileSync(path.join(owned,'without-filename-transform.js.txt'),first.outputText);fs.writeFileSync(path.join(owned,'with-filename-transform.js.txt'),fixed.outputText);fs.writeFileSync(path.join(owned,'inputs.json'),JSON.stringify(record,null,2));console.log(JSON.stringify({retained:Object.keys(record.files).length,withoutFileNameDiagnostics:first.diagnostics.length,withFileNameDiagnostics:fixed.diagnostics.length}));
