import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {variants,getVariant,matchingFromId} from '../../../src/chemistry/electron-configuration/identity.ts';
import {data as D} from '../../../src/chemistry/electron-configuration/data.js';
import {data as B} from '../../../src/activities/alevel/electrons-bonding/data.js';
import {referenceState} from '../../../src/chemistry/electron-configuration/engine.ts';
import {diagramImage,spinText} from '../../../src/chemistry/electron-configuration/display.ts';
import {same} from '../../../src/chemistry/electron-configuration/core.js';
const dir=import.meta.dirname,project=path.resolve(dir,'../../..'),require=createRequire(path.resolve(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');
const {chromium}=require('playwright');
const context=await chromium.launchPersistentContext(path.join(dir,'edge-profile'),{channel:'msedge',headless:true,viewport:{width:1365,height:900},args:['--no-first-run','--no-default-browser-check','--disable-gpu']});
const page=await context.newPage(),errors=[],results=[];page.on('pageerror',error=>errors.push(error.message));
const reportFile=path.join(dir,process.env.A11_BROWSER_CASE?'browser-focused-results.json':'browser-results.json');
const snapshot=()=>page.evaluate(()=>window.__mastersActivity.snapshot());
const flush=()=>page.evaluate(()=>window.__mastersActivity.flush());
const target=(activity,level)=>`${activity==='bonding'?'l6-t2-1-1':'l6-t2-1-2'}:${level}`;
async function navigate(url){try{await page.goto(url);}catch(error){if(!String(error).includes('ERR_ABORTED'))throw error;await page.goto(url);}}
async function open(activity='electron',level=1,extra=''){
 await navigate(`http://127.0.0.1:5181/alevel.html?run=a11-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}${extra}`);await page.waitForFunction(()=>window.__mastersActivity!==undefined);await page.getByLabel('Target',{exact:true}).selectOption(target(activity,level));await page.waitForFunction(()=>!document.querySelector('button.primary')?.disabled);
}
async function start(level=1,representation){await page.getByLabel('Target',{exact:true}).selectOption(target('electron',level));for(let tries=0;tries<30;tries++){const before=(await snapshot()).attempt?.attemptId;await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(previous=>window.__mastersActivity.snapshot().attempt!=null&&window.__mastersActivity.snapshot().attempt.attemptId!==previous,before);await flush();const value=await snapshot(),q=getVariant(value.question.ref.questionId);if(!representation||q.kind==='main'&&q.representation===representation){await page.waitForSelector('.ec-workspace');return q;}}throw Error('Could not select requested representation in 30 independent starts.');}
async function submit(){await page.getByRole('button',{name:'Check answer',exact:true}).click();await flush();await page.waitForFunction(()=>window.__mastersActivity.snapshot().attempt.phase==='assessed');await page.waitForFunction(()=>window.__mastersActivity.snapshot().history.length>0);}
async function referenceThroughUI(q){
 if(q.kind==='bonus'){for(const id of q.options){const item=D.species.find(item=>item.id===id);await page.getByLabel(`${item.name}, charge ${item.charge}`,{exact:true}).setChecked(same(item.counts,q.counts));}return;}
 const answer=referenceState(q.speciesId,q.representation);
 if(q.direction==='identify'){await page.getByLabel('Element name or symbol',{exact:true}).fill(answer.identity);return;}
 if(q.representation==='row'||q.representation==='energy'){const buttons=page.locator('.ec-box');let n=0;const order=q.representation==='energy'?[0,1,2,3,4,6,5,7]:[0,1,2,3,4,5,6,7];for(const index of order)for(const spin of answer.boxes[index]){await buttons.nth(n++).focus();await page.keyboard.press(spin===3?'2':spin===2?'d':String(spin));await flush();}return;}
 if(q.representation==='short')await page.locator('.ec-workspace select').first().selectOption(answer.core);
 for(let i=0;i<8;i++){const input=page.getByLabel(`Electrons in ${D.subshells[i]}`,{exact:true});if(await input.count()){await input.fill(answer.counts[i]);await flush();}}
}
async function next(){const before=await snapshot();await page.getByRole('button',{name:'Next question',exact:true}).click();await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt?.attemptId!==id,before.attempt.attemptId);await flush();return getVariant((await snapshot()).question.ref.questionId);}
async function run(id,operation){if(process.env.A11_BROWSER_CASE&&id!==process.env.A11_BROWSER_CASE)return;const began=Date.now();try{const evidence=await operation();results.push({id,status:'PASS',elapsedMs:Date.now()-began,evidence});}catch(error){results.push({id,status:'FAIL',elapsedMs:Date.now()-began,error:String(error.stack||error)});await page.screenshot({path:path.join(dir,`${id}-failure.png`),fullPage:true});}fs.writeFileSync(reportFile,JSON.stringify({results,errors},null,2));}
try{
 await run('orbital-keyboard-draft-reload-wrong-correction-immutable',async()=>{
  await open();const q=await start(1,'row');assert.equal(await page.locator('.ec-box').count(),18);
  await page.getByRole('button',{name:'Check answer',exact:true}).click();await flush();assert.equal((await snapshot()).attempt.phase,'answering');assert.equal((await snapshot()).history.length,0);
  const firstBox=page.locator('.ec-box').first();await firstBox.focus();await page.keyboard.press('2');await flush();assert.equal((await snapshot()).attempt.currentResponses.configuration.boxes[0][0],3);
  await page.keyboard.press('0');await flush();await page.waitForTimeout(1250);await page.evaluate(()=>window.__mastersActivity.checkpoint());const draft=await snapshot();assert.equal(draft.attempt.timing.idleLimitMs,180000);await page.screenshot({path:path.join(dir,'desktop-row-draft.png'),fullPage:true});
  await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!=null);await page.waitForSelector('.ec-workspace');await flush();const restored=await snapshot();assert.equal(restored.attempt.attemptId,draft.attempt.attemptId);assert.deepEqual(restored.attempt.currentResponses,draft.attempt.currentResponses);assert(restored.attempt.timing.activeMs>=draft.attempt.timing.activeMs);
  await submit();const first=await snapshot();assert.equal(first.attempt.firstAssessment.score,0);assert(first.attempt.firstResponse.timing.activeMs>0);const evidence=await page.evaluate(()=>window.__mastersActivity.history());assert.equal(evidence.length,1);
  await referenceThroughUI(q);await page.getByRole('button',{name:'Check correction',exact:true}).click();await flush();const corrected=await snapshot();assert.equal(corrected.correctionFeedback.status,'correct');assert.deepEqual(corrected.attempt.firstResponse,first.attempt.firstResponse);assert.deepEqual(corrected.attempt.firstAssessment,first.attempt.firstAssessment);assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),evidence);
  await page.getByRole('button',{name:'Show worked answer',exact:true}).click();await flush();await page.screenshot({path:path.join(dir,'desktop-corrected-worked.png'),fullPage:true});await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await flush();assert.deepEqual((await snapshot()).attempt.firstAssessment,first.attempt.firstAssessment);assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),evidence);const nextQ=await next();assert.equal((await snapshot()).attempt.phase,'answering');assert.equal((await snapshot()).history.length,1);
  return {firstRef:first.attempt.ref,nextVariant:nextQ,sourceIdleMs:180000,activeMs:first.attempt.firstResponse.timing.activeMs,draftExact:true,immutableFirstEvidence:true,oneRecord:true,keyboardSpins:true};
 });
 await run('full-short-energy-controls-all-four-representations',async()=>{
  const tested=[];for(const representation of ['full','short','energy']){await open('electron',representation==='short'?2:1);const q=await start(representation==='short'?2:1,representation);await referenceThroughUI(q);await flush();await page.screenshot({path:path.join(dir,`desktop-${representation}.png`),fullPage:true});await submit();assert.equal((await snapshot()).attempt.firstAssessment.score,1);tested.push({representation,ref:(await snapshot()).attempt.ref});}
  return {tested,allFourWithRow:true};
 });
 await run('level3-matching-dblock-exceptions-identify',async()=>{
  await open('electron',3);let q=await start(3);assert.equal(q.kind,'bonus');await referenceThroughUI(q);await flush();const draft=await snapshot();await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!=null);await flush();assert.deepEqual((await snapshot()).attempt.currentResponses,draft.attempt.currentResponses);await submit();assert.equal((await snapshot()).attempt.firstAssessment.score,1);await page.screenshot({path:path.join(dir,'desktop-matching.png'),fullPage:true});const groups=[];
  for(let n=0;n<10;n++){q=await next();await referenceThroughUI(q);await submit();groups.push(q.kind==='bonus'?'matching':`${q.group}:${q.direction}:${q.representation}`);if(q.kind==='main'&&q.direction==='identify'){assert.equal((await snapshot()).attempt.firstResponse.timing.idleLimitMs,60000);await page.screenshot({path:path.join(dir,'desktop-identify.png'),fullPage:true});}}
  assert(groups.some(group=>group.startsWith('d-atoms:')));assert(groups.some(group=>group.startsWith('d-ions:')));assert(groups.some(group=>group.includes(':identify:')));assert.equal((await snapshot()).history.length,11);return {initialMask:matchingFromId(draft.attempt.ref.questionId).mask,draftExact:true,groups,records:11};
 });
 await run('bonding-blank-wrong-partial-correct-and-reload',async()=>{
  await open('bonding');await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity.snapshot().attempt!=null);await flush();let current=await snapshot();const record=B.questions.find(item=>item.id===current.attempt.ref.questionId),input=page.locator('.question-part input,.question-part textarea').first();
  await page.getByRole('button',{name:'Check answer',exact:true}).click();await flush();assert.equal((await snapshot()).history.length,0);await input.fill('I do not know');await flush();await page.waitForTimeout(1100);await submit();const first=await snapshot(),evidence=await page.evaluate(()=>window.__mastersActivity.history());assert.equal(first.attempt.firstAssessment.score,0);assert.equal(first.attempt.firstResponse.timing.idleLimitMs,60000);await input.fill(record.fields[0].accept[0]);await page.getByRole('button',{name:'Check correction',exact:true}).click();await flush();assert.equal((await snapshot()).correctionFeedback.status,'correct');assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),evidence);await page.screenshot({path:path.join(dir,'desktop-bonding-correction.png'),fullPage:true});await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await flush();assert.deepEqual((await snapshot()).attempt.firstResponse,first.attempt.firstResponse);return {ref:first.attempt.ref,blankBlocked:true,wrongRecorded:true,correctionLearningOnly:true,sourceIdleMs:60000,records:1};
 });
 await run('revision-topic-add-all-pause-reload-restore-scheduler-next',async()=>{
  await open('electron',3,'&session=revision');await page.getByRole('button',{name:'ADD ALL l6-t2-1',exact:true}).click();await flush();assert.equal((await snapshot()).selectedCount,7);
  await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity.snapshot().attempt!=null);await flush();
  const before=await snapshot();const isBonding=before.question.ref.activityId==='alevel/electrons-bonding';const q=isBonding?null:getVariant(before.question.ref.questionId);
  if(isBonding)await page.locator('.question-part input,.question-part textarea').first().fill('I do not know');else await referenceThroughUI(q);await flush();
  await page.getByRole('button',{name:'Pause',exact:true}).click();await flush();const paused=await snapshot();assert.equal(paused.session.status,'paused');await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!=null);await flush();assert.deepEqual((await snapshot()).attempt.currentResponses,paused.attempt.currentResponses);assert.equal((await snapshot()).attempt.attemptId,paused.attempt.attemptId);
  await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await flush();await submit();const first=await snapshot();assert.equal(first.session.current.completed,true);
  const previousId=first.attempt.attemptId;await page.getByRole('button',{name:'Next question',exact:true}).click();await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt?.attemptId!==id,previousId);await flush();const after=await snapshot();assert.equal(after.session.kind,'revision');assert.notEqual(after.attempt.attemptId,first.attempt.attemptId);assert.equal(after.history.length,1);
  return {selectedCount:7,includesBondingAndAll3ConfigurationLevels:true,pausedDraftExact:true,schedulerNext:true,first:first.attempt.ref,next:after.attempt.ref};
 });
 await run('teacher-all-bonding-codes-representations-no-evidence',async()=>{
  const codes=[...B.questions.map(q=>q.id),...['full','short','row','energy'].flatMap(representation=>['build','identify'].map(direction=>variants.find(q=>q.speciesId==='Cr'&&q.representation===representation&&q.direction===direction).questionId)),'ECB-00000F'];
  for(const code of codes){await navigate(`http://127.0.0.1:5181/alevel.html?run=a11-review-${code}&mode=teacher&review=${code}`);await page.waitForSelector('.question-player');await page.waitForFunction(()=>window.__mastersActivity!==undefined);assert.equal((await snapshot()).attempt,null);assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),[]);assert(await page.getByRole('button',{name:'Start practice',exact:true}).isDisabled());assert(await page.locator('.worked-answer').isVisible());if(code==='EB03')assert(await page.getByText('Accepted alternatives: sub-shell; electron sub-shell',{exact:true}).isVisible());if(code==='EB04')assert(await page.getByText('Accepted alternatives: shell; electron shell',{exact:true}).isVisible());if(code.startsWith('EC-')||code.startsWith('ECB-'))await page.waitForSelector('.ec-workspace');}
  await page.screenshot({path:path.join(dir,'desktop-teacher-matching.png'),fullPage:true});return {codes:codes.length,all14Bonding:true,all4RepresentationsBothDirections:true,noAttemptOrEvidence:true};
 });
 await run('mobile-touch-energy-scroll-and-nondrag-spin-controls',async()=>{
  // Genuine touch context with an isolated new-project database.
  const touchContext=await chromium.launchPersistentContext(path.join(dir,'edge-touch-profile'),{channel:'msedge',headless:true,viewport:{width:390,height:844},isMobile:true,hasTouch:true,args:['--disable-gpu','--no-first-run']});const touch=await touchContext.newPage();try{
   await touch.goto(`http://127.0.0.1:5181/alevel.html?run=a11-touch-${Date.now().toString(36)}`);await touch.waitForFunction(()=>window.__mastersActivity!==undefined);await touch.getByLabel('Target',{exact:true}).selectOption(target('electron',1));let q;for(let tries=0;tries<30;tries++){const old=(await touch.evaluate(()=>window.__mastersActivity.snapshot())).attempt?.attemptId;await touch.getByRole('button',{name:'Start practice',exact:true}).tap();await touch.waitForFunction(id=>window.__mastersActivity.snapshot().attempt!=null&&window.__mastersActivity.snapshot().attempt.attemptId!==id,old);q=getVariant((await touch.evaluate(()=>window.__mastersActivity.snapshot())).question.ref.questionId);if(q.representation==='energy')break;}assert.equal(q.representation,'energy');await touch.waitForSelector('.ec-box');await touch.locator('.ec-box').first().tap();await touch.evaluate(()=>window.__mastersActivity.flush());assert.equal((await touch.evaluate(()=>window.__mastersActivity.snapshot())).attempt.currentResponses.configuration.boxes[0][0],1);await touch.getByText('Set spins without cycling',{exact:true}).tap();await touch.getByLabel('1s orbital 1',{exact:true}).selectOption('2');await touch.evaluate(()=>window.__mastersActivity.flush());assert.equal((await touch.evaluate(()=>window.__mastersActivity.snapshot())).attempt.currentResponses.configuration.boxes[0][0],2);await touch.locator('.ec-scroll').evaluate(element=>element.scrollLeft=element.scrollWidth);assert(await touch.locator('.ec-scroll').evaluate(element=>element.scrollLeft>0));assert(await touch.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await touch.screenshot({path:path.join(dir,'mobile-energy-touch-spin.png'),fullPage:true});await touch.reload();await touch.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!=null);await touch.waitForSelector('.ec-workspace');assert.equal((await touch.evaluate(()=>window.__mastersActivity.snapshot())).attempt.currentResponses.configuration.boxes[0][0],2);return {viewport:'390×844',actualTouch:true,energyInternalScroll:true,documentNoHorizontalOverflow:true,spinDownAlternative:true,reloadExact:true};
  }finally{await touchContext.close();}
 });
 await run('all71-models-real-browser-rendered-contact-sheets',async()=>{
  const renderPage=await context.newPage();await renderPage.setViewportSize({width:1500,height:1200});const files=[];for(let pageIndex=0;pageIndex<Math.ceil(D.species.length/10);pageIndex++){const group=D.species.slice(pageIndex*10,pageIndex*10+10);const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font:16px Arial;margin:15px}main{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.model{border:1px solid #aaa;padding:8px}.row{width:100%;height:50px}.energy{width:100%;height:260px}h2{font-size:16px;margin:4px 0}</style></head><body><h1>All source species: shared checked orbital depiction</h1><main>${group.map(item=>`<section class="model"><h2>${item.id} (${item.name}), e⁻=${item.z-item.charge}</h2><img class="row" alt="${item.id} row" src="${diagramImage(item.counts,'row')}"><img class="energy" alt="${item.id} energy" src="${diagramImage(item.counts,'energy')}"></section>`).join('')}</main></body></html>`;const name=`models-${pageIndex+1}`;fs.writeFileSync(path.join(dir,`${name}.html`),html);await renderPage.setContent(html);await renderPage.waitForFunction(()=>[...document.images].every(image=>image.complete&&image.naturalWidth>0));await renderPage.screenshot({path:path.join(dir,`${name}.png`),fullPage:true});files.push(`${name}.png`);}await renderPage.close();return {species:71,modelImages:142,contactSheets:files};
 });
}finally{fs.writeFileSync(reportFile,JSON.stringify({browser:'installed Edge headless with isolated new-project profiles',playwright:'1.62.1',results,errors},null,2));await context.close();}
console.log(JSON.stringify({results:results.map(({id,status,error})=>({id,status,error})),errors},null,2));if(results.some(result=>result.status!=='PASS')||errors.length)process.exitCode=1;
