import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {periodicData} from '../../../src/chemistry/electron-configuration/periodic-data.ts';
import {variants} from '../../../src/chemistry/electron-configuration/identity.ts';
const dir=import.meta.dirname,project=path.resolve(dir,'../../..'),require=createRequire(path.resolve(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');const {chromium}=require('playwright'),results=[],errors=[];
const context=await chromium.launchPersistentContext(path.join(dir,'reference-profile'),{channel:'msedge',headless:true,viewport:{width:1365,height:900},args:['--disable-gpu','--no-first-run']});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
async function exactReference(page){const actual=await page.locator('.ec-periodic-element').evaluateAll(elements=>elements.map(e=>({z:Number(e.getAttribute('data-atomic-number')),symbol:e.querySelector('strong').textContent,name:e.querySelector('small').textContent,mass:e.querySelector('.ec-periodic-mass').textContent})));assert.deepEqual(actual,periodicData.elements.map(e=>({z:e.z,symbol:e.symbol,name:e.name,mass:e.mass??''})));assert.equal(await page.locator('.ec-periodic-blank').count(),4);}
try{
 await page.goto(`http://127.0.0.1:5181/alevel.html?run=a11-reference-student-${Date.now().toString(36)}`);await page.waitForFunction(()=>window.__mastersActivity!==undefined);await page.getByLabel('Target',{exact:true}).selectOption('l6-t2-1-2:3');await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity.snapshot().attempt!=null);await page.waitForSelector('.ec-reference button');const before=await page.evaluate(()=>window.__mastersActivity.snapshot());const trigger=page.getByRole('button',{name:'Periodic table',exact:true});await trigger.focus();await page.keyboard.press('Space');await page.waitForSelector('dialog[open]');assert(await page.getByRole('button',{name:'Close periodic table',exact:true}).evaluate(e=>e===document.activeElement));await exactReference(page);await page.screenshot({path:path.join(dir,'desktop-periodic-reference.png'),fullPage:true});await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.ec-periodic-dialog')?.open);assert(await trigger.evaluate(e=>e===document.activeElement));await page.evaluate(()=>window.__mastersActivity.flush());const after=await page.evaluate(()=>window.__mastersActivity.snapshot());assert.deepEqual(after.attempt.currentResponses,before.attempt.currentResponses);assert.deepEqual(after.attempt.assistance,[]);assert.equal(after.history.length,0);assert.equal(after.attempt.attemptId,before.attempt.attemptId);results.push({id:'student-native-dialog-keyboard-exact114-reference',status:'PASS',namedElements:114,blankCells:[113,115,117,118],keyboardOpenEscapeFocusRestore:true,noResponseAssistanceOrEvidence:true});
 const identity=variants.find(q=>q.speciesId==='Cr'&&q.direction==='identify'&&q.representation==='energy');await page.goto(`http://127.0.0.1:5181/alevel.html?run=a11-reference-teacher-${Date.now().toString(36)}&mode=teacher&review=${identity.questionId}`);await page.waitForSelector('.ec-reference button');await page.getByRole('button',{name:'Periodic table',exact:true}).click();await page.waitForSelector('dialog[open]');await exactReference(page);await page.getByRole('button',{name:'Close periodic table',exact:true}).click();assert.equal((await page.evaluate(()=>window.__mastersActivity.snapshot())).attempt,null);assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),[]);results.push({id:'teacher-reference-remains-accessible-without-evidence',status:'PASS',code:identity.questionId});
 const mobile=await chromium.launchPersistentContext(path.join(dir,'reference-touch-profile'),{channel:'msedge',headless:true,viewport:{width:390,height:844},isMobile:true,hasTouch:true,args:['--disable-gpu','--no-first-run']});try{const touch=await mobile.newPage();touch.on('pageerror',error=>errors.push(error.message));await touch.goto(`http://127.0.0.1:5181/alevel.html?run=a11-reference-touch-${Date.now().toString(36)}&mode=teacher&review=${identity.questionId}`);await touch.waitForSelector('.ec-reference button');await touch.getByRole('button',{name:'Periodic table',exact:true}).tap();await touch.waitForSelector('dialog[open]');await exactReference(touch);assert(await touch.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await touch.screenshot({path:path.join(dir,'mobile-periodic-reference-left.png'),fullPage:true});await touch.locator('.ec-periodic-scroll').evaluate(e=>e.scrollLeft=e.scrollWidth);assert(await touch.locator('.ec-periodic-scroll').evaluate(e=>e.scrollLeft>0));await touch.screenshot({path:path.join(dir,'mobile-periodic-reference-right.png'),fullPage:true});await touch.getByRole('button',{name:'Close periodic table',exact:true}).tap();assert.deepEqual(await touch.evaluate(()=>window.__mastersActivity.history()),[]);results.push({id:'mobile-touch-full-reference-scroll-and-close',status:'PASS',viewport:'390×844',namedElements:114,internalHorizontalScroll:true,noDocumentOverflow:true,noTeacherEvidence:true});}finally{await mobile.close();}
}catch(error){results.push({id:'reference-browser',status:'FAIL',error:String(error.stack||error)});await page.screenshot({path:path.join(dir,'periodic-reference-failure.png'),fullPage:true});}finally{await context.close();fs.writeFileSync(path.join(dir,'reference-browser-results.json'),JSON.stringify({results,errors},null,2));}
console.log(JSON.stringify({results,errors},null,2));if(results.length!==3||results.some(result=>result.status!=='PASS')||errors.length)process.exitCode=1;
