import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const dir=import.meta.dirname,project=path.resolve(dir,'../../..'),require=createRequire(path.resolve(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');const {chromium}=require('playwright');
const results=[];
async function check(id,gem,level,limit){
 const context=await chromium.launchPersistentContext(path.join(dir,`timing-${id}-profile`),{channel:'msedge',headless:true,viewport:{width:1365,height:900},args:['--disable-gpu','--no-first-run']});const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
 const snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot());const checkpoint=()=>page.evaluate(async()=>{await window.__mastersActivity.checkpoint();await window.__mastersActivity.flush();return window.__mastersActivity.snapshot();});
 try{
  await page.goto(`http://127.0.0.1:5181/alevel.html?run=a11-time-${id}-${Date.now().toString(36)}`);await page.waitForFunction(()=>window.__mastersActivity!==undefined);await page.getByLabel('Target',{exact:true}).selectOption(`${gem}:${level}`);await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity.snapshot().attempt!=null);await page.waitForSelector('.question-player');
  const interact=async()=>{if(gem==='l6-t2-1-1')await page.locator('.question-part input,.question-part textarea').first().fill('I do not know');else await page.locator('.ec-matching input').first().click();await page.evaluate(()=>window.__mastersActivity.flush());};
  await interact();await page.waitForTimeout(1500);const initial=await checkpoint();assert.equal(initial.attempt.timing.idleLimitMs,limit);assert(initial.attempt.timing.activeMs>0);
  const blank=await context.newPage();await blank.goto('about:blank');await blank.bringToFront();await page.waitForTimeout(2000);const hidden=await checkpoint();const hiddenVisibility=await page.evaluate(()=>document.visibilityState);await page.waitForTimeout(1700);const hiddenEnd=await checkpoint();if(hiddenVisibility==='hidden')assert.equal(hiddenEnd.attempt.timing.activeMs,hidden.attempt.timing.activeMs);await blank.close();await page.bringToFront();await interact();
  const client=await context.newCDPSession(page);await page.evaluate(()=>{window.__a11Ticks=0;window.__a11TickInterval=setInterval(()=>window.__a11Ticks++,250);});const beforeFreeze=await checkpoint();await client.send('Page.setWebLifecycleState',{state:'frozen'});await new Promise(resolve=>setTimeout(resolve,6200));await client.send('Page.setWebLifecycleState',{state:'active'});await page.waitForTimeout(500);const thawed=await checkpoint();const ticks=await page.evaluate(()=>{clearInterval(window.__a11TickInterval);return window.__a11Ticks;});const freezeObserved=ticks<8;if(freezeObserved)assert(thawed.attempt.timing.activeMs-beforeFreeze.attempt.timing.activeMs<1500);await interact();
  // Wait through the genuine source allowance, with no synthetic timestamp/clock injection.
  const idleStart=await checkpoint();for(let elapsed=0;elapsed<limit+1600;elapsed+=45000)await page.waitForTimeout(Math.min(45000,limit+1600-elapsed));const idleEnd=await checkpoint();await page.waitForTimeout(1700);const beyond=await checkpoint();assert.equal(beyond.attempt.timing.activeMs,idleEnd.attempt.timing.activeMs);assert(idleEnd.attempt.timing.activeMs-idleStart.attempt.timing.activeMs<=limit+1000);assert(idleEnd.attempt.timing.activeMs-idleStart.attempt.timing.activeMs>=limit-2000);
  await interact();await page.waitForTimeout(1300);const resumed=await checkpoint();assert(resumed.attempt.timing.activeMs>idleEnd.attempt.timing.activeMs);await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity.snapshot().attempt.phase==='assessed');await page.evaluate(()=>window.__mastersActivity.flush());const first=await snap();await page.waitForTimeout(1300);assert.deepEqual((await checkpoint()).attempt.firstResponse,first.attempt.firstResponse);await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await page.evaluate(()=>window.__mastersActivity.flush());assert.deepEqual((await snap()).attempt.firstResponse,first.attempt.firstResponse);
  const evidence=await page.evaluate(()=>window.__mastersActivity.history());assert.equal(evidence.length,1);assert.deepEqual(evidence[0].timing,first.attempt.firstResponse.timing);assert.equal(errors.length,0);
  results.push({id,status:'PASS',sourceIdleMs:limit,initialActiveMs:initial.attempt.timing.activeMs,hiddenVisibility,backgroundExcluded:hiddenVisibility==='hidden'?true:'not observable in installed Edge headless; unchanged S2 accepted native shared-clock proof/A06 S3 tail applies',suspensionExcluded:freezeObserved?true:"headless CDP freeze did not suspend renderer timers; native gate remains A06-owned",rendererTicksDuringFreeze:ticks,freezeIncrement:thawed.attempt.timing.activeMs-beforeFreeze.attempt.timing.activeMs,idleIncrement:idleEnd.attempt.timing.activeMs-idleStart.attempt.timing.activeMs,overrunExcluded:true,reinteractionResumed:true,firstActiveMs:first.attempt.firstResponse.timing.activeMs,reloadFixed:true,persistedTimeExact:true,ref:first.attempt.ref});
 }catch(error){results.push({id,status:'FAIL',sourceIdleMs:limit,error:String(error.stack||error),errors});await page.screenshot({path:path.join(dir,`${id}-timing-failure.png`),fullPage:true});}finally{await context.close();fs.writeFileSync(path.join(dir,'timing-browser-results.json'),JSON.stringify({browser:'installed Edge headless; separate isolated contexts; genuine wall-clock waiting and CDP lifecycle freezing; no injected timestamps',results},null,2));}
}
await Promise.allSettled([check('bonding-one-minute','l6-t2-1-1',1,60000),check('matching-three-minute','l6-t2-1-2',3,180000)]);
console.log(JSON.stringify(results,null,2));if(results.length!==2||results.some(result=>result.status!=='PASS'))process.exitCode=1;
