import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const app=path.resolve(import.meta.dirname,'../..'),dir=import.meta.dirname,require=createRequire(path.resolve(app,'../../package.json')),{chromium}=require('playwright');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf','.json':'application/json'};
const server=http.createServer((request,response)=>{try{const match=/^\/statistics-restore\/(alevel|igcse)\/(.*)$/.exec(decodeURIComponent(new URL(request.url,'http://localhost').pathname));if(!match)throw Error('Unknown prefix');const root=path.resolve(app,'dist',match[1]),file=path.resolve(root,match[2]||'index.html');if(!file.startsWith(root+path.sep))throw Error('Outside build');response.setHeader('Content-Type',mime[path.extname(file)]??'application/octet-stream');response.end(fs.readFileSync(file));}catch{response.writeHead(404);response.end();}});
await new Promise(resolve=>server.listen(5204,'127.0.0.1',resolve));const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];
try{for(const course of ['alevel','igcse']){const ctx=await browser.newContext({viewport:{width:1366,height:1000},timezoneId:'Europe/London'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(`http://127.0.0.1:5204/statistics-restore/${course}/index.html?course=${course}&view=statistics`,{waitUntil:'networkidle'});await page.getByTestId('statistics-total').waitFor();assert.equal(await page.locator('.stats-metric').count(),5);assert.equal(await page.getByRole('heading',{name:'Your Stats',exact:true}).count(),1);assert.equal(await page.locator('.course-navigation,.platform-navigation').count(),0);assert.equal(await page.getByRole('button',{name:'All time',exact:true}).getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>window.__mastersActivity),undefined);assert((await page.locator('.stats-brand').innerText()).includes(course==='alevel'?'A LEVEL':'IGCSE'));
 await page.screenshot({path:path.join(dir,`${course}-release-prefix.png`),fullPage:true});await page.getByRole('button',{name:'Back to course map',exact:true}).last().click();await page.waitForURL(/view=home/);assert(page.url().includes(`/statistics-restore/${course}/index.html`));assert.equal(new URL(page.url()).searchParams.get('course'),course);
 await page.goto(`http://127.0.0.1:5204/statistics-restore/${course}/index.html?course=${course}&view=import`,{waitUntil:'networkidle'});assert(await page.locator('.platform-navigation').count());assert(await page.locator('.course-navigation').count());assert.deepEqual(errors,[]);results.push({course,status:'PASS',prefix:`/statistics-restore/${course}/`,statisticsSpecificShell:true,backPreservesPrefixAndCourse:true,importShellPreserved:true,devHooksAbsent:true});
 }catch(e){results.push({course,status:'FAIL',error:String(e.stack??e),errors});}finally{await ctx.close();}}}finally{await browser.close();await new Promise(resolve=>server.close(resolve));const report={status:results.length===2&&results.every(r=>r.status==='PASS')?'PASS':'FAIL',checkedAt:new Date().toISOString(),results};fs.writeFileSync(path.join(dir,'release-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;}
