import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {createServer} from 'vite';
const app=path.resolve(import.meta.dirname,'../..'),require=createRequire(path.resolve(app,'../../package.json')),{chromium}=require('playwright');
const devServer=await createServer({root:app,cacheDir:path.join(import.meta.dirname,'vite-cache'),optimizeDeps:{noDiscovery:true,include:['react','react-dom/client','react/jsx-runtime','react/jsx-dev-runtime','dexie','zustand','zustand/vanilla']},server:{host:'127.0.0.1',port:5205,strictPort:true,hmr:false}});await devServer.listen();
const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];
try {for(const course of ['alevel','igcse']){
 const context=await browser.newContext({viewport:{width:1366,height:1000},timezoneId:'Europe/London'}),page=await context.newPage(),run='stats-timing-'+course+'-'+Date.now(),base='http://127.0.0.1:5205/alevel.html',errors=[];page.on('pageerror',e=>errors.push(e.message));
 try {
  const activity=course==='alevel'?'acid-base-calculations':'calorimetry',gem=course==='alevel'?'u6-t1-1-2':'lower-10-3';
  await page.goto(`${base}?course=${course}&view=practice&activity=${course}/${activity}&leaf=${gem}&level=1&fresh=1&run=${run}`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__mastersActivity?.snapshot().question);await page.evaluate(()=>window.__mastersActivity.flush());
  await page.mouse.move(300,300);await page.keyboard.press('Tab');
  await page.evaluate(async()=>{const question=window.__mastersActivity.snapshot().question;for(const part of question.parts){if(part.kind==='numeric')await window.__mastersActivity.respond(part.id,{kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit});else if(part.kind==='text')await window.__mastersActivity.respond(part.id,{kind:'text',value:part.accepted[0]});else throw Error('Unexpected source question kind '+part.kind);}});
  await page.waitForTimeout(600);await page.getByRole('button',{name:'Check',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity.snapshot().attempt?.phase==='assessed');await page.evaluate(()=>window.__mastersActivity.flush());
  const first=await page.evaluate(()=>window.__mastersActivity.snapshot().history[0]);assert.equal(first.provenance,'new-attempt');assert.equal(first.score,1);assert(first.timing.activeMs>0);
  await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await page.evaluate(()=>window.__mastersActivity.flush());const restored=await page.evaluate(()=>window.__mastersActivity.snapshot().history);assert.deepEqual(restored,[first]);
  await page.goto(`${base}?course=${course}&view=statistics&run=${run}`,{waitUntil:'networkidle'});await page.getByTestId('statistics-total').waitFor();assert.equal(await page.getByTestId('statistics-total').innerText(),'1');assert.equal(Number(await page.getByTestId('statistics-time').getAttribute('data-active-ms')),first.timing.activeMs);assert.equal(await page.locator('.stats-chart-bar').evaluateAll(items=>items.reduce((n,item)=>n+Number(item.dataset.activeMs),0)),first.timing.activeMs);
  await page.locator('.stats-topic summary').last().click();const button=page.locator(`[data-gem="${gem}"] .stats-recent button`);await button.focus();const detail=await page.locator(`[data-gem="${gem}"] .stats-result-detail`).innerText();assert(detail.includes(first.ref.questionId));await button.click();await page.screenshot({path:path.join(import.meta.dirname,`${course}-live-timing-transfer.png`),fullPage:true});
  assert.deepEqual(errors,[]);results.push({course,status:'PASS',attemptId:first.id,questionCode:first.ref.questionId,activeMs:first.timing.activeMs,score:first.score,restoredEvidenceUnchanged:true,chartConserved:true,detail});
 }catch(e){results.push({course,status:'FAIL',error:String(e.stack??e),errors});await page.screenshot({path:path.join(import.meta.dirname,`${course}-live-timing-failure.png`),fullPage:true});}finally{await context.close();}
}}finally{await browser.close();await devServer.close();const report={status:results.length===2&&results.every(r=>r.status==='PASS')?'PASS':'FAIL',checkedAt:new Date().toISOString(),scope:'Actual source question provider, marking, attempt controller, active clock, immutable save/restore and statistics; existing DEV hooks issue responses only, trusted browser interaction and real clock. No substituted timing.',results};fs.writeFileSync(path.join(import.meta.dirname,'timing-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;}
