import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const project=path.resolve(import.meta.dirname,'../../../..'),slug='dev-reviewed-starter',folder=path.join(import.meta.dirname,slug),read=p=>JSON.parse(fs.readFileSync(p,'utf8')),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const sources=read(path.join(folder,'source-validation.json')),browser=read(path.join(folder,'browser-results.json'));assert.equal(sources.status,'PASS');assert.equal(browser.status,'PASS');
const generated=read(path.join(project,`development/authoring/families/${slug}/generation-manifest.json`));
const report={id:'A20/S4-AUTHORING-RUNNABLE-REFINEMENT',status:'PASS',confidence:0.97,rootAccepted:false,completedAt:new Date().toISOString(),requestedModel:'gpt-6.1-sol',requestedEffort:'high',actualModel:null,actualEffort:null,usage:null,
 source:'development/authoring/scaffold.mjs',generatedPath:`development/authoring/families/${slug}`,generatedByCLI:true,noManualGeneratedEdits:true,productionEnabled:false,
 generatedFiles:sources.generatedFiles,questionIdPrefix:generated.prefix,levels:[1,2,3],fixedQuestions:1,seededLevelConfigurations:72,
 validation:{source:'validation/s4/authoring-release/refinement/dev-reviewed-starter/source-validation.json',fixtures:'validation/s4/authoring-release/refinement/dev-reviewed-starter/fixtures.log',typecheck:'validation/s4/authoring-release/refinement/dev-reviewed-starter/typecheck.log',browser:'validation/s4/authoring-release/refinement/dev-reviewed-starter/browser-results.json',render:'validation/s4/authoring-release/refinement/rendered-review.md',chemistry:'validation/s4/authoring-release/refinement/chemistry-review.md',independentStartupDisposition:'validation/s4/refinement/review-scaffold-startup/disposition.json'},
 docs:'docs/authoring/new-activity.md',canonicalOnboarding:'authored-metadata.json + identity union when needed + definitions regeneration/check + lazy adapter; canonical scope/current persistence boundaries derived; legacy original-store parser unchanged',
 sharedAlgorithmsUnchanged:sources.baselineChanged.length===0,oldReleaseEvidencePreserved:sources.oldReleaseAndCompletionPreserved,
 limits:['Initial cold load stalls remain unclassified; accepted behavior suite runs against frozen warm-cache development server.','Only A06-reviewed initial DOMContentLoaded wait changed; no timeout/profile shortening/substantive assertion changes.','Current full OCR specification PDF not reread; retained official2016 section5.1.3(d),(f)(i) and departmental OCR3.1 map/previous chemistry review consulted.','CLI starter is reviewed-template DEV content; no new production activity/gem, release changes, S5 or publication authorised.','A01 formatting/aggregate and root acceptance remain separate.'],
 retainedFailures:['validation/s4/authoring-release/refinement/first-generated-fixture-failure.log','validation/s4/authoring-release/refinement/dev-refinement-starter/startup-cache-reload-probe.json','validation/s4/authoring-release/refinement/dev-refinement-starter/restarted-navigation-probe.json']};
const paths=['development/authoring/scaffold.mjs','development/authoring/serve.mjs','development/authoring/templates/prepare.mjs','development/authoring/templates/family.test.mjs','development/authoring/templates/browser.mjs','docs/authoring/README.md','docs/authoring/new-activity.md'];
report.sourceFingerprints=Object.fromEntries(paths.map(p=>[p,sha(fs.readFileSync(path.join(project,p)))]));
fs.writeFileSync(path.join(import.meta.dirname,'completion.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({id:report.id,status:report.status,output:'validation/s4/authoring-release/refinement/completion.json',confidence:report.confidence}));
