import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {fixtureKinds} from '../../../../src/development/fixtures.ts';
const root=path.resolve(import.meta.dirname,'../../../..'),require=createRequire(path.join(root,'../../package.json')),here=import.meta.dirname;
assert.equal(require('playwright/package.json').version,'1.62.1');const temp=path.join(here,'.bt');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
const report={jobId:'DEV-AUTHORING-CANONICAL',startedAt:new Date().toISOString(),browser:await browser.version(),checks:[],pageErrors:[],storageCalls:[]},run='correction-'+Date.now();page.on('pageerror',e=>report.pageErrors.push(e.message));
await context.addInitScript(()=>{window.devStorageCalls=[];const open=indexedDB.open.bind(indexedDB);indexedDB.open=function(name,...args){window.devStorageCalls.push(name);return open(name,...args);};});
const base='http://127.0.0.1:5181',snap=()=>page.evaluate(()=>window.__mastersFoundation.snapshot()),flush=()=>page.evaluate(()=>window.__mastersFoundation.flush());
async function click(name){await page.getByRole('button',{name,exact:true}).click();await flush();}
async function ready(){await page.waitForFunction(()=>window.__mastersFoundation);}
async function attempt(){await page.waitForFunction(()=>window.__mastersFoundation?.snapshot().attempt);await flush();}
const responses={numeric:{kind:'numeric',raw:'42',unit:'kJ'},'self-drawing':{kind:'numeric',raw:'42',unit:'kJ'},'automatic-text':{kind:'text',value:'This is a long automatic response.'},'self-rubric':{kind:'explanation',sections:[{id:'reason',text:'Synthetic evidence'},{id:'comparison',text:'Synthetic comparison'}]},choice:{kind:'choice',selected:['A']},'choice-dropdown':{kind:'choice',selected:['A']},'choice-multiple':{kind:'choice',selected:['A','B']},correction:{kind:'correction',selections:[{start:20,end:25,text:'error'}],replacement:'correct'},diagram:{kind:'diagram-selection',selectedObjectIds:['object-A']},editor:{kind:'molecule',graph:{atoms:[{id:1,element:'C',x:0,y:0}],bonds:[]},history:[]}};
try{
 for(const kind of fixtureKinds){
  await page.goto(`${base}/alevel.html?harness=s1&fixture=${kind}&run=${run}-${kind}`);await ready();await page.getByLabel('Target',{exact:true}).selectOption('u6-t1-1-2:1');await click('Start fixture');await attempt();
  await page.evaluate(r=>window.__mastersFoundation.respond('answer',r),responses[kind]);await flush();await page.mouse.click(700,330);await page.waitForTimeout(220);await page.evaluate(()=>window.__mastersFoundation.checkpoint());await flush();const before=await snap();assert.match(before.attempt.ref.questionId,/^AB-[A-Z0-9]{6}$/);assert.equal(before.saveStatus.kind,'saved');assert(before.attempt.timing.activeMs>0);
  await page.reload();await ready();await attempt();const after=await snap();assert.deepEqual(after.question,before.question);assert.deepEqual(after.attempt.ref,before.attempt.ref);assert.deepEqual(after.attempt.currentResponses,before.attempt.currentResponses);assert.equal(after.attempt.attemptId,before.attempt.attemptId);assert(after.attempt.timing.activeMs>=before.attempt.timing.activeMs);assert.equal(after.history.length,0);assert(after.databaseName.includes('-dev-controls-'));report.storageCalls.push(...await page.evaluate(()=>window.devStorageCalls));
  if(kind==='numeric'){
   await page.getByLabel(/Your answer/).fill('42');await flush();await click('Check answer');await page.waitForFunction(()=>window.__mastersFoundation.snapshot().history.length===1);const assessed=await snap();assert.equal(assessed.attempt.firstAssessment.marks.earned,1);assert(assessed.history[0].timing.activeMs>0);const evidence=assessed.history[0];await page.reload();await ready();await attempt();assert.deepEqual((await snap()).history,[evidence]);await page.screenshot({path:path.join(here,'dev-controls-numeric-assessed.png'),fullPage:true});
  }
  report.checks.push({name:`${kind}: canonical ref/content/response/attempt/timing reproduced from saved actual shared runtime`,status:'PASS',ref:before.attempt.ref,database:before.databaseName});
 }
 await page.goto(`${base}/alevel.html?harness=s1&fixture=numeric&run=${run}-revision`);await ready();await page.getByLabel('Session',{exact:true}).selectOption('revision');await click('ADD ALL u6-t1-1');assert((await snap()).selectedCount>0);await click('Start fixture');await attempt();await page.evaluate(r=>window.__mastersFoundation.respond('answer',r),responses.numeric);await flush();await page.evaluate(()=>window.__mastersFoundation.checkpoint());const revision=await snap();await page.reload();await ready();await attempt();assert.equal((await snap()).attempt.attemptId,revision.attempt.attemptId);assert.equal((await snap()).session.kind,'revision');await click('Check answer');await page.waitForFunction(()=>window.__mastersFoundation.snapshot().history.length===1);const scored=await snap();await click('Next question');await page.waitForFunction(id=>window.__mastersFoundation.snapshot().attempt.attemptId!==id,scored.attempt.attemptId);assert.equal((await snap()).history.length,1);report.checks.push({name:'Synthetic revision save/reload, first score/timing and scheduler Next',status:'PASS'});
 await page.goto(`${base}/alevel.html?harness=s1&fixture=numeric&run=${run}-teacher`);await ready();await click('Teacher preview');await page.getByRole('heading',{name:'Checked answer and diagrams',exact:true}).waitFor();assert.equal((await snap()).attempt,null);assert.equal((await snap()).history.length,0);await page.screenshot({path:path.join(here,'dev-controls-teacher.png'),fullPage:true});report.checks.push({name:'Synthetic teacher preview creates no attempt/timing/evidence',status:'PASS'});
 // Same run, different source-owned family tokens. Both reload their own exact attempt.
 const families=['dev-s5-independent','dev-canonical-correction'],saved=[];
 for(const name of families){await page.goto(`${base}/development/authoring/families/${name}/preview.html?run=${run}-scope`);await page.waitForFunction(()=>window.__mastersActivity);await page.getByLabel('Target',{exact:true}).selectOption('u6-t1-1-2:2');await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity.snapshot().attempt);await page.evaluate(()=>window.__mastersActivity.respond('ph',{kind:'numeric',raw:'1.23',unit:''}));await page.evaluate(()=>window.__mastersActivity.checkpoint());await page.evaluate(()=>window.__mastersActivity.flush());saved.push(await page.evaluate(()=>window.__mastersActivity.snapshot()));}
 assert.notEqual(saved[0].databaseName,saved[1].databaseName);assert.notEqual(saved[0].question.ref.questionId,saved[1].question.ref.questionId);
 for(let i=0;i<families.length;i++){await page.goto(`${base}/development/authoring/families/${families[i]}/preview.html?run=${run}-scope`);await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt);const actual=await page.evaluate(()=>window.__mastersActivity.snapshot());assert.equal(actual.databaseName,saved[i].databaseName);assert.equal(actual.attempt.attemptId,saved[i].attempt.attemptId);assert.deepEqual(actual.question,saved[i].question);assert.deepEqual(actual.attempt.currentResponses,saved[i].attempt.currentResponses);await page.screenshot({path:path.join(here,`dev-family-scope-${families[i]}.png`),fullPage:true});}
 report.checks.push({name:'Two DEV-family routes with identical run use distinct guarded databases and reproduce exact own code/ref/content on reload',status:'PASS',databases:saved.map(s=>s.databaseName),refs:saved.map(s=>s.question.ref)});
 assert(report.storageCalls.every(n=>n.startsWith('masters-of-chemistry-alpha-v2-alevel-dev-controls-')));assert.deepEqual(report.pageErrors,[]);report.status='PASS';
}catch(error){report.status='FAIL';report.error=String(error.stack);await page.screenshot({path:path.join(here,'dev-controls-failure.png'),fullPage:true});throw error;}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'development-browser-results.json'),JSON.stringify(report,null,2));await browser.close();}
