import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const project=path.resolve(import.meta.dirname,'../../../..'),here=import.meta.dirname,sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const before=JSON.parse(fs.readFileSync(path.join(here,'before-manifest.json'),'utf8')),changed=[];let patch='';
for(const file of before.files){const current=path.join(project,file.path),old=path.join(here,'before',file.path),currentHash=sha(fs.readFileSync(current));if(currentHash===file.sha256)continue;
 if(sha(fs.readFileSync(old))!==file.sha256)throw Error('Before snapshot changed: '+file.path);
 const diff=spawnSync('git',['diff','--no-index','--',old,current],{cwd:project,encoding:'utf8',maxBuffer:10*1024*1024});if(diff.status!==1)throw Error('Expected source difference '+file.path+' '+diff.stderr);patch+=diff.stdout;changed.push({path:file.path,beforeSha256:file.sha256,sha256:currentHash,diff:'before-current-source.patch'});
}
const newFiles=['src/development/identity.ts','development/authoring/family-slots.json',...fs.readdirSync(path.join(project,'development/authoring/families/dev-canonical-correction')).map(f=>'development/authoring/families/dev-canonical-correction/'+f)];
for(const file of newFiles){const current=path.join(project,file);const diff=spawnSync('git',['diff','--no-index','--','NUL',current],{cwd:project,encoding:'utf8',maxBuffer:10*1024*1024});if(diff.status!==1)throw Error('Expected new source diff '+file);patch+=diff.stdout;changed.push({path:file,beforeSha256:null,sha256:sha(fs.readFileSync(current)),diff:'before-current-source.patch'});}
fs.writeFileSync(path.join(here,'before-current-source.patch'),patch);fs.writeFileSync(path.join(here,'changed-paths.json'),JSON.stringify({jobId:'F1-CODEC-DEV',agentId:'F02',capturedAt:new Date().toISOString(),files:changed},null,2));
const baseline=JSON.parse(fs.readFileSync(path.join(here,'../baseline.json'),'utf8')),freeze=fs.readFileSync(path.join(project,baseline.priorEvidenceFreeze));
if(sha(freeze)!==baseline.priorEvidenceFreezeSha256)throw Error('Prior evidence freeze manifest changed');
const prior=JSON.parse(freeze).files,checked=prior.map(f=>({path:f.path,unchanged:fs.existsSync(path.join(project,f.path))&&sha(fs.readFileSync(path.join(project,f.path)))===f.sha256}));
if(checked.some(f=>!f.unchanged))throw Error('Prior F1 evidence changed');fs.writeFileSync(path.join(here,'prior-f1-integrity.json'),JSON.stringify({status:'PASS',baseline:'../baseline.json',files:checked},null,2));
const snapshotPaths=new Set(before.files.map(f=>f.path)),ownedPrefixes=['src/activities/alevel/acid-base-calculations/identity.ts','src/development/','src/foundation/ActivityHost.tsx','src/persistence/alpha-namespace.ts','scripts/test-component-identity.mjs','development/authoring/','docs/authoring/'];
const rows=baseline.inputs.filter(f=>ownedPrefixes.some(p=>f.path===p||p.endsWith('/')&&f.path.startsWith(p))).map(f=>({path:f.path,baselineSha256:f.sha256,currentSha256:sha(fs.readFileSync(path.join(project,f.path))),changed:sha(fs.readFileSync(path.join(project,f.path)))!==f.sha256,beforeTextCaptured:snapshotPaths.has(f.path)}));
fs.writeFileSync(path.join(here,'baseline-current-diff-manifest.json'),JSON.stringify({baseline:'validation/component-fidelity/f1-correction/baseline.json',rows,newFiles:changed.filter(f=>f.beforeSha256===null),exactTextDiff:'before-current-source.patch'},null,2));
console.log(JSON.stringify({changedPaths:changed.length,priorF1Preserved:checked.length,patchBytes:Buffer.byteLength(patch)}));
