import {productionRegistry} from '../../../../src/foundation/registry.ts';
import {createCourseMastery} from '../../../../src/domain/mastery/index.ts';
import {createRevisionSession,revisionScheduler,bindRevisionQuestion} from '../../../../src/domain/session/revision.ts';
import {createAttemptController,assessmentToEvidence} from '../../../../src/domain/attempt/attempt.ts';
import {createActiveClock} from '../../../../src/domain/timing/active-clock.ts';

// Construct canonical synthetic records with the real provider/controller/scheduler.
// Install only while the real Host is unloaded; the browser validates/restores them.
export async function fixture(course,kind){
 const reg=productionRegistry.get(course==='alevel'?'alevel/acid-base-calculations':'igcse/calorimetry'),gem=reg.gems[0],provider=await reg.provider(),policy=await reg.marking(),namespace={course,profileId:'local'},selected=gem.supportedLevels.map(level=>({course,activityId:reg.id,gemId:gem.id,level}));
 const attempts=[],evidence=[],summaries=()=>gem.supportedLevels.map(level=>createCourseMastery(course).summarize(evidence,gem.mastery,level));
 function fresh(target,id,seed){const ref=provider.select({...target,seed,previousQuestionIds:[]}),question=provider.restore(ref);return{question,attempt:{mode:'student',namespace,attemptId:id,ref,target,currentResponses:Object.fromEntries(question.parts.map(p=>{if(p.kind!=='numeric')throw Error('Numeric model required');return[p.id,{kind:'numeric',raw:String(p.acceptance.expected),unit:p.unit}]})),assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:reg.idleAllowance(question),finished:false}}}}
 function assess(f){const sample=()=>({monotonicMs:0,wallMs:Date.now(),visible:true,focused:true,suspended:false}),c=createAttemptController({question:f.question,state:f.attempt,policy,sample,clock:createActiveClock({attemptId:f.attempt.attemptId,idleLimitMs:f.attempt.timing.idleLimitMs,now:sample})}),r=c.dispatch({kind:'submit',at:Date.now()});if(!r.accepted)throw Error(r.message);const a=c.state(),e=assessmentToEvidence(a);if(e?.score!==1)throw Error('Canonical model failed');attempts.push(a);evidence.push(e);return e;}
 if(kind==='empty-practice')return{attempts,evidence,sessions:[{kind:'practice',namespace,id:'current-session',target:selected[0],selection:'fixed-level',currentAttemptId:null,previousQuestionIds:[],paused:true}]};
 if(kind==='terminal')for(const target of selected)for(let i=0;i<10;i++)assess(fresh(target,`a23-history-${course}-${target.level}-${i}`,101+i));
 let session=createRevisionSession({namespace,id:'current-session',selected,settings:[gem.mastery],summaries:summaries(),now:Date.now()});
 if(kind==='empty-revision')return{attempts,evidence,sessions:[{...session,status:'paused'}]};
 if(!summaries().every(s=>s.mastered))throw Error('Terminal fixture mastery not reached');
 for(let i=0;i<selected.length;i++){const id=`a23-terminal-${course}-${i}`;session=revisionScheduler.next(session,summaries(),Date.now(),id);const f=fresh(session.current.target,id,201+i);session=bindRevisionQuestion(session,f.attempt.ref);if(i===selected.length-1){attempts.push(f.attempt);return{attempts,evidence,sessions:[session],lastId:id};}const e=assess(f);session=revisionScheduler.accept(session,{attemptId:id,score:1,independent:true,completedAt:e.completedAt},summaries(),Date.now());}
 throw Error('Missing terminal fixture');
}
export async function rows(page,course){return page.evaluate(async course=>{const db=await new Promise((r,j)=>{const q=indexedDB.open(`masters-of-chemistry-${course}-local`);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});try{const out={};for(const n of['attempts','evidence','sessions'])out[n]=await new Promise((r,j)=>{const q=db.transaction(n).objectStore(n).getAll();q.onsuccess=()=>r(q.result.map(x=>x.value));q.onerror=()=>j(q.error)});return out}finally{db.close()}},course)}
export async function install(page,course,data){await page.goto(`http://127.0.0.1:5203/nested/${course}/index.html`);await page.getByRole('button',{name:'Start practice',exact:true}).waitFor();await page.goto(`http://127.0.0.1:5203/nested/${course}/.vite/manifest.json`);await page.evaluate(async({course,data})=>{const db=await new Promise((r,j)=>{const q=indexedDB.open(`masters-of-chemistry-${course}-local`);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});await new Promise((r,j)=>{const t=db.transaction(['attempts','evidence','sessions'],'readwrite');for(const name of['attempts','evidence','sessions'])for(const value of data[name])t.objectStore(name).put({course,profileId:'local',id:name==='sessions'?value.id:value.attemptId,value});t.oncomplete=r;t.onerror=()=>j(t.error);t.onabort=()=>j(t.error)});db.close()},{course,data});}
