import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {productionRegistry} from '../../../../src/foundation/registry.ts';
const here=import.meta.dirname,app=path.resolve(here,'../../../..'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.f12-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const all=JSON.parse(fs.readFileSync(path.join(here,'fixtures.json'))),fixtures=all.filter(f=>['acid','calorimetry','bond','bonding','energy','practical'].includes(f.source.family)&&!f.question.parts.some(p=>p.kind==='energy-profile'));
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={agentId:'F12',jobId:'F3-INDEPENDENT',status:'RUNNING',startedAt:new Date().toISOString(),checks:[],shots:[],errors:[],limits:['Fresh synthetic app IndexedDB namespaces and nonpersistent contexts only.','Native OS suspend/minimize coverage retained by foreman; this browser suite checks reload and first timing.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.locator('.source-player').screenshot({path:path.join(here,name+'.png')});report.shots.push(name+'.png')}
async function start(c,f,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5188/${f.course}.html?run=f12-independent-${Date.now()}-${Math.random().toString(36).slice(2)}`);await p.locator('.original-landing').waitFor({state:'attached'});
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();if(f.course==='alevel'&&f.gem.startsWith('u6'))await p.locator('#flipYear').click();const gem=p.locator('[data-leaf="'+f.gem+'"]').first();await gem.locator('xpath=ancestor::*[contains(@class,"topic-section")]').locator('.topic-trigger').click();await gem.click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click()}
 else{await p.evaluate(gem=>location.hash=gem,f.gem);await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${f.ref.level}"]`).click()}
 await p.locator('.question-player').waitFor();await flush(p);
 if(mode!=='revision'&&((await snap(p)).question.ref.questionId!==f.ref.questionId|| (await snap(p)).question.ref.level!==f.ref.level)){await p.evaluate(async f=>{const s=window.__mastersActivity.snapshot(),{productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const a=productionRegistry.get(f.activity),provider=await a.provider();provider.restore(f.ref);const id=crypto.randomUUID(),target={...s.attempt.target,gemId:f.gem,level:f.ref.level},attempt={...s.attempt,attemptId:id,ref:f.ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{...s.attempt.timing,attemptId:id,activeMs:0,finished:false}};const session={...s.session,currentAttemptId:id,...(s.session.kind==='practice'?{target,previousQuestionIds:[f.ref.questionId]}:{})};const repo=createChemistryRepository(s.databaseName),saved=await repo.saveCurriculum({attempt,session,question:provider.restore(f.ref),namespace:attempt.namespace});if(!saved.ok)throw Error(JSON.stringify(saved));repo.close?.()},f);await p.reload();await p.locator('.source-player').waitFor();await flush(p)}
 if(mode!=='revision')assert.equal((await snap(p)).question.ref.questionId,f.ref.questionId);return p;
}
function answers(f){const out={};for(const part of f.question.parts){if(part.kind==='numeric')out[part.id]={kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit};if(part.kind==='text')out[part.id]={kind:'text',value:part.accepted[0]};if(part.kind==='choice')out[part.id]={kind:'choice',selected:part.acceptedOptionSets[0]};if(part.kind==='correction'){const s=part.segments.find(x=>x.id===f.source.practical.correction.errorId);out[part.id]={kind:'correction',selections:[s],replacement:f.source.practical.fields[0].answers[0]}}}return out}
async function fill(p,f,data){for(const part of f.question.parts){const r=data[part.id];if(!r)continue;if(r.kind==='numeric'){const inputs=p.locator('.response-input');await inputs.nth(f.question.parts.filter(x=>x.kind==='numeric').findIndex(x=>x.id===part.id)).fill(r.raw)}else if(r.kind==='text'){await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.value)}else if(r.kind==='choice'){const field=p.locator('.choice-field,.choice-box').filter({has:p.getByText(f.source.fields[part.id].label,{exact:true})});if(f.source.family==='practical'){for(const selected of r.selected)await field.getByText(selected,{exact:true}).click()}else{for(const selected of r.selected)await field.getByRole('button').filter({hasText:selected}).click()}}else if(r.kind==='correction'){await p.getByRole('button',{name:r.selections[0].text.trim(),exact:true}).click();await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.replacement)}}await flush(p)}
async function wrong(f,correct){const a=productionRegistry.get(f.activity),policy=await a.marking();for(const part of f.question.parts){const v=correct[part.id];const candidates=part.kind==='numeric'?['999999']:part.kind==='choice'?part.options.map(o=>o.id).filter(id=>!v.selected.includes(id)):part.kind==='correction'?['increases','wrong']:['0','1','2','3','4','5','6','proton','neutron','ionic','covalent','metallic','endothermic','exothermic','positive','negative','wrong'];for(const x of candidates){const copy=structuredClone(correct);copy[part.id]=v.kind==='numeric'?{...v,raw:x}:v.kind==='choice'?{...v,selected:v.selected.length===1?[x]:[x,...v.selected.slice(1)]}:v.kind==='correction'?{...v,replacement:x}:{...v,value:x};const outcome=policy.mark(f.question,copy);if(outcome.accepted&&outcome.marks.earned<outcome.marks.available)return copy}}throw Error('No meaningful wrong fixture '+f.ref.questionId)}

async function review(p,met){const q=(await snap(p)).question,part=q.parts[0];for(const section of part.sections)await p.locator('[id$="-'+section.id+'"]').fill(part.rubric.map(r=>r.text).join(' '));await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.locator('.locked-answer').waitFor();await flush(p);return (await snap(p)).attempt}
async function finish(p,met){const a=(await snap(p)).attempt;for(const point of (await snap(p)).question.parts[0].rubric){if(!met)await p.locator('.decision.no:enabled').click();else{await p.locator('.decision.yes:enabled').click();await p.locator('.keyboard-evidence summary').click();await p.getByLabel('Start',{exact:true}).fill('0');await p.getByLabel('End (exclusive)',{exact:true}).fill(String(a.reviews[0].lockedText.length));await p.getByRole('button',{name:'Use selected text',exact:true}).click()}}await p.getByRole('button',{name:'Finish marking',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await flush(p)}
async function fullshot(p,name){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(here,name+'.png'),fullPage:true});report.shots.push(name+'.png')}
async function noOverflow(p){assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth));}
async function collapsed(p){const detail=p.locator('.original-first-marking'),summary=detail.locator('summary');assert.equal(await detail.count(),1);assert.equal(await detail.getAttribute('open'),null);assert(await p.locator('.assessment-feedback .score').isVisible());await summary.focus();await summary.press('Enter');assert.notEqual(await detail.getAttribute('open'),null);assert(await detail.locator('.mark-list').isVisible());await summary.press('Space');assert.equal(await detail.getAttribute('open'),null);}
try{
 for(const size of ['desktop','tablet','mobile']){
  const viewport={desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}}[size];
  // Exact requested EE regression with real option/button interactions.
  const ee=all.find(f=>f.ref.questionId==='EE-6US2V7'),ec=await b.newContext({viewport,hasTouch:size==='mobile'}),ep=await start(ec,ee),good=answers(ee),bad=await wrong(ee,good);
  await noOverflow(ep);await fullshot(ep,`${size}-EE-unanswered`);const metrics=await ep.locator('.pupil-answer-actions').evaluate(el=>({wrap:getComputedStyle(el).flexWrap,width:el.getBoundingClientRect().width,buttons:[...el.children].map(b=>({text:b.textContent,flex:getComputedStyle(b).flex,width:b.getBoundingClientRect().width,x:b.getBoundingClientRect().x,y:b.getBoundingClientRect().y}))}));assert.equal(metrics.wrap,'wrap');assert(metrics.buttons.every(b=>b.width<=metrics.width+1));if(size==='mobile'){assert(metrics.buttons.some(b=>b.width<metrics.width-30));assert(new Set(metrics.buttons.map(b=>b.y)).size>1)}
  await fill(ep,ee,bad);await ep.getByRole('button',{name:'Check answer',exact:true}).click();await ep.locator('.assessment-feedback').waitFor();await flush(ep);const first=await snap(ep);await fullshot(ep,`${size}-EE-incorrect`);
  await ep.evaluate(async()=>window.__mastersActivity.respond('field-0',{kind:'choice',selected:[]}));await fill(ep,ee,good);await ep.getByRole('button',{name:'Check correction',exact:true}).click();await ep.locator('.correction-feedback').waitFor();await flush(ep);assert.deepEqual((await snap(ep)).attempt.firstAssessment,first.attempt.firstAssessment);assert.deepEqual((await snap(ep)).attempt.firstResponse,first.attempt.firstResponse);await fullshot(ep,`${size}-EE-correction`);await ep.getByRole('button',{name:'Show worked answer',exact:true}).click();await fullshot(ep,`${size}-EE-model`);await ep.reload();await ep.locator('.worked-answer').waitFor();await flush(ep);assert.deepEqual((await snap(ep)).attempt.firstResponse,first.attempt.firstResponse);assert.equal((await ep.evaluate(()=>window.__mastersActivity.history())).length,1);report.checks.push({size,case:'EE-6US2V7',metrics,immutable:true,restoreDedup:true});await ec.close();
  // Numeric first details are collapsed, keyboard accessible, and independently immutable.
  const nf=all.find(f=>f.ref.questionId==='CAL-00I9HC'),nc=await b.newContext({viewport,hasTouch:size==='mobile'}),np=await start(nc,nf),ng=answers(nf),nb=await wrong(nf,ng);await fullshot(np,`${size}-numeric-unanswered`);await fill(np,nf,nb);await np.getByRole('button',{name:'Check answer',exact:true}).click();await np.locator('.assessment-feedback').waitFor();await flush(np);const nfirst=await snap(np);assert(nfirst.attempt.firstResponse.timing.activeMs>0);await collapsed(np);await noOverflow(np);await fullshot(np,`${size}-numeric-incorrect-collapsed`);await np.locator('.original-first-marking summary').press('Enter');await fullshot(np,`${size}-numeric-original-expanded`);await np.locator('.original-first-marking summary').press('Enter');await fill(np,nf,ng);await np.getByRole('button',{name:'Check correction',exact:true}).click();await np.locator('.correction-feedback').waitFor();await flush(np);assert.deepEqual((await snap(np)).attempt.firstResponse,nfirst.attempt.firstResponse);assert.deepEqual((await snap(np)).attempt.firstAssessment,nfirst.attempt.firstAssessment);await fullshot(np,`${size}-numeric-correction`);await np.getByRole('button',{name:'Show worked answer',exact:true}).click();await fullshot(np,`${size}-numeric-model`);await np.reload();await np.locator('.worked-answer').waitFor();await flush(np);assert.deepEqual((await snap(np)).attempt.firstResponse,nfirst.attempt.firstResponse);assert.equal((await np.evaluate(()=>window.__mastersActivity.history())).length,1);await np.getByRole('button',{name:'Next question',exact:true}).click();await np.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,nfirst.attempt.attemptId);assert.equal((await snap(np)).attempt.phase,'answering');assert.equal((await snap(np)).attempt.timing.finished,false);report.checks.push({size,case:'numeric',collapsedKeyboard:true,immutable:true,restoreDedup:true,freshNext:true});await nc.close();
  // Both curriculum explanation levels; original point selection, evidence, completed state.
  for(const rf of all.filter(f=>f.source.family==='comparison')){const rc=await b.newContext({viewport,hasTouch:size==='mobile'}),rp=await start(rc,rf);await fullshot(rp,`${size}-${rf.ref.questionId}-unanswered`);const locked=await review(rp,true);assert.equal(locked.firstAssessment,undefined);assert.equal(locked.timing,undefined);assert.equal((await rp.evaluate(()=>window.__mastersActivity.history())).length,0);await fullshot(rp,`${size}-${rf.ref.questionId}-self-review`);await finish(rp,true);const marked=await snap(rp);assert.equal(marked.attempt.firstAssessment.marks.earned,marked.attempt.firstAssessment.marks.available);assert.deepEqual(marked.attempt.firstResponse,locked.firstResponse);assert.equal(await rp.getByRole('button',{name:'Finish marking',exact:true}).count(),0);assert.equal(await rp.locator('.decision:enabled').count(),0);assert((await rp.locator('.answer-card .instruction').innerText()).includes('Marking complete'));assert((await rp.locator('.mark-footer').innerText()).includes('Marking complete'));await collapsed(rp);await noOverflow(rp);await fullshot(rp,`${size}-${rf.ref.questionId}-completed-collapsed`);await rp.locator('.original-first-marking summary').press('Enter');await fullshot(rp,`${size}-${rf.ref.questionId}-completed-expanded`);await rp.locator('.original-first-marking summary').press('Enter');await rp.getByRole('button',{name:'Show worked answer',exact:true}).click();await fullshot(rp,`${size}-${rf.ref.questionId}-model`);await rp.reload();await rp.locator('.worked-answer').waitFor();await flush(rp);assert.equal(await rp.getByRole('button',{name:'Finish marking',exact:true}).count(),0);assert.deepEqual((await snap(rp)).attempt.firstAssessment,marked.attempt.firstAssessment);assert.equal((await rp.evaluate(()=>window.__mastersActivity.history())).length,1);report.checks.push({size,case:rf.ref.questionId,keyboardEvidence:true,completed:true,collapsedKeyboard:true,immutable:true,restoreDedup:true});await rc.close();}
 }
 // Actual revision selection/scheduler; choose source comparison, use fresh selected question.
 const rf=all.find(f=>f.source.family==='comparison'),rc=await b.newContext({viewport:{width:820,height:1180}}),rp=await start(rc,rf,'revision');assert.equal((await snap(rp)).session.kind,'revision');const locked=await review(rp,true);await rp.locator('.decision.yes:enabled').click();await flush(rp);await rp.reload();await rp.locator('.keyboard-evidence').waitFor();await flush(rp);const restored=await snap(rp);assert.deepEqual(restored.attempt.firstResponse,locked.firstResponse);await rp.locator('.keyboard-evidence summary').click();await rp.getByLabel('Start',{exact:true}).fill('0');await rp.getByLabel('End (exclusive)',{exact:true}).fill(String(restored.attempt.reviews[0].lockedText.length));await rp.getByRole('button',{name:'Use selected text',exact:true}).click();for(const point of restored.question.parts[0].rubric.slice(1))await rp.locator('.decision.no:enabled').click();await rp.getByRole('button',{name:'Finish marking',exact:true}).click();await rp.locator('.assessment-feedback').waitFor();await flush(rp);assert.equal((await snap(rp)).attempt.firstAssessment.marks.earned,1);assert.deepEqual((await snap(rp)).attempt.firstResponse,locked.firstResponse);await fullshot(rp,'revision-completed');await rp.reload();await rp.locator('.assessment-feedback').waitFor();assert.equal((await rp.evaluate(()=>window.__mastersActivity.history())).length,1);await rp.getByRole('button',{name:'Next question',exact:true}).click();await rp.waitForFunction(id=>window.__mastersActivity.snapshot().attempt.attemptId!==id,locked.attemptId);assert.equal((await snap(rp)).session.kind,'revision');assert.equal((await snap(rp)).attempt.timing.finished,false);report.checks.push({case:'revision',lockedEvidenceReload:true,immutable:true,dedup:true,schedulerFreshNext:true});await rc.close();
 // Current teacher rendered samples across all11 curriculum activities; evidence remains empty.
 for(const activity of [...new Set(all.map(f=>f.activity))]){const f=all.find(f=>f.activity===activity),tc=await b.newContext({viewport:{width:390,height:844},hasTouch:true}),tp=await tc.newPage();tp.on('pageerror',e=>report.errors.push(e.message));await tp.goto(`http://127.0.0.1:5188/${f.course}.html?view=teacher&activity=${f.activity}&review=${f.ref.questionId}&level=${f.ref.level}&seed=${f.ref.seed}&run=f12-teacher`);await tp.locator('.question-player').waitFor();await flush(tp);assert.equal((await snap(tp)).attempt,null);assert.equal((await tp.evaluate(()=>window.__mastersActivity.history())).length,0);await noOverflow(tp);await fullshot(tp,'teacher-mobile-'+f.ref.questionId);report.checks.push({case:'teacher',activity,evidenceZero:true});await tc.close();}
 assert.equal(report.errors.length,0);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,shots:report.shots.length,errors:report.errors,failure:report.failure}))}
