import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {productionRegistry} from '../../../../src/foundation/registry.ts';
const here=import.meta.dirname,app=path.resolve(here,'../../../..'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.f12-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const all=JSON.parse(fs.readFileSync(path.join(here,'fixtures.json'))),fixtures=all.filter(f=>['acid','calorimetry','bond','bonding','energy','practical'].includes(f.source.family)&&!f.question.parts.some(p=>p.kind==='energy-profile'));
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={agentId:'F12',jobId:'F3-INDEPENDENT',status:'RUNNING',startedAt:new Date().toISOString(),checks:[],shots:[],errors:[],limits:['Fresh synthetic app IndexedDB namespaces and nonpersistent contexts only.','Native OS suspend/minimize coverage retained by foreman; this browser suite checks reload and first timing.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.locator('.source-player').screenshot({path:path.join(here,name+'.png')});report.shots.push(name+'.png')}
async function start(c,f,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5188/${f.course}.html?run=f12-independent-${Date.now()}-${Math.random().toString(36).slice(2)}`);await p.locator('.original-landing').waitFor({state:'attached'});
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();if(f.course==='alevel'&&f.gem.startsWith('u6'))await p.locator('#flipYear').click();const gem=p.locator('[data-leaf="'+f.gem+'"]').first();await gem.locator('xpath=ancestor::*[contains(@class,"topic-section")]').locator('.topic-trigger').click();await gem.click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click()}
 else{await p.evaluate(gem=>location.hash=gem,f.gem);await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${f.ref.level}"]`).click()}
 await p.locator('.question-player').waitFor();await flush(p);
 if(mode!=='revision'&&((await snap(p)).question.ref.questionId!==f.ref.questionId|| (await snap(p)).question.ref.level!==f.ref.level)){await p.evaluate(async f=>{const s=window.__mastersActivity.snapshot(),{productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const a=productionRegistry.get(f.activity),provider=await a.provider();provider.restore(f.ref);const id=crypto.randomUUID(),target={...s.attempt.target,gemId:f.gem,level:f.ref.level},attempt={...s.attempt,attemptId:id,ref:f.ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{...s.attempt.timing,attemptId:id,activeMs:0,finished:false}};const session={...s.session,currentAttemptId:id,...(s.session.kind==='practice'?{target,previousQuestionIds:[f.ref.questionId]}:{})};const repo=createChemistryRepository(s.databaseName),saved=await repo.saveCurriculum({attempt,session,question:provider.restore(f.ref),namespace:attempt.namespace});if(!saved.ok)throw Error(JSON.stringify(saved));repo.close?.()},f);await p.reload();await p.locator('.source-player').waitFor();await flush(p)}
 if(mode!=='revision')assert.equal((await snap(p)).question.ref.questionId,f.ref.questionId);return p;
}
function answers(f){const out={};for(const part of f.question.parts){if(part.kind==='numeric')out[part.id]={kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit};if(part.kind==='text')out[part.id]={kind:'text',value:part.accepted[0]};if(part.kind==='choice')out[part.id]={kind:'choice',selected:part.acceptedOptionSets[0]};if(part.kind==='correction'){const s=part.segments.find(x=>x.id===f.source.practical.correction.errorId);out[part.id]={kind:'correction',selections:[s],replacement:f.source.practical.fields[0].answers[0]}}}return out}
async function fill(p,f,data){for(const part of f.question.parts){const r=data[part.id];if(!r)continue;if(r.kind==='numeric'){const inputs=p.locator('.response-input');await inputs.nth(f.question.parts.filter(x=>x.kind==='numeric').findIndex(x=>x.id===part.id)).fill(r.raw)}else if(r.kind==='text'){await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.value)}else if(r.kind==='choice'){const field=p.locator('.choice-field,.choice-box').filter({has:p.getByText(f.source.fields[part.id].label,{exact:true})});if(f.source.family==='practical'){for(const selected of r.selected)await field.getByText(selected,{exact:true}).click()}else{for(const selected of r.selected)await field.getByRole('button').filter({hasText:selected}).click()}}else if(r.kind==='correction'){await p.getByRole('button',{name:r.selections[0].text.trim(),exact:true}).click();await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.replacement)}}await flush(p)}
async function wrong(f,correct){const a=productionRegistry.get(f.activity),policy=await a.marking();for(const part of f.question.parts){const v=correct[part.id];const candidates=part.kind==='numeric'?['999999']:part.kind==='choice'?part.options.map(o=>o.id).filter(id=>!v.selected.includes(id)):part.kind==='correction'?['increases','wrong']:['0','1','2','3','4','5','6','proton','neutron','ionic','covalent','metallic','endothermic','exothermic','positive','negative','wrong'];for(const x of candidates){const copy=structuredClone(correct);copy[part.id]=v.kind==='numeric'?{...v,raw:x}:v.kind==='choice'?{...v,selected:v.selected.length===1?[x]:[x,...v.selected.slice(1)]}:v.kind==='correction'?{...v,replacement:x}:{...v,value:x};const outcome=policy.mark(f.question,copy);if(outcome.accepted&&outcome.marks.earned<outcome.marks.available)return copy}}throw Error('No meaningful wrong fixture '+f.ref.questionId)}

async function review(p,met){const q=(await snap(p)).question,part=q.parts[0];for(const section of part.sections)await p.locator('[id$="-'+section.id+'"]').fill(part.rubric.map(r=>r.text).join(' '));await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.locator('.locked-answer').waitFor();await flush(p);return (await snap(p)).attempt}
async function finish(p,met){const a=(await snap(p)).attempt;for(const point of (await snap(p)).question.parts[0].rubric){if(!met)await p.locator('.decision.no:enabled').click();else{await p.locator('.decision.yes:enabled').click();await p.locator('.keyboard-evidence summary').click();await p.getByLabel('Start',{exact:true}).fill('0');await p.getByLabel('End (exclusive)',{exact:true}).fill(String(a.reviews[0].lockedText.length));await p.getByRole('button',{name:'Use selected text',exact:true}).click()}}await p.getByRole('button',{name:'Finish marking',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await flush(p)}
async function fullshot(p,name){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(here,name+'.png'),fullPage:true});report.shots.push(name+'.png')}
async function noOverflow(p){assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth));}
async function collapsed(p){const detail=p.locator('.original-first-marking'),summary=detail.locator('summary');assert.equal(await detail.count(),1);assert.equal(await detail.getAttribute('open'),null);assert(await p.locator('.assessment-feedback .score').isVisible());await summary.focus();await summary.press('Enter');assert.notEqual(await detail.getAttribute('open'),null);assert(await detail.locator('.mark-list').isVisible());await summary.press('Space');assert.equal(await detail.getAttribute('open'),null);}
try{
 for(const size of ['desktop','tablet','mobile']){const viewport={desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}}[size];
  const f=all.find(f=>f.question.parts[0].kind==='energy-profile'),c=await b.newContext({viewport,hasTouch:size==='mobile'}),p=await start(c,f);await fullshot(p,'current-'+size+'-energy-unanswered');await p.evaluate(async f=>{for(const [part,response]of Object.entries(f.source.modelResponses))await window.__mastersActivity.respond(part,response)},f);await flush(p);await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await flush(p);const first=await snap(p);assert.equal(first.attempt.firstAssessment.marks.earned,first.attempt.firstAssessment.marks.available);const metrics=await p.locator('.pupil-answer-actions').evaluate(e=>({wrap:getComputedStyle(e).flexWrap,width:e.getBoundingClientRect().width,buttons:[...e.children].map(x=>({text:x.textContent,width:x.getBoundingClientRect().width,y:x.getBoundingClientRect().y}))}));assert.equal(metrics.wrap,'wrap');assert(metrics.buttons.every(x=>x.width<=metrics.width+1));await noOverflow(p);await fullshot(p,'current-'+size+'-energy-correct');await p.getByRole('button',{name:'Show worked answer',exact:true}).click();await fullshot(p,'current-'+size+'-energy-model');assert.deepEqual((await snap(p)).attempt.firstResponse,first.attempt.firstResponse);report.checks.push({case:'affected-embedded-energy-actions',size,id:f.ref.questionId,metrics,firstScoreFrozen:true});await c.close();
  for(const sf of all.filter(f=>['electron','titration'].includes(f.source.family))){const tc=await b.newContext({viewport,hasTouch:size==='mobile'}),tp=await tc.newPage();await tp.goto(`http://127.0.0.1:5188/${sf.course}.html?view=teacher&activity=${sf.activity}&review=${sf.ref.questionId}&level=${sf.ref.level}&seed=${sf.ref.seed}&run=f12-specialist`);await tp.locator('.source-player').waitFor();await flush(tp);assert.equal((await snap(tp)).attempt,null);await noOverflow(tp);await fullshot(tp,'current-'+size+'-'+sf.source.family+'-model');report.checks.push({case:'specialist-current-model',size,family:sf.source.family,evidenceZero:true});await tc.close();}
  for(const rf of all.filter(f=>f.source.family==='comparison')){const rc=await b.newContext({viewport,hasTouch:size==='mobile'}),rp=await start(rc,rf),part=rf.question.parts[0];const values={'left-bonding':'Covalent bonding','left-structure':'Simple molecular structure','left-property':'The intermolecular forces between water molecules are weak.','right-bonding':'Ionic bonding','right-structure':'Giant lattice structure','right-property':'Strong electrostatic attractions act between oppositely charged sodium ions and chloride ions.','comparison':'Less energy is needed to overcome the intermolecular forces in water, so water has the lower melting point.','answer':'Water has covalent bonding and a simple molecular structure. Sodium chloride has ionic bonding and a giant lattice structure. The intermolecular forces between water molecules are weak. Strong electrostatic attractions act between oppositely charged sodium ions and chloride ions. Less energy is needed to overcome the intermolecular forces in water, so water has the lower melting point.'};for(const s of part.sections)await rp.locator('[id$="-'+s.id+'"]').fill(values[s.id]);await rp.getByRole('button',{name:'Check answer',exact:true}).click();await rp.locator('.locked-answer').waitFor();await flush(rp);const text=(await snap(rp)).attempt.reviews[0].lockedText;const ranges=part.sections.length===1?['Water has covalent bonding and a simple molecular structure.','Sodium chloride has ionic bonding and a giant lattice structure.','The intermolecular forces between water molecules are weak.','Strong electrostatic attractions act between oppositely charged sodium ions and chloride ions.',values.comparison]:['Covalent bonding\n\nSimple molecular structure','Ionic bonding\n\nGiant lattice structure',values['left-property'],values['right-property'],values.comparison];
   for(const [i,point]of part.rubric.entries()){await rp.locator('.decision.yes:enabled').click();await rp.locator('.keyboard-evidence summary').click();let phrase=ranges[i],start=text.indexOf(phrase);if(start<0){phrase=i===0?'Covalent bonding':i===1?'Ionic bonding':ranges[i];start=text.indexOf(phrase);}assert(start>=0,phrase+' in '+text);await rp.getByLabel('Start',{exact:true}).fill(String(start));await rp.getByLabel('End (exclusive)',{exact:true}).fill(String(start+phrase.length));await rp.getByRole('button',{name:'Use selected text',exact:true}).click()}
   await rp.getByRole('button',{name:'Finish marking',exact:true}).click();await rp.locator('.assessment-feedback').waitFor();await collapsed(rp);assert.equal(await rp.getByRole('button',{name:'Finish marking',exact:true}).count(),0);await noOverflow(rp);await fullshot(rp,'current-'+size+'-'+rf.ref.questionId+'-natural-completed');report.checks.push({case:'representative-natural-rubric',size,id:rf.ref.questionId,preciseKeyboardEvidence:true});await rc.close();}
 }report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'current-render-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,shots:report.shots.length,failure:report.failure}))}
