import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';
const here=import.meta.dirname,app=path.resolve(here,'../../../..'),json=f=>JSON.parse(fs.readFileSync(path.join(here,f))),hash=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const suites=['boundary-results.json','coverage.json','audit-final.json','timing-continuity.json','source-closure.json','browser-results.json','current-render-results.json','production-results.json','pause-stats-results.json','stats-browser.json','written-source-results.json','numeric-source-results.json','rubric-source-results.json'];for(const f of suites)assert.equal(json(f).status,'PASS',f);
const freeze=JSON.parse(fs.readFileSync(path.join(app,'validation/component-fidelity/f3/shared-final/freeze.json')));for(const f of freeze.files)assert.equal(hash(path.join(app,f.file)),f.sha256);
const screenshots=['mobile-EE-unanswered.png','mobile-numeric-correction.png','current-desktop-SBC-UFFEIZ-natural-completed.png','current-mobile-SBC-U5FSU0-natural-completed.png','current-mobile-energy-correct.png','current-desktop-titration-model.png','current-tablet-electron-model.png','production-pause-resume-stats.png'];
const evidence=[...suites,'tests.log','HANDOVER.md',...screenshots].map(f=>({path:f,sha256:hash(path.join(here,f))}));
const report={jobId:'F3-INDEPENDENT',agentId:'F12',parent:'F07',status:'PASS',completedAt:new Date().toISOString(),unresolved:[],sourceFreeze:freeze,validation:{domainTests:14,currentBrowserChecks:json('browser-results.json').checks.length,currentFullPageCaptures:json('browser-results.json').shots.length,affectedSpecialistAndRenderChecks:json('current-render-results.json').checks.length,currentSpecialistAndNaturalCaptures:json('current-render-results.json').shots.length,productionEntries:2,statsWidths:3,originalSourceCases:42,sourceCorpusRecords:929,curriculumActivities:11,sourceInputs:308,sourceUnchanged:305,sourceChanged:3,preservedEditorAssetInputs:90,originalReadableHashes:794,metadataOnlyPlaceholders:523,placeholderContentReads:0,protectedFinal:true,firstTimingStatsTransferMs:3576},evidence,dispositions:['Copied-import-depth fixture corrected; rawfailure retained.','Production database run selector corrected to discover isolated actualv2 store; rawfailure retained.','Sourceclosure excludes generatedrelease manifests under separate releasegate; rawfailure retained.','Freshmap practice launch distinguished from genuine savedview continuation; strict savedidentity equality passed; rawfailure retained.'],limits:['No new native OS suspension/minimisation/hidden exposure claim; headless focusprobe did not exposeinactive state. Exact retained native evidence independently verifies applicableunchanged clock/binding.','Historical specialist matrices remain historical; scoped source applicability plus current representative renders/affectedEEactions checked.','External original-app-check summary regeneration exception retained with actualfingerprints.','Concurrent foreignOLY content ignored; totalregistry13 participates only in shared build/source closure.','Root owns finalacceptance; foreman type/build/release/C3integration evidence separate; no publication.'],requestedModel:'gpt-6.1-sol',requestedEffort:'high',effectiveModel:null,effectiveEffort:null,usage:null};
fs.writeFileSync(path.join(here,'report.json'),JSON.stringify(report,null,2));
const manifest={jobId:'F3-INDEPENDENT',agentId:'F12',status:'PASS',output:'validation/component-fidelity/f3/independent/HANDOVER.md',confidence:0.96,reason:null,validation:{status:'PASS',report:'validation/component-fidelity/f3/independent/report.json',domainTests:14,currentBrowserChecks:24,currentAffectedSpecialistAndRenderChecks:15,productionEntries:2,sourceCorpusRecords:929,originalProtected:true,unresolved:0},actualModel:null,usage:null};fs.writeFileSync(path.join(here,'completion.json'),JSON.stringify(manifest,null,2));console.log(JSON.stringify(manifest));
