import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {productionRegistry} from '../../../../src/foundation/registry.ts';
const here=import.meta.dirname,app=path.resolve(here,'../../../..'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.f12-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const all=JSON.parse(fs.readFileSync(path.join(here,'fixtures.json'))),fixtures=all.filter(f=>['acid','calorimetry','bond','bonding','energy','practical'].includes(f.source.family)&&!f.question.parts.some(p=>p.kind==='energy-profile'));
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={agentId:'F12',jobId:'F3-INDEPENDENT',status:'RUNNING',startedAt:new Date().toISOString(),checks:[],shots:[],errors:[],limits:['Fresh synthetic app IndexedDB namespaces and nonpersistent contexts only.','Native OS suspend/minimize coverage retained by foreman; this browser suite checks reload and first timing.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.locator('.source-player').screenshot({path:path.join(here,name+'.png')});report.shots.push(name+'.png')}
async function start(c,f,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5188/${f.course}.html?run=f12-source-independent-${Date.now()}-${Math.random().toString(36).slice(2)}`);await p.locator('.original-landing').waitFor({state:'attached'});
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();if(f.course==='alevel'&&f.gem.startsWith('u6'))await p.locator('#flipYear').click();const gem=p.locator('[data-leaf="'+f.gem+'"]').first();await gem.locator('xpath=ancestor::*[contains(@class,"topic-section")]').locator('.topic-trigger').click();await gem.click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click()}
 else{await p.evaluate(gem=>location.hash=gem,f.gem);await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${f.ref.level}"]`).click()}
 await p.locator('.question-player').waitFor();await flush(p);
 if((await snap(p)).question.ref.questionId!==f.ref.questionId|| (await snap(p)).question.ref.level!==f.ref.level){await p.evaluate(async f=>{const s=window.__mastersActivity.snapshot(),{productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts');const a=productionRegistry.get(f.activity),provider=await a.provider();provider.restore(f.ref);const id=crypto.randomUUID(),target={...s.attempt.target,gemId:f.gem,level:f.ref.level},attempt={...s.attempt,attemptId:id,ref:f.ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{...s.attempt.timing,attemptId:id,activeMs:0,finished:false}};const session={...s.session,currentAttemptId:id,...(s.session.kind==='practice'?{target,previousQuestionIds:[f.ref.questionId]}:{})};const repo=createChemistryRepository(s.databaseName),saved=await repo.saveCurriculum({attempt,session,question:provider.restore(f.ref),namespace:attempt.namespace});if(!saved.ok)throw Error(JSON.stringify(saved));repo.close?.()},f);await p.reload();await p.locator('.source-player').waitFor();await flush(p)}
 assert.equal((await snap(p)).question.ref.questionId,f.ref.questionId);return p;
}
function answers(f){const out={};for(const part of f.question.parts){if(part.kind==='numeric')out[part.id]={kind:'numeric',raw:String(part.acceptance.expected),unit:part.unit};if(part.kind==='text')out[part.id]={kind:'text',value:part.accepted[0]};if(part.kind==='choice')out[part.id]={kind:'choice',selected:part.acceptedOptionSets[0]};if(part.kind==='correction'){const s=part.segments.find(x=>x.id===f.source.practical.correction.errorId);out[part.id]={kind:'correction',selections:[s],replacement:f.source.practical.fields[0].answers[0]}}}return out}
async function fill(p,f,data){for(const part of f.question.parts){const r=data[part.id];if(!r)continue;if(r.kind==='numeric'){const inputs=p.locator('.response-input');await inputs.nth(f.question.parts.filter(x=>x.kind==='numeric').findIndex(x=>x.id===part.id)).fill(r.raw)}else if(r.kind==='text'){await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.value)}else if(r.kind==='choice'){const field=p.locator('.choice-field,.choice-box').filter({has:p.getByText(f.source.fields[part.id].label,{exact:true})});if(f.source.family==='practical'){for(const selected of r.selected)await field.getByText(selected,{exact:true}).click()}else{for(const selected of r.selected)await field.getByRole('button').filter({hasText:selected}).click()}}else if(r.kind==='correction'){await p.getByRole('button',{name:r.selections[0].text.trim(),exact:true}).click();await p.getByLabel(f.source.fields[part.id].label,{exact:true}).fill(r.replacement)}}await flush(p)}
async function wrong(f,correct){const a=productionRegistry.get(f.activity),policy=await a.marking();for(const part of f.question.parts){const v=correct[part.id];const candidates=part.kind==='numeric'?['999999']:part.kind==='choice'?part.options.map(o=>o.id).filter(id=>!v.selected.includes(id)):part.kind==='correction'?['increases','wrong']:['0','1','2','3','4','5','6','proton','neutron','ionic','covalent','metallic','endothermic','exothermic','positive','negative','wrong'];for(const x of candidates){const copy=structuredClone(correct);copy[part.id]=v.kind==='numeric'?{...v,raw:x}:v.kind==='choice'?{...v,selected:v.selected.length===1?[x]:[x,...v.selected.slice(1)]}:v.kind==='correction'?{...v,replacement:x}:{...v,value:x};const outcome=policy.mark(f.question,copy);if(outcome.accepted&&outcome.marks.earned<outcome.marks.available)return copy}}throw Error('No meaningful wrong fixture '+f.ref.questionId)}

const {acidSourceQuestion}=await import('../../../../src/activities/alevel/acid-base-calculations/provider.ts');const {calorimetrySource}=await import('../../../../src/activities/igcse/calorimetry/provider.ts');const {bondCodec}=await import('../../../../src/chemistry/thermochemistry/identity.ts');const {bondSource}=await import('../../../../src/activities/igcse/bond-enthalpy/provider.ts');
async function native(c,f){const p=await c.newPage();const slug=f.activity.split('/')[1],url='http://127.0.0.1:5197/'+f.course+'/activities/'+slug+'/index.html';
 if(f.source.family==='acid'){const raw=acidSourceQuestion(f.ref);await p.addInitScript(({f,raw})=>{localStorage.setItem('alevel-acid-levels-session-v2',JSON.stringify({schema:2,routeKey:f.gem+':level:'+f.ref.level,leafId:f.gem,practice:'level',fixedLevel:f.ref.level,cycles:{},current:{id:'source-fixture',level:f.ref.level,templateId:raw.templateId,seed:f.ref.seed,responses:[],working:'',submitted:false,recorded:false,score:null,completedAt:null}}))},{f,raw});await p.goto(url+'?leaf='+f.gem+'&practice=level&level='+f.ref.level)}
 else {await p.goto(url+'?mode=pupil&practice=grade&grade='+f.ref.level);await p.locator('#checkPupilAnswer').waitFor();const raw=f.source.family==='bond'?bondSource(f.ref.questionId):calorimetrySource(f.ref.questionId);const payload=await p.evaluate(({slug,level,raw})=>{const key=slug+'-practice-grade-'+level+'-v1',s=JSON.parse(localStorage.getItem(key));s.current={...s.current,grade:level,family:slug==='bond-enthalpy'?raw.questionType:raw.example.setup+'-'+raw.config.target,seed:Math.floor(raw.seed/(slug==='bond-enthalpy'?1024:262144)),config:raw.config,submitted:false,assisted:false,responses:[],correct:[],eligible:false,scaffoldParts:[],selfCheck:null};return {key,s}},{slug,level:f.ref.level,raw:{...raw,config:raw.config??bondCodec.decode(f.ref.questionId).config}});await p.addInitScript(({key,s})=>localStorage.setItem(key,JSON.stringify(s)),payload);await p.reload()}
 await p.locator('.response-input').first().waitFor();await p.evaluate(()=>document.fonts.ready);return p;
}
async function fillnative(p,f,r){for(const [i,part] of f.question.parts.filter(x=>x.kind==='numeric').entries())await p.locator('.response-input').nth(i).fill(Number(r[part.id].raw).toPrecision(3))}
async function shotnative(p,f,name,model=false){const sel=model?(f.source.family==='acid'?'#practiceScreen':'.review-stack'):'#questionPanel';await p.locator(sel).screenshot({path:path.join(here,name+'.png')});report.shots.push(name+'.png')}
try{for(const size of ['desktop','tablet','mobile']){const viewport={desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}}[size];for(const family of ['acid','calorimetry','bond']){const f=all.find(f=>f.source.family===family),tag=size+'-'+f.ref.questionId,c=await b.newContext({viewport}),p=await native(c,f),good=answers(f),bad=await wrong(f,good);
 console.log('SOURCE',tag,(await p.locator('#questionPanel').innerText()).slice(0,600),'EXPECTED',f.question.context[0].text);if(f.source.family==='bond')assert.equal(await p.locator('#questionPanel .reaction-diagram svg').count(),1);else assert((await p.locator('#questionPanel').innerText()).includes(f.question.context[0].text));await shotnative(p,f,'native-'+tag+'-unanswered');const first={...f,question:{...f.question,parts:[f.question.parts[0]]}};await fillnative(p,first,good);await shotnative(p,f,'native-'+tag+'-partial');await fillnative(p,f,bad);await p.locator(family==='acid'?'#checkAnswers':'#checkPupilAnswer').click();await shotnative(p,f,'native-'+tag+'-incorrect');await fillnative(p,f,good);await p.locator(family==='acid'?'#checkAnswers':'#checkPupilAnswer').click();await shotnative(p,f,'native-'+tag+'-correction');if(family==='acid')await p.locator('#workedAnswer').evaluate(x=>x.open=true);else await p.locator('#answerPanel').evaluate(x=>x.open=true);await shotnative(p,f,'native-'+tag+'-model',true);await c.close();const cc=await b.newContext({viewport}),cp=await native(cc,f);await fillnative(cp,f,good);await cp.locator(family==='acid'?'#checkAnswers':'#checkPupilAnswer').click();if(f.source.family!=='acid')assert.equal(await cp.locator('.response-input.pupil-incorrect').count(),0);await shotnative(cp,f,'native-'+tag+'-correct');await cc.close();report.checks.push({tag,nativeFinalController:true,matchedRef:true,sixStates:true});console.log('PASS native '+tag)}}report.status='PASS'}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'numeric-source-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,shots:report.shots.length,failure:report.failure}))}
