import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire}from'node:module';
import {calorimetryProvider}from'../../../../src/activities/igcse/calorimetry/provider.ts';
const here=import.meta.dirname,app=path.resolve(here,'../../../..'),require=createRequire(path.resolve(app,'../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(app,'.f12-tmp');
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true}),report={status:'RUNNING',startedAt:new Date().toISOString(),checks:[],errors:[]};
async function rows(page){return page.evaluate(async()=>{const dbs=await indexedDB.databases(),dbinfo=dbs.find(x=>x.name.startsWith('masters-of-chemistry-alpha-v2-igcse-'));if(!dbinfo)return null;return new Promise((resolve,reject)=>{const r=indexedDB.open(dbinfo.name);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,tx=db.transaction(['attempts','evidence','sessions'],'readonly'),out={};for(const s of ['attempts','evidence','sessions']){const rr=tx.objectStore(s).getAll();rr.onsuccess=()=>out[s]=rr.result.map(r=>r.value)}tx.oncomplete=()=>{db.close();resolve({name:dbinfo.name,...out})}}})})}
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(here,name+'.png'),fullPage:true})}
try{for(const entry of ['alevel','igcse']){
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});await context.addInitScript(()=>{localStorage.setItem('masters-of-chemistry-alpha:sentinel','untouched');crypto.getRandomValues=a=>{a.fill(3);return a}});const p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5192/${entry}/?course=igcse&view=home&run=f12-prod-${entry}`);await p.locator('.original-landing.igcse').waitFor();await p.evaluate(()=>location.hash='lower-10-3');await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator('a.practice-choice[data-practice="1"]').tap();await p.locator('.source-calorimetry').waitFor();assert.equal(await p.evaluate(()=>typeof window.__mastersActivity),'undefined');const id=await p.locator('.header-question-code').innerText(),ref=calorimetryProvider.resolveLink(id),q=calorimetryProvider.restore(ref);assert(/CAL-[A-Z0-9]{6}/.test(id));
 for(const input of await p.locator('.response-input').all())await input.fill('999999');await p.getByRole('button',{name:'Check answer',exact:true}).tap();await p.locator('.assessment-feedback').waitFor();await p.waitForTimeout(250);const first=await rows(p);assert(first.name.startsWith('masters-of-chemistry-alpha-v2-'));assert.equal(first.evidence.length,1);const detail=p.locator('.original-first-marking');assert.equal(await detail.getAttribute('open'),null);await detail.locator('summary').focus();await detail.locator('summary').press('Enter');assert.notEqual(await detail.getAttribute('open'),null);await detail.locator('summary').press('Space');await shot(p,`production-${entry}-numeric-collapsed`);
 for(const [i,part]of q.parts.filter(x=>x.kind==='numeric').entries())await p.locator('.response-input').nth(i).fill(String(part.acceptance.expected));await p.getByRole('button',{name:'Check correction',exact:true}).tap();await p.locator('.correction-feedback').waitFor();await p.getByRole('button',{name:'Show worked answer',exact:true}).tap();await p.locator('.worked-answer').waitFor();await shot(p,`production-${entry}-numeric-model`);await p.waitForTimeout(250);const corrected=await rows(p);assert.deepEqual(corrected.evidence,first.evidence);assert.deepEqual(corrected.attempts.find(a=>a.attemptId===first.attempts[0].attemptId).firstResponse,first.attempts[0].firstResponse);await p.reload();await p.locator('.worked-answer').waitFor();const restored=await rows(p);assert.deepEqual(restored.evidence,first.evidence);assert.equal(await p.evaluate(()=>localStorage.getItem('masters-of-chemistry-alpha:sentinel')),'untouched');await p.getByRole('button',{name:'Next question',exact:true}).tap();await p.locator('.source-calorimetry').waitFor();await p.waitForTimeout(250);const next=await rows(p);assert.equal(next.evidence.length,1);assert(next.attempts.some(a=>a.phase==='answering'&&a.timing&&!a.timing.finished));assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth));report.checks.push({entry,id,collapsedKeyboard:true,immutableEvidence:true,firstTiming:first.evidence[0].timing,restoreDedup:true,freshNext:true,oldSentinelUntouched:true,devHarnessAbsent:true});await context.close();
 }assert.deepEqual(report.errors,[]);report.status='PASS';}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'production-results.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));}
