import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { server, project } from '../server.mjs';
const here=import.meta.dirname,require=createRequire(path.join(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');
const temp=path.join(here,'.browser');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const host=server();await new Promise(r=>host.listen(5201,'127.0.0.1',r));
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${temp}/cache`]}),report={startedAt:new Date().toISOString(),browser:await browser.version(),playwright:'1.62.1',checks:[],failures:[],settings:{cpuRate:4,viewport:{width:900,height:900}},pageErrors:[]};
async function durable(page,course){return page.evaluate(async course=>{const db=await new Promise((r,j)=>{const q=indexedDB.open(`masters-of-chemistry-${course}-local`);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});try{const result={};for(const name of ['attempts','sessions','evidence'])result[name]=await new Promise((r,j)=>{const q=db.transaction(name).objectStore(name).getAll();q.onsuccess=()=>r(q.result.map(x=>x.value));q.onerror=()=>j(q.error)});return result}finally{db.close()}},course)}
function current(rows){const session=rows.sessions[0],id=session.kind==='revision'?session.current.attemptId:session.currentAttemptId;return{session,attempt:rows.attempts.find(a=>a.attemptId===id)}}
async function ready(page,course,oldId){await page.waitForFunction(async({course,oldId})=>{const db=await new Promise((r,j)=>{const q=indexedDB.open(`masters-of-chemistry-${course}-local`);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});try{const session=await new Promise(r=>{const q=db.transaction('sessions').objectStore('sessions').get([course,'local','current-session']);q.onsuccess=()=>r(q.result?.value)}),id=session?.kind==='revision'?session.current?.attemptId:session?.currentAttemptId;if(!id||id===oldId)return false;const attempt=await new Promise(r=>{const q=db.transaction('attempts').objectStore('attempts').get([course,'local',id]);q.onsuccess=()=>r(q.result?.value)});return !!attempt&&document.querySelector('.question-meta code')?.textContent===attempt.ref.questionId}finally{db.close()}},{course,oldId},{timeout:10000})}
async function seed(page,course,mode,id){await page.goto('http://127.0.0.1:5201/probe.html');return page.evaluate(async({course,mode,id})=>{const{productionRegistry}=await import('/src/foundation/registry.ts');const{createChemistryRepository}=await import('/src/persistence/repository.ts');const{createCourseMastery}=await import('/src/domain/mastery/index.ts');const{createRevisionSession,revisionScheduler,bindRevisionQuestion}=await import('/src/domain/session/revision.ts');const activityId=course==='alevel'?'alevel/ph-titration-curves':'igcse/energy-enthalpy',reg=productionRegistry.get(activityId),provider=await reg.provider(),gem=reg.gems.find(g=>g.supportedLevels.includes(2)),target={course,activityId,gemId:gem.id,level:2},namespace={course,profileId:'local'},ref=course==='igcse'?{activityId,questionId:'D03',seed:0,level:2}:provider.select({...target,seed:3,previousQuestionIds:[]}),question=provider.restore(ref);let response;
if(course==='igcse'){const{record}=await import('/src/activities/igcse/energy-enthalpy/provider.ts');const{modelProfile}=await import('/src/chemistry/energy-profile/index.ts');response=modelProfile(record(ref.questionId));}else{const{getRecord}=await import('/src/activities/alevel/ph-titration-curves/provider.ts');const{answer}=await import('/src/chemistry/titration-curve/core.js');const a=answer(getRecord(ref.questionId));response={kind:'titration-curve',before:a.before,after:a.after,initialPH:a.initialPH,equivalenceVolume:a.equivalenceVolume,finalPH:a.finalPH,indicator:a.indicator};}
const attempt={mode:'student',namespace,attemptId:id,ref,target,currentResponses:{[question.parts[0].id]:response},assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:reg.idleAllowance(question),finished:false}};let session;
if(mode==='practice')session={kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:id,previousQuestionIds:[ref.questionId],paused:true};else{const summaries=[createCourseMastery(course).summarize([],gem.mastery,2)];session=createRevisionSession({namespace,id:'current-session',selected:[target],settings:[gem.mastery],summaries,now:Date.now()});session=revisionScheduler.next(session,summaries,Date.now(),id);session={...bindRevisionQuestion(session,ref),status:'paused'};}
const repository=createChemistryRepository(`masters-of-chemistry-${course}-local`),saved=await repository.saveCurriculum({attempt,session});repository.close();if(!saved.ok)throw Error(JSON.stringify(saved));return{attempt,session,question};},{course,mode,id})}
async function trustedType(page,input,text){await input.focus();await page.keyboard.press('Control+A');await page.keyboard.press('Backspace');await input.pressSequentially(text,{delay:30});assert.equal(await input.inputValue(),text)}
async function mouseNext(page,count=1){const button=page.getByRole('button',{name:'Next question',exact:true});await button.scrollIntoViewIfNeeded();const box=await button.boundingBox();assert(box);await page.mouse.click(box.x+box.width/2,box.y+box.height/2,{clickCount:count,delay:0})}
try{for(const course of ['alevel','igcse'])for(const mode of ['practice'])for(const scenario of ['dirty-single','dirty-double']){const id=`next-fix-${course}-${mode}-${scenario}`,context=await browser.newContext({viewport:report.settings.viewport}),page=await context.newPage(),cdp=await context.newCDPSession(page);page.on('pageerror',e=>report.pageErrors.push({id,error:e.message}));let diagnostics={};try{
await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await context.addInitScript(()=>{window.oldWrites=[];window.nextEvents=[];window.failAttempt=false;const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...a){if(this.name==='attempts'&&window.failAttempt)throw new DOMException('A21 reversible blur-save quota','QuotaExceededError');return put.apply(this,a)};for(const n of ['setItem','removeItem','clear']){const old=Storage.prototype[n];Storage.prototype[n]=function(...a){window.oldWrites.push([n,...a]);return old.apply(this,a)}}for(const name of ['pointerdown','mousedown','blur','focusout','pointerup','mouseup','click'])document.addEventListener(name,e=>{if(e.target?.matches?.('input')||e.target?.textContent==='Next question')window.nextEvents.push({type:name,trusted:e.isTrusted,target:e.target?.getAttribute?.('aria-label')||e.target?.textContent,nextDisabled:[...document.querySelectorAll('button')].find(b=>b.textContent==='Next question')?.disabled,save:document.querySelector('.save-status')?.textContent,at:performance.now()})},true)});
const fixture=await seed(page,course,mode,id);diagnostics.fixture=fixture;await page.goto(`http://127.0.0.1:5201/stage-s5/${course}/index.html?view=${mode}`);await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await page.locator('.question-player').waitFor();assert.equal(await page.locator('.question-meta code').innerText(),fixture.attempt.ref.questionId);await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.getByRole('button',{name:'Next question',exact:true}).waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();let before=await durable(page,course);const first=current(before).attempt;diagnostics.before=before;assert.equal(first.phase,'assessed');assert.equal(first.firstAssessment.score,1);assert.equal(before.evidence.length,1);assert(first.firstResponse.timing.activeMs>=0);if(scenario==='normal'){await page.getByRole('button',{name:'Pause and save',exact:true}).click();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Next question',exact:true}).count(),0);const pausedFirst=await durable(page,course);assert.equal(current(pausedFirst).attempt.attemptId,id);assert.deepEqual(current(pausedFirst).attempt.firstResponse,first.firstResponse);await page.reload();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();assert.deepEqual(await durable(page,course),pausedFirst);await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await page.getByRole('button',{name:'Next question',exact:true}).waitFor();await page.getByText('Saved on this device',{exact:true}).waitFor();before=await durable(page,course);}
const label=course==='igcse'?'Peak level screen y':'Initial pH',input=page.getByLabel(label,{exact:true}),draft=course==='igcse'?'270':String(Number((first.currentResponses.curve.initialPH+.1).toFixed(1)));
if(scenario!=='normal'){const oldValue=await input.inputValue();assert.notEqual(draft,oldValue);await trustedType(page,input,draft);assert.equal(current(await durable(page,course)).attempt.currentResponses[course==='igcse'?'profile':'curve'][course==='igcse'?'peak':'initialPH'],first.currentResponses[course==='igcse'?'profile':'curve'][course==='igcse'?'peak':'initialPH']);}
if(scenario==='dirty-quota')await page.evaluate(()=>window.failAttempt=true);await mouseNext(page,scenario==='dirty-double'?2:1);
if(scenario==='dirty-quota'){await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();const failed=await durable(page,course);assert.deepEqual(failed,before);assert.equal(current(failed).attempt.attemptId,id);assert.equal(await page.getByRole('button',{name:'Next question',exact:true}).isEnabled(),false);await mouseNext(page);assert.deepEqual(await durable(page,course),before);await page.evaluate(()=>window.failAttempt=false);await page.getByRole('button',{name:'Retry save',exact:true}).click();await page.getByText('Saved on this device',{exact:true}).waitFor();assert.equal(current(await durable(page,course)).attempt.attemptId,id);assert.equal(current(await durable(page,course)).attempt.currentResponses[course==='igcse'?'profile':'curve'][course==='igcse'?'peak':'initialPH'],Number(draft));assert.equal(await page.getByRole('button',{name:'Next question',exact:true}).isEnabled(),true);await mouseNext(page);}
await ready(page,course,id);const after=await durable(page,course),next=current(after).attempt,old=after.attempts.find(a=>a.attemptId===id);diagnostics.after=after;diagnostics.afterDOM=await page.evaluate(()=>({code:document.querySelector('.question-meta code')?.textContent,save:document.querySelector('.save-status')?.textContent,nextDisabled:[...document.querySelectorAll('button')].find(b=>b.textContent==='Next question')?.disabled}));diagnostics.events=await page.evaluate(()=>window.nextEvents);fs.writeFileSync(path.join(here,id+'-diagnostic-only.json'),JSON.stringify(diagnostics,null,2)+'\n');assert.equal(after.attempts.length,2);assert.notEqual(next.attemptId,id);assert.equal(next.phase,'answering');assert.equal(next.timing.attemptId,next.attemptId);assert.equal(next.timing.finished,false);assert(next.timing.activeMs<1500);assert.deepEqual(next.currentResponses,{});assert.deepEqual(old.firstResponse,first.firstResponse);assert.deepEqual(old.firstAssessment,first.firstAssessment);assert.deepEqual(old.timing,first.timing);assert.deepEqual(after.evidence,before.evidence);assert.equal(await page.locator('.question-meta code').innerText(),next.ref.questionId);if(mode==='revision'){assert.equal(current(after).session.submittedAttemptIds.filter(x=>x===id).length,1);assert.equal(current(after).session.current.completed,false)}
const newQuestion=await page.evaluate(async ref=>{const{productionRegistry}=await import('/src/foundation/registry.ts');return(await productionRegistry.get(ref.activityId).provider()).restore(ref)},next.ref),newInput=page.getByLabel(label,{exact:true});if(await newInput.count()){const initial=newQuestion.parts.find(p=>p.kind===(course==='igcse'?'energy-profile':'titration-curve'))?.initial;assert(initial);assert.equal(Number(await newInput.inputValue()),initial[course==='igcse'?'peak':'initialPH']);}
const events=await page.evaluate(()=>window.nextEvents);assert.deepEqual(await page.evaluate(()=>window.oldWrites),[]);await page.getByRole('button',{name:'Pause and save',exact:true}).click();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Next question',exact:true}).count(),0);const paused=await durable(page,course);await page.reload();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).waitFor();assert.deepEqual(await durable(page,course),paused);assert.deepEqual(await page.evaluate(()=>window.oldWrites),[]);const nextClicks=events.filter(e=>e.type==='click'&&e.target==='Next question');assert(nextClicks.length>=1&&nextClicks.every(e=>e.trusted));report.checks.push({id,status:'PASS',scenario,course,mode,previousId:id,nextId:next.attemptId,nextRef:next.ref,firstScore:first.firstAssessment.score,firstActiveMs:first.firstResponse.timing.activeMs,newPersistedMs:next.timing.activeMs,immutableFirst:true,singleEvidence:true,exactlyOneNewAttempt:true,localDraftReset:true,quotaBlockedAndRetry:scenario==='dirty-quota',pauseReloadGuard:true,events});console.log('PASS '+id);
}catch(e){diagnostics.error=e.stack;diagnostics.finalRows=await durable(page,course).catch(x=>({error:x.message}));diagnostics.dom=await page.evaluate(()=>({code:document.querySelector('.question-meta code')?.textContent,save:document.querySelector('.save-status')?.textContent,events:window.nextEvents}));fs.writeFileSync(path.join(here,id+'-diagnostic-only.json'),JSON.stringify(diagnostics,null,2)+'\n');report.failures.push({id,error:e.stack,diagnostics:id+'-diagnostic-only.json'});await page.screenshot({path:path.join(here,id+'-failure.png'),fullPage:true}).catch(()=>{});console.log('FAIL '+id+' '+e.message)}finally{await context.close()}}assert.deepEqual(report.pageErrors,[]);}finally{report.status=report.failures.length||report.pageErrors.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'diagnostic-only-results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();await new Promise(r=>host.close(r));console.log(JSON.stringify({status:report.status,checks:report.checks.length,failures:report.failures,pageErrors:report.pageErrors}));if(report.status!=='PASS')process.exitCode=1;}
