import { chromium } from '../../../../../node_modules/playwright/index.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const here=import.meta.dirname,browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),run='specialist-feedback-'+Date.now();
const report={status:'RUNNING',checks:[],failures:[],pageErrors:[]};page.on('pageerror',e=>report.pageErrors.push(e.message));
const snapshot=()=>page.evaluate(()=>window.__mastersActivity.snapshot()),flush=()=>page.evaluate(()=>window.__mastersActivity.flush());
async function ready(){await page.waitForFunction(()=>window.__mastersActivity);await page.waitForFunction(()=>window.__mastersActivity.snapshot().saveStatus.kind!=='saving');}
async function reload(){await page.reload();await ready();if(await page.getByRole('button',{name:'Resume saved attempt',exact:true}).count())await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await page.locator('.question-player').waitFor();await flush();}
async function fixture(activityId){await page.goto(`http://127.0.0.1:5203/alevel.html?run=${run}-${activityId.split('/')[1]}&view=practice&activity=${activityId}`);await ready();await page.evaluate(async activityId=>{const {productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts'),registration=productionRegistry.get(activityId),provider=await registration.provider(),level=1,target={course:'alevel',activityId,gemId:registration.gems[0].id,level},ref=provider.select({activityId,gemId:target.gemId,level,seed:5,previousQuestionIds:[]}),q=provider.restore(ref),id=crypto.randomUUID(),namespace={course:'alevel',profileId:'local'};const attempt={mode:'student',namespace,attemptId:id,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:registration.idleAllowance(q),finished:false}},session={kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:id,previousQuestionIds:[],paused:false};const saved=await createChemistryRepository(window.__mastersActivity.snapshot().databaseName).saveCurriculum({attempt,session});if(!saved.ok)throw Error(saved.error.message);},activityId);await reload();}
async function runCheck(id,fn){try{await fn();report.checks.push({id,status:'PASS'});}catch(error){report.failures.push({id,error:error.stack});await page.screenshot({path:path.join(here,'specialist-failure-'+id+'.png'),fullPage:true});}}
try{
 await runCheck('source-acid-correction-save-reload-next',async()=>{await fixture('alevel/acid-base-calculations');assert.equal(await page.locator('.source-player.source-acid').count(),1);let s=await snapshot();for(const part of s.question.parts)await page.evaluate(async ({id,unit})=>window.__mastersActivity.respond(id,{kind:'numeric',raw:'1.00',unit}),{id:part.id,unit:part.unit});await flush();await page.getByRole('button',{name:'Check',exact:true}).click();await flush();await page.locator('.assessment-feedback').waitFor();const first=await snapshot(),history=await page.evaluate(()=>window.__mastersActivity.history());assert.equal(history.length,1);
  await page.evaluate(async()=>{const {acidSourceQuestion}=await import('/src/activities/alevel/acid-base-calculations/provider.ts');const q=acidSourceQuestion(window.__mastersActivity.snapshot().question.ref);for(const p of q.responses){const raw=p.format==='dp2'?p.expected.toFixed(2):p.format==='dp3'?p.expected.toFixed(3):p.format==='sf3'?p.expected.toPrecision(3):p.format==='sf4'?p.expected.toPrecision(4):Math.round(p.expected).toString();await window.__mastersActivity.respond(p.key,{kind:'numeric',raw,unit:p.unit});}});await flush();await page.getByRole('button',{name:'Check',exact:true}).click();await flush();await page.locator('.correction-feedback').waitFor();assert.equal((await snapshot()).correctionFeedback.status,'correct');assert.equal(await page.getByRole('heading',{name:'Ideal answer'}).count(),0);await reload();assert.equal(await page.locator('.assessment-feedback').count(),1);assert.equal(await page.locator('.source-player').count(),1);assert.deepEqual((await snapshot()).attempt.firstResponse,first.attempt.firstResponse);assert.deepEqual((await snapshot()).attempt.firstAssessment,first.attempt.firstAssessment);assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),history);await page.getByRole('button',{name:'Give Up',exact:true}).click();await flush();await page.getByRole('heading',{name:'Worked answer',exact:true}).waitFor();await page.screenshot({path:path.join(here,'specialist-source-acid.png'),fullPage:true});await page.getByRole('button',{name:'Next',exact:true}).click();await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt?.attemptId!==id,first.attempt.attemptId);await flush();assert.equal((await snapshot()).attempt.phase,'answering');});
 await runCheck('dot-cross-reveal-check-reload-isolation',async()=>{await fixture('alevel/dot-and-cross');await page.locator('.dot-cross-player').waitFor();await page.getByRole('button',{name:'Give Up',exact:true}).click();await flush();await page.locator('.assessment-feedback').waitFor();const first=await snapshot();assert.equal(first.attempt.firstAssessment.kind,'revealed');await page.getByRole('button',{name:'Close answer',exact:true}).click();await page.getByRole('button',{name:'Check',exact:true}).click();await flush();await reload();await page.locator('.dot-cross-player').waitFor();assert.deepEqual((await snapshot()).attempt.firstResponse,first.attempt.firstResponse);assert.deepEqual((await snapshot()).attempt.firstAssessment,first.attempt.firstAssessment);assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,0);assert.equal(await page.getByRole('heading',{name:'Ideal answer'}).count(),0);await page.screenshot({path:path.join(here,'specialist-dot-cross.png'),fullPage:true});});
}finally{report.status=report.failures.length||report.pageErrors.length?'FAIL':'PASS';fs.writeFileSync(path.join(here,'specialist-browser-results.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;}
