import { chromium, devOrigin, outputDirectory } from '../paths.mjs';
import {spawn,spawnSync} from 'node:child_process';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const here=outputDirectory('explaining-properties/native'),run='ebp-author2-'+Date.now(),port=9384,profile=path.join(here,'profile'),delay=ms=>new Promise(r=>setTimeout(r,ms));
const report={jobId:'EBP-FIX-01',agentId:'A01-EBP',startedAt:new Date().toISOString(),run,method:'Root-authorised isolated temporary onscreen Chrome; isolated .artifacts/browser/explaining-properties/native/profile; pinned workspace Playwright connectOverCDP(noDefaults:true). Navigation uses explicitly untrusted DOM change/click; all timing restart inputs use CDP Input and require trusted native events. No visibility, focus, clock or lifecycle property replacement.',events:[],observations:[],checks:[],errors:[]};
fs.mkdirSync(profile,{recursive:true});
const args=[`--user-data-dir=${profile}`,`--remote-debugging-port=${port}`,'--remote-debugging-address=127.0.0.1','--no-first-run','--no-default-browser-check','--disable-extensions','--disable-background-networking','--disable-gpu','--window-position=80,80','--window-size=1440,1000','about:blank'];
const child=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',args,{stdio:['ignore','ignore','pipe'],windowsHide:false});child.stderr.on('data',d=>fs.appendFileSync(path.join(here,'native-stderr.log'),d));
let browser,page;const save=()=>fs.writeFileSync(path.join(here,'native-timing.json'),JSON.stringify(report,null,2)+'\n');
try{
 let ready=false;for(let n=0;n<80;n++){try{const r=await fetch(`http://127.0.0.1:${port}/json/version`);if(r.ok){ready=true;break;}}catch{}await delay(250);}assert(ready,'Chrome endpoint');
 browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`,{noDefaults:true,isLocal:true,artifactsDir:here});report.browserVersion=browser.version();const context=browser.contexts()[0];page=context.pages()[0];report.context='Root-authorised short project-owned isolated persistent profile; default context noDefaults avoids all focus/visibility overrides.';
 await page.exposeBinding('__ebpReviewEvent',(_,v)=>report.events.push(v));await page.addInitScript(()=>{
  const token=crypto.randomUUID(),origin=performance.timeOrigin;window.__ebpReviewDoc={token,origin};
  const emit=e=>queueMicrotask(()=>window.__ebpReviewEvent({event:e.type,trusted:e.isTrusted,wall:Date.now(),mono:performance.now(),token,origin,hidden:document.hidden,focused:document.hasFocus(),attempt:window.__mastersActivity?.snapshot().attempt}));
  for(const type of ['visibilitychange','freeze','resume','keydown','input','pointerdown'])document.addEventListener(type,emit,{capture:true});for(const type of ['focus','blur','pagehide','pageshow'])window.addEventListener(type,emit,{capture:true});
 });
 page.on('pageerror',e=>report.errors.push(e.message));const cdp=await context.newCDPSession(page);const nativeWindow=await cdp.send('Browser.getWindowForTarget');report.nativeWindowBefore=nativeWindow;await cdp.send('Browser.setWindowBounds',{windowId:nativeWindow.windowId,bounds:{windowState:'normal'}});
 const foregroundAction=spawnSync('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(import.meta.dirname,'foreground-owned-chrome.ps1'),'-ChromePid',String(child.pid)],{encoding:'utf8',windowsHide:true});report.ownedNativeForegroundAction={pid:child.pid,status:foregroundAction.status,stdout:foregroundAction.stdout,stderr:foregroundAction.stderr};assert.equal(foregroundAction.status,0,'Owned native window foreground action');
 const observe=async label=>{await page.evaluate(async()=>{await window.__mastersActivity.checkpoint();await window.__mastersActivity.flush();});const o=await page.evaluate(label=>({label,wall:Date.now(),token:window.__ebpReviewDoc.token,origin:performance.timeOrigin,hidden:document.hidden,focused:document.hasFocus(),attempt:window.__mastersActivity.snapshot().attempt}),label);report.observations.push(o);save();return o;};
 const trustedTab=async()=>{await cdp.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await cdp.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});};
 await page.bringToFront();await page.goto(`${devOrigin}/alevel.html?run=${run}&view=practice&activity=alevel/explaining-properties`);await page.waitForFunction(()=>window.__mastersActivity,undefined,{polling:250});
 await page.evaluate(()=>{const target=document.querySelector('select[aria-label="Target"]');if(!target)throw Error('Target selector missing');target.value='l6-t2-1-properties:1';target.dispatchEvent(new Event('change',{bubbles:true}));});
 await page.evaluate(()=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent==='Start practice');if(!button)throw Error('Start practice missing');button.click();});
 await page.waitForFunction(()=>document.querySelector('.question-player')&&window.__mastersActivity.snapshot().attempt?.ref.activityId==='alevel/explaining-properties',undefined,{polling:250});
 await page.bringToFront();await trustedTab();await delay(1300);const foreground=await observe('foreground');assert(!foreground.hidden&&foreground.focused);assert(report.events.some(e=>e.event==='keydown'&&e.trusted&&e.attempt?.attemptId===foreground.attempt.attemptId));assert(foreground.attempt.timing.activeMs>0,'Real EBP timer accrues in foreground after trusted input');
 const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await delay(700);const hidden=await observe('native other tab');assert(hidden.hidden&&!hidden.focused,'native tab must report hidden and not focused');assert(report.events.some(e=>e.event==='visibilitychange'&&e.trusted&&e.hidden&&e.attempt?.attemptId===foreground.attempt.attemptId));await delay(2600);const stable=await observe('background stable');assert.equal(stable.attempt.timing.activeMs,hidden.attempt.timing.activeMs);assert.equal(stable.attempt.attemptId,foreground.attempt.attemptId);assert.equal(stable.token,foreground.token);await page.bringToFront();await delay(1200);assert.equal((await observe('foreground without interaction')).attempt.timing.activeMs,hidden.attempt.timing.activeMs);await trustedTab();await delay(1300);const restarted=await observe('trusted input restart');assert(restarted.attempt.timing.activeMs>hidden.attempt.timing.activeMs);assert(report.events.some(e=>e.event==='visibilitychange'&&e.trusted&&!e.hidden&&e.attempt?.attemptId===foreground.attempt.attemptId));report.checks.push('native-hidden-tab-stop-focus-alone-stop-trusted-restart');await other.close();
 const start=report.events.length;await cdp.send('Page.setWebLifecycleState',{state:'frozen'});await delay(6600);await cdp.send('Page.setWebLifecycleState',{state:'active'});await delay(1000);const after=await observe('native lifecycle thaw');const events=report.events.slice(start),f=events.find(e=>e.event==='freeze'),r=events.find(e=>e.event==='resume');assert(f&&r&&f.trusted&&r.trusted,'trusted native freeze/resume');assert.equal(f.token,r.token);assert.equal(f.origin,r.origin);assert.equal(f.attempt.attemptId,r.attempt.attemptId);assert(r.wall-f.wall>=6500);assert.equal(f.attempt.timing.activeMs,r.attempt.timing.activeMs);assert.equal(after.token,f.token);assert.equal(after.attempt.timing.activeMs,r.attempt.timing.activeMs);report.checks.push('trusted-same-document-native-freeze-resume-zero-accrual');
 report.status='PASS';
}catch(e){report.status='ESCALATE';report.failure={message:e.message,stack:e.stack};if(page){report.failureSnapshot=await page.evaluate(()=>({hidden:document.hidden,focused:document.hasFocus(),snapshot:window.__mastersActivity?.snapshot(),body:document.body.innerText})).catch(()=>null);await page.screenshot({path:path.join(here,'native-failure.png'),fullPage:true}).catch(()=>{});}}
finally{report.finishedAt=new Date().toISOString();save();if(browser){const s=await browser.newBrowserCDPSession().catch(()=>null);if(s)await s.send('Browser.close').catch(()=>{});await browser.close().catch(()=>{});}child.kill();console.log(JSON.stringify({status:report.status,checks:report.checks,failure:report.failure?.message}));}
