import { projectRoot, outputDirectory, devOrigin, previewOrigin, chromium } from '../paths.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const here=outputDirectory('explaining-properties'),run='ebp-time-'+Date.now(),report={status:'RUNNING',run,startedAt:new Date().toISOString(),method:'Actual headless Microsoft Edge, pinned workspace Playwright1.62.1. Real elapsed 180-second idle, observed trusted input/lifecycle events; no clock replacement or synthetic visibility/events.',checks:[],failures:[],observations:[]};
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();await context.addInitScript(()=>{
 window.ebpDocument=crypto.randomUUID();window.ebpEvents=[];
 const record=e=>window.ebpEvents.push({type:e.type,trusted:e.isTrusted,wall:Date.now(),mono:performance.now(),hidden:document.hidden,focused:document.hasFocus(),document:window.ebpDocument,timing:window.__mastersActivity?.snapshot().attempt?.timing});
 for(const type of ['keydown','input','pointerdown','visibilitychange','freeze','resume'])document.addEventListener(type,record,{capture:true,passive:true});
 for(const type of ['blur','focus','pagehide','pageshow'])window.addEventListener(type,record,{capture:true,passive:true});
});
const tail=process.argv.includes('--tail');
const page=await context.newPage(),save=()=>fs.writeFileSync(path.join(here,tail?'timing-tail-results.json':'timing-browser-results.json'),JSON.stringify(report,null,2)+'\n');
const observe=label=>page.evaluate(label=>({label,wall:Date.now(),mono:performance.now(),document:window.ebpDocument,hidden:document.hidden,focused:document.hasFocus(),snapshot:window.__mastersActivity.snapshot(),events:window.ebpEvents}),label);
async function interact(){const input=page.locator('.inline-gap input').first();if(await input.count())await input.fill('ions');else{await page.locator('[data-error-id="phrase-0"]').click();await page.getByLabel('Replacement / correction',{exact:true}).fill('ions');}await page.evaluate(()=>window.__mastersActivity.flush());}
try{
 await page.goto(`${devOrigin}/alevel.html?run=${run}&view=practice&activity=alevel/explaining-properties&gem=l6-t2-1-properties&level=1&fresh=1`);await page.locator('.question-player').waitFor();await interact();
 const start=await observe('idle starts after actual input');report.observations.push(start);assert.equal(start.snapshot.attempt.timing.idleLimitMs,180000);assert(!start.hidden&&start.focused);save();console.log('START actual180-second idle '+new Date().toISOString());
 if(!tail){for(let i=0;i<19;i++)await page.waitForTimeout(10000);
 const idle=await observe('allowance exhausted');await page.waitForTimeout(6500);const plateau=await observe('idle plateau');report.observations.push(idle,plateau);
 assert.equal(plateau.snapshot.attempt.timing.activeMs,idle.snapshot.attempt.timing.activeMs);assert.equal(start.document,idle.document);assert.equal(start.snapshot.attempt.attemptId,idle.snapshot.attempt.attemptId);
 const lastInput=start.events.filter(e=>e.trusted&&['keydown','input','pointerdown'].includes(e.type)).at(-1);assert(lastInput);
 assert.equal(idle.events.filter(e=>e.trusted&&['keydown','input','pointerdown'].includes(e.type)&&e.mono>lastInput.mono).length,0);
 assert(idle.snapshot.attempt.timing.activeMs>=179000&&idle.snapshot.attempt.timing.activeMs<=182000);report.checks.push({id:'actual-180000ms-idle',status:'PASS',activeMs:idle.snapshot.attempt.timing.activeMs,plateauMs:6500,wallSinceInput:idle.wall-lastInput.wall,sameDocument:true});save();console.log('PASS actual idle');}
 else{const prior=JSON.parse(fs.readFileSync(path.join(here,'timing-browser-results.json'),'utf8'));assert(prior.checks.some(c=>c.id==='actual-180000ms-idle'&&c.status==='PASS'));report.checks.push({id:'retained-real-idle',status:'PASS',evidence:'timing-browser-results.json',scope:'Reuses valid real180s idle; subsequent raw lifecycle failure remains retained.'});}
 await interact();await page.waitForTimeout(1600);await page.evaluate(()=>window.__mastersActivity.checkpoint());const before=await observe('before native freeze');
 const cdp=await context.newCDPSession(page);await cdp.send('Page.setWebLifecycleState',{state:'frozen'});await new Promise(resolve=>setTimeout(resolve,8000));await cdp.send('Page.setWebLifecycleState',{state:'active'});await page.waitForTimeout(1600);await page.evaluate(()=>window.__mastersActivity.checkpoint());const after=await observe('after native thaw');report.observations.push(before,after);
 const freeze=after.events.find(e=>e.type==='freeze'&&e.wall>=before.wall),resume=after.events.find(e=>e.type==='resume'&&e.wall>=before.wall);assert.equal(before.document,after.document);
 if(freeze&&resume&&freeze.trusted&&resume.trusted){assert(resume.wall-freeze.wall>=7900);assert(after.snapshot.attempt.timing.activeMs-before.snapshot.attempt.timing.activeMs<1800);report.checks.push({id:'actual-native-suspension',status:'PASS',frozenWallMs:resume.wall-freeze.wall,counterDeltaMs:after.snapshot.attempt.timing.activeMs-before.snapshot.attempt.timing.activeMs,trustedEvents:true});}
 else report.checks.push({id:'actual-native-suspension-capability',status:'UNESTABLISHED',reason:'Page lifecycle command produces no trusted freeze/resume; successful command is not suspension evidence.',counterDeltaMs:after.snapshot.attempt.timing.activeMs-before.snapshot.attempt.timing.activeMs});save();
 await interact();await page.waitForTimeout(1200);await page.evaluate(()=>window.__mastersActivity.checkpoint());const stallBefore=await observe('before actual event-loop stall');const stallWall=Date.now();await page.evaluate(()=>{const until=performance.now()+8000;while(performance.now()<until){/* actual thread stalls; real clocks keep advancing */}});const stallElapsed=Date.now()-stallWall;await page.waitForTimeout(1600);await page.evaluate(()=>window.__mastersActivity.checkpoint());const stallAfter=await observe('after actual event-loop stall');report.observations.push(stallBefore,stallAfter);assert(stallElapsed>=7900);assert.equal(stallAfter.document,stallBefore.document);assert(stallAfter.snapshot.attempt.timing.activeMs-stallBefore.snapshot.attempt.timing.activeMs<1400);report.checks.push({id:'actual-event-loop-suspension-gap',status:'PASS',wallElapsedMs:stallElapsed,counterDeltaMs:stallAfter.snapshot.attempt.timing.activeMs-stallBefore.snapshot.attempt.timing.activeMs,scope:'Actual8s main-thread stall tests >5s suspension-gap cutoff. Does not claim native OS/page freeze.'});save();
 const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await new Promise(resolve=>setTimeout(resolve,6500));const background=await observe('other tab foreground');report.observations.push(background);
 report.checks.push({id:'actual-background-tab-capability',status:background.hidden?'ESTABLISHED':'UNESTABLISHED',hidden:background.hidden,focused:background.focused,reason:background.hidden?null:'Runtime reports every headless tab visible/focused; commands alone are not hidden-tab verification.'});await page.bringToFront();await other.close();save();
 // Restore/checkpoint and first timing transfer are actual UI interactions.
 await page.reload();await page.locator('.question-player').waitFor();const restored=await observe('reload same attempt');assert.equal(restored.snapshot.attempt.attemptId,start.snapshot.attempt.attemptId);assert(restored.snapshot.attempt.timing.activeMs>=after.snapshot.attempt.timing.activeMs);await interact();
 const snapshot=await page.evaluate(()=>window.__mastersActivity.snapshot());for(const part of snapshot.question.parts){if(part.kind==='text')await page.locator('.inline-gap input').nth(snapshot.question.parts.indexOf(part)).fill('incorrect complete response');else{await page.locator('[data-error-id="phrase-0"]').click();await page.getByLabel('Replacement / correction',{exact:true}).fill('incorrect complete response');}}
 await page.getByRole('button',{name:'Check',exact:true}).click();await page.locator('.assessment-feedback').waitFor();await page.evaluate(()=>window.__mastersActivity.flush());const assessed=await page.evaluate(()=>window.__mastersActivity.snapshot()),evidence=await page.evaluate(()=>window.__mastersActivity.history());assert.equal(evidence.length,1);assert.deepEqual(evidence[0].timing,assessed.attempt.firstResponse.timing);
 await page.waitForTimeout(1500);assert.deepEqual((await page.evaluate(()=>window.__mastersActivity.history()))[0].timing,evidence[0].timing);
 await page.getByRole('button',{name:'Back to course map',exact:true}).first().click();await page.getByRole('button',{name:'Stats',exact:true}).click();await page.getByTestId('statistics-time').waitFor();assert.equal(Number(await page.getByTestId('statistics-time').getAttribute('data-active-ms')),evidence[0].timing.activeMs);await page.screenshot({path:path.join(here,'statistics-timing.png'),fullPage:true});report.checks.push({id:'reload-first-freeze-statistics-transfer',status:'PASS',attemptId:assessed.attempt.attemptId,activeMs:evidence[0].timing.activeMs});save();console.log('PASS timing transfer');
}catch(error){report.failures.push({error:error.stack});console.log('FAIL '+error.stack);}finally{report.status=report.failures.length?'FAIL':report.checks.some(c=>c.status==='UNESTABLISHED')?'PARTIAL':'PASS';report.finishedAt=new Date().toISOString();save();await context.close();await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks,failures:report.failures}));if(report.status==='FAIL')process.exitCode=1;}
