import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {chromium} from '../../../../../node_modules/playwright/index.mjs';
const here=import.meta.dirname,project=path.resolve(here,'../../..');
const comparison=JSON.parse(fs.readFileSync(path.join(here,'browser-comparison.json')));
if(comparison.status!=='PASS')throw Error('Contact sheets require the accepted final comparison run.');
fs.writeFileSync(path.join(here,'state-matrix.json'),JSON.stringify({status:comparison.status,count:comparison.comparisons.length,ownedSourceFingerprint:comparison.ownedSourceFingerprint,finishedOwnedSourceFingerprint:comparison.finishedOwnedSourceFingerprint,method:comparison.visualMethod,pairs:comparison.comparisons.map(item=>({name:item.name,original:`screens/${item.name}-original.png`,restored:`screens/${item.name}-restored.png`,geometry:{original:item.original,restored:item.restored}}))},null,2)+'\n');
for(const course of ['alevel','igcse']){
 const names=[`${course}-desktop-unassessed`,`${course}-desktop-unassessed-revision-hover`,`${course}-desktop-unassessed-revision-focus`,`${course}-desktop-green-steady`,`${course}-desktop-purple-due`,`${course}-desktop-unassessed-details`,`${course}-desktop-unassessed-unavailable-details`,`${course}-desktop-unassessed-revision`,`${course}-tablet-unassessed`,`${course}-mobile-unassessed`,`${course}-mobile-unassessed-details`,`${course}-mobile-unassessed-revision`,...(course==='alevel'?['alevel-desktop-purple-due-upper']:['igcse-desktop-unassessed-teacher-details','igcse-desktop-unassessed-fourth-3-1-choices','igcse-desktop-unassessed-lower-10-1-choices'])];
 const html=`<!doctype html><html><head><meta charset="utf-8"><title>${course} original/restored landing comparison</title><style>body{margin:0;padding:20px;background:#e6e8ee;color:#111;font:14px Arial}h1{font-size:24px}.pair{margin-top:20px;break-inside:avoid}.images{display:grid;grid-template-columns:1fr 1fr;gap:12px}.images a{background:#080a1d;color:white;text-decoration:none}.images span{display:block;padding:7px;background:#203047}.images img{display:block;width:100%;height:390px;object-fit:cover;object-position:top}.mobile img{object-fit:contain}.label{font-size:17px;margin:8px 0}</style></head><body><h1>${course.toUpperCase()}: Original / restored</h1><p>Same browser viewport and isolated synthetic history. Click either image for its full-resolution screenshot. Extra course switch and small teacher/import controls are authorised additions.</p>${names.map(name=>`<section class="pair ${name.includes('mobile')?'mobile':''}"><h2 class="label">${name}</h2><div class="images">${['original','restored'].map(kind=>`<a href="screens/${name}-${kind}.png"><span>${kind}</span><img src="screens/${name}-${kind}.png" alt="${name} ${kind}"></a>`).join('')}</div></section>`).join('')}</body></html>`;
 fs.writeFileSync(path.join(here,`${course}-contact-sheet.html`),html);
}
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}});
for(const course of ['alevel','igcse']){await page.goto(`http://127.0.0.1:5183/validation/landing-restoration/design/${course}-contact-sheet.html`);await page.locator('img').last().waitFor();await page.evaluate(()=>Promise.all(Array.from(document.images).map(image=>image.decode())));await page.screenshot({path:path.join(here,`${course}-contact-sheet.png`),fullPage:true});}
await browser.close();
const inputs=['src/landing','public/assets/landing'];const paths=[];function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,item.name);if(item.isDirectory())walk(file);else paths.push(file);}}for(const dir of inputs)walk(path.join(project,dir));
fs.writeFileSync(path.join(here,'output-fingerprints.json'),JSON.stringify(paths.map(file=>({path:path.relative(project,file).replaceAll('\\','/'),sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')})),null,2)+'\n');
