import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
import {calorimetryConfigurations,calorimetryCode} from '../../../src/activities/igcse/calorimetry/provider.ts';
import {bondCode} from '../../../src/activities/igcse/bond-enthalpy/provider.ts';
import {core as bondCore} from '../../../src/chemistry/thermochemistry/bond-enthalpy-core.js';
const directory=import.meta.dirname,project=resolve(directory,'../../..'),require=createRequire(resolve(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');const {chromium}=require('playwright');
const profile=resolve(directory,'p',Date.now().toString().slice(-7));mkdirSync(profile,{recursive:true});
const context=await chromium.launchPersistentContext(profile,{channel:'msedge',headless:true,viewport:{width:1366,height:1000},args:['--no-first-run','--no-default-browser-check']});
const page=context.pages()[0]??await context.newPage(),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
const snap=()=>page.evaluate(()=>window.__mastersActivity?.snapshot()),flush=()=>page.evaluate(()=>window.__mastersActivity.flush());let serial=0;
async function open(id,query=''){await page.goto(`http://127.0.0.1:5187/igcse.html?run=a12-${id}-${Date.now()}-${serial++}${query}`);await page.waitForFunction(()=>!!window.__mastersActivity);await page.getByLabel('Target',{exact:true}).waitFor();}
async function start(target){await page.getByLabel('Target',{exact:true}).selectOption(target);await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='answering');await flush();return snap();}
async function fill(correct=true){const s=await snap();for(const part of s.question.parts.filter(p=>p.kind==='numeric')){const section=page.locator('.question-part').filter({has:page.locator(`#unused`)});void section;await page.locator('.question-part').nth(s.question.parts.findIndex(p=>p.id===part.id)).getByLabel(/Your answer|Final answer/).fill(String(correct?part.acceptance.expected:part.acceptance.expected+100));}await flush();}
async function submit(){await page.getByRole('button',{name:/Check answer|Submit and freeze response/,exact:true}).click();await page.waitForFunction(()=>['assessed','drawing-review'].includes(window.__mastersActivity?.snapshot().attempt?.phase));await flush();return snap();}
async function scenario(id,operation){try{results.push({id,status:'PASS',evidence:await operation()});}catch(e){results.push({id,status:'FAIL',error:String(e.stack)});await page.screenshot({path:resolve(directory,`${id}-failure.png`),fullPage:true});}writeFileSync(resolve(directory,'browser-results.json'),JSON.stringify({results,errors},null,2));}
try{
 await scenario('six-practice-targets-and-first-correction',async()=>{const routes=[];for(const gem of ['lower-10-3','lower-10-4'])for(const level of [1,2,3]){await open(`practice-${gem}-${level}`);const before=await start(`${gem}:${level}`);await page.getByRole('button',{name:/Check answer|Submit and freeze response/,exact:true}).click();await flush();assert.equal((await snap()).attempt.phase,'answering');assert.equal((await snap()).history.length,0);await fill(false);const numeric=await submit();if(level===3&&gem==='lower-10-4'){assert.equal(numeric.attempt.phase,'drawing-review');assert.equal(numeric.history.length,0);const frozen=JSON.stringify(numeric.attempt.firstResponse);await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='drawing-review');await flush();assert.equal(JSON.stringify((await snap()).attempt.firstResponse),frozen);await page.getByRole('button',{name:'Yes, my drawing meets every criterion',exact:true}).click();}
 await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await flush();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().history.length===1);const first=await snap();assert.equal(first.attempt.firstAssessment.score,level===3&&gem==='lower-10-4'?.5:0);assert.equal(first.history.length,1);const frozen=JSON.stringify(first.attempt.firstResponse),assessment=JSON.stringify(first.attempt.firstAssessment);await fill(true);await page.getByRole('button',{name:'Check correction',exact:true}).click();await flush();assert.equal((await snap()).correctionFeedback.status,'correct');assert.equal(JSON.stringify((await snap()).attempt.firstResponse),frozen);assert.equal(JSON.stringify((await snap()).attempt.firstAssessment),assessment);assert.equal((await snap()).history.length,1);assert.equal(first.history[0].timing.activeMs,first.attempt.firstResponse.timing.activeMs);assert.equal(first.attempt.firstResponse.timing.idleLimitMs,180000);await page.getByRole('button',{name:'Show worked answer',exact:true}).click();await page.screenshot({path:resolve(directory,`desktop-${gem}-${level}.png`),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(directory,`mobile-${gem}-${level}.png`),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1366,height:1000});routes.push({ref:before.question.ref,firstScore:first.attempt.firstAssessment.score,marks:first.attempt.firstAssessment.marks,timing:first.attempt.firstResponse.timing});}return routes;});
 await scenario('framework-local-check-final-binding-assistance-restore',async()=>{await open('framework');const before=await start('lower-10-3:2'),part=before.question.parts[0];await page.locator('.question-part').first().getByLabel('Your answer',{exact:false}).fill('12.3');await page.locator('.question-part').first().getByRole('button',{name:'Show working framework',exact:true}).click();await flush();assert.equal(await page.getByLabel('Final answer',{exact:true}).inputValue(),'12.3');const framework=part.workingFramework,fields=framework.rows.flatMap(row=>row.right.kind==='tokens'?row.right.tokens:[...row.right.numerator,...row.right.denominator]).filter(t=>typeof t!=='string');for(const field of fields.filter(f=>!f.finalResponse))await page.getByLabel(`Working number ${field.id}`,{exact:true}).fill(String(field.expected));await page.getByLabel('Final answer',{exact:true}).fill(String(part.acceptance.expected));await page.getByRole('button',{name:'Check working',exact:true}).click();assert.match(await page.locator('.working-framework [role=status]').textContent(),/does not change your marks/);await flush();assert.equal((await snap()).history.length,0);assert.equal((await snap()).attempt.currentResponses[part.id].raw,String(part.acceptance.expected));assert((await snap()).attempt.assistance.some(a=>a.supportId===framework.supportId));await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='answering');await flush();assert.equal(await page.getByLabel('Final answer',{exact:true}).inputValue(),String(part.acceptance.expected));for(const field of fields.filter(f=>!f.finalResponse))assert.equal(await page.getByLabel(`Working number ${field.id}`,{exact:true}).inputValue(),'');await fill(true);await submit();const after=await snap();assert.equal(after.attempt.firstAssessment.score,1);assert.equal(after.history.length,0);assert(after.attempt.firstResponse.assistance.some(a=>a.supportId===framework.supportId));return {transientIntermediates:true,persistedFinal:true,firstScore:1,independentRecords:0};});
 await scenario('level3-drawing-fail-aggregate-time-freeze',async()=>{await open('drawing-fail');await start('lower-10-4:3');await fill(true);const before=await submit();assert.equal(before.attempt.phase,'drawing-review');const frozen=JSON.stringify(before.attempt.firstResponse);await page.waitForTimeout(1500);await page.getByRole('button',{name:'No, my drawing needs correction',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await flush();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().history.length===1);const after=await snap();assert.equal(JSON.stringify(after.attempt.firstResponse),frozen);assert.equal(after.attempt.firstAssessment.score,.5);assert.equal(after.attempt.firstAssessment.marks.earned,1);assert.equal(after.attempt.firstAssessment.marks.available,2);assert.equal(after.history.length,1);await page.getByRole('button',{name:'Next question',exact:true}).click();await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.attemptId!==id,after.attempt.attemptId);return {numericCorrectDrawingFailScore:.5,timeImmutable:true,newAttempt:(await snap()).attempt.attemptId};});
 await scenario('revision-topic-add-all-pause-reload-next',async()=>{
  await open('revision','&session=revision');await page.getByRole('button',{name:'ADD ALL lower-10',exact:true}).click();const selected=(await snap()).selectedCount;assert(selected>=6);await start('lower-10-3:1');
  const visited=[];for(let route=0;route<18;route++){
   let current=await snap();const activity=current.question.ref.activityId;
   if(activity==='igcse/energy-enthalpy'){
    for(const part of current.question.parts){if(part.kind==='choice')await page.evaluate(({id,selected})=>window.__mastersActivity.respond(id,{kind:'choice',selected}),{id:part.id,selected:part.acceptedOptionSets[0]});else if(part.kind==='text')await page.evaluate(({id,value})=>window.__mastersActivity.respond(id,{kind:'text',value}),{id:part.id,value:part.accepted[0]});else if(part.kind==='energy-profile'){const {record}=await import('../../../src/activities/igcse/energy-enthalpy/provider.ts');const {modelProfile}=await import('../../../src/chemistry/energy-profile/index.ts');await page.evaluate(({id,response})=>window.__mastersActivity.respond(id,response),{id:part.id,response:modelProfile(record(current.question.ref.questionId))});}}
   }else if(activity==='igcse/energetics-practical'){
    const {record,correctionSegments}=await import('../../../src/activities/igcse/energetics-practical/provider.ts'),source=record(current.question.ref.questionId);
    for(const part of current.question.parts){if(part.kind==='choice')await page.evaluate(({id,selected})=>window.__mastersActivity.respond(id,{kind:'choice',selected}),{id:part.id,selected:part.acceptedOptionSets[0]});else if(part.kind==='text')await page.evaluate(({id,value})=>window.__mastersActivity.respond(id,{kind:'text',value}),{id:part.id,value:part.accepted[0]});else if(part.kind==='correction'){const segment=correctionSegments(source).find(s=>s.id===source.correction.errorId);await page.evaluate(({id,selection,replacement})=>window.__mastersActivity.respond(id,{kind:'correction',selections:[selection],replacement}),{id:part.id,selection:segment,replacement:source.fields[0].answers[0]});}}
   }else {assert(['igcse/calorimetry','igcse/bond-enthalpy'].includes(activity));await fill(true);
    await page.getByRole('button',{name:'Pause',exact:true}).click();await flush();const paused=await snap();await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.attemptId);await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await flush();assert.equal((await snap()).attempt.attemptId,paused.attempt.attemptId);assert.deepEqual((await snap()).attempt.currentResponses,paused.attempt.currentResponses);visited.push(activity);
   }
   await submit();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');await flush();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().saveStatus.kind==='saved');current=await snap();assert.equal(current.attempt.firstAssessment.score,1);
   const previous=current.attempt.attemptId;await page.getByRole('button',{name:'Next question',exact:true}).click();await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.attemptId!==id,previous);if(visited.includes('igcse/calorimetry')&&visited.includes('igcse/bond-enthalpy'))break;
  }assert(visited.includes('igcse/calorimetry')&&visited.includes('igcse/bond-enthalpy'));return {selected,visited,sessionKind:(await snap()).session.kind,next:(await snap()).question.ref};
 });
 await scenario('all16-displayed-diagrams-and-thermometers-teacher-render',async()=>{const diagrams=[];for(const reaction of bondCore.reactions){const code=bondCode(reaction.id,Math.max(...reaction.allowedLevels),7);await open('teacher-'+reaction.id,'&mode=teacher&review='+code);await page.getByRole('heading',{name:new RegExp(reaction.name),exact:true}).waitFor();const imgs=page.locator('.content-image');await page.waitForFunction(()=>Array.from(document.querySelectorAll('.content-image')).every(i=>i.complete&&i.naturalWidth>0));assert(await imgs.count()>=2);await imgs.first().screenshot({path:resolve(directory,`diagram-${reaction.id}.png`)});assert.equal((await snap()).attempt,null);assert.equal((await snap()).history.length,0);diagrams.push({reaction:reaction.id,code,images:await imgs.count()});}
 const config=calorimetryConfigurations().find(c=>c.example==='nh4no3'&&c.temperatureRoute==='thermometers'&&c.target==='dh'&&c.difficulty===3&&c.structure==='single-dh'),code=calorimetryCode(config,7);await open('thermometers','&mode=teacher&review='+code);await page.getByRole('heading',{name:/Calorimetry/,exact:true}).waitFor();await page.waitForFunction(()=>Array.from(document.querySelectorAll('.content-image')).every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:resolve(directory,'desktop-thermometers.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(directory,'mobile-thermometers.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));return {diagrams,thermometerCode:code,teacherEvidence:0};});
}finally{writeFileSync(resolve(directory,'browser-results.json'),JSON.stringify({status:results.every(r=>r.status==='PASS')&&!errors.length?'PASS':'FAIL',mode:'isolated headless installed Edge real production host',results,errors},null,2));await context.close();}
assert(results.every(r=>r.status==='PASS'),JSON.stringify(results.filter(r=>r.status!=='PASS')));assert.deepEqual(errors,[]);console.log('PASS thermochemistry production browser');
