import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
import {bondCode,bondSource} from '../../../src/activities/igcse/bond-enthalpy/provider.ts';
const directory=import.meta.dirname,require=createRequire(resolve(directory,'../../../../../package.json')),{chromium}=require('playwright');
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1366,height:1000}}),results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
try{for(const level of [1,2])for(const family of level===1?['enthalpy-change']:['enthalpy-change','unknown-bond']){
 let code;for(let seed=0;seed<128;seed++){const candidate=bondCode('methanol-synthesis',level,seed);if(bondSource(candidate).questionType===family){code=candidate;break;}}assert(code);const source=bondSource(code);assert.equal(source.reaction.deltaH,-119);
 await page.goto(`http://127.0.0.1:5187/igcse.html?run=a12-co-${Date.now()}&mode=teacher&review=${code}`);await page.getByRole('heading',{name:/Bond enthalpy.*methanol/i}).waitFor();await page.waitForFunction(()=>Array.from(document.querySelectorAll('.content-image')).every(i=>i.complete&&i.naturalWidth>0));
 const imageEvidence=await page.locator('.content-image').evaluateAll(images=>images.map(image=>{const text=decodeURIComponent(image.src.split(',')[1]),doc=new DOMParser().parseFromString(text,'image/svg+xml');return {naturalWidth:image.naturalWidth,carbonMinus:doc.querySelectorAll('[data-reviewed-charge="carbon-minus"]').length,parseErrors:doc.querySelectorAll('parsererror').length};}));assert(imageEvidence.length>=2);for(const image of imageEvidence){assert.equal(image.carbonMinus,1);assert.equal(image.parseErrors,0);assert(image.naturalWidth>0);}await page.screenshot({path:resolve(directory,`co-host-desktop-${level}-${family}.png`),fullPage:true});await page.locator('.content-image').first().screenshot({path:resolve(directory,`co-host-reviewed-${level}-${family}.png`)});await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(directory,`co-host-mobile-${level}-${family}.png`),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1366,height:1000});
 const snapshot=await page.evaluate(()=>window.__mastersActivity.snapshot());assert.equal(snapshot.attempt,null);assert.equal(snapshot.history.length,0);results.push({level,family,code,imageEvidence,deltaH:source.reaction.deltaH,independentEvidence:0});
}}finally{writeFileSync(resolve(directory,'co-browser-results.json'),JSON.stringify({status:results.length===3&&!errors.length?'PASS':'FAIL',results,errors},null,2));await browser.close();}assert.equal(results.length,3);assert.deepEqual(errors,[]);console.log('PASS reviewed CO actual production host models at both supported levels and both families');
