import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
const directory=import.meta.dirname,project=resolve(directory,'../../..'),require=createRequire(resolve(project,'../../package.json')),{chromium}=require('playwright');
const profile=resolve(directory,'p','t'+Date.now().toString().slice(-6));mkdirSync(profile,{recursive:true});
// Raw installed Chrome CDP avoids Playwright launch defaults that reactivate frozen pages.
const browserProcess=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',[`--user-data-dir=${profile}`,'--headless=new','--remote-debugging-port=9367','--remote-debugging-address=127.0.0.1','--no-first-run','--no-default-browser-check','about:blank'],{stdio:'ignore',windowsHide:true});
let ready=false;for(let i=0;i<60;i++){try{if((await fetch('http://127.0.0.1:9367/json/version')).ok){ready=true;break;}}catch{}await new Promise(done=>setTimeout(done,250));}assert(ready,'Raw headless Chrome CDP endpoint');
const browser=await chromium.connectOverCDP('http://127.0.0.1:9367',{noDefaults:true,artifactsDir:directory,isLocal:true}),context=browser.contexts()[0],page=context.pages()[0]??await context.newPage(),results=[];await page.setViewportSize({width:1000,height:800});
const wait=ms=>new Promise(done=>setTimeout(done,ms)),snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot()),flush=()=>page.evaluate(()=>window.__mastersActivity.flush());
try{
 await page.goto('http://127.0.0.1:5187/igcse.html?run=a12-timing-'+Date.now());await page.waitForFunction(()=>!!window.__mastersActivity);await page.getByLabel('Target',{exact:true}).selectOption('lower-10-3:1');await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='answering');const input=page.locator('.question-part input').first();await input.fill('1');await wait(1400);await page.evaluate(()=>window.__mastersActivity.checkpoint());await flush();const initial=await snap();assert(initial.attempt.timing.activeMs>500);
 const cdp=await context.newCDPSession(page);await cdp.send('Page.setWebLifecycleState',{state:'frozen'});await wait(6400);await cdp.send('Page.setWebLifecycleState',{state:'active'});await wait(1200);await page.evaluate(()=>window.__mastersActivity.checkpoint());await flush();const resumed=await snap();assert.equal(resumed.attempt.timing.activeMs,initial.attempt.timing.activeMs);results.push({id:'same-document-browser-suspension',status:'PASS',before:initial.attempt.timing,after:resumed.attempt.timing,freezeMs:6400});
 await input.press('ArrowLeft');await wait(1200);await page.evaluate(()=>window.__mastersActivity.checkpoint());await flush();const active=await snap();assert(active.attempt.timing.activeMs>resumed.attempt.timing.activeMs);
 const background=await context.newPage();await background.goto('about:blank');await background.bringToFront();await wait(1500);const visibility=await page.evaluate(()=>({hidden:document.hidden,focused:document.hasFocus()}));await page.evaluate(()=>window.__mastersActivity.checkpoint());const hidden=await snap();await wait(2200);await page.evaluate(()=>window.__mastersActivity.checkpoint());const stillHidden=await snap();assert(visibility.hidden||!visibility.focused);assert.equal(stillHidden.attempt.timing.activeMs,hidden.attempt.timing.activeMs);await background.close();await page.bringToFront();await input.press('ArrowLeft');results.push({id:'background-tab-stops-accrual',status:'PASS',visibility,before:hidden.attempt.timing,after:stillHidden.attempt.timing});
 await wait(183000);await page.evaluate(()=>window.__mastersActivity.checkpoint());await flush();const idle=await snap();await wait(2400);await page.evaluate(()=>window.__mastersActivity.checkpoint());const beyond=await snap();assert.equal(beyond.attempt.timing.activeMs,idle.attempt.timing.activeMs);const delta=idle.attempt.timing.activeMs-stillHidden.attempt.timing.activeMs;assert(delta>=178000&&delta<=181000,`180-second idle allowance, actual ${delta}`);results.push({id:'real-three-minute-idle-cutoff',status:'PASS',realIdleWaitMs:183000,before:stillHidden.attempt.timing,atCutoff:idle.attempt.timing,after:beyond.attempt.timing});
 await input.press('ArrowLeft');await wait(1300);await page.evaluate(()=>window.__mastersActivity.checkpoint());const renewed=await snap();assert(renewed.attempt.timing.activeMs>idle.attempt.timing.activeMs);results.push({id:'trusted-key-restarts-after-idle',status:'PASS',after:renewed.attempt.timing});
}catch(e){results.push({id:'timing-browser',status:'FAIL',error:String(e.stack)});}finally{writeFileSync(resolve(directory,'timing-browser-results.json'),JSON.stringify({status:results.every(r=>r.status==='PASS')?'PASS':'FAIL',mode:'raw installed headless Chrome/noDefaults CDP actual production host; same document CDP freeze and real wall-clock idle',results},null,2));await browser.close();browserProcess.kill();}
assert(results.every(r=>r.status==='PASS'),JSON.stringify(results));console.log('PASS actual thermochemistry clock browser');
