import fs from 'node:fs';import path from 'node:path';import {createRequire}from'node:module';
const require=createRequire(path.resolve('package.json')),here=path.join(import.meta.dirname,'final-accepted');
const report=JSON.parse(fs.readFileSync(path.join(here,'browser-results.json')));
const tags=report.checks.filter(x=>x.tag).map(x=>x.tag),states=['unanswered','partial','incorrect','correct','correction','model'];
const capturePath=tag=>'../'+report.checks.find(x=>x.tag===tag).captureFolder+'/';const html=tag=>`<!doctype html><html><head><meta charset="utf-8"><title>${tag} original / React equivalent states</title><style>body{background:#e5e7eb;color:#111;font:16px Arial;margin:20px}h1{font-size:24px}table{border-collapse:collapse}th,td{padding:12px;border:1px solid #aaa;vertical-align:top}img{display:block;max-width:none}a{color:#1642a0}h2{font-size:20px;margin:0 0 8px}</style></head><body><h1>${tag}: source final / React final</h1><p>Native-size workspace crops. Open linked full-page renders to inspect prompts, shared feedback, model answers, accepted masthead and footer. Diprotic families have Level 3 only.</p><table><thead><tr><th>Original final source component</th><th>Current React component</th></tr></thead><tbody>${states.map(state=>`<tr>${['original','react'].map(kind=>`<td><h2>${state}</h2><a href="${capturePath(tag)}${kind}-${tag}-${state}.png">Full-page ${kind} ${state}</a><img src="${capturePath(tag)}workspace-${kind}-${tag}-${state}.png" alt="${kind} ${state} ${tag}"></td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`;
process.env.TEMP=process.env.TMP=path.resolve('apps/Masters-of-Chemistry/.f11-tmp');
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});
const c=await b.newContext({viewport:{width:2920,height:1000}}),p=await c.newPage();
const contacts=[];for(const tag of tags){const file=path.join(here,'contact-'+tag+'.html');fs.writeFileSync(file,html(tag));await p.goto(new URL('file:///'+file.replaceAll('\\','/')).href);await p.locator('img').evaluateAll(async imgs=>{await Promise.all(imgs.map(img=>img.decode()))});await p.screenshot({path:path.join(here,'contact-'+tag+'.png'),fullPage:true});contacts.push({tag,html:path.basename(file),png:'contact-'+tag+'.png'});}
fs.writeFileSync(path.join(here,'contacts.json'),JSON.stringify({status:'PASS',count:contacts.length,contacts},null,2));await b.close();console.log('PASS '+contacts.length+' native-size paired six-state contacts');
