import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import assert from'node:assert/strict';const here=import.meta.dirname,report=JSON.parse(fs.readFileSync(path.join(here,'final-accepted/browser-results.json')));
const inspected=['desktop-TC-GMPGTV','tablet-TC-IUMADN','mobile-TC-H6RTPS','desktop-TC-IKPU6N','desktop-TC-HQNVLR','desktop-TC-JYNUNI','desktop-TC-J4S72K','desktop-TC-IUSLDL','desktop-TC-LWO80A','desktop-TC-LU98XN','tablet-TC-ME8GBL','tablet-TC-MO820K'];
const renders=[];for(const screenshot of report.screenshots){for(const prefix of['','workspace-']){const sourcePath=screenshot.replace(/([^/]+\.png)$/,prefix+'$1'),absolute=path.resolve(here,'final-accepted',sourcePath),bytes=fs.readFileSync(absolute);assert.equal(bytes.subarray(1,4).toString(),'PNG');const width=bytes.readUInt32BE(16),height=bytes.readUInt32BE(20);assert(width>300&&height>250);renders.push({path:path.relative(here,absolute).replaceAll('\\','/'),width,height,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')});}}
assert.equal(renders.length,864);fs.writeFileSync(path.join(here,'final-accepted/artifact-manifest.json'),JSON.stringify({status:'PASS',renders:864,fullPages:432,workspaceCrops:432,files:renders},null,2));
fs.writeFileSync(path.join(here,'render-review.json'),JSON.stringify({status:'PASS',reviewedAt:new Date().toISOString(),reviewer:'F11',method:'Viewed actual exported Edge renders and paired six-state contact PNGs; inspected full-size response workspaces and teacher/panned mobile examples.',pairedSixStateContactsInspected:inspected,coverage:'All seven families and all twelve genuine family-level combinations; desktop/tablet/mobile layouts and all six states represented.',fullSizeExamplesInspected:['final-v4/react-desktop-TC-GMPGTV-incorrect.png','final-v4/workspace-react-tablet-TC-MO820K-correct.png','final-tail/workspace-react-mobile-TC-LWO80A-correct.png','final-teacher-v2/desktop-TC-GMPGTV-teacher.png','final-teacher-v2/tablet-TC-JYNUNI-teacher.png','final-teacher-v2/mobile-TC-MO820K-teacher.png','mobile-pan-fixed-react.png'],findings:['Source mint/purple halves, yellow anchor/guides, equilibrium join, axis/tick layouts and selected source diagram thumbnails match.','Native chart labels and source indicator bands are legible; teacher controls retain original full opacity.','Mobile graph retains source650px horizontal-scroll topology, with trusted pan showing final pH/right axis.','Question context, accepted masthead/code/level/footer, source feedback heading and compact six-check feedback are present.','No new visual or chemical defect found after documented fixes.'],limits:['This is an authored F2 review; root source/render acceptance remains required.','Contact PNGs are overview sheets; linked native-size crops/full pages are the legibility evidence.','Whole-page widths differ because accepted common React shell is preserved.','No native OS hidden/suspension claim.']},null,2));
const teacher=JSON.parse(fs.readFileSync(path.join(here,'final-teacher-v2/teacher-results.json')));assert.equal(teacher.status,'PASS');assert.equal(teacher.checks.length,108);assert.deepEqual(teacher.errors,[]);
const interaction=JSON.parse(fs.readFileSync(path.join(here,'final-interactions/interaction-results.json')));assert.equal(interaction.status,'PASS');assert.deepEqual(interaction.errors,[]);
for(const file of['enter-probe-fixed-results.json','mobile-pan-fixed-results.json','mobile-input-final-results.json','audit-results.json'])assert.equal(JSON.parse(fs.readFileSync(path.join(here,file))).status,'PASS');
const paths=JSON.parse(fs.readFileSync(path.join(here,'path-hash-map.json')));for(const entry of paths)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.resolve('apps/Masters-of-Chemistry',entry.path))).digest('hex'),entry.currentSha256);
fs.writeFileSync(path.join(here,'completion.json'),JSON.stringify({agentId:'F11',jobId:'F2-TITRATION',status:'PASS',output:'validation/component-fidelity/f2/titration/resume-f11/HANDOVER.md',confidence:0.97,reason:null,validation:{chemistry:'audit-results.json:36 exact source/current records',browser:'final-accepted/browser-results.json:36 completed combinations /432 full renders',visual:'render-review.json; final-accepted/contacts.json:36 contacts; computed-source-match.json:216 exact SVG style pairs',teacher:'final-teacher-v2/teacher-results.json:108 checks/36 paired contacts',lifecycle:'final-interactions/interaction-results.json PASS',numericEnter:'enter-probe-fixed-results.json PASS',touch:'mobile-pan-fixed-results.json and mobile-input-final-results.json PASS',diffs:'path-hash-map.json; exact baseline/current and F11 patch diffs',typecheck:'typecheck-final.log PASS',protectedOriginals:'protected-originals-final.log PASS'},requestedModel:'gpt-6.1-sol',requestedEffort:'high',effectiveModelEffort:'not exposed',usage:'not exposed',acceptanceBoundary:'Worker PASS only; F2 root acceptance and shared integration/release gates remain with parent.'},null,2));console.log('PASS final rendered review,864 PNG manifest,teacher/lifecycle/current fingerprints and compact completion');
