import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import vm from 'node:vm';import{createRequire}from'node:module';
import{bank,reviewCode,titrationProvider}from '../../../../../src/activities/alevel/ph-titration-curves/provider.ts';
import{answer,curve,grade,initial}from '../../../../../src/chemistry/titration-curve/core.js';
import{checkSubmission}from '../../../../../src/chemistry/titration-curve/engine.ts';
const here=import.meta.dirname,require=createRequire(path.resolve('package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.resolve('apps/Masters-of-Chemistry/.f11-tmp');fs.mkdirSync(process.env.TEMP,{recursive:true});
const b=await require('playwright').chromium.launch({channel:'msedge',headless:true});
const report={jobId:'F2-TITRATION',agentId:'F11',startedAt:new Date().toISOString(),status:'RUNNING',checks:[],screenshots:[],metrics:[],errors:[],limits:['Headless Edge/pinned root Playwright 1.62.1; no native OS hidden/suspension claim.','Source interactions occur in fresh nonpersistent synthetic browser contexts.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shot(p,label){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(here,label+'.png'),fullPage:true});report.screenshots.push(label+'.png');}
async function start(c,q,mode='practice'){
 const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:5188/alevel.html?run=f11-'+Date.now()+'-'+Math.random().toString(36).slice(2));await p.locator('.original-landing').waitFor();
 if(mode==='revision'){await p.getByRole('button',{name:'Revision',exact:true}).click();await p.locator('#flipYear').click();await p.locator('[data-topic="u6-t1-topic-1"] .topic-trigger').click();await p.locator('[data-leaf="u6-t1-1-9"]').click();await p.getByRole('button',{name:'Go: start revision',exact:true}).click();}
 else{await p.evaluate(()=>location.hash='u6-t1-1-9');await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator('a.practice-choice[data-practice="'+q.level+'"]').click();}
 await p.locator('.tc-chart').waitFor();await flush(p);if((await snap(p)).question.ref.questionId!==reviewCode(q.id)){
 await p.evaluate(async({qid,level})=>{const s=window.__mastersActivity.snapshot();const{titrationProvider}=await import('/src/activities/alevel/ph-titration-curves/provider.ts');const{createChemistryRepository}=await import('/src/persistence/index.ts');const ref={...s.question.ref,questionId:qid,level};const question=titrationProvider.restore(ref);const newId=crypto.randomUUID();const attempt={...s.attempt,attemptId:newId,timing:{...s.attempt.timing,attemptId:newId,activeMs:0},ref,target:{...s.attempt.target,level},currentResponses:{},phase:'answering'};const session={...s.session,currentAttemptId:newId,target:attempt.target,previousQuestionIds:[qid]};const repo=createChemistryRepository(s.databaseName);const r=await repo.saveCurriculum({attempt,session});repo.close();if(!r.ok)throw Error(r.error.message);},{qid:reviewCode(q.id),level:q.level});await p.reload();await p.locator('.tc-chart').waitFor();await flush(p);}
 assert.equal((await snap(p)).question.ref.questionId,reviewCode(q.id));return p;
}
async function set(p,q,wrong=false){const a=answer(q);await p.locator('[data-piece="'+a.before+'"]').click();await p.locator('[data-piece="'+a.after+'"]').click();await p.locator('.tc-alternatives summary').click();for(const[label,val]of[['Initial pH',a.initialPH],['Equivalence volume / cm\u00b3',a.equivalenceVolume+(wrong?2:0)],['Final pH',a.finalPH]]){await p.getByLabel(label,{exact:true}).fill(String(val));await p.getByLabel(label,{exact:true}).press('Enter');}await p.locator('[data-indicator="'+a.indicator+'"]').click();await p.locator('.tc-alternatives summary').click();await flush(p);}
async function source(c,q,state){const p=await c.newPage();p.on('pageerror',e=>report.errors.push('source: '+e.message));await p.goto('http://127.0.0.1:5197/alevel/activities/ph-titration-curves/index.html?level='+q.level);await p.locator('#curve-chart').waitFor();await originalState(p,q,state);return p;}
async function originalState(p,q,state){await p.evaluate(({qid,state})=>TitrationActivity.loadQuestion(qid,state),{qid:q.id,state});}
function response(q,wrong=false){return{...answer(q),equivalenceVolume:answer(q).equivalenceVolume+(wrong?2:0)}}
try{
const c=await b.newContext({viewport:{width:1440,height:1000}}),p=await start(c,bank[0]);await set(p,bank[0]);let s=await snap(p);const id=s.attempt.attemptId;
const h=p.getByRole('slider',{name:'Initial pH anchor',exact:true});await h.focus();await p.keyboard.press('ArrowUp');await flush(p);assert(Math.abs((await snap(p)).attempt.currentResponses.curve.initialPH-s.attempt.currentResponses.curve.initialPH-.1)<1e-7);await p.keyboard.press('ArrowDown');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.curve.initialPH,s.attempt.currentResponses.curve.initialPH);
await p.locator('.tc-alternatives summary').click();const input=p.getByLabel('Initial pH',{exact:true});for(const bad of['-','1e2','2.85','15','']){await input.fill(bad);await input.press('Enter');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.curve.initialPH,s.attempt.currentResponses.curve.initialPH);assert.equal(await input.getAttribute('aria-invalid'),'true');}await input.fill('3');await input.press('Escape');assert(Math.abs(Number(await input.inputValue())-s.attempt.currentResponses.curve.initialPH)<1e-7);
const eq=p.getByRole('slider',{name:'Equivalence volume anchor',exact:true});await eq.scrollIntoViewIfNeeded();let box=await eq.boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+30,box.y+box.height/2,{steps:6});await p.mouse.up();await flush(p);assert.notEqual((await snap(p)).attempt.currentResponses.curve.equivalenceVolume,s.attempt.currentResponses.curve.equivalenceVolume);await p.getByRole('button',{name:'Undo curve edit',exact:true}).click();await flush(p);assert.equal((await snap(p)).attempt.currentResponses.curve.equivalenceVolume,s.attempt.currentResponses.curve.equivalenceVolume);await p.reload();await p.locator('.tc-chart').waitFor();await flush(p);assert.equal((await snap(p)).attempt.attemptId,id);assert.deepEqual((await snap(p)).attempt.currentResponses,s.attempt.currentResponses);
await p.getByRole('button',{name:'Check answer',exact:true}).click();await p.locator('.assessment-feedback').waitFor();await flush(p);const first=await snap(p);await p.getByRole('button',{name:'Show worked answer',exact:true}).click();await flush(p);assert.deepEqual((await snap(p)).attempt.firstResponse.timing,first.attempt.firstResponse.timing);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,1);await p.getByRole('button',{name:'Next question',exact:true}).click();await p.waitForFunction(id=>window.__mastersActivity.snapshot().attempt?.attemptId!==id,id);await flush(p);assert.equal((await snap(p)).attempt.phase,'answering');assert.equal((await snap(p)).attempt.firstAssessment,undefined);assert.equal((await snap(p)).attempt.timing.finished,false);report.checks.push({name:'keyboard/mouse/Undo/invalid draft/Escape/practice reload/first time freeze/fresh Next',status:'PASS'});await c.close();
const touchC=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),t=await start(touchC,bank[0]);await t.locator('[data-piece="before-weak-acid"]').tap();await t.locator('[data-piece="after-strong-base"]').tap();await flush(t);const before=await snap(t);const th=t.getByRole('slider',{name:'Initial pH anchor',exact:true});await th.scrollIntoViewIfNeeded();box=await th.boundingBox();const cd=await touchC.newCDPSession(t);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2-30}]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await flush(t);assert.notEqual((await snap(t)).attempt.currentResponses.curve.initialPH,before.attempt.currentResponses.curve.initialPH);await t.locator('.tc-alternatives summary').tap();await t.getByLabel('Initial pH',{exact:true}).fill('3.2');await t.getByLabel('Initial pH',{exact:true}).press('Enter');await flush(t);assert.equal((await snap(t)).attempt.currentResponses.curve.initialPH,3.2);await shot(t,'touch-anchor-numeric');report.checks.push({name:'mobile touch piece taps/trusted CDP touch anchor drag/non-drag numeric commit',status:'PASS'});await touchC.close();
const teacherC=await b.newContext({viewport:{width:820,height:1180}});for(const q of bank){const teacher=await teacherC.newPage();await teacher.goto('http://127.0.0.1:5188/alevel.html?view=teacher&activity=alevel%2Fph-titration-curves&review='+reviewCode(q.id)+'&level='+q.level+'&seed=3&run=f11-teacher-'+q.id);await teacher.locator('.tc-chart').waitFor();await flush(teacher);assert.equal((await snap(teacher)).attempt,null);assert.equal((await teacher.evaluate(()=>window.__mastersActivity.history())).length,0);assert.equal(await teacher.locator('.piece-choice[aria-pressed="true"]').count(),2);assert.equal(await teacher.locator('.indicator-choice[aria-pressed="true"]').count(),1);assert.equal(await teacher.locator('.titration-workspace button:not(:disabled)').count(),0);if(q.id==='TC01')await shot(teacher,'teacher-tablet-model');await teacher.close();}report.checks.push({name:'all36 teacher checked source-model curve/pieces/indicator renders; no attempt/history',status:'PASS'});await teacherC.close();
const revC=await b.newContext({viewport:{width:1440,height:1000}}),r=await start(revC,bank[0],'revision');await set(r,bank[0]);await flush(r);const rs=await snap(r);assert.equal(rs.session.kind,'revision');await r.reload();await r.locator('.tc-chart').waitFor();await flush(r);assert.equal((await snap(r)).attempt.attemptId,rs.attempt.attemptId);assert.deepEqual((await snap(r)).attempt.currentResponses,rs.attempt.currentResponses);await r.getByRole('button',{name:'Check answer',exact:true}).click();await r.locator('.assessment-feedback').waitFor();await flush(r);const rf=await snap(r);assert.equal(rf.attempt.firstAssessment.marks.earned,6);await r.getByRole('button',{name:'Next question',exact:true}).click();await r.waitForFunction(id=>window.__mastersActivity.snapshot().attempt?.attemptId!==id,rf.attempt.attemptId);await flush(r);assert.equal((await snap(r)).session.kind,'revision');assert.equal((await snap(r)).attempt.phase,'answering');report.checks.push({name:'actual revision selection/launch/restoration/assessment/scheduler Next',status:'PASS'});await revC.close();report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1;}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'interaction-results.json'),JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify(report.checks));}


