import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createRequire}from'node:module';
import{bank,reviewCode}from'../../../../../src/activities/alevel/ph-titration-curves/provider.ts';import{answer}from'../../../../../src/chemistry/titration-curve/core.js';
const here=path.join(import.meta.dirname,'final-teacher-v2');fs.mkdirSync(here,{recursive:true});const require=createRequire(path.resolve('package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.resolve('apps/Masters-of-Chemistry/.f11-tmp');
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={jobId:'F2-TITRATION',agentId:'F11',status:'RUNNING',checks:[],errors:[],startedAt:new Date().toISOString()};
try{for(const[size,viewport]of Object.entries({desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}})){
const context=await browser.newContext({viewport,hasTouch:size==='mobile'}),sourceContext=await browser.newContext({viewport,hasTouch:size==='mobile'});
for(const q of bank){const p=await context.newPage();p.on('pageerror',error=>report.errors.push(error.message));await p.goto('http://127.0.0.1:5188/alevel.html?view=teacher&activity=alevel%2Fph-titration-curves&review='+reviewCode(q.id)+'&level='+q.level+'&seed=3&run=f11-teacher-'+q.id);await p.locator('.tc-chart').waitFor();await p.evaluate(()=>window.__mastersActivity.flush());const snapshot=await p.evaluate(()=>window.__mastersActivity.snapshot());assert.equal(snapshot.attempt,null);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,0);const model=answer(q);assert.equal(Number(await p.getByRole('slider',{name:'Initial pH anchor',exact:true}).getAttribute('aria-valuenow')),model.initialPH);assert.equal(Number(await p.getByRole('slider',{name:'Equivalence volume anchor',exact:true}).getAttribute('aria-valuenow')),model.equivalenceVolume);assert.equal(Number(await p.getByRole('slider',{name:'Final pH anchor',exact:true}).getAttribute('aria-valuenow')),model.finalPH);assert.equal(await p.locator('.piece-choice[aria-pressed="true"]').count(),2);assert.equal(await p.locator('.indicator-choice[aria-pressed="true"]').getAttribute('data-indicator'),model.indicator);assert.equal(await p.locator('.titration-workspace button:not(:disabled)').count(),0);assert.equal(await p.locator('.piece-choice').first().evaluate(e=>getComputedStyle(e).opacity),'1');assert.equal(await p.locator('.indicator-choice').first().evaluate(e=>getComputedStyle(e).opacity),'1');assert.equal(await p.locator('.chart-handle').first().evaluate(e=>getComputedStyle(e).cursor),'default');assert.equal(await p.locator('.chart-handle').first().evaluate(e=>getComputedStyle(e).pointerEvents),'none');assert((await p.locator('.question-text').innerText()).includes(q.initialName));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
const representative=bank.find(x=>x.family===q.family&&x.level===q.level).id===q.id;if(representative){const original=await sourceContext.newPage();await original.goto('http://127.0.0.1:5197/alevel/activities/ph-titration-curves/index.html?review='+reviewCode(q.id));await original.locator('#curve-chart').waitFor();assert.equal(await original.evaluate(()=>TitrationActivity.getQuestion().id),q.id);assert.equal(await original.evaluate(()=>TitrationActivity.isReviewing()),true);await original.evaluate(()=>document.fonts.ready);await original.screenshot({path:path.join(here,size+'-'+reviewCode(q.id)+'-original-teacher.png'),fullPage:true});await original.close();await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(here,size+'-'+reviewCode(q.id)+'-teacher.png'),fullPage:true});await p.reload();await p.locator('.tc-chart').waitFor();assert.equal((await p.evaluate(()=>window.__mastersActivity.snapshot())).attempt,null);assert.equal((await p.evaluate(()=>window.__mastersActivity.history())).length,0);}
report.checks.push({size,id:q.id,canonicalId:reviewCode(q.id),level:q.level,family:q.family,checkedModel:true,readOnly:true,noAttemptOrHistory:true,status:'PASS'});await p.close();}
await context.close();await sourceContext.close();}assert.equal(report.errors.length,0);report.status='PASS';}catch(error){report.status='FAIL';report.failure=error.stack;process.exitCode=1;}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'teacher-results.json'),JSON.stringify(report,null,2));await browser.close();console.log(report.status+' '+report.checks.length+' teacher source models / read-only cursor / no evidence checks');}
