import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');fs.mkdirSync(path.join(here,'retained'),{recursive:true});
const freezeBytes=fs.readFileSync(path.join(project,'validation/s5/integration/freeze-current.json')),freeze=JSON.parse(freezeBytes);assert.equal(freeze.treeSha256,'35e6c969f6b9f5fefff7577922dd6703b6a645dc2308a460d44d19d3ce790eb1');assert.equal(sha(JSON.stringify(freeze.currentInputHashes)),freeze.treeSha256);for(const file of freeze.currentInputHashes)assert.equal(sha(fs.readFileSync(path.join(project,file.path))),file.sha256);fs.writeFileSync(path.join(here,'retained/freeze-current.json'),freezeBytes);
for(const f of ['src/foundation/ActivityHost.tsx','src/editors/energy-profile/index.tsx','src/ui/QuestionPlayer.tsx'])fs.copyFileSync(path.join(project,f),path.join(here,'retained',f.replaceAll('/','__')));
let s=fs.readFileSync(path.join(here,'../energy-next-classification/probe.mjs'),'utf8');
s=s.replaceAll('S5-REVIEW-ENERGY-NEXT-CLASSIFICATION','S5-REVIEW-ENERGY-NEXT-FIX').replaceAll('A06-classify-','A06-fix-').replace("['unfinished-draft','clean-control']","['unfinished-draft','clean-control','quota-failure-retry','duplicate-next']");
const old="const before=await durable(p);assert.equal(before.attempts[0].phase,'assessed');assert.equal(before.evidence.length,1);if(mode==='unfinished-draft')await type(p,p.getByLabel('Peak level screen y',{exact:true}),'270',false);const beforeClick=await dom(p);await p.getByRole('button',{name:'Next question',exact:true}).click();let changed=false;try{await p.waitForFunction(()=>document.querySelector('.question-meta code')?.textContent!=='D03',null,{timeout:5000});changed=true}catch{}const afterClick=await dom(p),after=await durable(p);const result={mode,before,beforeClick,changed,afterClick,after};await p.screenshot({path:path.join(here,mode+'.png'),fullPage:true});\n  if(mode==='unfinished-draft'&&!changed){await p.getByText('Saved on this device',{exact:true}).waitFor();await p.getByRole('button',{name:'Next question',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.question-meta code')?.textContent!=='D03',null,{timeout:5000});result.secondClick={dom:await dom(p),durable:await durable(p)};}";
assert(s.includes(old));
s=s.replace(old,`const before=await durable(p);assert.equal(before.attempts[0].phase,'assessed');assert.equal(before.evidence.length,1);const oldId=before.sessions[0].currentAttemptId;
  if(mode==='quota-failure-retry')await p.evaluate(()=>{window.failDraftSave=true;const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...args){if(window.failDraftSave&&this.name==='attempts'&&value?.value?.currentResponses?.profile?.peak===270)throw new DOMException('A06 synthetic dirty-blur quota failure','QuotaExceededError');return original.call(this,value,...args)}});
  if(mode!=='clean-control')await type(p,p.getByLabel('Peak level screen y',{exact:true}),'270',false);const beforeClick=await dom(p);const nextButton=p.getByRole('button',{name:'Next question',exact:true});if(mode==='duplicate-next')await nextButton.dblclick({delay:0});else await nextButton.click();
  let changed=false;if(mode==='quota-failure-retry'){await p.getByRole('button',{name:'Retry save',exact:true}).waitFor();}else{await p.waitForFunction(()=>document.querySelector('.question-meta code')?.textContent!=='D03',null,{timeout:10000});changed=true;await p.getByText('Saved on this device',{exact:true}).waitFor();}
  const afterClick=await dom(p),after=await durable(p);const result={mode,before,beforeClick,changed,afterClick,after};await p.screenshot({path:path.join(here,mode+'.png'),fullPage:true});const oldAfter=after.attempts.find(a=>a.attemptId===oldId);assert.deepEqual(oldAfter.firstResponse,before.attempts[0].firstResponse);assert.deepEqual(oldAfter.firstAssessment,before.attempts[0].firstAssessment);assert.deepEqual(after.evidence,before.evidence);assert.equal(after.evidence.length,1);
  if(mode==='quota-failure-retry'){assert.equal(after.sessions[0].currentAttemptId,oldId);assert.equal(afterClick.code,'D03');assert.equal(after.attempts.length,1);assert.equal(oldAfter.currentResponses.profile.peak,150);assert(await nextButton.isDisabled());await p.evaluate(()=>window.failDraftSave=false);await p.getByRole('button',{name:'Retry save',exact:true}).click();await p.getByText('Saved on this device',{exact:true}).waitFor();const retried=await durable(p);assert.equal(retried.sessions[0].currentAttemptId,oldId);assert.equal(retried.attempts[0].currentResponses.profile.peak,270);await p.getByRole('button',{name:'Next question',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.question-meta code')?.textContent!=='D03',null,{timeout:10000});await p.getByText('Saved on this device',{exact:true}).waitFor();result.retry={dom:await dom(p),durable:await durable(p)};assert.notEqual(result.retry.durable.sessions[0].currentAttemptId,oldId);assert.deepEqual(result.retry.durable.evidence,before.evidence);assert.equal(result.retry.durable.attempts.length,2);
  }else{assert.notEqual(after.sessions[0].currentAttemptId,oldId);assert.equal(after.attempts.length,2);const fresh=after.attempts.find(a=>a.attemptId===after.sessions[0].currentAttemptId);assert.equal(fresh.phase,'answering');assert.equal(fresh.firstResponse,undefined);assert.equal(fresh.firstAssessment,undefined);assert.deepEqual(fresh.currentResponses,{});assert.equal(fresh.timing.finished,false);assert(fresh.timing.activeMs<2500);assert(afterClick.events.some(e=>e.type==='click'&&e.target==='Next question'&&e.trusted));if(mode==='duplicate-next')assert(afterClick.events.filter(e=>e.type==='pointerdown'&&e.target==='Next question'&&e.trusted).length>=2);}
`);
s=s.replace("report.status='CAPTURED'","report.status='PASS'");fs.writeFileSync(path.join(here,'probe.mjs'),s);fs.writeFileSync(path.join(here,'preflight.json'),JSON.stringify({checkedAt:new Date().toISOString(),treeSha256:freeze.treeSha256,inputs:freeze.currentInputHashes.length,freezeHash:sha(freezeBytes),probeHash:sha(s)},null,2)+'\n');console.log(JSON.stringify({inputs:freeze.currentInputHashes.length,tree:freeze.treeSha256}));
