import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateOlympiad,safeJson} from '../../../src/persistence/validation.ts';
import {chemicalChallenge,sourceBank,currentBAnswers,c3KErratum} from '../../../src/activities/olympiad/c3l6/source-bank.ts';
import {moleculeMatches,c3Policy} from '../../../src/activities/olympiad/c3l6/policy.ts';
import {core,moleculeEngine} from '../../../src/chemistry/molecule/engine.ts';
const load=n=>JSON.parse(fs.readFileSync(new URL('../fixes/c3-k-erratum/'+n,import.meta.url),'utf8'));
const mutations=[['nested',p=>p.historicalOutcome.raw.historicalOutcome=structuredClone(p.historicalOutcome)],['profile',p=>p.historicalOutcome.raw.profileId='other'],['course',p=>p.historicalOutcome.raw.course='igcse'],['activity',p=>p.historicalOutcome.raw.activityId='alevel/electrons-bonding'],['policy',p=>p.historicalOutcome.policyVersion='unknown'],['reason',p=>p.historicalOutcome.reason='anything'],['extra history field',p=>p.historicalOutcome.score=1],['extra raw field',p=>p.historicalOutcome.raw.mastery=1],['malformed atom ref',p=>p.historicalOutcome.raw.drawingsB.K.graph.bonds[0].b=999],['stale snapshot',p=>p.historicalOutcome.raw.unitChecks['b-iv-3'].drawingFingerprint='f'],['impossible count',p=>p.historicalOutcome.raw.unitChecks['b-iv-3'].correct=2],['dependent completion',p=>p.historicalOutcome.raw.completed.a=false],['history length',p=>p.historicalOutcome.raw.drawingsB.K.history=Array.from({length:101},()=>structuredClone(p.drawingsB.K.graph))]];
test('A22 independent historical namespace, snapshot and serialization boundaries',()=>{const valid=load('native-revalidated.json');validateOlympiad(valid);for(const [name,mutate]of mutations){const p=structuredClone(valid);mutate(p);assert.throws(()=>validateOlympiad(p),name);}const deep={};let next=deep;for(let i=0;i<26;i++)next=next.child={};assert.throws(()=>safeJson(deep));const cycle={};cycle.child=cycle;assert.throws(()=>safeJson(cycle));assert.throws(()=>safeJson({mass:Infinity}));fs.writeFileSync(new URL('c3-history-boundaries.json',import.meta.url),JSON.stringify({status:'PASS',cases:mutations.map(x=>x[0]),serialization:['depth26','cyclic','nonfinite'],validHistory:true},null,2));});
test('A22 independent current chemical projection and source-policy bypass resistance',()=>{const rawK=sourceBank.stages.b.answers.find(s=>s.id==='K'),currentK=currentBAnswers.find(s=>s.id==='K'),wrong=rawK.alternatives.find(a=>a.smiles===c3KErratum.rejectedSourceSmiles),correct=rawK.alternatives.find(a=>a.smiles===c3KErratum.acceptedSmiles),draw=a=>({kind:'molecule',graph:structuredClone(a.graph),history:[]});assert.equal(rawK.alternatives.length,2);assert.equal(currentK.alternatives.length,1);assert.equal(core.formula(wrong.graph),'C2H4O4');assert.equal(core.formula(correct.graph),'C2H4O4');assert.equal(moleculeEngine.checkSubmission(draw(wrong)).status,'ready');assert.equal(moleculeMatches(draw(wrong),rawK),false);assert.equal(moleculeMatches(draw(correct),rawK),true);const raw=load('native-historical-wrong-k.json'),before=structuredClone(raw),revalidated=c3Policy.validateCompletion(chemicalChallenge,raw);assert.deepEqual(raw,before);assert.deepEqual(revalidated.historicalOutcome.raw,before);assert.deepEqual(revalidated.completed,{a:true,b:false,c:false});assert.deepEqual(c3Policy.validateCompletion(chemicalChallenge,revalidated),revalidated);for(const slot of [...currentBAnswers,...sourceBank.stages.c.answers])for(const a of slot.alternatives)assert.equal(moleculeMatches(draw(a),slot),true);assert.equal([...currentBAnswers,...sourceBank.stages.c.answers].reduce((n,s)=>n+s.alternatives.length,0),22);});
