import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';
import {bank as eb,energyProvider,energyRef,reviewCode} from '../../../src/activities/igcse/energy-enthalpy/provider.ts';
import {energyMarking} from '../../../src/activities/igcse/energy-enthalpy/marking.ts';
import {bank as pb,practicalProvider,practicalRef,correctionSegments} from '../../../src/activities/igcse/energetics-practical/provider.ts';
import {practicalMarking,practicalLearningReview,sourceResponse} from '../../../src/activities/igcse/energetics-practical/marking.ts';
import {modelProfile,initialProfile,checkProfile} from '../../../src/chemistry/energy-profile/index.ts';
import {profileSVG} from '../../../src/chemistry/energy-profile/svg.ts';
import {createAttemptController,assessmentToEvidence} from '../../../src/domain/attempt/attempt.ts';
import {createActiveClock} from '../../../src/domain/timing/active-clock.ts';
const original=new URL('../../../../Masters-of-IGCSE-Chemistry/src/activities/',import.meta.url),ctx={};
for(const a of ['energy-enthalpy','energetics-practical'])for(const f of ['data.js','core.js'])vm.runInNewContext(fs.readFileSync(new URL(`${a}/${f}`,original),'utf8'),ctx);
vm.runInNewContext(fs.readFileSync(new URL('../assets/question-review.js',original),'utf8'),ctx);const sourceCodes=ctx.QuestionReview.bank('EE',ctx.EnergyData.questions);
const plain=x=>JSON.parse(JSON.stringify(x));
function correctEnergy(q){return q.fields?Object.fromEntries(q.fields.map((f,i)=>[`field-${i}`,f.options?{kind:'choice',selected:[f.options.find(o=>f.accept.includes(o))]}:{kind:'text',value:f.accept[0]}])):{profile:modelProfile(q)};}
// Keep the construction readable rather than derive expected scores from the adapter.
function practicalAnswers(q){const r={};for(const [i,f] of q.fields.entries()){if(q.correction&&i===0){const {id,...range}=correctionSegments(q).find(s=>s.id===q.correction.errorId);r.correction={kind:'correction',selections:[range],replacement:f.answers[0]};}else r[f.id]=f.options?{kind:'choice',selected:f.multiselect?[...f.answers]:[f.options.find(o=>f.answers.includes(o))]}:{kind:'text',value:f.answers[0]};}return r;}
test('complete 54 energy and 14 practical banks equal independent original data, exact source IDs/levels/hashes and full routes',()=>{
 assert.deepEqual(plain(eb.questions),plain(ctx.EnergyData.questions));assert.deepEqual(plain(pb),plain(ctx.PRACTICAL_BANK.questions));assert.equal(eb.questions.length,54);assert.equal(pb.length,14);assert.equal(eb.questions.filter(q=>q.grade===1).length,28);assert.equal(eb.questions.filter(q=>q.grade===2).length,26);assert.equal(pb.filter(q=>q.band==='7-8').length,8);assert.equal(pb.filter(q=>q.band==='9').length,6);
 for(const q of eb.questions){assert.equal(reviewCode(q.id),sourceCodes.id(q));const ref=energyRef(q.id,0xffffffff);assert.equal(energyProvider.restore(ref).ref.questionId,q.id);assert.equal(energyProvider.resolveLink(reviewCode(q.id)).questionId,q.id);assert.equal(energyProvider.resolveLink(q.id).level,q.grade);assert.equal(energyProvider.restore(ref).parts.reduce((n,p)=>n+p.marks,0),q.points.length);}
 for(const q of pb){const ref=practicalRef(q.id,0xffffffff);assert.equal(practicalProvider.restore(ref).ref.questionId,q.id);assert.equal(practicalProvider.resolveLink(q.id).questionId,q.id);assert.equal(practicalProvider.restore(ref).parts.reduce((n,p)=>n+p.marks,0),q.fields.length+(q.correction?1:0));}
 for(const [provider,levels,id,gem] of [[energyProvider,[1,2],'energy-enthalpy','lower-10-1'],[practicalProvider,[2,3],'energetics-practical','lower-10-2']])for(const level of levels){const seen=[];const total=(id==='energy-enthalpy'?eb.questions.filter(q=>q.grade===level):pb.filter(q=>(q.band==='9'?3:2)===level)).length;for(let i=0;i<total;i++){const ref=provider.select({activityId:`igcse/${id}`,gemId:gem,level,seed:i,previousQuestionIds:seen});assert(!seen.includes(ref.questionId));seen.push(ref.questionId);}assert.equal(seen.length,total);}
 assert.throws(()=>energyProvider.restore({...energyRef('C01'),level:3}));assert.throws(()=>practicalProvider.restore({...practicalRef(pb[0].id),level:1}));
});
test('every energy accepted phrase and offered choice, unknown versus known wrong, missing responses, all profile references and semantic perturbations',()=>{
 for(const q of eb.questions){const question=energyProvider.restore(energyRef(q.id)),responses=correctEnergy(q),result=energyMarking.mark(question,responses);assert(result.accepted,q.id);assert.equal(result.marks.earned,q.points.length,q.id);
  if(q.fields){for(const [i,f] of q.fields.entries()){for(const value of f.accept){if(f.options&&!f.options.includes(value))continue;const testResponse={...responses,[`field-${i}`]:f.options?{kind:'choice',selected:[value]}:{kind:'text',value}};assert.equal(energyMarking.mark(question,testResponse).marks.earned,q.points.length,q.id+' '+value);}for(const value of [...(f.options??[]),'gibberishxyz','not any','', 'temperature']){const state=ctx.EnergyCore.markField(f,value,ctx.EnergyData);const outcome=energyMarking.mark(question,{...responses,[`field-${i}`]:f.options?{kind:'choice',selected:value?[value]:[]}:{kind:'text',value}});assert.equal(outcome.accepted,!['unknown','empty'].includes(state));if(outcome.accepted)assert.equal(outcome.marks.points[i].earned,state==='correct'?1:0);}}}
  else {assert.deepEqual(plain(modelProfile(q)),{kind:'energy-profile',...plain(ctx.EnergyCore.model(q))});assert.deepEqual(plain(initialProfile(q)),{kind:'energy-profile',...plain(ctx.EnergyCore.initial(q))});const model=modelProfile(q);for(const changed of [{...model,left:'wrong'}, {...model,right:'wrong'}, {...model,p:model.p<model.r?300:155},{...model,peak:330},{...model,vertical:'temperature'},{...model,horizontal:'time'},{...model,arrows:Object.fromEntries(Object.entries(model.arrows).map(([key,a])=>[key,{...a,tail:{anchor:'p'}}]))}]){assert.equal(checkProfile(changed,q).status,'ready');const expected=ctx.EnergyCore.check(q,changed,ctx.EnergyData),got=energyMarking.mark(question,{profile:changed});assert(got.accepted);assert.deepEqual(got.marks.points.map(p=>!!p.earned),plain(expected));}assert.equal(energyMarking.mark(question,{profile:{...model,peak:NaN}}).accepted,false);if(q.editor.arrows.length)assert.equal(energyMarking.mark(question,{profile:{...model,arrows:{}}}).accepted,false);assert.match(profileSVG(model,q.editor),/<svg/);}
 }
});
test('all practical source correct/incorrect/alternative scores, exact complete-set counts and correction phrase gates',()=>{
 for(const q of pb){const question=practicalProvider.restore(practicalRef(q.id)),responses=practicalAnswers(q),source=ctx.PracticalCore.gradeQuestion(q,sourceResponse(q,responses)),got=practicalMarking.mark(question,responses);assert(got.accepted);assert.equal(got.marks.earned,q.fields.length+(q.correction?1:0));assert.deepEqual(got.marks.points.map(p=>!!p.earned),plain(source.points.map(p=>p.correct)));
  assert.equal(practicalMarking.mark(question,{}).accepted,false);
  for(const [i,f] of q.fields.entries()){const partId=q.correction&&i===0?'correction':f.id;for(const answer of f.options??f.answers){const r={...responses,[partId]:q.correction&&i===0?{...responses.correction,replacement:answer}:f.options?{kind:'choice',selected:f.multiselect?f.answers:[answer]}:{kind:'text',value:answer}},expected=ctx.PracticalCore.gradeQuestion(q,sourceResponse(q,r)),outcome=practicalMarking.mark(question,r);assert(outcome.accepted);assert.deepEqual(outcome.marks.points.map(p=>!!p.earned),plain(expected.points.map(p=>p.correct)));}
   if(!f.options){const r={...responses,[partId]:q.correction&&i===0?{...responses.correction,replacement:'A chemically valid alternative requiring review'}:{kind:'text',value:'A chemically valid alternative requiring review'}},outcome=practicalMarking.mark(question,r);assert(outcome.accepted);const point=outcome.marks.points.find(p=>p.pointId===f.id);assert(point.learningReview.eligible);const frozen={responses:r,submittedAt:100,timing:{activeMs:20,idleLimitMs:180000},assistance:[]},assessment={kind:'marked',assessedAt:100,marks:outcome.marks,score:practicalMarking.masteryScore(outcome.marks),selfAssessed:false};const reviewed=practicalLearningReview.review(question,frozen,assessment,r,[{partId,pointId:f.id,judgement:'equivalent',reviewer:'student'}]);assert.equal(reviewed.reviewedMarks.earned,outcome.marks.earned+1);assert.equal(assessment.marks.earned,outcome.marks.earned);}
  }
  if(q.correction){const {id,...wrong}=correctionSegments(q).find(s=>s.id!==q.correction.errorId);const r={...responses,correction:{...responses.correction,selections:[wrong]}};const wrongOutcome=practicalMarking.mark(question,r);assert(wrongOutcome.accepted);assert.equal(wrongOutcome.marks.earned,0);assert(wrongOutcome.marks.points.every(p=>!p.learningReview));}
 }
});
const sample=ms=>({monotonicMs:ms,wallMs:100000+ms,visible:true,focused:true,suspended:false});
test('real shared controller keeps first response/timing/evidence immutable through unknown, wrong, correction and alternative review/reload',()=>{
 let now=sample(0);const q=practicalProvider.restore(practicalRef('EP-CXMNAV',7)),r=practicalAnswers(pb.find(q=>q.id==='EP-CXMNAV'));r.correction.replacement='limits energy exchange';const state={mode:'student',namespace:{course:'igcse',profileId:'A13'},attemptId:'A13-test',ref:q.ref,target:{course:'igcse',activityId:q.ref.activityId,gemId:'lower-10-2',level:q.ref.level},phase:'answering',currentResponses:r,assistance:[],timing:{attemptId:'A13-test',activeMs:0,idleLimitMs:180000,finished:false}};const clock=createActiveClock({attemptId:state.attemptId,idleLimitMs:180000,now:()=>now,saved:state.timing});const c=createAttemptController({question:q,state,policy:practicalMarking,learningReviewPolicy:practicalLearningReview,clock,sample:()=>now});now=sample(2000);const submitted=c.dispatch({kind:'submit',at:now.wallMs});assert(submitted.accepted);const first=plain(c.state().firstAssessment),time=plain(c.state().firstResponse.timing),evidence=plain(assessmentToEvidence(c.state()));assert.equal(first.score,0.5);c.dispatch({kind:'review-valid-alternative',decision:{partId:'correction',pointId:'replacement',judgement:'equivalent',reviewer:'student'}});assert.equal(c.state().learningReview.reviewedMarks.earned,2);c.dispatch({kind:'respond',partId:'correction',response:{...r.correction,replacement:'reduces'}});now=sample(600000);const corrected=c.dispatch({kind:'check-correction'});assert.equal(corrected.correctionFeedback.status,'correct');assert.deepEqual(plain(c.state().firstAssessment),first);assert.deepEqual(plain(c.state().firstResponse.timing),time);assert.deepEqual(plain(assessmentToEvidence(c.state())),evidence);assert.equal(plain(JSON.parse(JSON.stringify(c.state()))).ref.questionId,'EP-CXMNAV');
});


test('source provenance unchanged and every energy equation balances atoms with declared polarity',()=>{const fingerprints=JSON.parse(fs.readFileSync(new URL('../../s3/energy/source-fingerprints.json',import.meta.url),'utf8'));for(const [file,hash] of Object.entries(fingerprints))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),hash);function side(raw){const counts={};for(const molecule of raw.split('+')){const clean=molecule.trim().replace(/[\u2080-\u2089]/g,c=>String(c.charCodeAt(0)-0x2080)).replace(/\([gls]\)/g,''),parts=clean.match(/^(\d+)?(.*)$/),coeff=Number(parts[1]||1);for(const [_,atom,count]of parts[2].matchAll(/([A-Z][a-z]?)(\d*)/g))counts[atom]=(counts[atom]||0)+coeff*Number(count||1);}return Object.fromEntries(Object.entries(counts).sort());}for(const q of eb.questions.filter(q=>q.equation)){const [left,right]=q.equation.split('\u2192');assert.deepEqual(side(left),side(right),q.id);if(q.enthalpyText&&q.polarity)assert.equal(q.enthalpyText.includes('\u2212'),q.polarity==='exo',q.id);}});
