import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {bank} from '../../../src/activities/alevel/dot-and-cross/bank.js';import {modelSVG} from '../../../src/chemistry/dot-and-cross/model.ts';import {check,validateReference} from '../../../src/chemistry/dot-and-cross/core.js';
const root=path.resolve(import.meta.dirname,'../../..'),out=import.meta.dirname,entries=[];
for(const id of ['boron-trifluoride','sulfur-hexafluoride','phosphorus-pentachloride','sulfur-tetrafluoride','chlorine-trifluoride','nitrate-ion','tetrahydridoaluminate-ion','sodium-borohydride']){const r=bank.find(r=>r.id===id);assert(r);entries.push({id,kind:'A-level advanced dot and cross',svg:modelSVG(r),record:r});}
const dir=path.join(root,'src/activities/olympiad/c3l6/assets/digitised');
for(const sub of ['intro','a','b','c'])for(const f of fs.readdirSync(path.join(dir,sub)).filter(f=>f.endsWith('.svg')).sort())entries.push({id:sub+'/'+f,kind:'Current C3 retained asset',svg:fs.readFileSync(path.join(dir,sub,f),'utf8')});
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
for(let i=0;i<entries.length;i+=4)fs.writeFileSync(path.join(out,`diagrams-${String(21+i/4).padStart(2,'0')}.html`),'<!doctype html><meta charset="utf-8"><style>body{font:18px Arial;margin:24px}section{border-bottom:2px solid #ddd;padding:14px}img{display:block;max-width:100%;max-height:520px}h2{font-size:20px}</style>'+entries.slice(i,i+4).map(e=>`<section><h2>${esc(e.kind+' '+e.id)}</h2><img style="background:${/^(intro|a|c)\//.test(e.id)?'#0a0d26':'white'}" src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(e.svg)}"></section>`).join(''));
fs.writeFileSync(path.join(out,'additional-diagram-index.json'),JSON.stringify(entries.map((e,i)=>({id:e.id,kind:e.kind,sha256:crypto.createHash('sha256').update(e.svg).digest('hex'),page:21+Math.floor(i/4)})),null,2));
console.log({additionalDiagrams:entries.length});
