import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {acidProvider} from '../../../src/activities/alevel/acid-base-calculations/provider.ts';import {acidEngine} from '../../../src/activities/alevel/acid-base-calculations/engine.js';import {electronsBondingProvider} from '../../../src/activities/alevel/electrons-bonding/provider.ts';import {data as bondingData} from '../../../src/activities/alevel/electrons-bonding/data.js';import {productionRegistry} from '../../../src/foundation/registry.ts';
const root=path.resolve(import.meta.dirname,'../../..'),out=import.meta.dirname,require=createRequire(path.resolve(root,'../../package.json')),{chromium}=require('playwright'),sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const server=http.createServer((req,res)=>{try{const parts=decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname).split('/').filter(Boolean);if(!['alevel','igcse'].includes(parts[0]))throw Error('route');const base=path.resolve(root,'dist',parts[0]),file=path.resolve(base,...parts.slice(1));if(!file.startsWith(base+path.sep)||!fs.existsSync(file))throw Error('scope');const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf'};res.writeHead(200,{'content-type':mime[path.extname(file)]??'application/octet-stream','cache-control':'no-store'});fs.createReadStream(file).pipe(res);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(5202,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true}),report={at:new Date().toISOString(),status:'RUNNING',browser:browser.version(),playwright:require('playwright/package.json').version,checks:[],errors:[],screenshots:[]};let context;
async function fresh(){await context?.close();context=await browser.newContext({viewport:{width:1360,height:1000}});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));return page;}
async function ready(page){await page.waitForFunction(()=>window.__mastersActivity!==undefined);await page.waitForFunction(()=>window.__mastersActivity.snapshot().saveStatus.kind!=='saving');}
async function shot(page,name){const file=path.join(out,name+'.png');await page.screenshot({path:file,fullPage:true});report.screenshots.push({file:path.basename(file),sha256:sha(fs.readFileSync(file))});}
async function teacher(page,ref){await page.goto('http://127.0.0.1:5202/alevel/index.html?'+new URLSearchParams({view:'teacher',activity:ref.activityId,review:ref.questionId,level:String(ref.level),seed:String(ref.seed)}));await page.locator('.teacher-answer').waitFor();await ready(page);return page.evaluate(()=>window.__mastersActivity.snapshot());}
async function fixture(page,ref){await page.goto('http://127.0.0.1:5202/alevel/index.html?view=practice&activity='+encodeURIComponent(ref.activityId));await ready(page);const registration=productionRegistry.get(ref.activityId),q=(await registration.provider()).restore(ref),gem=registration.gems.find(g=>g.supportedLevels.includes(ref.level)),id='A22-chemical-'+ref.questionId,namespace={course:'alevel',profileId:'local'},target={course:'alevel',activityId:ref.activityId,gemId:gem.id,level:ref.level},attempt={mode:'student',namespace,attemptId:id,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:registration.idleAllowance(q),finished:false}},session={kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:id,previousQuestionIds:[]};
 await page.evaluate(async({attempt,session})=>{const name=window.__mastersActivity.snapshot().databaseName;await new Promise((resolve,reject)=>{const request=indexedDB.open(name);request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction(['attempts','sessions'],'readwrite');tx.objectStore('attempts').put({course:'alevel',profileId:'local',id:attempt.attemptId,value:attempt});tx.objectStore('sessions').put({course:'alevel',profileId:'local',id:'current-session',value:session});tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error);};});},{attempt,session});await page.reload();await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.ref.questionId===id,ref.questionId);await ready(page);return q;}
try{
 let page=await fresh();for(const id of ['AB-0000SN','AB2-3-1-1','ABL-00000V']){const ref=acidProvider.resolveLink(id),snapshot=await teacher(page,ref),expected=acidProvider.restore(ref);assert.deepEqual(snapshot.question,expected);const body=await page.locator('body').innerText();for(const p of expected.parts)for(const b of p.prompt)if(b.kind==='text')assert(body.includes(b.text));assert.equal(snapshot.history.length,0);await shot(page,'final-teacher-'+id);report.checks.push({kind:'final-production-precision',id,ref,exactQuestion:true,noEvidence:true});}
 for(const record of bondingData.questions){page=await fresh();const ref=electronsBondingProvider.resolveLink(record.id),snapshot=await teacher(page,ref);assert.deepEqual(snapshot.question,electronsBondingProvider.restore(ref));if(['EB07','EB08','EB09'].includes(record.id))await shot(page,'final-teacher-'+record.id);report.checks.push({kind:'final-production-bonding14',id:record.id,prompt:snapshot.question.context[0].text,unchangedAnswer:true});}
 page=await fresh();const ref=acidProvider.resolveLink('AB2-3-1-1'),q=await fixture(page,ref),source=acidEngine.generateFromReview(ref.questionId),inputs=page.locator('.question-parts input');assert.equal(await inputs.count(),source.responses.length);for(let n=0;n<source.responses.length;n++){const r=source.responses[n];await inputs.nth(n).fill(r.format==='dp2'?r.expected.toFixed(2):r.expected.toPrecision(3));}await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.evaluate(()=>window.__mastersActivity.flush());const graded=await page.evaluate(()=>window.__mastersActivity.snapshot());assert.equal(graded.attempt.firstAssessment.marks.earned,source.responses.length);await shot(page,'final-pupil-acid-format');report.checks.push({kind:'final-production-pupil-marking',id:ref.questionId,earned:graded.attempt.firstAssessment.marks.earned,available:source.responses.length,pupilInstructionAgree:true});
 for(const [id,answer] of [['EB07','3'],['EB08','5'],['EB09','giant ionic lattice']]){page=await fresh();const ref=electronsBondingProvider.resolveLink(id);await fixture(page,ref);await page.locator('.question-parts input,.question-parts textarea').first().fill(answer);await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.evaluate(()=>window.__mastersActivity.flush());const s=await page.evaluate(()=>window.__mastersActivity.snapshot());assert.equal(s.attempt.firstAssessment.marks.earned,s.attempt.firstAssessment.marks.available);await shot(page,'final-pupil-'+id);report.checks.push({kind:'final-production-qualified-pupil-marking',id,answer,prompt:s.question.context[0].text,score:s.attempt.firstAssessment.score});}
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;if(context){const pages=context.pages();if(pages[0])await shot(pages[0],'final-browser-failure').catch(()=>{});}console.error(e);}
finally{await context?.close();await browser.close();await new Promise(r=>server.close(r));report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'production-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,errors:report.errors}));}
