import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const project=path.resolve(import.meta.dirname,'../../../..'),require=createRequire(path.join(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');
const temp=path.join(import.meta.dirname,'.browser-temp');fs.mkdirSync(temp,{recursive:true});process.env.TEMP=temp;process.env.TMP=temp;
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true,args:[`--disk-cache-dir=${temp}/cache`]}),context=await browser.newContext({acceptDownloads:true}),page=await context.newPage();
const report={startedAt:new Date().toISOString(),browser:await browser.version(),playwright:'1.62.1',checks:[],pageErrors:[]};page.on('pageerror',e=>report.pageErrors.push(e.message));
try{
 await context.addInitScript(()=>{window.f1StorageCalls=[];for(const method of ['getItem','setItem','removeItem']){const original=Storage.prototype[method];Storage.prototype[method]=function(key,...args){window.f1StorageCalls.push({method,key});return original.call(this,key,...args);};}const original=indexedDB.open.bind(indexedDB);indexedDB.open=function(name,...args){window.f1StorageCalls.push({method:'indexedDB.open',key:name});return original(name,...args);};});
 await page.goto('http://127.0.0.1:5181/alevel.html?view=import&run=f1-identity');
 await page.getByRole('heading',{name:'Import or export progress'}).waitFor();
 const setup=await page.evaluate(async()=>{
  const {alphaDatabaseName}=await import('/src/persistence/alpha-namespace.ts');
  const {createChemistryRepository}=await import('/src/persistence/index.ts');
  const {acidProvider,acidRef}=await import('/src/activities/alevel/acid-base-calculations/provider.ts');
  const {acidEngine}=await import('/src/activities/alevel/acid-base-calculations/engine.js');
  const {acidMarking}=await import('/src/activities/alevel/acid-base-calculations/marking.ts');
  const {createActiveClock}=await import('/src/domain/timing/active-clock.ts');
  const {createAttemptController,assessmentToEvidence}=await import('/src/domain/attempt/attempt.ts');
  const namespace={course:'alevel',profileId:'local'},source=acidEngine.generate('h-to-ph',1,7),question=acidProvider.restore(acidRef(source));
  let sample={monotonicMs:0,wallMs:100000,visible:true,focused:true,suspended:false};
  const state={mode:'student',namespace,attemptId:'F1-identity-first',ref:question.ref,target:{course:'alevel',activityId:question.ref.activityId,gemId:'u6-t1-1-2',level:1},phase:'answering',currentResponses:Object.fromEntries(source.responses.map(r=>[r.key,{kind:'numeric',raw:String(r.expected),unit:r.unit}])),assistance:[],timing:{attemptId:'F1-identity-first',activeMs:0,idleLimitMs:60000,finished:false}};
  const clock=createActiveClock({attemptId:state.attemptId,idleLimitMs:60000,now:()=>sample});
  const controller=createAttemptController({question,state,policy:acidMarking,clock,sample:()=>sample});
  sample={...sample,monotonicMs:2500,wallMs:102500};const assessed=controller.dispatch({kind:'submit',at:sample.wallMs});
  if(!assessed.accepted)throw Error('Assessment blocked: '+assessed.message);
  const evidence=assessmentToEvidence(controller.state());
  const repo=createChemistryRepository(alphaDatabaseName('alevel','f1-identity'));
  const saved=await repo.saveCurriculum({attempt:controller.state(),evidence});if(!saved.ok)throw Error(saved.error.message);
  const loaded=await repo.loadAttempt(namespace,state.attemptId);if(!loaded.ok)throw Error(loaded.error.message);
  const before=JSON.stringify(evidence);controller.dispatch({kind:'respond',partId:source.responses[0].key,response:{kind:'numeric',raw:'999',unit:source.responses[0].unit}});
  sample={...sample,monotonicMs:500000,wallMs:600000};controller.dispatch({kind:'check-correction'});
  if(JSON.stringify(assessmentToEvidence(controller.state()))!==before)throw Error('Correction changed first evidence');
  const session={kind:'practice',namespace,id:'F1-canonical-session',target:state.target,selection:'fixed-level',currentAttemptId:state.attemptId,previousQuestionIds:[question.ref.questionId],paused:true};
  const sessionSaved=await repo.saveSession(session),sessionLoaded=await repo.loadSession(namespace,session.id);
  if(!sessionSaved.ok||!sessionLoaded.ok||JSON.stringify(sessionLoaded.value)!==JSON.stringify(session))throw Error('Canonical session restore failed');
  const revision={kind:'revision',namespace,id:'F1-canonical-revision',createdAt:100000,status:'paused',selectedGemIds:['u6-t1-1-2'],levels:[{target:state.target,mode:'check',required:1,streak:0,confirmedAt:null,initialScore:null}],round:['u6-t1-1-2'],lastGemId:null,current:{attemptId:state.attemptId,target:state.target,ref:question.ref,completed:true},previous:[{target:state.target,ref:question.ref}],submittedAttemptIds:[state.attemptId]};
  const revisionSaved=await repo.saveSession(revision),revisionLoaded=await repo.loadSession(namespace,revision.id);
  if(!revisionSaved.ok||!revisionLoaded.ok||JSON.stringify(revisionLoaded.value)!==JSON.stringify(revision))throw Error('Canonical revision restore failed');
  const oldRepo=createChemistryRepository('masters-of-chemistry-alevel-local'),oldLoad=await oldRepo.curriculumHistory(namespace);oldRepo.close();
  repo.close();return {ref:question.ref,loaded:loaded.value,evidence,oldStoreGuard:oldLoad,storage:window.f1StorageCalls};
 });
 assert(setup.oldStoreGuard.ok===false);assert.equal(setup.oldStoreGuard.error.code,'invalid-data');assert.match(setup.ref.questionId,/^AB-[A-Z0-9]{6}$/);assert.equal(setup.evidence.timing.activeMs,2500);assert.deepEqual(setup.loaded.ref,setup.ref);
 report.checks.push({name:'real IndexedDB canonical attempt/practice/revision save/restore; first-score/time immutable after correction',status:'PASS',ref:setup.ref,activeMs:setup.evidence.timing.activeMs});
 const downloadWait=page.waitForEvent('download');await page.getByRole('button',{name:'Export current progress'}).click();const download=await downloadWait;
 const file=path.join(import.meta.dirname,'current-export.json');await download.saveAs(file);const batch=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(batch.curriculum.length,1);assert.deepEqual(batch.curriculum[0],setup.evidence);
 await page.reload();await page.getByRole('heading',{name:'Import or export progress'}).waitFor();await page.getByLabel('Upload current export').setInputFiles(file);await page.getByRole('button',{name:'Preview import'}).click();await page.getByRole('status').filter({hasText:'1 current records ready'}).waitFor();await page.getByRole('button',{name:'Import reviewed progress'}).click();await page.getByRole('status').filter({hasText:'0 imported; 1 already present'}).waitFor();
 report.checks.push({name:'actual UI export / reload / import deduplicates exact current first evidence',status:'PASS'});
 await page.goto('http://127.0.0.1:5181/alevel.html?view=import&run=f1-identity-import-target');await page.getByRole('heading',{name:'Import or export progress'}).waitFor();await page.getByLabel('Upload current export').setInputFiles(file);await page.getByRole('button',{name:'Preview import'}).click();await page.getByRole('status').filter({hasText:'1 current records ready'}).waitFor();await page.getByRole('button',{name:'Import reviewed progress'}).click();await page.getByRole('status').filter({hasText:'1 imported; 0 already present'}).waitFor();
 const imported=await page.evaluate(async()=>{const {createChemistryRepository}=await import('/src/persistence/index.ts');const repo=createChemistryRepository('masters-of-chemistry-alpha-v2-alevel-f1-identity-import-target');const r=await repo.curriculumHistory({course:'alevel',profileId:'local'});repo.close();return r;});assert(imported.ok);assert.deepEqual(imported.value,[setup.evidence]);
 report.checks.push({name:'current canonical import into fresh database preserves evidence exactly',status:'PASS'});
 const invalid={...batch,curriculum:[{...batch.curriculum[0],ref:{...batch.curriculum[0].ref,questionId:'AB2-0-1-7'}}]};await page.getByLabel('Current export JSON').fill(JSON.stringify(invalid));await page.getByRole('button',{name:'Preview import'}).click();await page.getByRole('status').filter({hasText:'Invalid question reference'}).waitFor();assert(await page.getByRole('button',{name:'Import reviewed progress'}).isDisabled());
 report.checks.push({name:'obsolete internal code rejected before import',status:'PASS'});
 const cross={...batch,namespace:{course:'igcse',profileId:'local'}};await page.getByLabel('Current export JSON').fill(JSON.stringify(cross));await page.getByRole('button',{name:'Preview import'}).click();await page.getByRole('status').filter({hasText:'Import namespace/source mismatch'}).waitFor();
 report.checks.push({name:'cross-course import rejected',status:'PASS'});
 const calls=await page.evaluate(()=>window.f1StorageCalls);report.storageCalls=calls;
 await page.screenshot({path:path.join(import.meta.dirname,'current-import-browser.png'),fullPage:true});
 await page.goto('http://127.0.0.1:5181/alevel.html?view=home&run=f1-identity');
 await page.locator('.original-landing').waitFor();
 const landingCalls=await page.evaluate(()=>window.f1StorageCalls);report.landingStorageCalls=landingCalls;calls.push(...landingCalls);
 for(const call of [...setup.storage,...calls])assert(call.key.startsWith('masters-of-chemistry-alpha-v2'),JSON.stringify(call));
 report.checks.push({name:'instrumented localStorage/IndexedDB all reads/writes/opens use alpha-v2 namespace; old database rejected without open',status:'PASS'});
 assert.deepEqual(report.pageErrors,[]);report.status='PASS';
}catch(error){report.status='FAIL';report.error=String(error);throw error;}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(import.meta.dirname,'browser-results.json'),JSON.stringify(report,null,2));await browser.close();}
