import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {reviewedMethanolSynthesisSVG} from '../../../src/chemistry/thermochemistry/reviewed-co-svg.ts';
import {data} from '../../../src/chemistry/thermochemistry/bond-enthalpy-data.js';
const here=import.meta.dirname,project=resolve(here,'../../..'),hash=content=>createHash('sha256').update(content).digest('hex');
const provenance=JSON.parse(readFileSync(resolve(here,'provenance.json'),'utf8'));
const original=data.reactions.find(r=>r.id==='methanol-synthesis').svg;
assert.equal(hash(original),'8290640db0821f819075df57ea3d85f2828fdb9139aa8721ef3e85a0802d4da7');
assert.equal(hash(reviewedMethanolSynthesisSVG),'02de76dd4029588cd04a591c7bb514fb2b6103f5ce96239e24543ec5babae2eb');
assert.equal(reviewedMethanolSynthesisSVG.replace(provenance.correction.insertedElement,''),original);
assert.equal(hash(readFileSync(resolve(project,'../Masters-of-IGCSE-Chemistry/src/activities/bond-enthalpy/data.js'))),provenance.source.fileSha256);
const chemistry=JSON.parse(readFileSync(resolve(here,'chemistry-check.json'),'utf8')),render=JSON.parse(readFileSync(resolve(here,'render-results.json'),'utf8'));
assert.equal(chemistry.status,'PASS');assert.equal(render.status,'PASS');assert.equal(render.xml.negativePaths,1);assert.equal(render.xml.parseErrors,0);assert.equal(render.playwright,'1.62.1');assert.deepEqual(render.errors,[]);
assert.equal(provenance.bondCalculation.brokenTotal-provenance.bondCalculation.madeTotal,provenance.bondCalculation.deltaH);
assert.equal(provenance.bondCalculation.deltaH,-119);
const images=['desktop-before-after.png','reviewed-full-reaction.png','mobile-full-reaction.png','mobile-co-charge-detail.png'];
provenance.status='PASS';provenance.reviewedAt=new Date().toISOString();provenance.reviewedBy='A07 independent chemistry/charge/render review';
provenance.source.copiedDataFileSha256=hash(readFileSync(resolve(project,'src/chemistry/thermochemistry/bond-enthalpy-data.js')));
provenance.validation={chemistry:'chemistry-check.json',xml:'render-results.json',byteRecovery:'Removal of exactly the inserted carbon-minus vector recovers the entire inherited SVG byte-for-byte',supplementaryRdkit:'2025.09.1; Python3.13.5; read-only invariants, no rendering or managed regeneration claimed',manualVisualInspection:{status:'PASS',observation:'Inspected the full reaction before/after, corrected883px reaction and390px/mobile358px image: superscriptC-minus andO-plus are distinct, triple bond retained, no label collision or clipping; methanol/hydrogen/coefficient/arrow geometry unchanged.',images:images.map(path=>({path,sha256:hash(readFileSync(resolve(here,path)))}))},scripts:['create-reviewed-svg.mjs','check_chemistry.py','render-review.mjs','accept-review.mjs'].map(path=>({path,sha256:hash(readFileSync(resolve(here,path)))}))};
writeFileSync(resolve(here,'provenance.json'),JSON.stringify(provenance,null,2)+'\n');
console.log(JSON.stringify({status:provenance.status,originalSha256:provenance.source.originalSvgSha256,reviewedSha256:provenance.correction.newSvgSha256,deltaH:provenance.bondCalculation.deltaH}));
