import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import prettier from 'prettier';

const project = path.resolve(import.meta.dirname, '..');
const sources = {
  alevel: 'apps/Masters-of-A-Level-Chemistry/src/activities/flashcards/cards.js',
  igcse: 'development/igcse/activities/recall/reviews/Rocket Recall - questions and allowed answers.csv',
};
const raw = Object.fromEntries(Object.entries(sources).map(([course, name]) => [course, fs.readFileSync(path.resolve(project, '../..', name), 'utf8')]));
const sha = (text) => crypto.createHash('sha256').update(text).digest('hex');
const marker = 'globalThis.FLASHCARDS = ';
assert(raw.alevel.includes(marker));
const approved = JSON.parse(raw.alevel.slice(raw.alevel.indexOf(marker) + marker.length).trim().replace(/;$/, ''));
assert.equal(approved.length, 6, 'Changed source bank needs a fresh scope review');

// Quoted fields, escaped quotes and embedded newlines in the teacher-owned CSV.
function csv(text) {
  text = text.replace(/^\uFEFF/, '');
  const rows = []; let row = [], field = '', quoted = false;
  for (let index = 0; index < text.length; index++) {
    const char = text[index];
    if (char === '"') {
      if (quoted && text[index + 1] === '"') { field += '"'; index++; }
      else quoted = !quoted;
    } else if (!quoted && (char === ',' || char === '\n')) {
      row.push(field.replace(/\r$/, '')); field = '';
      if (char === '\n') { rows.push(row); row = []; }
    } else field += char;
  }
  assert(!quoted, 'Unclosed CSV quote');
  if (field || row.length) { row.push(field.replace(/\r$/, '')); rows.push(row); }
  const headers = rows.shift();
  return rows.filter((r) => r.some(Boolean)).map((r) => Object.fromEntries(headers.map((h, i) => [h, r[i] ?? ''])));
}
const ids = ['igcse-recall-012', 'igcse-recall-007', 'igcse-recall-009', 'igcse-recall-010', 'igcse-recall-011', 'igcse-recall-013'];
const rows = csv(raw.igcse);
const selected = ids.map((id) => {
  const matches = rows.filter((row) => row['Question ID'] === id);
  assert.equal(matches.length, 1, `Missing or multipart starter card ${id}`);
  const row = matches[0];
  assert.equal(row['Needs further work'], '', `Unresolved teacher review: ${id}`);
  assert(row.Question && row['Allowed answer 1']);
  return row;
});
const card = (id, prompt, answer) => ({ id, prompt: [{ kind: 'text', text: prompt }], answer: [{ kind: 'text', text: answer }] });
const decks = {
  alevel: approved.map((source) => {
    let { id, prompt, answer } = source;
    if (id === 'orbital-filling-rules') prompt = 'What rules are used to fill orbitals in the ground-state electron configuration of an atom?';
    if (id === 'ionic-lattice') { id = 'ionic-lattice-solid'; prompt = 'What structure do solid ionic compounds have?'; }
    return card(id, prompt, answer);
  }),
  igcse: selected.map((row) => card(row['Question ID'], row.Question, row['Allowed answer 1'])),
};
for (const deck of Object.values(decks)) assert.equal(new Set(deck.map((c) => c.id)).size, deck.length);
const config = JSON.parse(fs.readFileSync(path.join(project, '.prettierrc.json')));
const generated = await prettier.format(`import type { Course } from '../contracts/identity.ts';\nimport type { Flashcard } from './FlashcardTable.tsx';\n// Generated by scripts/prepare_recall.mjs; source and adaptations in provenance.json.\nexport const starterDecks: Readonly<Record<Course, readonly Flashcard[]>> = ${JSON.stringify(decks)};\n`, { ...config, parser: 'typescript' });
const provenance = {
  sources: Object.fromEntries(Object.entries(sources).map(([course, source]) => [course, { path: source, sha256: sha(raw[course]) }])),
  authority: 'Six approved A-level records and six unflagged single-answer records from the teacher-reviewed IGCSE CSV. Starter scope only.',
  alevel: approved.map((source, index) => ({ id: decks.alevel[index].id, sourceId: source.id, spec: source.spec })),
  igcse: ids,
  adaptations: [
    { sourceId: 'orbital-filling-rules', reason: 'Correct grammatical omission and final punctuation; chemistry and answer unchanged.' },
    { sourceId: 'ionic-lattice', id: 'ionic-lattice-solid', reason: 'Explicitly qualify solid state. Separate runtime ID preserves the original question.' },
  ],
  originals: { alevel: approved.map(({ id, prompt, answer, spec }) => ({ id, prompt, answer, spec })), igcse: selected },
};
for (const [name, text] of [['starter-decks.ts', generated], ['provenance.json', JSON.stringify(provenance, null, 2) + '\n']]) {
  const file = path.join(project, 'src/recall', name);
  if (process.argv.includes('--write')) fs.writeFileSync(file, text);
  else assert.equal(fs.readFileSync(file, 'utf8'), text, `${name} differs from reviewed inputs`);
}
console.log('PASS: six course-appropriate starter cards per course; reviewed sources and adaptations retained.');
