import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const project=path.resolve(import.meta.dirname,'..'),workspace=path.resolve(project,'../..');
const read=p=>JSON.parse(fs.readFileSync(path.join(project,p),'utf8').replace(/^\uFEFF/,''));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const manifest=read('resources/source-generation/inventory/coverage-manifest.json'),control=read('resources/source-generation/controls/control-start.json'),lock=read('resources/source-generation/controls/root-contract-lock.json'),contract=read('project-contract.json');
const aliases={'validation/original-app-baseline.json':'resources/source-generation/controls/original-app-baseline.json','validation/root-contract-lock.json':'resources/source-generation/controls/root-contract-lock.json'};
const controls=Object.entries(control.files).map(([originalPath,expectedSha256])=>{const currentPath=aliases[originalPath]||originalPath,absolute=path.join(project,currentPath),actualSha256=fs.existsSync(absolute)?hash(fs.readFileSync(absolute)):null;return {originalPath,currentPath,expectedSha256,actualSha256,status:expectedSha256===actualSha256?'PASS':'FAIL'};});
const sourceFailures=[];
for(const source of manifest.sources){const p=path.resolve(workspace,source.path);if(!fs.existsSync(p)){sourceFailures.push({path:source.path,reason:'missing'});continue;}const b=fs.readFileSync(p);if(b.length!==source.bytes||hash(b)!==source.sha256)sourceFailures.push({path:source.path,reason:'byte/hash mismatch'});}
const structuralFailures=[];
const ids=values=>values.map(a=>a.id).sort();
const typedIds=[...new Set(fs.readFileSync(path.join(project,'src/contracts/identity.ts'),'utf8').match(/(?:alevel|igcse)\/[a-z0-9-]+/g))].sort();
if(new Set(manifest.sources.map(s=>s.path)).size!==manifest.sources.length)structuralFailures.push('duplicate frozen source paths');
if(JSON.stringify(typedIds)!==JSON.stringify(ids(contract.activities)))structuralFailures.push('current typed IDs differ from current contract');
const challenge=manifest.activities.find(a=>a.id==='alevel/c3l6-organic-reactions');
if(!challenge||challenge.strand!=='olympiad'||challenge.leafIds.length||challenge.supportedLevels.length||Object.keys(challenge.masteryRegistrations).length)structuralFailures.push('frozen Olympiad isolation changed');
if(manifest.activities.some(a=>!a.entrypoint.endsWith('/index.html')||!a.sourceHashes.length||!a.sourceEvidence))structuralFailures.push('invalid frozen provenance metadata');
const runtimeScope=spawnSync(process.execPath,[path.join(project,'scripts/write-s0-scope.mjs'),'--check'],{cwd:project,encoding:'utf8'});
if(runtimeScope.status!==0)structuralFailures.push('source-derived runtime scope equality check failed; scripts/write-s0-scope.mjs --check');
const scopeArtifacts=path.join(project,'.artifacts/source-generation');fs.mkdirSync(scopeArtifacts,{recursive:true});fs.writeFileSync(path.join(scopeArtifacts,'runtime-scope-check.log'),(runtimeScope.stdout||'')+'\n'+(runtimeScope.stderr||''));
const historicalFailures=controls.filter(c=>c.status==='FAIL').map(c=>'historical control differs: '+c.originalPath);
if(hash(fs.readFileSync(path.join(project,'project-contract.json')))!==lock.sha256)historicalFailures.push('current contract differs from historical S0 lock');
if(JSON.stringify(ids(manifest.activities))!==JSON.stringify(ids(contract.activities)))historicalFailures.push('current activities differ from frozen twelve-activity S0 scope');
const sourcesOnly=process.argv.includes('--sources-only');
const report={schemaVersion:1,status:sourceFailures.length||structuralFailures.length||(!sourcesOnly&&historicalFailures.length)?'FAIL':'PASS',mode:sourcesOnly?'sources-only':'historical-s0-baseline',checkedAt:new Date().toISOString(),activities:manifest.activities.length,sources:manifest.sources.length,sourceCheck:{status:sourceFailures.length?'FAIL':'PASS',failures:sourceFailures},structuralCheck:{status:structuralFailures.length?'FAIL':'PASS',failures:structuralFailures},historicalBaseline:{status:historicalFailures.length?'DIFFERS':'UNCHANGED',recordedAt:control.recordedAt,controls,failures:historicalFailures,originalContractSha256:lock.sha256},retiredChecks:['Historical worker handover/output existence checks were stage machinery removed with authorised validation cleanup. Source-derived runtime scope equality remains executable through scripts/write-s0-scope.mjs --check.','Current catalogue check: node scripts/write-catalogue-definitions.mjs --check'],limitations:['This deterministic source check does not claim new chemistry or rendered acceptance.','Frozen sourceEvidence fields preserve historical identifiers; deleted review files are not runtime or regeneration inputs.','--sources-only explicitly excludes historical-control equality from command exit status; baseline differences remain visible.']};
const artifacts=path.join(project,'.artifacts/source-generation');fs.mkdirSync(artifacts,{recursive:true});fs.writeFileSync(path.join(artifacts,'source-and-historical-controls.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;
