// Generated by scripts/source-generation/structure/extract-source.mjs; original source is read only.
import type {SourceReference} from '../../../contracts/identity.ts';
export interface Comparison {readonly id:string; readonly focus:'melting-boiling'|'conductivity'|'hardness';readonly left:Readonly<{name:string;property:string}>;readonly right:Readonly<{name:string;property:string}>;readonly prompt:string;readonly points:readonly Readonly<{text:string;reject?:string}>[];}
export const comparisons:readonly Comparison[]=[
  {
    "id": "water-sodium-chloride-melting",
    "focus": "melting-boiling",
    "left": {
      "name": "Water",
      "property": "low melting point"
    },
    "right": {
      "name": "Sodium chloride",
      "property": "high melting point"
    },
    "prompt": "Explain, in terms of their structure and bonding, why water has a low melting point but sodium chloride has a high melting point.",
    "points": [
      {
        "text": "Water has covalent bonding and a simple molecular structure."
      },
      {
        "text": "Sodium chloride has ionic bonding and a giant lattice structure."
      },
      {
        "text": "The intermolecular forces between water molecules are weak.",
        "reject": "Do not award if the response says the covalent bonds are weak or that covalent bonds break when water melts."
      },
      {
        "text": "Strong electrostatic attractions act between oppositely charged ions; accept between sodium ions, Na⁺, and chloride ions, Cl⁻.",
        "reject": "Do not award if sodium chloride is described using intermolecular forces, covalent bonds or molecules."
      },
      {
        "text": "Less energy is needed to overcome the intermolecular forces in water, so water has the lower melting point."
      }
    ]
  },
  {
    "id": "methane-magnesium-oxide-boiling",
    "focus": "melting-boiling",
    "left": {
      "name": "Methane",
      "property": "low boiling point"
    },
    "right": {
      "name": "Magnesium oxide",
      "property": "high boiling point"
    },
    "prompt": "Explain, in terms of their structure and bonding, why methane has a low boiling point but magnesium oxide has a high boiling point.",
    "points": [
      {
        "text": "Methane has covalent bonding and a simple molecular structure."
      },
      {
        "text": "Magnesium oxide has ionic bonding and a giant lattice structure."
      },
      {
        "text": "The intermolecular forces between methane molecules are weak.",
        "reject": "Do not award if the response says the covalent bonds are weak or are broken during boiling."
      },
      {
        "text": "Strong electrostatic attractions act between oppositely charged ions; accept between magnesium ions, Mg²⁺, and oxide ions, O²⁻.",
        "reject": "Do not award if magnesium oxide is described as molecules or using intermolecular forces."
      },
      {
        "text": "Much more energy is needed to overcome the ionic attractions, so magnesium oxide has the higher boiling point."
      }
    ]
  },
  {
    "id": "hexane-methane-boiling",
    "focus": "melting-boiling",
    "left": {
      "name": "Hexane",
      "property": "higher boiling point"
    },
    "right": {
      "name": "Methane",
      "property": "lower boiling point"
    },
    "prompt": "Explain, in terms of their structure and bonding, why hexane has a higher boiling point than methane.",
    "points": [
      {
        "text": "Both substances have covalent bonding and simple molecular structures."
      },
      {
        "text": "Hexane molecules are larger than methane molecules, with a greater relative molecular mass or more electrons."
      },
      {
        "text": "The intermolecular forces between hexane molecules are stronger than those between methane molecules.",
        "reject": "Do not award if the response compares the strength of the covalent bonds."
      },
      {
        "text": "More energy is needed to overcome the intermolecular forces in hexane, giving it the higher boiling point.",
        "reject": "Do not award if the response says covalent bonds are broken during boiling."
      }
    ]
  },
  {
    "id": "diamond-sodium-chloride-melting",
    "focus": "melting-boiling",
    "left": {
      "name": "Diamond",
      "property": "high melting point"
    },
    "right": {
      "name": "Sodium chloride",
      "property": "high melting point"
    },
    "prompt": "Explain, in terms of their structure and bonding, why diamond and sodium chloride both have high melting points even though their bonding is different.",
    "points": [
      {
        "text": "Diamond has covalent bonding and a giant lattice structure."
      },
      {
        "text": "Many strong covalent bonds between carbon atoms must be broken to melt diamond.",
        "reject": "Do not award references to intermolecular forces or molecules in diamond."
      },
      {
        "text": "Sodium chloride has ionic bonding and a giant lattice structure."
      },
      {
        "text": "Strong electrostatic attractions act between oppositely charged ions; accept between sodium ions, Na⁺, and chloride ions, Cl⁻.",
        "reject": "Do not award references to covalent bonds, intermolecular forces or sodium chloride molecules."
      },
      {
        "text": "Large amounts of energy are required to overcome the strong bonding or attractions in both structures."
      }
    ]
  },
  {
    "id": "c60-diamond-melting",
    "focus": "melting-boiling",
    "left": {
      "name": "C₆₀ fullerene",
      "property": "lower melting point"
    },
    "right": {
      "name": "Diamond",
      "property": "much higher melting point"
    },
    "prompt": "Explain, in terms of their structure and bonding, why C₆₀ fullerene has a much lower melting point than diamond even though both are forms of carbon.",
    "points": [
      {
        "text": "C₆₀ has a simple molecular structure."
      },
      {
        "text": "There are weak intermolecular forces between C₆₀ molecules.",
        "reject": "Do not award if the covalent bonds within each C₆₀ molecule are described as weak."
      },
      {
        "text": "Diamond has covalent bonding and a giant lattice structure."
      },
      {
        "text": "Diamond contains many strong covalent bonds extending throughout the structure.",
        "reject": "Do not award references to diamond molecules or intermolecular forces in diamond."
      },
      {
        "text": "Less energy is needed to overcome the intermolecular forces in C₆₀ than to break the covalent bonds in diamond."
      }
    ]
  },
  {
    "id": "graphite-diamond-conductivity",
    "focus": "conductivity",
    "left": {
      "name": "Graphite",
      "property": "conducts electricity"
    },
    "right": {
      "name": "Diamond",
      "property": "does not conduct"
    },
    "prompt": "Explain, in terms of their structure and bonding, why graphite conducts electricity but diamond does not.",
    "points": [
      {
        "text": "Both graphite and diamond have covalent bonding and giant lattice structures made from carbon atoms."
      },
      {
        "text": "Each carbon atom in graphite forms three covalent bonds, leaving one electron per carbon atom delocalised."
      },
      {
        "text": "The delocalised electrons in graphite are free to move, so graphite conducts electricity.",
        "reject": "Do not award if graphite is said to conduct because its layers slide or because it contains ions."
      },
      {
        "text": "Each carbon atom in diamond forms four covalent bonds, so all four outer electrons are used in bonding."
      },
      {
        "text": "Diamond has no charged particles free to move, so diamond does not conduct electricity.",
        "reject": "Do not award the incorrect claim that diamond contains no electrons."
      }
    ]
  },
  {
    "id": "solid-molten-sodium-chloride-conductivity",
    "focus": "conductivity",
    "left": {
      "name": "Solid sodium chloride",
      "property": "does not conduct"
    },
    "right": {
      "name": "Molten sodium chloride",
      "property": "conducts"
    },
    "prompt": "Explain, in terms of their structure and bonding, why solid sodium chloride does not conduct electricity but molten sodium chloride does.",
    "points": [
      {
        "text": "Sodium chloride is ionic and contains charged ions."
      },
      {
        "text": "In solid sodium chloride, the ions are held in fixed positions in a giant lattice."
      },
      {
        "text": "The charged ions are fixed and cannot move, so solid sodium chloride does not conduct electricity.",
        "reject": "Do not award explanations based on electrons moving through sodium chloride."
      },
      {
        "text": "When sodium chloride melts, the ions become free to move."
      },
      {
        "text": "The charged ions are free to move, so molten sodium chloride conducts electricity.",
        "reject": "Do not award if molecules or delocalised electrons are identified as the moving charged particles."
      }
    ]
  },
  {
    "id": "copper-sodium-chloride-conductivity",
    "focus": "conductivity",
    "left": {
      "name": "Solid copper",
      "property": "conducts electricity"
    },
    "right": {
      "name": "Solid sodium chloride",
      "property": "does not conduct"
    },
    "prompt": "Explain, in terms of their structure and bonding, why solid copper conducts electricity but solid sodium chloride does not.",
    "points": [
      {
        "text": "Copper has metallic bonding in a giant lattice structure."
      },
      {
        "text": "Copper contains delocalised electrons that are free to move."
      },
      {
        "text": "Sodium chloride has ionic bonding in a giant lattice structure."
      },
      {
        "text": "The ions in solid sodium chloride are in fixed positions and cannot move, so solid sodium chloride does not conduct electricity.",
        "reject": "Do not award if electrons or molecules are described as the particles that move in sodium chloride."
      }
    ]
  },
  {
    "id": "graphite-diamond-hardness",
    "focus": "hardness",
    "left": {
      "name": "Graphite",
      "property": "soft"
    },
    "right": {
      "name": "Diamond",
      "property": "hard"
    },
    "prompt": "Explain, in terms of their structure and bonding, why graphite is soft but diamond is hard.",
    "points": [
      {
        "text": "Both graphite and diamond have covalent bonding and giant lattice structures made from carbon atoms."
      },
      {
        "text": "In graphite, each carbon atom forms three covalent bonds in layers."
      },
      {
        "text": "Only weak attractions act between the graphite layers.",
        "reject": "Do not award if the covalent bonds within a graphite layer are described as weak."
      },
      {
        "text": "The layers can slide over one another, making graphite soft."
      },
      {
        "text": "In diamond, each carbon atom forms four strong covalent bonds in a rigid three-dimensional lattice."
      },
      {
        "text": "The many strong covalent bonds make diamond hard."
      }
    ]
  }
];
export const identities:readonly Readonly<{sourceKey:string;questionId:string}>[]=[
  {
    "sourceKey": "water-sodium-chloride-melting:2",
    "questionId": "SBC-U5FSU0"
  },
  {
    "sourceKey": "water-sodium-chloride-melting:3",
    "questionId": "SBC-UFFEIZ"
  },
  {
    "sourceKey": "methane-magnesium-oxide-boiling:2",
    "questionId": "SBC-3M81WX"
  },
  {
    "sourceKey": "methane-magnesium-oxide-boiling:3",
    "questionId": "SBC-3C8G7Y"
  },
  {
    "sourceKey": "hexane-methane-boiling:2",
    "questionId": "SBC-E4WN2I"
  },
  {
    "sourceKey": "hexane-methane-boiling:3",
    "questionId": "SBC-EEW8RH"
  },
  {
    "sourceKey": "diamond-sodium-chloride-melting:2",
    "questionId": "SBC-4KKN3Z"
  },
  {
    "sourceKey": "diamond-sodium-chloride-melting:3",
    "questionId": "SBC-4AL1F0"
  },
  {
    "sourceKey": "c60-diamond-melting:2",
    "questionId": "SBC-8456XU"
  },
  {
    "sourceKey": "c60-diamond-melting:3",
    "questionId": "SBC-8E4SMT"
  },
  {
    "sourceKey": "graphite-diamond-conductivity:2",
    "questionId": "SBC-2C40VA"
  },
  {
    "sourceKey": "graphite-diamond-conductivity:3",
    "questionId": "SBC-2M3MK9"
  },
  {
    "sourceKey": "solid-molten-sodium-chloride-conductivity:2",
    "questionId": "SBC-F8MV0J"
  },
  {
    "sourceKey": "solid-molten-sodium-chloride-conductivity:3",
    "questionId": "SBC-EYN9BK"
  },
  {
    "sourceKey": "copper-sodium-chloride-conductivity:2",
    "questionId": "SBC-KIHCFZ"
  },
  {
    "sourceKey": "copper-sodium-chloride-conductivity:3",
    "questionId": "SBC-K8HQR0"
  },
  {
    "sourceKey": "graphite-diamond-hardness:2",
    "questionId": "SBC-8H8DTX"
  },
  {
    "sourceKey": "graphite-diamond-hardness:3",
    "questionId": "SBC-878S4Y"
  }
];
export const sources:readonly SourceReference[]=[
  {
    "path": "apps/Masters-of-IGCSE-Chemistry/src/activities/structure-and-bonding/data.js",
    "sha256": "6f43c088ee0e1c2fe20a580eff294a88b9db605c897212e2cc9a0f6d505a62cd",
    "symbolOrSection": "StructureBondingComparisonData.questions"
  },
  {
    "path": "apps/Masters-of-IGCSE-Chemistry/src/activities/structure-and-bonding/core.js",
    "sha256": "3d95f2cbf1f372f0c1d4c28ce7fa0ab7f1f15d63f8815b52d65fab50348c8c8c",
    "symbolOrSection": "levelTwoSections"
  },
  {
    "path": "apps/Masters-of-IGCSE-Chemistry/src/activities/structure-and-bonding/app.js",
    "sha256": "a3c004b779ca72ac262c7742edb45a4f91b6845307718434807b10c95978eb97",
    "symbolOrSection": "levelTwoHtml, levelThreeHtml, lockAnswer"
  }
];
