import {chromium} from '../../../../../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const here=import.meta.dirname,run=`a17-molecule-${Date.now()}`,report={status:'RUNNING',headless:true,playwright:'1.62.1',checks:[],errors:[]};
const context=await chromium.launchPersistentContext(path.join(here,run),{channel:'msedge',headless:true,viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
try{
 await page.goto(`http://127.0.0.1:5192/alevel.html?run=${run}&view=olympiad`);await page.waitForFunction(()=>window.__mastersOlympiad!==undefined);await page.getByRole('button',{name:'Start part (a)',exact:true}).click();
 await page.evaluate(async()=>{const module=await import('/src/activities/olympiad/c3l6/index.ts');for(const item of module.c3Challenge.classifications)await window.__mastersOlympiad.command({kind:'classify',id:item.id,value:item.answer});});await page.getByRole('button',{name:'Check part (a)',exact:true}).click();await page.getByRole('button',{name:'Continue to part (b)',exact:true}).click();await page.locator('.molecule-editor').waitFor();await page.getByRole('button',{name:'Add atom',exact:true}).click();await page.evaluate(()=>window.__mastersOlympiad.flush());const first=await page.evaluate(()=>window.__mastersOlympiad.snapshot());assert.equal(first.progress.drawingsB.A.graph.atoms.length,1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(here,'molecule-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(here,'molecule-desktop.png'),fullPage:true});await page.reload();await page.locator('.molecule-editor').waitFor();const restored=await page.evaluate(()=>window.__mastersOlympiad.snapshot());assert.deepEqual(restored.progress.drawingsB.A,first.progress.drawingsB.A);assert.equal(restored.progress.stage,'b');
 const evidence=await page.evaluate(async()=>{const {createChemistryRepository}=await import('/src/persistence/index.ts');return createChemistryRepository(window.__mastersOlympiad.snapshot().databaseName).curriculumHistory({course:'alevel',profileId:'local'});});assert(evidence.ok);assert.equal(evidence.value.length,0);assert.deepEqual(report.errors,[]);report.checks.push('Actual source Part(a) prerequisite/Check/continue, molecular non-drag Add atom, desktop/mobile no overflow and saved graph restore; zero curriculum evidence');report.snapshot={first,restored,evidence};report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;process.exitCode=1;await page.screenshot({path:path.join(here,'molecule-failure.png'),fullPage:true}).catch(()=>{});console.error(e);}
finally{fs.writeFileSync(path.join(here,'molecule-browser-results.json'),JSON.stringify(report,null,2));await context.close();console.log(JSON.stringify({status:report.status,errors:report.errors}));}
