import {useEffect,useMemo,useState,useRef} from 'react';
import type {ActivityId,ActivityRegistry,Course,QuestionRef,TeacherCatalogueEntry} from '../contracts/index.ts';
import {teacherCatalogue} from './teacher-catalogue.ts';

export function TeacherPicker({course,registry,activityId,onActivity,onQuestion,initialCode,initialRef}:{readonly course:Course;readonly registry:ActivityRegistry;readonly activityId:ActivityId;readonly onActivity:(id:ActivityId)=>void;readonly onQuestion:(ref:QuestionRef)=>void;readonly initialCode?:string;readonly initialRef?:QuestionRef}){
 const [rows,setRows]=useState<readonly TeacherCatalogueEntry[]>([]),[search,setSearch]=useState(''),[level,setLevel]=useState('all'),[key,setKey]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const registrations=registry.curriculumFor(course);
 const pendingRef=useRef<QuestionRef|null>(null),initialHandled=useRef(false);
 useEffect(()=>{let cancelled=false;setLoading(true);setRows([]);setSearch('');setKey('');setError('');void (async()=>{
  // The DEV proof registry can use the same chooser without changing the production catalogue.
  let result:readonly TeacherCatalogueEntry[];
  const registration=registry.get(activityId);if(!registration||registration.strand!=='curriculum')throw Error('Activity unavailable');
  const provider=await registration.provider();
  const sourceRows=await teacherCatalogue(activityId);
  const sourceApplicable=sourceRows.length>0&&provider.coverage.filter(c=>c.kind==='fixed').every(c=>c.questionIds.every(id=>sourceRows.some(row=>row.ref.questionId===id)))&&(()=>{try{provider.restore(sourceRows[0]!.ref);return true;}catch{return false;}})();
  if(sourceApplicable)result=sourceRows;
  else result=provider.coverage.flatMap(coverage=>coverage.kind==='fixed'?coverage.questionIds.map(id=>{const ref=provider.resolveLink(id);if(!ref)throw Error('Missing fixed question route');return {key:id,label:provider.restore(ref).title,ref};}):coverage.families.flatMap(family=>family.levels.map(level=>{const gem=registration.gems.find(g=>g.supportedLevels.includes(level));if(!gem)throw Error('Generated family has no registered level');const ref=provider.resolveLink(family.templateId)??provider.select({activityId,gemId:gem.id,level,seed:1,previousQuestionIds:[]});return {key:family.templateId+':'+level,label:`${family.templateId} / Level ${level}`,ref};})));
  if(!cancelled){setRows(result);setLoading(false);
   if(initialRef&&!initialHandled.current){initialHandled.current=true;if(initialRef.activityId!==activityId){pendingRef.current=initialRef;onActivity(initialRef.activityId);}setKey(result.find(row=>row.ref.questionId===initialRef.questionId&&row.ref.level===initialRef.level)?.key??'');onQuestion(initialRef);return;}
   if(initialCode&&!initialHandled.current){initialHandled.current=true;for(const item of registrations){const ref=(await item.provider()).resolveLink(initialCode);if(ref){if(item.id!==activityId){pendingRef.current=ref;onActivity(item.id);}onQuestion(ref);return;}}setError('Question code not recognised for this course.');}
   const requested=pendingRef.current?.activityId===activityId?pendingRef.current:null;pendingRef.current=null;
   const first=result[0];if(requested){setKey(result.find(row=>row.ref.questionId===requested.questionId&&row.ref.level===requested.level)?.key??'');onQuestion(requested);}else if(first){setKey(first.key);onQuestion(first.ref);}}

 })().catch(reason=>{if(!cancelled){setLoading(false);setError(String(reason));}});return()=>{cancelled=true;};},[activityId,registry]);
 const filtered=useMemo(()=>{const words=search.toLowerCase().trim().split(/\s+/);return rows.filter(row=>(level==='all'||String(row.ref.level)===level)&&words.every(word=>(row.label+' '+row.group+' '+row.ref.questionId).toLowerCase().includes(word)));},[rows,search,level]);
 const lookup=async()=>{setError('');for(const item of registrations){const ref=(await item.provider()).resolveLink(code);if(ref){if(item.id!==activityId){pendingRef.current=ref;onActivity(item.id);}onQuestion(ref);setKey(rows.find(row=>row.ref.questionId===ref.questionId&&row.ref.level===ref.level)?.key??'');return;}}setError('Question code not recognised. Enter a complete source ID or historical review code.');};
 return <section className="teacher-picker" aria-label="Teacher question catalogue"><h2>Teacher question catalogue</h2><p>Choose any source question or generator configuration. Search names, routes and original codes. Checked answers appear immediately.</p><div className="teacher-picker-controls"><label>Activity<select aria-label="Teacher activity" value={activityId} onChange={e=>onActivity(e.target.value as ActivityId)}>{registrations.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label>Level<select aria-label="Teacher level filter" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">All source levels</option>{[1,2,3].map(l=><option key={l} value={l}>Level {l}</option>)}</select></label><label>Search catalogue<input type="search" aria-label="Search teacher catalogue" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><p role="status" data-testid="teacher-catalogue-count">{loading?'Loading complete catalogue…':`${filtered.length} of ${rows.length} source questions or configurations`}</p><label>Question or configuration<select aria-label="Teacher question" value={filtered.some(r=>r.key===key)?key:''} disabled={loading||!filtered.length} onChange={e=>{const row=rows.find(r=>r.key===e.target.value);if(row){setKey(row.key);onQuestion(row.ref);}}}><option value="">Select a question</option>{filtered.map(row=><option key={row.key} value={row.key}>{row.label}</option>)}</select></label><form className="teacher-code" onSubmit={e=>{e.preventDefault();void lookup();}}><label>Open original question code<input aria-label="Question code" value={code} onChange={e=>setCode(e.target.value)} placeholder="Source ID or complete review code"/></label><button type="submit" disabled={!code.trim()}>Open question code</button></form>{error&&<p role="alert">{error}</p>}</section>;
}
