import {chromium} from '../../../../../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {bank,reviewCode} from '../../../src/activities/alevel/ph-titration-curves/provider.ts';
import {answer} from '../../../src/chemistry/titration-curve/core.js';
const here=import.meta.dirname,run=`a14-titration-${Date.now()}`,report={jobId:'S3-TITRATION',run,startedAt:new Date().toISOString(),checks:[],errors:[],status:'RUNNING'};
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100}});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const snap=()=>page.evaluate(()=>window.__mastersActivity.snapshot());const flush=()=>page.evaluate(()=>window.__mastersActivity.flush());
const check=s=>{report.checks.push(s);console.log(s);};
async function click(name){await page.getByRole('button',{name,exact:true}).click();await flush();}
async function start(level){await page.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-${level}`);await page.getByLabel('Target',{exact:true}).selectOption(`u6-t1-1-9:${level}`);await click('Start practice');await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);await page.locator('.tc-chart').waitFor();}
async function setAnswer(q,{wrong=false}={}){const a=answer(q);for(const [side,label] of [['before',a.before],['after',a.after]]){const name=label.replace(`${side}-`,'').split('-').map((w,i)=>i===0?w[0].toUpperCase()+w.slice(1):w).join(' ')+` · ${q.reverse?'falling':'rising'}`;await page.getByRole('button',{name,exact:true}).click();await flush();}
 for(const [label,v] of [['Initial pH',a.initialPH],['Equivalence volume / cm³',a.equivalenceVolume+(wrong?.5:0)],['Final pH',a.finalPH]]){await page.getByLabel(label,{exact:true}).fill(v.toFixed(1));await flush();}
 await page.getByRole('button',{name:new RegExp(a.indicator==='phenolphthalein'?'^Phenolphthalein':a.indicator==='methyl-orange'?'^Methyl orange':'^Methyl red')}).click();await flush();}
try{
 await start(2);let s=await snap();assert.equal(s.question.ref.questionId,'TC01');assert.equal(s.attempt.timing.idleLimitMs,600000);const id=s.attempt.attemptId;
 await click('Check answer');assert.equal((await snap()).attempt.phase,'answering');assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,0);check('incomplete curve blocks assessment and creates no evidence');
 await setAnswer(bank[0],{wrong:true});const anchor=page.getByRole('slider',{name:'Initial pH anchor',exact:true});await anchor.focus();await page.keyboard.press('ArrowUp');await flush();assert(Math.abs((await snap()).attempt.currentResponses.curve.initialPH-answer(bank[0]).initialPH-.1)<1e-5);await page.keyboard.press('ArrowDown');await flush();check('keyboard anchor steps and real numeric/piece/indicator controls construct source curve');
 await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);await page.locator('.tc-chart').waitFor();s=await snap();assert.equal(s.attempt.attemptId,id);assert.equal(s.attempt.currentResponses.curve.equivalenceVolume,23);check('reload restores same question seed/attempt and full curve response');
 // Actual SVG pointer movement then Undo returns the saved response.
 const handle=page.getByRole('slider',{name:'Equivalence volume anchor',exact:true});await handle.scrollIntoViewIfNeeded();const box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+30,box.y+box.height/2,{steps:5});await page.mouse.up();await flush();assert.notEqual((await snap()).attempt.currentResponses.curve.equivalenceVolume,23);await click('Undo curve edit');assert.equal((await snap()).attempt.currentResponses.curve.equivalenceVolume,23);check('pointer drag updates meaningful volume and Undo restores prior chemical state');
 await click('Check answer');s=await snap();assert.equal(s.attempt.phase,'assessed');assert.equal(s.attempt.firstAssessment.marks.earned,5);const firstResponse=structuredClone(s.attempt.firstResponse),firstAssessment=structuredClone(s.attempt.firstAssessment);assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,1);
 await page.getByLabel('Equivalence volume / cm³',{exact:true}).fill('22.5');await flush();await click('Check correction');s=await snap();assert.equal(s.correctionFeedback.status,'correct');assert.deepEqual(s.attempt.firstResponse,firstResponse);assert.deepEqual(s.attempt.firstAssessment,firstAssessment);assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,1);check('wrong first5/6 fixed; corrected6/6 learning feedback cannot mutate first/time/evidence');
 await click('Show worked answer');await page.screenshot({path:path.join(here,'practice-correction-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(here,'practice-correction-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1100});
 await page.reload();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt?.phase==='assessed');assert.deepEqual((await snap()).attempt.firstAssessment,firstAssessment);await click('Next question');await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.attemptId!==id,id);s=await snap();assert.equal(s.question.ref.questionId,'TC02');assert.equal(s.attempt.phase,'answering');assert.equal(s.attempt.timing.idleLimitMs,600000);check('assessed reload/Next preserves old timing and advances genuine sequential18-question pool');
 await click('Pause');const paused=await snap();await page.reload();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await flush();assert.equal((await snap()).attempt.attemptId,paused.attempt.attemptId);check('practice pause/reload/resume');
 await start(3);s=await snap();assert.equal(s.question.ref.questionId,'TC19');await setAnswer(bank[18]);await click('Check answer');assert.equal((await snap()).attempt.firstAssessment.marks.earned,6);await page.screenshot({path:path.join(here,'diprotic-level3-desktop.png'),fullPage:true});check('level3 genuine complete-dissociation diprotic factors, full correct calculation/indicator');
 // Full teacher bank renders every model against exact supported historical code.
 for(const q of bank){const teacher=await context.newPage();await teacher.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-teacher-${q.id}&mode=teacher&review=${reviewCode(q.id)}`);await teacher.getByRole('heading',{name:'Worked answer',exact:true}).waitFor();await teacher.locator('.worked-answer img').evaluate(img=>img.decode());await teacher.locator('.tc-chart').waitFor();assert.equal(await teacher.locator('.titration-workspace button:not(:disabled)').count(),0);assert.equal(await teacher.evaluate(()=>window.__mastersActivity.history().then(h=>h.length)),0);await teacher.locator('.worked-answer').screenshot({path:path.join(here,`model-${q.id}.png`)});if(['TC01','TC09','TC13','TC16','TC19','TC22'].includes(q.id)){await teacher.setViewportSize({width:390,height:844});assert(await teacher.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await teacher.screenshot({path:path.join(here,`teacher-${q.id}-mobile.png`),fullPage:true});}await teacher.close();}check('all36 historical teacher models decode/render without evidence; six chemistry-family mobile screens fit');
 const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const touch=await touchContext.newPage();await touch.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-touch`);await touch.getByLabel('Target',{exact:true}).selectOption('u6-t1-1-9:2');await touch.getByRole('button',{name:'Start practice',exact:true}).tap();await touch.locator('.tc-chart').waitFor();await touch.getByRole('button',{name:'Weak acid · rising',exact:true}).tap();await touch.evaluate(()=>window.__mastersActivity.flush());assert.equal(await touch.evaluate(()=>window.__mastersActivity.snapshot().attempt.currentResponses.curve.before),'before-weak-acid');await touch.screenshot({path:path.join(here,'mobile-touch.png'),fullPage:true});await touchContext.close();check('actual mobile touchscreen selection plus numeric controls available');
 await page.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-revision&session=revision`);await page.getByRole('button',{name:'ADD ALL u6-t1-1',exact:true}).click();assert.equal((await snap()).selectedCount,17);check('U6 revision ADD ALL selects fifteen acid routes plus exactly two true titration levels');
 // Genuine U6 topic round: five acid gems then titration, using assisted skip without false evidence.
 await page.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-revision-titration&session=revision`);await page.getByRole('button',{name:'ADD ALL u6-t1-1',exact:true}).click();await click('Start practice');await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);for(let i=0;i<5;i++){const prior=await snap();assert.equal(prior.question.ref.activityId,'alevel/acid-base-calculations');await click('Reveal answer (assisted)');await click('Next question');await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.attemptId!==id,prior.attempt.attemptId);}await page.locator('.tc-chart').waitFor();s=await snap();assert.equal(s.session.kind,'revision');assert.equal(s.question.ref.activityId,'alevel/ph-titration-curves');await setAnswer(bank[0]);await click('Pause');const revisionId=(await snap()).attempt.attemptId;await page.reload();await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await flush();assert.equal((await snap()).attempt.attemptId,revisionId);assert.equal((await snap()).attempt.currentResponses.curve.before,'before-weak-acid');await click('Check answer');assert.equal((await snap()).attempt.firstAssessment.marks.earned,6);await click('Next question');await page.waitForFunction(id=>window.__mastersActivity?.snapshot().attempt?.attemptId!==id,revisionId);assert.equal((await snap()).session.kind,'revision');await page.screenshot({path:path.join(here,'revision-next.png'),fullPage:true});check('same real revision host launch/respond/pause/reload/resume/check/scheduler Next');
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);await page.screenshot({path:path.join(here,'browser-failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));await browser.close();}



