import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
const original='../Masters-of-A-Level-Chemistry/src/activities/ph-titration-curves/';
const context=vm.createContext({});vm.runInContext(fs.readFileSync(original+'data.js','utf8'),context);
fs.writeFileSync('src/activities/alevel/ph-titration-curves/bank.json',JSON.stringify(context.TitrationData,null,2)+'\n');
let core=fs.readFileSync(original+'core.js','utf8');
core=core.replace("(function(root){\n  'use strict';",'// Pure numerical and chemical engine extracted verbatim from the checked source.');
core=core.slice(0,core.indexOf('  root.TitrationCore='));
core+='\nexport {KW,snap,clamp,quantities,equivalenceVolume,chargeResidual,equilibriumPH,answer,initial,pieces,indicators,suitableIndicators,curve,grade};\n';
fs.writeFileSync('src/chemistry/titration-curve/core.js',core);
const files=[original+'data.js',original+'core.js',original+'app.js',original+'session.js','../../development/alevel/data/ph-titration-curves.json','../../development/alevel/validation/ph-titration-curves/answer-key.json','../../resources/curriculum/ocr-a-level/a-level-specification-map.md'];
fs.writeFileSync('validation/s3/titration/source-fingerprints.json',JSON.stringify(files.map(path=>({path,sha256:crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex')})),null,2));
