import {chromium} from '../../../../../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const here=import.meta.dirname,run=`a14-final-${Date.now()}`,report={startedAt:new Date().toISOString(),status:'RUNNING',checks:[],errors:[]};
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
try{
 await page.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-mobile&mode=teacher&review=TC01`);await page.locator('.worked-answer img').evaluate(img=>img.decode());await page.locator('.tc-chart').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('.worked-answer .content-image-scroll').evaluate(el=>el.scrollWidth>el.clientWidth));await page.screenshot({path:path.join(here,'final-mobile-legible-model.png'),fullPage:true});const textBefore=await page.locator('.worked-answer .content>p').last().boundingBox();await page.locator('.worked-answer .content-image-scroll').evaluate(el=>{el.scrollLeft=el.scrollWidth;});const textAfter=await page.locator('.worked-answer .content>p').last().boundingBox();assert.equal(textAfter.x,textBefore.x);await page.screenshot({path:path.join(here,'final-mobile-model-final-anchor.png'),fullPage:true});report.checks.push('final model preserves550px labels and scrolls inside mobile without document overflow');
 await page.setViewportSize({width:1440,height:1000});await page.clock.install();await page.goto(`http://127.0.0.1:5181/alevel.html?run=${run}-clock`);await page.getByLabel('Target',{exact:true}).selectOption('u6-t1-1-9:2');await page.getByRole('button',{name:'Start practice',exact:true}).click();await page.waitForFunction(()=>window.__mastersActivity?.snapshot().attempt!==null);await page.locator('.tc-chart').waitFor();await page.clock.runFor(605000);await page.evaluate(()=>window.__mastersActivity.flush());let s=await page.evaluate(()=>window.__mastersActivity.snapshot());assert(s.attempt.timing.activeMs>=599000&&s.attempt.timing.activeMs<=600000,JSON.stringify(s.attempt.timing));const idle=s.attempt.timing.activeMs;await page.clock.runFor(5000);await page.evaluate(()=>window.__mastersActivity.flush());assert.equal((await page.evaluate(()=>window.__mastersActivity.snapshot())).attempt.timing.activeMs,idle);report.checks.push('real browser production binding under accelerated clock clips idle at source600000ms and stops until trusted interaction');
 await page.getByRole('button',{name:'Weak acid · rising',exact:true}).click();await page.clock.runFor(2000);await page.evaluate(()=>window.__mastersActivity.flush());await page.evaluate(()=>window.__mastersActivity.checkpoint());s=await page.evaluate(()=>window.__mastersActivity.snapshot());assert(s.attempt.timing.activeMs>idle);report.checks.push('trusted curve click resumes active time after idle');
 const before=s.attempt.timing.activeMs;await page.clock.fastForward(15000);await page.evaluate(()=>window.__mastersActivity.checkpoint());s=await page.evaluate(()=>window.__mastersActivity.snapshot());assert.equal(s.attempt.timing.activeMs,before);report.checks.push('browser suspension gap is excluded rather than credited as active chemistry work');
 await page.getByRole('button',{name:'Strong base · rising',exact:true}).click();for(const [label,value] of [['Initial pH','2.8'],['Equivalence volume / cm³','22.5'],['Final pH','12.9']]){await page.getByLabel(label,{exact:true}).fill(value);await page.evaluate(()=>window.__mastersActivity.flush());}await page.getByRole('button',{name:/^Phenolphthalein/}).click();await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.evaluate(()=>window.__mastersActivity.flush());s=await page.evaluate(()=>window.__mastersActivity.snapshot());const records=await page.evaluate(()=>window.__mastersActivity.history());assert.equal(records.length,1);assert.deepEqual(records[0].timing,s.attempt.firstResponse.timing);const fixed=structuredClone(records[0]);await page.clock.runFor(5000);await page.getByRole('button',{name:'Check correction',exact:true}).click();await page.evaluate(()=>window.__mastersActivity.flush());assert.deepEqual((await page.evaluate(()=>window.__mastersActivity.history()))[0],fixed);report.checks.push('first600000ms source-clock timing transfers exactly into persisted curriculum evidence and stays fixed after correction/time');assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);process.exitCode=1;await page.screenshot({path:path.join(here,'final-review-failure.png'),fullPage:true}).catch(()=>{});}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'final-browser-results.json'),JSON.stringify(report,null,2));await browser.close();}



