'use strict';
const fs=require('node:fs'),crypto=require('node:crypto');
const out='apps/Masters-of-Chemistry/validation/s0/inventory',docs='apps/Masters-of-Chemistry/docs/inventory';
const m=JSON.parse(fs.readFileSync(out+'/coverage-manifest.json','utf8'));
const checks=JSON.parse(fs.readFileSync(out+'/reference-check-results.json','utf8'));
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const coverage=a=>a.source==='acid-base-calculations'?'38 active V2 templates; 63 supported template-level routes; 33 legacy templates':a.source==='electron-configurations'?'71 species; 36 atom entries; 4 representations; both directions + seeded matching':a.source==='c3l6-organic-reactions'?'10 classifications; 12 B targets / 7 units; 9 C targets; 23 structure alternatives':a.bankArrays.find(b=>b.path===a.activeBank)?.count+' '+(a.source==='calorimetry'?'examples / 4 mastery families / '+a.finiteGeneratorConfigurations.count+' teacher configurations':a.source==='bond-enthalpy'?'reactions / 2 mastery families':'fixed questions');
let doc='# Migration coverage inventory\n\nRun `'+m.runId+'`; stable worker A02 / S0-INVENTORY. This inventory is a source preservation baseline, not a new chemistry audit, a migrated activity or publication approval. Both source apps were read-only. No browser storage was accessed and no original build or content generator ran.\n\n';
doc+='## Reproduce and verify\n\nFrom the workspace root:\n\n```powershell\nnode apps/Masters-of-Chemistry/validation/s0/inventory/collect.cjs\nnode apps/Masters-of-Chemistry/validation/s0/inventory/collect.cjs check\nnode apps/Masters-of-Chemistry/validation/s0/inventory/run-reference-checks.cjs\nnode apps/Masters-of-Chemistry/validation/s0/inventory/test-acid-levels-ported.cjs\nnode apps/Masters-of-Chemistry/validation/s0/inventory/validate-source-models.cjs\nnode apps/Masters-of-Chemistry/validation/s0/inventory/build-docs.cjs\n```\n\n';
doc+='The original reference suite intentionally retains one failure: `test_acid_levels.js` assumes every U6 registration is acid and rejects the subsequently valid titration registration. The owned port checks the exact five acid leaves plus the separately registered titration leaf/levels, then runs the unchanged 15 mastery routes and 33 historical question fixtures. Its changes are only root resolution and that outdated assertion. No original test is edited.\n\n';
doc+='The [machine manifest](../../validation/s0/inventory/coverage-manifest.json) contains one record per exact contract ID, supported level-to-source-ID lists, every bank array and family/template count, teacher/runtime entrypoint scripts, release inclusion, dependencies and source SHA-256/bytes. Per-activity `*-evidence.json` files retain source path/line/text for IDs, random seeds, marking, scaffolds, timing and storage. `identity-index.json` maps existing source keys to supported historical review IDs without using display order. No full generated-question snapshots are introduced.\n\n';
doc+='## Exact scope\n\n| Activity | Supported levels | Coverage |\n|---|---|---|\n';for(const a of m.activities)doc+='| `'+a.id+'` | '+(a.supportedLevels.join(', ')||'Olympiad stages only')+' | '+coverage(a)+' |\n';
doc+='\n**Exclusions:** Rocket Recall contributes no runtime, navigation, dependencies, release assets or imported progress. Original Rocket files are untouched. Dormant molecule-builder index/app, mechanism prototype, old acid portable/mastery pages and electron legacy pages are not activated. The shared checked molecule core/layout/editor/styles required by C3L6 are dependencies, not an additional activity. C3L6 has no gem, curriculum revision, mastery score or curriculum timing/statistics evidence.\n\n';
doc+='## Source and level decisions\n\n';
for(const a of m.activities){doc+='### '+a.id+'\n\n';doc+='- Entry: `'+a.entrypoint+'`. Active scripts: '+a.activeScriptRefs.map(s=>'`'+s+'`').join(', ')+'.\n';doc+='- Leaf IDs: '+(a.leafIds.map(x=>'`'+x+'`').join(', ')||'none')+'. Levels: '+(a.supportedLevels.join(', ')||'none; separate challenge progression')+'.\n';doc+='- Source ownership: '+a.sourceOwner+'\n';doc+='- Identity and seed: '+a.identity+'\n';doc+='- Editor/response: '+a.editor+'.\n';doc+='- Marking: '+a.marking+'\n';doc+='- Pedagogical differences: '+a.scaffolding+'\n';doc+='- Curriculum/reference boundary: '+a.curriculum+'\n';doc+='- Timing: '+a.timing+'\n';for(const [level,row] of Object.entries(a.levelMapping)){doc+='- Level '+level+': '+row.count+' source identities';if(row.categories)doc+='; pupil pools '+Object.entries(row.categories).map(([k,v])=>k+' '+v.count).join(', ');if(row.matchingEnabled)doc+=' plus seeded matching';doc+=' (exact lists in manifest).\n';}doc+='\n';}
doc+='## Persistence and migration constraints\n\nSource activity evidence retains exact key strings and saved fields. Import reads must preserve question IDs/seed, response/diagram state, attempt ID, immutable first evidence, hint/reveal state and validated timing where present. Existing absent timing stays absent. Never write old keys. Replace source page controllers/iframe bridges and DOM/title-derived registrations with the shared attempt/session/repository boundary; retain checked marking/editor engines.\n\nA-level mastery retains threshold 0.8; electron/bonding/dot half-lives are 3, acid half-lives 2 with progressionVersion 2, titration half-lives 2 at levels 2/3. Former covalent `l6-t2-1-4` maps to diagram `l6-t2-1-3` while retaining historical source IDs; hidden Ka/pKa `u6-t1-1-4` routes to weak acid `u6-t1-1-5`. Historical stores and progression versions remain explicit. IGCSE keeps threshold 0.8 and each activity/grade half-life in `masteryRegistrations`; Grade 9 energy tuning is reserved and does not authorise a Grade 9 activity. C3L6 stores challenge completion/graphs separately with source answer-version/signature checks.\n\nExtra hint/reveal assistance is distinct from built-in level scaffolding. Stop time on first assessment, including written-answer lock before rubric review; retries/corrections/reloads cannot produce independent evidence. Teacher/review views are evidence-free. Rebuild behaviour and actual browser/rendered checks are later-stage gates; the static inventory does not claim those have passed.\n\n';
doc+='## Checked chemistry/reference map and limitations\n\nFifteen original read-only model/regression scripts pass. Among their retained output are independent acid reconstruction of 38 templates / 228 questions / 2,936 checks, 1,242 calorimetry outputs, 123 exact bond reaction/level/seed outputs and the full 91-entry A-level diagram reference bank. The separate source-model check passes 63 acid identity routes, 33 historical fixtures, all 23 C3L6 graph/formula alternatives and all 14 practical model responses/empty-response/correction gates. These are regression/invariant checks; they do not establish a fresh expert audit.\n\n`reference-validation-map.json` maps each activity to checks, retained source provenance and status. IGCSE `test_dot_cross_bank.js` still names absent `resources/past-paper-atlas/data/atlas.json`; do not run it as-is or remove the provenance check to claim PASS. Port its independent electron-count fixture and resolve the historical atlas mapping during migration. Other diagram checks do pass.\n\nHistorical C3L6 draft chemistry reports were identified by path and metadata but are offline cloud placeholders; none was hydrated. Live promoted content/answer graphs were inspected instead and validated against the readable source editor model. The historical reports remain provenance to recover only with separately authorised access if needed. All original `src` content is readable, so this limitation does not prevent exact bank preservation.\n\nThe repository OCR gem map was consulted: it records OCR H432 Version 3.1 (May 2026), reviewed 10 September 2026. Acid source metadata retains its older Version 3.0 (2025) / access 4 September 2026 provenance; do not silently rewrite historical metadata or treat its version as the current specification. This is a migration inventory, not a formal new curriculum coverage audit. IGCSE uses its Pearson specification evidence; Olympiad extension is labelled separately.\n\nNo source equations, constants, names, charges or diagrams were changed. Embedded reaction SVGs and C3L6 assets must retain original checked fingerprints; any future changed chemistry/depictions needs fresh substantive and rendered review. Teacher-edited bank exports must never be overwritten by generators.\n';
fs.mkdirSync(docs,{recursive:true});fs.writeFileSync(docs+'/migration-inventory.md',doc);
const hashReview=(prefix,key)=>{let h=2166136261;for(const c of key)h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;return prefix+'-'+(h%(36**6)).toString(36).toUpperCase().padStart(6,'0');};
const index={schemaVersion:1,identitySource:'Existing permanent source IDs and original QuestionReview.bank FNV-1a hash; never display order',activities:m.activities.map(a=>{const bank=a.bankArrays.find(b=>b.path===a.activeBank);let ids=bank?.ids||[];let entries=[];if(a.source==='electron-configurations')ids=[...new Set(Object.values(a.levelMapping).flatMap(l=>l.sourceIds))];if(a.source==='structure-and-bonding')ids=ids.flatMap(id=>a.supportedLevels.map(level=>id+':'+level));const prefix=({'electron-configurations':'EC','dot-and-cross':'DAC','structure-and-bonding':'SBC','energy-enthalpy':'EE','ph-titration-curves':'TC'})[a.source];if(prefix)entries=ids.map(sourceKey=>({sourceKey,questionId:hashReview(prefix,sourceKey)}));else if(['electrons-bonding','energetics-practical'].includes(a.source))entries=ids.map(id=>({sourceKey:id,questionId:id}));else if(a.source==='c3l6-organic-reactions')entries=a.bankArrays.filter(b=>b.path.endsWith('.answers')).flatMap(b=>b.ids.map(sourceTarget=>({sourceStage:b.path.split('.')[2],sourceTarget})));return {id:a.id,convention:a.identity,entries,count:entries.length};})};
for(const a of index.activities){const ids=a.entries.filter(e=>e.questionId).map(e=>e.questionId);if(new Set(ids).size!==ids.length)throw Error(a.id+' duplicate historical review IDs');}
fs.writeFileSync(out+'/identity-index.json',JSON.stringify(index,null,2)+'\n');
const refMap={schemaVersion:1,scope:'Existing checks and historical provenance; mapped-only does not mean executed/passed',activities:m.activities.map(a=>({id:a.id,checks:a.references.map(file=>{const result=checks.results.find(r=>r.file===file);return {file,exists:fs.existsSync(file),status:result?.status||'MAPPED_ONLY',evidence:result?.log||null,...(file.startsWith('scripts/')&&fs.existsSync(file)?{sha256:hash(fs.readFileSync(file)),bytes:fs.statSync(file).size}:{})};}),supplemental:a.source==='acid-base-calculations'?['source-model-validation.json','ported-acid-levels.log']:['c3l6-organic-reactions','energetics-practical'].includes(a.source)?['source-model-validation.json']:[],historicalCloudProvenance:a.source==='c3l6-organic-reactions'?{status:'OFFLINE_METADATA_ONLY_NOT_HYDRATED',paths:a.references}:null})),knownReferenceLimitations:[{file:'scripts/test_acid_levels.js',status:'STALE_ASSERTION_RETAINED',replacement:'test-acid-levels-ported.cjs',difference:'all U6 exact registrations include valid titration leaf'},{file:'scripts/test_dot_cross_bank.js',status:'NOT_RUN_STALE_DEPENDENCY',missing:'resources/past-paper-atlas/data/atlas.json'}]};
fs.writeFileSync(out+'/reference-validation-map.json',JSON.stringify(refMap,null,2)+'\n');
console.log(JSON.stringify({status:'PASS',documents:1,activityReferenceEntries:refMap.activities.length,identityEntries:index.activities.reduce((n,a)=>n+a.count,0)}));
