'use strict';
// Read-only source inventory; all generated evidence is confined to this directory.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=process.cwd(), project='apps/Masters-of-Chemistry', out=project+'/validation/s0/inventory';
const contract=JSON.parse(fs.readFileSync(project+'/project-contract.json','utf8'));
const annotations=require('./annotations.cjs');
const mode=process.argv[2]||'generate';
const preflight=require('node:child_process').spawnSync('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',out+'/preflight-local-inputs.ps1'],{encoding:'utf8'});
assert.equal(preflight.status,0,'Non-src input locality gate failed; do not hydrate offline files: '+preflight.stderr);
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const plainData=v=>JSON.parse(JSON.stringify(v));
const read=p=>fs.readFileSync(p,'utf8');
const norm=p=>p.replaceAll('\\','/');
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(dir+'/'+e.name):[dir+'/'+e.name]).sort();}
function fingerprint(p){const b=fs.readFileSync(p);return {path:p,bytes:b.length,sha256:sha(b)};}
function load(c,p){vm.runInContext(read(p),c,{filename:p,timeout:5000});}
function context(){return vm.createContext({console:{log(){},warn(){},error(){}},localStorage:{getItem(){return null;}},addEventListener(){}});}
function summary(v){if(!v||typeof v!=='object')return v;const r={};for(const k of ['id','key','name','label','title','level','grade','band','type','pattern','grades','levels','allowedLevels','family','group','strand','focus','category','practiceCategory','namedSpecies','totalCharge','formula','setup','target','massRoutes','amountRoutes','temperatureRoutes','representations','groups','matching','marking','curriculum','metadata','source','version','prerequisiteOrder'])if(v[k]!==undefined)r[k]=v[k];for(const k of ['fields','points','parts','alternatives','species','items','products','reactions'])if(Array.isArray(v[k]))r[k+'Count']=v[k].length;return r;}
function arrays(value,prefix='',seen=new Set()) {if(!value||typeof value!=='object'||seen.has(value))return [];seen.add(value);const rows=[];for(const [key,v] of Object.entries(value)){if(typeof v==='function')continue;let p=prefix?prefix+'.'+key:key;if(Array.isArray(v)){rows.push({path:p,count:v.length,ids:v.filter(x=>x&&typeof x==='object'&&x.id!==undefined).map(x=>x.id),entries:v.map(summary)});}else if(v&&typeof v==='object')rows.push(...arrays(v,p,seen));}return rows;}
function evidenceLines(files,regex){return files.filter(f=>/\.(js|html|css|md)$/.test(f)).flatMap(file=>read(file).split(/\r?\n/).flatMap((text,i)=>regex.test(text)?[{file,line:i+1,text}]:[]));}
function dependencies(html){let result=[],external=[];let queue=[html],seen=new Set();while(queue.length){const file=queue.shift();if(seen.has(file))continue;seen.add(file);if(!fs.existsSync(file)){result.push({from:html,path:file,exists:false});continue;}if(!/\.(html|css)$/.test(file))continue;const text=read(file);const refs=[...text.matchAll(/(?:src|href)\s*=\s*["']([^"']+)["']|url\(\s*["']?([^\s)'";]+)["']?\s*\)/gi)].map(m=>m[1]||m[2]);for(const ref of refs){if(/^(?:https?:|data:|#|mailto:|javascript:)/.test(ref)){if(/^https?:/.test(ref))external.push(ref);continue;}const clean=ref.split(/[?#]/)[0];if(!clean)continue;const target=norm(path.normalize(path.join(path.dirname(file),clean)));result.push({from:file,reference:ref,path:target,exists:fs.existsSync(target)});if(fs.existsSync(target)&&/\.(html|css)$/.test(target))queue.push(target);}}return {references:result,external:[...new Set(external)].sort()};}
const manifest={schemaVersion:1,runId:contract.runId,jobId:'S0-INVENTORY',generatedAt:new Date().toISOString(),scope:'source migration coverage; no new chemistry audit or browser behaviour certification',reproduction:{fields:['questionId','seed'],fullQuestionSnapshots:false,displayOrderDefinesIds:false},excluded:contract.excluded,activities:[],sources:[]};
const sourcePaths=new Set([project+'/project-contract.json']);
// These non-src source inputs were explicitly checked as local/readable in source-provenance-availability.json.
for(const file of ['resources/curriculum/ocr-a-level/a-level-specification-map.md','development/tests/fixtures/acid-legacy-reviews.json','development/alevel/data/ph-titration-curves.json','development/alevel/validation/ph-titration-curves/answer-key.json','development/igcse/plans/igcse-energy-enthalpy-automarked-question-bank.md','development/alevel/data/flashcards/l6-electrons-bonding-key-learning.csv','scripts/generate_ph_titration_curves.js','scripts/build_energy_enthalpy.js','scripts/energy_enthalpy_reactions.js','scripts/build_bond_enthalpy_generator.py','scripts/build_acid_base_mastery.js','scripts/build_electron_configurations.js'])sourcePaths.add(file);
for(const a of contract.activities){const app=`apps/Masters-of-${a.course==='alevel'?'A-Level':'IGCSE'}-Chemistry`,src=app+'/src',dir=src+'/activities/'+a.source;const files=walk(dir);const release=JSON.parse(read(app+'/release.json'));const c=context();const catalog=context();load(catalog,src+'/landing/catalog.js');const registry=Object.entries(catalog).filter(([k])=>k!=='console'&&k!=='localStorage'&&k!=='addEventListener').map(([key,value])=>({key,value}));if(a.course==='igcse')load(c,src+'/assets/numeric-mastery.js');for(const name of ['data.js','core.js','session.js','levels.js','mastery-core.js','content.js','assessment.js']){const file=dir+'/'+name;if(!fs.existsSync(file)||name==='session.js')continue;load(c,file);}
 const modules=Object.entries(c).filter(([k])=>!['console','localStorage','addEventListener','NumericMastery'].includes(k));const bankArrays=modules.filter(([k])=>!/Core|Assessment|Session|Mastery|Levels/.test(k)).flatMap(([key,v])=>arrays(v,key));const coverage=modules.filter(([k])=>/Levels|Session|Mastery/.test(k)).flatMap(([key,v])=>arrays(v,key));
 const html=dir+'/index.html';const deps=dependencies(html);const activeScriptRefs=[...read(html).matchAll(/<script[^>]+src=["']([^"']+)/gi)].map(m=>m[1]);
 const released=files.filter(f=>release.files.includes(f.slice(src.length+1)));const supporting=files.filter(f=>!released.includes(f));
 const relevantRegistry=registry.map(r=>({key:r.key,entries:Object.fromEntries(Object.entries(r.value||{}).filter(([k,v])=>typeof v==='object'&&v&&String(v.href||'').includes('/'+a.source+'/')))})).filter(r=>Object.keys(r.entries).length);
 const coreApis=modules.map(([name,api])=>({name,exports:Object.keys(api),functions:Object.entries(api).filter(([,v])=>typeof v==='function').map(([k])=>k)}));
 const shared=[src+'/landing/catalog.js',src+'/assets/test-mode-core.js',src+'/assets/test-mode-bridge.js',src+'/assets/active-question-time.js',src+'/assets/question-review.js',src+'/assets/test-mode.js',a.course==='alevel'?src+'/assets/alevel-mastery.js':src+'/assets/igcse-mastery-config.js',app+'/release.json'];
 const runtimeFiles=[...new Set([...released,...deps.references.filter(r=>r.exists).map(r=>r.path),...shared])].sort();
 const lines=evidenceLines([...new Set([...files,...runtimeFiles])], /questionId|reviewId|QuestionReview|encodeQuestion|decodeQuestion|seed|mulberry|xorshift|idleLimit|allowance\(|localStorage|sessionStorage|storageKey|const\s+(?:key|acidKey|KEY|STORE)\s*=|scaffold|selfCheck|overrides|progressionVersion|halfLives|threshold|hiddenGems|redirects|leafId|config\s*=|catalog\s*=/);
 const notes=annotations[a.id];assert(notes,a.id);const fixed=bankArrays.find(b=>b.path===notes.activeBank);const levelMapping={};const finiteVariants=[];
 for(const ref of notes.references)if(ref.startsWith('scripts/')&&fs.existsSync(ref))sourcePaths.add(ref);
 for(const level of notes.supportedLevels){let ids=[];
  if(a.source==='acid-base-calculations')ids=[...new Set(c.AcidBaseLevels.scopes.flatMap(s=>s.levels[level]))];
  else if(a.source==='electron-configurations'){const conf=c.ElectronLevelSession.LEVELS[level];for(const item of c.ElectronData.species.filter(s=>conf.groups.includes(s.group)))for(const repr of conf.representations.filter(r=>r!=='short'||c.ElectronCore.coreOptions(item).length))for(const direction of ['build','identify'])ids.push(item.id+':'+direction+':'+repr);}
  else if(a.source==='dot-and-cross')ids=c.DotCrossData.questions.filter(q=>q.grades.includes(level)).map(q=>q.id);
  else if(a.source==='bond-enthalpy')ids=c.BondEnthalpyData.reactions.filter(q=>q.allowedLevels.includes(level)).map(q=>q.id);
  else if(a.source==='calorimetry')ids=c.CalorimetryReviewData.examples.map(q=>q.id);
  else if(a.source==='energetics-practical')ids=c.PRACTICAL_BANK.questions.filter(q=>q.band===(level===2?'7-8':'9')).map(q=>q.id);
  else ids=(fixed?.entries||[]).filter(q=>!q.level&&!q.grade||Number(q.level||q.grade)===level).map(q=>q.id);
  const row={sourceIds:ids,count:ids.length};
  if(a.source==='dot-and-cross'){row.categories=Object.fromEntries(['ionic','covalent'].map(category=>{const seen=new Set();const qs=c.DotCrossData.questions.filter(q=>{const cat=q.practiceCategory||q.category,key=cat==='covalent'&&!q.namedSpecies?'covalent:'+q.formula:q.id;if(cat!==category||!q.grades.includes(level)||seen.has(key))return false;seen.add(key);return true;});return [category,{pupilPoolIds:qs.map(q=>q.id),count:qs.length}];}));}
  if(a.source==='acid-base-calculations')row.leaves=Object.fromEntries(c.AcidBaseLevels.scopes.map(s=>[s.id,{templateIds:s.levels[level],count:s.levels[level].length}]));
  if(a.source==='electron-configurations')row.matchingEnabled=c.ElectronLevelSession.LEVELS[level].matching;
  if(a.source==='calorimetry')for(const example of c.CalorimetryReviewData.examples)for(const target of ['q','dh'])for(const massRoute of example.massRoutes)for(const amountRoute of example.amountRoutes.filter(r=>target==='q'||r!=='limiting'||level===3))for(const temperatureRoute of ['initial-final','delta','thermometers'])for(const structure of c.CalorimetryReviewCore.structureOptions(target,amountRoute,level).filter(s=>s.value!=='auto'))finiteVariants.push({level,exampleId:example.id,target,massRoute,amountRoute,temperatureRoute,structure:structure.value});
  levelMapping[level]=row;
 }
 for(const f of [...files,...shared,...deps.references.filter(r=>r.exists).map(r=>r.path)])sourcePaths.add(f);
 const masteryContext=context();load(masteryContext,a.course==='alevel'?src+'/assets/alevel-mastery.js':src+'/assets/igcse-mastery-config.js');const mastery=a.course==='alevel'?masteryContext.ALevelMastery:masteryContext.IGCSEMasteryConfig;
 const masteryRegistrations=a.course==='alevel'?Object.fromEntries(notes.leafIds.map(id=>[id,mastery.config[id]])):Object.fromEntries(Object.entries(mastery.activities).filter(([,config])=>notes.leafIds.includes(config.leafId)));
 const metadata=Object.fromEntries(modules.filter(([k])=>!/Core|Assessment|Session|Mastery|Levels/.test(k)).map(([k,v])=>[k,Object.fromEntries(['metadata','generationMetadata','source','sourceUrl','version','curriculum','gem'].filter(key=>v[key]!==undefined).map(key=>[key,v[key]]))]));
 let generatorFamilies=[];
 let historicalCodecMappings=null;
 if(a.source==='acid-base-calculations')historicalCodecMappings={prefix:'AB2',templates:c.AcidBaseLevels.templates.map((t,index)=>({templateId:t.id,legacyCodecIndex:index,indexBase36:index.toString(36).toUpperCase()})),format:'AB2-<source codec index>-<level>-<canonical uint32 seed base36>',source:'levels.js reviewId/decodeV2; ordinal is the historical codec mapping, never a navigation/display index'};
 if(a.source==='calorimetry'||a.source==='bond-enthalpy'){const codecSource=src+'/assets/generated-review.js';historicalCodecMappings={source:codecSource,prefix:a.source==='calorimetry'?'CAL':'BE',capacity:36**6,sourceFields:evidenceLines([codecSource],/key:.*radix:/).filter(row=>a.source==='calorimetry'?row.line>=25:row.line<=21)};}
 if(a.source==='electron-configurations'){const buckets=new Map();for(const s of c.ElectronData.species){const key=s.counts.join(',');if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(s.id);}generatorFamilies=[{id:'main',variantCount:levelMapping[3].count,sourceKeyFields:['speciesId','direction','representation']},{id:'matching',level:3,selection:'up to three isoelectronic positives, three negatives, seeded shuffle; complete group-mask 15 in active ECB codec',templates:[...buckets].filter(([,ids])=>ids.length>=2&&c.ElectronData.species.length-ids.length>=3).map(([counts,positiveIds])=>({counts:counts.split(',').map(Number),positiveIds,positiveCount:positiveIds.length,negativeCount:c.ElectronData.species.length-positiveIds.length}))}];generatorFamilies[1].templateCount=generatorFamilies[1].templates.length;}
 if(a.source==='acid-base-calculations')generatorFamilies=[{id:'active-v2',templateCount:c.AcidBaseLevels.templates.length,levelRouteCount:Object.values(levelMapping).reduce((n,row)=>n+row.count,0),seedDomain:'unsigned uint32, encoded canonically in AB2 review ID'},{id:'legacy-compatibility',templateCount:c.AcidBaseData.templates.length,source:'AcidBaseCore.generate and legacy decoder retained separately'}];
 if(a.source==='calorimetry')generatorFamilies=plainData(c.CalorimetryMastery.families);
 if(a.source==='bond-enthalpy')generatorFamilies=c.BondEnthalpyMastery.families.map(f=>({...plainData(f),levelReactionIds:Object.fromEntries(f.levels.map(level=>[level,levelMapping[level].sourceIds]))}));
 manifest.activities.push({...a,...notes,levelMapping,masteryRegistrations,masteryThreshold:a.strand==='curriculum'?mastery.threshold:null,dataMetadata:metadata,generatorFamilies,historicalCodecMappings,finiteGeneratorConfigurations:a.source==='calorimetry'?{kind:'core selectable configurations before numeric seed variation; amount route is retained even for q',count:finiteVariants.length,entries:finiteVariants}:null,sourceRoot:dir,entrypoint:html,activeScriptRefs,releaseIncludedFiles:released,notReleasedFiles:supporting,dependencies:deps,registrations:relevantRegistry,modules:coreApis,bankArrays,generatorCoverage:coverage,sourceHashes:files.map(fingerprint),runtimeSourceHashes:runtimeFiles.map(fingerprint),sourceEvidence:out+'/'+a.id.replace('/','-')+'-evidence.json'});
 if(mode!=='check'){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+'/'+a.id.replace('/','-')+'-evidence.json',JSON.stringify({activityId:a.id,lines},null,2)+'\n');}
}
manifest.sources=[...sourcePaths].sort().map(fingerprint);
const bonding=manifest.activities.find(a=>a.id==='alevel/electrons-bonding').dataMetadata.BondingData.source;
assert.equal(manifest.sources.find(s=>s.path===bonding.path).sha256,bonding.sha256,'Reviewed bonding CSV fingerprint disagrees with fixed bank provenance');
if(mode==='check'){const previous=JSON.parse(read(out+'/coverage-manifest.json'));const comparable=x=>{const y=JSON.parse(JSON.stringify(x));delete y.generatedAt;return y;};assert.deepEqual(comparable(manifest),comparable(previous));console.log(JSON.stringify({status:'PASS',activities:manifest.activities.length,fingerprintedSources:manifest.sources.length,check:'full regenerated manifest matches retained coverage and current source bytes'}));}
else fs.writeFileSync(out+'/coverage-manifest.json',JSON.stringify(manifest,null,2)+'\n');
assert.equal(manifest.activities.length,12);assert.deepEqual(manifest.activities.map(a=>a.id),contract.activities.map(a=>a.id));assert.equal(new Set(manifest.sources.map(s=>s.path)).size,manifest.sources.length);for(const a of manifest.activities){assert(fs.existsSync(a.entrypoint));assert(a.activeScriptRefs.length);assert.deepEqual(Object.keys(a.levelMapping).map(Number),a.supportedLevels);for(const bank of a.bankArrays){assert.equal(new Set(bank.ids).size,bank.ids.length, a.id+': duplicate IDs in '+bank.path);}for(const row of Object.values(a.levelMapping)){assert.equal(new Set(row.sourceIds).size,row.count);assert(row.count>0);}if(a.strand==='olympiad'){assert.equal(a.leafIds.length,0);assert.equal(a.supportedLevels.length,0);assert.equal(Object.keys(a.masteryRegistrations).length,0);assert.equal(a.registrations.length,0);}else{assert(a.leafIds.length);assert.equal(a.masteryThreshold,0.8);assert.equal(Object.keys(a.masteryRegistrations).length,a.leafIds.length);}}
