import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const code=['src/ui/QuestionPlayer.tsx','src/ui/ResponseControl.tsx','src/ui/CorrectionSegments.tsx','src/ui/EnergeticsResponseControl.tsx','src/ui/EnergeticsPracticalPilot.tsx','src/ui/energetics-practical-pilot.css','src/ui/fonts/PlaywriteEnglandJoined.ttf','src/ui/fonts/OFL-PlaywriteEnglandJoined.txt'];
const baseline=JSON.parse(fs.readFileSync(path.join(here,'../baseline.json'),'utf8'));
const changedPaths=code.map(file=>({path:file,sha256:hash(path.join(project,file)),baselineSha256:baseline.inputs.find(item=>item.path===file)?.sha256??null}));
const evidencePaths=fs.readdirSync(here).filter(name=>!['completion.json','manifest.mjs'].includes(name)).map(name=>'validation/component-fidelity/f1/ui-pilot/'+name);
const browser=JSON.parse(fs.readFileSync(path.join(here,'browser-results.json'),'utf8')),verification=JSON.parse(fs.readFileSync(path.join(here,'verification.json'),'utf8'));
const report={jobId:'F1-UI-PILOT',agentId:'F03',runId:'COMPONENT-FIDELITY-20261003',status:browser.status==='PASS'&&verification.status==='PASS'?'PASS':'FAIL',completedAt:new Date().toISOString(),outputPath:'validation/component-fidelity/f1/ui-pilot/HANDOVER.md',evidencePaths,changedPaths,validation:{typecheck:verification.status,chemistryMarking:'PASS - unchanged practical/source/controller focused regression',browser:browser.status,screenshotCount:browser.screenshots.length,sourceMatrix:'12 activities; exact source-linked DOM/CSS/font/SVG/interaction and state locators',contactSheets:['validation/component-fidelity/f1/ui-pilot/contact-desktop.png','validation/component-fidelity/f1/ui-pilot/contact-tablet.png','validation/component-fidelity/f1/ui-pilot/contact-mobile.png'],protectedApps:'F01 stage validation owner; no protected writes',productionBuilds:'F01 integration owner; code frozen'},confidence:0.98,unresolved:[],limitations:['Only five diagram-free EP written-correction/typed-answer questions activate the F1 pilot; other controls/states are matrix-only preparation for F2.','Native OS hidden/minimised/suspend not tested or claimed.','Full historical S3 energy identity assertions still use obsolete C01 codes; F02 owns canonical coverage; focused practical/source/controller chemistry tests PASS.','No complete textual before/after diff was captured; baseline hashes and function-level change map supplied.'],usage:null,servers:{original:{url:'http://127.0.0.1:5197',session:27739,readOnly:true},react:{url:'http://127.0.0.1:5188',session:99905},shutdownOwner:'F01/root after acceptance review'}};
fs.writeFileSync(path.join(here,'completion.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({jobId:report.jobId,agentId:report.agentId,status:report.status,outputPath:report.outputPath,evidencePath:'validation/component-fidelity/f1/ui-pilot/completion.json',changedPaths:changedPaths.map(p=>p.path),validation:report.validation,confidence:report.confidence,unresolved:report.unresolved}));
