import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const here=import.meta.dirname,workspace=path.resolve(here,'../../../../../..');
const entries=[
 ['alevel','acid-base-calculations',['numeric','numeric-working'],['levels-app.js','levels.css','scaffold.js'],'Separate original built-in stages at Level 1 from requested support; strict scientific rounding; multipart all-required submission.',['.answer-input','.working-input','.marking','.feedback']],
 ['alevel','electrons-bonding',['short-text','choice','typed-gap'],['app.js','styles.css'],'Preserve complete-set selections, missing versus rejected response, rendered electronic subscripts and charge conventions.',['.answer-input','.choice-option','.answer-row','.feedback']],
 ['alevel','electron-configurations',['subshell-count','orbital-box','identity-choice','core-dropdown','isoelectronic-multiple-choice'],['levels-app.js','styles.css'],'Active levels-app.js supersedes dormant app.js. Preserve paired spins, equivalent orbital permutations, orbital energy geometry, shorthand core and matching complete set.',['.species-card','.orbital-box','.orbital-boxes','.configuration-display','.bonus-options','.bonus-option']],
 ['alevel','dot-and-cross',['electron-placement','bonding-editor','atom-editor'],['app.js','styles.css'],'Accepted dot-cross experience is preserved; maintain source diagram/layout and chemistry validator, keyboard and non-drag electron placements.',['.editor','.workspace','.feedback']],
 ['alevel','ph-titration-curves',['curve-editor','curve-numeric','curve-choice'],['app.js','styles.css'],'Reproduce original SVG curves, axes, draggable handles plus numeric non-drag controls, strong/weak combinations and half/equivalence prompts.',['.curve','.handle','.plot','.feedback']],
 ['alevel','c3l6-organic-reactions',['sequential-molecule-editor','structure-selection','challenge-completion'],['activity.js','styles.css'],'Olympiad only; linked original structures and introductory examples; preserve sequential dependencies, saved drawings and accepted molecule editor; no mastery/timing evidence.',['.challenge','.molecule','.stage','.feedback']],
 ['igcse','calorimetry',['numeric','numeric-working','drawing-self-check'],['app.js','styles.css'],'Original seeded mass/temperature/heat-capacity contexts; preserve worked formula fractions/units, raw final result and mandatory drawing/equation self-check where applicable.',['.working','.answer-input','.marking','.feedback']],
 ['igcse','bond-enthalpy',['numeric','numeric-working','drawing-self-check','molecule-reference'],['app.js','styles.css'],'Preserve balanced equation/stoichiometry, bond tally, sign convention and source molecule SVGs; diagram self-assessment follows frozen independent calculation.',['.working','.answer-input','.marking','.feedback']],
 ['igcse','structure-and-bonding',['explanation-sections','rubric-self-review','evidence-selection'],['app.js','styles.css'],'Explanation fields freeze before rubric review. Preserve source student-answer/evidence highlighting, staged rubric points and valid alternatives; never auto-mark long reasoning.',['.answer','.rubric','.marking','.feedback']],
 ['igcse','dot-and-cross',['electron-placement','bonding-editor','atom-editor'],['app.js','styles.css'],'Accepted shared editor preserved with course-specific bank/validator; no element/species charge or valence generalisation.',['.editor','.workspace','.feedback']],
 ['igcse','energy-enthalpy',['typed-gap','button-choice','reaction-profile-editor','equation-reference'],['app.js','styles.css','editor.js'],'Preserve source reaction-profile SVG geometry, independent reactant/product/activation handles, labelled energy changes, typed gaps and expected-versus-unrecognised feedback.',['.answer-field','.answer-input','.answer-options','.answer-option','.field-note','.feedback']],
 ['igcse','energetics-practical',['typed-answer','written-correction','apparatus-selection','multiple-choice','graph-reference','equivalent-wording-review'],['app.js','styles.css','diagrams.js'],'Final CSS overrides are authoritative. Handwritten pupil phrase buttons use Playwrite England Joined; correction error selection is prerequisite to replacement point. Original per-point equivalents become learning review only, first evidence stays fixed.',['.question-workspace','.question-content','.marking','.field-set','.answer-input','.answer-area','.correction-box','.correction-segments','.error-segment','.mcq-options','.mcq-option','.results','.result-row','.override-button','.review-answer']]
];
const hash=text=>crypto.createHash('sha256').update(text).digest('hex');
function evidence(file){const absolute=path.join(workspace,file);if(!fs.existsSync(absolute))return{path:file,exists:false};const bytes=fs.readFileSync(absolute),text=bytes.toString('utf8');return{path:file,sha256:hash(bytes),bytes:bytes.length,text};}
const activities=entries.map(([course,activity,controlKinds,extra,pedagogy,selectors])=>{
 const base=`apps/Masters-of-${course==='alevel'?'A-Level':'IGCSE'}-Chemistry/src/activities/${activity}`;
 const html=evidence(`${base}/index.html`);const linked=[...html.text.matchAll(/(?:src|href)="([^"]+\.(?:js|css))"/g)].map(m=>path.posix.normalize(`${base}/${m[1]}`));
 const files=[...new Set([html.path,...linked,...extra.map(x=>`${base}/${x}`)])].map(evidence).filter(x=>x.exists!==false);
 const sourceFiles=files.map(({text,...item})=>item);
 const domDefinitions=files.filter(f=>f.path.endsWith('.js')||f.path.endsWith('.html')).flatMap(f=>f.text.split(/\r?\n/).flatMap((line,index)=>{
  if(!/(?:createElement|className|classList|innerHTML|setAttribute\(['"](?:aria|role)|<input|<textarea|<svg|<button|<fieldset|<select|keydown|pointerdown|pointermove|touchstart|function\s+(?:make|render|mark|check|construction|identity|diagram|boxMarkup|start|matching))/i.test(line))return[];
  return[{path:f.path,line:index+1,excerpt:line.trim()}];
 }));
 const cssRules=files.filter(f=>f.path.endsWith('.css')).flatMap(f=>[...f.text.matchAll(/([^{}]+)\{([^{}]*)\}/g)].map(m=>({path:f.path,line:f.text.slice(0,m.index).split('\n').length,selector:m[1].trim(),declarations:m[2].trim(),requestedComponentFamily:selectors.some(s=>m[1].includes(s))||/font-face/.test(m[1])})));
 const fonts=files.filter(f=>f.path.endsWith('.css')).flatMap(f=>[...f.text.matchAll(/url\(['"]?([^)'"\s]+\.(?:ttf|woff2?))['"]?\)/g)].map(m=>path.posix.normalize(`${path.posix.dirname(f.path)}/${m[1]}`))).filter((v,i,a)=>a.indexOf(v)===i).map(evidence).map(({text,...f})=>f);
 const inlineSvg=files.filter(f=>/\.(?:js|html)$/.test(f.path)).flatMap(f=>f.text.split(/\r?\n/).flatMap((line,index)=>/<svg|viewBox|<path|<line|<circle|<polyline|<polygon|<ellipse|<rect|<text|createElementNS|setAttribute\(['"](?:d|x|y|cx|cy|r|points|viewBox)/.test(line)?[{path:f.path,line:index+1,excerpt:line.trim()}]:[]));
 const responsiveConditions=files.filter(f=>f.path.endsWith('.css')).flatMap(f=>[...f.text.matchAll(/@media[^{}]+/g)].map(m=>({path:f.path,line:f.text.slice(0,m.index).split('\n').length,condition:m[0].trim()})));
 const svgAssetFiles=[];function collectSvg(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const target=path.join(dir,item.name);if(item.isDirectory())collectSvg(target);else if(item.name.endsWith('.svg'))svgAssetFiles.push(target);}}collectSvg(path.join(workspace,base));
 const externalSvgAssets=svgAssetFiles.map(file=>{const relative=path.relative(workspace,file).split(path.sep).join('/'),item=evidence(relative);return{path:relative,sha256:item.sha256,bytes:item.bytes,viewBox:item.text.match(/viewBox="([^"]+)"/)?.[1]??null,geometry:item.text};});
 return{id:`${course}/${activity}`,course,controlKinds,canonicalRoute:`http://127.0.0.1:5197/${course}/activities/${activity}/index.html`,pedagogy,
  sourceFiles,fonts,domDefinitions,cssRulesInCascadeOrder:cssRules,responsiveConditions,inlineSvgDefinitions:inlineSvg,externalSvgAssets,
  requiredStates:['unanswered','partial','incorrect','correct','correction','model'],
  stateEvidence: Object.fromEntries(['unanswered','partial','incorrect','correct','correction','model'].map(state=>[state,domDefinitions.filter(d=>new RegExp(state==='unanswered'?'empty|blank|disabled|ready':state==='partial'?'ready|incomplete|refreshCheck|input':state==='incorrect'?'wrong|error|incorrect|reject|false':state==='correct'?'correct|true|pass':state==='correction'?'retry|reset|override|correction|recheck':'model|answer|review|reveal','i').test(d.excerpt)).map(d=>({path:d.path,line:d.line}))])),
  f1:activity==='energetics-practical'?'Diagram-free written-correction/typed replacement pilot; graph correction and remaining controls scheduled F2':activity==='dot-and-cross'||activity==='c3l6-organic-reactions'?'Preserve accepted specialist experience':'Reference-only; restore in F2',
  note:'DOM/CSS references include the active HTML-linked shared styles and appended final overrides in file cascade order; CSS excerpts are reference evidence, not imported global styles.'};
});
const matrix={schemaVersion:1,runId:'COMPONENT-FIDELITY-20261003',jobId:'F1-UI-PILOT',agentId:'F03',generatedAt:new Date().toISOString(),scope:'All 12 canonical active activity component families and states; original sources read-only, no original builds or reconstructed page wrappers',activities};
if(activities.length!==12||new Set(activities.map(a=>a.id)).size!==12)throw Error('Matrix coverage');
for(const a of activities)if(!a.sourceFiles.length||!a.domDefinitions.length||!a.cssRulesInCascadeOrder.length)throw Error(`Missing source-linked component evidence ${a.id}`);
fs.writeFileSync(path.join(here,'reference-matrix.json'),JSON.stringify(matrix,null,2)+'\n');
fs.writeFileSync(path.join(here,'REFERENCE-MATRIX.md'),'# Original component restoration matrix\n\nSource-linked machine evidence: [reference-matrix.json](reference-matrix.json). Generated by `node validation/component-fidelity/f1/ui-pilot/reference-matrix.mjs`. This matrix covers all twelve current activities, active HTML dependencies, exact control DOM construction lines, CSS rules in cascade order, font hashes and SVG definitions. Unanswered/partial/incorrect/correct/correction/model source locators are retained separately. Locators do not claim rendered verification for F2.\n\n| Activity | Control families | Educational distinction | F1 scope |\n|---|---|---|---|\n'+activities.map(a=>`| ${a.id} | ${a.controlKinds.join(', ')} | ${a.pedagogy} | ${a.f1} |`).join('\n')+'\n\n## Restoration boundaries\n\nKeep the accepted common masthead, one pink canonical code at top, grade/level pill, footer and invisible timing. Reuse component DOM, final CSS, fonts and source-owned SVG geometry; do not restore source page headers, progress, timers, pause/navigation wrappers, source storage or assessment ownership. Preserve dot-cross and molecule editor experience. F2 must take equivalent-state desktop/tablet/mobile browser screenshots and inspect them; this source matrix is preparation, not F2 acceptance.\n\n## Pilot source corrections\n\nEP-CXMNAV, EP-CNN1LW, EP-DHLUOT, EP-6O192J and EP-6E1NDK use the final handwriting and typed replacement controls. EP-780GGH has a graph and remains on its existing player until F2. Original selected phrase uses a native button with inline boxed text and Playwrite England Joined; it moves focus to the replacement input. Keep literal punctuation and whitespace from source segments. Original checked inputs lock, while new learning correction remains editable after first assessment under the shared immutable assessment engine. That host adaptation is deliberate and does not create a new score.\n');
console.log(`Source matrix: ${activities.length} activities, ${activities.reduce((n,a)=>n+a.domDefinitions.length,0)} DOM/interaction references, ${activities.reduce((n,a)=>n+a.cssRulesInCascadeOrder.length,0)} CSS rules`);
