import {chromium} from '../../../../../node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const here=import.meta.dirname,bank=JSON.parse(fs.readFileSync(path.join(here,'../../../src/activities/olympiad/c3l6/bank.json'),'utf8')),run=`a16-c3-${Date.now()}`;
const qualification=JSON.parse(fs.readFileSync(path.join(here,'../../../src/activities/olympiad/c3l6/qualification.json'),'utf8'));
const report={jobId:'S3-OLYMPIAD-C3L6',run,startedAt:new Date().toISOString(),checks:[],errors:[],status:'RUNNING'};
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage();
page.on('pageerror',e=>report.errors.push(e.message));
const check=s=>{report.checks.push(s);console.log(s);},snap=()=>page.evaluate(()=>window.__mastersOlympiad.snapshot()),flush=()=>page.evaluate(()=>window.__mastersOlympiad.flush());
async function click(name){await page.getByRole('button',{name,exact:true}).click();await flush();}
async function command(c){await page.evaluate(c=>window.__mastersOlympiad.command(c),c);await flush();}
async function load(p=page,suffix=run,teacher=false){await p.goto(`http://127.0.0.1:5181/alevel.html?run=${suffix}&olympiad=c3l6${teacher?'&mode=teacher':''}`);await p.waitForFunction(()=>window.__mastersOlympiad?.snapshot().progress!==null);await p.locator('.c3l6').waitFor();}
async function counts(p=page){return p.evaluate(async()=>{const {databaseName}=window.__mastersOlympiad.snapshot();return new Promise((resolve,reject)=>{const r=indexedDB.open(databaseName);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,tx=db.transaction(['attempts','evidence','sessions','olympiad'],'readonly'),out={};for(const key of tx.objectStoreNames){const q=tx.objectStore(key).count();q.onsuccess=()=>out[key]=q.result;}tx.oncomplete=()=>{db.close();resolve(out);};};});});}
async function completeA(p=page){for(const a of bank.stages.a.answers)await p.evaluate(c=>window.__mastersOlympiad.command(c),{kind:'classify',id:a.id,value:a.answer});await p.evaluate(()=>window.__mastersOlympiad.command({kind:'check-a'}));await p.evaluate(()=>window.__mastersOlympiad.flush());}
const state=graph=>({kind:'molecule',graph,history:[]});
try{
 await load();assert.equal((await snap()).progress.stage,'intro');assert.equal(await page.getByRole('button',{name:'Part (b)',exact:true}).isDisabled(),true);await page.screenshot({path:path.join(here,'intro-desktop.png'),fullPage:true});await click('Start part (a)');
 assert.equal(await page.locator('.c3-reaction').count(),10);assert.equal(await page.getByRole('button',{name:'Check part (a)',exact:true}).isDisabled(),true);
 for(const a of bank.stages.a.answers){await page.locator('fieldset').filter({has:page.getByText('Reaction '+a.label,{exact:true})}).getByRole('radio',{name:a.answer,exact:true}).check();await flush();}
 await click('Check part (a)');assert.equal((await snap()).progress.completed.a,true);assert.equal((await snap()).saveStatus.kind,'saved');await page.screenshot({path:path.join(here,'classifications-desktop.png'),fullPage:true});await click('Continue to part (b)');
 check('real classification UI preserves all10, checks whole part and gates b/c; actual repository saves');
 // Build genuine methanoic acid via molecular controls, not a model selector.
 await click('Add atom');await page.getByLabel('Selected atom',{exact:true}).selectOption('1');await page.getByLabel('New element',{exact:true}).selectOption('O');await page.getByLabel('Bond order',{exact:true}).selectOption('2');await click('Extend selected atom');await page.getByLabel('Bond order',{exact:true}).selectOption('1');await page.getByLabel('Extension direction',{exact:true}).selectOption('120');await click('Extend selected atom');
 let s=await snap();assert.equal(s.progress.drawingsB.A.graph.atoms.length,3);assert.equal(s.progress.drawingsB.A.graph.bonds.length,2);assert(await page.locator('.molecule-editor').innerText().then(t=>t.includes('CH2O2')));
 const before=structuredClone(s.progress.drawingsB.A);const atom=page.getByRole('button',{name:/^Atom 2,/});await atom.focus();await page.keyboard.press('ArrowDown');await flush();assert.equal((await snap()).progress.drawingsB.A.graph.atoms[1].y,before.graph.atoms[1].y+10);await click('Undo');assert.deepEqual((await snap()).progress.drawingsB.A,before);
 const view=await page.locator('.molecule-workspace').getAttribute('viewBox');await click('Fit molecule');assert.notEqual(await page.locator('.molecule-workspace').getAttribute('viewBox'),view);await click('Zoom out');await click('Pan right');assert.deepEqual((await snap()).progress.drawingsB.A,before);
 await atom.scrollIntoViewIfNeeded();const box=await atom.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+25,box.y+box.height/2+15,{steps:5});await page.mouse.up();await flush();assert.notDeepEqual((await snap()).progress.drawingsB.A.graph,before.graph);await click('Undo');assert.deepEqual((await snap()).progress.drawingsB.A,before);
 await page.screenshot({path:path.join(here,'methanoic-acid-editor-desktop.png'),fullPage:true});await page.reload();await page.waitForFunction(()=>window.__mastersOlympiad?.snapshot().progress?.stage==='b');assert.deepEqual((await snap()).progress.drawingsB.A,before);check('authentic spatial methanoic-acid construction, keyboard/pointer move, semantic Undo and saved graph/history reload');
 const hydrazone=page.locator('.c3-unit').nth(2);await hydrazone.getByRole('heading',{name:qualification.student.label,exact:true}).waitFor();assert((await hydrazone.innerText()).includes(qualification.student.context));const image=hydrazone.getByRole('img',{name:qualification.student.imageAlt,exact:true});await image.evaluate(img=>img.decode());const svgMetadata=await image.evaluate(async img=>fetch(img.src).then(r=>r.text()));assert(svgMetadata.includes('<title>'+qualification.publicCopiedSvgMetadata.title+'</title>'));assert(svgMetadata.includes('<desc>'+qualification.publicCopiedSvgMetadata.description+'</desc>'));const unsolvedText=await page.locator('.c3l6').innerText();assert(!/gyromitrin|fungal toxin|propanone/i.test(unsolvedText));assert.equal(await page.getByRole('heading',{name:'Teacher source note',exact:true}).count(),0);await hydrazone.screenshot({path:path.join(here,'qualified-hydrazone-student-desktop.png')});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await hydrazone.screenshot({path:path.join(here,'qualified-hydrazone-student-mobile.png')});await page.setViewportSize({width:1440,height:1100});check('exact reviewed model label/context/accessible alt and public SVG title/desc; unsolved student context contains no gyromitrin claim, fungal-toxin claim or product-D disclosure; affected desktop/mobile fit');
 // Stage B checks run on all products; deliberately wrong same-formula structure remains assessable.
 for(const unit of (await page.evaluate(async()=>{const m=await import('/src/activities/olympiad/c3l6/index.ts');return m.c3Challenge.dependencies.bUnits;}))){for(const id of unit.slots){if(id==='A')continue;const slot=bank.stages.b.answers.find(a=>a.id===id);await command({kind:'draw-b',slotId:id,drawing:state(slot.alternatives.at(-1).graph)});}await command({kind:'check-b-unit',unitId:unit.id});}
 assert.equal((await snap()).progress.completed.b,true);assert.equal(await page.locator('.c3-unit').count(),7);await click('Continue to part (c)');await click('Z');
 // Build epoxide via explicit ring closure in the UI.
 await page.getByLabel('New element',{exact:true}).selectOption('C');await click('Add atom');await page.getByLabel('Selected atom',{exact:true}).selectOption('1');await page.getByLabel('Extension direction',{exact:true}).selectOption('120');await click('Extend selected atom');await page.getByLabel('Selected atom',{exact:true}).selectOption('2');await page.getByLabel('New element',{exact:true}).selectOption('O');await page.getByLabel('Extension direction',{exact:true}).selectOption('0');await click('Extend selected atom');await page.getByLabel('Selected atom',{exact:true}).selectOption('1');await page.getByLabel('Bond target',{exact:true}).selectOption('3');await click('Set / close bond');await click('Check structure Z');assert.equal((await snap()).progress.slotChecks.Z.passed,true);
 check('all12 hydrolysis products/seven unit checks preserve G/K alternatives; epoxide built by real ring closure and checked');
 for(const slot of bank.stages.c.answers.filter(s=>s.id!=='Z')){await command({kind:'draw-c',slotId:slot.id,drawing:state(slot.alternatives[0].graph)});await command({kind:'check-c-slot',slotId:slot.id});}
 const completed=structuredClone((await snap()).progress);assert.deepEqual(completed.completed,{a:true,b:true,c:true});await command({kind:'check-c-slot',slotId:'Z'});assert.deepEqual((await snap()).progress,completed);assert.deepEqual(await counts(),{attempts:0,evidence:0,sessions:0,olympiad:1});
 await page.reload();await page.waitForFunction(()=>window.__mastersOlympiad?.snapshot().progress?.completed.c);assert.deepEqual((await snap()).progress,completed);await page.screenshot({path:path.join(here,'completed-network-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(here,'completed-network-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1100});
 check('all9 C targets complete; duplicate checks/reload keep one Olympiad row with zero curriculum attempts/evidence/sessions');
 await click('Restart challenge');await page.getByRole('dialog',{name:'Restart this challenge?',exact:true}).waitFor();await click('Cancel restart');assert.deepEqual((await snap()).progress,completed);await click('Restart challenge');await click('Confirm restart');s=await snap();assert.equal(s.progress.stage,'intro');assert.deepEqual(s.progress.completed,{a:false,b:false,c:false});assert.deepEqual(s.progress.drawingsB,{});assert.deepEqual(s.progress.drawingsC,{});assert.deepEqual(await counts(),{attempts:0,evidence:0,sessions:0,olympiad:1});await page.reload();await page.waitForFunction(()=>window.__mastersOlympiad?.snapshot().progress?.stage==='intro');assert.deepEqual((await snap()).progress.completed,{a:false,b:false,c:false});check('source confirmed Restart: cancel preserves state; confirm clears only challenge state and retains one isolated row through reload');
 // Teacher can inspect all stages before any pupil completion, without saving.
 const teacher=await context.newPage();teacher.on('pageerror',e=>report.errors.push(e.message));await load(teacher,run+'-teacher',true);
 await teacher.getByRole('button',{name:'Part (a)',exact:true}).click();assert.equal(await teacher.locator('.c3-reaction').count(),10);for(let i=0;i<10;i++)await teacher.locator('.c3-reaction').nth(i).screenshot({path:path.join(here,`review-a-${i+1}.png`)});
 await teacher.getByRole('button',{name:'Part (b)',exact:true}).click();const sourceNote=teacher.getByRole('complementary',{name:'Teacher source note',exact:true});assert((await sourceNote.innerText()).includes(qualification.teacher.note));assert((await sourceNote.innerText()).includes(qualification.teacher.provenanceNote));assert.equal(await sourceNote.getByRole('link',{name:'PubChem CID 9548611',exact:true}).getAttribute('href'),qualification.teacher.citation);await sourceNote.screenshot({path:path.join(here,'qualified-hydrazone-teacher-desktop.png')});await teacher.setViewportSize({width:390,height:844});assert(await teacher.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await sourceNote.screenshot({path:path.join(here,'qualified-hydrazone-teacher-mobile.png')});await teacher.setViewportSize({width:1440,height:1100});check('exact separate teacher source note and primary citation preserve source-label provenance without leaking D into the student prompt');for(const slot of bank.stages.b.answers){await teacher.getByRole('button',{name:`Edit structure ${slot.id}`,exact:true}).click();await teacher.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await teacher.locator('.c3-editor-panel').screenshot({path:path.join(here,`review-b-${slot.id}.png`)});await teacher.locator('.c3-editor-panel details').screenshot({path:path.join(here,`graphs-b-${slot.id}.png`)});}
 await teacher.getByRole('button',{name:'Part (c)',exact:true}).click();for(const slot of bank.stages.c.answers){await teacher.getByRole('button',{name:slot.id,exact:true}).click();await teacher.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await teacher.locator('.c3-editor-panel').screenshot({path:path.join(here,`review-c-${slot.id}.png`)});await teacher.locator('.c3-editor-panel details').screenshot({path:path.join(here,`graphs-c-${slot.id}.png`)});}
 assert.deepEqual(await counts(teacher),{attempts:0,evidence:0,sessions:0,olympiad:0});await teacher.setViewportSize({width:390,height:844});assert(await teacher.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await teacher.screenshot({path:path.join(here,'teacher-mobile.png'),fullPage:true});await teacher.close();check('fresh teacher review unlocks allsource stages and renders all23 accepted alternative graphs, no saved completion/evidence');
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),mobile=await mobileContext.newPage();await load(mobile,run+'-touch');await completeA(mobile);await mobile.getByRole('button',{name:'Part (b) · Complete',exact:true}).count();await mobile.getByRole('button',{name:'Part (b)',exact:true}).tap();await mobile.getByRole('button',{name:'Edit structure M',exact:true}).tap();await mobile.getByLabel('New element',{exact:true}).selectOption('N');await mobile.getByRole('button',{name:'Add atom',exact:true}).tap();await mobile.evaluate(()=>window.__mastersOlympiad.flush());assert.equal(await mobile.evaluate(()=>window.__mastersOlympiad.snapshot().progress.drawingsB.M.graph.atoms[0].element),'N');assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:path.join(here,'touch-ammonia.png'),fullPage:true});await mobile.getByRole('button',{name:'Undo',exact:true}).tap();await mobile.evaluate(()=>window.__mastersOlympiad.flush());assert.equal(await mobile.evaluate(()=>window.__mastersOlympiad.snapshot().progress.drawingsB.M.graph.atoms.length),0);await mobileContext.close();check('real mobile touch slot/element/atom/Undo controls and narrow viewport fit');
 assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;console.error(e);await page.screenshot({path:path.join(here,'browser-failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));await browser.close();}
