import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=process.cwd(),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),files=[];
for(const rel of ['src/activities/olympiad/c3l6','src/chemistry/molecule','src/editors/molecule']){function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())walk(p);else files.push({path:path.relative(root,p).replaceAll('\\','/'),sha256:hash(p)});}}walk(path.join(root,rel));}
const source=JSON.parse(fs.readFileSync(path.join(root,'validation/s3/c3l6/source-fingerprints.json'),'utf8'));
const workspace=path.resolve(root,'../..'),metadataQualifiedAssets=[];for(const item of source){const originalPath=path.join(workspace,item.path);if(hash(originalPath)!==item.sha256)throw Error('Original source changed: '+item.path);const asset=item.path.match(/\/c3l6-organic-reactions\/(assets\/digitised\/.*)$/);if(asset){const copied=path.join(root,'src/activities/olympiad/c3l6',asset[1]),copiedHash=hash(copied);if(copiedHash!==item.sha256){if(asset[1]!=='assets/digitised/b/gyromitrin-skeletal-notes.svg')throw Error('Copied asset differs: '+asset[1]);const original=fs.readFileSync(originalPath,'utf8'),qualified=fs.readFileSync(copied,'utf8'),review=JSON.parse(fs.readFileSync(path.join(root,'src/activities/olympiad/c3l6/qualification.json'),'utf8'));const title=qualified.match(/<title>([\s\S]*?)<\/title>/)[1],description=qualified.match(/<desc>([\s\S]*?)<\/desc>/)[1];if(title!==review.publicCopiedSvgMetadata.title||description!==review.publicCopiedSvgMetadata.description)throw Error('Qualified wording differs from reviewed exact metadata.');const recovered=qualified.replace(/<title>[\s\S]*?<\/title>/,original.match(/<title>[\s\S]*?<\/title>/)[0]).replace(/<desc>[\s\S]*?<\/desc>/,original.match(/<desc>[\s\S]*?<\/desc>/)[0]),recoveredHash=crypto.createHash('sha256').update(recovered).digest('hex');if(recoveredHash!==item.sha256)throw Error('SVG change exceeds title/description qualification.');metadataQualifiedAssets.push({path:asset[1],originalSha256:item.sha256,qualifiedSha256:copiedHash,recoveredGeometryAndAllOtherBytesSha256:recoveredHash,disposition:'S3-REVIEW-C3-NAME APPROVE_BOUNDED_MODEL_QUALIFICATION'});}}}
const result={status:'PASS',checkedAt:new Date().toISOString(),originalSourceFilesUnchanged:source.length,byteIdenticalCopiedAssets:source.filter(s=>s.path.includes('/assets/digitised/')).length-metadataQualifiedAssets.length,metadataQualifiedAssets,files:files.sort((a,b)=>a.path.localeCompare(b.path))};
fs.writeFileSync(path.join(root,'validation/s3/c3l6/output-fingerprints.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,originalSourceFilesUnchanged:source.length,byteIdenticalCopiedAssets:result.byteIdenticalCopiedAssets,runtimeFiles:files.length}));
