import {chromium} from '../../../../node_modules/playwright/index.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const here=import.meta.dirname,browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),run='dot-special-'+Date.now();
const report={startedAt:new Date().toISOString(),checks:[],failures:[],pageErrors:[]};page.on('pageerror',e=>report.pageErrors.push(e.message));
let fixtureNumber=0;
const snapshot=()=>page.evaluate(()=>window.__mastersActivity.snapshot()),flush=()=>page.evaluate(()=>window.__mastersActivity.flush());
async function ready(){await page.waitForFunction(()=>window.__mastersActivity);await page.waitForFunction(()=>window.__mastersActivity.snapshot().saveStatus.kind!=='saving');}
async function reload(){await page.reload();await ready();if(await page.getByRole('button',{name:'Resume saved attempt',exact:true}).count())await page.getByRole('button',{name:'Resume saved attempt',exact:true}).click();await page.locator('.dot-cross-editor svg').waitFor();await flush();}
async function fixture(course,sourceId){const activityId=course+'/dot-and-cross';await page.goto(`http://127.0.0.1:5203/${course}.html?course=${course}&run=${run}-${sourceId}-${++fixtureNumber}&view=practice&activity=${activityId}`);await ready();await page.evaluate(async({course,sourceId,activityId})=>{const {productionRegistry}=await import('/src/foundation/registry.ts'),{createChemistryRepository}=await import('/src/persistence/index.ts'),{fixedIdentity}=await import('/src/content/canonical-identity.ts'),registration=productionRegistry.get(activityId),provider=await registration.provider(),questionId=fixedIdentity(course==='alevel'?'DAC':'DC').code(sourceId),level=course==='alevel'&&['phosphorus-pentachloride','sulfur-hexafluoride'].includes(sourceId)?3:2,target={course,activityId,gemId:registration.gems[0].id,level},ref={activityId,questionId,level,seed:0},q=provider.restore(ref),id=crypto.randomUUID(),namespace={course,profileId:'local'},attempt={mode:'student',namespace,attemptId:id,ref,target,currentResponses:{},assistance:[],phase:'answering',timing:{attemptId:id,activeMs:0,idleLimitMs:registration.idleAllowance(q),finished:false}},session={kind:'practice',namespace,id:'current-session',target,selection:'fixed-level',currentAttemptId:id,previousQuestionIds:[],paused:false};const saved=await createChemistryRepository(window.__mastersActivity.snapshot().databaseName).saveCurriculum({attempt,session});if(!saved.ok)throw Error(saved.error.message);},{course,sourceId,activityId});await reload();}
async function response(kind='reference'){await page.evaluate(async kind=>{const s=window.__mastersActivity.snapshot(),course=s.question.ref.activityId.split('/')[0],provider=await import(`/src/activities/${course}/dot-and-cross/provider.ts`),record=provider.getRecord(s.question.ref.questionId),state={kind:'dot-and-cross',...structuredClone(record.reference)};if(kind==='wrong')state.electrons.pop();if(kind==='atoms')state.electrons=[];await window.__mastersActivity.respond('diagram',state);},kind);await flush();}
const action=name=>page.locator(`[data-question-action="${name}"]`);
async function check(){await action('check').click();await flush();}
async function screenshot(name){await page.screenshot({path:path.join(here,name+'.png'),fullPage:false,animations:'disabled',timeout:60000});}
async function row(expected){const status=page.locator('.dot-check-status');assert.equal(await status.textContent(),expected);if(expected){const cls=await status.getAttribute('class');assert(cls.includes(expected.toLowerCase()));const [s,a,b,card]=await Promise.all([status.boundingBox(),page.locator('.dot-question-actions').boundingBox(),action('check').boundingBox(),page.locator('.dc-editor-card').boundingBox()]);assert(Math.abs(s.x-a.x)<2);assert(Math.abs(s.y+s.height/2-b.y-b.height/2)<2);assert(a.y+a.height<=card.y+2);assert.equal(b.height,36);const next=await action('next').boundingBox();assert(Math.abs(next.x+next.width-a.x-a.width)<3);}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
async function attemptCheck(id,fn){if(process.argv[2]&&id!==process.argv[2])return;try{await fn();report.checks.push({id,status:'PASS'});}catch(error){report.failures.push({id,error:error.stack});await screenshot('FAIL-'+id);}}
try{
 for(const [sourceId,centre,terminal] of [['sulfur-hexafluoride','S','F'],['phosphorus-pentachloride','P','Cl']])await attemptCheck(sourceId+'-pointer-geometry',async()=>{
  await page.setViewportSize({width:1440,height:1000});await fixture('alevel',sourceId);
  const canvas=page.locator('.dot-cross-editor svg');
  const screen=async p=>canvas.evaluate((svg,p)=>{const s=new DOMPoint(p.x,p.y).matrixTransform(svg.getScreenCTM());return{x:s.x,y:s.y};},p);
  async function dragAtom(element,p,expectedRadius,expectedX){const button=page.getByRole('button',{name:element+' atom',exact:true});await button.scrollIntoViewIfNeeded();const b=await button.boundingBox(),s=await screen(p);await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(s.x,s.y,{steps:6});const ghost=page.locator('.drag-ghost circle');assert.equal(Number(await ghost.getAttribute('r')),expectedRadius);assert(Math.abs(Number(await ghost.getAttribute('cx'))-expectedX)<0.001);await screenshot(sourceId+'-drag-'+element);await page.mouse.up();await flush();}
  await dragAtom(centre,{x:500,y:325},100,500);await dragAtom(terminal,{x:635,y:325},64,640);
  let state=(await snapshot()).attempt.currentResponses.diagram;assert.equal(state.atoms.length,2);assert(Math.abs(Math.hypot(state.atoms[0].x-state.atoms[1].x,state.atoms[0].y-state.atoms[1].y)-140)<1e-7);
  await page.getByRole('button',{name:'Dot electron',exact:true}).click();const s=await screen({x:588,y:325});await page.mouse.move(s.x,s.y);await page.locator('.electron-preview').waitFor();await screenshot(sourceId+'-electron-preview');await page.mouse.click(s.x,s.y);await flush();state=(await snapshot()).attempt.currentResponses.diagram;assert.equal(state.electrons.length,1);assert.equal(state.electrons[0].anchor.kind,'bond');await row('');
  const saved=structuredClone(state);await reload();assert.deepEqual((await snapshot()).attempt.currentResponses.diagram,saved);assert.equal(await page.locator('.dot-cross-editor .shell[r="100"]').count(),1);
 });
 for(const [sourceId,centre,terminal] of [['sulfur-hexafluoride','S','F'],['phosphorus-pentachloride','P','Cl']])await attemptCheck(sourceId,async()=>{
  await page.setViewportSize({width:1440,height:1000});await fixture('alevel',sourceId);await check();await row('');assert.equal((await snapshot()).attempt.phase,'answering');
  await response();const state=(await snapshot()).attempt.currentResponses.diagram,central=state.atoms.find(a=>a.element===centre);assert.equal(await page.locator(`[data-atom="${central.id}"] .shell`).getAttribute('r'),'100');
  await page.getByRole('button',{name:'Dot electron',exact:true}).click();
  assert.equal(await page.locator(`.atom-region[data-region*='${central.id}']`).getAttribute('r'),'112');
  const coords=await page.evaluate(async()=>{const s=window.__mastersActivity.snapshot(),{getRecord}=await import('/src/activities/alevel/dot-and-cross/provider.ts'),{createLayout}=await import('/src/chemistry/dot-and-cross/layout.js'),record=getRecord(s.question.ref.questionId),layout=createLayout(record.id),state=s.attempt.currentResponses.diagram;return state.electrons.map(e=>({id:e.id,p:layout.point(state,e.anchor)}));});
  for(const e of coords){const hit=page.locator(`[data-electron="${e.id}"] .electron-hit`);assert(Math.abs(Number(await hit.getAttribute('cx'))-e.p.x)<1e-7);assert(Math.abs(Number(await hit.getAttribute('cy'))-e.p.y)<1e-7);}
  await check();await row('Correct');await screenshot(sourceId+'-desktop-correct');const first=(await snapshot()).attempt,history=await page.evaluate(()=>window.__mastersActivity.history());assert.equal(history.length,1);
  await reload();await row('Correct');assert.deepEqual((await snapshot()).attempt.firstResponse,first.firstResponse);
  await page.getByTitle('Hide circles',{exact:true}).click();await flush();await row('');assert.equal(await page.locator('.dot-cross-editor .shell').count(),0);await action('give-up').click();await flush();assert.equal(await page.locator('dialog .shell').count(),0);await row('');await page.getByRole('button',{name:'Close answer',exact:true}).click();
  await page.getByTitle('Show circles',{exact:true}).click();await flush();await response('wrong');await check();await row('Incorrect');await screenshot(sourceId+'-desktop-incorrect');assert((await snapshot()).correctionFeedback.marks.earned<1);
  await page.setViewportSize({width:390,height:844});await row('Incorrect');await screenshot(sourceId+'-mobile-incorrect');
  await response();await row('');await check();await row('Correct');await screenshot(sourceId+'-mobile-correct');await action('give-up').click();await flush();await row('');assert.equal(await page.locator('dialog .shell[r="100"]').count(),1);await screenshot(sourceId+'-mobile-model');await page.getByRole('button',{name:'Close answer',exact:true}).click();
  assert.deepEqual((await snapshot()).attempt.firstResponse,first.firstResponse);assert.deepEqual((await snapshot()).attempt.firstAssessment,first.firstAssessment);assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),history);
  await action('clear').click();await flush();await row('');await check();await row('');assert.equal((await snapshot()).correctionFeedback.status,'incomplete');
  await page.setViewportSize({width:1440,height:1000});await action('next').click();await page.waitForFunction(id=>window.__mastersActivity.snapshot().attempt?.attemptId!==id,first.attemptId);await flush();await row('');assert.notEqual((await snapshot()).attempt.attemptId,first.attemptId);
 });
 await attemptCheck('first-partial-incorrect-correct-retry',async()=>{await fixture('alevel','sulfur-hexafluoride');await response('wrong');await check();await row('Incorrect');const first=(await snapshot()).attempt;assert(first.firstAssessment.marks.earned>0&&first.firstAssessment.marks.earned<1);const history=await page.evaluate(()=>window.__mastersActivity.history());await response();await row('');await check();await row('Correct');await action('give-up').click();await flush();await row('');await page.getByRole('button',{name:'Close answer',exact:true}).click();await check();await row('Correct');assert.deepEqual((await snapshot()).attempt.firstAssessment,first.firstAssessment);assert.deepEqual((await snapshot()).attempt.firstResponse,first.firstResponse);assert.deepEqual(await page.evaluate(()=>window.__mastersActivity.history()),history);});
 for(const [course,id] of [['alevel','h2s'],['alevel','sulfur-tetrafluoride'],['alevel','chlorine-trifluoride'],['igcse','h2o']])await attemptCheck(course+'-'+id,async()=>{await fixture(course,id);await response();assert.equal(await page.locator('.dot-cross-editor .shell[r="100"]').count(),0);await check();await row('Correct');await action('clear').click();await flush();await row('');await action('give-up').click();await flush();await row('');assert.equal((await snapshot()).attempt.firstAssessment.kind,'marked');await page.getByRole('button',{name:'Close answer',exact:true}).click();await reload();await row('');});
 await attemptCheck('fresh-reveal-no-checked-status',async()=>{await fixture('alevel','sulfur-hexafluoride');await action('give-up').click();await flush();await row('');assert.equal((await snapshot()).attempt.firstAssessment.kind,'revealed');assert.equal((await page.evaluate(()=>window.__mastersActivity.history())).length,0);await screenshot('sf6-revealed-model');await page.getByRole('button',{name:'Close answer',exact:true}).click();await reload();await row('');});
}finally{report.status=report.failures.length||report.pageErrors.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results'+(process.argv[2]?'-'+process.argv[2]:'')+'.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify(report));if(report.status!=='PASS')process.exitCode=1;}
