import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const here=import.meta.dirname,project=path.resolve(here,'../..'),read=f=>JSON.parse(fs.readFileSync(path.join(here,f))),sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const full=read('browser-results-attempt5.json'),reveal=read('browser-results-fresh-reveal-no-checked-status.json'),latest=read('browser-results-first-partial-incorrect-correct-retry.json');assert.equal(reveal.status,'PASS');assert.equal(latest.status,'PASS');assert.deepEqual(full.pageErrors,[]);assert.deepEqual(full.failures.map(f=>f.id),['fresh-reveal-no-checked-status']);
const byId=new Map();for(const [report,file] of [[full,'browser-results-attempt5.json'],[reveal,'browser-results-fresh-reveal-no-checked-status.json'],[latest,'browser-results-first-partial-incorrect-correct-retry.json']])for(const check of report.checks)byId.set(check.id,{...check,evidence:file});assert.equal(byId.size,10);
const preservation=read('preservation-after.json');assert.equal(preservation.status,'PASS');assert.equal(preservation.metadataOnly.length,0);
const production=read('production-browser-results.json');assert.equal(production.status,'PASS');const release=read('release-checks.json');assert(release.every(r=>r.status==='PASS'));const testBytes=fs.readFileSync(path.join(here,'tests-final.txt'));assert(testBytes.toString(testBytes[0]===255?'utf16le':'utf8').includes('fail 0'));
const sources=['src/chemistry/dot-and-cross/layout-identity.ts','src/editors/dot-and-cross/DotCrossEditor.tsx','src/ui/DotCrossPlayer.tsx','src/ui/dot-cross-player.css','src/chemistry/dot-and-cross/layout.js','src/chemistry/dot-and-cross/model.ts','src/activities/alevel/dot-and-cross/bank.js','src/activities/alevel/dot-and-cross/marking.ts','src/content/canonical-fixed-ids.json'];
const unchangedExistingUI=['src/editors/dot-and-cross/editor.css','src/ui/SourceQuestionPlayer.tsx'].map(file=>{const before=path.join(here,'before',file);assert.equal(sha(before),sha(path.join(project,file)));return{file,sha256:sha(before),status:'UNCHANGED'};});
const result={job_id:'DOT-SPECIAL-SHELLS-01',agent_id:'A01',status:'PASS',rootAcceptance:'PENDING',checkedAt:new Date().toISOString(),requestedRuntime:{model:'gpt-6.1-sol',effort:'high'},effectiveRuntime:'unexposed',browserChecks:[...byId.values()],productionChecks:production.checks,releaseChecks:release,preservation,unchangedExistingUI,sourceFingerprints:Object.fromEntries(sources.map(f=>[f,sha(path.join(project,f))])),historicalLimitations:['Frozen original-app baseline retains prior drift; actual task before/after preservation passes.','Historical active-time audit missing validation/explaining-properties/current-inputs.json; no historical evidence recreated.','No broad historical missing-wrapper test suite rerun or repairs.'],usage:'unexposed; no invented measurements',retainedFailures:'browser-results-attempt1..5.json retain harness preconditions, subpixel/async assertions and one blank dev-page timeout; all ten required browser cases have PASS evidence.'};fs.writeFileSync(path.join(here,'check.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,browserChecks:byId.size,productionChecks:production.checks.length,preservedFiles:preservation.checkedFiles,rootAcceptance:result.rootAcceptance}));
