import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const project=path.resolve(import.meta.dirname,'../..'), workspace=path.resolve(project,'../..');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const roots=['apps/Masters-of-A-Level-Chemistry','apps/Masters-of-IGCSE-Chemistry','node_modules','apps/Masters-of-Chemistry/node_modules'];
function snapshot(){const files={};function walk(full){for(const e of fs.readdirSync(full,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const f=path.join(full,e.name),key=path.relative(workspace,f).replaceAll('\\','/');if(e.isSymbolicLink())files[key]={symlink:fs.readlinkSync(f)};else if(e.isDirectory())walk(f);else if(e.isFile()){try{files[key]={sha256:hash(fs.readFileSync(f))};}catch(error){const s=fs.statSync(f);files[key]={unavailable:error.code,bytes:s.size,mtimeMs:s.mtimeMs};}}}}for(const root of roots)walk(path.join(workspace,root));for(const f of ['package.json','package-lock.json','apps/Masters-of-Chemistry/package.json','apps/Masters-of-Chemistry/package-lock.json'])files[f]={sha256:hash(fs.readFileSync(path.join(workspace,f)))};return files;}
const beforePath=path.join(import.meta.dirname,'preservation-before.json'), mode=process.argv[2];
if(mode==='before'){assert(!fs.existsSync(beforePath),'Do not replace actual before evidence');const ui={};for(const f of ['src/ui/DotCrossPlayer.tsx','src/ui/dot-cross-player.css','src/editors/dot-and-cross/DotCrossEditor.tsx','src/editors/dot-and-cross/editor.css','src/ui/SourceQuestionPlayer.tsx','src/ui/source-question-player.css']){if(fs.existsSync(path.join(project,f))){const b=fs.readFileSync(path.join(project,f));ui[f]={sha256:hash(b)};const out=path.join(import.meta.dirname,'before',f);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,b);}}const result={capturedAt:new Date().toISOString(),roots,files:snapshot(),existingUI:ui};fs.writeFileSync(beforePath,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({mode,files:Object.keys(result.files).length}));}
else if(mode==='after'){const before=JSON.parse(fs.readFileSync(beforePath)),after=snapshot(),changed=[...new Set([...Object.keys(before.files),...Object.keys(after)])].filter(k=>JSON.stringify(before.files[k])!==JSON.stringify(after[k]));const result={status:changed.length?'FAIL':'PASS',checkedAt:new Date().toISOString(),beforeCapturedAt:before.capturedAt,checkedFiles:Object.keys(after).length,changed,metadataOnly:Object.entries(after).filter(([,v])=>v.unavailable).map(([k])=>k)};fs.writeFileSync(path.join(import.meta.dirname,'preservation-after.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));assert.equal(changed.length,0);}
else throw Error('Use before or after');
