import type { Course } from '../contracts/identity.ts';
import type { Flashcard } from './FlashcardTable.tsx';
// Generated by scripts/prepare_recall.mjs; source and adaptations in provenance.json.
export const starterDecks: Readonly<Record<Course, readonly Flashcard[]>> = {
  alevel: [
    {
      id: 'electron-shell-capacities',
      prompt: [
        {
          kind: 'text',
          text: 'State the maximum number of electrons in the first four principal electron shells.',
        },
      ],
      answer: [{ kind: 'text', text: '2, 8, 18, 32' }],
    },
    {
      id: 'subshell-capacities',
      prompt: [
        { kind: 'text', text: 'State the maximum number of electrons in an s, p and d subshell.' },
      ],
      answer: [{ kind: 'text', text: 's = 2; p = 6; d = 10' }],
    },
    {
      id: 'orbital-filling-rules',
      prompt: [
        {
          kind: 'text',
          text: 'What rules are used to fill orbitals in the ground-state electron configuration of an atom?',
        },
      ],
      answer: [
        {
          kind: 'text',
          text: 'Fill lower-energy orbitals first.\nEach orbital holds a maximum of two electrons with opposite spins.\nOrbitals of equal energy are occupied singly with parallel spins before pairing.',
        },
      ],
    },
    {
      id: 'ionic-lattice-solid',
      prompt: [{ kind: 'text', text: 'What structure do solid ionic compounds have?' }],
      answer: [{ kind: 'text', text: 'Giant ionic lattice' }],
    },
    {
      id: 'coordinate-bond',
      prompt: [{ kind: 'text', text: 'Define the term dative bond' }],
      answer: [
        {
          kind: 'text',
          text: 'A covalent bond in which both electrons in the shared pair are supplied by one atom.',
        },
      ],
    },
    {
      id: 'bond-enthalpy-strength',
      prompt: [{ kind: 'text', text: 'Define the term average bond enthalpy' }],
      answer: [
        {
          kind: 'text',
          text: 'The enthalpy change required to break one mole of a specified type of covalent bond in gaseous molecules, averaged over different compounds.',
        },
      ],
    },
  ],
  igcse: [
    {
      id: 'igcse-recall-012',
      prompt: [
        { kind: 'text', text: 'What is the state symbol for something dissolved in water?' },
      ],
      answer: [{ kind: 'text', text: '(aq)' }],
    },
    {
      id: 'igcse-recall-007',
      prompt: [
        {
          kind: 'text',
          text: 'What is the name for the change of state from a solid to a liquid?',
        },
      ],
      answer: [{ kind: 'text', text: 'melting' }],
    },
    {
      id: 'igcse-recall-009',
      prompt: [
        { kind: 'text', text: 'What is the name for the change of state from a gas to a liquid?' },
      ],
      answer: [{ kind: 'text', text: 'condensation' }],
    },
    {
      id: 'igcse-recall-010',
      prompt: [
        {
          kind: 'text',
          text: 'What is the name for the change of state from a liquid to a solid?',
        },
      ],
      answer: [{ kind: 'text', text: 'freezing' }],
    },
    {
      id: 'igcse-recall-011',
      prompt: [
        { kind: 'text', text: 'What is the name for the change of state from a solid to a gas?' },
      ],
      answer: [{ kind: 'text', text: 'Sublimation' }],
    },
    {
      id: 'igcse-recall-013',
      prompt: [
        { kind: 'text', text: 'What is the name for the liquid in which a solute dissolves?' },
      ],
      answer: [{ kind: 'text', text: 'solvent' }],
    },
  ],
};
