import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const project=path.resolve(import.meta.dirname,'../../../..'),base='validation/component-fidelity/f2/resume/',read=n=>JSON.parse(fs.readFileSync(path.join(project,n),'utf8'));
const audit=read(base+'audit-after.json'),release=read(base+'release-check-final.json'),shared=read(base+'shared-validation.json'),specialists=read(base+'specialist-validation.json'),applicability=read(base+'specialist-applicability.json');for(const r of[audit,release,shared,specialists,applicability])assert.equal(r.status,'PASS');
for(const n of ['runtime-final/production-browser.json','runtime-final/stats-browser.json','final-c3-k.json','timing-continuity.json','preserved-editors.json'])assert.equal(read(base+n).status,'PASS',n);
const files=['shared/resume-f08/completion.json','electron/resume-f09/completion.json','energy/resume-f10/completion.json','titration/resume-f11/completion.json'];const jobs=files.map(n=>{const file='validation/component-fidelity/f2/'+n,m=read(file);assert.equal(m.status,'PASS');return{jobId:m.jobId,agentId:m.agentId,status:'FOREMAN_VALIDATED',manifest:file,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(project,file))).digest('hex')};});
const sourceReview={componentFiles:read(base+'source-changes.json').files.filter(r=>r.owner!=='external-or-unassigned'),patches:['F01-before-current.patch','F03-before-current.patch','F04-before-current.patch','F05-before-current.patch','F06-before-current.patch'].map(n=>base+n),isolatedNumericValidator:base+'validation-component-only.json',isolatedNumericValidatorPatch:base+'validation-component-only.patch',foreignHunkDisposition:'validation.ts includes foreign OLY validators; numeric working change isolated in validation-component-only.patch/json. No foreign source hunk edited by F07. External/unassigned source records retained only to make the combined inputs explicit.',lateSharedApplicability:base+'specialist-applicability.json',review:'F07 reviewed specialist bounded patches, numeric working/strict response validator and metadata-based shared code; actual contacts and C3 mobile model inspected. Worker source-image/chemistry evidence retained. Root source/render acceptance still required.'};
const report={schemaVersion:1,runId:'COMPONENT-FIDELITY-20261003',stage:'F2',status:'VALIDATED_AWAITING_ROOT_ACCEPTANCE',foreman:'F07',replaces:'F01',checkedAt:new Date().toISOString(),jobs,unresolved:[],gates:{F1:'accepted by root',F2:'Implementation plus foreman validation complete; root source/render gate remains',F3:'Not dispatched; forbidden before root F2 acceptance',publication:false},staffing:{requestedModel:'gpt-6.1-sol',requestedEffort:'high',effective:null,usage:null,foremen:1,implementationReplacements:4,independentReviewers:0,nestedDelegation:false},validation:{shared:base+'shared-validation.json',specialists:base+'specialist-validation.json',originals:base+'audit-after.json',sourceInputs:base+'audit-after.json',buildSourceFreeze:base+'build-source-inputs.json',typecheck:base+'typecheck-final.json',build:base+'build-final.json',release:base+'release-check-final.json',tests:{count:68,logs:['regression-initial.log','registration-timing.log','shared-attempt.log','c3-regression-final.log'].map(n=>base+n),identity:'863 fixed refs /5481 acid round-trips; permanent AB template radix192 and maxseed11337407;252 goldens/267 source marking records preserved.'},timing:base+'timing-continuity.json',preservedEditors:base+'preserved-editors.json',currentProduction:base+'runtime-final/production-browser.json',currentStats:base+'runtime-final/stats-browser.json',currentC3:base+'final-c3-k.json'},sourceReview,counts:{sharedRecords:929,curriculumActivities:11,sharedArtifactHashes:shared.artifacts.length,electronVariantRenders:27,energyStatePairs:162,titrationViewportFamilyCases:36,titrationStateStylePairs:216,titrationArtifactHashes:864,originalReadable:794,originalMetadataOnly:523,priorF1Unchanged:324,historicalUnchanged:23971,historicalTotal:23972},releaseBudgets:release.courses,scope:'Component restoration for existing curriculum and preservation of dot-cross/molecule/C3. Concurrent OLY2011 content ignored;13-activity current registry appears only in whole-app build/runtime closure. No original builds, real user storage or publication.',limitations:[
'One historical mutable original-app-check summary was regenerated externally. Expected/current fingerprints and before/after bytes retained; actual originals independently match794 byte hashes and523 metadata-only entries, with zero placeholder content reads. Do not claim the summary byte-unchanged.',
'New browser evidence uses isolated headless Edge with pinned Playwright. CDP frozen did not suspend timers; retain the failed capability probes. Prior exact native clock/binding and60/180/300/600s interval evidence applies under unchanged timing code; no new OS suspension/minimisation claim.',
'Late numeric/comparison/practical/written shared deltas reviewed as unaffected for specialist paths; earlier specialist fingerprints remain historical rather than being relabelled as current.',
'Actual failures and bounded fixture refinements retained. C3 copied historical test initially selected a molecule-editor details section; direct exact reference-section locator passed unchanged assertions after explicit test-only disposition.'
],previews:{vite:5188,static:5192,readOnlyOriginal:5197,execSessions:[79911,50930,54640]},recommendedRootSamples:['shared/resume-f08/contact-mobile-EP-4G1A0S.png','shared/resume-f08/contact-source-written-mobile-EE-6US2V7.png','shared/resume-f08/contact-desktop-SBC-UFFEIZ.png','shared/resume-f08/contact-desktop-CAL-00I9HC.png','electron/resume-f09/context-final/contacts-desktop-energy.png','energy/resume-f10/final/contact-desktop-D03.png','titration/resume-f11/final-accepted/contact-desktop-TC-GMPGTV.png'].map(n=>'validation/component-fidelity/f2/'+n)};
fs.writeFileSync(path.join(project,base+'foreman-report.json'),JSON.stringify(report,null,2)+'\n');
const p=read('component-fidelity-progress.json');p.status='awaiting_root_f2_acceptance';p.stages.F2='validated_awaiting_root_acceptance';p.updatedAt=report.checkedAt;p.unresolved=[];for(const job of p.jobs.filter(j=>j.jobId.startsWith('F2-'))){job.status='foreman_validated';job.validation=job.jobId==='F2-SHARED'?base+'shared-validation.json':base+'specialist-validation.json';}p.evidence=[...new Set([...p.evidence,base+'foreman-report.json'])];fs.writeFileSync(path.join(project,'component-fidelity-progress.json'),JSON.stringify(p,null,2)+'\n');console.log(JSON.stringify({status:report.status,jobs:jobs.length,unresolved:0,report:base+'foreman-report.json'}));
