import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const here=import.meta.dirname,project=path.resolve(here,'../../../..'),require=createRequire(path.resolve(project,'../../package.json'));
assert.equal(require('playwright/package.json').version,'1.62.1');process.env.TEMP=process.env.TMP=path.join(project,'.component-fidelity-tmp');
const browser=await require('playwright').chromium.launch({channel:'msedge',headless:true});const report={status:'PASS',checkedAt:new Date().toISOString(),checks:[],errors:[]};
try{for(const entry of ['alevel','igcse']){
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});await context.addInitScript(()=>{crypto.getRandomValues=array=>{array.fill(3);return array;};});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
 await page.goto(`http://127.0.0.1:5192/${entry}/?course=igcse&view=home`);await page.locator('.original-landing.igcse').waitFor();await page.evaluate(()=>location.hash='lower-10-2');await page.locator('#gemDetails').waitFor({state:'visible'});await page.locator('a.practice-choice[data-practice="2"]').click();await page.locator('.source-practical').waitFor();
 assert.equal(await page.locator('.header-question-code').innerText(),'EP-CXMNAV');assert.equal(await page.locator('.source-practical .question-review-id').count(),0);assert.equal(await page.evaluate(()=>typeof window.__mastersActivity),'undefined');
 await page.getByRole('button',{name:'completely prevents',exact:true}).tap();await page.getByLabel('Replacement phrase',{exact:true}).fill('increases');await page.getByRole('button',{name:'Check answer',exact:true}).tap();await page.getByRole('status',{name:'First assessment',exact:true}).waitFor();assert.equal(await page.locator('.assessment-feedback .score').innerText(),'1/2');
 await page.getByLabel('Replacement phrase',{exact:true}).fill('reduces');await page.getByRole('button',{name:'Check correction',exact:true}).tap();await page.getByRole('status',{name:'Learning correction check',exact:true}).waitFor();assert.equal(await page.locator('.correction-feedback .score').innerText(),'2/2');assert.equal(await page.locator('.assessment-feedback .score').innerText(),'1/2');
 const font=await page.locator('.error-segment').first().evaluate(e=>getComputedStyle(e).fontFamily);assert(font.includes('Playwrite England Joined'));assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.screenshot({path:path.join(here,`production-${entry}-pilot-mobile.png`),fullPage:true});
 await page.waitForTimeout(150);await page.reload();await page.locator('.source-practical').waitFor();assert.equal(await page.locator('.assessment-feedback .score').innerText(),'1/2');report.checks.push({entry,canonicalCode:'EP-CXMNAV',touch:true,first:'1/2',correction:'2/2',firstRestored:true,font,developmentHarnessAbsent:true});await context.close();
}assert.deepEqual(report.errors,[]);}catch(error){report.status='FAIL';report.error={message:error.message,stack:error.stack};process.exitCode=1;}finally{await browser.close();fs.writeFileSync(path.join(here,'production-browser.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));}
