import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const project=path.resolve(import.meta.dirname,'../../../..'),dir=path.join(project,'validation/component-fidelity/f2/shared/resume-f08');
const read=n=>JSON.parse(fs.readFileSync(path.join(dir,n),'utf8')),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const m=read('completion.json');assert.equal(m.jobId,'F2-SHARED');assert.equal(m.agentId,'F08');assert.equal(m.status,'PASS');assert(m.confidence>0&&m.confidence<=1);assert(fs.existsSync(path.join(project,m.output)));
const frozen=read('capture-freeze.json');for(const row of frozen.files)assert.equal(hash(path.join(project,row.file)),row.sha256,row.file);
const suites=[];const images=new Set();
for(const name of m.validation.references){assert(fs.existsSync(path.join(dir,name)),name);if(!name.endsWith('.json')||['capture-freeze.json','hashes-and-diffs.json','contacts.json'].includes(name))continue;const r=read(name);assert.equal(r.status,'PASS',name);for(const f of r.shots??r.screenshots??[])images.add(typeof f==='string'?f:f.path);suites.push({name,checks:r.checks?.length??null,images:(r.shots??r.screenshots??[]).length});}
const coverage=read('coverage.json');assert.equal(coverage.rows.length,11);assert.equal(coverage.rows.reduce((n,r)=>n+r.checked,0),929);assert.equal(coverage.rows.filter(r=>r.family==='preserved-dot-cross').length,2);
const contacts=read('contacts.json').files;assert.equal(contacts.length,55);for(const f of contacts)images.add(f);
const artifacts=[...images].map(file=>{assert.equal(typeof file,'string');const f=path.join(dir,file);assert(fs.existsSync(f),file);const b=fs.readFileSync(f);assert.equal(b.subarray(1,4).toString(),'PNG',file);return{file,bytes:b.length,width:b.readUInt32BE(16),height:b.readUInt32BE(20),sha256:hash(f)};});
const report={status:'PASS',checkedAt:new Date().toISOString(),agent:'F07',jobId:'F2-SHARED',coverage:929,activities:11,contacts:55,suites,freeze:frozen,artifacts,renderedSample:['contact-mobile-EP-4G1A0S.png','contact-source-written-mobile-EE-6US2V7.png','contact-desktop-SBC-UFFEIZ.png','contact-desktop-CAL-00I9HC.png'],inspection:'F07 inspected actual six-state/source contacts, native SVG graph, borderless choice controls, comparison locked evidence layout and numeric working/model rows; F08 retains detailed chemistry/source review.',limitations:'Superseded black graph and pre-instruction captures retained; latest affected suites supersede only their respective earlier renders.'};
fs.writeFileSync(new URL('./shared-validation.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,artifacts:artifacts.length,freeze:frozen.at}));
