import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const here=import.meta.dirname,root=path.resolve(here,'../../..');function read(p){const b=fs.readFileSync(path.join(here,p)),s=b[0]===255&&b[1]===254?b.toString('utf16le'):b.toString('utf8');return JSON.parse(s.replace(/^\uFEFF/,''));}
const current=read('final-input-fingerprints.json'),perf=read('performance.json'),reports=Object.fromEntries(['render-browser.json','a11y-detail.json','release-browser.json','startup-fix-browser.json','final-c3-k.json','generated-browser/browser-results.json','final-keyboard.json','final-dot-invalid-undo.json','typing-browser.json','metadata-proof.json','final-energy-tail.json','final-titration-next.json','cleanup.json'].map(p=>[p,read(p)]));for(const [p,r]of Object.entries(reports))assert.equal(r.status,'PASS',p);assert.equal(current.status,'PASS');assert.equal(perf.status,'PASS');assert.equal(current.freezeEvidence.treeSha256,'35e6c969f6b9f5fefff7577922dd6703b6a645dc2308a460d44d19d3ce790eb1');assert.equal(current.freezeEvidence.inputCount,517);
perf.coordination={reservation:'A01/A21/A06 explicit browser quiet window',performanceUTC:[perf.startedAt,perf.finishedAt],A06BrowserClosedUTC:'2026-10-03T05:32:39.910Z',A21BrowserQuiet:'Direct parent arranged idle pending final profiling closure; notified actual start/end',allOtherA23BrowsersClosed:true,reservationReleased:true,hostBackgroundCPU:'Not instrumented; no physical hardware isolation guarantee.'};perf.limits.push('Known A21/A06 reviewer browsers were explicitly held closed/idle during this final interval. Background host CPU/processes remain uninstrumented.');fs.writeFileSync(path.join(here,'performance.json'),JSON.stringify(perf,null,2));
let handover=fs.readFileSync(path.join(here,'HANDOVER.md'),'utf8');handover=handover.replace(/^Status:.*$/m,'Status: PASS for the assigned S5 independent render/accessibility/release/performance/authoring review. Final current freeze 35e6… passes fresh checks, including the independently diagnosed and separately fixed Next-on-blur defect. Root stage acceptance remains separate.');handover=handover.replace('## Final frozen build review','## First frozen build review (before Next fix)');handover += `
## Final current acceptance evidence — PASS

The sole follow-up runtime change after the first freeze was the separately owned Host Next-save handling. A06 independently reviewed the bounded fix and current dirty/clean/quota/duplicate cases. A23 preserved all earlier passing/failing reports and screenshots under \`before-next-fix/\`, kept all raw exception records, then tested the fresh current build. No authoring output, editor, source bank, provider or marking change occurred in this follow-up.

All **517 frozen inputs** are independently byte-identical before and after this final browser/performance work: tree \`35e6c969f6b9f5fefff7577922dd6703b6a645dc2308a460d44d19d3ce790eb1\`. [final-input-fingerprints.json](final-input-fingerprints.json) records current file hashes, unchanged CLI output/template/generator fingerprints and read-only in-memory inventory validation.

| Final current entry | Manifest SHA-256 | FULL eager JS gzip | Runtime / lazy chunks |
| --- | --- | --- | --- |
| A Level | \`7aaff9bc8e9a60eac7f1934a22fa77e0e0044bafb7f7485eee1e7de17bbe2763\` | 151,587 bytes | 129 / 59 |
| IGCSE | \`d05ff28920b81a9436179ff16eea0d8576a00e3519284f610cee763800adaa28\` | 151,587 bytes | 129 / 59 |

This is **53,213 bytes below the 204,800-byte full eager shell budget**, per entry. Each course retains six enabled activities and six aliases; banks are physically deferred through the shared universal registry as disclosed above. Final fresh checks pass: full render29, focused a11y4, old-link/prefix/direct-refresh23, startup recovery/wording8, C3 K desktop/mobile2 and unchanged generated shared-host7. Screens in \`screens/\` are fresh current-build output; previous-freeze images remain separately preserved. The three-editor raw-draft/semantic-commit/invalid/Undo/restore proof and pure authoring tests carry unchanged editor/generator fingerprints; current fresh Host/Next and shared-host tests supplement them.

[final-energy-tail.json](final-energy-tail.json) now passes the **exact reviewed unchanged v2 assertion tail** against the product fix: D03 peak150 and activation-arrow tail240/head160/x300 typed/committed/restored; required labels and ΔH arrow supplied through actual UI; persisted profile ready; assessed Next; unfinished270 followed by one Next click advances to D11 with a fresh attempt and clean220 coordinates. No old270 draft leaks. The earlier failure causes remain preserved exactly as recorded, and A06's separate event classification supplies the genuine product evidence.

[final-titration-next.json](final-titration-next.json) independently tests the same interaction in the other numeric editor. Actual trusted events show Next enabled at mousedown, blur, mouseup and click while the save status is Saving; one click advances TC01→TC02 and creates a fresh attempt with empty responses. Original first response and first assessment are byte-equivalent; the unfinished11.2 draft does not leak to the fresh input. Both tests use actual UI, current saved repository state and source-faithful durable launch history written only after unloading the old host.

Final current [performance.json](performance.json) measures six cold and six editor observations in the explicitly coordinated quiet browser window **05:35:10.299–05:35:58.392 UTC**. A06 browsers closed by05:32:39.910; A21 was held browser-idle by the foreman until this reservation closed. All other A23 browsers were closed. The actual profiling browser is closed and all three parties were notified of the interval/reservation release. Background host processes were not instrumented; this remains a descriptive small headless CDP series, not a physical device/hardware-isolated benchmark.

| Final current measurement | Three-sample observed range |
| --- | --- |
| A Level cold shell / lazy start | 4,521–4,577 ms / 902–932 ms |
| IGCSE cold shell / lazy start | 4,456–4,569 ms / 1,426–1,440 ms |
| Titration30-step gesture plus two frames / release checkpoint | 560–565 ms / 55–63 ms |
| Real three-character draft plus two frames | 202–214 ms, including imposed40 ms/character delay |
| Enter-to-two-frames / Enter-to-checkpoint | 43–49 ms / 55–59 ms |
| Full real typing through checkpoint | 265–278 ms |

Settings remain4× CPU,150ms latency,200000B/s down,93750B/s up, cache disabled,390×844 DPR1; interaction chart switches to1440×1000. Actual local gesture movement and raw typing create **zero attempt writes before pointer release or Enter**; each meaningful commit saves state. No layout overflow/page errors occurred. The source-owned explicit request trace records actual lazy-load boundaries. No invented benchmarks/timing/storage/scheduler changes were made.

[cleanup.json](cleanup.json) confirms both owned listeners5195/5203 are closed; every owned browser closed in finally, and no other process was stopped. The generated DEV preview emitted existing Vite public-directory path advisories for its source font reference; requests/font rendering succeeded and production prefix/font checks pass. Generated outputs remain untouched. The root receives this assigned review as PASS; full chemistry, inherited cloud/Python/source limits and native timing disposition remain with their separately assigned reviews/root acceptance. No publication occurred.
`;fs.writeFileSync(path.join(here,'HANDOVER.md'),handover);
const completion={agentId:'A23',jobId:'S5-RENDER-ACCESSIBILITY-RELEASE',status:'PASS',outputPaths:['validation/s5/render-release/HANDOVER.md','validation/s5/render-release/final-input-fingerprints.json','validation/s5/render-release/performance.json','validation/s5/render-release/render-browser.json','validation/s5/render-release/final-keyboard.json','validation/s5/render-release/final-energy-tail.json','validation/s5/render-release/final-titration-next.json','validation/s5/render-release/metadata-proof.json','validation/s5/render-release/generated-browser/browser-results.json','validation/s5/render-release/cleanup.json','development/authoring/families/dev-s5-independent/'],confidence:0.97,reason:null,validation:{freezeTree:current.freezeEvidence.treeSha256,frozenInputs:517,render:29,accessibility:4,oldLinks:23,startupAndWording:8,C3K:2,sharedGeneratedHost:7,editorKeyboard:3,dotInvalidUndoRestore:4,energyNextTail:4,titrationTrustedNext:1,CLI:'Generated once; fixed+72 finite seeded trueL1/L2/inverseL3 fixtures and typecheck PASS; output/template/generator integrity PASS',metadata:'Actual generator→derived definitions/scope/revision/persistence and historical-parser distinction PASS',release:{activitiesPerCourse:6,aliasesPerCourse:6,runtimeFilesPerCourse:129,lazyChunksPerCourse:59,fullInitialGzipPerCourse:151587,budget:204800},performance:{coldSamples:6,editorSamples:6,settings:'Headless Edge154/rootPlaywright1.62.1; CDP4×CPU/150ms/200000down/93750up;390pxDPR1;cache disabled',UTC:[perf.startedAt,perf.finishedAt]},cleanup:'Both owned servers and every browser closed',protectedOriginals:'1317 items unchanged;523 metadata-only; no hydration',limitations:['Headless Edge, no CUA/native browser available; not a screen-reader/WCAG certification.','Shared universal physical deferred graph contains both-course banks; no course-exclusive packaging claim.','Small CDP descriptive sample; hardware/background activity uninstrumented.','Native timing and full chemistry/source limitations belong to separate reviews/root acceptance.']},requestedSettings:{model:'gpt-6.1-sol',reasoningEffort:'high'},effectiveSettings:'unknown',usage:null};fs.writeFileSync(path.join(here,'completion.json'),JSON.stringify(completion,null,2));console.log(JSON.stringify({status:completion.status,freeze:completion.validation.freezeTree,output:'validation/s5/render-release/completion.json'}));
