import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {registerHooks} from 'node:module';
const root=path.resolve(import.meta.dirname,'../../..'),sandbox=path.join(import.meta.dirname,'metadata-sandbox');
const gem={id:'dev-approved-new-gem',topicId:'dev-approved-topic',label:'Typed metadata proof',supportedLevels:[1,3],mastery:{gemId:'dev-approved-new-gem',supportedLevels:[{level:1,halfLife:2,label:'Structured'},{level:3,halfLife:2,label:'Application'}],threshold:.8,comparison:'strictly-greater',historicalAliases:[],legacySourceKeys:[],activeProgressionVersion:1}},activity={id:'alevel/dev-approved-new-activity',course:'alevel',strand:'curriculum',title:'Independent metadata projection proof',source:[],gems:[gem]};
const addedGem={...gem,id:'dev-approved-added-gem',topicId:'dev-added-topic',supportedLevels:[2],mastery:{...gem.mastery,gemId:'dev-approved-added-gem',supportedLevels:[{level:2,halfLife:2,label:'Existingactivitynewgem'}]}};
for(const p of ['scripts','src/catalogue','validation/s0/inventory'])fs.mkdirSync(path.join(sandbox,p),{recursive:true});
for(const p of ['scripts/write-catalogue-definitions.mjs','validation/s0/inventory/coverage-manifest.json'])fs.copyFileSync(path.join(root,p),path.join(sandbox,p));
fs.writeFileSync(path.join(sandbox,'src/catalogue/authored-metadata.json'),JSON.stringify({activities:[activity],gems:[{activityId:'alevel/acid-base-calculations',gem:addedGem}]}));
const generated=spawnSync(process.execPath,[path.join(sandbox,'scripts/write-catalogue-definitions.mjs')],{encoding:'utf8'});assert.equal(generated.status,0,generated.stderr);
const content=fs.readFileSync(path.join(sandbox,'src/catalogue/definitions.ts'),'utf8'),defs=JSON.parse(content.match(/export const activityDefinitions = ([\s\S]+) as const satisfies/)[1]);assert.equal(defs.length,13);
// Scoped test loader supplies metadata produced by actual unchanged generator to
// actual unchanged runtime boundary modules. Production files remain untouched.
registerHooks({load(url,context,next){if(url.endsWith('/src/catalogue/definitions.ts'))return {format:'module',source:'export const activityDefinitions='+JSON.stringify(defs),shortCircuit:true};return next(url,context);}});
const [{activityScope},{deriveCatalogueBoundary,leafBoundary},{topicTargets,validCurriculumTarget},{historicalLeaves},{createRegistry}]=await Promise.all([import('../../../src/catalogue/scope.ts'),import('../../../src/persistence/catalogue-boundary.ts'),import('../../../src/domain/session/index.ts'),import('../../../src/catalogue/historical-leaves.ts'),import('../../../src/catalogue/registry.ts')]);
const scope=activityScope.find(a=>a.id===activity.id);assert.deepEqual(scope.supportedLevels,[1,3]);assert.deepEqual(leafBoundary[gem.id],{activityId:activity.id,levels:[1,3]});assert(historicalLeaves.every(h=>leafBoundary[h.id].historicalOnly));
const registry=createRegistry([{id:activity.id,provider:async()=>null,marking:async()=>null,idleAllowance:()=>180000,idleRationale:'synthetic metadata-only proof'}]);const targets=topicTargets(registry.curriculumFor('alevel'),'alevel',gem.topicId);assert.deepEqual(targets.map(t=>t.level),[1,3]);assert(targets.every(validCurriculumTarget));assert.throws(()=>deriveCatalogueBoundary([...defs,activity],historicalLeaves));assert.equal(createRegistry([]).get(activity.id),undefined);assert.deepEqual(leafBoundary[addedGem.id],{activityId:'alevel/acid-base-calculations',levels:[2]});const existingRegistry=createRegistry([{id:'alevel/acid-base-calculations',provider:async()=>null,marking:async()=>null,idleAllowance:()=>180000,idleRationale:'synthetic addedgem metadata proof'}]);const addedTargets=topicTargets(existingRegistry.curriculumFor('alevel'),'alevel',addedGem.topicId);assert.deepEqual(addedTargets.map(t=>t.level),[2]);assert(addedTargets.every(validCurriculumTarget));
const {parseLegacyImport}=await import('../../../src/persistence/legacy.ts');const namespace={course:'alevel',profileId:'local'},legacyBase={id:'A23-known-original',leafId:'u6-t1-1-2',level:1,score:1,completedAt:1720000000000};const knownLegacy=parseLegacyImport({namespace,sourceKey:'masters-alevel-results-v1',rawText:JSON.stringify([legacyBase])});assert.equal(knownLegacy.ok,true);const newIdentityLegacy=[gem.id,addedGem.id].map(leafId=>parseLegacyImport({namespace,sourceKey:'masters-alevel-results-v1',rawText:JSON.stringify([{...legacyBase,leafId}])}));assert(newIdentityLegacy.every(result=>result.ok===false));const parser=fs.readFileSync(path.join(root,'src/persistence/legacy.ts'),'utf8');assert(!parser.includes('authored-metadata'));assert(!parser.includes('dev-approved-new'));assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'src/catalogue/authored-metadata.json'))),{activities:[],gems:[]});
fs.writeFileSync(path.join(import.meta.dirname,'metadata-proof.json'),JSON.stringify({status:'PASS',generatorStdout:generated.stdout,syntheticActivity:activity,addedGem,addedTargets,scope,boundary:leafBoundary[gem.id],revisionTargets:targets,method:'Actual unchanged generator on owned copied tree;scopedNode loader injects its generated metadata intoactual unchanged scope,registry,session andpersistence-boundary modules.',canonicalChain:'authored metadata + frozen migration inventory -> typed definitions -> scope,persistence boundary and registry -> explicit adapter -> revision targets. Metadata alone doesnotenableprovider.',typedBoundary:'For a genuinely new production activity,the explicit ActivityId union also needs the documented approved extension;notclaimedverifiedhere. Generated family onexistinggemtypechecks separately.',legacyParserRuntime:{knownOriginalAccepted:knownLegacy.ok,newAuthoredIdentitiesRejected:newIdentityLegacy.map(result=>result.error)},historicalDistinction:'legacy.ts remainsan original-store parser;retired identities stayhistoricalOnly;no new authored identities added.',productionMutation:false},null,2));console.log('actual metadata generator and derived boundary proof PASS');
