import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
import{bank,reviewCode}from'../../../../../../src/activities/igcse/energy-enthalpy/provider.ts';import{initialProfile,modelProfile}from'../../../../../../src/chemistry/energy-profile/index.ts';
const temporary=path.resolve('apps/Masters-of-Chemistry/.f10-tmp');fs.mkdirSync(temporary,{recursive:true});process.env.TEMP=temporary;process.env.TMP=temporary;
const here=import.meta.dirname,require=createRequire(path.resolve(here,'../../../../../../../../package.json'));assert.equal(require('playwright/package.json').version,'1.62.1');const{chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true});
const report={jobId:'F2-ENERGY',agentId:'F10',startedAt:new Date().toISOString(),status:'RUNNING',browser:'Edge headless / pinned root Playwright 1.62.1',isolation:'Fresh ephemeral browser contexts; original source served readonly. Synthetic source snapshots only in isolated context localStorage.',checks:[],screenshots:[],metrics:[],errors:[],limitations:['No new native OS hide/suspend certification.','The original has no correction/reveal-model flow; its correction/model paired diagrams are original saved-state rendering of the equivalent corrected/checked model, while React uses the shared live correction/reveal engine.']};
const snap=p=>p.evaluate(()=>window.__mastersActivity.snapshot()),flush=p=>p.evaluate(()=>window.__mastersActivity.flush());
async function shoot(p,name,selector){await p.evaluate(()=>document.fonts.ready);const file=name+'.png';if(name.startsWith('original-')&&fs.existsSync(path.join(here,'..',file)))fs.copyFileSync(path.join(here,'..',file),path.join(here,file));else await p.locator(selector).first().screenshot({path:path.join(here,file)});report.screenshots.push(file);}
async function startReact(context,q,mode='practice'){
 const pool=bank.questions.filter(x=>x.grade===q.grade),seed=pool.findIndex(x=>x.id===q.id)||pool.length;
 await context.addInitScript(seed=>{crypto.getRandomValues=array=>{array.fill(seed);return array;};},seed);
 const p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:5188/igcse.html?course=igcse&run=f10-'+mode+'-'+Date.now()+'-'+Math.random());await p.locator('.original-landing').waitFor();
 await p.evaluate(()=>location.hash='lower-10-1');await p.locator('#gemDetails').waitFor({state:'visible'});await p.locator(`a.practice-choice[data-practice="${q.grade}"]`).click();await p.locator('.question-player').waitFor();if(q.editor)await p.locator('.energy-profile-editor').waitFor();await flush(p);assert.equal((await snap(p)).question.ref.questionId,reviewCode(q.id));return p;
}
async function sourceState(context,q,m,state){
 const p=await context.newPage();await p.addInitScript(({q,m,state})=>{localStorage.setItem('sjs-energy-enthalpy-v2-attempt-grade'+q.grade,JSON.stringify({version:1,questionId:q.id,grade:q.grade,answers:[],editor:m,hinted:false,revealed:['incorrect','correct','correction','model'].includes(state),marked:null,attemptId:'synthetic-f10-'+q.id}));},{q,m,state});
 p.on('pageerror',e=>report.errors.push(e.message));await p.goto(`http://127.0.0.1:5197/igcse/activities/energy-enthalpy/index.html?practice=grade&grade=${q.grade}`);await p.locator(q.editor?'#builder .energy-svg':'#diagram .energy-svg').waitFor();
 if(['incorrect','correct','correction','model'].includes(state))await p.evaluate(({q,m})=>{const marked=EnergyCore.check(q,m,EnergyData);const key='sjs-energy-enthalpy-v2-attempt-grade'+q.grade,save=JSON.parse(localStorage.getItem(key));localStorage.setItem(key,JSON.stringify({...save,revealed:true,marked,completedAt:Date.now()}));},{q,m});
 if(['incorrect','correct','correction','model'].includes(state)){await p.reload();await p.locator('#builder .energy-svg').waitFor();}
 return p;
}
async function setProfile(p,m){await p.evaluate(m=>window.__mastersActivity.respond('profile',m),m);await flush(p);}
async function metric(p,selector){return p.locator(selector).evaluate(el=>{const text=el.querySelector('text'),c=getComputedStyle(text),card=getComputedStyle(el);return{width:el.getBoundingClientRect().width,fontFamily:c.fontFamily,fontWeight:c.fontWeight,fontSize:c.fontSize,fill:c.fill,bg:card.backgroundColor,overflow:document.documentElement.scrollWidth>innerWidth};});}
async function gesture(p,action,dx,dy,touch=false){const loc=p.locator('.energy-profile-editor [data-act="'+action+'"]');const box=await loc.boundingBox();assert(box,action);const x=box.x+box.width/2,y=box.y+box.height/2;await loc.scrollIntoViewIfNeeded();const rect=await loc.boundingBox(),px=rect.x+rect.width/2,py=rect.y+rect.height/2;
 if(touch){const cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:px,y:py}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:px+dx,y:py+dy}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await p.mouse.move(px,py);await p.mouse.down();await p.mouse.move(px+dx,py+dy,{steps:5});await p.mouse.up();}await flush(p);}
try{
 const q=bank.questions.find(q=>q.id==='D03'),c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await startReact(c,q);
 for(const level of['r','p','peak']){const before=(await snap(p)).attempt.currentResponses.profile??initialProfile(q);await gesture(p,'level:'+level,0,20);const after=(await snap(p)).attempt.currentResponses.profile;assert(after[level]>before[level]);for(const other of['r','p','peak'].filter(k=>k!==level))assert.equal(after[other],before[other]);}
 const left=p.locator('[data-act="level:r"]');await left.focus();const prior=(await snap(p)).attempt.currentResponses.profile;await p.keyboard.press('ArrowUp');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.profile.r,prior.r-20);assert.equal(await left.evaluate(el=>document.activeElement===el),true);
 for(const [index,level]of[[0,'r'],[1,'p']]){await p.locator('.editor-tray [data-act="label:'+index+'"]').focus();await p.keyboard.press('Enter');await p.locator('[data-act="level:'+level+'"]').focus();await p.keyboard.press('Enter');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.profile[level==='r'?'left':'right'],q.editor.formula[index]);}
 await p.locator('.editor-tray [data-new="ea"]').focus();await p.keyboard.press('Enter');await flush(p);assert((await snap(p)).attempt.currentResponses.profile.arrows.ea);await p.locator('[data-act="head:ea"]').focus();await p.keyboard.press('Enter');await p.locator('[data-act="level:peak"]').focus();await p.keyboard.press('Enter');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.profile.arrows.ea.head.anchor,'peak');
 await setProfile(p,modelProfile(q));const before=(await snap(p)).attempt.currentResponses.profile;await gesture(p,'head:ea',30,-15);const after=(await snap(p)).attempt.currentResponses.profile;assert.notDeepEqual(after.arrows.ea,before.arrows.ea);assert.deepEqual(after.arrows.delta,before.arrows.delta);assert.equal(after.r,before.r);assert.equal(after.p,before.p);assert.equal(after.peak,before.peak);
 await p.locator('.coordinate-alternatives summary').click();const coordinate=p.getByLabel('Peak level screen y',{exact:true}),saved=(await snap(p)).attempt.currentResponses.profile;await coordinate.fill('-');assert.deepEqual((await snap(p)).attempt.currentResponses.profile,saved);await coordinate.press('Enter');await flush(p);assert.deepEqual((await snap(p)).attempt.currentResponses.profile,saved);assert.equal(await coordinate.getAttribute('aria-invalid'),'true');await coordinate.fill('123');await coordinate.press('Escape');assert.equal(await coordinate.inputValue(),String(saved.peak));await coordinate.fill('105');await coordinate.press('Enter');await flush(p);assert.equal((await snap(p)).attempt.currentResponses.profile.peak,105);
 const partial=await snap(p);await p.reload();await p.locator('.energy-profile-editor').waitFor();await flush(p);assert.equal((await snap(p)).attempt.attemptId,partial.attempt.attemptId);assert.deepEqual((await snap(p)).attempt.currentResponses,partial.attempt.currentResponses);
 report.checks.push({kind:'desktop-interaction',independentReactantProductPeak:true,keyboardFocusRetained:true,formulaEnterAttach:true,endpointEnterAttach:true,endpointIndependent:true,invalidCoordinateDraftPreservesProfile:true,escapeCancels:true,explicitCommit:true,restoreExactAttemptRefProfile:true});await c.close();
 const tc=await browser.newContext({viewport:{width:390,height:844},hasTouch:true}),tp=await startReact(tc,q);for(const level of['r','p','peak']){const before=(await snap(tp)).attempt.currentResponses.profile??initialProfile(q);await gesture(tp,'level:'+level,0,18,true);const after=(await snap(tp)).attempt.currentResponses.profile;assert(after[level]>before[level]);for(const other of['r','p','peak'].filter(k=>k!==level))assert.equal(after[other],before[other]);}await setProfile(tp,modelProfile(q));const tb=(await snap(tp)).attempt.currentResponses.profile;await gesture(tp,'tail:delta',-18,12,true);const ta=(await snap(tp)).attempt.currentResponses.profile;assert.notDeepEqual(ta.arrows.delta,tb.arrows.delta);assert.deepEqual(ta.arrows.ea,tb.arrows.ea);report.checks.push({kind:'mobile-touch',trustedCdpTouchGestures:true,independentReactantProductPeak:true,independentArrowEndpoint:true,documentOverflow:await tp.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});await tc.close();
 const variants=['D01','D02','D03','D04','D05','D07','D08','D10','D15'];
 for(const [size,viewport]of Object.entries({desktop:{width:1440,height:1000},tablet:{width:820,height:1180},mobile:{width:390,height:844}}))for(const id of variants){const q=bank.questions.find(q=>q.id===id),rc=await browser.newContext({viewport,hasTouch:size==='mobile'}),oc=await browser.newContext({viewport,hasTouch:size==='mobile'}),r=await startReact(rc,q),initial=initialProfile(q),model=modelProfile(q),partial={...initial,left:model.left},wrong={...model,left:model.right,right:model.left,p:model.p>model.r?155:300,peak:330};
 for(const[state,m]of[['unanswered',initial],['partial',partial],['incorrect',wrong],['correction',model],['model',model]]){
  if(state!=='unanswered')await setProfile(r,m);
  if(state==='incorrect'){await r.getByRole('button',{name:'Check answer',exact:true}).click();await r.locator('.assessment-feedback').waitFor();await flush(r);}
  if(state==='correction'){await r.getByRole('button',{name:'Check correction',exact:true}).click();await r.locator('.correction-feedback').waitFor();await flush(r);assert.equal((await snap(r)).correctionFeedback.marks.earned,q.points.length);}
  if(state==='model'){await r.getByRole('button',{name:'Show worked answer',exact:true}).click();await r.locator('.worked-answer').waitFor();await flush(r);}
  const o=await sourceState(oc,q,m,state);await shoot(r,`react-${size}-${id}-${state}`,'.energy-profile-editor');await shoot(r,`react-${size}-${id}-${state}-diagram`,'.energy-profile-editor .edit-canvas');await shoot(o,`original-${size}-${id}-${state}`,'#builder');await shoot(o,`original-${size}-${id}-${state}-diagram`,'#builder .edit-canvas');if(true){await shoot(r,`react-${size}-${id}-${state}-full`,'.question-player');await shoot(o,`original-${size}-${id}-${state}-full`,'.workspace');}
  if(state==='unanswered'){assert((await r.locator('.question-player').innerText()).includes(q.prompt),id+' original prompt retained');const box=await r.locator('.edit-canvas').first().boundingBox(),parent=await r.locator('.energy-profile-editor').first().boundingBox();if(size==='desktop')assert(Math.abs(box.x+box.width/2-parent.x-parent.width/2)<2,id+' source canvas centered');const rm=await metric(r,'.edit-canvas'),om=await metric(o,'.edit-canvas');report.metrics.push({size,id,react:rm,original:om});for(const prop of['fontFamily','fontWeight','fontSize','fill','bg'])assert.equal(rm[prop],om[prop],size+' '+id+' '+prop);assert.equal(rm.overflow,false);}
  await o.close();
 }
 const first=(await snap(r)).attempt.firstAssessment,frozen=(await snap(r)).attempt.firstResponse,history=await r.evaluate(()=>window.__mastersActivity.history());assert.equal(history.length,1);assert.equal(first.marks.earned<first.marks.available,true);assert.equal(frozen.timing.idleLimitMs,180000);assert(frozen.timing.activeMs>0);
 await r.reload();await r.locator('.worked-answer').waitFor();await flush(r);assert.deepEqual((await snap(r)).attempt.firstAssessment,first);assert.deepEqual((await snap(r)).attempt.firstResponse,frozen);assert.equal((await r.evaluate(()=>window.__mastersActivity.history())).length,1);
 const correctContext=await browser.newContext({viewport,hasTouch:size==='mobile'}),cr=await startReact(correctContext,q);await setProfile(cr,model);await cr.getByRole('button',{name:'Check answer',exact:true}).click();await cr.locator('.assessment-feedback').waitFor();await flush(cr);assert.equal((await snap(cr)).attempt.firstAssessment.marks.earned,q.points.length);const co=await sourceState(oc,q,model,'correct');await shoot(cr,`react-${size}-${id}-correct`,'.energy-profile-editor');await shoot(cr,`react-${size}-${id}-correct-diagram`,'.energy-profile-editor .edit-canvas');await shoot(co,`original-${size}-${id}-correct`,'#builder');await shoot(co,`original-${size}-${id}-correct-diagram`,'#builder .edit-canvas');if(true){await shoot(cr,`react-${size}-${id}-correct-full`,'.question-player');await shoot(co,`original-${size}-${id}-correct-full`,'.workspace');}await co.close();
 report.checks.push({kind:'equivalent-states',size,id,canonical:reviewCode(id),variant:q.editor.type,polarity:q.polarity??null,states:['unanswered','partial','incorrect','correct','correction','model'],computedDiagramSourceFontsColours:true,exactRestore:true,firstScoreTimingFixed:true,oneEvidenceRow:true,correctionFullMarks:true});await correctContext.close();await rc.close();await oc.close();
 }
 const teacherContext=await browser.newContext({viewport:{width:1440,height:1000}}),teacher=await teacherContext.newPage();const tq=bank.questions.find(q=>q.id==='D15');await teacher.goto(`http://127.0.0.1:5188/igcse.html?course=igcse&run=f10-teacher&view=teacher&activity=igcse%2Fenergy-enthalpy&review=${reviewCode(tq.id)}&level=2&seed=14`);await teacher.locator('.teacher-answer').waitFor();await flush(teacher);assert.equal((await snap(teacher)).attempt,null);assert.equal((await teacher.evaluate(()=>window.__mastersActivity.history())).length,0);assert.equal(await teacher.locator('.energy-profile-editor [data-act]').count(),0);await shoot(teacher,'react-desktop-teacher-model','.question-player');await teacher.reload();await teacher.locator('.teacher-answer').waitFor();assert.equal(await teacher.locator('.header-question-code').innerText(),reviewCode(tq.id));report.checks.push({kind:'teacher',sameCanonicalProfileRef:true,noAttemptNoEvidence:true,lockedHandles:true});await teacherContext.close();
 report.sourceCaptures='Earlier identical-source captures reused for full/editor views; diagram crops and all current views rendered after freeze';report.status='PASS';
}catch(error){report.status='FAIL';report.errors.push(error.stack??String(error));console.error(error);}finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'browser-results.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,screenshots:report.screenshots.length,errors:report.errors}));if(report.status!=='PASS')process.exitCode=1;}
