import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import assert from'node:assert/strict';
const here=import.meta.dirname,sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(path.join(here,p))),before=read('fingerprints-before.json'),after=read('fingerprints-after.json'),mobile=read('mobile-results.json'),perf=read('performance.json');
assert.equal(before.status,'PASS');assert.equal(after.status,'PASS');assert.deepEqual(before.freeze,after.freeze);assert.equal(after.freeze.treeSha256,'fa9b70c77954462612fb26a8d125d255f0af3456efff569d53a8ae3fa3dd3c52');assert.equal(after.freeze.inputCount,517);assert.equal(mobile.status,'PASS');assert.equal(mobile.checks.length,6);assert.deepEqual(mobile.failures,[]);assert.deepEqual(mobile.pageErrors,[]);assert.equal(perf.status,'PASS');assert.equal(perf.freeze,after.freeze.treeSha256);assert.equal(perf.shell.length,2);assert.equal(perf.editors.length,2);assert.deepEqual(perf.errors,[]);
assert.equal(sha(fs.readFileSync(path.join(here,'mobile-live-region-proposal.mjs'))),'d0190eb5b0c044eebd8bc45ae0d22e31e771dd74a0a016233e3bd2bc320f9581');assert.equal(sha(fs.readFileSync(path.join(here,'fixtures.mjs'))),'598bc7383f6f1e9b2730ec2779a6a471b281bffdd0163080fc43c68b30d63da1');
const screens=mobile.checks.flatMap(c=>c.captures.map(x=>({path:'screens/'+x.name+'.png',ariaPath:x.name+'-aria.txt',overflow:x.overflow})));assert.equal(screens.length,16);for(const s of screens){assert.equal(s.overflow.width,390);assert(s.overflow.scroll<=390);s.sha256=sha(fs.readFileSync(path.join(here,s.path)));s.ariaSha256=sha(fs.readFileSync(path.join(here,s.ariaPath)));}
const metrics=perf.shell.map(s=>{const e=perf.editors.find(e=>e.course===s.course);assert.equal(e.duringAttemptPutCount,e.beforeAttemptPutCount);assert.equal(e.writes.length,1);assert.equal(e.checkpointMatchesDurable,true);return{course:s.course,coldShellReadyMs:s.shellReadyMs,localGestureAndTwoFramesMs:e.localGestureAndTwoFramesMs,pointerupToSavedCheckpointMs:e.pointerupToSavedCheckpointMs}});
const carried=['HANDOVER.md','completion.json','render-browser.json','a11y-detail.json','release-browser.json','startup-fix-browser.json','final-c3-k.json','final-keyboard.json','final-dot-invalid-undo.json','typing-browser.json','final-energy-tail.json','final-titration-next.json','performance.json','generated-integrity.json','generated-browser/browser-results.json','metadata-proof.json','protected-originals-check.json'].map(p=>({path:'validation/s5/render-release/'+p,sha256:sha(fs.readFileSync(path.join(here,'..',p))),fresh:false}));
const visual={status:'PASS',agentId:'A23',inspectedAt:new Date().toISOString(),surface:mobile.surface,screens,manualFindings:['Visually inspected all16 current full-page mobile captures: terminal failure/recovered and both empty-session kinds paused/failure/recovered in both courses.','Natural vertical scrolling exposes full setup and footer; all pages390px wide without horizontal overflow, clipped messages or overlapping controls.','Quota message wraps within bounded panel; Retry remains labelled and real Tab produces visible yellow focus outline.','Failure keeps Revision in progress or Revision paused; successful terminal Retry displays Saved on this device and Revision complete.','Successful no-attempt Resume removes paused/error panels, returns setup, retains honest0 saved results/time0, and creates no question/results.','Terminal question preserves first assessment; focusing answering keeps navigation/sidebar/setup hidden until Change activity or view.','Accessible semantics verified through fresh aria snapshots plus actual aria-live polite terminal region / role alert paused region and role status paused notice. Native screen-reader speech not measured.'],priorStyleCarry:'Comfortaa brand, systemUI body, glyph/contrast/detail checks carried from source-identical CSS/font/editor files; current licensed assets validated against source.'};fs.writeFileSync(path.join(here,'visual-inspection.json'),JSON.stringify(visual,null,2));
const verification={status:'PASS',agentId:'A23',jobId:'S5-RENDER-ACCESSIBILITY-RELEASE',checkedAt:new Date().toISOString(),freeze:after.freeze.treeSha256,inputCount:517,prePostStable:true,sourceChanges:after.sourceChanges,releases:after.releases.map(r=>r.validation),mobile:{count:6,startedAt:mobile.startedAt,finishedAt:mobile.finishedAt,liveRegions:'terminal polite; paused role alert',TabFocusVisible:true,EnterRetry:true,durableCompletionOnlyAfterSuccess:true,noAttemptRowsFabricated:true,reloadExact:true,screenshotCount:16},performance:{startedAt:perf.startedAt,finishedAt:perf.finishedAt,settings:perf.settings,metrics,limitations:perf.limits,coordination:'A01 approved window. A21 confirmed browser/server closed since06:37:00.530Z and explicitly idle. A06 was notified before and after. No browser overlap reported; host background CPU unmeasured.'},carry:carried,carryRule:'Only ActivityHost source changed from prior35e6 frozen full review; full earlier profile is descriptive prior-build evidence, not a measurement of this rebuilt Host. New six branches and two checkpoint samples exercise current shared queue; thorough lifecycle/concurrency belongs to A21/A06/root integration.',rawFailures:['c1-probe/','fa9-initial-probe/','fa9-live-region-assumption/'],approvedFixtureHashes:{mobile:'d0190eb5b0c044eebd8bc45ae0d22e31e771dd74a0a016233e3bd2bc320f9581',fixtures:'598bc7383f6f1e9b2730ec2779a6a471b281bffdd0163080fc43c68b30d63da1'},cleanup:'All own static5203/browser contexts closed in finally;5195 not opened in this follow-up; no foreign processes stopped.'};fs.writeFileSync(path.join(here,'verification.json'),JSON.stringify(verification,null,2));
const handover=`# A23 S5 reopened render/accessibility/release follow-up — PASS

Current freeze **${after.freeze.treeSha256}**,517 inputs byte-identical before/after browser work. Host SHA **${after.sourceChanges[0].after}** is the sole changed source versus prior full review35e6. No product/source/build/release edits; writes confined to this evidence folder.

## Fresh current checks

Six390×844 DPR1 headless Edge154.0.4258.48 mobile cases PASS: each course terminal revision completion failure/Retry, paused empty revision Resume, and paused empty practice Resume. Real sessions.put QuotaExceededError leaves durable rows unchanged and does not falsely display completion. Actual Tab reaches focus-visible Retry; Enter saves the exact pending transition. Attempts/evidence stay immutable; empty Resume creates no fabricated rows/question; reload agrees with durable state. All16 fresh captures were manually viewed; accessible snapshots accompany each. Terminal uses the actual polite live region, paused branches use role alert; this establishes DOM/AX semantics, not native screen-reader speech.

[Mobile results](mobile-results.json), [visual inspection and screenshot hashes](visual-inspection.json), [verification](verification.json).

## Current release

Read-only releaseInventory regeneration in memory and validateRelease pass both releases:6 enabled activities,6 relative aliases,129 runtime files,59 lazy JS chunks each. Full eager shell gzip is **151857 bytes A Level /151856 IGCSE**, within204800. Manifests **9f58cdd660546f6526010d7a546aee051cd1bb0ec5d6ab7ae3cfac684d165fd0** and **b44d8cbcfd271890d82b9984a80a83b1527d0becd1ab728a29a0776504f8d17a**. Licensed brand assets match source. No DEV/test/source/package/iframe/Rocket runtime; explicit Rocket compatibility rejection text is retained. Shared universal registry physically defers banks from both courses; enabled course scope is separate. Previous direct refresh/coded/codeless/nested old-link browser checks carry because compatibility routes/aliases are byte-identical.

[Before fingerprints](fingerprints-before.json), [after fingerprints](fingerprints-after.json), with full517 current hashes and in-memory inventories.

## Bounded current measurements

Quiet browser interval **${perf.startedAt}–${perf.finishedAt}**, all own browsers/server then closed. Root pinned Playwright1.62.1, headless Edge, CDP4×CPU,150ms latency,200000B/s down,93750B/s up,cache disabled. Cold shell390×844; actual editor1440×1000. One observation per course:

|Course|Cold shell ready (ms)|30-step gesture +2 frames (ms)|Pointer-up to saved checkpoint (ms)|
|---|---:|---:|---:|
${metrics.map(x=>`|${x.course}|${x.coldShellReadyMs.toFixed(1)}|${x.localGestureAndTwoFramesMs.toFixed(1)}|${x.pointerupToSavedCheckpointMs.toFixed(1)}|`).join('\n')}

A Level titration and IGCSE energy each render movement locally with zero attempts.put calls until pointer-up, then exactly one semantic checkpoint, visible Saved status and exact durable responses. These are bounded descriptive observations including automation/transport overhead, not a device benchmark or timing distribution. Hardware/background CPU unmeasured; no physical mobile/native claim. A21 confirmed idle; A06 notified; no reported overlapping browser work.

[Raw measurements/settings/requests](performance.json).

## Explicit prior evidence carry

[Prior full handover](../HANDOVER.md) and [prior completion](../completion.json) remain unchanged. Chemistry/content/editors/C3/metadata/generator/templates/public assets are byte-identical. Prior full desktop/mobile rendering, orbital/energy/titration/dot/molecule teacher models, typing/Undo/reload/Next, glyph/font/contrast/focus/touch/non-drag, all navigation and old links, genuine CLI generation/fixed+72 seeded tests/DEV shared Host fixture, authored metadata→definitions→scope/persistence and historical-parser boundary remain applicable within those unchanged scopes. Generated outputs/templates/scaffold fingerprints freshly verified. **Prior full performance.json is tied to35e6 and05:35:10.299–05:35:58.392Z, not this rebuilt code**; use the bounded current observations above for the changed queue. Thorough new session/concurrency lifecycle is separately A21/A06/root owned.

## Preserved failure dispositions

c1-probe retains Node browserClockSample document failures before terminal installation; supported ClockSample hooks apply only to synthetic history. fa9-initial-probe retains invalid native evidence row-key fixture failure before Host; exact canonical id fix approved. fa9-live-region-assumption retains actual terminal failure screenshots/body with visible error/Retry but missing guessed role alert; A06 independently reviewed exact source-faithful polite-region continuation. The async Promise readiness candidate was never accepted/executed; final polling awaits real database reads with the original30000ms deadline. No original FAIL relabelled. Final approved executable SHA d0190eb5… and canonical fixture SHA598bc738… retained.

Reproduce final mobile: node validation/s5/render-release/session-only-save-fix/mobile-live-region-proposal.mjs. Profiling requires quiet-window coordination: node validation/s5/render-release/session-only-save-fix/performance.mjs. Fingerprints are read-only via fingerprints.mjs before|after. All browsers/server finally close;5195 unused.

Requested settings gpt-6.1-sol/high; effective unknown; actual usage null.
`;fs.writeFileSync(path.join(here,'HANDOVER.md'),handover);
const completion={agentId:'A23',jobId:'S5-RENDER-ACCESSIBILITY-RELEASE',status:'PASS',outputPaths:['validation/s5/render-release/session-only-save-fix/HANDOVER.md','validation/s5/render-release/session-only-save-fix/verification.json','validation/s5/render-release/session-only-save-fix/mobile-results.json','validation/s5/render-release/session-only-save-fix/performance.json','validation/s5/render-release/session-only-save-fix/fingerprints-after.json','validation/s5/render-release/completion.json'],confidence:0.96,reason:null,validation:{freeze:after.freeze.treeSha256,inputs:517,prePostStable:true,freshMobileCases:6,currentColdSamples:2,currentSemanticCheckpointSamples:2,currentRelease:'PASS6activities6aliases129runtime59lazy',priorFullReview:'Carried explicitly from35e6 for unchanged source only',evidence:'validation/s5/render-release/session-only-save-fix/verification.json'},requestedSettings:{model:'gpt-6.1-sol',reasoningEffort:'high'},effectiveSettings:'unknown',usage:null};fs.writeFileSync(path.join(here,'completion.json'),JSON.stringify(completion,null,2));console.log(JSON.stringify({status:'PASS',metrics,completion}));
